### PR TITLE
Port some refactor from teeworlds-0.7

### PR DESCRIPTION
**Pull request by Kaffeine**
Hi, devs.

I'm considering options to rebase another mod on the DDNet code and I found a lot of missing API.
I also think that it would be simpler for you to cherry-pick patches if DDNet will provide and use a similar API.

I ran the client and checked that the configuration save/load works correctly.

Backported changes overview:
- Extract some `CGameContext` code to methods (`SendMotd()`, `SendSettings()`)
- Provide getters for CEntity members and make some of them `private`
- Extract allocation macros from `entity.h` to `alloc.h` (to reduce includes)
- Extract / introduce `CConsole::Init()`
- Introduce CConfig API from commit https://github.com/teeworlds/teeworlds/commit/de5859b3717406f9f0e728506ad0ef15d4e87337 (the old API is kept and still used in the codebase)

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Kaffeine** [comment]
Please let me know if I can and should do anything about the clang-tidy warnings. The code in `alloc.h` is identical to that from `entity.h`.

**Comment by heinrich5991** [comment]
Thanks for taking your time to do this. It looks good to me in general.

The clang-tidy warning should be fixed or silenced, it seems we silenced it before: https://github.com/ddnet/ddnet/commit/7a9a67c5d77bad671759431ec7e0becb9cec222e#diff-efeaabc2aacb2a014cf32ea48d7a7184de0ed87731bc7ca71335bd73d7215fa8R29. Is that silencing correct, @def-?

**Comment by Kaffeine** [comment]
> Thanks for taking your time to do this. It looks good to me in general.
> 
> The clang-tidy warning should be fixed or silenced, it seems we silenced it before: [7a9a67c#diff-efeaabc2aacb2a014cf32ea48d7a7184de0ed87731bc7ca71335bd73d7215fa8R29](https://github.com/ddnet/ddnet/commit/7a9a67c5d77bad671759431ec7e0becb9cec222e#diff-efeaabc2aacb2a014cf32ea48d7a7184de0ed87731bc7ca71335bd73d7215fa8R29). Is that silencing correct, @def-?

Oh, indeed. I lost those `NOLINT` changes.

**Comment by heinrich5991** [comment]
bors r+

Thanks a lot. :)

**Comment by Kaffeine** [comment]
> bors r+

I reviewed my own changes and noticed that `EscapeParam` can be removed in favor of `str_escape` (it was done in DDNet). :disappointed: 
Sorry about that. As the `bors` is still pending, maybe I should do that change?

**Comment by heinrich5991** [comment]
@Kaffeine Just make a new PR, no worries. :)

**Pull request merged**
