### PR TITLE
Store saves client-side in ddnet-saves.txt

### PR DESCRIPTION
**Pull request by def-**
Only appends saves, just in case you forgot where you saved.

Unfortunately only stores your own name, not your entire team.

### CODE REVIEW

**Comment by fokkonaut** [comment]
This can be abused by modded servers to spam that log file

**Comment by def-** [comment]
Yes.

**Comment by heinrich5991** [comment]
It would be better if this could be called by the chat code so that it doesn't trigger on messages that aren't displayed to the user.

**Comment by def-** [comment]
Done.

**Comment by def-** [comment]
Superseded by https://github.com/ddnet/ddnet/pull/2322

**Pull request closed without merging**
