### PR TITLE
Expose IStorage::GetPath()

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Please use the description to provide a motivation for you pull request, as requested by the template. This is also a good habit for commit messages.

**Comment by ChillerDragon** [comment]
In my fork I want to create folders in the TYPE_SAVE directory. And it seems like there is no way doing that without modifying storage.cpp

**Comment by Robyt3** [comment]
We also have `IStorage::GetCompletePath` which just delegate to `GetPath` with additional validation.

**Comment by ChillerDragon** [comment]
Oh wow I am blind, I actually looked for that but did not find it. Thanks guys :)

**Pull request closed without merging**
