### PR TITLE
Fix client crash when echoing client message to chat, use em dash for client messages in chat like on upstream

### PR DESCRIPTION
**Pull request by Robyt3**
client-message

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I think I prefer echo over say_self. Rest seems fine. Other opinions?

**Comment by Robyt3** [comment]
I removed the `echo` -> `say_self` change.

**Comment by Robyt3** [comment]
Also using the em dash in the appearance settings now, which I previously forgot.

**Pull request merged**
