### PR TITLE
Always show IPs, most moderators don't stream

### PR DESCRIPTION
**Pull request by heinrich5991**
CC #3827

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
@fokkonaut mentioned that this feature could also be used to restrict people from viewing IP addresses.

In that respect, #3827 and #3828 are the same, they stop that feature from working.

**Comment by heinrich5991** [comment]
Status: I don't really care either way, need a decision.

@fokkonaut would like to keep this feature.

If you already bind your rcon password, you can also bind `show_ips 1` onto the same key.

Opinions? @Learath2 @def-

**Comment by Learath2** [comment]
Mh, I like that we have the ability to do this, I'm not particularly fond of the implementation but I guess it's better if it stays.

**Comment by heinrich5991** [comment]
Sounds good.

**Pull request closed without merging**
