### PR TITLE
Add back skins by Moby Dog

### PR DESCRIPTION
**Pull request by heinrich5991**
CC #2518

### CODE REVIEW

**Comment by heinrich5991** [comment]
That's missing the following skins:

- bauer (pparently only reworked by Moby Dog)
- Red Coke
- Straw Crytek

**Comment by def-** [comment]
Nice!
bors r+

**Comment by def-** [comment]
@heinrich5991 Shouldn't we count bauer as a new skin since it was reworked?

**Comment by heinrich5991** [comment]
Moby Dog said he was unwilling to license it since it's not his work.

**Pull request merged**
