### PR TITLE
Use golden angle to generate unique, distinct DDTeam colors

### PR DESCRIPTION
**Pull request by Robyt3**
The DDTeam colors were previously generated in HSL by taking the team index and multiplying it by 360/64° to calculate the hue, which results in team colors being evenly distributed over the entire color range like a rainbow. However, this causes colors of adjacent teams to be very similar and therefore hard to distinguish.

Now, the hue is calculated by multiplying the team index with the golden angle (~137.50776°) and taking the modulo 360° of that. Due to the properties of the golden angle, this can generate never repeating sequences of unique colors where the adjacent colors are very distinct.

Duplicate code is reduced by adding the `CGameClient::GetDDTeamColor` function.

Screenshots:
- Before: 
screenshot_2023-09-04_17-41-52
- After: 
screenshot_2023-09-04_17-41-36
- Comparison: 
comparison1
- Comparison (all in one row): 
comparison2
- Comparison (sorted by color, showing that a full rainbow of colors is still available, just in a different order): 
comparison3

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [X] Tested in combination with possibly related configuration options (`cl_chat_teamcolors` and `cl_nameplates_teamcolors`)
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
Heavily against this and not helpful for my colorblindness at all either.
Also not happy about this because it makes it impossible to use my rainbowname feature.
I personally like the color pattern of the teams.

**Review by def- — APPROVED** [review]
Ok from my side, but some players will complain.

**Comment by heinrich5991** [comment]
> not helpful for my colorblindness at all either.

How does this relate to colorblindness? It mostly seems to be about switching colors around.

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Comment by ChillerDragon** [comment]
Why are there kills with weapons in the kill feed in your screenshots? How does that happen?

**Comment by Robyt3** [comment]
> Why are there kills with weapons in the kill feed in your screenshots? How does that happen?

It's a test server that sends random kill messages for all clients, to test kill message related functions.

**Comment by ChillerDragon** [comment]
> > Why are there kills with weapons in the kill feed in your screenshots? How does that happen?
> 
> 
> 
> It's a test server that sends random kill messages for all clients, to test kill message related functions.

Cool stuff

**Pull request merged**
