### PR TITLE
Add japanese compressed font

### PR DESCRIPTION
**Pull request by TsFreddie**
This is a 57kb hiragana/katakana font sits between deja vu sans and source han sans. GlowSansJCompressed is a fork of Source Han Sans so the style and license are the same: https://github.com/welai/glow-sans/blob/master/docs/README-en.md

Was torn between condensed (thiner) font and compressed (thinnest) font, but I figure since we want to fit them better, might as well make more text fit rather than less:

image

The font weight is "book" because glow sans has 9 font weights instead of matching source han sans's 7. so the weight name was shifted.

_Japanese translation will come later._

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Seems fine to me. Is it ok not to have it in 15.5?

**Comment by TsFreddie** [comment]
> Seems fine to me. Is it ok not to have it in 15.5?

Yes.

There is also some additional context info requested by my tri-lingo friend for japanese, like `players [browser]` as in "player counts" and `players [ingame]` as in "list of players". and maybe `No [serverinfo]` as in "absence" and `No [dialog]` as in "negative". i'll compile those too for the next version, when he was done with the current translation.

**Comment by def-** [comment]
Sure, see also https://github.com/ddnet/ddnet/issues/3868 for context info

**Pull request merged**
