### PR TITLE
Add GLES support

### LINKED ISSUE #2885: [regression] Segmentation fault with SDL_VIDEODRIVER=wayland
Starting DDNet with `SDL_VIDEODRIVER=wayland ./DDNet` worked perfectly fine until a07e9ac2cf5f4a1856a58749caf9f5afc85022d2. I've used `git bisect` to find this exact commit.

```
[2020-09-20 12:23:52][binds]: ...
[2020-09-20 12:23:52][client]: starting...
[2020-09-20 12:23:52][sdl]: SDL version 2.0.12 (compiled = 2.0.12)
[2020-09-20 12:23:52][gfx]: out of ideas. failed to init graphics
[2020-09-20 12:23:52][client]: couldn't init graphics
[Thread 0x7ffff5fcb700 (LWP 29774) exited]
[Thread 0x7ffff67cc700 (LWP 29773) exited]

Thread 1 "DDNet" received signal SIGSEGV, Segmentation fault.
0x00007ffff74a8f0c in malloc_consolidate () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
(gdb) bt
#0  0x00007ffff74a8f0c in malloc_consolidate () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#1  0x00007ffff74aa4e0 in _int_free () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#2  0x00005555556798cc in CHeap::~CHeap() ()
#3  0x00007ffff74604f3 in __run_exit_handlers () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#4  0x00007ffff74606ae in exit () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#5  0x00007ffff744903a in __libc_start_main () from /usr/x86_64-pc-linux-gnu/lib/libc.so.6
#6  0x000055555560763e in _start ()
```

### PR DESCRIPTION
**Pull request by Jupeyy**
I know i *****ed up, that i didnt move the files in a different commit, but when i noticed it was already too late.
Its mostly disabling stuff that GLES doesn't support. Global LOD bias or glOrtho for examlpe.

~***Strong note***:
This will move ALL linux implementation to GLES instead of GL, since GLES is supported by X11 and wayland, we probably want some testing for this.
This also means, that the default for Linux gets GLES 3.0 which is equivalent to OpenGL 3.3, not OpenGL 3.0!!!~

~If you wonder "why":
Gles just works differently to OGL, it knows about all functions that exists, and e.g. doesn't require GLEW at all, but that also means, that GLES does NOT work while we use OGL, because GLEW would kill GLES.~
GLEW in EGL mode works fine with wayland, just requires X11 to use EGL too(SDL_VIDEO_X11_FORCE_EGL)

_Additionally, for GLES only, only 3.0 and 1.0 context are supported._(doesn't matter anymore for linux)

probably fixes:
~not_really_fixes  #3797~
fixes #2885

And would also allow android support, if i ever get these build scripts upto date, or smby is interested into fixing them for me :D

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
dunno about ubuntu 16, seems like there is a packet mismatch

**Comment by def-** [comment]
```
In file included from src/engine/client/graphics_threaded.cpp:30:
src/engine/client/video.h:9:10: fatal error: GLES/gl.h: No such file or directory
    9 | #include <GLES/gl.h>
      |          ^~~~~~~~~~~
compilation terminated.
```
Shouldn't this be detected at cmake level already?

**Comment by Jupeyy** [comment]
I think we dont detect GL libs at cmake, we just assume them in the path

**Comment by def-** [comment]
How to test this? I'm not sure how to get GLES installed. Do we have to ship it too? Will this break compatibility for old hardware?

**Comment by Jupeyy** [comment]
> How to test this? I'm not sure how to get GLES installed. Do we have to ship it too? Will this break compatibility for old hardware?

Thats the question.. mesa should come with GLES and GL, so it doesnt need any more requirements
You can test it by just starting the client, if it works, then it alraedy uses GLES.
I assume atleast newer NVIDIA drivers also have GLES support

**Comment by def-** [comment]
But I can't build it. I have mesa installed.

**Comment by Jupeyy** [comment]
Dunno, maybe ur package provider forgot to include GLES1?

The files defenitely exists, else the ubuntu latest ci would also fail
https://gitlab.freedesktop.org/mesa/mesa/-/tree/master/include/GLES

**Comment by Jupeyy** [comment]
Well too bad then, this would have been the only way to not ship 2 executables and still be compatible with wayland and x11, without any hacks.

But this doesnt invalidate the PR.
You literally only have to undef #define CONF_BACKEND_OPENGL_ES 1 in detect.h again and it should work with normal OpenGL again

**Comment by def-** [comment]
There is only GLES2 and GLES3 in /usr/include/ on Arch Linux, no GLES.

**Comment by Jupeyy** [comment]
Yeah seems like they dropped support for it. Even tho I can't find any explanation why they did it. But I honestly doubt we are ready for gles3 only yet and gles2 is very different to opengl2

**Comment by Jupeyy** [comment]
If somebody wants to test GLES3 only ^

I'll remove the detect stuff else, I cant find any solution for wayland only, that isnt compile time only

**Comment by def-** [comment]
```
In file included from src/engine/client/backend_sdl.cpp:35:
src/engine/client/video.h:1: error: unterminated #ifndef
    1 | #ifndef ENGINE_CLIENT_VIDEO_H
      | 
src/engine/client/backend_sdl.cpp: In static member function ‘static void CGraphicsBackend_Threaded::ThreadFunc(void*)’:
src/engine/client/backend_sdl.cpp:92:6: error: ‘IVideo’ has not been declared
   92 |   if(IVideo::Current())
      |      ^~~~~~
src/engine/client/backend_sdl.cpp:93:4: error: ‘IVideo’ has not been declared
   93 |    IVideo::Current()->NextVideoFrameThread();
      |    ^~~~~~
```

**Comment by Jupeyy** [comment]
> ```
> In file included from src/engine/client/backend_sdl.cpp:35:
> src/engine/client/video.h:1: error: unterminated #ifndef
>     1 | #ifndef ENGINE_CLIENT_VIDEO_H
>       | 
> src/engine/client/backend_sdl.cpp: In static member function ‘static void CGraphicsBackend_Threaded::ThreadFunc(void*)’:
> src/engine/client/backend_sdl.cpp:92:6: error: ‘IVideo’ has not been declared
>    92 |   if(IVideo::Current())
>       |      ^~~~~~
> src/engine/client/backend_sdl.cpp:93:4: error: ‘IVideo’ has not been declared
>    93 |    IVideo::Current()->NextVideoFrameThread();
>       |    ^~~~~~
> ```

what commit is that, i am currently changing some headers :D, so if the ci fails i update stuff

**Comment by Jupeyy** [comment]
You can now select the driver with the environment flag "DDNET_DRIVER"

set it to GLES and it will select GLES3 instead of OGL

We could do a patch for wayland (smth like SDL_VIDEODRIVER == "wayland").
I'm not sure yet, if hacks like these are really nice

**Comment by def-** [comment]
Ok, builds now and still works on X11. I'm wondering if we want to have such a large graphics change again, how high is the risk this will break things for regular players? Wayland is probably only used by a very small number of DDNet players.

**Comment by Jupeyy** [comment]
> Ok, builds now and still works on X11. I'm wondering if we want to have such a large graphics change again, how high is the risk this will break things for regular players? Wayland is probably only used by a very small number of DDNet players.

The change itself is rather small, our GL 3.3 context was relativly compatible to GLES3, just as the GL 1.x was to GLES 1(which we cant use bcs it was removed in some linux dists :D).
The problem this looks so huge is, that i mostly moved all code into seperate files now, bcs it was a huge mess and i wanted to clean up a bit.
That includes:
- backend_sdl shouldnt call any GL code
- no GL headers inside header files
- better support for other driver backends in general, if'd ever add dx or vulkan or whatever

So the "biggest" change here is that Linux now supports GLES and OpenGL.
Rest stays pretty much unchanged, except the cleanup. If i didnt add a bug there it should be safe

**Comment by ardadem** [comment]
Ok, i just tried on wayland and it's works on ingame but menu background is pixalated.

normal:
2021-05-02-12:24:45_screenshot

DDNET_DRIVER=GLES SDL_VIDEODRIVER=wayland set:
2021-05-02-12:20:32_screenshot

**Comment by Jupeyy** [comment]
Ah, i also tested wayland on KDE and thought its a KDE bug(that the colors look soo bad)
maybe waylands defaults for the framebuffer color range is too small, i'll later test a bit

**Comment by Jupeyy** [comment]
adding:

SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);

before window creation would fix this.
But that would also be a wayland only fix probably

**Comment by ardadem** [comment]
Yes, it's fixed. But i just noticed when i join a server first time game flickers (black screen) for a moment.

**Comment by Jupeyy** [comment]
> Yes, it's fixed. But i just noticed when i join a server first time game flickers (black screen) for a moment.
> 
> EDIT: okay, it's easy to reproduce. it happens when i switch between workspaces on sway. mb same on alt+tabbing.

possible, but the color thing i'd rate as AMD driver "bug" since, they could just do higher colors default, SDL doesnt garantuee the numbers as max value, but as minimum and Android devices do exactly that, old devices give ugly colors, while newer give a much better color range.

I also had other bugs, like 2 cursors(ingame and desktop cursor from terminal) rendered with wayland.
So its possible these are still bugs in the desktop environment or the driver, since GLES on x11 is the same GLES that is used on wayland and it works fine with x11

**Comment by ardadem** [comment]
dunno, this is what happens:


https://user-images.githubusercontent.com/13207692/116809532-1ba8b100-ab47-11eb-8ff4-d11f68e87a73.mp4

**Comment by Jupeyy** [comment]
> dunno, this is what happens:
> 
>  recording.mp4

i dunno how fast u got this, but i tested the game for like 5minutes with wayland and didnt had any huge issues besides input lag and the second cursor annoying me xd

**Comment by Scrumplex** [comment]
@Jupeyy 

> adding:
> 
> SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
> SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
> SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
> 
> before window creation would fix this.
> But that would also be a wayland only fix probably

I mean it would be a Wayland-only fix. But would it break anything? I am sure that 10-bit color support isn't a thing anyways so it might be okay to set these values to 8.

**Comment by Scrumplex** [comment]
Okay weird bug:

When I move my mouse rapidly while the client is loading the game exits before I even see the title screen. It does not crash so there is no backtrace

**Comment by Jupeyy** [comment]
> @Jupeyy
> 
> > adding:
> > SDL_GL_SetAttribute(SDL_GL_RED_SIZE, 8);
> > SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, 8);
> > SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, 8);
> > before window creation would fix this.
> > But that would also be a wayland only fix probably
> 
> I mean it would be a Wayland-only fix. But would it break anything? I am sure that 10-bit color support isn't a thing anyways so it might be okay to set these values to 8.

Yeah I dunno. I did something like that once on android and there were devices that couldn't handle it. So who knows how some other hardware reacts.
As said I would expect from amd driver to just chose the best frame buffer options it supports by default, just like android devices so, since these attributes we set are required minimum values, it does not guarantee, that the values cannot be higher

**Comment by ardadem** [comment]
The color issue fixed on SDL upstream, just tested and it's gone.

**Comment by Jupeyy** [comment]
The video renderer still needs better integration into the GL backend, but not doing this in this pr.
I used the GLES backend for a few days now, didnt see any glitches

**Comment by def-** [comment]
This diff is kind of hard to review, would be nice in the future to split up the actual change and the refactoring.

**Comment by Jupeyy** [comment]
https://github.com/Jupeyy/ddnet/commit/04b7721f4d3c05ea32180c6f4b1dd6465588f1ad


This is the relevant part of the first commit, which makes most diff

**Comment by Jupeyy** [comment]
If someone wants to test:
https://github.com/Jupeyy/ddnet/commit/086c7a987d72e52cd893546245af66273e29defb

you have to compile with cmake .. -DPREFER_BUNDLED_LIBS=1
It should work on our current master, without this GLES patch, even with wayland.
Note:
This requires relatively new SDL headers bcs of SDL_HINT_VIDEO_X11_FORCE_EGL (you can also remove the lines, if u dont care about x11)

**Comment by def-** [comment]
bors r+
Seems to still work fine on X11, haven't tested Wayland.

**Pull request merged**
