### PR TITLE
Add valgrind to integration test

### PR DESCRIPTION
**Pull request by def-**
@ChillerDragon 

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Why did you remove the `./` s?

**Comment by def-** [comment]
Seems useless. Paths are in local directory by default, even without it.

**Comment by ChillerDragon** [comment]
> Seems useless. Paths are in local directory by default, even without it.

```
chiller@debian:/usr/local/bin$ ls fail_*
fail_me
chiller@debian:/usr/local/bin$ for f in fail_*; do echo "$f"; done
fail_me
chiller@debian:/usr/local/bin$ 
```

**Comment by def-** [comment]
I don't understand your example.

**Comment by def-** [comment]
It makes sense when you start an argument with `*`, because then a cleverly named file can cause funny things. Thus I left one `./` in.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
