### PR TITLE
Only embed map file in manual client demos

### PR DESCRIPTION
**Pull request by Robyt3**
Do not embed the map file in auto, race and replay demos, to keep them smaller. See #5868.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Sorry that I didn't comment on the original issue any further.

Hmm... This is probably going to lead to some unplayable demos. Perhaps we could add the download URL to the maps and only don't store the map in demos where the download URL is known? This way, the demo player could automatically download the map once it's being played without the map file.

**Comment by Robyt3** [comment]
> This way, the demo player could automatically download the map once it's being played without the map file.

CC #2267.

**Comment by def-** [comment]
So right now this will lead to demos not being sharable without the .map file?

**Comment by Robyt3** [comment]
Yes. If you don't have the .map file, an error will be shown when you try to play the demo. The same is already the case for auto player demos recorded by the server.

**Comment by def-** [comment]
I think this makes the demo sharing experience worse, so I would say this is not worth it right now without automatic map download at least. And automatic map download would not work on unofficial servers too.

**Comment by heinrich5991** [comment]
I agree with @def- here.

**Pull request closed without merging**
