### PR TITLE
Make the dummy always press fire when cl_dummy_hammer is active

### PR DESCRIPTION
**Pull request by trml**

### CODE REVIEW

**Comment by def-** [comment]
What's the motivation?

**Comment by Learath2** [comment]
Probably to make deepfly with dummy as consistent as it is with a non-dummy
player

**Comment by trml** [comment]
Yes, this would make hammer-out-of-freeze and similar always work with dummy (similar to how it works for normal players now), as well as make it possible to deepfly without using the deepfly bind. 
 It would also make deepfly more reliable than it is with the bind (which doesn't always work), and would make it possible to deepfly with both dummy and main.

**Comment by def-** [comment]
sounds fine to me.

**Comment by Patiga** [comment]
Deep-fly as well as hammer-fly from hammer-hit works really fluently now using dummy hammer-fly, great fix :+1:
really annoying is the screaming dummy tho, every time it tries to hammer

**Comment by heinrich5991** [comment]
Sounds great. :)

bors r+

Thanks @trml! And thanks @Patiga for testing. :)

**Pull request merged**
