### PR TITLE
Version 12.4

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by def-** [comment]
Learath2: i wanted to get @fokkonaut's time format thing and @timakro's isddnet in aswell (with a netobj instead of their netmsgs)
deen: but you missed the hand
deen: ok, so I'll wait for these fixes

**Comment by def-** [comment]
https://github.com/ddnet/ddnet-web/pull/79

**Comment by def-** [comment]
Jupstar ✪: the skin selector only shows my current skin

**Comment by Learath2** [comment]
> Jupstar ✪: the skin selector only shows my current skin

06fc970ea1 fixes this

**Pull request merged**
