### PR TITLE
Update default tune zone, when no local character is alive and tune zones don't exist

### LINKED ISSUE #4140: Vanilla shotgun broken while in spec
b1051d23984bed5de37eb5339cd8bd1271213f2b
breaks vanilla shotgun, when in spec (looking at someone shooting, while in spec)

@TsFreddie

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #4140

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
bors r-

Needs discussion if game settings changing is supported.

**Comment by Jupeyy** [comment]
but LoadMapSettings is only called from OnConnect, so there is no change in settings afterwards

**Comment by heinrich5991** [comment]
True @ only called once.

**Comment by heinrich5991** [comment]
Just one more question, is the data already available in `OnConnected`?

**Comment by Jupeyy** [comment]
Yeah that's the only thing I wasn't sure, if that can happen, but i connected to a server, so its called on ddnet

**Comment by Jupeyy** [comment]
Ah its somehow cached when you disconnect and reconnect again?

At first start its false

**Comment by heinrich5991** [comment]
Mh, cached might be an optimistic statement for "never getting cleared".

**Comment by Jupeyy** [comment]
So the dirty hack would be to add a bool that is like `m_NeedsTuneZonePredictUpdate` and just sets everything when UpdatePrediction is called the first time

If you got an better idea would be nice, bcs i don't have the overview over the flow the network code

**Comment by Jupeyy** [comment]
> Mh, cached might be an optimistic statement for "never getting cleared".

that explains why the entities are changed a few moments after the connect to vanilla :D

**Comment by heinrich5991** [comment]
I think with #4169 you can set it the first time `OnNewSnapshot` is called.

**Comment by trml** [comment]
Small question: Is the client guaranteed to receive the first snapshot before the first tuning message?

**Comment by Jupeyy** [comment]
Thats a question you should answer me xd

**Comment by Jupeyy** [comment]
But if tuning messages are always send, we dont need to initialize the tuning params anyway, do we?

**Comment by trml** [comment]
For the tunezone the player starts in (which would be zone 0 most of the time), we don't. For the others, they are not received from the server until the first time the player visits them (or specs them, I assume, but not sure), so this code can help with predicting those the first time after joining a map.

And about the first question, I'm not sure :P these things would be a lot easier to reason about if the tunings were part of the snapshot.

**Comment by Jupeyy** [comment]
Ok i don't even know what the tunezone packet is.
But isn't skipping index 0 the main problem?
Index 0 =  default tune zone(which might not be updated by the server) -> has to be initialized

**Comment by Jupeyy** [comment]
Should i remove the first commit, or can it theoretically happen that the server sends it too early if it wanted

**Comment by trml** [comment]
> Should i remove the first commit, or can it theoretically happen that the server sends it too early if it wanted

After looking more at the code, the NETMSGTYPE_SV_TUNEPARAMS message only updates `m_Tuning`, while the code block in LoadMapSettings only updates `m_aTuningList`, and settings are only moved from m_Tuning to m_aTuningList after OnNewSnapshot is called, so this commit is perhaps not needed after all. And the code before my first comment was actually correct :| (the added condition in LoadMapSettings)

The second commit additionaly fixes that tunings were ignored when joining to spec on vanilla servers, though. (which was also part of the cause for the bug)

**Comment by Jupeyy** [comment]
ah yeah true, i'll just remove it

**Comment by Learath2** [comment]
Q: Why do we have `m_Tuning` at all? Why can't we just use `TuningList()[0]`?

**Comment by Jupeyy** [comment]
Bcs we don't have a packet that sends the tune params for a tunezone (no tune index)
So we need a temporary state anyway

But we do use TuningList[0] most of the time now

**Comment by Learath2** [comment]
Should we sneak the tune zone index in there? Iirc vanilla ignores any extra tuning, so we could just add it to the end as a "tune".

**Comment by Jupeyy** [comment]
That's something you should discuss with @trml or heinrich , I've no idea if packet sizes are checked or not

**Comment by trml** [comment]
Using a faketune would work, yes. Then perhaps fall back to vanilla behavior (use zone 0 for everything) if the tune/info doesn't exist.

**Comment by heinrich5991** [comment]
This still fixes the original issue? @Jupeyy

**Comment by Jupeyy** [comment]
Yes

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
