### PR TITLE
Replace browser icons with font icons

### PR DESCRIPTION
**Pull request by Jupeyy**
Replace and remove the menu icons and use the font icons instead.
Personally i find them more attractive, and objectivly they are resolution indepentent.

Opinions?

before:
screenshot_2022-03-19_11-26-51

screenshot_2022-03-19_11-31-02

after:
screenshot_2022-03-19_11-45-24

screenshot_2022-03-19_11-30-41

screenshot_2022-03-19_11-44-16

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Personally I'm in favor. Other opinions?

**Comment by C0D3D3V** [comment]
Looks like you could also put parts of the code into a function to avoid duplicated code, but it looks good.

**Comment by C0D3D3V** [comment]
The finish flag could be friendlier, it's pretty rigid and not slanted. The old flag was more wavy

**Comment by sjrc6** [comment]
I like it.

**Comment by Jupeyy** [comment]
> The finish flag could be friendlier, it's pretty rigid and not slanted. The old flag was more wavy

The old looked weird tho, not like a racing flag

But yeah the waving point is true, tho i dont find any better icon:

https://fonts.google.com/icons

if you want to search

**Comment by Jupeyy** [comment]
> Looks like you could also put parts of the code into a function to avoid duplicated code, but it looks good.

yeah if we merge it, its defs worth it :D

**Comment by C0D3D3V** [comment]
this flag is in the free licensed version of font awesome https://fontawesome.com/icons/flag-checkered?s=solid

**Comment by Jupeyy** [comment]
> this flag is in the free licensed version of font awesome https://fontawesome.com/icons/flag-checkered?s=solid

You sure the license is free. Remeber debian and other linux distros have quite a bit of requirement

**Comment by C0D3D3V** [comment]
the duotone version would also look good, but unfortunately it is not free

**Comment by C0D3D3V** [comment]
This is the descriprion of the free license:
https://fontawesome.com/license/free

Font Awesome Free is free, open source, and GPL friendly. You can use it for commercial projects, open source projects, or really almost whatever you want. 



So one could add the svg of the flag to our ttf... 

or grab the flag from the published free licenced ttf

https://github.com/FortAwesome/Font-Awesome/

In font awesome v5 the flag looks like this:
https://fontawesome.com/v5/icons/flag-checkered?s=solid
the v5 ttf can be downloaded from here
ttps://github.com/FortAwesome/Font-Awesome/archive/5.15.4.tar.gz

**Comment by Jupeyy** [comment]
if you want to look at it go ahead, you can always cherry-pick this pr

**Comment by C0D3D3V** [comment]
Ok, yes I will do later screenshots with the flags from font awesome.

this is the font license:
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#5667e9e4


We could also just incude one version of font awesome, but that would maybe be to much for only one used icon :D

**Comment by Jupeyy** [comment]
> Ok, yes I will do later screenshots with the flags from font awesome.
> 
> this is the font license: https://scripts.sil.org/OFL
> 
> We could also just incude one version of font awesome, but that would maybe be to much for only one used icon :D

Yeah they have a really good amount of icons, we can also replace our material icons with that font, they seem to have all icons we use

**Comment by Jupeyy** [comment]
image

**Comment by C0D3D3V** [comment]
xD i was just about to merge the flags from the different font awesome versions into our font. I don't need to do that after all.
I also saw that the noto-color-emoji (which I think android also uses) has a nice racing finish flag, but the font is not compatible.

Which font awesome version do you have now merged?

**Comment by Jupeyy** [comment]
> Which font awesome version do you have now merged?

latest from their github, 6.10 was it i think

**Comment by C0D3D3V** [comment]
One thing that we don't make so easy anymore is the swapping of the symbols, until now we had the possibility to make the graphics swappable in the assets settings (in future). So the change by the user is no longer so easy, but I think it looks very good, and requires no change. I think it is very good.

**Comment by Jupeyy** [comment]
image

they dont have a verifies with sprinkles, so i simmulated it, looks like a real one :D

**Comment by C0D3D3V** [comment]
I already liked the round symbols with the hook, but if you like the symbol with the sprinkles, I won't stop you.

**Comment by Jupeyy** [comment]
> I already liked the round symbols with the hook, but if you like the symbol with the sprinkles, I won't stop you.

I'd say i am used to it, since that's what all social media does :D

**Comment by Chairn** [comment]
Well, i prefer the old ones, but the flag looks good in the second new version. Is it possible to change the background color of the tick or does it match the type column color?

**Comment by C0D3D3V** [comment]
Can it be that the tick is not quite centered? In the round version it looks more central, could be that the smaller font must be moved down?  Or is that just an illusion?

**Comment by Jupeyy** [comment]
> Can it be that the tick is not quite centered? In the round version it looks more central, could be that the smaller font must be moved down? Or is that just an illusion?

i dunno should be pretty centered actually, except its inside the font



> Is it possible to change the background color of the tick or does it match the type column color?

to what color do you want it? Blue and green and most commonly used, so i chose blue

**Comment by C0D3D3V** [comment]
I think he meant the tick itself not the frame.

**Comment by def-** [comment]
We are only using a fixed set of glyphs from icons.otf? I'll try to optimize the file with https://stackoverflow.com/questions/35555816/delete-all-unused-characters-from-a-ttf-font-with-fontforge

**Comment by def-** [comment]
Or maybe not worth the effort for 1 MB.
bors r+

**Pull request merged**
