### PR TITLE
Rename all variables for strict camel-casing of abbreviations

### LINKED ISSUE #7750: Yet another meta variable naming discussion: SoundID/SoundId MsgID/MsgId
We use ``ClientID`` all over the code base. Also ``SoundID`` and ``MsgID`` is used. But then there is also ``MsgId`` and ``SoundId``. I propose to stick to ``ID`` everywhere and get rid of all ``Id``.

### PR DESCRIPTION
**Pull request by heinrich5991**
This is the strict version, ID → Id, UI → Ui, except DDNet which stays DDNet.

This would fix #7750.

Done using a naive rename script (for bash, use `shopt -s globstar`):

```fish
sed -i \
        -e 's/\([a-z]_\?\)ID/\1Id/g' \
        -e 's/\([^ ]\)\<UI\>/\1Ui/g' \
        -e 's/UI()/Ui()/g' \
        -e 's/\<CUI\>/CUi/g' \
        -e 's/\([\ta-z.(&]\|[,=|] \)ID\>/\1Id/g' \
        -e 's/\<ID\>\([^ ").]\)/Id\1/g' \
        -e 's/\<ID\([0-9]\)/Id\1/g' \
        -e 's/\<ID\>\( [<=>:+*/-]\)/Id\1/g' \
        -e 's/int ID/int Id/g' \
        -e 's/\([a-z]_\?\)GPU/\1Gpu/g' \
        -e 's/\([a-z]_\?\)IP/\1Ip/g' \
        -e 's/\([a-z]_\?\)CID/\1Cid/g' \
        -e 's/\([a-z]_\?\)MySQL/\1Mysql/g' \
        -e 's/MySql/Mysql/g' \
        -e 's/\([a-xz]_\?\)SQL/\1Sql/g' \
        -e 's/DPMode/DpMode/g' \
        -e 's/TTWGraphics/TTwGraphics/g' \
        \
        -e 's/Ipointer/IPointer/g' \
        -e 's/\.vendorId/.vendorID/g' \
        -e 's/\.windowId/.windowID/g' \
        -e 's/SDL_GetWindowFromId/SDL_GetWindowFromID/g' \
        -e 's/SDL_AudioDeviceId/SDL_AudioDeviceID/g' \
        -e 's/SDL_JoystickId/SDL_JoystickID/g' \
        -e 's/SDL_JoystickInstanceId/SDL_JoystickInstanceID/g' \
        -e 's/AVCodecId/AVCodecID/g' \
        src/**/*.cpp src/**/*.h {datasrc,scripts}/**/*.py
git checkout -- src/engine/external
```

I like this option because it presents clear rules.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by archimede67** [comment]
I don't think this makes much sense. I would say it's fine that `ID` becomes `Id` because the word is `Identifier`. But I don't see why it would be the same for things like `GPU` or `UI` which are not a single word each. Since they are both composed of multiple word, the abbreviation being all uppercase makes more sense, plus I find `Gpu` to be quite ugly for example.

**Comment by heinrich5991** [comment]
> But I don't see why it would be the same for things like `GPU` or `UI` which are not a single word each. Since they are both composed of multiple word, the abbreviation being all uppercase makes more sense, plus I find `Gpu` to be quite ugly for example.

The idea is to have a rule that we can mindlessly apply without getting into discussions which abbreviations should be uppercased and which not.

E.g. Rust has https://rust-lang.github.io/api-guidelines/naming.html, which says:
> In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, Usize rather than USize or Stdin rather than StdIn. In snake_case, acronyms and contractions are lower-cased: is_xid_start.

In fact, we already use `Uuid` in our codebase.

**Comment by def-** [comment]
This will create lots of conflicts for anyone having a fork and have little use in my opinion (as most naming convention changes after a project is already large).

**Comment by heinrich5991** [comment]
> This will create lots of conflicts for anyone having a fork and have little use in my opinion (as most naming convention changes after a project is already large).

This **unifies** the naming convention. If we don't pick either way, we'll stay with both naming conventions, wasting time on PRs discussing which to use. Which wastes less time?

**Comment by Jupeyy** [comment]
> This **unifies** the naming convention. 

this is generally cool. 

> If we don't pick either way, we'll stay with both naming conventions, wasting time on PRs discussing which to use. Which wastes less time?

But if we allow both, how can it cost more time?

I'd support this if clang-tidy or clang-format supports it and auto fixes it in the editor. Before that it will waste time on PRs discussion non obvious design choices + the reviewer has to manually review it, which also costs time. I'd rate it similar to the code format stuff before we had clang-format.

**Comment by BlaiZephyr** [comment]
> I'd support this if clang-tidy or clang-format supports it and auto fixes it in the text editor / IDE.
this also seem's like a better way of handling it for us mod maker's

> This will create lots of conflicts for anyone having a fork and have little use in my opinion (as most naming convention changes after a project is already large).
having clang-tidy | clang-format handle the naming convention seem's to be more convenient rather than using another script just for that, it also prevents having to handle merge conflicts (even if its just a one time thing, it still seem's annoying to do)

**Comment by ChillerDragon** [comment]
> This will create lots of conflicts for anyone having a fork and have little use in my opinion (as most naming convention changes after a project is already large).

@def- as someone who cares a lot of git conflicts and someone who is merging multiple forks into ddnet I do not think this would be a problem. This could be shipped with 4 lines of bash that auto solve the merge conflict. It will conflict yes but solving the conflict should be a simple copy paste of a merge helper.

Pseudo code:
- merge until one sha before this commit
- merge `-X ours` only this commit (auto applies current version on conflict)
- run heinrichs sed command; commit or commit ammend
- merge the rest

The pr could be tagged with a label and everyone who opted in to get notified for mod relevant changes will get a notification and see the merge helper command. #7895

> But if we allow both, how can it cost more time?
@Jupeyy 

It personally costs me more developer time if I get compile errors due to case mismatch. Which I got multiple times when working with MsgID for example because the code uses different casing in different places.

**Review by def- — APPROVED** [review]

**Comment by ChillerDragon** [comment]
@heinrich5991 not sure which shell you are using that globs **.cpp correctly. I came up with this alternative which passes shellcheck with a /bin/sh shebang so it should be POSIX complaint

```
#!/bin/sh

find . \
	-type f \
	\( -name "*.cpp" -o -name "*.h" \) \
	-not -path "./src/engine/external/*" \
	-exec \
	sed -i \
        -e 's/\([a-z]_\?\)ID/\1Id/g' \
        -e 's/\<UI\>/Ui/g' \
        -e 's/\<ID\>/Id/g' \
        -e 's/\([a-z]_\?\)GPU/\1Gpu/g' \
        -e 's/\([a-z]_\?\)IP/\1Ip/g' \
        -e 's/\([a-z]_\?\)CID/\1Cid/g' \
        -e 's/MySQL/Mysql/g' \
        -e 's/\([a-z]_\?\)SQL/\1Sql/g' \
        -e 's/DPMode/DpMode/g' \
        -e 's/TTWGraphics/TTwGraphics/g' \
        \
        -e 's/Ipointer/IPointer/g' \
        -e 's/\.vendorId/.vendorID/g' \
        -e 's/\.windowId/.windowID/g' \
        -e 's/SDL_GetWindowFromId/SDL_GetWindowFromID/g' \
        -e 's/SDL_AudioDeviceId/SDL_AudioDeviceID/g' \
        -e 's/SDL_JoystickId/SDL_JoystickID/g' \
        -e 's/SDL_JoystickInstanceId/SDL_JoystickInstanceID/g' \
        -e 's/AVCodecId/AVCodecID/g' \
	{} \;
```

**Comment by heinrich5991** [comment]
Fixed up the script to be more precise. Also noted you can use `shopt -s globstar` to run it in bash.

**Comment by ChillerDragon** [comment]
Merging this went as smooth as I expected it to be. I merged my first fork and here are the commands I ran if anyone else needs them

```bash
# run every command on its own and check for errors
# especially the `git merge` commands need manual intervention on conflict
# this script has to be run from the root of your ddnet source code

[ -n "${BASH_VERSINFO+x}" ] && shopt -s globstar

git remote add ddnet git@github.com:ddnet/ddnet.git
git fetch ddnet

git merge --no-edit 17402cc43fdf51c8cb81b724228f11c423d17007^
# now is a good time to verify your build is still passing
# and your code is working as expected

git merge --no-edit -X ours 17402cc43fdf51c8cb81b724228f11c423d17007
# your code is now expected to have compile errors
# do not try to fix them

sed -i \
        -e 's/\([a-z]_\?\)ID/\1Id/g' \
        -e 's/\([^ ]\)\<UI\>/\1Ui/g' \
        -e 's/UI()/Ui()/g' \
        -e 's/\<CUI\>/CUi/g' \
        -e 's/\([\ta-z.(&]\|[,=|] \)ID\>/\1Id/g' \
        -e 's/\<ID\>\([^ ").]\)/Id\1/g' \
        -e 's/\<ID\([0-9]\)/Id\1/g' \
        -e 's/\<ID\>\( [<=>:+*/-]\)/Id\1/g' \
        -e 's/int ID/int Id/g' \
        -e 's/\([a-z]_\?\)GPU/\1Gpu/g' \
        -e 's/\([a-z]_\?\)IP/\1Ip/g' \
        -e 's/\([a-z]_\?\)CID/\1Cid/g' \
        -e 's/\([a-z]_\?\)MySQL/\1Mysql/g' \
        -e 's/MySql/Mysql/g' \
        -e 's/\([a-xz]_\?\)SQL/\1Sql/g' \
        -e 's/DPMode/DpMode/g' \
        -e 's/TTWGraphics/TTwGraphics/g' \
        \
        -e 's/Ipointer/IPointer/g' \
        -e 's/\.vendorId/.vendorID/g' \
        -e 's/\.windowId/.windowID/g' \
        -e 's/SDL_GetWindowFromId/SDL_GetWindowFromID/g' \
        -e 's/SDL_AudioDeviceId/SDL_AudioDeviceID/g' \
        -e 's/SDL_JoystickId/SDL_JoystickID/g' \
        -e 's/SDL_JoystickInstanceId/SDL_JoystickInstanceID/g' \
        -e 's/AVCodecId/AVCodecID/g' \
        src/**/*.cpp src/**/*.h {datasrc,scripts}/**/*.py
git checkout -- src/engine/external

# your code should now compile again
# verify everything is working and then commit the changes

git add . && git commit -m "Run camel case style script"

# now you are past the problematic commit and can continue merging from here
```

**Comment by heinrich5991** [comment]
Thanks, @ChillerDragon. ❤️

**Comment by ChillerDragon** [comment]
This should be added to the ./scripts/fix_style.py ASAP and it should be checked in the CI. The diff is already piling up again.

**Comment by ChillerDragon** [comment]
I gave it a try and rage quitted. Getting sed to work on mac is such a pain. Doing it in python would be too slow.

But if we do not enforce that new style guide the code will pretty soon be as inconsitent as before.

**Pull request merged**
