### PR TITLE
Version 15.3

### PR DESCRIPTION
**Pull request by def-**
zopfli_screenshot-20210131@174106
DDNet 15.3 is supposed to release in 1 week, assuming no bad bugs are found. Please test Release Candidate 1 to prevent problems being only discovered after release. Report bugs in the #bugs channel or directly on Github:

- Windows 32bit: https://ddnet.tw/downloads/DDNet-15.3-rc4-win32.zip
- Windows 64bit: https://ddnet.tw/downloads/DDNet-15.3-rc4-win64.zip
- Linux x86: https://ddnet.tw/downloads/DDNet-15.3-rc4-linux_x86.tar.xz
- Linux x86_64: https://ddnet.tw/downloads/DDNet-15.3-rc4-linux_x86_64.tar.xz
- Mac OS X: https://ddnet.tw/downloads/DDNet-15.3-rc4-osx.dmg

You can also test the release candidate in Steam by clicking on Settings -> Properties -> Betas and opting into the Release Candidates. This will automatically update you to a new release candidate when it is available, and to the next release when no new candidate is available. So you can always leave this setting enabled to help us test new releases earlier.

The following changes are included, ideally test their behaviour specifically. But just playing as you do normally also helps:

- [Client] **Add Discord rich presence (except on Linux x86)** [Ryozuki & heinrich5991]
- [Client] **Allow online resizing of window on Windows** [Jupeyy]
- [Client] **Menu tabs animations** [Banana090]
- [Client] **Color picker in settings** [Banana090]
- [Client] **Better sliders and lists** [Banana090]
- [Client] **Indicate strength of hook in nameplates (ctrl-shift-d)**
- [Client] **Freeview mouse moves faster when zoomed out**
- [Client] Don't predict input from dummy when it's paused
- [Client] Keep showing last checkpoint after kill
- [Client] Use map download URL from info2.ddnet.tw
- [Client] Fixed mouse jumping after losing focus [Banan090]
- [Client] Notify about vote when logged in
- [Client] Fix prediction with global collision off tiles and tunings [trml]
- [Client] Check skin/sprite images for correctness [Jupeyy]
- [Client] Unlimited texture names [Jupeyy]
- [Client] Remove hardcoded zoom level limits (cl_limit_max_zoom_level) [Jupeyy]
- [Client] Filter invalid kill messages [Jupeyy]
- [Client] First Arabic client translation [.Yukki]
- [Client] Add F-DDrace entities [fokkonaut]
- [Client] Update ingame BlockWorlds entities [Brokecdx]
- [Client] Don't sort server browser on entry adding, but once per update call [Jupeyy]
- [Client] Respect possible particle size increase, of worst case rotation [Jupeyy]
- [Client] Dynamically size scoreboard title
- [Client] Remove ddnet info tmp file always when quitting [Ryozuki]
- [Client] Fix freezing with text boxes [TsFreddie]
- [Client] Move PNG loading in SkinDL to fetch thread to prevent graphics lags
- [Client] Add more default binds and binds in settings (h for dummy hammer, up/down for deepfly on/off, / for chat command)
- [Client] HTTP Map Download: Time out faster
- [Client] Increase Intel driver blocklist range [Jupeyy]
- [Client] Run server in background on Windows
- [Client] Fix client crash with too many items
- [Client] Fix up/down keys in demo browser
- [Client] Log duplicate messages in console
- [Client] Port some refactor from teeworlds-0.7 [Kaffeine]
- [Editor] Allow reordering commands in the server settings editor [Learath2]
- [Editor] Make dragging quads in the editor more sensitive to small mouse deltas [timakro]
- [Server] **Make netclipping of entities and events respect shown distance**
- [Server] **Display median time instead of average**
- [Server] Reset practice after team saved and got killed
- [Server] Add (un)endless_hook commands
- [Server] rank/teamrank: Display how much better you are
- [Server] Add /top5team s?i command to show all team ranks of a player [Zwelf]
- [Server] Check finish of team after player joins spectators
- [Server] Allow UTF8 ban reasons
- [Server] Remove SQL locks [Zwelf]
- [Server] Handle switch number 0
- [Server] Improve error messages when you can't join team
- [Server] Fix storing load/save result in main thread without incrementing usage count [Zwelf]
- [Server] Synchronize database thread via atomic_bool instead of use_count from shared pointer [Zwelf]
- [Server] Keep veto right after joining dummy with lower ID
- [Server] Support F-Client and replace non-extended extension messages [heinrich5991]
- [Server] Fix server crash with too many items
- [Server] Fix centisecs rounding in ranks
- [Server] Show sixup client info in status [nobody-mb]
- [Server] Also display DDNet version for 0.7 clients in status [heinrich5991]
- [Server] Disable ninja jetpack when player has telegun
- [Everywhere] Lots of minor fixes, thanks to everyone!

### CODE REVIEW

**Comment by murpii** [comment]
Not really a bug but: 
y8GKGMiUOd

**Comment by edg-l** [comment]
image
Steam release on linux should have discord enabled, steam itself only supports ubuntu lts, so any older distro is not supported and we should do the same for the ddnet client on linux.

I don't agree with this comment https://github.com/ddnet/ddnet/pull/3500#issuecomment-769270013, i want to use the steam release.

**Comment by def-** [comment]
> Not really a bug but:
> y8GKGMiUOd

@Banana090 Thoughts?

**Comment by def-** [comment]
> image
> Steam release on linux should have discord enabled, steam itself only supports ubuntu lts, so any older distro is not supported and we should do the same for the ddnet client on linux.
> 
> I don't agree with this comment [#3500 (comment)](https://github.com/ddnet/ddnet/pull/3500#issuecomment-769270013), i want to use the steam release.

This means I need a different build process for the Steam release for Linux with a more recent Debian version. Or bite into the apple and upgrade all Linux builds. Many distributions won't work anymore then.

**Comment by def-** [comment]
Actually Ubuntu LTS does not work with the Discord lib since it only ships glibc 2.23 and Discord lib requires 2.27.

**Comment by edg-l** [comment]
> Actually Ubuntu LTS does not work with the Discord lib since it only ships glibc 2.23 and Discord lib requires 2.27.

https://launchpad.net/ubuntu/focal/+source/glibc

They ship 2.31, note that the pic i sent says "latest ubuntu lts" which is right now 20.04.

**Comment by edg-l** [comment]
> > image
> > Steam release on linux should have discord enabled, steam itself only supports ubuntu lts, so any older distro is not supported and we should do the same for the ddnet client on linux.
> > I don't agree with this comment [#3500 (comment)](https://github.com/ddnet/ddnet/pull/3500#issuecomment-769270013), i want to use the steam release.
> 
> This means I need a different build process for the Steam release for Linux with a more recent Debian version. Or bite into the apple and upgrade all Linux builds. Many distributions won't work anymore then.

Is it that troublesome to only do it for steam?

**Pull request closed without merging**
