### PR TITLE
Allow changing opacity of freeze bars

### PR DESCRIPTION
**Pull request by Learath2**
A couple players mentioned a lower opacity freeze bar is better for them. This allows that without introducing an extra option but rather repurposing the old ones.

It adds a magic coefficient of `.75f`. Which I thought looks reasonable, but if really wanted we could make `cl_freezebar_inside_freeze` an opacity setting too so people can independently set their in-freeze alpha too.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by C0D3D3V** [comment]
I would like to have two sliders, one for inside freeze one for normal freezebar. Because I do not want to see the freezebar inside freeze at all.

**Comment by C0D3D3V** [comment]
I see you converted it to `m_ClFreezeBarsInsideFreeze` ...

**Comment by C0D3D3V** [comment]
I guess `cl_freezebar_alpha_inside_freeze` is reasonable, because maybe someone gets triggered because the freezebar changes transparency while you jump through freeze.

Otherwise, I think the change is good.

**Comment by Learath2** [comment]
It's less than ideal that now we have weird configuration that is possible where freeze bars will only be shown while inside freeze, but I guess I'll just have to live with it.

**Comment by heinrich5991** [comment]
Perhaps the opacities could be multiplied? So that you can't have a freezebar only in freeze.

**Comment by Learath2** [comment]
> Perhaps the opacities could be multiplied? So that you can't have a freezebar only in freeze.

I thought about this but idk how to communicate it to the layman. I could call it the "in freeze alpha multiplier" but does that really mean anything to the standard player?

**Comment by C0D3D3V** [comment]
You could name it "Multiplicative opacity of freeze bar inside freeze"
And to the label you could add a tooltip "This opacity is multiplied to the normal freeze bar opacity" (if it is not to long)

I guess that is better then some other setting texts that also do not communicate the truth. (for example we could calculate the correct nameplate size in the nameplate size slider text using the offset of the default size, to not suggest the size would be 0 if you slide it to the left.) But I guess we improve with every step.

Thinking about this. How about just call it "Opacity of freeze bar inside freeze" and use in the lable as maximum the set normal opacity, and calculate the muliplicative opacity.

**Comment by heinrich5991** [comment]
Status: Waiting for author.

@Learath2 Still interested?

**Comment by Learath2** [comment]
So what would we like to do? I liked the initial version of this PR because it avoided the weird situation in the first place.

Is "Multiplicative Opacity" really a concept the layman understands?

**Comment by C0D3D3V** [comment]
I tested this option with the new textures used in #6724 I think it makes no sens to allow this option with the new teytures. The bar is already so small...  Maybe we wait till the release of the new textures, and then ask again if the option is still wished.

**Comment by edg-l** [comment]
closing as its stale, anyone interested can open another pr with the conflicts fixed

**Pull request closed without merging**
