### PR TITLE
Fix mysql windows

### PR DESCRIPTION
**Pull request by kinggta**
sv_use_sql 1
add_sqlserver "w" "teeworlds" "record" "root" "" "localhost" "3306" "1"
add_sqlserver "r" "teeworlds" "record" "root" "" "localhost" "3306"
for config file something like this wll work without crash mysql on windows.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Can you explain your changes? Why did the existing connect code not work, what does yours do differently to fix it?

**Comment by kinggta** [comment]
In server.cpp if not being like this
`
bool SetUpDb;
if (str_comp_nocase(pResult->GetString(0), "w") == 0)
{
	ReadOnly = false;
	SetUpDb = pResult->NumArguments() == 8 ? pResult->GetInteger(7) : true;
}
`
and users in cfg file use codes like 
add_sqlserver "w" "teeworlds" "record" "root" "" "localhost" "3306" "1"
add_sqlserver "r" "teeworlds" "record" "root" "" "localhost" "3306" "1"
server will crash after run.

In server_sql.cpp connection_properties is problem in windows.
When i debug DDNet-Server on windows show me this lines
`
	connection_properties["hostName"]      = sql::SQLString(m_aIp);
	connection_properties["port"]          = m_Port;
	connection_properties["userName"]      = sql::SQLString(m_aUser);
	connection_properties["password"]      = sql::SQLString(m_aPass);
	connection_properties["OPT_CONNECT_TIMEOUT"] = 10;
	connection_properties["OPT_READ_TIMEOUT"] = 10;
	connection_properties["OPT_WRITE_TIMEOUT"] = 20;
	connection_properties["OPT_RECONNECT"] = true;
	connection_properties["OPT_CHARSET_NAME"] = sql::SQLString("utf8mb4");
`

so i add this simple mysql connection for windows.
`
	char aBuf[128];
	str_format(aBuf, sizeof(aBuf), "tcp://%s:%d", m_aIp, m_Port);	
	// Create connection
	{
		scope_lock GlobalLockScope(m_pGlobalLock);
		m_pDriver = get_driver_instance();
	}
	m_pConnection = m_pDriver->connect(aBuf, m_aUser, m_aPass);
`
So sorry for my terrible English.

**Comment by def-** [comment]
> So sorry for my terrible English.

No worries, it's easy to understand. And thanks for making this PR I asked you for :)

**Comment by Learath2** [comment]
I wonder why connection_properties doesn't work on windows

**Comment by def-** [comment]
I saw the same issue on Debian with zcatch using the bundled mysql version. The solution seems to be to update the mysql cpp connector.

**Pull request closed without merging**
