### PR TITLE
Try fixing "out of sync" MySQL error

### PR DESCRIPTION
**Pull request by heinrich5991**
Do this by always reading the result set to the end before starting the
next query.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Tries fixing #3649, couldn't reproduce the bug locally.

**Comment by def-** [comment]
@Zwelf thoughts?

**Comment by Zwelf** [comment]
Looks like this is a way to fix it:
> Error number: 2014; Symbol: CR_COMMANDS_OUT_OF_SYNC;
>
> Message: Commands out of sync; you can't run this command now
> 
> Commands were executed in an improper order. This error occurs when a function is called that is not appropriate for the current state of the connection. For example, if mysql_stmt_fetch() is not called enough times to read an entire result set (that is, enough times to return MYSQL_NO_DATA), this error may occur for the following C API call. [[1]](https://dev.mysql.com/doc/mysql-errors/8.0/en/client-error-reference.html#error_cr_commands_out_of_sync)

But another way to approach it would be to use [mysql_stmt_store_result()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-stmt-store-result.html) to not fetch one row at a time with mysql_stmt_fetch(). This could reduce the round trip times until the result is fetched (and might simplify the code)?

**Comment by Zwelf** [comment]
To reproduce and test this, queries which don't access rows can be executed (e.g. `/top5team` with at least one teamrank). I think we can merge for now, even if heinrich only tested the change but couldn't reproduce the bug.

**Comment by Learath2** [comment]
Um, isn't the entire point of this API not having to fetch the entire result? I'm really not sure about this fix.

**Comment by heinrich5991** [comment]
> Um, isn't the entire point of this API not having to fetch the entire result? I'm really not sure about this fix.

Not in my understanding. In my understanding, the point of the API is to not have the complete result set in memory at once. Not really useful for our use case, I guess.

From https://dev.mysql.com/doc/mysql-errors/8.0/en/client-error-reference.html#error_cr_commands_out_of_sync:
> Commands were executed in an improper order. This error occurs when a function is called that is not appropriate for the current state of the connection. For example, if mysql_stmt_fetch() is not called enough times to read an entire result set (that is, enough times to return MYSQL_NO_DATA), this error may occur for the following C API call.

**Comment by Zwelf** [comment]
Tested a bit, but OUT_OF_SYNC still occurs with this patch applied

**Comment by Learath2** [comment]
How about a [`mysql_stmt_free_result()`](https://dev.mysql.com/doc/c-api/8.0/en/mysql-stmt-free-result.html) sounds like it will close any open cursor without bearing the cost of fetching all the rest of the rows.

**Comment by heinrich5991** [comment]
Root cause was something different.

**Pull request closed without merging**
