### PR TITLE
Add favorite skins

### PR DESCRIPTION
**Pull request by Jupeyy**
Advantages:
- my friend fokkonaut can mark his favorite vanilla skins
- u can mark skin db skins which auto download if not loaded

untested, bad code, maybe buggy.
but still want feedback :)

image

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
I dont see a show favourites only button, is that intended?

**Comment by def-** [comment]
How about we fuse this with the vanilla skins and make them the favorites by default?

**Comment by fokkonaut** [comment]
> How about we fuse this with the vanilla skins and make them the favorites by default?

The vanilla skins option was meant to only render vanilla skins ingame, not for filtering in the first place.

**Comment by NouaaTW** [comment]
looks cool, but imo on the image the favorite logo looks extra weird, maybe it's because of the color?

**Pull request merged**
