### PR TITLE
Add secure_random_uninit

### PR DESCRIPTION
**Pull request by ChillerDragon**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Also in `src/test/test.cpp`.

**Comment by ChillerDragon** [comment]
> Also in `src/test/test.cpp`.

Ye thought about that then was too sure to figure out where exactly :D

**Comment by Robyt3** [comment]
Yeah, just directly before `cmdline_free`.

**Comment by ChillerDragon** [comment]
Thanks

**Pull request merged**
