### PR TITLE
DON'T SUBMIT: Disable security

### PR DESCRIPTION
**Pull request by def-**
-fstack-protector-all and FORTIFY_SOURCE
Just an attempt to see what performance impact it has

### CODE REVIEW

**Comment by def-** [comment]
Please try the nightly build of this change if you have performance problems with newer DDNet versions: https://ddnet.tw/news/nightly-builds/
Note that this has reduced security though.

**Comment by heinrich5991** [comment]
We should probably swap `-fstack-protector-all` for `-fstack-protector-strong`.

**Comment by heinrich5991** [comment]
(Note that `-fstack-protector-all` was also enabled in bam and that `_FORTIFY_SOURCE` should have a negligible performance impact.)

**Comment by def-** [comment]
Well, it was just a hunch while I was enabling warnings closeby.

**Pull request closed without merging**
