### PR TITLE
Update simplified_chinese.txt

### PR DESCRIPTION
**Pull request by QingGo**
fix translation error and add some translation.

### CODE REVIEW

**Comment by TsFreddie** [comment]
IIRC, "Play" is used in demo menu to "play" the demo. While in the start menu "Play" means "start playing the game".

We can apply a dirty solution to change "Play" in the demo menu to "Playback" to avoid translation conflict, or add context to the localization string like upstream does.

**Comment by QingGo** [comment]
Approve @TsFreddie. I didn't think about this change can affect the "Play" at demo menu. Change the "Play" at main menu to "Start Game" of change the "Play" at demo menu to "Playback" could fix this problem.

**Comment by def-** [comment]
Since the old "Play" in demo menu has been in use for a while, let's keep it.

The cleanest solution would be to have context as in Teeworlds. I'll give that a try.

I'm wondering if we should also just switch to json instead of the weird format we have at the moment. But then json might be a bit annoying to edit and Transifex probably costs money.

**Comment by def-** [comment]
See https://github.com/ddnet/ddnet/pull/2816

**Pull request merged**
