### PR TITLE
Deemphasize foes

### PR DESCRIPTION
**Pull request by Scrumplex**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Scrumplex** [comment]
I would also appreciate some thoughts about this. Currently the foe feature is not well integrated. In addition to this I though about also de-emphasizing the name in other places (scoreboard, server browser, spectator-menu)

**Comment by heinrich5991** [comment]
This is something you'd like to see yourself? It seems that deemphasizing in the scoreboard/serverbrowser might actually emphasize the name if it's the only thing that's "deemphasized".

Please use the Teeworlds variable name style btw.

**Comment by Scrumplex** [comment]
> This is something you'd like to see yourself?

I mean I am not quite happy with my implementation above. I just opened the PR to get some ideas from others :D

> It seems that deemphasizing in the scoreboard/serverbrowser might actually emphasize the name if it's the only thing that's "deemphasized".

I mean it should still be a visual indicator. It should be noticeable, just not distracting.

I also thought about de-saturating their colors. 
For example Team 0 nameplates would be gray (still 100% opacity), while colored nameplates would be de-saturated.
This is fairly easy to implement by changing the saturation here:
https://github.com/ddnet/ddnet/blob/b12d481de7bede0d89589758f3c10a4cfed2fadf/src/game/client/components/nameplates.cpp#L115

Similarly scoreboard / server browsers could have gray text instead of white.

**Comment by heinrich5991** [comment]
Status: Not likely to be merged as-is.

The idea is still interesting. CS:GO replaces names of blocked players with the name of their player color, e.g. "Green". Perhaps we could find some names to replace blocked player's names with?

**Comment by Scrumplex** [comment]
Interesting idea! Though we would probably still need something to signalise that it's not actually the real name of the player. Maybe *just an italic font*?

**Comment by Scrumplex** [comment]
Let's discuss this on #4525

**Comment by heinrich5991** [comment]
As is, this seems to highlight foes more than deempasize them. Discussion about this feature happens in #5354. Closing.

**Pull request closed without merging**
