### PR TITLE
add the engine encryption interface

### PR DESCRIPTION
**Pull request by edg-l**
I guess this supersedes https://github.com/ddnet/ddnet/pull/4106

This time this is just an engine interface, it uses a modern encryption library (that @Learath2  often suggested): https://doc.libsodium.org/

The important question is how to store the key pairs, or if to store them at all, would there be a problem with generating a new key pair on every startup?

The next step is to figure out how to share the public keys and then enable a secure channel.

Future possible stuff:
- Encrypted chat
- Accounts?

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by C0D3D3V** [comment]
I do not understand your comment "The nonce doesn't have to be confidential, but it should be used with just one invocation of FillNonce for a particular pair of public and secret keys."

A nonce should be random for every single message, and not be used again. 
This has nothing at all to do with the key pair.

**Comment by edg-l** [comment]
> I do not understand your comment "The nonce doesn't have to be confidential, but it should be used with just one invocation of FillNonce for a particular pair of public and secret keys."
> 
> A nonce should be random for every single message, and not be used again. This has nothing at all to do with the key pair.

I just copied the docs from the libsodium page, but i think you are right

**Comment by edg-l** [comment]
> The nonce doesn't have to be confidential, but it should be used with just one invocation of crypto_box_easy() for a particular pair of public and secret keys.

I actually copied the document wrongly, my bad :D

**Comment by heinrich5991** [comment]
This was an interesting experiment. I think we shouldn't merge it unless we have a need for that encryption, otherwise it might be a bad fit once we actually need some.

If you feel differently, feel free to reopen or ask for a reopen.

**Pull request closed without merging**
