### PR TITLE
Fix GCC 9.2.0 compilation

### PR DESCRIPTION
**Pull request by def-**
src/game/server/ddracechat.cpp:623:39: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]

### CODE REVIEW

**Comment by Learath2** [comment]
Casting a `const char *` to a `char *` is hardly correct. 0.7 seems to have const variants of the whitespace functions, maybe we should use those as well.

**Comment by 12pm** [comment]
oh yeah that would be nice

**Comment by heinrich5991** [comment]
> Casting a `const char *` to a `char *` is hardly correct.

From a pedantic standards point of view, casting between `const` and non-`const` is always OK. Only writing through a `char *` to an object declared as `const char` is forbidden. I agree that it's undesirable to cast from `const` to non-`const`.

**Comment by def-** [comment]
To me this is a deficiency in the type system and adding a differently named const-variant is also a hack, but ok.

**Pull request merged**
