### PR TITLE
Remove unused cl_show_spec_tee config (fixes #2378)

### LINKED ISSUE #2378: cl_show_spec_tee 0 not working (14.0.1)
Title.

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by VxMiMxV** [comment]
So we won't be able to disable spec tee visibility?

**Comment by def-** [comment]
That would be my approach. Why do you want to disable it? I don't think it's disturbing to know where a tee can pop up from at any moment.

**Comment by VxMiMxV** [comment]
I dislike dashed skin idea ~ #2309
It's fine i'll just stick to 14.0

**Comment by heinrich5991** [comment]
You can replace the dashed skin with anything you like. Replace `x_spec.png` with your own skin file.

bors r+

Thanks.

**Comment by VxMiMxV** [comment]
You should read related posts before posting so you understand the context.

> You can replace the dashed skin with anything you like. Replace `x_spec.png` with your own skin file.

I prefer to see peoples custom skins, universal skin for everyone just seems wrong to me.


Removing the ability to toggle  `cl_show_spec_tee` just seemed weird to me since 90% of features have that customizability aspect.

Note: 
You can spare trying to "convince" me by making arguments like

>I don't think it's disturbing to know where a tee can pop up from at any moment

>It'd require code changes

etc.

Just wanted to clear things up.
I won't update the client and we don't need to argue.

**Pull request merged**
