### PR TITLE
Tell new devs not to feel intimidated

### PR DESCRIPTION
**Pull request by def-**
Images by @VoxelDoesCode :
unknown
unknown2

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
bors r+

I should work on my image.

**Comment by Chairn** [comment]
I still don't understand what the fish represents

**Comment by VoxelDoesCode** [comment]
I just have an odd sense of humor...

**Comment by def-** [comment]
> I should work on my image.

I think your image is great. You're the guy who helps people.

**Pull request merged**
