### PR TITLE
Send extended entity info

### PR DESCRIPTION
**Pull request by trml**
For prediction of bullets and moving pickups in switch layer (#3990).

This sends the info in a separate netobject (as proposed in #4102), as an alternative to adding new netobjects/fields for each type individually (projectiles, pickups, etc). Since map items never change, this information would likely only be sent once in the snapshot delta.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
No need to send the layer.

**Comment by trml** [comment]
Layer is currently only used for switch or game layer, so it's not really needed, but I'd rather send a little too much information than too little, if there is a chance if it could ever be needed. (for example, if more layers are added sometime in the future). If it's certain that layer won't be used for anything later it can be removed though.

It would also be possible to add more information here to make this a more general "map item info" netobject. And for example add the entity type to separate things like draggers from guns and laser walls. One possibility could be to use the list in mapitems.h directly, but since that one is mainly used to define the tiles an alternative would perhaps be to make a new list.

**Comment by def-** [comment]
@trml Not sure if you're on Discord or how else to reach you. If you want a free DDNet magnet, send me a Discord message or email with your address.

**Comment by fokkonaut** [comment]
Can we get this for CDoor too? In my mod SSwitchers not only holds NumSwitchers, but also another array for plot doors, which are created separately which would lead to mispredictions. Using this and #4114 it would be possible to properly do that.

**Comment by trml** [comment]
I added another field that would allow to specify the entity class (door, etc), but only added it for pickups and projectiles for now as examples, since this PR is mainly meant as a proposal for the network change.

Adding it for doors would perhaps also belong better in a separate PR related to prediction. @fokkonaut If the entities on your server are created differently from doors in ddnet that could effect the prediction (and the network side) as well, as doors in ddnet don't require this PR for prediction.

**Comment by fokkonaut** [comment]
Doors are created the same way as in DDNet, just for the plot doors on my server, they get created via a different tile with ids starting at 1 again. If I can specify the m_Number for a door, then all would work, because plot doors are another array starting at m_NumSwitchers.

**Comment by Learath2** [comment]
Hm, entity class sounds like a bit redundant. Why did you end up adding it here? Isn't the id enough to figure out the type?

**Comment by trml** [comment]
@Learath2 Having the extra field could make it possible to distinguish between laser/doors/draggers/light/gun, by adding more types like ENTITYCLASS_DRAGGER, or even more spesific types like ENTITYCLASS_DRAGGER_WEAK. The regular netobject for doors/laser/dragger all just get sent as NETOBJTYPE_LASER currently, and don't contain this info. But for pickups and projectiles it is redundant though.

This could potentially be used for predicting draggers, or in case someone at some point wants to make doors (and similar) visually different in the client. The idea was also that it wouldn't cost much to add it, as long as this would be mainly used for map entities. An alternative to this way of doing it would be to add a new netobject for lasers (or for the individual classes), though.

**Comment by Learath2** [comment]
Aha, makes sense. I guess we should name the object more generically. Maybe EntityEx?

**Comment by fokkonaut** [comment]
@Learath2 that sounds good. If it is possible to set m_Number for doors aswell, which with a generic implementation of assigning the EntityEx to a real Entity works fine.

**Comment by trml** [comment]
EntityEx sounds like it matches with the previous extended netobjects, so changed it to that. It would still be possible to add more fields here, but I can't think of any at the moment.

**Comment by fokkonaut** [comment]
Could you add doors while at it? I'm sure predictions for them will come soon, if I have the time I would also look at it.

**Comment by fokkonaut** [comment]
Also, we have an enum ENTTYPE in CGameWorld on the server side, probably also on the client for the prediction. Now that this information made it to the network level, you could add the enum to network.py.

**Comment by Jupeyy** [comment]
@trml What's your opinion on fokkonauts suggestions?

**Comment by trml** [comment]
I can add doors as well. I was perhaps thinking of adding it in a separate pr though, if this gets pulled, since in that case this could potentially be used to send lasers doors in a way that might be more beneficial to prediction.

Also, just to clarify, the idea was that this could be added for more entities in the future (as needed) by adding more types at the end of EntityClasses.

> Also, we have an enum ENTTYPE in CGameWorld on the server side, probably also on the client for the prediction. Now that this information made it to the network level, you could add the enum to network.py.

I'm not sure if I understand, but the gameworld enum already corresponds to the netobject types, and like the netobjects it lacks separate types for doors, draggers, etc. The enum added in this PR could contain information about the class, and also things like subtypes of the same class.

The gameworld enum is also used internally by the server physics for getting/inserting items (and as a side effect the order of the enum affects the order entities are ticked in), so it wouldn't be trivial to change/extend it either.

**Comment by fokkonaut** [comment]
i have separated enum entries for each enttype in gameworld and cant see any negative result with this, since doors arent checked within the door entity itself anyways.

**Comment by trml** [comment]
Yes, for doors it doesn't affect anything, but for other entities it would have side effects if you added them in the wrong order, and that would limit the possibility to extend this to more entities (or their subtypes) in the future.

**Comment by Jupeyy** [comment]
@fokkonaut so is that ok for you?

**Comment by fokkonaut** [comment]
What exactly? Using a separated enum? Sure.

**Comment by Jupeyy** [comment]
> What exactly? Using a separated enum? Sure.

I mean the pr as it is, and doors in a new pr

**Comment by fokkonaut** [comment]
Well, since we have the switchstate in this release it would be good to have this in the next release aswell.

**Comment by Jupeyy** [comment]
merged with #4176

**Pull request closed without merging**
