### PR TITLE
Create codeql-analysis.yaml

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by edg-l** [comment]
Can you explain what this is/does?

**Comment by Learath2** [comment]
It really shocks me that it didn't find anything :D

**Comment by def-** [comment]
I think we need to submit it and have it run as a continual run to get results for the current code state. In PRs it should only find what problems that the PR introduced.

**Comment by heinrich5991** [comment]
Haven't looked at it in-depth, let's try it out.

bors r+

**Pull request merged**
