### PR TITLE
Add New Year season theme by mind and use for 2 days

### PR DESCRIPTION
**Pull request by def-**
Map reduces my FPS from 60 to 53, mind can't optimize it further.

I'd release this as 15.2.5 in 1-2 days ideally with no other new changes in.

screenshot_2020-12-28_14-51-48

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
LGTM,  I'll leave it to @Jupeyy to take a look maybe he can tell us why the performance hit happens

**Review by Learath2 — APPROVED** [review]
LGTM,  I'll leave it to @Jupeyy to take a look maybe he can tell us why the performance hit happens

**Comment by def-** [comment]
This has to be release in 1 day at latest though.

**Comment by Learath2** [comment]
Ah, new year keeps slipping out of my mind...

bors r+

**Pull request merged**
