### PR TITLE
Extend DDNet-Server-Launcher, support DDNet-Server from client in dmg (fixes #4441)

### LINKED ISSUE #4441: Can't run DDNet-Server from main menu on macOS (Website dmg version)
Works when building yourself and works in Steam version

### PR DESCRIPTION
**Pull request by def-**
Screenshot 2021-12-25 at 19 32 08
The old version would just open the file opener immediately which was quite confusing for new users.

Also removed sqlite3 for mac and mysql entirely since they are not needed.
## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by edg-l** [comment]
@Learath2 u are the macos guy maybe you can take a look

**Comment by Learath2** [comment]
I didn't test it but the changes look sane and they are indeed better. LGTM

**Comment by heinrich5991** [comment]
Has conflicts.

**Comment by def-** [comment]
Fixed

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
