### PR TITLE
Switch to simple check symbol for official server

### PR DESCRIPTION
**Pull request by def-**
screenshot-20190319@160225

### CODE REVIEW

**Comment by def-** [comment]
screenshot-20190319@170312

**Comment by def-** [comment]
Made a vote: https://forum.ddnet.tw/viewtopic.php?f=3&t=6783

**Comment by Learath2** [comment]
Maybe a silhouette of the logo to avoid having too many colors?

**Comment by def-** [comment]
Oh well, looks like the vote is pretty clearly against this.

**Pull request closed without merging**
