### PR TITLE
Create traditional_chinese

### PR DESCRIPTION
**Pull request by SiuFuWong**
Add Traditional Chinese language

### CODE REVIEW

**Comment by def-** [comment]
@ACTom @TsFreddie  Mind to review?

**Comment by ACTom** [comment]
No problem

**Comment by def-** [comment]
Thanks for the PR, thanks for the reviews!

**Comment by def-** [comment]
I believe this wasn't tested. Misses the index.txt entry. Mind adding one @SiuFuWong, @TsFreddie, @ACTom ?

**Comment by ACTom** [comment]
Sorry for this,I just only review the content.
It need to add 繁體中文 to index.txt and rename traditional_chinese to traditional_chinese.txt

**Comment by def-** [comment]
Thanks, done.

**Comment by SiuFuWong** [comment]
Thanks

**Pull request merged**
