### PR TITLE
Use std::clamp

### PR DESCRIPTION
**Pull request by def-**
Not sure if we want to, there are some easy functions like this we could
take from stdlib now

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
The disadvantage of this is that we move further from Vanilla. Not sure if it should be submitted.

**Comment by C0D3D3V** [comment]
Does Vanilla also use C++11? I can make a PR on vanilla so that they also use the std functions xD

**Comment by def-** [comment]
std::clamp is C++17

**Comment by def-** [comment]
Yes, we could just have a type def for clamp = std::clamp if we want to keep the diff to Vanilla down. But maybe this is a good moment for a decision if we want to do this or keep going different ways from Vanilla.

**Comment by C0D3D3V** [comment]
I've had the feeling for a long time that the projects are coming apart. Even if we have always tried to maintain a certain connection (especially because we are the ones who have built in the compatibility layer...). But for me we can make as many changes to the code as necessary to make the code more maintainable and consistent. We can still merge the changes into vanilla if they like it.

Since we also used the prefix "std::" everywhere instead of making a type def, I would stick to it. (Even if I personally find a type def nicer, ... but it should be at least consistent in the code).

**Comment by Jupeyy** [comment]
Are we still at this discussion xd just ignore vanilla until it gets active maintainers again

**Comment by def-** [comment]
Well, some of us have been making changes moving us away from vanilla, but some others like @ChillerDragon  try to get us closer again, so would be good to decide on a direction

**Comment by Jupeyy** [comment]
Better code will profit thousands of users and new contributors

More vanilla won't give us more anything.
Pretty much only robyte added good stuff to vanilla and these things from him are not really portable anyway bcs the diff is too huge anyway

**Comment by ChillerDragon** [comment]
I actually do not mind a upstream diff as long as we stay protocol compatible. If further code diffs decrease the probability of updating the client to 0.7 thats bad imo.

**Comment by Jupeyy** [comment]
I dunno. What does 0.7 protocol add? Chat encryption?  Quic? Any cleanup(maybe a tiny bit)? Proper support for mod specific packets? Maybe it's better to start thinking if it's not nicer to drop vanilla support completely and write cleaner code

**Comment by C0D3D3V** [comment]
We can switch to the 0.7 protocol even without being close to the 0.7 code base.  I see no problem in making our code better and still having goals like implementing the 0.7 protocol.

**Comment by ChillerDragon** [comment]
> I dunno. What does 0.7 protocol add? Chat encryption? Quic? Any cleanup(maybe a tiny bit)? Proper support for mod specific packets? Maybe it's better to start thinking if it's not nicer to drop vanilla support completely and write cleaner code

The 0.7 protocol has a pvp community around it. Many pro ctf players use the vanilla client and play on vanilla servers. So 0.7 would allow ddnet players to play standard teeworlds gametypes. Also teeworlds is still a source for new players.

> We can switch to the 0.7 protocol even without being close to the 0.7 code base. I see no problem in making our code better and still having goals like implementing the 0.7 protocol.

Sure. As long someone does it I am fine with it. But it will make copying code from vanilla harder. But yes you are right one does not need to copy code to implement a protocol.

**Comment by Jupeyy** [comment]
> The 0.7 protocol has a pvp community around it. Many pro ctf players use the vanilla client and play on vanilla servers. So 0.7 would allow ddnet players to play standard teeworlds gametypes. Also teeworlds is still a source for new players.

if thats the main problem i'll gladly port ictf and the standard vanilla gametypes, i have to port fng then anyway

**Comment by edg-l** [comment]
I'm all in for getting further away from vanilla, I'm also all in for breaking the protocol if it means improvements.

Teeworlds 0.7 is essentially dead, lets face it.

image

image


I don't know why we still cater to it. It's just holding us back.

**Comment by Chairn** [comment]
Maybe we should vote?

**Comment by heinrich5991** [comment]
I think the simpler change would be `using std::clamp` in the relevant header file, I'd prefer that.

**Comment by def-** [comment]
Done

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
