### PR TITLE
Overload ui SplitMid functions with tripple split

### PR DESCRIPTION
**Pull request by ChillerDragon**
tripple_hsplitmid_spacing70
tripple_vsplitmid_spacing10
tripple_vsplitmid
tripple_hsplitmid

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Looks generally good.

What's the use case?

I generally don't like overloading. In this case, the name doesn't have anything to do with the function anymore, you're not splitting it in the middle. Not sure what a good name would be.

**Comment by ChillerDragon** [comment]
> What's the use case?

The current code works fine for splitting stuff in equally sized chunks if you have multiples of two. Like 2 buttons or 4 buttons. But 3 or 6 is always a bit messy and is currently done with a bunch of left and right splits and sometimes even hardcodet sizes.

I need it for example for https://github.com/ddnet/ddnet/pull/5949 while looking at the alignment code of the buttons in upstream I noticed that I did not like its complexity.

image

**Comment by archimede67** [comment]
What about a multi split function that takes N rects and splits them equally? So we aren't limited to 2 or 3.

**Comment by ChillerDragon** [comment]
> What about a multi split function that takes N rects and splits them equally? So we aren't limited to 2 or 3.

2 easily scales to 4 and 8. While 3 scales to 6 and 9. So mostly 5 is missing. Yea would be nice to also support 5 but not sure if anyone will ever need it and if its worth the effort.

**Review by Robyt3 — CHANGES_REQUESTED** [review]
I don't think the spacing should be applied outside. That would be different than existing mid-split functions, which only add spacing inside. If you need outside spacing then you can do a margin before the split. I think that's cleaner than the opposite, having to do a negative margin before the split if you don't want the spacing outside.

We currently don't add any spacing outside when splitting an element into 3, so I don't think it makes sense to add this solely for 0.7 support. I'm fine with merging #5949 before the 0.7 skin menu is reworked completely, so making that (somewhat temporary) code easier to write doesn't seem like a priority to me.

I'd also prefer adding only a general function to split into N rects, instead of adding multiple functions for every case, if we want to add something like this.

If we add something like this, then it should also be used for existing code where possible. With a quick regex search for `VSplitLeft.*?w / 3` you can find 3 locations where this function could be used (and some false positives). There are more locations where we split into N different rects, e.g. the tabs in the settings, but those are implemented using loops so a function accepting N rects wouldn't be useful anywhere else AFAICT.

Also, the ASCII art looks cool, but it will not render correctly in doxygen unless you surround it with `@verbatim` and `@endverbatim`.

**Comment by ChillerDragon** [comment]
> I don't think the spacing should be applied outside.

I might have skipped too much geometry class. But is that even possible while accepting a spacing from the user and keeping everything even and all rects at the same size?

draw


1. This is what I did.
    :white_check_mark: User given spacing is applied between all rects
    :white_check_mark: Distance to parent is the same on both sides
    :white_check_mark: All rects have the same size
    :x: The inner rects do not touch the parent
2. :white_check_mark: User given spacing is applied between all rects
    :white_check_mark: Distance to parent is the same on both sides
    :x: All rects have the same size
    :white_check_mark: The inner rects do not touch the parent
3. :x: User given spacing is applied between all rects
    :white_check_mark: Distance to parent is the same on both sides
    :white_check_mark: All rects have the same size
    :white_check_mark: The inner rects do not touch the parent
4. :white_check_mark: User given spacing is applied between all rects
    :x: Distance to parent is the same on both sides
    :white_check_mark: All rects have the same size
    :x: The inner rects do not touch the parent

> Also, the ASCII art looks cool, but it will not render correctly in doxygen unless you surround it with ``@verbatim`` and ``@endverbatim``.

Done.

image


> We currently don't add any spacing outside when splitting an element into 3, so I don't think it makes sense to add this solely for 0.7 support.

I will use it in that very scenario. But this is not for 0.7 support. This is to have an easier way to quickly align 3 buttons/columns in ddnet in general.

> If we add something like this, then it should also be used for existing code where possible.

I would like to avoid useless code diffs or touch working code that might break. It was more intended for new code. But if that is a requirement for the merge sure I can give it a go.

> That would be different than existing mid-split functions, which only add spacing inside.

> I generally don't like overloading. In this case, the name doesn't have anything to do with the function anymore, you're not splitting it in the middle. Not sure what a good name would be.

I renamed it to HSpaceAround and VSpaceAround people with CSS background should feel comfortable with those names.

https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

> I'd also prefer adding only a general function to split into N rects, instead of adding multiple functions for every case, if we want to add something like this.

Sure that would be nice but I don't think that it conflicts with this pr. Imo extending double split with tripple split is a nice addition. If one also wants n split they should open their pr with it.

**Comment by Robyt3** [comment]
> I might have skipped too much geometry class. But is that even possible while accepting a spacing from the user and keeping everything even and all rects at the same size?

Choice 3 is how I would expect this function to work based on how all other functions work. To instead get choice 1, you first do a margin on the whole rect and then the choice 3 split.

> > If we add something like this, then it should also be used for existing code where possible.

> I would like to avoid useless code diffs or touch working code that might break. It was more intended for new code. But if that is a requirement for the merge sure I can give it a go.

I'd prefer you try and break existing code to show that this PR works.

> > I'd also prefer adding only a general function to split into N rects, instead of adding multiple functions for every case, if we want to add something like this.

> Sure that would be nice but I don't think that it conflicts with this pr. Imo extending double split with tripple split is a nice addition. If one also wants n split they should open their pr with it.

I'm just not very convinced that the 3-way-split is generally useful, but if you think that it's useful enough like this then we can add it.

> I renamed it to HSpaceAround and VSpaceAround people with CSS background should feel comfortable with those names.

Sorry for more nitpicking, but when reading the code, "H space around" reads like "put a H margin/space around it" to me, which doesn't make it clear what this function does. I don't have any concrete alternative right now, but I think `Split` still belongs in the name, because you are splitting something. It's the "mid" part that

**Comment by ChillerDragon** [comment]
> Choice 3 is how I would expect this function to work based on how all other functions work. To instead get choice 1, you first do a margin on the whole rect and then the choice 3 split.

How is 3 supposed to work? If the user requests spacing 2.f but that would result in case 2. or 4. unless the spacing is changed to 3.f. If we remove the spacing argument from the method signature how much spacing should it use? What if the user wants no spacing at all?

**Comment by ChillerDragon** [comment]
Okay I am not interested in arguing anymore here. This feature is clearly not wanted. I thought it was a nice addition. I do not want to keep discussing here I do not need it that bad to spend more time on it.

**Pull request closed without merging**
