### PR TITLE
Revert "Build our own drmingw with mingw"

### PR DESCRIPTION
**Pull request by def-**
Pastoer reported on Discord that this causes warnings when closing client:
Screenshot 2022-06-22 at 18 04 01

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I don't know what this is about, but reverts sound safe.

bors r+

**Comment by def-** [comment]
Outdated Windows 7 failed to start client with DrMingw, so I built our own version. Now our own version is opening dialog windows when closing client. Only one person had problems with old Windows 7, and it was resolved after enabling security updates.

**Comment by C0D3D3V** [comment]
The popup message should only pop up on a crash (In this case a crash on closing the client). Because it asks for debug symbols...
The only article I found for this popup, is this german forum:
https://www.hilfdirselbst.ch/foren/Microsoft_Internet_Symbol_Store_-_Was_ist_das_P258443.html

**Comment by def-** [comment]
Yes, but we didn't get this popup before, which is more convenient.

**Comment by heinrich5991** [comment]
This probably needs another force-push. Submodules are annoying that way. Let's try it anyways:

bors r+

**Pull request merged**
