### PR TITLE
Set libnotify icon

### PR DESCRIPTION
**Pull request by yangfl**

### CODE REVIEW

**Comment by def-** [comment]
Where is the icon file loaded from?

**Comment by heinrich5991** [comment]
Presumably from here:

https://github.com/ddnet/ddnet/blob/049e7c80cf6a17e688724cd679931bc57a8b067f/CMakeLists.txt#L2322-L2324

However, I don't know what happens for the Steam build when the icon is not present. Needs some testing.

**Comment by def-** [comment]
@yangfl can you please check if this still works in Steam build with icon missing?

**Comment by yangfl** [comment]
`notify_notification_new` also accepts icon filename as input. But after some searches I found it's hard to retrive the real path from `IStorage`, so I gave up and let's just take care of system icons.

And `notify_notification_new` is very permissive even if you pass garabge as `icon`, in that case an old plain notification will still be shown (just as what is look like now).

**Pull request merged**
