### PR TITLE
Show health and armor of all players to all spectators

### PR DESCRIPTION
**Pull request by ChillerDragon**
Untested. @gerdoe-jr needs this for his custom client on ddnet-insta servers.

image

### CODE REVIEW

**Comment by heinrich5991** [comment]
This does not appear to be related to DDNet.

**Comment by gerdoe-jr** [comment]
@heinrich5991, can server send health and armor of all players by default? It doesn't make codebase any bigger or messier, but will help with this issue

**Comment by heinrich5991** [comment]
In general, please fix the issue you want to fix not in DDNet, but in the project you use, ddnet-insta.

Health/armor isn't really used in DDNet, so a better course of action for DDNet would be to remove the member variables entirely and compute them on-the-fly in the snap method.

**Comment by gerdoe-jr** [comment]
> so a better course of action for DDNet would be to remove the member variables entirely

Theoretical ideal mod-friendly interface of CCharacter is quite opposite to this IMHO, it should have getters at least

**Pull request closed without merging**
