### PR TITLE
Add `/join [player]`

### LINKED ISSUE #3878: Add /team first ! To create teams faster.
So this would be a chat command that put you in the first empty team available, so u delete the situation of when u write /team 1 and it say its locked, then /team 2 and its lock, etc and directly put u in first team number available. I hope its clear ^^"
(/team first or /team random or /team empty or /team -1 or whatever u want)

### PR DESCRIPTION
**Pull request by furo321**
This adds `/join r[player]` which can be used to join a specified player's team.

Closes #3878

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I like `/join <playername>`. I think `/accept` might be not so nice because you might be invited by multiple teams. What about printing `/join <the person who invited>` instead?

**Comment by furo321** [comment]
Yeah, it doesn't work very well if you're invited by multiple teams. Also wouldn't `Use /team %d to join` be better in this case?

**Comment by heinrich5991** [comment]
Oh yea, that would work as well.

**Comment by furo321** [comment]
I removed `/accept` and updated the invite text.

image

**Review by def- — APPROVED** [review]

**Pull request merged**
