### PR TITLE
Add new renderer(as streamed vertices) for editor

### PR DESCRIPTION
**Pull request by Jupeyy**
Does not improve performance in editor!

### CODE REVIEW

**Comment by def-** [comment]
Why do we want it then, because it looks closer to ingame, right?

**Comment by Jupeyy** [comment]
Yes

**Comment by def-** [comment]
Tested it a bit, seems to work fine. Will wait for some more tests before submitting.

**Comment by def-** [comment]
No one else tested, so let's add this in for the RC. Somehow we're getting lots of large features quickly again, faster than I expected. That's a great problem to have :)

**Pull request merged**
