### PR TITLE
Implement context for translations (largely taken from Teeworlds)

### PR DESCRIPTION
**Pull request by def-**
Missing: scripts/languages doesn't work yet, but the context can be
added manually, see german.txt for an example.

### CODE REVIEW

**Comment by TsFreddie** [comment]
Teeworlds string search might be broken. See https://github.com/teeworlds/teeworlds/pull/2733

**Comment by def-** [comment]
I thought so too initially, but it actually seems to work reliably (at least from what I tested).

**Comment by TsFreddie** [comment]
French and Chinese on teeworlds wasn't working properly before.

**Comment by def-** [comment]
Finished now, ready for review.

**Comment by Learath2** [comment]
LGTM

bors r+

**Pull request merged**
