### PR TITLE
Version 15.9

### PR DESCRIPTION
**Pull request by def-**
DDNet 15.9 is supposed to release in 1 week, assuming no bad bugs are found. Please test the Release Candidate to prevent problems being only discovered after release. Report bugs in the #bugs channel on DDNet Discord or directly on Github:
icons
- Windows 32bit: https://ddnet.tw/downloads/DDNet-15.9-rc3-win32.zip
- Windows 64bit: https://ddnet.tw/downloads/DDNet-15.9-rc3-win64.zip
- Linux x86: https://ddnet.tw/downloads/DDNet-15.9-rc3-linux_x86.tar.xz
- Linux x86_64: https://ddnet.tw/downloads/DDNet-15.9-rc3-linux_x86_64.tar.xz
- Mac OS X: https://ddnet.tw/downloads/DDNet-15.9-rc3-macos.dmg

You can also test the release candidate in Steam by clicking on Settings -> Properties -> Betas and opting into the Release Candidates. This will automatically update you to a new release candidate when it is available, and to the next release when no new candidate is available. So you can always leave this setting enabled to help us test new releases earlier.

The following changes are included, ideally test their behaviour specifically. But just playing as you do normally also helps:

- [Server] **Live freeze tiles** (cannot move or jump, but can use hook and weapons) [GiuCcc]
- [Server] **Add teleport/tp chat command to teleport yourself to another player or spectated location** (requires /practice)
- [Client] **Add new icons and macOS installer graphics** [Ravie]
- [Client] Add windowed fullscreen mode on Windows [Jupeyy]
- [Client] Support 128 players in server browser [fokkonaut]
- [Client] Adjustable prediction margin (cl_prediction_margin) [trml]
- [Client] Improve projectile prediction [trml]
- [Client] Use power button to quit (hopefully more clear)
- [Client] Implement "reset" command to reset specific config values to default value
- [Client] Add cl_port, cl_dummy_port, cl_contact_port for ISPs that throttle specific ports
- [Client] Remove compatible version filter [heinrich5991]
- [Client] Display more relevant version numbers on command line
- [Client] Fix bullet rendered through walls [trml]
- [Client] Fix ARM-specific crash in macOS when moving screen [Jupeyy]
- [Client] Fix console line offsets when resizing [Jupeyy]
- [Client] Fix changing resolution in fullscreen [Jupeyy]
- [Client] Improved double click handling [Robyt3]
- [Client] Reduce default ambient volume to 30
- [Client] Update score HUD immediately when switching dummy
- [Client] Allow multiple commands when adding vote in UI
- [Client] Allow "zoom" command to take smaller/larger values
- [Client] Improve super prediction
- [Client] Improve preformance when listing directories [Robyt3]
- [Client] Lower chance of losing config files [heinrich5991]
- [Client] Explicitly disable notch area on Macbook Pro for fullscreen
- [Editor] Support enter and escape keys in editor when confirming save
- [Editor] Don't react to server settings shortcuts when dialog is open
- [Server] 255 jump tile acts as no double jump [heinrich5991]
- [Server] Fail database queries faster [Zwelf]
- [Server] Improve database writes during shutdown and bad network [Zwelf]
- [Server] Extend and fix DDNet Server launcher on macOS
- [Server] Also switch rescue tees when swapping
- [Server] Implement sv_min_team_size to prevent too small teams counting as team finishes
- [Server] Default players to being AFK when joining
- [Server] Fix warnings to only warn every 3 seconds when touching start line
- [Server] Reload map when changing sv_sixup [Robyt3]
- [Client+Server] Handle signals (SIGINT, SIGTERM) [Robyt3]
- [Client+Server] Fix lots of undefined behavior [Robyt3]

### CODE REVIEW

**Comment by murpii** [comment]
Double click speed is to fast, (e.g by selecting demos)
Prediction margin doesn't save after relaunch
minor typo in: [Editor] Don't react to server settings _shorctus_ when dialog is open

**Comment by def-** [comment]
> Double click speed is to fast, (e.g by selecting demos)

@Robyt3 can this be changed to be the same as before?

>  Prediction margin doesn't save after relaunch

I think this is intentional.Right @trml?

>  minor typo in: [Editor] Don't react to server settings shorctus when dialog is open

Thanks, fixed.

**Comment by murpii** [comment]
> > minor typo in: [Editor] Don't react to server settings shorctus when dialog is open
> 
> Thanks, fixed.

noooot quite there yet :D

**Comment by trml** [comment]
> > Prediction margin doesn't save after relaunch
> 
> I think this is intentional.Right @trml?

Originally I set it not to not be saved since I wasn't sure if it would end up being confusing if you temporarily set it at a high value (e.g. 100-200) and forgot about it later (and since there is no gui setting to indicate it). But I would be fine with making it a saved config variable, and for some use cases like having it permanently at a low value (less than 10) that could be more useful.

**Comment by l-ouis** [comment]
was live freeze added to entities yet?

**Comment by heinrich5991** [comment]
No.

**Comment by l-ouis** [comment]
https://media.discordapp.net/attachments/932210366048501800/932568744197246976/unknown.png

by soapy sandwich, seems good for the mapping entities

still need one for in game entities

**Comment by def-** [comment]
ok, I'll add that.

**Comment by def-** [comment]
> https://media.discordapp.net/attachments/932210366048501800/932568744197246976/unknown.png
> 
> by soapy sandwich, seems good for the mapping entities
> 
> still need one for in game entities

There are 3 images but only 2 entities.

**Comment by murpii** [comment]
Entity one and three are just for comparison. The main difference is the eyes aren't closed

**Comment by def-** [comment]
Then we are still missing an entity image for livefreeze off. and also the image is missing transparency.

**Comment by l-ouis** [comment]
i believe it was a concept sketch, i will ask soapy sandwich if he can finish it / provide an svg, etc.

**Pull request closed without merging**
