### PR TITLE
RFC: Check implicit int <-> bool conversions

### PR DESCRIPTION
**Pull request by def-**
I don't like it. Other thoughts?

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
Well, implicit int to bool is neither unspecified nor undefined, so why bother?

**Comment by Robyt3** [comment]
The implicit bool -> int conversions are weird and should maybe be refactored, but the conversion itself is well-defined. I only took a cursory look but these conversions are probably the minority.

Some implicit int -> bool conversions could be fixed by making variables or parameters type bool instead.

**Comment by Learath2** [comment]
I don't like it. The conversion is well defined and whether we like it or not `int`s have been abused as `bool`s and used as bad alternatives for `enum`s for decades.

We could look through our codebase and get rid of uses like these but it definitely can't be done for the libraries we use. So at the very least a blanket approach like this doesn't make much sense to me.

**Comment by C0D3D3V** [comment]
xD I would expect that it converts IsReachable to a bool, instead of making a static cast. But I think that is not possible automaticly
grafik

**Pull request closed without merging**
