### PR TITLE
Init curl first, then call curl_version_info

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Jupeyy** [comment]
Ok update:
i tested libcurl release form their website, and it showed the same overflow warning as our libcurl.dll(EVEN with this patch)

then i tried their latest github code, in debug i probs get a false positive, in release mode i get nothing(however, i built that lib with VS)
```
> 
> Error #21: UNINITIALIZED READ: reading 0x0000006d620fee40-0x0000006d620fee44 4 byte(s)
> # 0 ucrtbased.dll!strpbrk                +0x1fd    (0x00007ffc77b0412d <ucrtbased.dll+0xc412d>)
> # 1 ucrtbased.dll!mbspbrk_l              +0x33     (0x00007ffc77a66e34 <ucrtbased.dll+0x26e34>)
> # 2 libcurl-d.dll!_tcspbrk                [c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt\tchar.h:1579]
> # 3 libcurl-d.dll!Curl_load_library       [c:\users\user\desktop\teeworlds\curl-master\lib\system_win32.c:193]
> # 4 libcurl-d.dll!Curl_win32_init         [c:\users\user\desktop\teeworlds\curl-master\lib\system_win32.c:94]
> # 5 libcurl-d.dll!global_init             [c:\users\user\desktop\teeworlds\curl-master\lib\easy.c:165]
> # 6 libcurl-d.dll!curl_global_init        [c:\users\user\desktop\teeworlds\curl-master\lib\easy.c:218]
> # 7 HttpInit                              [c:\users\user\desktop\teeworlds\ddnet\src\engine\client\http.cpp:44]
> # 8 CClient::InitInterfaces               [c:\users\user\desktop\teeworlds\ddnet\src\engine\client\client.cpp:2956]
> # 9 main                                  [c:\users\user\desktop\teeworlds\ddnet\src\engine\client\client.cpp:4253]
```

Sadly i cannot really test anything more, bcs dr. memory crashes internally directly at the start.
image

So if someone else wants to test on windows

**Comment by Learath2** [comment]
This is a good idea, eventhough curl doesn't require it, it could in the future the way the documentation for this is worded.

> This function must be called at least once within a program (a program is all the code that shares a memory space) before the program calls any other function in libcurl.

bors r+

**Comment by def-** [comment]
Maybe the Dr. Memory is a false positive then? I don't see what else we could be doing wrong.

**Comment by Jupeyy** [comment]
Idc, but as i said, compiling that lib myself didnt show anything

**Pull request merged**
