### PR TITLE
Various fixes for server demo recording and playback

### LINKED ISSUE #5362: Unable to play demo recorded by the server
DDNet version 16.1
Architecture win64

How I recorded this demo:
1. Set sv_player_demo_record 1 in data/autoexec_server.cfg
2. Start server
3. Joined the server and finished the map
4. Got file named "everything_too fat_ 0.68.demo"

Download demo - https://drive.google.com/file/d/1jNx3TdkbsWOuCjU-BWOzfe8hML6U-vN5/view?usp=sharing

Client log when I try to play this demo(nothing happens instead of little screen glitch):

image

Server log:

[2022-06-06 13:18:49][engine]: running on windows-win64-amd64
[2022-06-06 13:18:49][engine]: arch is little endian
[2022-06-06 13:18:49][storage]: added path '$USERDIR' ('C:\Users\ricov\AppData\Roaming/Teeworlds')
[2022-06-06 13:18:49][storage]: added path '$DATADIR' ('data')
[2022-06-06 13:18:49][storage]: added path '$CURRENTDIR' ('C:\Users\ricov\Desktop\DDNet-16.1-win64')
[2022-06-06 13:18:49][host_lookup]: host='localhost' port=0 1
[2022-06-06 13:18:49][host_lookup]: host='localhost' port=0 2
[2022-06-06 13:18:49][console]: executing 'autoexec_server.cfg'
[2022-06-06 13:18:49][server]: added maps to votes
[2022-06-06 13:18:49][console]: moderator access for 'left' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'left' is now enabled
[2022-06-06 13:18:49][console]: user access for 'left' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'right' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'right' is now enabled
[2022-06-06 13:18:49][console]: user access for 'right' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'up' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'up' is now enabled
[2022-06-06 13:18:49][console]: user access for 'up' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'down' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'down' is now enabled
[2022-06-06 13:18:49][console]: user access for 'down' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'super' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'super' is now enabled
[2022-06-06 13:18:49][console]: user access for 'super' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unsuper' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unsuper' is now enabled
[2022-06-06 13:18:49][console]: user access for 'unsuper' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'tele' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'tele' is now enabled
[2022-06-06 13:18:49][console]: user access for 'tele' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'totele' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'totele' is now enabled
[2022-06-06 13:18:49][console]: user access for 'totele' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'totelecp' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'totelecp' is now enabled
[2022-06-06 13:18:49][console]: user access for 'totelecp' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'logout' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'logout' is now enabled
[2022-06-06 13:18:49][console]: user access for 'logout' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'ninja' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'ninja' is now enabled
[2022-06-06 13:18:49][console]: user access for 'ninja' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'grenade' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'grenade' is now enabled
[2022-06-06 13:18:49][console]: user access for 'grenade' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'shotgun' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'shotgun' is now enabled
[2022-06-06 13:18:49][console]: user access for 'shotgun' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'laser' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'laser' is now enabled
[2022-06-06 13:18:49][console]: user access for 'laser' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'weapons' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'weapons' is now enabled
[2022-06-06 13:18:49][console]: user access for 'weapons' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unweapons' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unweapons' is now enabled
[2022-06-06 13:18:49][console]: user access for 'unweapons' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unlaser' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unlaser' is now enabled
[2022-06-06 13:18:49][console]: user access for 'unlaser' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unshotgun' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unshotgun' is now enabled
[2022-06-06 13:18:49][console]: user access for 'unshotgun' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'ungrenade' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'ungrenade' is now enabled
[2022-06-06 13:18:49][console]: user access for 'ungrenade' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unsolo' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unsolo' is now enabled
[2022-06-06 13:18:49][console]: user access for 'unsolo' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'undeep' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'undeep' is now enabled
[2022-06-06 13:18:49][console]: user access for 'undeep' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'status' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'status' is now enabled
[2022-06-06 13:18:49][console]: user access for 'status' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'ban' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'ban' is now disabled
[2022-06-06 13:18:49][console]: user access for 'ban' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unban' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unban' is now disabled
[2022-06-06 13:18:49][console]: user access for 'unban' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'ban_range' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'ban_range' is now disabled
[2022-06-06 13:18:49][console]: user access for 'ban_range' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unban_range' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unban_range' is now disabled
[2022-06-06 13:18:49][console]: user access for 'unban_range' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'unban_all' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'unban_all' is now disabled
[2022-06-06 13:18:49][console]: user access for 'unban_all' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'bans' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'bans' is now disabled
[2022-06-06 13:18:49][console]: user access for 'bans' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'bans_save' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'bans_save' is now disabled
[2022-06-06 13:18:49][console]: user access for 'bans_save' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'kick' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'kick' is now disabled
[2022-06-06 13:18:49][console]: user access for 'kick' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'force_vote' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'force_vote' is now disabled
[2022-06-06 13:18:49][console]: user access for 'force_vote' is now disabled
[2022-06-06 13:18:49][console]: moderator access for 'moderate' is now enabled
[2022-06-06 13:18:49][console]: helper access for 'moderate' is now disabled
[2022-06-06 13:18:49][console]: user access for 'moderate' is now disabled
[2022-06-06 13:18:49][console]: failed to open 'myServerconfig.cfg'
[2022-06-06 13:18:49][server]: starting...
[2022-06-06 13:18:49][datafile]: loading. filename='maps/everything.map'
[2022-06-06 13:18:49][datafile]: allocsize=1152
[2022-06-06 13:18:49][datafile]: readsize=920
[2022-06-06 13:18:49][datafile]: swaplen=940
[2022-06-06 13:18:49][datafile]: item_size=736
[2022-06-06 13:18:49][datafile]: loading done. datafile='maps/everything.map'
[2022-06-06 13:18:49][server]: maps/everything.map sha256 is 2dc0b4d97898974af5c82606a6d80ec7732dd559fed5ac64105e15729c3220c4
[2022-06-06 13:18:49][sixup]: couldn't load map maps7/everything.map
[2022-06-06 13:18:49][sixup]: disabling 0.7 compatibility
[2022-06-06 13:18:49][socket]: Setting TOS on ipv6 failed: 2
[2022-06-06 13:18:49][server]: server name is 'Always working test server'
[2022-06-06 13:18:49][datafile]: loading data index=1 size=186 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=2 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=4 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=6 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=8 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=5 size=42 uncompressed=5000
[2022-06-06 13:18:49][datafile]: loading data index=9 size=41 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=7 size=28 uncompressed=5000
[2022-06-06 13:18:49][datafile]: loading data index=3 size=39 uncompressed=10000
[2022-06-06 13:18:49][server]: version 16.1 on win64 amd64
[2022-06-06 13:18:49][server]: +-------------------------+
[2022-06-06 13:18:49][server]: | rcon password: 'MGFL4K' |
[2022-06-06 13:18:49][server]: +-------------------------+
[2022-06-06 13:18:49][datafile]: loading. filename='maps/everything.map'
[2022-06-06 13:18:49][datafile]: allocsize=1152
[2022-06-06 13:18:49][datafile]: readsize=920
[2022-06-06 13:18:49][datafile]: swaplen=940
[2022-06-06 13:18:49][datafile]: item_size=736
[2022-06-06 13:18:49][datafile]: loading done. datafile='maps/everything.map'
[2022-06-06 13:18:49][server]: maps/everything.map sha256 is 2dc0b4d97898974af5c82606a6d80ec7732dd559fed5ac64105e15729c3220c4
[2022-06-06 13:18:49][datafile]: loading data index=1 size=186 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=2 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=4 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=6 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=8 size=33 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=5 size=42 uncompressed=5000
[2022-06-06 13:18:49][datafile]: loading data index=9 size=41 uncompressed=10000
[2022-06-06 13:18:49][datafile]: loading data index=7 size=28 uncompressed=5000
[2022-06-06 13:18:49][datafile]: loading data index=3 size=39 uncompressed=10000
[2022-06-06 13:18:49][sql]: load best time done on read database 0
[2022-06-06 13:18:49][sql]: load best time done on read database 0
[2022-06-06 13:18:54][server]: player is ready. ClientID=0 addr=<{192.168.56.1:8027}> secure=yes
[2022-06-06 13:18:54][server]: player has entered the game. ClientID=0 addr=<{192.168.56.1:8027}> sixup=0
[2022-06-06 13:18:54][game]: team_join player='0:too fat' team=0
[2022-06-06 13:18:54][chat]: *** 'too fat' entered and joined the game
[2022-06-06 13:18:54][sql]: load player data done on read database 0
[2022-06-06 13:18:54][ddnet]: cid=0 version=16010
[2022-06-06 13:18:54][demo_recorder]: Recording to 'demos/everything_8310_0_tmp.demo'
[2022-06-06 13:18:57][chat-command]: 0 used /timeout 3SBT4PPNWKRfW9VY
[2022-06-06 13:18:59][chat]: *** too fat finished in: 0 minute(s)  0.68 second(s)
[2022-06-06 13:18:59][demo_recorder]: Stopped recording
[2022-06-06 13:18:59][sql]: SQLite statement: INSERT OR IGNORE INTO record_race(        Map, Name, Timestamp, Time, Server,     cp1, cp2, cp3, cp4, cp5, cp6, cp7, cp8, cp9, cp10, cp11, cp12, cp13,    cp14, cp15, cp16, cp17, cp18, cp19, cp20, cp21, cp22, cp23, cp24, cp25,         GameID, DDNet7) VALUES ('everything', 'too fat', DATETIME('2022-06-06 13:18:59', 'utc'), 0.68, 'UNK',   0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,   0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,   0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00,       'b98096b3-ac24-49f6-8a0c-0d50a36e99a4', 0)
[2022-06-06 13:18:59][sql]: save score done on write database 0

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #5362.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [X] Tested in combination with possibly related configuration options
- [X] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Could you add an integration test for demo recording and then play it back in the client?

**Comment by Robyt3** [comment]
> Could you add an integration test for demo recording and then play it back in the client?

Should be possible. I can try tomorrow.

**Comment by Robyt3** [comment]
I added normal client and server demos in the integration test. Auto demos are more complicated due to the filename being dependent on the finish time.

**Comment by def-** [comment]
Cool, thanks
bors r+
We might have to split up integration test into multiple soon.

**Pull request merged**
