### PR TITLE
Fix ctrl+shift+d moving tee (fixes #2930)

### LINKED ISSUE #2930: "ctrl + shift + d" bind is moving tee again
"ctrl + shift + d" bind is moving tee again ^

### PR DESCRIPTION
**Pull request by def-**
@plsplsplslol ok from your side?

### CODE REVIEW

**Comment by def-** [comment]
Why do we even skip modifiers for +xxx binds btw?

**Comment by heinrich5991** [comment]
I don't know why we skip modifiers for +xxx binds.

@Learath2 Can you think of bad side effects this has?

**Comment by Learath2** [comment]
@def- && @heinrich5991 initially I tried to remove that but then I quickly figured out why Dune added it in the first place. It's rather tough to define the behaviour of such chords. What constitutes a key up? What constitutes a key down?

It's one of those things that are trivial to talk about but really hard to put it in simple logic.

**Comment by def-** [comment]
Then let's keep skipping them. PR is still ready.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
