### PR TITLE
Fix killmessages might drop text container indices, if a killmsg was invalid

### LINKED ISSUE #5143: Crash on alt-tab with OpenGL 3.3 / Vulkan
```
[2022-05-17 20:06:28][datafile]: loading done. datafile='downloadedmaps/RedCastle2_de71ee62.map'
[2022-05-17 20:06:28][client]: loaded map 'downloadedmaps/RedCastle2_de71ee62.map'
[2022-05-17 20:06:28][client/network]: loading done
[2022-05-17 20:06:28][textrender]: Found non empty text container with index 992
[2022-05-17 20:06:28][assert]: /home/deen/isos/ddnet/ddnet-source/src/engine/client/text.cpp(1912): text container was not empty
```
Doesn't happen with OpenGL 3.0, reported by Nice on Discord

### PR DESCRIPTION
**Pull request by Jupeyy**
Kill is a temporary variable, that's why the indices were dropped without notice

fixes #5143

also reverted the hacks.
i guess we can keep 493f47515c556472f3d009e18b47655e2f8ba9fb for now, it at least gives a hint to find such stuff

_**we should also release a new patch version with this**_

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Should we just keep the debugging stuff? I'd prefer if we know about issues with future text container usage sooner.

**Comment by Jupeyy** [comment]
i dunno but at least [b3e0633](https://github.com/ddnet/ddnet/pull/6698/commits/b3e0633ef8921e9aa2b82ceb7adc9317aabf3231) is probs not very useful xd

**Comment by Jupeyy** [comment]
ah fck xd

**Comment by def-** [comment]
> we should also release a new patch version with this

This is not a regression in the current release, is it? Since the bug it fixed is from last year: https://github.com/ddnet/ddnet/issues/5143

**Comment by Jupeyy** [comment]
it's a regression from the new kill messages, which more often trigger it.
So if they new, it's in this release

**Comment by Kaffeine** [comment]
So good to have this finally fixed! Thanks @Jupeyy

**Comment by Jupeyy** [comment]
Ah btw @Kaffeine . In case of your mod, where it happened more often. It means that either the killer id or the victim id get invalid some times. I think it could:tm: also be simply unlucky, if e.g. a kill message network package is delayed, while the player, with that id that is used inside of the msg, disconnects.
But it could also mean the server sometimes actually generates invalid IDs. I dunno if that's generally a problem^^
That could explain why it mostly happened on non ddrace servers in the past^^

**Comment by Kaffeine** [comment]
> - a kill message network package is delayed, while the player, with that id that is used inside of the msg, disconnects.
> - either the killer id or the victim id get invalid some times

You're right on both.
I added a 'sub' mod with server-side bots, and those bots "disconnect" immediately on being killed a certain times (the bots have limited lives count). If `CNetMsg_Sv_KillMsg` and 'player disconnected' (Connless `SERVERINFO`?) can be shuffled then probably that is the reason for most of the crashes indeed.

The server also had a bug and could send expired/invalid ClientID for 'kill assistant' (which is processed 99% similarly to the killer/victim). However it only resulted in incorrect rendering as far as I seen.

The bots use up to 56 player slots, so the number of bot 'killed' + 'disconnected' pairs is 20-56 per round (1-3 minutes).
Screenshot_20230604_133002

**Pull request merged**
