### PR TITLE
Clear up instructions on using make

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by def-** [comment]
Or maybe we should just tell people to use ninja instead with `-G Ninja`. Seems better than make in any way.

**Comment by heinrich5991** [comment]
Teeworlds docs (written by me :P) mention Ninja as a way to speed up the build:

https://github.com/teeworlds/teeworlds/blob/e55aab45af0ecec6416d5b81cdd1d3836414f70d/readme.md#build-options

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
LGTM. Thanks!

bors r+

**Pull request merged**
