### PR TITLE
Avoid double free on m_pScore (fixes #3939)

### LINKED ISSUE #3939: Changing map twice causes double free
Found thanks to -Ofast, and weird that address sanitizer does not report this, but looking at it, i'd say it's definitely a bug:

https://github.com/ddnet/ddnet/blob/c24060f2448c5c88d74cffdacc3e09342ca9fa7a/src/game/server/gamecontext.cpp#L98

deletes `m_pScore` without setting it to zero

https://github.com/ddnet/ddnet/blob/c24060f2448c5c88d74cffdacc3e09342ca9fa7a/src/game/server/gamecontext.cpp#L100

initializes gamecontext without setting `m_pScore` to zero either (so at this point `m_pScore` points to invalid memory)

[...]

next time changing the map

https://github.com/ddnet/ddnet/blob/c24060f2448c5c88d74cffdacc3e09342ca9fa7a/src/game/server/gamecontext.cpp#L98
is called, it will delete an already free'd pointer

e.g. setting `m_pScore = 0` in the destructor also solves the issue for me. But i'm not sure if that causes any bugs, so better second opinion on this

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Guess if we delete it anyway in the destructor, we can also just set it to zero in the constructor always? :D

**Comment by Jupeyy** [comment]
Maybe we should generally avoid weird hacks like this, and just make the constructor better

**Comment by Jupeyy** [comment]
well `m_pVoteOptionHeap` is probably also kinda UB, from an argument like "constructor" can construct uninitialized values like it wants point, it should probably be fetched before destructing and be part of the constructor call list(same for other values that aren't initialized), but i'd be ok if we don't do it now, what would you say?

**Comment by def-** [comment]
I don't think I understand your comment and the code here.

**Comment by Jupeyy** [comment]
I just think that the code is really bad:

- A constructor that doesn't initialize all values is already unreliable, in this case ok, except for `m_pScore` as described in the issue
- CGameContext is a non trivial type, it has virtual functions, normally using virtual functions also implies using a virtual destructor. Calling the destructor of CGameContext and then new on the pointer with the base class `CGameContext` is just bad code

Imo it would be nicer to add a virtual void Reset(); and move the destructor code to a Destruct function
Then Reset can just call Destruct, Construct, garantuee the correctness of the call with the `int Resetting` parameter and also removing the `m_Resetting` hack(just bcs Destruictors don't have parameters)

**Comment by Jupeyy** [comment]
I just removed the Destructor parameter hack, I still feel like its weird code that OnShutdown Resets and reallocates the gamecontext xD
But ok, that is vanilla code and I guess a matter of not now

**Comment by def-** [comment]
bors r+
Thanks

**Pull request merged**
