### PR TITLE
HSV color picker for quad points

### PR DESCRIPTION
**Pull request by cinaera**
The UI handling of the picker is a bit ugly cause of the Active/HotItem UI system and the popup system. Debugging is pretty time consuming to correctly state the active UI item all the time, but atm it's working okish

Edit: here a quick preview \o/
hsv_picker

### CODE REVIEW

**Comment by east** [comment]
Just tested, looks pretty awesome :)

**Comment by east** [comment]
> [6:47:14 PM] Soreu: together with this, could there be possibility to just enter HEX code under it?

Do you want to add that?

**Comment by cinaera** [comment]
Sure, can try to add it as soon as I have time (:

**Comment by cinaera** [comment]
Added.

**Comment by east** [comment]
Seems to work, we should push this into the next version.

**Comment by def-** [comment]
Very nice work, @cineara

**Pull request merged**
