### PR TITLE
Minor refactoring of `os_version_str`

### PR DESCRIPTION
**Pull request by Robyt3**
## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Due to the changed function signature, this will probably require antibot to be recompiled.

**Comment by heinrich5991** [comment]
From a quick look, it seems like most functions that only return success or failure in this file return something falsy (e.g. 0) on success and something truthy (e.g. 1) on failure. Is there a reason why you chose to change that?

> Due to the changed function signature, this will probably require antibot to be recompiled.

That should be good, I don't think the antibot calls this function.

**Comment by Robyt3** [comment]
For the functions that return `bool` I prefer if  `true` equals success and `false` equals failure, because we also use this style in the rest of the codebase. Now that system is fully C++, we don't need to follow the more archaic style where 0 is success so rigorously.

I find calls like `if(function_returning_bool(...)) { /* handle success */ }` to be more readable. There's probably an argument to be made that `if(!function_returning_int(...))` checks could be changed to `if(function_returning_int(...) == 0)` to make it more explicit that an integer is returned which indicates some error code if non-zero.

Right now we have (according to a quick look through the comments):

- 6 functions returning `true` on success.
- 2 functions returning `1` on success (candidates for next refactoring).
- 24 functions returning `0` on success, most from the `io`/`net`/`fs` groups, which I would not change in the immediate future.

**Comment by edg-l** [comment]
lgtm

bors r+

**Pull request merged**
