### PR TITLE
Add team change mutes (fixes #1144)

### LINKED ISSUE #1144: Apply spam protection to spec/game join messages
With team_change_delay default value being 3, one can spam spectator => ingame forever, effectively flooding the chat for everyone.. even more efficient with a dummy; some sort of spam protection should be applied to that: either do not display the messages anymore if he's been spamming it, or prevent him from joining game/spectators (the same way you aren't able to send a message anymore if spam protections triggers on you)

### PR DESCRIPTION
**Pull request by ChillerDragon**
Im not sure if the tunings are perfect.
But the only false positive i could imagine is two lan buddys joining with dummys.
The last tee would trigger the team change ban for 10 minutes.
But this false positive is okay i think because they will probably play longer than 10 minutes and no message gets lost at all.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Mh. What I ment by #1144 was quite literally applying the same spam protection to join/leave messages as well: I.e. let them count towards the same chat limit, mute for it and don't display these messages if you're chat-muted.

**Comment by heinrich5991** [comment]
What do you think?

**Comment by ChillerDragon** [comment]
So combine them? And use one score for team change messages and chat messages? I guess that will be very tricky to tune correctly. Because we would get false positives for players who say a lot hi to people after joining with dummy. Or we would never catch the spammer. Imo this system is defnetly test worthy in offical servers.

**Comment by heinrich5991** [comment]
As discussed in PM, I'd rather have one system to tune. Joining/leaving teams is similarly annoying to chat messages.

**Pull request closed without merging**
