### PR TITLE
Add support for dynamically loading an antibot module

### PR DESCRIPTION
**Pull request by heinrich5991**
Support for this feature is turned off by default. This feature allows
to integrate with noby's anticheat feature.

### CODE REVIEW

**Comment by def-** [comment]
I'm fine with this in general, didn't read the code closely though. The antibot calls happen in the main thread, so the antibot code should be deterministically fast, right?

**Comment by Learath2** [comment]
This is not really dynamic given we are still linking the antibot during compilation, no? I think we could benefit from actually dynamically loading the antibot code.

**Comment by heinrich5991** [comment]
> This is not really dynamic given we are still linking the antibot during compilation, no? I think we could benefit from actually dynamically loading the antibot code.

This is dynamic insofar that you can always replace the shared library that this is linking to (i.e. before program start, no need to recompile). You cannot replace it during runtime though (and that would probably be harder to implement).

**Comment by heinrich5991** [comment]
> The antibot calls happen in the main thread, so the antibot code should be deterministically fast, right?

The calls do happen in the main thread, but the same is true on noby's fng servers. I just disentangled the source code a little bit, to make it work like a plugin.

**Comment by Learath2** [comment]
Let's do a test run

LGTM
bors r+

**Pull request merged**
