### PR TITLE
Render all entities on non ddnet servers

### LINKED ISSUE #1741: custom mod front layer entities
when playing custom mods (gametype is not exactly DDrace or DDNet or DDraceNetwork) the client should render all tiles from the front layer aswell, because custom mods -> custom tiles, also for front layer

### PR DESCRIPTION
**Pull request by 12pm**
Fixes #1741

### CODE REVIEW

**Comment by fokkonaut** [comment]
Not good, for example my mod has this protocol aswell and sends to use DDNet entities. Just make another Flag for it, would be the best

**Comment by 12pm** [comment]
If your server uses ddnet entities, what's wrong with this?

**Comment by Learath2** [comment]
The `m_Entities*` group is used for the overlay stuff I think but better ask @heinrich5991 :P

**Comment by fokkonaut** [comment]
@12pm it uses modified ddnet entities. Some players have them, not everybody. This m_EntitiesDDNet is send by the server and tells the client to use the ddnet entities if they are available. You should add a flag named RENDER_UNUSED and let the server decide whether to send it.

**Pull request merged**
