### PR TITLE
Lower save/swap punishments

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by houseme-kyle** [comment]
I think the time penalty can still be 60 seconds. But I agree the cooldown should be a lot lower. Happy either way.

**Comment by Jupeyy** [comment]
> I think the time penalty can still be 60 seconds. But I agree the cooldown should be a lot lower. Happy either way.

just for asking:
was the idea of cooldown = penalty to prevent time cheats(like going up faster)?

**Comment by Jupeyy** [comment]
> > I think the time penalty can still be 60 seconds. But I agree the cooldown should be a lot lower. Happy either way.
> 
> just for asking:
> was the idea of cooldown = penalty to prevent time cheats(like going up faster)?

Or what is the idea of a high cooldown anyway? E.g. why cant it be 10 seconds and still add the 60 seconds penalty?

**Comment by def-** [comment]
We didn't want to give people a way to get higher time than actually spent.

**Comment by Jupeyy** [comment]
> We didn't want to give people a way to get higher time than actually spent.

Ok, but now it does, 30 seconds cd, 60 s penalty, is that ok for you/is it on purpose?

**Comment by def-** [comment]
Factor 2 increasing time doesn't sound so bad to me. I doubt it will be mass-abused and not worth it compared to just afk-ing on server for a few hours.

**Comment by Jupeyy** [comment]
Alright
bors r+

**Comment by Jupeyy** [comment]
> Factor 2 increasing time doesn't sound so bad to me. I doubt it will be mass-abused and not worth it compared to just afk-ing on server for a few hours.

I think the max possible time was around 80 years, so even with a factor 10 they'd need to be afk pretty long xDD

**Pull request merged**
