### PR TITLE
Smaller buttons to refresh and enter server

### PR DESCRIPTION
**Pull request by def-**
Better for 5:4, allows seeing full ip:port, also ran language update, removed "Refresh" in demo menu too for consistency
Old:
screenshot-20220925@140452
New:
screenshot-20220925@140252
screenshot-20220925@140237

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
> Why not the refresh button we use everywhere else

Where can I find that?

**Comment by def-** [comment]
Can't combine it with other text in the same button

**Comment by def-** [comment]
Not when using the leak ip setting

**Comment by Learath2** [comment]
> Not when using the leak ip setting

The button itself could be made into a progress bar, I think I used that approach in something before. Or maybe a thin progress-line beneath the browser listbox?

**Comment by VoxelDoesCode** [comment]
I remember making a concept of this a while back, that also adds an icon to Server address.
image

**Comment by heinrich5991** [comment]
This looks good to me. Unfortunately, it has merge conflicts now.

**Comment by heinrich5991** [comment]
The icons in the original post?

**Comment by VoxelDoesCode** [comment]
Speaking of which, do you think we should make an enum for font icons? So that it's easier to reuse and read in code? Or would that be too much?

**Comment by Robyt3** [comment]
The loading percentage is no longer shown on the refresh button. Can you try using the refresh icon from the icon font?

**Comment by Jupeyy** [comment]
the enter button is also not from the icon font, we defs need a replacement for that too^^

> Speaking of which, do you think we should make an enum for font icons? So that it's easier to reuse and read in code? Or would that be too much?

some kind of naming is probably always good for us humans :P

**Comment by VoxelDoesCode** [comment]
> some kind of naming is probably always good for us humans :P 

Okay, I implimented that into #6494 !

**Pull request closed without merging**
