### PR TITLE
[DRAFT] Start working on 0.7 skins menu

### PR DESCRIPTION
**Pull request by ChillerDragon**
I started working on this a while ago and it is still far from being finished. Just wanted to share that I am working on this and get some feedback if it even has a chance to be merged when finished.

The goal of this pr is to have a additional skin menu which lets ddnet client users pick 0.7 skins in addition to 0.6 skins. Which then can be used for a ddnet 0.7 bridge or 0.7 only client.

screenshot_2022-07-25_14-05-58
screenshot_2022-07-25_14-07-06
screenshot_2022-07-25_14-07-12

### CODE REVIEW

**Comment by ChillerDragon** [comment]
> The concept sounds good to me.
> 
> I'd want to not complicate the API for rendering tees, it should automatically pick the right renderer based on the skin info.

There could be a skins/ and a skins7/ folder like for maps

**Comment by blueskyGH** [comment]
I am working on something similiar. This looks good, its always great to see other approaches.
Gonna watch the progress.

**Comment by heinrich5991** [comment]
Status: Unfinished.

Still working on this, @ChillerDragon?

**Comment by ChillerDragon** [comment]
> Status: Unfinished.
> 
> 
> 
> Still working on this, @ChillerDragon?

Why are you asking? Wanna cleanup prs? It is on my radar and I will get back to it and keep solving conflicts. But this will probably not finish in the near future.

I opened the pr not to show how close to finish I was. But just to check in if the idea has a chance of being merged. And poke the 0.7 client discussion a bit.

I could use some help on the skin rendering and UI list code.

( Looking at you @Jupeyy 👀 )

**Comment by ChillerDragon** [comment]
Thanks to @Jupeyy for pointing out render order of for and background. It now looks like this.

screenshot_2022-10-21_18-12-36

**Comment by ChillerDragon** [comment]
Thanks to @Robyt3 for porting upstreams CListBox now it looks closer to how it should look like :)

screenshot_2023-07-16_12-32-18

**Comment by heinrich5991** [comment]
Status: Draft.

**Comment by ChillerDragon** [comment]
image

Update: colors are now working :)

**Comment by ChillerDragon** [comment]
> The concept sounds good to me.
> 
> I'd want to not complicate the API for rendering tees, it should automatically pick the right renderer based on the skin info.

I renamed the old RenderTee to RenderTee6 and made both RenderTee6 and RenderTee7 private.
There is now this public wrapper RenderTee that calls the 7 render if it finds a valid 0.7 texture and uses 0.6 otherwise.

```c++
void CRenderTools::RenderTee(const CAnimState *pAnim, const CTeeRenderInfo *pInfo, int Emote, vec2 Dir, vec2 Pos, float Alpha)
{
	if(pInfo->m_aTextures[SKINPART_BODY].IsValid())
		RenderTee7(pAnim, pInfo, Emote, Dir, Pos);
	else
		RenderTee6(pAnim, pInfo, Emote, Dir, Pos, Alpha);
}
```

**Comment by ChillerDragon** [comment]
merged into #5949

**Pull request closed without merging**
