### PR TITLE
Remove hard-coded commands from client-side

### LINKED ISSUE #7665: Do not let the client assume available chat commands
Since https://github.com/ddnet/ddnet/pull/7649 the server can inform the client about what chat commands it has.
The ddnet client has a list of commands which matches the current ddnet version and it will always autocomplete those.
@furo321 decided to keep that list around. I suggest to remove that hardcodet list. Since it can be wrong on non ddnet servers or on ddnet servers in another version. We can also wait a few releases with this change to give server maintainers time to update. But then we should not keep using a old hack that has misleading autocompletions when there is already a cleaner system in place.

> heinrich5991: having an incorrect list is worse than having no list at all

### PR DESCRIPTION
**Pull request by Robyt3**
Both console and chat commands are sent to clients dynamically with respective messages, so the static lists of commands were only used for servers not making use of these messages. Instead of assuming potentially incorrect console and chat commands on those servers, the lists will now be empty for those servers.

Move the command registration from the `ddracecommands.h` and `ddracechat.h` header files to the `CGameContext::RegisterDDRaceCommands` and `CGameContext::RegisterChatCommands` functions and delete the header files. The `CHAT_COMMAND` and `CONSOLE_COMMAND` macros are removed, because they only add unnecessary indirection now. The strings `CHAT_COMMAND` and `CONSOLE_COMMAND` are simply replaced with `Console()->Register` and semicolons are added at the end of the lines.

Closes #7665.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
We could potentially keep them for old DDNet servers, but probably not worth it. What do you think?

**Comment by Robyt3** [comment]
> We could potentially keep them for old DDNet servers, but probably not worth it. What do you think?

Doesn't seem worth it to me for the added complexity.

**Comment by Robyt3** [comment]
> [!IMPORTANT]
> Note for modders: Servers are now expected to send the correct console and chat commands instead of depending on the default lists of commands.

See #7895.

**Comment by gerdoe-jr** [comment]
Oh, this makes possible getting rid of chat/console macros

**Review by heinrich5991 — APPROVED** [review]
I just checked, we've been sending the RCON commands for more than 10 years now, seems fine to remove it. ^^

Thanks!

**Pull request merged**
