### PR TITLE
Pr super pred

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Fixed the wrong change in here and formatting. Does this keep prediction with super working properly?

**Comment by fokkonaut** [comment]
I dont understand?.

**Comment by def-** [comment]
SameTeam and IsOtherTeam are used for collision prediction in the client I believe. So if you consider super players to be in another team then they might be predicted to move through another tee.

**Comment by def-** [comment]
@fokkonaut ?

**Comment by fokkonaut** [comment]
Well, I personally find it very weird that super players are now "in a different team". Because they arent and I think that was nicely visible already because they use the alpha of show others.
We should drop this change again, where they are in team 64 clientside and instead use the m_Super variable from ddnet character to handle super as that can also be used in the core etc.

The client should always display the player in his correct team like before imo.

**Comment by def-** [comment]
If you can get that to predict well, go ahead. I couldn't, and I liked being able to see who is in super clearly by viewing scoreboard.

**Comment by fokkonaut** [comment]
We shouldnt base prediction on what "you liked" but on the technical aspect of making use of the ddnet character. The team can then be sent to the client on top in order to show this separate team.

**Pull request closed without merging**
