### PR TITLE
Enable clang-tidy's modernize-use-override (fixes #5139)

### LINKED ISSUE #5139: Mark all overridden functions with `override`
Gives some better diagnostics in case you fail to override a function due to a typo.

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Do we want it for destructors too?

**Comment by heinrich5991** [comment]
Is there an upside doing it for destructors as well? I personally can't see any right now.

**Comment by def-** [comment]
Yep, literally takes 1 minute with clang-tidy's -fix:
```
cmake -G Ninja -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-fix" -DCMAKE_C_CLANG_TIDY="clang-tidy;-fix" -DCMAKE_BUILD_TYPE=Debug -Werror=dev && ninja
```

**Comment by def-** [comment]
> Is there an upside doing it for destructors as well? I personally can't see any right now.

Done

**Comment by heinrich5991** [comment]
`src/engine/client/discord.cpp` is missing some in the deactivated `CONF_DISCORD`.

**Comment by def-** [comment]
Looks like the clang-tidy version we have in CI doesn't support turning off for destructors yet. Is it ok to upgrade that?

**Comment by Chairn** [comment]
Maybe we should enable `-Wsuggest-override` flag as well

**Comment by heinrich5991** [comment]
> Maybe we should enable `-Wsuggest-override` flag as well

That might also be the easier option, don't need to check it in clang-tidy if we have a warning for it.

**Comment by Chairn** [comment]
I couldn't push to deen's fork:
https://github.com/Chairn/ddnet/tree/deenoverride

**Comment by heinrich5991** [comment]
> Not sure if i should make my own PR or not

You can make your own PR including the commits of deen.

**Comment by def-** [comment]
> I couldn't push to deen's fork: https://github.com/Chairn/ddnet/tree/deenoverride
> 
> Not sure if i should make my own PR or not

Taken your changes, thanks.

**Comment by Chairn** [comment]
Kinda weird that CI doesnt support `-Wsuggest-override`...
`-- Performing Test FLAG_SUPPORTED_Wsuggest_override - Failed`

**Comment by heinrich5991** [comment]
bors r+

Thanks! :)

**Review by heinrich5991 — APPROVED** [review]

**Pull request merged**
