### PR TITLE
Don't miss dummy disconnects. Fix #2257

### LINKED ISSUE #2257: highlight of wrong player
as found by enji on discord:

> if i connect to a empty server i get ID 0 and when i connect my dummy it gets ID 1, when I kick him with command "kick 1" it disconnects the tee but my client still thinks my dummy is in the game, then when somebody connects and gets my dummy original ID which was 1 and that person gets tagged in msg, the msg will highlight for me

### PR DESCRIPTION
**Pull request by Learath2**

### CODE REVIEW

**Comment by def-** [comment]
bors r+
thanks for the quick fix

**Comment by fokkonaut** [comment]
I dont think there should be a tick check for it, there should be another way just like a normal kick

**Comment by Learath2** [comment]
This is how the normal kick check works, it's right above this one

**Comment by fokkonaut** [comment]
Yes, I noticed. Thats why I deleted my message

**Pull request merged**
