### PR TITLE
Vk only allow asserts after initialization

### LINKED ISSUE #4891: Switching to vulkan and restarting will crash
As the game crash on start, once people switched, they can't change the renderer option back without twiddling in the cfg file. It should at least revert back to a base graphic renderer.

```shell
[2022-03-24 19:48:31][client]: starting...
[2022-03-24 19:48:31][sdl]: SDL version 2.0.8 (compiled = 2.0.8)
[2022-03-24 19:48:31][gfx]: Created Vulkan 1.0 context.
[2022-03-24 19:48:32][vulkan]: vulkan error: No vulkan compatible devices found.
[2022-03-24 19:48:32][assert]: ../src/engine/client/backend/vulkan/backend_vulkan.cpp(1094): No vulkan compatible devices found.
Illegal instruction (core dumped)
#0  0x00005555555deea6 in dbg_break() () at ../src/base/system.cpp:207
#1  0x00005555555dee7c in dbg_assert_imp(char const*, int, int, char const*) (filename=0x555555908208 "../src/engine/client/backend/vulkan/backend_vulkan.cpp", line=1094, test=0, msg=0x7fffffff7f50 "No vulkan compatible devices found.") at ../src/base/system.cpp:200
#2  0x00005555556302ed in CCommandProcessorFragment_Vulkan::SetError(char const*, char const*) (this=0x5555560dd550, pErr=0x5555559088c8 "No vulkan compatible devices found.", pErrStrExtra=0x0) at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:1094
#3  0x000055555563cd29 in CCommandProcessorFragment_Vulkan::SelectGPU(char*, char*, char*) (this=0x5555560dd550, pRendererName=0x555555d80914 "", pVendorName=0x555555d80714 "", pVersionName=0x555555d80814 "") at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:3438
#4  0x00005555556432c3 in CCommandProcessorFragment_Vulkan::InitVulkanSDL(SDL_Window*, unsigned int, unsigned int, char*, char*, char*) (this=0x5555560dd550, pWindow=0x555555dec1c0, CanvasWidth=1366, CanvasHeight=768, pRendererString=0x555555d80914 "", pVendorString=0x555555d80714 "", pVersionString=0x555555d80814 "")
    at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:5239
#5  0x000055555564a77e in CCommandProcessorFragment_Vulkan::Cmd_PreInit(CCommandProcessorFragment_GLBase::SCommand_PreInit const*) (this=0x5555560dd550, pCommand=0x555555dbf050)
    at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:6947
#6  0x0000555555646279 in CCommandProcessorFragment_Vulkan::RunCommand(CCommandBuffer::SCommand const*) (this=0x5555560dd550, pBaseCommand=0x555555dbf050)
    at ../src/engine/client/backend/vulkan/backend_vulkan.cpp:6074
#7  0x00005555556c946f in CCommandProcessor_SDL_GL::RunBuffer(CCommandBuffer*) (this=0x5555560d0950, pBuffer=0x7fffffff8940) at ../src/engine/client/backend_sdl.cpp:245
#8  0x00005555556c8ecb in CGraphicsBackend_Threaded::RunBufferSingleThreadedUnsafe(CCommandBuffer*) (this=0x555555d80500, pBuffer=0x7fffffff8940) at ../src/engine/client/backend_sdl.cpp:135
#9  0x00005555556cb890 in CGraphicsBackend_SDL_GL::Init(char const*, int*, int*, int*, int*, int, int, int*, int*, int*, int*, IStorage*) (this=0x555555d80500, pName=0x55555590fbd4 "DDNet Client", pScreen=0x555555c1fab0 <g_Config+4144>, pWidth=0x555555c1fab4 <g_Config+4148>, pHeight=0x555555c1fab8 <g_Config+4152>, pRefreshRate=0x555555c1fabc <g_Config+4156>, FsaaSamples=0, Flags=21, pDesktopWidth=0x555555c1fac0 <g_Config+4160>, pDesktopHeight=0x555555c1fac4 <g_Config+4164>, pCurrentWidth=0x7fffd9869020, pCurrentHeight=0x7fffd9869024, pStorage=0x555555d28aa0)
    at ../src/engine/client/backend_sdl.cpp:1106
#10 0x00005555556fead4 in CGraphics_Threaded::IssueInit() (this=0x7fffd9869010)
    at ../src/engine/client/graphics_threaded.cpp:2247
#11 0x00005555556fee81 in CGraphics_Threaded::InitWindow() (this=0x7fffd9869010)
    at ../src/engine/client/graphics_threaded.cpp:2304
#12 0x00005555556ff38f in CGraphics_Threaded::Init() (this=0x7fffd9869010)
    at ../src/engine/client/graphics_threaded.cpp:2443
#13 0x00005555556dcc36 in CClient::Run() (this=0x7fffdb53d010)
    at ../src/engine/client/client.cpp:2872
#14 0x00005555556e609d in main(int, char const**) (argc=1, argv=0x7fffffffd5e8)
    at ../src/engine/client/client.cpp:4458
```

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #4891

@Chairn can you test if this is enough.

Also I'd like to open an issue on SDL2. So some minor questions:
Is libvulkan1.so installed on your system?
What does `vulkaninfo | grep driverID` show on your system?

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
Okay, this is what is installed on my system:
```bash
$ locate libvulkan
/opt/Signal/libvulkan.so.1
/usr/lib/x86_64-linux-gnu/libvulkan.so
/usr/lib/x86_64-linux-gnu/libvulkan.so.1
/usr/lib/x86_64-linux-gnu/libvulkan.so.1.1.70
/usr/lib/x86_64-linux-gnu/libvulkan_intel.so
/usr/lib/x86_64-linux-gnu/libvulkan_radeon.so
/usr/share/code/libvulkan.so.1
/usr/share/doc/libvulkan-dev
/usr/share/doc/libvulkan1
/usr/share/doc/libvulkan-dev/changelog.Debian.gz
/usr/share/doc/libvulkan-dev/copyright
/usr/share/doc/libvulkan1/changelog.Debian.gz
/usr/share/doc/libvulkan1/copyright
/var/lib/dpkg/info/libvulkan-dev:amd64.list
/var/lib/dpkg/info/libvulkan-dev:amd64.md5sums
/var/lib/dpkg/info/libvulkan1:amd64.list
/var/lib/dpkg/info/libvulkan1:amd64.md5sums
/var/lib/dpkg/info/libvulkan1:amd64.shlibs
/var/lib/dpkg/info/libvulkan1:amd64.triggers
$ apt list --installed | grep -i vulkan
libvulkan-dev/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
libvulkan1/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
mesa-vulkan-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
vulkan-utils/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
$ apt list --installed | grep -i vulkan

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libvulkan-dev/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
libvulkan1/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
mesa-vulkan-drivers/bionic-updates,now 20.0.8-0ubuntu1~18.04.1 amd64 [installed]
vulkan-utils/bionic-updates,now 1.1.70+dfsg1-1ubuntu0.18.04.1 amd64 [installed]
$ vulkaninfo
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_standard_validation.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/icd.d/intel_icd.x86_64.json - The file has already been read once
WARNING: [Loader Message] Code 0 : Skipping manifest file /usr/share/vulkan/icd.d/radeon_icd.x86_64.json - The file has already been read once
/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
$ echo $?
255
```

Im not sure i can test this week as i need to move on on personal work as well.

**Comment by def-** [comment]
Should this be considered a blocker for 16.0 release?

**Comment by def-** [comment]
Do we have to wait for Chairn or can someone else on Windows test this?

**Comment by Jupeyy** [comment]
I just simulated the crash in the related issue.
Looks like it's enough

**Comment by Chairn** [comment]
Tested (ubuntu 18, no GPU), works fine.

```shell
[2022-04-02 03:41:58][client]: starting...
[2022-04-02 03:41:58][sdl]: SDL version 2.0.8 (compiled = 2.0.8)
[2022-04-02 03:41:58][gfx]: Created Vulkan 1.0 context.
[2022-04-02 03:42:00][vulkan]: vulkan error: No vulkan compatible devices found.
[2022-04-02 03:42:00][sdl]: SDL version 2.0.8 (compiled = 2.0.8)
[2022-04-02 03:42:00][gfx]: Created OpenGL 3.0 context.
[2022-04-02 03:42:00][opengl]: Vendor string: Intel Open Source Technology Center
[2022-04-02 03:42:00][opengl]: Version string: 3.0 Mesa 20.0.8
[2022-04-02 03:42:00][gfx]: GPU vendor: Intel Open Source Technology Center
[2022-04-02 03:42:00][gfx]: GPU renderer: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
[2022-04-02 03:42:00][gfx]: GPU version: 3.0 Mesa 20.0.8
```

**Pull request merged**
