### PR TITLE
Version 16.2

### PR DESCRIPTION
**Pull request by def-**
DDNet 16.2 is supposed to release in 1 week, assuming no bad bugs are found. Please test the Release Candidate to prevent problems being only discovered after release. Report bugs in the #bugs channel on DDNet Discord or directly on Github:

- Windows 32bit: https://ddnet.tw/downloads/DDNet-16.2-rc7-win32.zip
- Windows 64bit: https://ddnet.tw/downloads/DDNet-16.2-rc7-win64.zip
- Linux x86: https://ddnet.tw/downloads/DDNet-16.2-rc7-linux_x86.tar.xz
- Linux x86_64: https://ddnet.tw/downloads/DDNet-16.2-rc7-linux_x86_64.tar.xz
- Mac OS X: https://ddnet.tw/downloads/DDNet-16.2-rc7-macos.dmg

You can also test the release candidate in Steam by clicking on Settings -> Properties -> Betas and opting into the Release Candidates. This will automatically update you to a new release candidate when it is available, and to the next release when no new candidate is available. So you can always leave this setting enabled to help us test new releases earlier.
Screenshot 2022-06-15 at 00 25 23

173692601-61f65fe7-afa7-4031-8116-075c665d76d1

The following changes are included, ideally test their behaviour specifically. But just playing as you do normally also helps:
- [Client] **DDNet HUD** [c0d3d3v]
- [Client] **Controller support** [Robyt3]
- [Client] **Add community skin option** [Jupeyy]
- [Client] **Prediction of switch state toggles** [trml]
- [Client] **Use STUN to check network status when connecting** [heinrich5991]
- [Server] **HTTP masterserver registering** [heinrich5991]
- [Client] Reworked draggers, turrets, hooks always visible [c0d3d3v]
- [Client] Video Recorder: Don't ever skip any frame [Jupeyy]
- [Client] Use ellipsis in scoreboard for too long names [c0d3d3]
- [Client] Added live freeze in comfort entities [louis]
- [Client] Fix prediction input timing [trml]
- [Client] Fix input getter for dummy [trml]
- [Client] Fix dummy tick handling [sjrc6]
- [Client] Remove ui_scale [Robyt3]
- [Client] Remove cl_nameplates_ha(_size) [Robyt3]
- [Client] Fix ingame menu button behavior when holding mouse button [Robyt3]
- [Client] Prevent UI lockups [Robyt3]
- [Client] Always render nameplate of spec char [c0d3d3v]
- [Client] Fix pos1 only scrolling up one page in console [Robyt3]
- [Client] Lower max allowed FSAA on OpenGL [Jupeyy]
- [Client] Fix toggle with multiple chains [Robyt3]
- [Client] Remove cl_show_console [Robyt3]
- [Client] Fix video rendering being too fast [Jupeyy]
- [Client] Add basic driver version parsing for Vulkan [Jupeyy]
- [Client] Update tooltip text after changing language
- [Client] Support nesting CUI clipping regions and other UI elements [Robyt3]
- [Client] Remove cl_reset_wanted_weapon_on_death [Chairn]
- [Client] Fix crash because of hooks on non-DDNet servers [c0d3d3v]
- [Editor] Fix deleting envelopes not updating sounds [Ravie & c0d3d3v]
- [Server] Practice: Unfreeze when rescued, reset speed when teleporting [kiw-q]
- [Server] Practice: Unfreeze after teleporting [hus3h]
- [Server] Add `/cptime name` to get checkpoint times of another player (for speedrunning)
- [Server] Fix laser bounce physics on Putt Putt [c0d3d3v]
- [Server] Fix server loading map twice on startup [Zwelf]
- [Server] Fixed non-determinism in physics while keeping old behavior [c0d3d3v]
- [Server] Swap: Also swap no-collision and no-hook status [c0d3d3v]
- [Server] Prevent time overflow [c0d3d3v]
- [Server] Weapon-specific shields: Send normal shields to old clients [c0d3d3v]
- [Server] Explicitly delete game server from server list on shutdown [heinrich5991]
- [Server] Make capital /WHISPER work
- [Server] Remove sv_checkpoint_save
- [Server] Paginate bans
- [Server] Make input handling teehistorian-friendly [Zwelf]
- [Server] Update unicode script generation [Chairn]
- [Client+Server] Support outdated Windows 7 again (hopefully)
- [Tooling] Add integration test script and coverage map [ChillerDragon]

### CODE REVIEW

**Comment by heinrich5991** [comment]
The net messages for the DDRace HUD are currently still in flux AFAIK. We should either wait for them to converge or revert the DDRace HUD for this version, otherwise we'll have to deal with backward compatibility with the half-finished version.

**Comment by C0D3D3V** [comment]
I see the following options:
- I get https://github.com/ddnet/ddnet/pull/5210 finished before the release.
- Or we do not care about full HUD support for 16.2 (so after changing the NetObject the HUD will no longer display FreezeBar, NinjaBar and used Jump). This will probably happen early after the release, but we could then release fast a 16.3 with only few changes.

I'm working on https://github.com/ddnet/ddnet/pull/5210 now, so hopefully I'm finished very soon.

**Comment by def-** [comment]
How much time do you need? I'm ok with pushing 16.2 back 1-3 weeks. Would still keep the branch and only pick fixes to it in that time. (and the HUD changes)

**Comment by C0D3D3V** [comment]
If my idea works to fix the compatibility with expanding net objects. Then I will be finished with it tomorrow if everything irl is fine. If my idea doesn't work, I'll get back to you....

**Comment by fokkonaut** [comment]
Can we get https://github.com/ddnet/ddnet/pull/5427 in before, to have the HUD update complete?

**Comment by def-** [comment]
Marked as milestone

**Comment by C0D3D3V** [comment]
This still includes the commit from @fokkonaut 
`Let the server decide which hud to display ` That should be removed.

**Comment by Scrumplex** [comment]
> This still includes the commit from @fokkonaut `Let the server decide which hud to display ` That should be removed.

That commit causes an issue with the Vulkan renderer, at least for me.

See https://cdn.discordapp.com/attachments/293493549758939136/990591146394779728/vulkan_hud.mp4

```
# bad: [12a5524febe807900e5e52c4cbeb445fb79d72e4] Fix win32 discord compilation
# good: [be4ae021e5f7c1e9eac461ca1dad116feb0d2871] Update Brazilian Portuguese translation (supersedes #5304)
git bisect start '16.2-rc4' '16.2-rc3'
# bad: [c084d528868c41c0b0590468de1a94ee97bc0395] Add Opacity option for freeze bars inside freeze
git bisect bad c084d528868c41c0b0590468de1a94ee97bc0395
# bad: [4ee11581678b7c17cbaa8fbe95d3ee0d5f495c7a] remove tile info messages and freeze/ninja stars for new clients using version checking
git bisect bad 4ee11581678b7c17cbaa8fbe95d3ee0d5f495c7a
# good: [62e1c6a4c9db81a3a8f1c872b547d8b36720d79a] Update spanish.txt
git bisect good 62e1c6a4c9db81a3a8f1c872b547d8b36720d79a
# bad: [d0c1edcd8ffaf3ab1ace32cb830d09aefb2943bc] Revert "Build our own drmingw with mingw"
git bisect bad d0c1edcd8ffaf3ab1ace32cb830d09aefb2943bc
# bad: [79bf01b7d0561cde34f0431ee4641b1dc2c0bb5c] Let the server decide which hud to display
git bisect bad 79bf01b7d0561cde34f0431ee4641b1dc2c0bb5c
# first bad commit: [79bf01b7d0561cde34f0431ee4641b1dc2c0bb5c] Let the server decide which hud to display
```

**Comment by C0D3D3V** [comment]
@def-  I pushed the revert, without force pushing. And tested it. For me it works. ... So you could release the next RC :)

**Comment by def-** [comment]
@C0D3D3V  I guess there were some complaints about HUD changes. Anything we want to do about them or should I release 16.2 as planned?
@heinrich5991 I guess we also need https://github.com/ddnet/ddnet/pull/5210 and push back release a few days to get it tested?

**Pull request closed without merging**
