### PR TITLE
new lock indicator

### PR DESCRIPTION
**Pull request by BlaiZephyr**
### design by catseyenebulous
partially closes ddnet#8467

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by def-** [comment]
@l-ouis Is this more tee-ish?

**Comment by l-ouis** [comment]
Design looks better than previously but the icon seems to be rendered poorly-
image

I wouldn't recommend shading the lock shackle as you did -- maybe just don't shade it, or make the whole shackle a darker tone.
Also, I recommend adding more shading to the lock body -- see how much shading the default tee has and try to recreate the same proportion on the lock icon

**Comment by BlaiZephyr** [comment]
@l-ouis catseyenebulous updated it once again - mind giving your opinion on that? ty!

**Comment by l-ouis** [comment]
Shape looks better now, but my final recommendation is to make the black outline of the lock match the similar outlines in the double-jump and solo indicators. (Match the outline size to the other icons in the ingame HUD screenshot)

**Comment by l-ouis** [comment]
The outline width is a lot more fitting now
I'm not sure if my eyes are tricking me but it feels like the corners of the lock body have slightly bigger outlines, so I changed it below. (I'm not exactly sure if the lock body is a smooth curve or not though so it's really hard to tell). I'll just leave my edit here but either version looks fine enough -- I'd consult a more experienced DDNet artist as well just to get a second opinion

hud_edit

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Pull request merged**
