### PR TITLE
Texture change option from ATH

### PR DESCRIPTION
**Pull request by Deathmanlol**
Hi,
 
I am not good at coding.
I tried to add the Texture change option from AllTheHaxx Client (https://github.com/AllTheHaxx/AllTheHaxx) to DDNet.

When i click on the Texture button i added i get the error :

read access violation 
"this" was "0x10". 
Exception thrown: read access violation. this was 0x10

Sorry i am bad in coding and just copied.

### CODE REVIEW

**Comment by def-** [comment]
Hm, I see quite a lot of seemingly unrelated changes in there. Also, we would then be shipping many more graphics.

**Comment by Deathmanlol** [comment]
More graphics bad?

I said i am bad and just copied xd

**Comment by d3fault** [comment]
The ATH copyright license adds a GPL-esq clause: 
> You are allowed to modify the client and redistribute these executables,
  but you MUST give the sourcecode of which the respective exectuable was made
  to anyone who asks for it.

https://github.com/AllTheHaxx/AllTheHaxx/blob/master/license.txt#L24

**Comment by Learath2** [comment]
I don't like the license either and I don't like the implementation either. If we implement anything like this we shouldn't ship any extra graphics anyway, just let people use theirs.

@Deathmanlol if you want to see this as a feature, I suggest you implement it cleanly, or create an issue for it.

**Pull request closed without merging**
