### PR TITLE
Record rcon authentication stuff into teehistorian

### PR DESCRIPTION
**Pull request by heinrich5991**
This allows to check moderator actions after-the-fact.

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I thought you want to protect Moderators and let them do what they want.

But great to see this feature from you!!

**Comment by heinrich5991** [comment]
@Learath2 Wanna merge so I can start writing a parser?

**Comment by Learath2** [comment]
Mind if I give the parser a try?
bors r+

**Comment by heinrich5991** [comment]
You can do that – `libtw2` already has one that covers version 1 of teehistorian.

**Pull request merged**
