### PR TITLE
Rename variables for consistency

### PR DESCRIPTION
**Pull request by Zwelf**
The following member variables:
    
* m_name to m_aName
* m_String to m_aString
* m_CpCurrent to m_aCpCurrent
* m_Switchers to m_paSwitchers
* SavedTees to m_paSavedTees

The first one is kind of obvious. The others followed while looking at the code. I am not sure if the m_pa prefix is the correct one, it's a pointer to a dynamically allocated array.

### CODE REVIEW

**Comment by fokkonaut** [comment]
pa -> ap

**Comment by def-** [comment]
Oh no, now I started something. :/

**Comment by Zwelf** [comment]
My change is not related to #2210 (just looked it up, this is what you are referencing?).
The variable m_name struck me when reformatting #2200. I noticed the others while creating this PR. Would you prefer if this PR only changed m_name?

**Comment by def-** [comment]
Nono, it's ok.

**Comment by heinrich5991** [comment]
In Teeworlds code, the (array/pointer) prefix is always a direct function of the declared type. The switch member variable which has declared type `SSimpleSwitchers *` should therefore have the name `m_pSwitchers;` even if it is used as an array. This can also be seen in all the functions taking a `char *` pointer: Even though it's a pointer to an array, the declared type is just a pointer and thus these strings only have the prefix `p` and not `pa`.

**Comment by Zwelf** [comment]
I changed the variables according to the discussion above.

* m_Switchers to m_pSwitchers
* SavedTees to m_pSavedTees

**Pull request merged**
