### PR TITLE
Swap times should be per player, not per team (fixes #6155)

### LINKED ISSUE #6155: Swap timeout sometimes resets
image
As reported on Discord by bencie. I have seen this too

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I believe it was intentional to make it per-team? Doesn't really make sense for team 0 though.

I guess it's fine to make it per-tee.

**Comment by Chairn** [comment]
Probably fixes https://github.com/ddnet/ddnet/issues/5184 as well

**Comment by def-** [comment]
Yes, it looks like this was originally intentional, but forgot to be adapted after enabling for team 0. Thanks, Chairn, marked them as same bug.

**Comment by def-** [comment]
Ping, this is really annoying. Can anyone review?

**Comment by Learath2** [comment]
I was sure this got merged, somehow slipped my eye. Looks sane to me

bors r+

**Pull request merged**
