### PR TITLE
Warn when connecting to new server with high gametime

### PR DESCRIPTION
**Pull request by def-**
as suggested by HalfNoob on Discord

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
When cl_confirm_disconnect_time is 0, you cant connect to a server anymore.
Also it doesnt connect to the new server

**Comment by def-** [comment]
Thanks, fixed.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Comment by Jupeyy** [comment]
Have to ask again
"Also it doesnt connect to the new server"
Is that intended?

**Pull request merged**
