### PR TITLE
Always try extracting map before fail. Fix #1886

### LINKED ISSUE #1886: Cannot play demo without map file
Why dont we store the map file inside of the demo file? Right now we cannot play the demo, if the map is edited. For example record a demo on DDNet server on Kobra 4. Then go to editor, and click "load current map". Just edit the map a bit and hit ctrl+s, so dont save it in your private maps folder. Then try to play the demo and you will get a "map differs from server hash1 != hash2".

### PR DESCRIPTION
**Pull request by Learath2**
~~I think we should also store the SHA256 in the demo, but I'm not sure how to upgrade the demo format.~~

I also stored the SHA256 in the demo, but is this the right way to do it?
I smell endianness issues.

### CODE REVIEW

**Comment by def-** [comment]
So this changes the demo format?

**Comment by Learath2** [comment]
@def- As far as I can read, yes, but only breaks forwards compatibility.

**Comment by def-** [comment]
Then let's just get this in. @heinrich5991 ok from your side?

**Comment by Learath2** [comment]
@def- I'd love to get this in, but not before @heinrich5991 or you make sure that this is the correct way to extend the demo format.

**Comment by heinrich5991** [comment]
> I smell endianness issues.

No endian issues here btw.

**Comment by Learath2** [comment]
@heinrich5991 yeah I was thinking an uuid as well, but couldn't really figure out the best way to generate and add one there. Something like what you did for mapitems?

**Comment by heinrich5991** [comment]
One way: Just generate a UUID (probably best locally with `CalculateUuid("some_unique_string@ddnet.tw")`) and put it into the demo before the map's sha256. This lets us identify demos we generated with certainty which is already pretty good as far as map formats are concerned.

Unnecessarily complicated way: Think about how to extend the demo format with UUIDs and do it.

**Comment by def-** [comment]
Would like to release a new DDNet version soon. Should we get this in?

**Comment by Learath2** [comment]
Forgot about this, gimme a day or two. I'd like this one in there aswell

**Comment by Learath2** [comment]
@heinrich5991 can you take a quick look.
@fokkonaut can you verify that this fixes #1886 

I gave it a test myself, but it'd be nice if someone else can test it as well.
It doesn't break old demos. One issue is that if the demo format is extended by some other party, I just hope that they didn't add anything to the header. If they do, this all breaks.

**Comment by heinrich5991** [comment]
LGTM

bors r+

**Pull request merged**
