### PR TITLE
Fix min mouse position for follow factor

### PR DESCRIPTION
**Pull request by Jupeyy**
@Learath2 you were the last to change this, would be nice if you could check if this is correct behaviour, i didn't find anything wrong :D

### CODE REVIEW

**Comment by Jupeyy** [comment]
more like this probably

**Comment by heinrich5991** [comment]
@Jupeyy What does this PR do, what bug does this fix/what behavior does this change?

**Comment by heinrich5991** [comment]
And sorry for the inexcusably long response time, I decided to take a look at all outstanding PRs now.

**Comment by Jupeyy** [comment]
if you set your min mouse distance(cl_mouse_min_distance) to e.g. 100, the cursor should not be closer than 100 pixels(or whatever unit it is) from the tee(atleast thats what i assume bcs max_distance is the opposite). that seemed broken, probs bcs nobody ever used it?

**Comment by heinrich5991** [comment]
Works as advertised, though it's probably a little used feature. But this fixes it, so thanks. :)

bors r+

**Pull request merged**
