### PR TITLE
Send logout packet after using timeout protection (fixes #3490)

### LINKED ISSUE #3490: Can't log into rcon after timeout protection used, still shown as logged in
Can be reproduced by logging into rcon before using timeout protection to get the timed out tee.

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I think it would be better if the packet is only sent if the client is actually logged in. Could you change that?

**Comment by def-** [comment]
Any idea how? The problem here is tracking where the old client was and whether it was logged in before timeout protection was used.

**Comment by heinrich5991** [comment]
Does `m_aClients[ClientID].m_Authed != AUTHED_NO` before `DelClientCallback` work?

**Comment by def-** [comment]
Nope, that doesn't work.

**Pull request closed without merging**
