### PR TITLE
Smooth Camera

### LINKED ISSUE #3096: RFC: Smooth Dynamic Camera
This is my attempt of making a dynamic camera option for people with motion sickness or high mouse sensitivity.

The camera provides two new settings: 
- smoothness (`cl_camera_smoothness`): determines the speed of the camera
  - 0 being instant with no smoothness
  - 100 being the most smooth but slower camera movement.

- stabilizing factor (`cl_camera_stabilizing`): determines how fast your cursor need to move before the stabilization kicks in
  - 0 being no stabilization, camera will always move at a constant speed
  - 100 being max stabilization, a tiny mouse movement will decrease the camera speed down to almost at halt
  - this setting is made for "spinny" players while still allow the camera to extend far enough and fast enough when they are actually aiming and not spinning or hooking around.

- There is a menu setting that sets both value to 50.

If you hate dynamic camera, I'd recommend you download the artifact and try out yourself see if you can use the extra view distance without being sick. (Don't forget dynamic camera settings like `cl_mouse_deadzone` and `cl_mouse_followfactor` still applies, try to adjust them as well)

[Video Demo](https://streamable.com/kedppm)
[Code for Teeworlds](https://github.com/TsFreddie/teeworlds/tree/0.7-smoothdyncam)
[Code for DDNet](https://github.com/TsFreddie/ddnet/tree/smoothdyncam)
[Artifacts for Teeworlds](https://github.com/TsFreddie/teeworlds/runs/1247575998)
[Upstream Discussion at Teeworlds](https://github.com/teeworlds/teeworlds/issues/2777)

### PR DESCRIPTION
**Pull request by TsFreddie**
closes #3096

Since nobody expressed any opinions, how about we get this in and see some reactions. it is off by default anyway.

### CODE REVIEW

**Comment by def-** [comment]
Looks good to me, I like it. @heinrich5991 ?

**Comment by Learath2** [comment]
I'll try this out tonight, but I'm not sure how useful a smooth stabilized dynamic camera would be. It's like the worst of both worlds, your reference isn't stable but it appears stable so I feel it would throw you off.

Only one way to know, testing it out :)

**Comment by b3z** [comment]
[This example](https://streamable.com/kedppm) by Freddie shows the effect quite well. It makes me feel a little dizzy.

**Comment by Learath2** [comment]
Oh, I forgot to report back. It's not as bad as I thought it would feel, though it was a little disorienting for me, it felt sluggish. Idk maybe it could be added for the people who don't like the current dyncam at all?

**Comment by TsFreddie** [comment]
Yeah, that's the idea. Ppl who really hate current dyncam don't want to change aiming habits. I tried my best to let them have the view without changing the way they use their mouse. Probably need more feedback from ppl who don't use dyncam at all.

**Pull request merged**
