### PR TITLE
Other idea about #3219 (Scoreboard line height and font size matches for each team)

### PR DESCRIPTION
**Pull request by b3z**
Maybe this would be a solution? Or does is break anything else important? I have no overview.
I tested it ingame and it seemed to work.

I am not sure if this is a good idea but are the team sizes used for anything else?

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Banana090** [comment]
Definitely will break something. 100%. You can't just change actual team size for this

**Comment by def-** [comment]
Let's not do this. Otherwise we might access team out of bounds.

**Comment by b3z** [comment]
> Let's not do this. Otherwise we might access team out of bounds.

Why so? The out of bounds?

Another idea would be to just give a copy to the RenderFunction but I guess this solution is just shit.

**Comment by b3z** [comment]
Better go with #3219

**Pull request closed without merging**
