### PR TITLE
Allow server to redirect clients

### PR DESCRIPTION
**Pull request by ChillerDragon**
This is a preperation for #6754 (redirect players on map vote)
And an implementation of #5662 (redirect players)

The redirect rcon command can be used by admins to move the whole player base to a new server. Using ``redirect -1 ger.ddnet.org:8303`` to redirect all clients that support it. Or redirect individual ids which could be an alternative to the kick command.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Didn't read it, but why security hints?

Is it only allowed to redirect to a server is the same ip?

**Comment by ChillerDragon** [comment]
> Didn't read it, but any security hints?
> 
> Is it only allowed to redirect to a server is the same ip?

```C++
		else if(Msg == NETMSG_REDIRECT)
		{
			const char *pAddr = Unpacker.GetString(CUnpacker::SANITIZE_CC);
			Connect(pAddr);
		}
```

The client passes the string given by the server to the connect method. No restrictions what so ever.

**Comment by Jupeyy** [comment]
Mh k. We should discuss stuff like that tho
Be it for attack possibilities or for privacy concerns

Generally this is an action the user does not directly control. So maybe a pop-up with "Do you want to be moved to that server?" Is required.

If you have other concerns please write them down

**Comment by ChillerDragon** [comment]
> Mh k. We should discuss stuff like that tho Be it for attack possibilities or for privacy concerns
> 
> Generally this is an action the user does not directly control. So maybe a pop-up with "Do you want to be moved to that server?" Is required.
> 
> If you have other concerns please write them down

https://github.com/ddnet/ddnet/issues/5662#issuecomment-1197546057

**Comment by ChillerDragon** [comment]
The biggest attack vector I see is the unsanitized string being passed to ``Connect()`` and there being parsed by C++ code.

**Comment by ChillerDragon** [comment]
> The second is not correct. You are writing packets to a different ip, that you cannot directly influence.
If a evil server send me to ger.ddnet.to then i might think I am on a ddnet server, while in fact I'm on some weird server xdd it could silently mirror the server

Is that not the same as registering ger.ddnet.to in the master server?

**Comment by Jupeyy** [comment]
Well I'm not a scammer so I'm sadly not as creative. But 1. In server browser there is a verified icon 2. The scammer could broadcast smth like l. Server shutdown. We redirect u to ddnet severs 

Besides that. Even if ger ddnet severs would move me to rus ddnet severs, I'm not sure if this is nice.

I don't have a very strong opinion on what I wrote here, just not sure if i like it wildcard

**Comment by heinrich5991** [comment]
I agree that we should talk about security. Maybe only allowing the same IP address is good for a start.

We should think about what happens when the client ignores the redirect. Probably the server should not continue to serve that client. Are there other protocols with mandatory redirect features? How do they handle this? HTTP has redirects, but it's not really the same, I think.

Then, the string (should it be a string) should not be passed to the client's `Connect` function directly, that's a backward compatibility hazard. Instead, it should only accept a small, well-defined format.

**Comment by ChillerDragon** [comment]
So what about the packet containing only a integer field which is the port. And the client the connects to the current ip and that port?

**Comment by ChillerDragon** [comment]
> And it should probably not be a console command, I'd prefer not to normalize moderation by redirection.

Imo having the option is nice. If you do not want to normalize it on official ddnet servers just do not give mods access to it. But could come in handy during some tournaments if there is a hotfix that has to be shipped and the server has to be restarted or something like that.

> We should think about what happens when the client ignores the redirect. Probably the server should not continue to serve that client. Are there other protocols with mandatory redirect features? How do they handle this? HTTP has redirects, but it's not really the same, I think.

Imo its fine that the client can ignore it. Depending for what this is used the server can then follow up with a kick if wanted or send a broadcast to clients that do not support it.

**Comment by ChillerDragon** [comment]
Force pushed to only send the port.

**Comment by Filto001** [comment]
@ChillerDragon will this work for older clients?

**Comment by ChillerDragon** [comment]
> @ChillerDragon will this work for older clients?

This only works for clients that have this patch.

**Comment by Kaffeine** [comment]
Hi, thank you for working on this!
I think that features implementation can be postponed but it would be nice to have a future-proof protocol (the message) right in this MR.

1. A 'cookie' or 'opaque id' (as I suggested in https://github.com/ddnet/ddnet/issues/5662#issuecomment-1584614117
    That extra data can be used to re-create the same teams for moved players, and maybe keep some player settings (timer type, dnd, etc).

2. Password option maybe?
3. A message?
4. Speaking of the "same IP" — I suggest to keep the IP in the message but for now check <s>or just ignore</s> it on the client (to keep protocol the same when we 'll decide to allow different IPs, maybe with a confirmation or a checkbox in settings).


Note: there is no check for whether the new address is the same as that of the current server. Probably it opens a possibility to make clients quickly autojoin the server on shutdown (instead of `NET_CTRLMSG_CLOSE` with a reason the server can send NETMSG_REDIRECT to itself) which is something I'd definitely use on my server to improve server update workflow.

**Comment by ChillerDragon** [comment]
Redirecting to another ip could be cool if you have two servers/networks for anti flood or ddos.
So one server has a strict firewall allowing no traffic in and thus runs smooth. The other allows all traffic and accepts external connections. If a connection is then verified it can whitelist the ip on the other host and redirect the client there. So a attacker can only lag the verification server but not the gameplay server.

**Comment by heinrich5991** [comment]
> 1. Speaking of the "same IP" — I suggest to keep the IP in the message but for now check or just ignore it on the client (to keep protocol the same when we 'll decide to allow different IPs, maybe with a confirmation or a checkbox in settings).

I think we can simply introduce a new message in that case.

**Comment by heinrich5991** [comment]
> We should think about what happens when the client ignores the redirect. Probably the server should not continue to serve that client. Are there other protocols with mandatory redirect features? How do they handle this? HTTP has redirects, but it's not really the same, I think.

I think the correct course of action is to disconnect all clients that do not support the feature with a message, and no longer accept any messages from clients that support this feature.

> 2. A 'cookie' or 'opaque id' (as I suggested in https://github.com/ddnet/ddnet/issues/5662#issuecomment-1584614117
That extra data can be used to re-create the same teams for moved players, and maybe keep some player settings (timer type, dnd, etc).

That sounds sensible.

> 3. Password option maybe?

Kinda redundant with the 'opaque ID'.

> 4. A text message (e.g. to be displayed in `POPUP_CONNECTING` along with "Connecting to ")?

This is 

> > And it should probably not be a console command, I'd prefer not to normalize moderation by redirection.
> 
> Imo having the option is nice. If you do not want to normalize it on official ddnet servers just do not give mods access to it. But could come in handy during some tournaments if there is a hotfix that has to be shipped and the server has to be restarted or something like that.

No, I think that options in the official DDNet server are also important. If people want to use this for moderation, they'd have to patch the source by themselves, which can be enough friction that people might not do it.

**Comment by ChillerDragon** [comment]
I am also in favor of adding cookies. But that belongs into a different pr.

> > We should think about what happens when the client ignores the redirect. Probably the server should not continue to serve that client. Are there other protocols with mandatory redirect features? How do they handle this? HTTP has redirects, but it's not really the same, I think.
> 
> I think the correct course of action is to disconnect all clients that do not support the feature with a message, and no longer accept any messages from clients that support this feature.

Whats the benefit of that? This pr is more about the client implementation. What the server then does can be decided when the server does use it. Also if you instantly kill the connection without any ack then the packet might have been lost in udp land and the client does not know what is going on so that has to be properly handled. If you do nothing the tw protocol will ensure it being sent automatically.

If I follow your other feedback (which I plan to do) of removing the rcon part there is no server implementation left to think about in this pr.

> I think we can simply introduce a new message in that case.

Which then takes a few update cycles to get it shipped to clients. What is the disadvantage of redirecting to another ip? Also redirecting to a domain would be nice. The reason why I initially passed the whole input directly to the Connect method is to also allow for comma separated fallback ips.

**Comment by heinrich5991** [comment]
> Whats the benefit of that? This pr is more about the client implementation.

The benefit of this is that client mods will use the implementation deemed "correct" and not the most lazy one.

> Also if you instantly kill the connection without any ack then the packet might have been lost in udp land and the client does not know what is going on so that has to be properly handled.

I agree. I'd only close the connection for clients not supporting the feature. For the rest, it simply ignores all further packets, waiting for the client to close the connection.

**Comment by heinrich5991** [comment]
> What is the disadvantage of redirecting to another ip?

We haven't completely thought about the security implications, and I think we haven't seen a detailed use case yet.

> The reason why I initially passed the whole input directly to the Connect method is to also allow for comma separated fallback ips.

The network protocol should not be tied to the stuff that users can put into the connect method, i.e. it should get its own implementation with a well-thought out format. Just a port seems to work for the use case we have in mind, redirecting between servers hosted in the same location, e.g. for map votes.

**Comment by ChillerDragon** [comment]
> > What is the disadvantage of redirecting to another ip?
> 
> We haven't completely thought about the security implications, and I think we haven't seen a detailed use case yet.

How does one complete security research?
Which details are missing for a firewall server that redirects to another network?

If the different IP is a deal breaker for you thats sad but I rather have port only map votes and self redirects for server restarts than nothing.

**Comment by ChillerDragon** [comment]
Force pushed the rcon command away

**Comment by Kaffeine** [comment]
> > Password option maybe?
>
> Kinda redundant with the 'opaque ID'.

It depends on the opaque data format and on the packets order.

If we'd use a dictionary (e.g. json) with arbitrary keys AND the client can parse the password from that <s>opaque</s> (not any more) data OR if we send that `opaque_data` before the expected message with password [`NETMSG_INFO`](https://github.com/ddnet/ddnet/blob/c955905662853a6b7ecf0f95fa22037556d3d94b/src/engine/client/client.cpp#L477C17-L477C17)) then yes, an explicit password in the protocol message is not needed.

Please note that in that case the server 'll have to deserialize the opaque data before authentication, so this potentially can lead to attacks with huge/invalid opaque data and the server password protection won't help.

It is also possible that (for whatever reason) we'll decide to say that "the opaque data format is entirely up to the server", because (except the auth data) the player settings are totally mod-dependent. Having the password in its own field is the only thing needed for interoperability in that case.

**Comment by Kaffeine** [comment]
> > I think we can simply introduce a new message in that case.
>
> Which then takes a few update cycles to get it shipped to clients.

We can add a new message but then we'll have to keep the support for different versions of that message both in the server and in the client code. IOW increased maintenance burden for a little reason.

**Comment by heinrich5991** [comment]
LGTM, thanks!

**Comment by Kaffeine** [comment]
What, why? What is about https://github.com/ddnet/ddnet/pull/6757#issuecomment-1616686360?
It would be disappointing to support different versions of the redirect message. I see, you always like to maintain some extra code. :sarcasm:

**Comment by heinrich5991** [comment]
Sorry for merging without addressing all remaining concerns. I reverted the commit. Can you reopen this or another pull request for this, @ChillerDragon?

> We can add a new message but then we'll have to keep the support for different versions of that message both in the server and in the client code. IOW increased maintenance burden for a little reason.

I don't think that the maintenance burden would be reduced if we went with the following solution:

> 1. Speaking of the "same IP" — I suggest to keep the IP in the message but for now check or just ignore it on the client (to keep protocol the same when we 'll decide to allow different IPs, maybe with a confirmation or a checkbox in settings).

This would still lead to supporting two protocols.

**Comment by heinrich5991** [comment]
Ah, and now I remember I also had a blocking concern: Clients messages should no longer be accepted after the redirect message was sent their way.

**Comment by ChillerDragon** [comment]
> Ah, and now I remember I also had a blocking concern: Clients messages should no longer be accepted after the redirect message was sent their way.

Which I fixed by not sending the message to clients in this pullrequest. Whoever implements that has to cover it if wanted.

**Comment by heinrich5991** [comment]
> > Ah, and now I remember I also had a blocking concern: Clients messages should no longer be accepted after the redirect message was sent their way.
> 
> Which I fixed by not sending the message to clients in this pullrequest. Whoever implements that has to cover it if wanted.

The idea behind providing the method that people using this message will be lazy and just use the function we provide. Thus it doesn't work to defer it to them, I think.

**Comment by ChillerDragon** [comment]
> > > Ah, and now I remember I also had a blocking concern: Clients messages should no longer be accepted after the redirect message was sent their way.
> 
> > 
> 
> > Which I fixed by not sending the message to clients in this pullrequest. Whoever implements that has to cover it if wanted.
> 
> 
> 
> The idea behind providing the method that people using this message will be lazy and just use the function we provide. Thus it doesn't work to defer it to them, I think.

Okay easy fix. Delete more code and make this a client only pullrequest 😜 it's the more important part anyways to get it out to clients. Server Code can be changed easily

**Comment by heinrich5991** [comment]
> Okay easy fix. Delete more code and make this a client only pullrequest stuck_out_tongue_winking_eye it's the more important part anyways to get it out to clients. Server Code can be changed easily

This doesn't help with the evil lazy people. :p Do you want an implementation idea for ignoring further messages/dropping old clients?

**Comment by Kaffeine** [comment]
Oh. My first thought was that we can define the message now with all the data-members we want to add later, and then we can send more data in newer servers.

But now I see that it won't work in that way. If we define the message as `{ address, port }` and use only port for now, then the now-released client 'll do wrong things when we'll have both the `address` and the `port` because `"", 8304` is totally different from `"xxx.yyy.zzz.www, 8304"` — we can't just drop the IP and pretend to be compatible.
So the only way to compatibility is implement both IP and port right now and e.g. declare that the address must be empty to mean "the same host/IP". Then if the client 'll receive some custom address from a newer server it won't join the same server on the given port by a mistake.

We can add other fields:
- opaque data (if the client does not implement the data bypassing then it won't have the player state restored) BUT as the only action for the client is to bypass it, then it seems easy to implement
- text message (can be actually implemented later)
- password ([if we even want it](https://github.com/ddnet/ddnet/pull/6757#issuecomment-1616650456)) (if the client does not support the pw then the user 'll have to enter it)

**Pull request merged**
