### PR TITLE
Add Thread Safety Analysis

### PR DESCRIPTION
**Pull request by def-**
https://clang.llvm.org/docs/ThreadSafetyAnalysis.html

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Huh, looks good. :)

**Comment by def-** [comment]
Ready for review, doesn't check this much, but can be extended in the future with stricter checks.

**Comment by Learath2** [comment]
Are we checking this anywhere in CI? Seems our only target that compiles with clang is macOS and that's AppleClang, god knows which version it is.

**Comment by def-** [comment]
Yes, the apple clang build is doing this.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
