### PR TITLE
Add cl_show_local_direction (fixes #3978)

### LINKED ISSUE #3978: Show own key presses with cl_show_direction (2?) enabled
This was asked a bunch of times on the discord. As of now, the only way to actually see your own key presses is by recording and watching the recorded demo in the demo viewer.

in addition if anyone wants to plan on adding this, maybe consider also adding: #3281 ? :D

### PR DESCRIPTION
**Pull request by HamidReza585**
cl_show_local_direction allows you to see your own key presses during the game.

I changed the statements so it will allow local player to have key press arrows (inside the game), and I added a statement for configs (settings), so if you have cl_show_local_direction enabled, it will render the directions (arrows) for the local player. (Also affects demos and videos, same as cl_show_direction)

ScreenShot

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
How about just using `cl_show_direction 2` to also show your own?

**Comment by HamidReza585** [comment]
> How about just using `cl_show_direction 2` to also show your own?

I was thinking of doing that but I have no idea how to add it to settings then

**Comment by def-** [comment]
You can have 2 checkboxes and set the value based on it. It should work, you can compare if the value is 1 or 2 or 0 and set it to any you want.

**Comment by HamidReza585** [comment]
> You can have 2 checkboxes and set the value based on it. It should work, you can compare if the value is 1 or 2 or 0 and set it to any you want.

Done

**Comment by def-** [comment]
bors r+
Thanks

**Pull request merged**
