### PR TITLE
Reduce dummy map size from 549 bytes to 191 bytes

### PR DESCRIPTION
**Pull request by heinrich5991**
Also include a tool to generate said map; the map is generated without
any hacks. It could likely be made smaller using a few tricks.

### CODE REVIEW

**Comment by heinrich5991** [comment]
I opened a test server with this map, and neither the server nor the client had a problem with it.

**Comment by heinrich5991** [comment]
Old:
```
DATAFILE
header: Header { hv: HeaderVersion { magic: [68, 65, 84, 65], version: 4 }, hr: HeaderRest { size: 533, swaplen: 456, num_item_types: 5, num_items: 7, num_data: 2, size_items: 332, size_data: 77 } }
item_type type_id=0
  item id=0
    00000001           1 ....
item_type type_id=1
  item id=0
    00000001           1 ....
    ffffffff          -1 ....
    ffffffff          -1 ....
    ffffffff          -1 ....
    ffffffff          -1 ....
item_type type_id=4
  item id=0
    00000003           3 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000001           1 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    80808080 -2139062144 ....
    80808080 -2139062144 ....
    80808000 -2139062272 ....
  item id=1
    00000003           3 ....
    00000000           0 ....
    00000000           0 ....
    00000064         100 ....
    00000064         100 ....
    00000001           1 ....
    00000001           1 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    c7e1ede5  -941494811 Game
    80808080 -2139062144 ....
    80808000 -2139062272 ....
item_type type_id=5
  item id=0
    98de7290 -1730252144 .^..
    00000003           3 ....
    00000000           0 ....
    00000002           2 ....
    00000001           1 ....
    00000000           0 ....
    ffffffff          -1 ....
    d1f5e1e4  -772415004 Quad
    f3808080  -209682304 s...
    80808000 -2139062272 ....
  item id=1
    98de7290 -1730252144 .^..
    00000002           2 ....
    00000000           0 ....
    00000003           3 ....
    00000002           2 ....
    00000002           2 ....
    00000001           1 ....
    000000ff         255 ....
    000000ff         255 ....
    000000ff         255 ....
    000000ff         255 ....
    ffffffff          -1 ....
    00000000           0 ....
    ffffffff          -1 ....
    00000001           1 ....
    c7e1ede5  -941494811 Game
    80808080 -2139062144 ....
    80808000 -2139062272 ....
    00eaa120    15376672 .j!.
    443de763  1144907619 ..g.
    0000000c          12 ....
    40800000  1082130432 ....
    428d0000  1116536832 ....
item_type type_id=6
  item id=0
data id=0 size=152
  |00cbf3ff 40d8f6ff 00350c00 40d8f6ff| ....@....5..@... 00000000
  |00cbf3ff c0270900 00350c00 c0270900| .....'...5...'.. 00000010
  |00800000 00800000 5e000000 84000000| ........^....... 00000020
  |ae000000 ff000000 5e000000 84000000| ........^....... 00000030
  |ae000000 ff000000 cc000000 e8000000| ................ 00000040
  |ff000000 ff000000 cc000000 e8000000| ................ 00000050
  |ff000000 ff000000 00000000 00000000| ................ 00000060
  |00040000 00000000 00000000 00040000| ................ 00000070
  |00040000 00040000 ffffffff 00000000| ................ 00000080
  |ffffffff 00000000|                   ........         00000090
                                                         00000098
data id=1 size=16
  |00000000 00000000 00000000 00000000| ................ 00000000
                                                         00000010
```

New:
```
DATAFILE
header: Header { hv: HeaderVersion { magic: [68, 65, 84, 65], version: 4 }, hr: HeaderRest { size: 175, swaplen: 164, num_item_types: 2, num_items: 2, num_data: 1, size_items: 104, size_data: 11 } }
item_type type_id=4
  item id=0
    00000001           1 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000001           1 ....
item_type type_id=5
  item id=0
    00000000           0 ....
    00000002           2 ....
    00000000           0 ....
    00000002           2 ....
    00000002           2 ....
    00000002           2 ....
    00000001           1 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    00000000           0 ....
    ffffffff          -1 ....
    00000000           0 ....
    ffffffff          -1 ....
    00000000           0 ....
data id=0 size=16
  |00000000 00000000 00000000 00000000| ................ 00000000
                                                         00000010
```

**Comment by CytraL** [comment]
just curious, so you use the dummy map?

**Comment by east** [comment]
Awesome! But we should try it with multiple clients first, I will do that once I am home.

**Comment by east** [comment]
Well, the client doesn't crash but there is no background so users will see an 'empty graphics buffer' (you will notice it with gfx_clear 1). It could look pretty strange on some systems.

**Comment by heinrich5991** [comment]
Bytes before: 291 (549 uncompressed)
Bytes with new, ugly dummy map: 64 (191 uncompressed)
Bytes with new, black dummy map: 114 (306 uncompressed)

**Comment by east** [comment]
Hm, for me the map crc of the black dummy map is 0x6c760ac4.
Looks good though, I think we can use it.

**Comment by heinrich5991** [comment]
You're right, the CRC must be of some older iteration of the map. Fixed.

**Pull request merged**
