### PR TITLE
Added a transparent image to the assets directory called "none"

### PR DESCRIPTION
**Pull request by Steinchen99**
To be able to have invisible assets without having to create them yourself.

image

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Why would you want to set an entirely transparent texture for anything except maybe the extras? Being able to easily set transparent assets will just cause confusion for players that accidentally use these.

**Comment by Steinchen99** [comment]
> Why would you want to set an entirely transparent texture for anything except maybe the extras? Being able to easily set transparent assets will just cause confusion for players that accidentally use these.

I added them to all, not just to "extras"

**Comment by Steinchen99** [comment]
> Why would you want to set an entirely transparent texture for anything except maybe the extras? Being able to easily set transparent assets will just cause confusion for players that accidentally use these.

Should I add it only to extras? There's a lot people who don't want to see the snow particles.

**Comment by Robyt3** [comment]
> Should I add it only to extras? There's a lot people who don't want to see the snow particles.

In my opinion, no. They can create their own transparent image if they want to.

**Comment by heinrich5991** [comment]
> In my opinion, no. They can create their own transparent image if they want to.

I agree. We don't need to ship customizations, they can be downloaded from elsewhere.

**Pull request closed without merging**
