### PR TITLE
Add UBSan and ASan to CI

### PR DESCRIPTION
**Pull request by ChillerDragon**
Start server and headless client once and see if it gets some ubsan or asan hits.
The headless client might have less or different violations of the holy c++ standard but its the best way to get some client code runtime in the CI.

Related issue https://github.com/ddnet/ddnet/issues/3050

### CODE REVIEW

**Comment by C0D3D3V** [comment]
But what would be the use case of this? I already get dozens of issues from UBSan/ASan on the Master branch.
Wouldn't we ignore them like we do now?

**Comment by C0D3D3V** [comment]
Ah you only check for SAN files... mh ok

**Comment by ChillerDragon** [comment]
> But what would be the use case of this? I already get dozens of issues from UBSan/ASan on the Master branch. Wouldn't we ignore them like we do now?

Yea the issues should be fixed or whitelisted before this pr is merged. A failing pipeline is no fun.

**Comment by ChillerDragon** [comment]
@def- this pipeline should pass now. Not sure if its possible to rerun without force pushing something.

**Comment by Robyt3** [comment]
You could rebase and force push to run the pipeline again.

**Pull request merged**
