### PR TITLE
show_ips

### PR DESCRIPTION
**Pull request by def-**
The problem is that the same console output is sent to all right now,
not sure how to change that cleanly

### CODE REVIEW

**Comment by def-** [comment]
We could format IPs in a special easily recognizable way and then CServer::SendRconLine filters that out if the player doesn't have show_ips set, but some player could make their name into that pattern.

**Comment by def-** [comment]
Drawbacks:

- Only one IP address per line supported
- Player could call themselves <[foo]> and then have their IP address leaked

**Review by heinrich5991 — COMMENTED** [review]
It's a big hack, but I guess it's fine…

Are we doing `nullptr` these days?

According to the ranks page, among a couple of braces, `<{` has the lowest player count (3). Maybe use that instead?

**Comment by def-** [comment]
Oops, I got used to nullptr at work. Will fix. Also will switch to <{

**Comment by fokkonaut** [comment]
Didn't Ryozuki use nullptr's too?

**Comment by ChillerDragon** [comment]
@fokkonaut ye @Ryozuki trys to sneaky break vanilla compability o.O

**Comment by Ryozuki** [comment]
We should put somewhere `#define NULL nullptr`

> @fokkonaut ye @Ryozuki trys to sneaky break vanilla compability o.O

You don't know what you are talking about.

**Comment by Learath2** [comment]
I think the only nullptr actually needed is the one in `str.cpp` for the
test to appease the template resolver.

**Review by heinrich5991 — APPROVED** [review]
Thanks!

bors r+

**Pull request merged**
