### PR TITLE
Add Speedup tiles correctly at the border creation & remove tile layer extension restriction & fix the LastIndex buffer initlialization & setup non mipmap textures up correctly(texture completness)

### PR DESCRIPTION
**Pull request by Jupeyy**
Allows speedups to be drawn on extended range(out of map range) too.

### CODE REVIEW

**Comment by Jupeyy** [comment]
to be fair maps like aim 10.0 still are bad at zooming out, because the overlay is just based on the layer extension. still it should be more responsive up to some point.

**Comment by heinrich5991** [comment]
I don't really understand what this pull request is doing, but I'm willing to merge it. Could you please fix the style issues (braces go on a new line, static variables are called `s_*`).

**Comment by Jupeyy** [comment]
im too stupid for this job

**Pull request merged**
