### PR TITLE
Prediction fixes

### LINKED ISSUE #1671: Prediction valgrind complaints
```
==19973== Conditional jump or move depends on uninitialised value(s)
==19973==    at 0x5D8DC2B: sqrtf (in /usr/lib/libm-2.29.so)
==19973==    by 0x21F4DE: vector2_base<float> normalize<float>(vector2_base<float> const&) (vmath.h:71)
==19973==    by 0x21B99A: CCharacterCore::Tick(bool) (gamecore.cpp:171)
==19973==    by 0x3296C7: CGameClient::DetectStrongHook() (gameclient.cpp:2111)
==19973==    by 0x32823B: CGameClient::UpdatePrediction() (gameclient.cpp:1951)
==19973==    by 0x3249D3: CGameClient::OnNewSnapshot() (gameclient.cpp:1376)
==19973==    by 0x2414B2: CClient::Update() (client.cpp:2534)
==19973==    by 0x242DBE: CClient::Run() (client.cpp:2948)
==19973==    by 0x247B7D: main (client.cpp:3814)
==19973== 
==19973== Conditional jump or move depends on uninitialised value(s)
==19973==    at 0x21CE13: CCharacterCore::Tick(bool) (gamecore.cpp:427)
==19973==    by 0x3296C7: CGameClient::DetectStrongHook() (gameclient.cpp:2111)
==19973==    by 0x32823B: CGameClient::UpdatePrediction() (gameclient.cpp:1951)
==19973==    by 0x3249D3: CGameClient::OnNewSnapshot() (gameclient.cpp:1376)
==19973==    by 0x2414B2: CClient::Update() (client.cpp:2534)
==19973==    by 0x242DBE: CClient::Run() (client.cpp:2948)
==19973==    by 0x247B7D: main (client.cpp:3814)
==19973== 
==19973== Conditional jump or move depends on uninitialised value(s)
==19973==    at 0x21D2A6: CCharacterCore::Tick(bool) (gamecore.cpp:459)
==19973==    by 0x3296C7: CGameClient::DetectStrongHook() (gameclient.cpp:2111)
==19973==    by 0x32823B: CGameClient::UpdatePrediction() (gameclient.cpp:1951)
==19973==    by 0x3249D3: CGameClient::OnNewSnapshot() (gameclient.cpp:1376)
==19973==    by 0x2414B2: CClient::Update() (client.cpp:2534)
==19973==    by 0x242DBE: CClient::Run() (client.cpp:2948)
==19973==    by 0x247B7D: main (client.cpp:3814)
==19973== Conditional jump or move depends on uninitialised value(s)
==19973==    at 0x21D4FB: CCharacterCore::Tick(bool) (gamecore.cpp:461)
==19973==    by 0x3296C7: CGameClient::DetectStrongHook() (gameclient.cpp:2111)
==19973==    by 0x32823B: CGameClient::UpdatePrediction() (gameclient.cpp:1951)
==19973==    by 0x3249D3: CGameClient::OnNewSnapshot() (gameclient.cpp:1376)
==19973==    by 0x2414B2: CClient::Update() (client.cpp:2534)
==19973==    by 0x242DBE: CClient::Run() (client.cpp:2948)
==19973==    by 0x247B7D: main (client.cpp:3814)
```
valgrind --tool=memcheck reported this. Could you take a look @trml ?

### PR DESCRIPTION
**Pull request by trml**
I believe this fixes #1671 (uninitialized variables).

Some other things: Use new ddnetchar fields in prediction, small fix for prediction of moving pickups, fix the freeze end tick in ddnetcharacter (will add it to the client later)

Also adds a setting for choosing between new/old antiping for grenade like suggested in #1683 (cl_antiping_gunfire 0 to disable).

### CODE REVIEW

**Comment by fokkonaut** [comment]
We dont need the old antiping for grenade? The point he wanted is that you sync audio with visuals, e.g. firing grenade -> instant sound. Dont play the sound when you receive it, play it just clientside with the shot. (Also, the target cross is not synchronized with the weaponswitch, only if you receive the server packet, that you changed weapons)

**Comment by trml** [comment]
My impression was that it's not just about sounds, and getting sounds right is also a little bit of work (I dont have time right now). This was only thought of as an option to turn it off, and the new antiping would still be enabled by default.

**Comment by fokkonaut** [comment]
Oh, okay. Good then

**Comment by Learath2** [comment]
Could we maybe avoid `DetectStrongHook` by sending some id from the server in `DDNetCharacter`? Maybe something like a world entity id.

**Comment by trml** [comment]
@Learath2 It was added to DDNetCharacter previously (StrongWeakID) and is applied to prediction in this pr, so DetectStrongHook will now only be used on servers without DDNetCharacter.

**Comment by def-** [comment]
Your changes are large, let's merge and beta test?
bors r+

**Comment by trml** [comment]
Yes, that could be an idea.

**Pull request merged**
