### PR TITLE
Fix build which broke in 3 different ways

### PR DESCRIPTION
**Pull request by def-**
```
src/engine/client/backend/opengl/backend_opengl.cpp:1599: undefined reference to `__stack_chk_fail'
```
Still testing if this fixes the build. Edit: works

### CODE REVIEW

**Comment by Robyt3** [comment]
Does this also address `libssp-0.dll` not being found for Windows users when launching the client?

error

**Comment by heinrich5991** [comment]
Sorry for the troubles, it worked on my machine™.

**Comment by Jupeyy** [comment]
Please note the added bug

**Comment by Jupeyy** [comment]
> Sorry for the troubles, it worked on my machine™.

Or did it work on your Windows machine?

**Comment by def-** [comment]
I'Ll provide a fix

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Pull request merged**
