### PR TITLE
Add Esperanto language

### PR DESCRIPTION
**Pull request by dannyhpy**

### CODE REVIEW

**Comment by def-** [comment]
Very cool. Should we ask graphics community on Discord if someone can adapt an Esperanto flag?

**Comment by SoulyVEVO** [comment]
Esperanto

**Comment by blueskyGH** [comment]
Cool!
It would be great if you can extend the list for atleast those phrases:

"Your nickname '%s' is already used (%d points). Do you still want to use it?"
"There's an unsaved map in the editor, you might want to save it before you quit the game."
"Are you sure that you want to disconnect and switch to a different server?"
"Vote description:"
"Join blue"
"Join red"
"No servers match your filter criteria"
"Server executable not found, can't run server"
"You must restart the game for all settings to take effect."

And ofcourse everything else you are able to translate 😃

**Comment by dannyhpy** [comment]
> Very cool. Should we ask graphics community on Discord if someone can adapt an Esperanto flag?

@def-: Teeworlds already has one, posted [here](https://github.com/ddnet/ddnet/pull/5644#issuecomment-1189657195) by @SoulyVEVO t

**Pull request merged**
