### PR TITLE
Fix the CMake Mac build

### LINKED ISSUE #805: CMake build on OSX
Doesn't work yet

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #805.

### CODE REVIEW

**Comment by def-** [comment]
Thanks for working on this.

Windows build fails?

**Comment by heinrich5991** [comment]
Windows build tested an old commit. The error was not platform-specific, and I fixed it on macOS, should be fixed on Windows as well.

**Comment by heinrich5991** [comment]
You and the CI were right, the Windows build was indeed broken.

**Comment by heinrich5991** [comment]
Now we "only" need to fix the errors... Apparantly `CreateStandardAlert` and `RunStandardAlert` are deperecated: https://stackoverflow.com/questions/3783540/initcursor-createstandardalert-runstandardalert-not-declared-in-scope-wh#3791684.

**Comment by Learath2** [comment]
Maybe travis should only build OSX so we have one CI for each OS.

**Comment by heinrich5991** [comment]
Mh. I dunno, more testing = more better? :P

**Comment by Learath2** [comment]
This actually works on a real mac. 10.10.5 specifically. I got no warnings. If you have `opus` however you get `ogg/ogg.h not found` even if you have ogg.

**Pull request merged**
