### PR TITLE
Removed freeze tiles corners

### PR DESCRIPTION
**Pull request by BannZay**
Freeze usually placed on maps in groups, so corners make it worse. Its very tiny but it is there!
screenshot_2016-09-22_01-50-36

There is fixed (freeze, deepfreeze, undeep, etc...)
screenshot_2016-09-22_01-55-02

### CODE REVIEW

**Comment by def-** [comment]
Hey, I added that intentionally! Gametiles are for mapping, not for playing by the way. It's useful to easily estimate distances, for example how far you can hook.

**Comment by BannZay** [comment]
> Gametiles are for mapping

But half of users(including me) playing with entities 100 all the time. Weird decission.

> It's useful to easily estimate distances

I`m totally confused if you talking about freeze tiles(

**Comment by BannZay** [comment]
> Gametiles are for mapping
It changes everything

**Comment by Ekidoxx** [comment]
What about changing it just on `entities_clear` now a.k.a. `ddnet.png`, so that mappers will see the corners but players not?

**Comment by Ekidoxx** [comment]
Wasn't it that `entities_clear` are displayed only for entities overlay, so that mappers would still see corners in editor but players wouldn't during races?

**Pull request closed without merging**
