### PR TITLE
Set 5 as minimum mousesens instead of 0

### PR DESCRIPTION
**Pull request by nzyuzin**
The reasons behind this PR are discussed in line notes of 325410d2af897cb81196e2821e94a6fda5883e97.

### CODE REVIEW

**Comment by def-** [comment]
When we do this, then the 0 default value does not work. This breaks dyncam for every player and is exactly what I fixed.

**Comment by nzyuzin** [comment]
Did you actually test it? If cl_dyncam_mousesens is not in config files then it's set to 0 regardless of min value.

I don't see a *bug* that was fixed here, because it works as intended -- it's 0 before user sets the value himself and if he does set it then he can't set it lower than 5.

For sure I just tested it myself and it works as intended.

**Comment by heinrich5991** [comment]
@nzyuzin Calm down.

I guess the client would save the setting in the settings.cfg (`CFGFLAG_SAVE`) and then on next start the command `cl_dyncam_mousesens 0` will be executed and so `cl_dyncam_mousesens` will be set to 5 if I understand this correctly.

**Comment by nzyuzin** [comment]
I just checked that (deleted `cl_dyncam_mousesns`) from configs, opened/closed the client and it was saved as 0, not 5.

**Comment by nzyuzin** [comment]
Ok, my mistake.

It was set to 5 after client restart with `cl_dyncam_mousesens` being 0.

**Comment by heinrich5991** [comment]
Yes. And as I understand it, the command `cl_dyncam_mousesens 0` will be executed on next start. *This command* will set it to 5.

**Comment by nzyuzin** [comment]
Yeah, got it, thanks @heinrich5991!

**Pull request closed without merging**
