### PR TITLE
add dummy_copy and dummy_hammer hud viz

### PR DESCRIPTION
**Pull request by d3fault**
It's just text for now, I'm too lazy to make it a graphic. Someone else can do that in another commit.

Screenshot_2020-12-11_23-33-44

### CODE REVIEW

**Comment by heinrich5991** [comment]
Good idea. I wouldn't add it without graphics, it doesn't fit with the rest of the UI as text.

**Comment by d3fault** [comment]
> Good idea. I wouldn't add it without graphics, it doesn't fit with the rest of the UI as text.

[x] Allow edits and access to secrets by maintainers

**Comment by heinrich5991** [comment]
I don't intend to produce the graphics myself (I haven't done any graphics yet). This text output could go to some debug output, but as is, I'd prefer not to merge it (not even as a starting point for some graphics later™).

**Comment by Banana090** [comment]
I had the idea of something like that, but It really should be done using visual icons, as well as change whole top left HUD panel, showing all the info, not only dummy_copy/hammer

(Calling for render from GameTimer render sounds rly cool xD)

**Comment by d3fault** [comment]
I agree it should be a graphic, but I suck at graphics. If I made one yall wouldn't like it and we'd be in the same boat :-P (except I'd have wasted my time doing graphics). If we just publish it as-is, it will *itch* those aesthetically inclined types and they will *scratch* that itch asap. It would probably only be text for about 24 hours ;). Hell just accepting it into github's master branch will probably be enough to get someone to scratch that itch (before a ddnet.tw release is ever made).

**Comment by d3fault** [comment]
if nobody scratches the itch before it's time to make a ddnet.tw release (doubtful), revert

**Comment by Banana090** [comment]
How about just making full normal update, with good code

**Comment by Learath2** [comment]
Maybe we should ask around on discord, I'm sure someone would be interested to do the gfx for it.

**Comment by def-** [comment]
And not just for these 2. We should also get solo part, available weapons etc illustrated.

**Comment by heinrich5991** [comment]
Status: Waiting for graphics.

**Comment by Banana090** [comment]
@heinrich5991 I'm making my own with help of Ravie

**Comment by heinrich5991** [comment]
Status: Waiting for graphics, now there's a request on Discord.

**Comment by heinrich5991** [comment]
Status: Waiting for graphics, meme image is accurate. I don't think we'll get graphics by just waiting.

**Comment by ChillerDragon** [comment]
How is one even supposed to visualize dummy copy?

**Comment by d3fault** [comment]
> How is one even supposed to visualize dummy copy?

Any arbitrary graphic, perhaps 2 tees side by side executing the same action

**Comment by heinrich5991** [comment]
Status: We actually have visuals for that now. :o Check the Discord.

**Comment by def-** [comment]
@d3fault Any plans to add the graphics from https://discord.com/channels/252358080522747904/876771361706635296 or should someone else try?

**Comment by d3fault** [comment]
definitely not [anytime soon]. the text version is gud enuff 5 me B)

**Comment by C0D3D3V** [comment]
> @d3fault Any plans to add the graphics from https://discord.com/channels/252358080522747904/876771361706635296 or should someone else try?

I have already taken the first steps (https://github.com/c0d3d3v/ddnet/tree/New_HUD). I will implement the new HUD. I have already clarified this with Ryozuki and Ravie and we will stay in contact to discuss the details of how to best display it.

**Comment by def-** [comment]
Let's close this in favor of the upcoming change by @C0D3D3V

**Pull request closed without merging**
