### PR TITLE
Let the server decide which hud to display

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Looks okay to me. Could you change the capitalization from `HUD` to `Hud` in camel case names?

**Comment by fokkonaut** [comment]
> 

Mh?

**Comment by fokkonaut** [comment]
> Do you not one more flag for freezebar? If you want to show stars instead of freezebar.

Mh?

**Comment by fokkonaut** [comment]
> Do you not one more flag for freezebar? If you want to show stars instead of freezebar.

That should be a clientside option.

**Comment by fokkonaut** [comment]
> Looks okay to me. Could you change the capitalization from `HUD` to `Hud` in camel case names?

Done.

**Comment by C0D3D3V** [comment]
I do not like the client side option. But this would be in addition to client side option. You are a modder. I do not care. But If you want to display not the freeze bar... You could add a flag for that

**Comment by fokkonaut** [comment]
> I do not like the client side option. But this would be in addition to client side option. You are a modder. I do not care. But If you want to display not the freeze bar... You could add a flag for that

I want the players to decide what they want. I dislike to forbid things that players like, I try to give as much freedom as possible and also want that for myself then of course.

**Comment by fokkonaut** [comment]
As you can see in https://github.com/ddnet/ddnet/pull/5420 I am not the only one that likes to stick with the original design.

**Comment by C0D3D3V** [comment]
I also see no benefit at all in your OnHudChange function. You could just init all quads all the time. That is a onetime cost, should not be to problematic.

**Comment by C0D3D3V** [comment]
Mh ok I see now why you did it.

**Comment by C0D3D3V** [comment]
I'm not sure if calling OnHudChange, from outside the HUD component is the best way to solve this. But if the other think this is fine, then I think it is ok. 
@fokkonaut you can run `scripts/fix_style.py` in the project root

**Comment by fokkonaut** [comment]
> 

I am not that big of a client dev, could you maybe add a commit to this pr?

**Comment by C0D3D3V** [comment]
I will add this to https://github.com/ddnet/ddnet/pull/5420
And will try to replace RenderQuadContainer with RenderQuadContainerEx to avoid recreating of the Quads (at least I think that is more elegant, even if it is slightly less fast)

**Comment by fokkonaut** [comment]
But please, please keep the freeze stars and the option to disable the bar. Thanks❤️

**Comment by C0D3D3V** [comment]
freeze stars are removed, option to disable the bar is added back in :(
superseeded by https://github.com/ddnet/ddnet/pull/5420

**Comment by fokkonaut** [comment]
could we then do the freeze stars clientside for those clients with a flag or something? i dont know, they should not be removed entirely

**Comment by fokkonaut** [comment]
And they should also not be forced for the future. I think they should just stay, i mean i dont think they hurt as much

**Comment by C0D3D3V** [comment]
They are damage indicators not thawing indicators.

**Comment by fokkonaut** [comment]
I like it too, and its definitely useful for some, but I personally like the look of the stars and also find them useful for a good estimation when freeze ends (ofc bar can do that too, but the bar is not teeish. I also like tw because of its teeishness and simpleness.)

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Comment by heinrich5991** [comment]
Oh, clang-format still failing. @fokkonaut

**Comment by def-** [comment]
Done
bors r+

**Comment by def-** [comment]
bors retry
Haven't seen this before:
```
/Users/runner/work/_temp/3a1b4853-aaa3-481a-a58e-308c40fe9cfe.sh: line 2: 11917 Segmentation fault: 11  ./DDNet-Server shutdown
```

**Comment by def-** [comment]
@fokkonaut Related to this change? https://github.com/ddnet/ddnet/runs/7026442944?check_suite_focus=true

**Comment by C0D3D3V** [comment]
It is maybe  because he does not unfree the quads.
superseeded by https://github.com/ddnet/ddnet/pull/5420

**Pull request closed without merging**
