### PR TITLE
Ship map_convert_07 executable, allow drag'n'drop and ship Gold Mine map (with sixup version) instead of Kobra 4 and Goo!

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Should ship maps which we're allowed to ship instead.

We haven't been able to contact the authors of Goo! and Kobra 4 I think.

**Comment by def-** [comment]
ok, let's just take a 1 star novice map then. any we have licensed or mapper ready to license?

**Comment by heinrich5991** [comment]
We can take Gold Mine by <BµmM>, now licensed under CC-BY-SA.

**Comment by def-** [comment]
Done.

**Comment by def-** [comment]
A second map would be nice too.

**Comment by def-** [comment]
bors r+
I'll put this in for release now.

**Pull request merged**
