### PR TITLE
[Concept] Add new mouse state (ingame mouse)

### PR DESCRIPTION
**Pull request by Jupeyy**
This would remove ui_mousesense and use the desktop cursor position instead for menus and editor
This would also fix the editor cursor to not move faster than in menus.
That's probably how most games would handle menus, instead of using relative mouse mode
And this would work for touch inputs.

The normal gameplay relative mouse is ofc NOT affected by any kind

Opinions?

Missing:
- [x] m_MouseSlow in menus
- [x] Make desktop cursor invisible
- [x] Some components that use ui mouse
- [x] Remove focus in/out relative mouse state changes, fixed with next SDL version

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
I personally would still like a modifier for UI mousesense, as I play with lower UI mouse sense in tw than my desktop sense.

**Comment by Jupeyy** [comment]
> I personally would still like a modifier for UI mousesense, as I play with lower UI mouse sense in tw than my desktop sense.

Why tho, doesnt it make most sense to have it just like on desktop, you can just increase the desktop mouse speed?

**Comment by edg-l** [comment]
I'm in favour of adding this, one is usually already used to the sense of your desktop

**Comment by Jupeyy** [comment]
For me and (probably all windows, not tested) users it also fixes the resize dragging of the window corners (gfx_resizable 1)

2 ideas i had generally that would benefit from this:
- We could also (__optionally__) allow to not grab the input while in editor for example (makes the editor more like a desktop program)
- We could add an option for tournament streamers, while they are in spectators to not grab the input, allows easier switching between multiple instances

**Comment by Learath2** [comment]
Not grabbing in the editor sounds like a great idea. I overall like this PR but I wonder if macOS will like it. Will check tonight.

**Comment by Jupeyy** [comment]
> Not grabbing in the editor sounds like a great idea. I overall like this PR but I wonder if macOS will like it. Will check tonight.

Nice, generally there were two problem without the new SDL version:
- that the cursor is invisible when the window is NOT focused and relative mouse mode isnt deactivated, e.g. the ingame cursor,  (i removed the deactivation in this pr and added an issue under SDL and also a fix, bcs triggering that event on ddnet side, caused desktop fullscreen always trap the mouse under windows(its a mix of bug between our code and SDL under windows
`https://github.com/libsdl-org/SDL/pull/4683`)
- cl_mouseold caused teleport glitches, when mouse mode wasn't deactivated, but that is fixed in new SDL too (`https://github.com/libsdl-org/SDL/pull/4683#issuecomment-914539146` (the edit: part))
Rest should also work with old SDL I think

**Comment by heinrich5991** [comment]
I like this PR.

**Comment by heinrich5991** [comment]
I tested it, I don't notice any difference. This is good I guess? :)

**Comment by Jupeyy** [comment]
> I tested it, I don't notice any difference. This is good I guess? :)

Thanks for testing.
On default setting ui_mousesens is 200, which should make the mouse move way faster than you expect from your window cursor, also if you use accelerated mouse in your DE, it will feel different ingame(if you dont use mouse old).[might also depend on resolution, i dunno how exactly relative mouse movement differs from flat mouse in DEs]

The biggest change however is in the editor, in the current version the cursor in the editor moves really fast and random
Now it should move the same as the menus

**Comment by heinrich5991** [comment]
Is this good to be merged? @Jupeyy

**Comment by Jupeyy** [comment]
I tested it on windows and linux, so from my side fine
But can't test macOS

**Comment by def-** [comment]
I say let's try it in an RC.
bors r+

**Pull request merged**
