### PR TITLE
Sort spectator view by team, then name (not score) (fixes #2808)

### LINKED ISSUE #2808: Sort players in spectator mode alphabetically regardless of their rank
Right now in both the scoreboard and when in spectator mode, players are sorted first by who-has-better-rank-time in let's call it group A, and then, whoever doesn't have finish is sorted alphabetically in group B - and that's annoying af since years.

This kind of sorting does have sense in the scoreboard, because there you want to see who's best, but in the list in spectator mode its making it so much harder to find the player you want, since you have to go thru the whole list one-by-one as the player can be placed anywhere.

The command `/spec <nick>` is not much helping due to allowing nearly all of unicode characters in nickname, and as of so it happens to be even more annoying than just checking one nick after another in spectator mode.

So please, make the list in spectator mode sorted fully alphabetically, regardless of one's rank. And if there are teams, list them at very end (as it is currently) though with still keeping the alphabetical order of its members' nicks.

---

image
image

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by fokkonaut** [comment]
Against this, they should stay sorted the same way as scoreboard is. In my 0.7 client I found it very annoying having spectators not sorted the same way as scoreboard, so I needed to add that.

**Comment by Jupeyy** [comment]
I think in general alphabethical sorting is the easiest to read, and since the score isn't displayed in spec i don't see a reason not to change this

**Comment by def-** [comment]
I was also not sure initially, but in the end I think it's better by name.

**Comment by def-** [comment]
I made a vote on Discord #announcements channel

**Comment by gerdoe-jr** [comment]
20+ ppl voted for Yes.

**Comment by Jupeyy** [comment]
ok, i think the vote is pretty one sided.
If fokkonout really needs the other sorting he can still add a sorting button, or config variable.

bors r+

**Pull request merged**
