### PR TITLE
only send isddnet to server if gametype is ddnet

### PR DESCRIPTION
**Pull request by timgame**

### CODE REVIEW

**Comment by east** [comment]
We should improve IsDDNet() to support ddnet based gametypes aswell before doing this patch.

**Comment by heinrich5991** [comment]
I think we should just use Learath2's proposal now, extend NETMSG_NULL.

**Comment by timgame** [comment]
@heinrich5991 how is that related to this pr?

**Comment by heinrich5991** [comment]
Because sending which features you support shouldn't depend on the gametype string in my opinion.

**Comment by east** [comment]
Yes, this also was discussed before. First we should get rid of the gametype as dependency for ddnet features.

**Comment by timgame** [comment]
But as long as it depends on the gametype we can merge this, you cant rename the gametype of your ddnet mod so that it doesnt match IsDDNet anyways, the client expects another protocol (for example for grenades) then.

**Comment by heinrich5991** [comment]
But it explicitly should not depend on the game type.

**Comment by east** [comment]
There are mods online based on ddnet using another gametype name. Not sure though whether there will be further incompatibilities with this patch.

**Comment by timgame** [comment]
@east, actually i would like to do exactly this, but it doesnt work because the client expects another protocol because it thinks the server is not ddnet but the server knows that the client is ddnet and sends the ddnet protocol.

**Comment by timgame** [comment]
I'll start working on a solution without the gametype now.

**Comment by heinrich5991** [comment]
You could complete the work by Learath2.

**Comment by east** [comment]
Hmm... As long as we are improving IsDDNet() for the next release, this pr could be merged I guess.

**Comment by heinrich5991** [comment]
Is there a current issue that this is trying to address?

**Comment by timgame** [comment]
I cant see how these 2 lines Learath2 added to client and server can change how IsDDNet works. I didnt look into what these are doing though.

**Comment by east** [comment]
Iirc it's about implementing a sub-protocol for ddnet, so we can create further netmessages. His patch was quite short, yes.

**Comment by H-M-H** [comment]
It would really be nice to have a ddnet subprotocol and yes I agree with heinrich5991: protocol should not depend on the gametypestring. Btw could someone point me to the code that limits the number of netmessages ?

**Comment by heinrich5991** [comment]
Three things:
1) Forward compatiblity with vanilla, we don't want to clash with future versions of the vanilla protocol.
2) Compatiblity with other mods, we don't want to use the same message IDs as they do.
3) The hack used in message packing only works for integers up to 32 or so.

**Comment by timgame** [comment]
But can we merge this for now?

**Comment by heinrich5991** [comment]
Is there a problem that this pull request tries to address? If not, I don't think we need to change this now.

**Comment by timgame** [comment]
Okay, we won't merge this,

**Pull request closed without merging**
