### PR TITLE
Don't check dnsbl when alone

### PR DESCRIPTION
**Pull request by Learath2**
Should help relieve some of the issues reported on discord.

### CODE REVIEW

**Comment by def-** [comment]
Have you tested this? It looks like SinglePlayer will always be true.

**Comment by heinrich5991** [comment]
Random idea: Votes could also work if there are *only* dnsbl-ed players.

**Comment by Learath2** [comment]
> Have you tested this? It looks like SinglePlayer will always be true.

Hadn't tested it, but the variable was called `NotAlone`, forgot to negate when changing the name.
I still haven't tested it but it looks sane enough. I can test it tomorrow when I get home.

**Pull request merged**
