### PR TITLE
Don't allow infinite shotgun bounce (fixes #4809)

### LINKED ISSUE #4809: /tp in /practice leads to shotgun abuse
from my messages in #bugs recently:

image
image

how to do it: go into /practice in a team, /tp to a shotgun (or laser, but sg is faster) on the map, and then /tp inside of a block, then hold down shotgun

this both lags the server over time (you need about 15 minutes and 10 people holding down sg, but it causes significant spikes) and causes massive hearing loss to anyone unfortunate enough to have /showothers enabled near the shotgun spams

### PR DESCRIPTION
**Pull request by def-**
I hope this kind of physic isn't used anywhere, I couldn't trigger it without being stuck in wall.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
This fixes server lag, but doesn't fix sound being audible from other teams

**Comment by def-** [comment]
Was this part of #4809 ?

**Comment by Chairn** [comment]
Yes, when louis did that, it spammed a very acute sound on team 0

**Comment by C0D3D3V** [comment]
@Chairn I have just tested the change, you only hear a normal shotgun shot and that only in your own team. In team 0 you do not hear the shot. You also hear no bounce and it is normally loud. 

Have you tested the changes on a local server?

**Comment by Chairn** [comment]
Louis and his mates where in team, they /tp near to us with shotgun inside blocks. They started spamming it, and we were hearing it while playing in team 0.

**Comment by C0D3D3V** [comment]
Did you have /showothers on?

**Comment by C0D3D3V** [comment]
I think this PR will also fix this. The problem was if you turn showothers of, that the laser entitie is still there and bounce around. But with this patch it is instant away.

**Comment by heinrich5991** [comment]
bors r+

Let's hope this doesn't break anything.

**Pull request merged**
