### PR TITLE
Don't rely on snapshot for ddnet gametype

### PR DESCRIPTION
**Pull request by Jupeyy**
@fokkonaut you need to test again if you mod works.
This time i also did the test for masked entites(but not for non masked ones).

### CODE REVIEW

**Comment by Jupeyy** [comment]
good that we have rc now xd

**Comment by fokkonaut** [comment]
Close this please. That was the whole idea of the GameInfoEx Snap, that it could be modified ingame and also does not require any other "gametype checks" like it used to.

**Comment by Jupeyy** [comment]
Chill, the gameinfoex is still respected, just not in the HasSpeedlayer or stuff like that, that should not be checked with the gameinfo. bcs the snapshot is sent too late

**Comment by Jupeyy** [comment]
@fokkonaut if ur mod works all is fine isnt it?, i check the masked entities, you need to check that unmasked work please

**Comment by fokkonaut** [comment]
Okay. I will give it a try later

**Comment by heinrich5991** [comment]
Can you explain what this changes? From reading the source code, it seems identical in behavior to me.

**Comment by Jupeyy** [comment]
Sure. The first snap shot didn't send isddnet flag. And since I removed unknown mod type in a previous commit. It defaults to ddnet now

Also don't mask entities is false on the first enter

So mod is ddnet but ddnet flag is not set and entities are masked

Results in broken ddnet entities

**Comment by heinrich5991** [comment]
> The first snap shot didn't send isddnet flag.

Are you sure? It seems to unconditionally send the `CNetObj_GameInfoEx`:

https://github.com/ddnet/ddnet/blob/2a3b254b4793930a0d19efaf8494a521d6668fca/src/game/server/gamecontroller.cpp#L538-L560

Since the intention is to support live switching of entities, this seems like the wrong fix.

**Comment by Jupeyy** [comment]
I entered ddnet looked if it enters the isddnet check on function top.... It didn't.. So I assumed the snap shot is sent too late

**Comment by Jupeyy** [comment]
Live switching still works. It's just for building the entities

**Comment by Jupeyy** [comment]
ok another try:
first of all the title might be missleading:
Don't rely on snapshot for ddnet entities building process

2nd, @heinrich5991 you probs didnt saw that i changed the behaviour to support not masking for all mods individually, bcs fokko complained about it

and 3rt,
Everything inside `if(!m_EntitiesIsLoaded[EntitiesModType + (int)EntitesAreMasked])`
should now be defined behaviour independent on what happens outside(except some uninitialized memory :D)

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by def-** [comment]
@heinrich5991 is it good now?

**Comment by def-** [comment]
Seems to work fine to me.

**Comment by heinrich5991** [comment]
@def- It is good now, but @Jupeyy asked me to cancel merging.

**Comment by Jupeyy** [comment]
yeah updated what we discussed in discord

**Comment by heinrich5991** [comment]
bors r+

Thanks! :)

**Pull request merged**
