### PR TITLE
Add /modhelp chat command

### PR DESCRIPTION
**Pull request by Ryozuki**
- Adds the chat command /modhelp <message>
- It sends `Moderator help is requested by %s (ID: %d):\nproblem here...` to all authed clients.
- The command has a configurable delay to prevent spam, defaults to 60 seconds.

### CODE REVIEW

**Comment by Learath2** [comment]
You could just type it out in chat :/ I feel this is pointless unless it works across servers.

**Comment by 12pm** [comment]
I think this is useful. Sometimes you don't want to publicly complain or ask for help. Also, you might not know who is a mod. 
It might not be really be needed, but it makes asking for help more convenient.

If a user uses this command and no one is authed, it should say for the user that there is no mod on the server.

**Comment by heinrich5991** [comment]
It would we good if we had some sort of command that could notify external services, such as the Discord server. As it stands, I don't think it's particularly useful. If the command notified the user about no one listening, then it'd have the same downside as https://github.com/ddnet/ddnet/pull/1001#issuecomment-374422269.

**Comment by heinrich5991** [comment]
Reopened on request by @Ryozuki.

**Comment by def-** [comment]
Let's try this out. Can still remove it if someone implements something better later.

**Pull request merged**
