### PR TITLE
Fix collecting weapon in solo part not making any sound.

### LINKED ISSUE #2219: TeamMask in pickup.cpp
All team masks in pickup.cpp for the sounds are without passing the asker, so `pChr->Teams()->TeamMask(pChr->Team())` should be `pChr->Teams()->TeamMask(pChr->Team(), -1, pChr->GetPlayer()->GetCID())`

### LINKED ISSUE #3822: collecting weapon in solo part doesnt make sound
when /showothers is on it does

edit:: does make a sounds for others outside of solo, with /showothers off

### PR DESCRIPTION
**Pull request by edg-l**
fixes #3822
fixes #2219

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
And you are sure `i` is the correct way? kinda looks wrong to me to use a iterator
wouldn't something like `pChar->m_pPlayer->GetCID()` be more logical?

**Comment by edg-l** [comment]
@Jupeyy do you like it more now?

**Comment by Jupeyy** [comment]
ngl i don't even know what it does under the hood, just saw it randomly xd

**Comment by edg-l** [comment]
Fixes #2219 too

**Pull request merged**
