### PR TITLE
Add crude backward compatibility for weapon shields

### LINKED ISSUE #5039: Specific weapon removal shields not shown in vanilla
https://github.com/ddnet/ddnet/pull/4728#issuecomment-1112860690

I forgot the vanilla compatibility of this feature.

The thread already has a small discussion about it. Perhaps we could simply show a normal shield as @Zoozti proposed?
>I think its the best way to just show vanilla/old client players a normal shield. So they see they will lose weapons and dont get surprised by an invisible tile

CC @C0D3D3V @def- @edg-l @fokkonaut @Zoozti

### PR DESCRIPTION
**Pull request by heinrich5991**
They only display as shields.

Fixes #5039.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Untested, don't merge yet.

**Comment by C0D3D3V** [comment]
Will probably make old clients do prediction errors. But this should be acceptable.

**Comment by C0D3D3V** [comment]
15.9.1 xD rofl
grafik

Your build:
grafik

**Comment by C0D3D3V** [comment]
btw there is also an out of bound array access in old clients here in RenderPickup()
grafik
https://github.com/ddnet/ddnet/blob/1110e1592aa36459c9a9daf38fba5ab1e90ee860/src/game/client/components/items.cpp#L138-L167

But I already fixed it in #5085

**Comment by C0D3D3V** [comment]
You should make a check if it is actually a special shield, or not?
```
if(m_Type >= POWERUP_ARMOR_SHOTGUN && m_Type] <= POWERUP_ARMOR_NINJA)
{
pPickup->m_Type = POWERUP_ARMOR;
}
```

**Comment by C0D3D3V** [comment]
ah sorry this is 15.9.1 with a server on your build, the screenshot above was 16.0.3 server
grafik

**Comment by C0D3D3V** [comment]
maybe we could send disabled shields, that are switch layer with number 0, so that the old clients do not mispredict

**Comment by heinrich5991** [comment]
@C0D3D3V If you want, you can take this over. :) If not, I'll probably find some time to update it at some point.

**Comment by C0D3D3V** [comment]
I tried to send disabled shields. I had no success. The condition from above should be enough to fix it. It only needs to be POWERUP_ARMOR_LASER not POWERUP_ARMOR_NINJA in the condition.

**Comment by def-** [comment]
I'll release 16.1 without this. We don't have any maps using weapon shields yet anyway.

**Pull request closed without merging**
