### PR TITLE
Sixup needs it's own maps

### PR DESCRIPTION
**Pull request by Learath2**
Preliminary testing suggests this works fine. Albeit it is not the prettiest thing ever.

### CODE REVIEW

**Comment by def-** [comment]
Looks good on a quick glance. Did you test with a map that embeds graphics in 0.6?

**Comment by Learath2** [comment]
I tested whether I could load two different maps, one edited a bit and I can. I didn't test embeds specifically.

**Comment by def-** [comment]
Ok, good enough.

**Pull request merged**
