### PR TITLE
Add sv_old_grenade

### PR DESCRIPTION
**Pull request by def-**
Easier solution for https://github.com/ddnet/ddnet/pull/1091

### CODE REVIEW

**Comment by heinrich5991** [comment]
I'm not opposed to this solution, the other one is probably really overengineered. :/

**Comment by def-** [comment]
Well, your solution is probably better if we expect to find more bugs, and to have a list of affected CRCs, for teehistorian as well. So I'm not sure. But let's not keep the players waiting any longer.

**Comment by gamertyp** [comment]
This fix here is a lot better, makes more sense, less complicated, more usable, doesn't need changes in code to change a design bug on the map, ...

**Comment by heinrich5991** [comment]
@gamertyp The code in the merged pull request doesn't need changes in the code to change a design bug on the map. In fact, it's this pull request that leaves existing maps unfixed.

**Pull request closed without merging**
