### PR TITLE
Always show dragger/hook when attached far away

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
There was a map where this was causing huge bandwidth problems for the server, which is why I disabled it.

**Comment by fokkonaut** [comment]
> There was a map where this was causing huge bandwidth problems for the server, which is why I disabled it.

I explained the problem of the draggers here: https://github.com/ddnet/ddnet/issues/3622

**Comment by fokkonaut** [comment]
It's only for the case that a mapper increased the dragger range and makes a dragger drag you that is outside of your view range. You cant see it, only with /showall or when zooming out as much that you can see the dragger.

**Comment by C0D3D3V** [comment]
You could add the networkclip next to the target networkclip as an and condition. So if the player does not se the taeget he still gets the dragger if he sees the dragger.

**Comment by fokkonaut** [comment]
> You could add the networkclip next to the target networkclip as an and condition. So if the player does not se the taeget he still gets the dragger if he sees the dragger.
> 
> ```
> if(pTarget && NetworkClipped(SnappingClient, pTarget->m_Pos) && NetworkClipped(SnappingClient, m_Pos))
> 			continue;
> ```

Thought about that too, but thats not how it was before so I thought I'd do it like this. If @def- wants, sure.

**Comment by C0D3D3V** [comment]
>    Thought about that too, but thats not how it was before so I thought I'd do it like this. If @def- wants, sure.

Before it was in xD just not in this condition.... So just put it back in
With the rest I'm happy, I will test it later this day. This seems to be the first step to avoid sending unnecessary dragger data to the client. 

This could probably also make jao shooter playable.

**Comment by C0D3D3V** [comment]
Now I understand what you want to do with the split of the loop. You just want to prevent that a CNetObj_EntityEx is sent. I don't think that will do much. I thought that all 64 CNetObj_Lasers are always sent, but this is not true. So it won't improve anything with jao shooter.

**Comment by fokkonaut** [comment]
> Now I understand what you want to do with the split of the loop. You just want to prevent that a CNetObj_EntityEx is sent. I don't think that will do much (but better than nothing). I thought that all 64 CNetObj_Lasers are always sent, but this is not true. So it won't improve anything with jao shooter.

Thats not what I am trying to do. I want to show draggers, when they are not in range and a tee is still connected to it. The loop split is to prevent entityEx being sent without a matching dragger.

**Comment by C0D3D3V** [comment]
This will btw. not send draggers if the taget is not in view. If you want to send draggers, with target and start pos is out of view, you would have to check if the laser intercepts the view. 

You could also prevent the sending of CNetObj_EntityEx with only one bool, instead of a list and a bool. Just check if it the first dragger that is send, and if it is send CNetObj_EntityEx, for all other skip that.

**Comment by fokkonaut** [comment]
> This will btw. not send draggers if the taget is not in view. If you want to send draggers, with target and start pos out of view, you would have to check if the laser intercepts the view.

I know. But that is not as important and I just wanted to make it possible for the two mappers that a player can see his own dragger, even when far away. I did not plan on making a general overhaul of the dragger class.

**Comment by heinrich5991** [comment]
> 1. Player hooks are now always shown when attached to a wall or a tee when in your viewing range, no matter how far the tee is away (will get sent now when hookpos is in range)

This is not that much of an improvement, it's just making the heuristic a little better.

>> This will btw. not send draggers if the taget is not in view. If you want to send draggers, with target and start pos out of view, you would have to check if the laser intercepts the view.
> I know. But that is not as important and I just wanted to make it possible for the two mappers that a player can see his own dragger, even when far away. I did not plan on making a general overhaul of the dragger class.

I think this would be the proper fix, it should also not be that hard: Perhaps just check whether the closest point on the hook/dragger line is within max(width/2, height/2) of the player's camera center.

**Comment by fokkonaut** [comment]
While at it, https://github.com/ddnet/ddnet/blob/e3eeec762d0634d93aef6d076e6c414e013ff9d2/src/game/server/entity.cpp#L90
has a problem, it doesnt take showdistance / 2.
In my mod, I use showdistance.xy / 2 + 6*32

**Comment by C0D3D3V** [comment]
Would this also fix missing hooks like in the case? The top tee also hooks an other tee above him.
grafik

**Comment by C0D3D3V** [comment]
I included all your changes and fixed them in https://github.com/ddnet/ddnet/pull/5063. You can close this PR

**Comment by C0D3D3V** [comment]
> Would this also fix missing hooks like in this case? The top tee also hooks an other tee above him. grafik

I tried it, it would not be fixed. But it is fixed with https://github.com/ddnet/ddnet/pull/5063/commits/0672d0fffbce2f5252e4aff4f8c415bcfd370ef7

**Comment by heinrich5991** [comment]
> I included all your changes and fixed them in #5063 (at least most xD). You can close this PR

Superseded by #5063.

**Pull request closed without merging**
