### PR TITLE
Mod Support: CMake: Use DDNet_VERSION to construct DDNET_VERSION_NUMBER

### PR DESCRIPTION
**Pull request by Kaffeine**
`CLIENT_VERSIONNR` is used to declare DDNet protocol capabilities. It makes no sense for a forked client to suddenly report different DDNet client version for the same codebase. Equally for the server code it makes no sense to report `SERVER_DEMO_CLIENT` DDNet version different (lower) than what is supported by this code base (and e.g. record network events generated for some old client version).

This way **the mods can and should define their project with own version after DDNet `project()`** to
1. Use their version number in updater, packages, and in-game version info but also
2. Keep the original DDNet `DDNetVersion` number on the network level.

Example `CMakeLists.txt`:
```diff
 # Set version if not explicitly set
 if(NOT VERSION)
   set(VERSION 17.2.1)
 endif()
 
 project(DDNet
   VERSION ${VERSION}
 )
 
+project(Infclass
+  VERSION 0.1.7
+)
+
 set(ORIGINAL_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
 set(ORIGINAL_CMAKE_REQUIRED_INCLUDES ${CMAKE_REQUIRED_INCLUDES})
 set(ORIGINAL_CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES})
 set(OWN_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${PROJECT_SOURCE_DIR}/cmake)
 set(CMAKE_MODULE_PATH ${OWN_CMAKE_MODULE_PATH})
```

This way I have infclass-0.1.7 packages and 0.1.7 version displayed in the game, and also have proper `DDNetVersion=17021` on the network level.

Before this change, the game 'd identify itself as `DDNetVersion=0017`.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by heinrich5991** [comment]
I think it'd make sense to get rid of the CMake parsing the version entirely, as two `project` calls look unintended to me.

**Comment by Kaffeine** [comment]
> I think it'd make sense to get rid of the CMake parsing the version entirely

IOW you want to set the (network) `DDNET_VERSION_NUMBER` explicitly? But the current automatic implementation is safe, and in case of manual setup we can make mistakes like in https://github.com/ddnet/ddnet/pull/6970/files

> as two `project()` calls look unintended to me

100% legal and documented feature. I'd prefer to just `set(DDNet_VERSION 17.2.1)` but it does not give us `DDNet_VERSION_MAJOR`/`DDNet_VERSION_MINOR`/`DDNet_VERSION_PATCH` like the `project()` call.

**Comment by heinrich5991** [comment]
> 100% legal and documented feature.

The documentation page doesn't tell me it's supposed to be used for parsing version numbers. What text did you interpret to find that something like this is a documented feature?

**Comment by Kaffeine** [comment]
> it's supposed to be used for parsing version numbers

I said (meant) that subsequent calls to `project()` are documented, and also that `project()` set version variables.

E.g. it is documented here: https://cmake.org/cmake/help/v3.27/variable/CMAKE_PROJECT_NAME.html#variable:CMAKE_PROJECT_NAME

And the set of the version is documented at your link.

>  Takes a `<version>` argument composed of non-negative integer components, i.e. `<major>[.<minor>[.<patch>[.<tweak>]]]`, and sets the variables
> -    PROJECT_VERSION, <PROJECT-NAME>_VERSION
> -    PROJECT_VERSION_MAJOR, <PROJECT-NAME>_VERSION_MAJOR
> -    PROJECT_VERSION_MINOR, <PROJECT-NAME>_VERSION_MINOR
> -    PROJECT_VERSION_PATCH, <PROJECT-NAME>_VERSION_PATCH
> -    PROJECT_VERSION_TWEAK, <PROJECT-NAME>_VERSION_TWEAK.


I'm not going to say that it is the version parser but in case of DDNet forks it is convenient, as the forks won't have to maintain DDNet net version and won't have conflicts in
```diff
-set(VERSION 17.2.1)
+set(VERSION 17.2.2)
```
```diff
-set(VERSION 17.2.2)
+set(VERSION 17.3)
```
etc.

DDNet can provide and change `HOMEPAGE_URL`, `DESCRIPTION`, etc without conflicts in forks, and all those use-cases are documented for multiply `project()` calls: https://cmake.org/cmake/help/latest/variable/CMAKE_PROJECT_DESCRIPTION.html

**Comment by Kaffeine** [comment]
As I've [said](https://github.com/ddnet/ddnet/pull/7145#discussion_r1319156175)
> I checked `-DVERSION=18.0`, `18.1`, `18.1.0`, `18.1.1`, `18.99`, `18.99.1`, `18.999` (this one leads to error in https://github.com/ddnet/ddnet/pull/7145/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR149)

So you're building with current date as the version? Uh, I didn't expect that (and there is no clue in the script).
What is the wanted behavior? You want to build version `20230913` with the net version from the last release (`17021`)?

**Comment by Kaffeine** [comment]
Do you need this ASAP or 4 hours later is OK?

**Comment by def-** [comment]
It's been broken for 5 days, so 4 hours won't hurt :D

**Comment by heinrich5991** [comment]
I guess it'd be best if the network version is not modified by any custom version that is passed in. It doesn't really make sense for it to do so.

**Comment by Kaffeine** [comment]
I'm sorry I can't get to it today. I'll submit a proper solution tomorrow.

**Pull request merged**
