### PR TITLE
Add mod name to ban reason

### PR DESCRIPTION
**Pull request by Learath2**
Don't quite remember why I made this :)

### CODE REVIEW

**Comment by Learath2** [comment]
Don't know the cmake magic needed to make this work :/

**Comment by H-M-H** [comment]
This is nothing about cmake but about a missing argument in CNetBan::Init for masterservers: https://github.com/ddnet/ddnet/blob/9da2655ea7b04bbdde38f78fef970011367dc741/src/mastersrv/mastersrv.cpp#L345

**Comment by heinrich5991** [comment]
Is this feature wanted?

**Comment by def-** [comment]
no

**Pull request closed without merging**
