### PR TITLE
"Always show start screen" option on the start screen

### PR DESCRIPTION
**Pull request by Jupeyy**
Would this be ok for you @def- ?

The setting in general isn't very intuitive to find, as you saw in discord, many already complained

screenshot_2020-09-19_16-16-44

### CODE REVIEW

**Comment by Jupeyy** [comment]
ah have to fix for 5:4

**Comment by Ekidoxx** [comment]
Is it really necessary to break so simple screen with option that is easily accessible in settings if someone even bothers to check for it?

**Comment by Jupeyy** [comment]
Don't really want to judge about such things, but always consider the worst case, when making changes :D

**Comment by fokkonaut** [comment]
I would call it `Skip start menu` instead

**Comment by def-** [comment]
This should use the same name as in settings so we only have to localize once.

**Comment by Jupeyy** [comment]
Skip the main menu

main sounds wrong
menu isnt a nice word

but ok idc

**Comment by def-** [comment]
Then rename both to be consistent

**Comment by Jupeyy** [comment]
i dont want to start a debate xD, i just use the right localize now, should be fine, nobody will care xD

**Comment by edg-l** [comment]
Tested and works

**Comment by def-** [comment]
screenshot-20200922@142340
The spacing is a bit close for translations. But then we have the same problem in many places. Should we maybe find a more general solution for that and scale too large texts down automatically? I guess that would look a bit ugly though.

**Comment by def-** [comment]
I made a vote on Discord.

**Comment by Jupeyy** [comment]
I thought about a marquee, but that would require more state saving for the individual text boxes, which'd like to see anyway, bcs then, we can enable buffering for them xd

**Comment by def-** [comment]
Maybe we should just have added a text about that in the in-client news instructing old players how they can turn off the start screen?

**Comment by Jupeyy** [comment]
I'd be ok with that too, so let others decide :D

**Comment by def-** [comment]
I have written the news, let's hope that's enough for now. Otherwise we can revive the PR.

**Pull request closed without merging**
