### PR TITLE
Fix memory leaks and related.

### PR DESCRIPTION
**Pull request by Ryozuki**
Don't merge yet.

I want to use this pr to fix several leaks and stuff, if you find something you can report it here.

[valgrind-out.txt](https://github.com/ddnet/ddnet/files/4451261/valgrind-out.txt)

### CODE REVIEW

**Comment by heinrich5991** [comment]
👍

**Comment by Ryozuki** [comment]
[valgrind-out.txt](https://github.com/ddnet/ddnet/files/4451647/valgrind-out.txt)
This one has --gen-suppressions=all

**Comment by heinrich5991** [comment]
Requested reminder:

```
==103327== Conditional jump or move depends on uninitialised value(s)
==103327==    at 0x2253E3: str_utf8_decode (system.c:3116)
==103327==    by 0x28BA4D: CTextRender::TextEx(CTextCursor*, char const*, int) (text.cpp:920)
==103327==    by 0x28AF7D: CTextRender::TextWidth(void*, float, char const*, int, float*) (text.cpp:752)
==103327==    by 0x3622C4: CUI::DoLabel(CUIRect const*, char const*, float, int, int) (ui.cpp:390)
==103327==    by 0x380A73: CEditor::RenderStatusbar(CUIRect) (editor.cpp:4701)
==103327==    by 0x3870C9: CEditor::Render() (editor.cpp:5863)
==103327==    by 0x38902C: CEditor::UpdateAndRender() (editor.cpp:6280)
==103327==    by 0x25484C: CClient::Run() (client.cpp:3081)
==103327==    by 0x259F70: main (client.cpp:4079)
==103327==  Uninitialised value was created by a stack allocation
==103327==    at 0x3805AA: CEditor::RenderStatusbar(CUIRect) (editor.cpp:4645)
==103327== 
{
   <insert_a_suppression_name_here>
   Memcheck:Cond
   fun:str_utf8_decode
   fun:_ZN11CTextRender6TextExEP11CTextCursorPKci
   fun:_ZN11CTextRender9TextWidthEPvfPKciPf
   fun:_ZN3CUI7DoLabelEPK7CUIRectPKcfii
   fun:_ZN7CEditor15RenderStatusbarE7CUIRect
   fun:_ZN7CEditor6RenderEv
   fun:_ZN7CEditor15UpdateAndRenderEv
   fun:_ZN7CClient3RunEv
   fun:main
}
```

and related are not false positives, `TextEx` reads beyond the string it got in [line 920](https://github.com/ddnet/ddnet/blob/0da0dddf15f83ca74b927b0a67cf7bad92d72e32/src/engine/client/text.cpp#L920). It reads the next character after the current one without checking that the current one is not 0, thus reading past the string's end.


https://github.com/ddnet/ddnet/blob/0da0dddf15f83ca74b927b0a67cf7bad92d72e32/src/engine/client/text.cpp#L914-L920

**Comment by Ryozuki** [comment]
```
==22716== 114,312 (6,344 direct, 107,968 indirect) bytes in 1 blocks are definitely lost in loss record 2,352 of 2,363
==22716==    at 0x483977F: malloc (vg_replace_malloc.c:309)
==22716==    by 0x2180B2: CSnapshotStorage::Add(int, long long, int, void*, int) (snapshot.cpp:475)
==22716==    by 0x24FD6F: CClient::ProcessServerPacket(CNetChunk*) (client.cpp:1929)
==22716==    by 0x251FD0: CClient::PumpNetwork() (client.cpp:2424)
==22716==    by 0x253061: CClient::Update() (client.cpp:2679)
==22716==    by 0x254444: CClient::Run() (client.cpp:3030)
==22716==    by 0x259F70: main (client.cpp:4079)
```
snapshot storage is possibly leaking

**Comment by Ryozuki** [comment]
Maybe someone can look if the storage really leaks, if not you can merge.

**Comment by heinrich5991** [comment]
Thanks a lot for tracking all these down. :)

bors r+

**Pull request merged**
