### PR TITLE
Overhaul translations

### PR DESCRIPTION
**Pull request by Vy0x2**
1. Converted translations starting with a lower case to upper case and fixed general errors (especially in the italian translations, a lot of duplicates etc.)
2. Alphabetical order of the translations now

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Vy0x2** [comment]
Note. I cant test or look into every file, i took some random samples and tested it with the german and arabic one, seemed good.

**Comment by def-** [comment]
I'm not sure I'm a big fan of this change. Other opinions? Why have a specific order of translations? Why capitalize everything?

**Comment by Vy0x2** [comment]
Because its a pain in the ass if you want to find something, since the order different in every language file
Its easier to maintain if there is an order
Capitalize everyting since there are only 5 translations that start with a lower case letter and 4 of them got introduced recently in some vulkan/graphics changes. And the other (old) one is "transmits your player name to info.ddnet.org" which just should be upper case like everything else, i dont see a reason why it should be lower case

**Comment by heinrich5991** [comment]
These things seem to be lowercase because they're additions in parentheses.

> Because its a pain in the ass if you want to find something, since the order is different in every language file

ctrl-f should be sufficient, no?

> Its easier to maintain if there is an order

I agree that it's nice to have some sort of canonical ordering. I'm not sure the best ordering is alphabetical though. If we want to have an ordering, there should be a script to enforce the ordering. You should probably not write that script right now because we're not sure about the ordering yet.

> i dont see a reason why it should be lower case

Normalizing the case of translations for normalization's sake is not a good idea. You should look into the contexts to decide whether it makes sense to have it upper-case or not.

**Comment by Vy0x2** [comment]
> ctrl-f should be sufficient, no?

If you are unsure about the correct spelling, its easier to search it in the alphabet.
If the translations beginning with "AntiPing" are in line 15, line 250 and line 1500, its a bit stressful to have a good overview

> These things seem to be lowercase because they're additions in parentheses.

The german translation for "default" is in upper case, it seems not very intuitive to use lower case in all cases I changed

**Comment by heinrich5991** [comment]
> The german translation for "default" is in upper case,

The German word for "default" is a noun. All nouns in German start with a capital letter. That should definitely not influence the English or other localizations.

**Pull request closed without merging**
