### PR TITLE
Set correct colour for authed colour reset button

### PR DESCRIPTION
**Pull request by furo321**
https://github.com/ddnet/ddnet/pull/7630#issuecomment-1850804027

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by heinrich5991 — APPROVED** [review]
Thanks for the quick fix!

**Comment by ChillerDragon** [comment]
Amazing thanks I was about to do that :)

**Comment by Kaffeine** [comment]
Why you didn't take the color from `m_ClAuthedPlayerColor`
IMO the cumbersome code to convert the color from the config easily outweigh the constant duplication. 😢

**Comment by ChillerDragon** [comment]
> Why you didn't take the color from `Config()->m_ClAuthedPlayerColor`? IMO the cumbersome code to convert the color from the config easily outweigh the constant duplication. 😢
> 
> Or oh, we don't have an API to get it?

Agreed. If there is no API would be nice to build one. Could use the include macro trick to generate some color constants.

**Pull request merged**
