### PR TITLE
Client tells server its zoom level (fixes #2087)

### LINKED ISSUE #2087: We ALL need a cl_showall 0/1 plzplz
Typing /showall everytime u join is megaboring, if someone could code a console command to automate it on ddnet's settings it'd be megacool
Megathx

### PR DESCRIPTION
**Pull request by def-**
and server adapts the visible distance to it

### CODE REVIEW

**Comment by heinrich5991** [comment]
This sends a vital message each time the zoom level changes, so if people scroll to zoom, it'll send a couple of unneeded packets. A better way might be to only send updates when an input packet leaves the client.

Another thing: Perhaps this could be done by sending the client's viewport + a bit, so the server doesn't have to do the weird circle calculation.

**Comment by heinrich5991** [comment]
Before implementing my suggestions, can you tell me what you think about them?

**Comment by def-** [comment]
> This sends a vital message each time the zoom level changes, so if people scroll to zoom, it'll send a couple of unneeded packets. A better way might be to only send updates when an input packet leaves the client.

Meh, seems like it shouldn't matter much. And don't we send inputs rather often too? Also, if you zoom out without moving your mouse, you won't get an updated view then?

> Another thing: Perhaps this could be done by sending the client's viewport + a bit, so the server doesn't have to do the weird circle calculation.

This sounds good, the circle is stupid.

**Comment by heinrich5991** [comment]
LGTM, thanks. :)

bors r+

**Pull request merged**
