### PR TITLE
CMake: Change the net versioning

### PR DESCRIPTION
**Pull request by Kaffeine**
Set `DDNET_VERSION_NUMBER` from `DDNET_NETWORK_VERSION` no matter what `VERSION` is. Provide `get_network_version_number()` which parses version to network version (can be useful for mods).

Fixes https://github.com/ddnet/ddnet/pull/7153#issuecomment-1717561522

### CODE REVIEW

**Comment by Kaffeine** [comment]
Function `get_network_version_number(VERSION OUTPUT)` should be moved to a file in `/cmake/` but unfortunately we don't have a file with functions yet.


> ```set(DDNET_NETWORK_VERSION 17.2.1)```

I don't like the var naming, any suggestions welcome.

We need a name for the version which is used to generate network version number, and used as the project version if not overridden by `VERSION` cmake conf option.

We can't use `VERSION`, `PROJECT_VERSION`, `DDNET_VERSION`.

We can use `DEFAULT_VERSION` if it sounds better. Or we can drop :unamused: the net version generation and set it manually e.g.:
```diff
 if(NOT VERSION)
   set(VERSION 17.2.1)
 endif()
+set(NET_VERSION 17021)
 
 project(DDNet
   VERSION ${VERSION}
 )
```

**Review by def- — APPROVED** [review]
I'll try this later, thanks

**Comment by def-** [comment]
```
CMake Error at CMakeLists.txt:15 (project):
  VERSION "-20230915" format invalid.
```
Do I need to change something in https://github.com/ddnet/ddnet-scripts/blob/master/release/build.sh ?

**Comment by Kaffeine** [comment]
No you don't have to. The whole idea is to keep/restore compatibility.

The new version should work like before (e.g. previous release).

**Comment by Kaffeine** [comment]
Oh wait. I thought the issue is in the netversion but it is right in the `project()` call. I don't see where this `-` could come from. Can you provide the cmake arguments?
I see:
```
cmake -DVERSION=$VERSION -DCMAKE_OSX_ARCHITECTURES=\"arm64;x86_64\" -DCMAKE_BUILD_TYPE=Release -DDISCORD=ON -DWEBSOCKETS=OFF -DIPO=OFF -DPREFER_BUNDLED_LIBS=ON $(echo $FLAGS) ../ddnet-source && \
```

Do we have "`-20230915`" in the shell `VERSION` variable?

**Comment by Kaffeine** [comment]
Or hmm, maybe the `VERSION` is `17.2.1-20230915` or something like that? As I [said](https://github.com/ddnet/ddnet/pull/7153#issuecomment-1717576225) before I don't see any clue about the `VERSION` variable value in the script. It is hard to fix something without that information.

**Comment by Kaffeine** [comment]
We parse version.h to get the version?! Plot twist.

https://github.com/ddnet/ddnet-scripts/blob/master/release/build-and-deploy.sh#L25

```shell
V="$(curl -s https://raw.githubusercontent.com/$MAIN_REPO_USER/$MAIN_REPO_NAME/$MAIN_REPO_BRANCH/src/game/version.h | grep "^#define GAME_RELEASE_VERSION" | cut -d'"' -f2)"
```

**Comment by heinrich5991** [comment]
image

This is what the current steam nightly shows. So it'd be 17.2.1-20230914?

**Comment by heinrich5991** [comment]
Maybe we should just change everything back? People having to adjust their scripts because we wanted to make our CMakeLists.txt nicer doesn't sound too nice.

**Comment by Kaffeine** [comment]
The original goal is to use the conventional tool CMake `project(VERSION)` to set the version instead of parsing source code (who would ever do that..).

**Comment by heinrich5991** [comment]
If that's the entire goal, I think it might be better to revert this, given the breakage it seems to cause.

**Comment by Kaffeine** [comment]
Okay-okay, I give up against that level of engineering. I can find better better application for my rare free time.

**Comment by Kaffeine** [comment]
> Putting the version number into the CMakeLists.txt file is probably really the correct place for it.

That is the main point for me. If we all agree on that _in principle_ then I'll try to get back to it, taking in account all use-cases.

I can't agree with a position that "this is fine, let's keep it as is (forever)", it just makes me mad and I'm sorry for overreacting.

> I'm not sure what we can do about the broken scripts. We could either duplicate the version number, which is probably also bad, or just let the scripts break.

I also don't have a solution right now and no time to work on it (I'm going for some two weeks trip). In other projects the CI scripts (including night builds) pass custom `BUILD_VERSION` argument which appended to the project version, so the project always uses the version from CMake with some suffix.
Instead of parsing the version, the script can run `cmake -DBUILD_VERSION=<date>` and/or `BUILD_VERSION=<commit hash>`.

**Comment by Kaffeine** [comment]
> Sorry about wasting your time, I'll fix it myself later.

Miscommunication. I didn't understand your needs, you didn't say a word about the possible `VERSION` values and I thought that you pass the next release version (such as `17.3.0`) when building the next RC.

I'm also sorry for breaking the things. You also could think about the script parsing `version.h` during the code review. It seems that we have a very different practice in CI/CD and thus this happened.

**Comment by Kaffeine** [comment]
I've cooled down a little and want to try again, as today I'll have some time for that. The goal is to cleanup and modernize the DDNet build system code, starting with `version` handling. If it won't work then please revert the changes (probably I won't have opportunity to reply before Oct 1).

@def-  Can you please describe the use-cases of `VERSION` option so I can come with a solution that 'll be modern (in terms of https://cliutils.gitlab.io/modern-cmake/) and fit all the needs?

I'll have to adjust the build scripts as it makes no sense to parse the project version just to pass it back to it. I'm going to add the said `BUILD_VERSION` and use it instead. Now I assume that in case of RC builds you already have bumped project and netversion, and just add something like `rc1` which is fully compatible with that `BUILD_VERSION` approach.

If you don't like the `BUILD_VERSION` name then it can be `VERSION_EXTRA` or whatever sounds better for you.

**Comment by def-** [comment]
I just need some way of setting the version for RCs (17.2.1-rc1) and for nightly (17.2.1-20230915). I don't care about what way to set it, the ddnet-scripts/release is what I use for that, but I can fix that after the fact too.

**Comment by Kaffeine** [comment]
Makes sense. I'll do that in the next hours (or fail and disappear for the said while).

**Pull request merged**
