### PR TITLE
fixed faulty message id

### PR DESCRIPTION
**Pull request by ChillerDragon**
(cherry picked from commit https://github.com/teeworlds/teeworlds/commit/9023796d270b216c5859cc6b351a91a4656c58ec)

### CODE REVIEW

**Comment by Learath2** [comment]
Hmm, are you sure we can do this? Looks a bit like a protocol change. I'll
take a better look later

**Comment by ChillerDragon** [comment]
@Learath2 tbh I have no clue. But I tested it and the client can still connect to ddnet and non ddnet servers and works fine as far as I know.

**Comment by ChillerDragon** [comment]
Ok I found the first issue :/ 
It broke map downloads.

**Comment by Learath2** [comment]
@heinrich5991 if you have a couple minutes can you take a look at this? I'm not completely familiar with the entire thing

**Comment by heinrich5991** [comment]
Looks good to me.

Thanks.

bors r+

**Comment by heinrich5991** [comment]
bors retry

**Comment by Learath2** [comment]
bors retry

**Comment by Learath2** [comment]
New day, lets hope Microsoft fixed their repository.

bors retry

**Pull request merged**
