### PR TITLE
Add str_utf8_copy that trim broken utf8 sequence at the end.

### PR DESCRIPTION
**Pull request by TsFreddie**
Currently this replaces `str_copy` text input and clipboard paste in chat. Many places may need the same treatments, like steam names.

image

Test string:
abcd今天是个好日子心想的事儿都能成今天是个好日子打开了家门咱迎春风今天是个好日子心想的事儿都能成今天是个好日子打开了家门咱迎春风今天是个好日子心想的事儿都能成今天是个好日子打

### CODE REVIEW

**Comment by def-** [comment]
Did you test if this is actually required with https://github.com/ddnet/ddnet/pull/2726 ? I guess we can clean up twice :)

**Comment by TsFreddie** [comment]
Unrelated, this fix similar stuff when you paste in editbox and chat lineinput locally.

**Comment by TsFreddie** [comment]
image
image

screenshots for context

**Comment by heinrich5991** [comment]
Can you add a couple of tests exercising the common and edge cases of this function?

If possible, could you reuse our existing UTF-8 parser (`str_utf8_decode`)?

Might `str_utf8_truncate` already do what you need if you set `truncation_len` to a large value?

**Review by heinrich5991 — CHANGES_REQUESTED** [review]
See above.

**Comment by TsFreddie** [comment]
I guess str_utf8_truncate will do when `truncation_len` and `dst_size` is the same.

**Comment by heinrich5991** [comment]
Could you create a function `str_utf8_copy` that calls `str_utf8_truncate` instead? It's not really the intention to truncate the string in those places where it's called, so it shows the wrong intention.

And some tests for correct behavior would be nice.

**Comment by heinrich5991** [comment]
Okay, how can you test this?

In src/test/str.cpp, add

```
TEST(Str, Utf8Copy)
{
	char aBuf[4];
	str_utf8_copy(aBuf, "abc", sizeof(aBuf));
	EXPECT_STREQ(aBuf, "abc");
	str_utf8_copy(aBuf, "abcd", sizeof(aBuf));
	EXPECT_STREQ(aBuf, "abcd");
	str_utf8_copy(aBuf, "áà", sizeof(aBuf));
	EXPECT_STREQ(aBuf, "á");
	str_utf8_copy(aBuf, "aâ", sizeof(aBuf));
	EXPECT_STREQ(aBuf, "aâ");
	str_utf8_copy(aBuf, "aâa", sizeof(aBuf));
	EXPECT_STREQ(aBuf, "aâ");
}
```

**Review by heinrich5991 — APPROVED** [review]
Thanks for your patience!

bors r+

**Pull request merged**
