### PR TITLE
fix projectiles not rendering on mods based on ddnet

### PR DESCRIPTION
**Pull request by ZombieToad**
for some reason the client doesnt render extrainfo projectiles if the gamemode wasnt ddnet

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Oh thats great c:
thanks!

**Comment by ChillerDragon** [comment]
But you just removed some stuff? Are you sure all is still working the same without it? What was it needed for?

**Comment by Piepow** [comment]
If you change the name of the game type to something that isn't recognized as ddnet, projectiles won't render unless you use `FillInfo` instead of `FillExtraInfo` in projectile.cpp. But then nobody can use antiping for projectiles on your server.

**Comment by ZombieToad** [comment]
i couldnt find why it was needed

**Comment by heinrich5991** [comment]
Looks good to me. Thanks!

bors r+

**Comment by heinrich5991** [comment]
This should probably be reverted.

**Pull request merged**
