### PR TITLE
map_convert_07: Check image width for divisibility by 16

### PR DESCRIPTION
**Pull request by def-**
As noticed on Sunny Land.

> [5:31 PM] redix: in theory it should be enough if width and height are divisible by 16

Now running this over our maps and fixing them manually.

### CODE REVIEW

**Comment by def-** [comment]
Should also warn about this in DDNet editor I guess.

**Comment by def-** [comment]
Fixed all our maps based on this.

**Comment by heinrich5991** [comment]
Have you confirmed that it divisible by 16 suffices? redix said that they must exactly be 1024x1024.

**Comment by def-** [comment]
Yes, looks fine in 0.7.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
