### PR TITLE
Make chat command arguments case-insensitive when possible

### PR DESCRIPTION
**Pull request by dobrykafe**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by BlaiZephyr** [comment]
isnt this already fixed by #8014 ?

**Comment by archimede67** [comment]
This is about command arguments, not commands themselves

**Review by def- — APPROVED** [review]

**Comment by heinrich5991** [comment]
@dobrykafe What's the motivation for this? Do you personally sometimes mistype them?

**Comment by dobrykafe** [comment]
> @dobrykafe What's the motivation for this? Do you personally sometimes mistype them?

Since commands themselves are already case-insensitive + 40% of arguments were before as well I think it makes sense for them all to behave the same. Not having to re-type everything if you accidentally leave on caps-lock or capitalize first letter is great!

**Pull request merged**
