### PR TITLE
fix some skins

### PR DESCRIPTION
**Pull request by l-ouis**
some changes for skins
1. fix paladin border
old:
screenshot_2020-10-29_21-22-53
new:
screenshot_2020-10-29_21-26-06

~~2. fix capitalization on "Aoe4leg" and "PaladiN" to "aoe4leg" and "paladin". skin names should not start with a capital letter because it pushes it to the top of the skin list, messing up alphabetical order (maybe should fix this with the code, not with skin names)~~

3. remove terrorist skin - it is quite un-teeish and I don't think it belongs in the client-shipped skin list.

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [x] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

idk all this code checklist stuff I don't think I need to test since it's just file changes

also, idk how to use github so I probably forked the wrong repository or something idk

### CODE REVIEW

**Comment by fokkonaut** [comment]
not a good idea to change skin names, people wont see skins with the other name then

**Comment by l-ouis** [comment]
good point. I don't even know if renaming files is possible just through GitHub so I have to delete them and reupload them which is kind of odd. I guess the capitalization issue should be fixed in the name sorting code, so I've opened a pull request at #3213.

**Comment by fokkonaut** [comment]
renaming works fine here.

**Comment by def-** [comment]
Thanks, fixed the CMakeLists.txt and squashed all into one commit.

bors r+

**Comment by b3z** [comment]
Since when is PaladiN not black anymore?

**Comment by fokkonaut** [comment]
It is and always was, he probably just colored the body to show that the shadow is not correct. Senseless if I think about it, because the skin cant be colored anyways

**Pull request merged**
