### PR TITLE
Add discord rich presence

### PR DESCRIPTION
**Pull request by edg-l**
Current work done: finding discord libraries (tested only on linux by me)

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by edg-l** [comment]
I'm having a bit of trouble since the discord sdk doesn't provide static libraries for linux (it provides a .so file), it being shared i dont know how to distribute it, distros dont offer this library to be installed, idk what to do here.

**Comment by def-** [comment]
I guess we could put the shared lib in ddnet-libs and add it in the default builds.

**Comment by edg-l** [comment]
I invited deen, heinrich and learath to a "discord dev" app team https://discord.com/developers/applications

**Comment by edg-l** [comment]
Somehow the config i am adding isn't being added/detected?, i need to find if it's just a issue with my configs.

**Comment by edg-l** [comment]
image
image

**Comment by def-** [comment]
Btw, what happens if I have multiple DDNet clients running?

**Comment by edg-l** [comment]
I guess it works fine, whoever updates ur activity last will remain i guess

**Comment by heinrich5991** [comment]
I'm in favor of
a) factoring all of this into a single file, so we don't have Discord API bits lying around in game code,
b) using the same stub approach for Discord API so we don't have to have conditional compilation and don't have to ship Discord's stuff in our DDNet libs repo.

I'd do both myself, building on this PR, if no one complains.

**Comment by edg-l** [comment]
> I'm in favor of
> a) factoring all of this into a single file, so we don't have Discord API bits lying around in game code,
> b) using the same stub approach for Discord API so we don't have to have conditional compilation and don't have to ship Discord's stuff in our DDNet libs repo.
> 
> I'd do both myself, building on this PR, if no one complains.

Go ahead, it's fine for me, but maybe ask @Learath2 , he was the one who proposed the ifdef aproach.

**Comment by Learath2** [comment]
@heinrich5991 can we have this conversation one last time because everytime I go to do something like this, the stubs are what put me off. I just want to make sure it's sane.

What exactly do we gain from the stubs assuming there is no legal issue with us shipping steamapi or discord gamesdk headers?

Avoiding conditional compilation is one less thing to test on CI sure but what does the stub compilibg on CI prove?

**Comment by heinrich5991** [comment]
If we're allowed to redistribute the Discord SDK, then there's only one reason remaining that I can think of: Ease of builds. I guess that is mostly mitigated by the fact that we ship the libs. If working with the stubs is annoying, I think developer convenience should be valued higher than the other reason, so I'll just go with a) I guess. :)

**Pull request closed without merging**
