### PR TITLE
readme: dont assume number of threads when using make

### PR DESCRIPTION
**Pull request by dobrykafe**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by Robyt3 — APPROVED** [review]

**Comment by ChillerDragon** [comment]
What about don't assume nproc is installed? hehe

**Comment by ChillerDragon** [comment]
Who knows just a little bit of make understands the line can be adjusted. Who knows no make and has only 1 core can still run it and it will compile. 16 core users can also run it without issues.

On the other hand some linux flavors and out of the box macOS do not ship the nproc command. On their system the command will now fail.

**Comment by heinrich5991** [comment]
> What about don't assume nproc is installed? hehe

```
$ pacman -Qo nproc
/usr/bin/nproc is owned by coreutils 9.4-2
```
Should be installed on pretty much any Linux.

**Comment by ChillerDragon** [comment]
> > What about don't assume nproc is installed? hehe
> 
> 
> 
> ```
> 
> $ pacman -Qo nproc
> 
> /usr/bin/nproc is owned by coreutils 9.4-2
> 
> ```
> 
> Should be installed on pretty much any Linux. The macOS thing is an issue though.

Most Linux users have coreutils installed yes. But not all. On Mac you can also install core utils via brew but you have to actively do that. acme.sh greps some number in /proc instead of nproc. Which would be way too bloat for the readme. Same as adding the macOS alternative. Imo the hardcodet number was more portable.

**Comment by ChillerDragon** [comment]
Also what about non Linux? Like FreeBSD and Solaris and their kind.

**Comment by heinrich5991** [comment]
I agree that it could be an issue on non-Linux. But name me a desktop Linux distro without `nproc` by default.

**Comment by ChillerDragon** [comment]
> I don't know. Have you investigated?

I have not investigated. But I could see users uninstalling coreutils even if that seems like a bad idea. There might be some minimal distribution not sure.

The point is that acme.sh decided not to reply on nproc but grep instead. They know what they are doing and it is a widely used posix script.

Also yes Mac alone is reason enough. Before this pr some systems would compile slower than they could. But none would ever fail. After this pr. Most systems use 100% cpu and for some the command fails.

The reason why I keep coming up with the non Mac cases is. Please do not add coreutils to the list of programs in the brew install step and call it a day.

**Comment by ChillerDragon** [comment]
My bad it was not acme.sh it was ruby-build.

https://github.com/rbenv/ruby-build/blob/e1b36a32fb87d61955ac38f1889b7e3cb3b2f407/bin/ruby-build#L241-L257

**Comment by ChillerDragon** [comment]
Yep so same as macOS also FreeBSD is affected 

https://github.com/rbenv/ruby-build/commit/f4c2fe67e3b8f2f2304ce75beaa54bc5b3cb5371

**Comment by ChillerDragon** [comment]
It seems like most linux distros even minimal ones such as alpine and busybox have nproc available. But many non linux but posix complaint systems do not have it. Also nproc is not a POSIX command.

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/contents.html

**Comment by heinrich5991** [comment]
> Also yes Mac alone is reason enough.

I agree.

What I don't like is making up reasons. Thanks for investigating non-Linux and Linux systems. We see that it works on Linux systems but not on non-Linux systems, and macOS should be enough of a reason to change it back.

**Comment by furo321** [comment]
I don't think assuming `nproc` is installed is an issue. The first section that was changed was `Running tests (Debian/Ubuntu)`, so `nproc` being installed is pretty much guaranteed.

The second section is a bit more vague, `Importing the official DDNet Database`. It also assumes you're running Linux. It uses the `systemctl` and `yaourt` commands, which are both Linux specific.

**Comment by ChillerDragon** [comment]
Hm yea true. If it's a linux section it could stay linux only I guess.

**Pull request merged**
