### PR TITLE
Show "Free View" for Sixup

### PR DESCRIPTION
**Pull request by Learath2**
@fokkonaut is this enough?

bors delegate=fokkonaut

### CODE REVIEW

**Comment by fokkonaut** [comment]
Should be, but the cooldowntick should just be Server()->Tick()

**Comment by Learath2** [comment]
There is a cooldown before you can get back out of spec tho, no?

**Comment by fokkonaut** [comment]
Yes, but thats only serverside. This is not a real spectator join, so the cooldown is irrelevant, because you use the chat command only, not the join button.

**Pull request merged**
