### PR TITLE
Restore old /save behavior

### LINKED ISSUE #2362: Disable 3 word default pws for saves?
They seem to not be received so well and cause confusion.

@Zwelf Would it be possible to safely fix it so that we just get an error again and the team can choose a new code on their own?

### PR DESCRIPTION
**Pull request by Zwelf**
Fixes #2362, supersedes #2367 

I didn't change the /save message. There are already two different: "Use '/load %s' on %s to continue" and "Use '/load %s' to continue".
I think it would be better to add a NetMessage, this could also solve the problem of saving which team members were in the team.

>  I guess this can't be used to cheat anything?

Only if an instant rehook is necessary. Might be useful for rehooking an edge hook (but you still have to aim).

### CODE REVIEW

**Comment by def-** [comment]
bors r+
Thanks

**Comment by def-** [comment]
I think I misunderstood the implications of this. Jeroen on Discord just shared a video that showed that he failed because he was in /pause when saving, save existed, tee tried to rehook and failed. I guess we need a better solution, sorry. :/
[lmao.zip](https://github.com/ddnet/ddnet/files/4838224/lmao.zip)

**Comment by Zwelf** [comment]
Could be fixed by extending the CSaveTee to also include the hooked object. Not so easy for HookedPlayer as ClientIDs don't persist.

**Comment by def-** [comment]
This had to be emergency-reverted since it immediately gives you reloaded weapon when save code exists without any timer, so you can use grenade super quickly on race maps.

**Comment by Zwelf** [comment]
Sorry for the bugs causing the emergency-reverts. `CCharacter::m_ReloadTimer` isn't stored in the database yet. Should I just add it in #2424 or would you prefer a separate pull request (or not storing it in the database, just in `CSaveTee` as a quick fix)?

**Comment by def-** [comment]
That's ok. Changing this kind of code is expected to break things. I guess it's fine in #2424.

**Pull request merged**
