### PR TITLE
speedup demo with mouse scroll only if menu is active

### PR DESCRIPTION
**Pull request by Anime-pdf**
Fix for https://github.com/ddnet/ddnet/issues/8797

Preview:
https://github.com/user-attachments/assets/6233e6e0-deb9-4a2a-96b4-54347b0a721c

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Not sure about this. Seems like it might make some workflows more annoying that involve demo recording at certain speeds without hud.

**Comment by Anime-pdf** [comment]
Arrows hotkeys are still available. The main motivation is that a large number of players use scrollwheel for zooming, and it overlaps with changing speed. In referenced issue, I also mentioned adding demo hotkeys to settings, but I felt a little lazy for that

**Comment by ChillerDragon** [comment]
A bit off topic: I recommend shift+scroll for zoom

**Review by def- — APPROVED** [review]

**Comment by ChillerDragon** [comment]
I have been watching daily demos in the last few days and it was quite annoying. I always close the menu because i want to see the full viewport and then I have to toggle it off and on while seeking through the demo.

**Comment by ChillerDragon** [comment]
This really broke my workflow. I zoom with shift+scroll which does not work if the menu is open. So I have to now toggle the menu on and off to be able to zoom and change speed.

**Comment by Anime-pdf** [comment]
I'm sorry to hear that. As I've noticed, reverting things is not an option in ddnet, even if a lot of people complain about it, and it complicates things as well. 
I saw you reverted this change in chillerbox-ux client, I thought you use it on a daily basis. 
As an alternative to reverting, I can offer you contributing further towards this issue: https://github.com/ddnet/ddnet/issues/7559 it will likely resolve your frustration and help other frustrated users too.

**Comment by ChillerDragon** [comment]
Reverting is a thing in ddnet it happens. I do use chillerbot-ux as my daily driver but also occasionally end up using ddnet for example while contributing to ddnet. Also it causes me maintenance effort to merge this revert into newer ddnet versions. But yes I will survive just wanted to mention here that I am not happy with the change and somebody elses workflow might also have been broken.

I would vote for a revert but at this point it seems to be a 1v1 your zoom bind vs my zoom bind.

**Comment by gerdoe-jr** [comment]
This strongly needs #7556 to be done and merged, hardcoded bindings can always interfere with user binds

**Pull request merged**
