### PR TITLE
Disallow dummy option (closes #4305, #4316)

### LINKED ISSUE #4305: Dummy is a kind of hacker--click*
I set my server
sv_max_clients_per_ip 4
and dummy connect,I don't welcome dummy
But I can't stop them！！！！！！！！
Let the dummy appear only on the server where the motd has written some specific characters

like: sv_motd #dummyenable#

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Please send `SERVERCAPFLAG_ALLOWDUMMY` in the server so that normal DDNet servers allow dummies.

Otherwise looks good to me. :)

**Comment by fokkonaut** [comment]
I did, but forget to re-add it after testing. Sorry.

**Comment by heinrich5991** [comment]
No problem, thanks that you tested this pull request. I also sometimes forget to remove testing code before making the PR.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
