### PR TITLE
Fix scroll regions active below popup menus in server browser

### LINKED ISSUE #8087: Overlapping scroll regions focuses the region underneath
https://github.com/ddnet/ddnet/assets/141338449/24b92b7a-a3dd-43c8-8e3c-378168fcdf90

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #8087.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by archimede67** [comment]
Is it possible to detect the scroll region that is being rendered in front of the others (I guess the last one that is rendered)? That way we could perhaps change the scroll region logic to only allow scrolling in regions in front of all the others when the mouse is inside (always take the frontmost one and scroll this one), instead of handling the server browser specific case.

**Comment by Robyt3** [comment]
> Is it possible to detect the scroll region that is being rendered in front of the others (I guess the last one that is rendered)? That way we could perhaps change the scroll region logic to only allow scrolling in regions in front of all the others when the mouse is inside (always take the frontmost one and scroll this one), instead of handling the server browser specific case.

It is, and I implemented that at first, but it didn't feel right. I think when a popup menu is open, all UI elements below the popup menu should be disabled without making an exception specifically for scroll regions.

Scroll regions used in popup menus should only be active iff the popup is active (`bool Active` argument of the popup render function), if showing popup menus above this popup should be supported, so I think this works without any changes to scroll regions in general.

**Comment by archimede67** [comment]
> It is, and I implemented that at first, but it didn't feel right. I think when a popup menu is open, all UI elements below the popup menu should be disabled without making an exception specifically for scroll regions.

I don't think they should be disabled per say, but any element under that popup definitely should not catch any event (clicks, scroll, etc). I think keeping the functionality of the elements underneath outside of the popup's region is better than disabling everything when a popup is open.

> Scroll regions used in popup menus should only be active iff the popup is active (bool Active argument of the popup render function), if showing popup menus above this popup should be supported, so I think this works without any changes to scroll regions in general.

I agree about scroll regions in popup menus only being active if the popup is active.

**Comment by Robyt3** [comment]
> I think keeping the functionality of the elements underneath outside of the popup's region is better than disabling everything when a popup is open.

The popup menus have always been modal, I don't want to change that now. It would likely introduce bugs because popup menus were not designed to handle changes to their parent popup menus or the menu/editor while they are open.

Allowing this only for scroll regions with the mouse might be feasible, because it's a "passive" action that only changes the view, so it hopefully shouldn't break anything. This would be similar to how it works on Windows 10 and newer, where you can scroll any window with the scroll wheel while hovering it, even if the window is not active/focused. I'll PR that tomorrow.

**Comment by archimede67** [comment]
> The popup menus have always been modal, I don't want to change that now. It would likely introduce bugs because popup menus were not designed to handle changes to their parent popup menus or the menu/editor while they are open.

Yes, I wasn't very clear but of course clicking outside for example would close the popup. I was talking more specifically about visual functionality such as scroll, hover animation etc.

> Allowing this only for scroll regions with the mouse might be feasible, because it's a "passive" action that only changes the view, so it hopefully shouldn't break anything. This would be similar to how it works on Windows 10 and newer, where you can scroll any window with the scroll wheel while hovering it, even if the window is not active/focused. I'll PR that tomorrow.

That was exactly what I was thinking about! That way it would work for any popup in any menu and not only in the server browser menu.

**Comment by Robyt3** [comment]
Superseded by #8096.

**Pull request closed without merging**
