### PR TITLE
Remove sv_spectator_votes

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Can we just remove that condition altogether? It's no use in DDNet, we don't limit player slots, people don't go into spectator mode to spectate.

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by fokkonaut** [comment]
Spectators cant start votes on the clientside anyways if they are in spectator mode (at least 0.7)

**Pull request merged**
