### PR TITLE
Make skin refind cleanup bit more aggressive

### LINKED ISSUE #7165: Crash due invalid player tee texture after enabling "vanilla skins only" option
Same assertion error as #6882 but for a tee being rendered ingame after enabling the "vanilla skin only" option. Reported by "Way" on Discord.

```
0x000000014032ddf7: dbg_break() at src/base/system.cpp:222
 (inlined by) dbg_assert_imp(char const*, int, int, char const*) at src/base/system.cpp:215
0x00000001401dd37b: dbg_assert_imp(char const*, int, int, char const*) at src/base/system.cpp:217
0x000000014002ed20: CGraphics_Threaded::TextureSet(IGraphics::CTextureHandle) at src/engine/client/graphics_threaded.cpp:857
0x00000001400cadfb: CPlayers::RenderHand(CTeeRenderInfo const*, vector2_base<float>, vector2_base<float>, float, vector2_base<float>, float) at src/game/client/components/players.cpp:56
0x00000001400cdd42: CPlayers::RenderPlayer(CNetObj_Character const*, CNetObj_Character const*, CTeeRenderInfo const*, int, float) at src/game/client/components/players.cpp:650
0x00000001400cf6c3: CPlayers::OnRender() at src/game/client/components/players.cpp:856
0x00000001400e943d: CGameClient::OnRender() at src/game/client/gameclient.cpp:681
0x0000000140020a51: CClient::DebugRender() at src/engine/client/client.cpp:1038
 (inlined by) CClient::Render() at src/engine/client/client.cpp:1214
0x000000014002aaa8: CClient::Run() at src/engine/client/client.cpp:3302
0x000000014032bf25: main at src/engine/client/client.cpp:4828
```

Version 17.2.1 64 bit Steam.

### PR DESCRIPTION
**Pull request by Jupeyy**
tested ingame by trying to reproduce (so not 100% fix), but seems logical to me

fixes #7165

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
a cleaner solution would be able to tell if no skin was set vs. the entry is inactive

the current solution might create a render call that does not include a texture (so will probably make a white square.. which sucks too)

i dunno if we can certainly say e.g. if a client slot is a connected player

**Comment by Robyt3** [comment]
Does this potentially also fix #6882? Maybe it happens rarely because some player has an empty skin name.

**Comment by Jupeyy** [comment]
quite possible, but i didnt fix anything in the kill messages D:
i should tho!

**Comment by Jupeyy** [comment]
victim render infos were already cleared all the time, so only added for killer

**Review by def- — APPROVED** [review]

**Pull request merged**
