### PR TITLE
Always update text cursor y (closed #8282)

### LINKED ISSUE #8282: CreateTextContainer does not change the cursor y on line breaks
image

More of a missing feature than a bug maybe. I realized that while working on colored broadcast where I wanted to use the cursor to keep track of line offsets while doing multiple text containers for different colors.

Slap this code in any `OnRender()` method to reproduce.

```C++
STextContainerIndex Line1, Line2;
CTextCursor Cursor;
TextRender()->SetCursor(&Cursor, 40.0f, 40.0f, 12.0f, TEXTFLAG_RENDER);
TextRender()->CreateTextContainer(Line1, &Cursor, "hello\nworld");
TextRender()->RenderTextContainer(Line1, TextRender()->DefaultTextColor(), TextRender()->DefaultTextOutlineColor());

TextRender()->CreateTextContainer(Line2, &Cursor, "foo");
TextRender()->RenderTextContainer(Line2, TextRender()->DefaultTextColor(), TextRender()->DefaultTextOutlineColor());
```

### PR DESCRIPTION
**Pull request by ChillerDragon**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
This is my first time messing with anything text/render related. I am quite lost in this 400 lines method. But it seems like `GotNewLine` is `false` even if the cursor drew a `\n` which is weird in the first place and I did not bother to investigate why.

But then why should the x coordinate be updated at all times but the y only conditionally? I don't think the if statement is needed. And it does indeed fix the bug from https://github.com/ddnet/ddnet/issues/8282 and I do not notice any new bugs.

**Comment by ChillerDragon** [comment]
So I investigated a bit. Seems like only line wrapping sets `GotNewLine` to be true. But the newline character does not.

https://github.com/ddnet/ddnet/blob/7e857ce37e14c811808e2511d2c054b14c12bbf5/src/engine/client/text.cpp#L1677-L1690

https://github.com/ddnet/ddnet/blob/7e857ce37e14c811808e2511d2c054b14c12bbf5/src/engine/client/text.cpp#L1901-L1909

That explains why it did not update the y coordinate. But I still think that the better fix is to remove the if statement. Instead of also setting new line to be true on that branch. It is adding code vs removing code. It is too complex of a method already.

**Comment by ChillerDragon** [comment]
Not sure what pit falls to look for. I used asan and clicked through all the UIs. Demos, editor, menu. Made sure the chat wrapped fine when opening the scoreboard.

**Comment by Robyt3** [comment]
Maybe this somehow influences text cursor or text selection rendering at line breaks, you could also check such cases to make sure. You could also check if this affects #8179 in any way. I'll review this PR later.

**Comment by ChillerDragon** [comment]
> Maybe this somehow influences text cursor or text selection rendering at line breaks, you could also check such cases to make sure.

Local console text selection from the middle of the line or end of line across multiple lines seems to work as expected.

image


The ``if(GotNewLine)`` is still from matricks' "[copied refactor to trunk](https://github.com/ddnet/ddnet/commit/72c06a258940696093f255fb1061beb58e1cdd0b)" in 2010. The variable `GotNewLine` is unused otherwise.

**Comment by ChillerDragon** [comment]
> You could also check if this affects https://github.com/ddnet/ddnet/issues/8179 in any way.

**Comment by ChillerDragon** [comment]
I am becoming more and more confident that this is okay. Anything else I should test? Otherwise I would say its ready to merge.

**Review by Robyt3 — APPROVED** [review]
Seems good, thanks.

#8179 seems unaffected, it only happens with specific names and may also only specific screen sizes.

**Pull request merged**
