### PR TITLE
Warn new players about name with points (fixes #3178)

### LINKED ISSUE #3178: warn players when they choose a name that already has points on it
i was thinking it would be awkward to choose a name that someone else already had and find that you already have good times on all novice maps. maybe warn players when they choose a name like "your name already has over 50 points on it"?

### PR DESCRIPTION
**Pull request by def-**
screenshot-20201023@233252

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Changed Ok -> Yes, Back -> No.

**Comment by Banana090** [comment]
Yes should be left button

**Comment by Banana090** [comment]
btw how does this work with "nameless tee" and "brainless tee"? xD

**Comment by murpii** [comment]
> btw how does this work with "nameless tee" and "brainless tee"? xD

Those are no longer being used as default names, thus will die over time.
#2615 by heinrich :)

**Comment by def-** [comment]
Works the same as with any other name

**Comment by l-ouis** [comment]
maybe a "don't remind me again" for people who change their name often?

**Comment by def-** [comment]
This warning is only shown directly after the welcome screen, not for regular name changes.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
