### PR TITLE
Only use pthread_attr_set_qos_class_np if it's available

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I can't reproduce this (even on macOS with native Clang) unfortunately

**Comment by heinrich5991** [comment]
Have you tried with nix on macOS? If not, I'd ask someone with that setup.

**Comment by def-** [comment]
no, only tried with cmake

**Comment by heinrich5991** [comment]
I don't remember the result. I'll try again on Thursday.

**Comment by heinrich5991** [comment]
Forgot it on Thursday, let's try next week.

**Comment by ncfavier** [comment]
The x86_64-darwin nixpkgs build [still fails](https://github.com/NixOS/nixpkgs/pull/212735#issuecomment-1404815230) with the same error after applying this patch, unfortunately.

I'm happy to test further patches using the nixpkgs CI, but I don't know anything about macOS development. I'm not even sure what SDK version we're using, the build doesn't seem to report it.

**Comment by def-** [comment]
That's strange, the code on macOS side looks like this:
```
__OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0)
int
pthread_attr_set_qos_class_np(pthread_attr_t *__attr,
		qos_class_t __qos_class, int __relative_priority);
```
Which indicates to me that it should be available on macOS 10.10

**Comment by ncfavier** [comment]
Are you sure `__MAC_OS_X_VERSION_MIN_REQUIRED` and `__MAC_10_10` are defined? What header exposes them? (If they're both undefined, the expression would evaluate to `0 >= 0`)

**Comment by def-** [comment]
Oooh, they are defined on my system, but probably __MAC_10_10 is not defined on nixOS since it targets an older one. Thanks, will fix

**Comment by ncfavier** [comment]
My chaotic [attempt](https://logs.nix.ci/?key=nixos/nixpkgs.212735&attempt_id=c5e1036c-a697-47fb-ac33-2f2821e3ca41) at getting the compiler to print out anything useful reveals that `MAC_OS_X_VERSION_MIN_REQUIRED` (note, no leading underscores) is set to 101300, so this patch wouldn't work anyway.

I don't really know what's going on, I'll try asking the nixpkgs darwin team.

**Comment by def-** [comment]
My guess is that you can tell an older version of osx sdk to target a higher version of itself and it happily obliges? Seems weird, maybe the way we use `CMAKE_OSX_DEPLOYMENT_TARGET` in cmake is totally wrong?

**Comment by ncfavier** [comment]
Someone [reports](https://github.com/NixOS/nixpkgs/pull/212735#issuecomment-1404994430) that adding `#include <pthread/qos.h>` fixes it, but this header should be included by the darwin `pthread.h`. Maybe the actual `pthread.h` used is not the darwin one? I wonder if this has to do with

https://github.com/ddnet/ddnet/blob/a9207a931f0998feeed3b48de82bfd8cebc28851/CMakeLists.txt#L560-L563

Also note this depressing mess of a thread: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=103949

**Comment by def-** [comment]
Thanks, I don't mind adding that include if it works with that.

**Comment by ncfavier** [comment]
The current patch works!

**Comment by def-** [comment]
Thanks for figuring out all of this @ncfavier . @heinrich5991 good to merge?

**Comment by heinrich5991** [comment]
Yup, should be good. Thanks!

bors r+

**Pull request merged**
