### PR TITLE
Implement /unlock & clarify the /help lock text

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by fokkonaut** [comment]
/lock also toggles lock, its used by everyone, 0 or 1 is optional, otherwise toggle. No need for unlock

**Comment by heinrich5991** [comment]
Conversation on Discord has led to `/unlock` being added:

>[5:38 PM] BannZay: /lock /unlock triple times more user friendly IMO. Does kill protection affects teams in case its locked and somebody died? If no, it would be nice to have

**Comment by Chairn** [comment]
Thanks, unlock is indeed more user friendly and more explicit. Will prevent killing team when someone is falling in void map (e.g. back in the sky).

**Comment by heinrich5991** [comment]
Thanks.

**Pull request merged**
