### PR TITLE
Add nameplates friend marks

### PR DESCRIPTION
**Pull request by BannZay**
Problem: when I play with a friend in team 0, and there are many players nearby, I cannot distinguish him due to nameplates overlapping. It's getting worse when they are in freeze.

Solution: Mark your teammate as "Friend" and setup "cl_nameplates_friendmark"

Result:
v2

### CODE REVIEW

**Comment by louis45508** [comment]
how does it work with clans? isn't there an option to show clans above nametags?

a really nice idea. it might be nicer to just render the friend heart (the thing in chat) above their name.

**Comment by BannZay** [comment]
> though it might be nicer to just render the friend heart

Not sure how the image affects your vision in this case (nameplates renders on top of game world). Even though its not I need some assist with rendering such heart properly.

> how does it work with clans?

This is how nameplate looks like if you enable ids, clans and friendmarks altogather
fullNameplateName

**Comment by BannZay** [comment]
With `cl_nameplates_friendmark 1` it renders heart and with `cl_nameplates_friendmark 2` renders '[F]' . Not sure what I personally preffer.

This is how friendmark with all other features enabled looks like (scales with cl_nameplates_size):

nameplates_heart

Should be ready if none can find an improvement here

**Comment by heinrich5991** [comment]
Can you select one of these styles and only do that? Either [F] or the heart. Thanks. :)

**Comment by BannZay** [comment]
Sure, I will go with the heart. Hope none will be complaining about the "picture" in nameplates =)

**Review by heinrich5991 — APPROVED** [review]
bors r+

Thanks!

**Pull request merged**
