### PR TITLE
Add target clientid to antibot OnHammerHit

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
@heinrich5991 I guess needs to be updated on official servers carefully?

**Comment by heinrich5991** [comment]
That's correct. Please also increment the antibot ABI version.

I guess you need the hammer hit target for your own servers? @fokkonaut

**Comment by fokkonaut** [comment]
> I guess you need the hammer hit target for your own servers? @fokkonaut

Yes, and I think its generally not bad to have.

**Comment by fokkonaut** [comment]
Can we get this in?

**Comment by def-** [comment]
I'd prefer to wait for heinrich5991 to be back from vacation when we deploy this and something goes wrong.

**Comment by heinrich5991** [comment]
Am back from vacation. Is this all you need?

**Comment by fokkonaut** [comment]
Should be. ANTIBOT_MAX_CLIENTS can probably not be increased, right?

**Comment by heinrich5991** [comment]
Not for DDNet, it can continue to be increased for your custom build.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by heinrich5991** [comment]
bors retry

**Comment by heinrich5991** [comment]
Status: Ready to be merged, I need to be present so I can rebuild the antibot on the servers.

bors still ignores the pull request, but the issue on bors hasn't seen activity, so I guess we'll just merge it without bors.

**Comment by def-** [comment]
Submitted. Tell me when you want to update on servers.

**Pull request merged**
