### PR TITLE
Use player name from the Steam API as fallback

### LINKED ISSUE #2605: Use Steam API to set player name?

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #2605.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Needs testing on Windows, I have a feeling it'll break there.

**Comment by Learath2** [comment]
Why is this a stub encompassing another stub? Is it not feasible to just have one class `CSteam` that reacts different on whether `SteamAPI_Init` returns true or false? I think we already need to be able to react to that returning "false" in pretty much the same way as we'd react to compiling without steam integration at all.

**Comment by heinrich5991** [comment]
The stub in src/steam/steam_api_stub.cpp is pretending there is no Steam (it calls `abort` if a function other than `SteamAPI_Init` is called).

The stub in src/engine/client/steam.cpp handles the non-Steam case and the case where the Steam API fails to initialize the same; it doesn't call any Steam functions after that.

**Comment by heinrich5991** [comment]
Windows works, needs testing on Linux and macOS.

**Comment by heinrich5991** [comment]
I think it also works on Linux now.

@edg-l As for packaging, would it be okay to install this shared library (and possibly libddnet-antibot.so) into /usr/lib/ddnet/? We need it to be called libsteam_api.so, and probably don't want to put it into the global namespace.

@Learath2 Could you try to test this on macOS?

You can put a `steam_appid.txt` next to the executable containing just the number `412220`. Then the real `libsteam_api.so` (or similar for other platforms) will recognize your built executable as DDNet.

**Comment by def-** [comment]
Should we get this into 14.4 or needs a bit more time?

**Comment by edg-l** [comment]
In `/usr/lib/ddnet/` is where the tools are installed

`install(TARGETS ${TARGETS_TOOLS} DESTINATION ${CMAKE_INSTALL_LIBDIR}/ddnet COMPONENT tools)`

Cmake is what does this, some packages put some libraries in folders there so i guess it would be ok, this is a change ddnet needs to make to the cmake file, not on the packagers part tho.

**Comment by heinrich5991** [comment]
Needs more time.

**Comment by heinrich5991** [comment]
This is ready now.

@deen @Learath?

**Comment by heinrich5991** [comment]
This is ready now.

@def- @Learath2?

**Comment by Learath2** [comment]
One question, should we maybe just use the steam name for steam tees? It's kinda confusing to have 2 names with one taking precedence

**Comment by heinrich5991** [comment]
From Discord:
> [2:10 PM] heinrich5991: @Learath2 about the nick situation: currently, you'll get the steam name by default, it will be "shadowed" in the nick text fields
> [2:10 PM] heinrich5991: until you put someting of your own in there
> [2:11 PM] heinrich5991: I'd prefer to allow changing nicks for steam, I'm open to more intuitive UI. if you guys think we shouldn't allow to change nicks in the steam version, I'm also fine with that
> [2:16 PM] Learath2: I'm not quite sure what the best practice is

**Comment by def-** [comment]
nori on Discord suggests: Mb we should use steam name for dummy too, like [D] prefix on it?

**Comment by heinrich5991** [comment]
@def- Done.

**Comment by def-** [comment]
bors r+
Thanks! Do I have to do anything special for the Steam build now?

**Comment by heinrich5991** [comment]
In the steam build, you need to replace the libsteam_api.so/libsteam_api.dylib/steam_api.dll with the appropriate one (right architecture, OS) from https://partner.steamgames.com/downloads/steamworks_sdk.zip (downloadable after logging into a developer account, subdirectory sdk/redistributable_bin/). Note that you need to rename the 64-bit Windows dll from steam_api64.dll to steam_api.dll.

**Comment by def-** [comment]
Thanks. To test that it works I guess I can just replace the DDNet.exe (and dll) in the steam directory?

**Comment by def-** [comment]
Also, I think we have no upgrade path for shared libs on Linux. If we ever need to update the stubs we will run into problems.

**Comment by def-** [comment]
Ok, we call it libsteam_api.dll, not steam_api.dll

**Pull request merged**
