### PR TITLE
Don't bypass the anti-spam system

### PR DESCRIPTION
**Pull request by heinrich5991**
Quick-fix for
https://github.com/ddnet/ddnet/pull/3669#issuecomment-794805243.

Probably breaks that feature a bit.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by murpii** [comment]
thanks heinrich

**Comment by houseme-kyle** [comment]
@heinrich5991 couldn't we mute them on the command level? Even though it is implied by the for-loop, the function doesn't allow for multiple messages.

**Comment by heinrich5991** [comment]
This is not the proper fix, this is merely a quick fix because the servers are currently being spammed using this method.

**Pull request merged**
