### PR TITLE
Overhaul console design: replace background, improve contrast

### PR DESCRIPTION
**Pull request by Robyt3**
Replace the dotted background texture of the console with a less noticeable noise texture.

Replace the large striped bar at the bottom of the console with a small bar with a slightly darker color than the respective console background. Remove the shadow above the striped bar.

Improve the spacing between the console backlog and input with the additional free space from the replaced striped bar. The total console height is not changed.

Improve the contrast of the console completion options by slightly increasing the saturation/brightness of the text color and by coloring the selection rectangle black instead of using an orange color which was very similar to the highlight color. Also highlight the matching string of the selected completion option instead of only highlighting it for all other options.

Screenshots:
- Local console:
   - Before:
local old
   - After: 
local new
- Remote console:
   - Before:
remote old
   - After:  
remote new

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]
Maybe my eyes are too bad but for me the background_noise looks the same as transparency. What are we going to do with people who like the old console style and want it back?

**Comment by ChillerDragon** [comment]
> What are we going to do with people who like the old console style and want it back?

I would consider my self quite conservative. And the change looks fine to me. Also this is only affecting users that are using the console. So I would suggest not worrying about users that dislike it until the first person complains.

**Review by heinrich5991 — APPROVED** [review]
I'm fine with the change, I think the new thing looks better.

I guess it's losing a bit on classic Teeworlds style.

**Review by Learath2 — APPROVED** [review]
Looks much more modern. I'm unsure whether there is any value in shipping the old version given that the console isn't something every player looks at.

LGTM

**Comment by Robyt3** [comment]
> It feels very empty without the bar at the bottom. I wouldn't suggest putting the old bar on the new design but a retexture of the bar would be nice if you have time 👍

You mean it's empty while no completion options are shown? I don't really like how the bar looked and used up a lot of vertical space even if it was using a different texture or untextured (see for example #9215). I replaced the bar with a small darker border and removed the top shadow entirely.

I think the console UX/UI could still be improved though, so this space would likely not be as empty eventually. Some ideas I had, that require more work than this PR that mostly puts a new skin over the old behavior:

- Scrollbars and buttons so console is also fully usable on Android.
- Show completion options in a vertical list like editor map settings and support mouse input.
- Also show the command description when completion options are shown (e.g. currently you can't see the description of `bind` unless you specify an argument).

**Comment by sjrc6** [comment]
I liked the textured bar at the bottom, it made it easy to tell what the console was open from a glance. It kind just feels like a grey rectangle with text now.

**Pull request merged**
