### PR TITLE
Don't warn about unfinishable map for super team

### PR DESCRIPTION
**Pull request by def-**
As reported by Cøke

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
Should this maybe also disable the killing of the team from the last patch?

**Comment by def-** [comment]
It is.

**Comment by heinrich5991** [comment]
This doesn't seem to change anything? TEAM_FLOCK is 0 and TEAM_SUPER is MAX_CLIENTS.

**Comment by def-** [comment]
Can't reproduce

**Pull request closed without merging**
