### PR TITLE
Improve performance of /top5points query, remove negative /top5points since it makes no sense anyway

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
It's still a bit slow, 1-2 seconds. Anyone got good ideas for how to speed it up?
```
MariaDB [teeworlds]> SELECT RANK() OVER w AS Rank, Points, Name FROM record_points WINDOW w as (ORDER BY Points DESC) ORDER BY Rank LIMIT 10, 5;
+------+--------+-------------+
| Rank | Points | Name        |
+------+--------+-------------+
|   11 |  23047 | .:Danytto:. |
|   12 |  22921 | Noctua      |
|   13 |  22718 | Infern@L    |
|   14 |  22232 | ano :3      |
|   15 |  22148 | Goran       |
+------+--------+-------------+
5 rows in set (1.282 sec)

MariaDB [teeworlds]> EXPLAIN SELECT RANK() OVER w AS Rank, Points, Name FROM record_points WINDOW w as (ORDER BY Points DESC) ORDER BY Rank LIMIT 10, 5;
+------+-------------+---------------+-------+---------------+--------+---------+------+--------+----------------------------------------------+
| id   | select_type | table         | type  | possible_keys | key    | key_len | ref  | rows   | Extra                                        |
+------+-------------+---------------+-------+---------------+--------+---------+------+--------+----------------------------------------------+
|    1 | SIMPLE      | record_points | index | NULL          | points | 7       | NULL | 292501 | Using index; Using temporary; Using filesort |
+------+-------------+---------------+-------+---------------+--------+---------+------+--------+----------------------------------------------+
1 row in set (0.000 sec)
```

**Comment by Learath2** [comment]
I honestly don't get why `RANK()` needs to go over every row, it should only need to go as far down as the bottom limit. If anyone knows someone working with mysql in a professional capacity maybe we could ask them as this is fairly odd.

Anyway `SELECT RANK() OVER (ORDER BY Points DESC) AS Rank, Name, Points FROM record_points LIMIT 10, 5;` is a tad shorter but not faster.

If a session variable is acceptable `SET @curRank := 0; SELECT @curRank := @curRank + 1 AS Rank, Name, Points FROM record_points ORDER BY Points DESC LIMIT 15;` is much faster. Needs some clever mysql trickery to get it into a subquery to extract the last 5 so might be easier to get the last 5 rows in C++.

If not maybe the same query but we rank it in C++ after we get the result?

**Comment by def-** [comment]
We also need to consider the case of people having the same points, should be same rank then. I could check if my old query (before we used rank) here, is faster.

**Comment by Learath2** [comment]
> We also need to consider the case of people having the same points, should be same rank then. I could check if my old query (before we used rank) here, is faster.

The second query I gave should work for people having the same points

**Comment by def-** [comment]
Yeah, it's a bit stupid that MariaDB doesn't do this optimization on its own.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
