### PR TITLE
Remove tile buffering

### PR DESCRIPTION
**Pull request by ChillerDragon**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
> What is the motivation for the changes of this pull request?

**Comment by ChillerDragon** [comment]
> > What is the motivation for the changes of this pull request?

https://github.com/ddnet/ddnet/blob/5aa4b58d4e030b5d55ebea612acbaebb52f20506/src/game/client/components/maplayers.cpp#L332

already checked here

**Comment by Jupeyy** [comment]
it's not a `or`. so either of them can be `true`

**Comment by ChillerDragon** [comment]
Ah yes lol

**Comment by ChillerDragon** [comment]
sorry xd

**Pull request closed without merging**
