### PR TITLE
Fix DbgDummy check being at the wrong place

### LINKED ISSUE #4325: weird debug macro
https://github.com/ddnet/ddnet/blob/15319a3e50e294c6a368332cc5c7e242b2d267d5/src/game/server/player.cpp#L168

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #4325.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Advantage over #4337: Easier to understand for me.

**Comment by def-** [comment]
> Advantage over #4337: Easier to understand for me.

Help, I'm trapped in a recursion.

**Comment by heinrich5991** [comment]
Oops, I meant #4329.

**Pull request merged**
