### PR TITLE
Some chat fixes

### PR DESCRIPTION
**Pull request by Jupeyy**
Very round:
screenshot_2020-10-22_22-16-56

bit round:
screenshot_2020-10-22_22-17-33

No rounding left:
screenshot_2020-10-22_22-18-16

No rounding at all:
screenshot_2020-10-22_22-18-54

old chat:
screenshot_2020-10-22_22-28-43

Just gave some examples so its easier to see what is nice

### CODE REVIEW

**Comment by Banana090** [comment]
Too dark screenshots to see anything. But I'll stay for my first version "very round"

**Comment by Jupeyy** [comment]
use a browser with zoom function, i prefer no rounding

**Comment by Banana090** [comment]
If really I would make the whole hud customizable. Every variable. Rounding, margin, position of HUD elements, padding, size...

**Comment by def-** [comment]
> If really I would make the whole hud customizable

https://github.com/ddnet/ddnet/issues/3106

**Comment by Jupeyy** [comment]
smaller tee, less margin

screenshot_2020-10-22_22-54-43

**Comment by Banana090** [comment]
@def- there must be an option to not show some config variables in the console. Then it's not the problem. Everything could be customizable by entering "Customize Hud Mode" and moving UI Boxes wherever you want.

**Comment by def-** [comment]
I think we should tune it so that it looks great for all use cases, and then no need to have so many options. Just one option to go back to the old chat style is good enough then.

**Comment by Learath2** [comment]
One issue with very round is that it looks exponentially worse the lower the resolution, it looks crisp on 1440p and highdpi.

**Comment by Jupeyy** [comment]
Ok small padding now, for you to test:
changes:

```static constexpr float MESSAGE_PADDING_X = 5.0f;
-       static constexpr float MESSAGE_TEE_SIZE = 8.0f;
+       static constexpr float MESSAGE_TEE_SIZE = 7.0f;
        static constexpr float MESSAGE_TEE_PADDING_RIGHT = 0.5f;
        static constexpr float FONT_SIZE = 6.0f;
-       static constexpr float MESSAGE_PADDING_Y = 2.0f;
-       static_assert(FONT_SIZE + MESSAGE_PADDING_Y >= 6.0f, "Corners for background chat are too huge for this combination of font size and message padding.");
+       static constexpr float MESSAGE_PADDING_Y = 1.0f;
+       static constexpr float MESSAGE_ROUNDING = 3.0f;
+       static_assert(FONT_SIZE + MESSAGE_PADDING_Y >= MESSAGE_ROUNDING * 2.0f, "Corners for background chat are too huge for this combination of font size and message padding.");```

**Comment by def-** [comment]
lgtm. Maybe a bit too round, but I don't mind.

**Comment by Jupeyy** [comment]
Sadly the tees are a bit far in the ground, to explain why, see for example a huge skin like this
screenshot_2020-10-25_16-08-44

it easily fills most of the chat background :/
very hard to fix

**Pull request merged**
