### PR TITLE
Lower dilate threshold

### PR DESCRIPTION
**Pull request by Jupeyy**
Mh hoped the diff is smaller, dunno if all diffs are caused by the redilate or if my zopfli version changed

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Each time we do something like this, our repository size permanently increases by the sum of all images. What is the motivation for this change?

**Comment by Jupeyy** [comment]
I know, we have to move to a submodule if thats a problem, the motivation is that the threshold was too high, the alpha threshold should only kick in for wrongly interpolated pixels

**Comment by Jupeyy** [comment]
i still need a non dilated version of f-ddrace @fokkonaut , you still got it?

**Comment by Jupeyy** [comment]
Seems like the first 64 tiles are the same in both images, so i just copied them over

**Comment by def-** [comment]
bors r+
Thanks

**Pull request merged**
