### PR TITLE
Remove vulkan dependency for headless client

### PR DESCRIPTION
**Pull request by ChillerDragon**
Turn off vulkan when compiling headless client.

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by heinrich5991** [comment]
This makes you unable to compile the headless client with vulkan enabled. Either only disable it in the CI directly, or just change the default whether Vulkan is enabled.

**Comment by def-** [comment]
How does headless client with vulkan make sense? It‘s supposed to run on servers withoug gpu, right?

**Comment by ChillerDragon** [comment]
> This makes you unable to compile the headless client with vulkan enabled. Either only disable it in the CI directly, or just change the default whether Vulkan is enabled.

Yea. But do we want to allow compiling the headless client with vulkan support? What does that even mean :D

**Comment by ChillerDragon** [comment]
Compiling on servers without gpu already works fine by passing ``-DVULKAN=OFF`` this pr is just to restrict the user to not be able to link useless vulkan. And also to avoid a depedency alert (which would also be solved with the default heinrich suggested)

**Comment by heinrich5991** [comment]
It seems to me that by default, OpenGL libraries are also linked into the headless client. Why is Vulkan different?

**Comment by heinrich5991** [comment]
You can turn off vulkan for the headless client using `-DVULKAN=OFF` manually. That should be enough. See also #6893.

**Pull request closed without merging**
