### PR TITLE
Fix rescue tee when swapping (fixes #4578)

### LINKED ISSUE #4578: /rescue after using /swap moves tee to old swap location
if only one tee is frozen:
https://user-images.githubusercontent.com/60477660/148668004-600e16fa-9f9c-4102-9af7-0e6a72d85430.mp4
If both tee are frozen:
https://user-images.githubusercontent.com/60477660/148668013-0d1fe55f-ccb9-45a7-bffd-9ae5d99ce39d.mp4
both videos resulted in a softlock

Reported by JimmyJazzThe1st

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by murpii** [comment]
Thanks deen, this fixed it

**Comment by Jupeyy** [comment]
Maybe also swap the rescue positoins?
I dunno if this could break something where the two tees are seperated from each other and then with /r would get to the old position again

**Comment by def-** [comment]
We do that already.

**Comment by Jupeyy** [comment]
Alright
bors r+

**Pull request merged**
