### PR TITLE
Add command 'repeat' to repeat the text last one said

### PR DESCRIPTION
**Pull request by sirius1242**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Sounds like spam for me? Could you explain what its usefull for?

**Comment by sirius1242** [comment]
Sometimes we would repeat the text which another one said. If you think this is spam, I'm so sorry to open this.

**Comment by 12pm** [comment]
Maybe show some example cases that aren't spam? ;)

**Comment by 12pm** [comment]
>if you the content you want to say is like that the last one said

obviously.. but why do you want to do that? you can reference a message easily with in other ways

**Comment by sirius1242** [comment]
You mean "I agree with him?" or "+1?", I think they do have some differences, there maybe some differences of custom between us, XD.

**Comment by def-** [comment]
I bet this would lead to people trying to write "I am gay" just so that you accidentally repeat it. :D 

This also seems a bit unusual for me, are there other games doing it? Maybe you could do something like `bind x say "是"` or is that not expressive enough?

Anyway, even if this particular PR might not get accepted, thanks for looking for ways to improve DDNet.

**Pull request closed without merging**
