### PR TITLE
Add infrastructure for preserving bugs

### PR DESCRIPTION
**Pull request by heinrich5991**
Unfix the grenade bug for "Binary".

### CODE REVIEW

**Comment by heinrich5991** [comment]
Needs testing: https://forum.ddnet.tw/viewtopic.php?f=68&p=63143#p63143.

**Comment by def-** [comment]
Why not have a config for enabling the old behaviour and set that on the map in question?

**Comment by heinrich5991** [comment]
@def- That was basically to discourage new maps to rely on the bug. But I guess you're right. ^^

**Comment by def-** [comment]
Then call the flag something with "old" or "bug" in the name to make it obvious that you're not supposed to use it and we just have it for compatibility.

**Comment by heinrich5991** [comment]
@def- Can we have it both ways? Now you can add `mapbug grenade-doubleexplosion@ddnet.tw` to the map config to retain the behavior, but the old "Binary" map also works.

**Comment by def-** [comment]
I don't like it personally.

**Comment by Learath2** [comment]
Well it was kinda our fault that it broke, it does maybe make sense to patch them in source but I'm still not sold on making what's essentially a map change with a source change.

**Comment by heinrich5991** [comment]
@def- You'd prefer to only have the config?

**Comment by def-** [comment]
Yep.

**Comment by def-** [comment]
I don't understand why this needs to be so complicated, it's literally a 2-liner to fix and now instead we have 2 large frameworks for fixing map bugs in incompatible ways. Seems really over-engineered to me.

**Comment by def-** [comment]
Anyway, I'll add this now since our players have seemingly been waiting for months with a broken map...

**Pull request merged**
