### PR TITLE
Try to fix code coverage upload (fixes #6277)

### LINKED ISSUE #6277: Code coverage is not being updated anymore
https://codecov.io/gh/ddnet/ddnet/branch/master shows that the last update was 2 months ago.

Also, there is a typo in the flag name "int**e**grationtests" (https://app.codecov.io/gh/ddnet/ddnet/flags).

### PR DESCRIPTION
**Pull request by def-**
> [2023-01-12T17:25:29.471Z] ['error'] There was an error running the uploader: No gcov files found

Broken in https://github.com/ddnet/ddnet/pull/5599 because the cmake-init-env overwrites outside env variables

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
@heinrich5991 How can I pass LDFLAGS when linking with rust?

**Comment by heinrich5991** [comment]
There's theoretically `RUSTFLAGS` and `-Clink-arg`. The problem is that we need to pass `--coverage` to the linker?

**Comment by def-** [comment]
Exactly.

**Comment by Robyt3** [comment]
Any idea how to solve the build failure on Ubuntu, @heinrich5991?

**Comment by heinrich5991** [comment]
No, not right now. :(

**Comment by def-** [comment]
Done.

**Comment by Robyt3** [comment]
Exported run logs for permanent reference: [14_Test headless client (unit tests).txt](https://github.com/ddnet/ddnet/files/12164570/14_Test.headless.client.unit.tests.txt)

**Comment by heinrich5991** [comment]
I fixed the remaining build problem.

Could you review? @Robyt3

**Review by def- — COMMENTED** [review]
Thanks @heinrich5991

**Review by Robyt3 — APPROVED** [review]
Thanks! Looks like it already works, the PR is included in https://app.codecov.io/gh/ddnet/ddnet/pulls.

**Pull request merged**
