### PR TITLE
Add system console command

### PR DESCRIPTION
**Pull request by ChillerDragon**
This adds the possibility to execute bash or BATCH commands in the client console.
It can be used to run .sh or .bat files via bind and speedup tasks like starting local server.
Idea by fokkonaut https://forum.ddnet.tw/viewtopic.php?f=48&t=5769

### CODE REVIEW

**Comment by def-** [comment]
Remote shell via game server, yay.

**Comment by ChillerDragon** [comment]
Ye im not too sure about security too. But i don't know yet how to abuse it.

**Comment by def-** [comment]
The old attack was to send spoofed UDP packets pretending to be an admin user, thus executing arbitrary commands on the host system.

**Comment by ChillerDragon** [comment]
Yes but isn't it different client side?

**Comment by def-** [comment]
Ah, it's in the client, I didn't read the change before :)

Not so bad then, but generally why not just use window manager shortcuts?

**Comment by Learath2** [comment]
No, this won't end well, someone will sneak a `rm -rf --no-preserve-root /` in a 1337 h4x script that kids will download and it'll be our fault.

**Comment by ChillerDragon** [comment]
Well you can... but i think you can use this to do a lot of things. Im not sure yet what to use it for. But you could automatically create a copy of the current demo or something (i don't know if this really works) or stuff like this. @Learath2 ye maybe.

**Comment by H-M-H** [comment]
If you really want to execute some other programs via binds you could (ab)use the `echo` command and parse the client log I guess. But you should be careful not to mix them up with actual servermessages.

**Comment by heinrich5991** [comment]
I'd like @H-M-H idea, I think that can achieve the same effect without adding the ability to call arbitrary commands from the DDNet client.

**Comment by heinrich5991** [comment]
I've made a little Python script that can do what you want, with current DDNet:

```python
import re
import subprocess
import sys

def main():
    import argparse
    p = argparse.ArgumentParser(description="Parse a program's output and execute other depending on that")
    p.add_argument("--keyword", default="execute", help="Regular expression to watch for. The remainder of lines containing that keyword will be executed. Default: ^execute.")
    p.add_argument("command", metavar="COMMAND", help="Command whose output should be watched")
    p.add_argument("args", metavar="ARGS", nargs=argparse.REMAINDER, help="Parameters to the command")
    args = p.parse_args()
    command = subprocess.Popen([args.command, *args.args], stdin=subprocess.DEVNULL, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    keyword = re.compile((args.keyword + " ").encode())
    processes = []
    for line in command.stdout:
        sys.stdout.write(line.decode(errors="replace"))
        sys.stdout.flush()
        match = keyword.search(line)
        if match:
            remainder = line[match.end():]
            try:
                processes.append(subprocess.Popen(remainder, shell=True, stdin=subprocess.DEVNULL))
            except OSError as e:
                print("Failed to run {:?}: {}".format(remainder, e))
    for p in processes:
        p.wait()

if __name__ == '__main__':
    sys.exit(main())
```

Use a strong password, e.g. generate one with `python -c 'import random,string;print("".join(random.SystemRandom().sample(string.ascii_letters + string.digits, 16)))'` and then call DDNet like this: `python [script] --keyword [password] DDNet`. Then you can execute programs from a DDNet client by binding `echo [password] [your command]`.

Would this work for you?

**Comment by ChillerDragon** [comment]
Sick Python skills. Good Job... but generating a password and starting a script with the client and 27 arguments is too much work. Nobody would use this because of lazyness. And even If i would find a cool usecase i would prefer to modify the client manually and add this pr.

**Comment by def-** [comment]
I used something like this to make a quiz bot running in my client. We also have snake and tron for ddnet servers:
https://github.com/ddnet/ddnet-scripts/blob/master/servers/scripts/tron.sh
https://github.com/ddnet/ddnet-scripts/blob/master/servers/scripts/tron.py

**Comment by heinrich5991** [comment]
I believe it should take some work to execute arbitrary commands from the client.

**Pull request closed without merging**
