### PR TITLE
Also use Brokecdx-' new blockworlds entities

### PR DESCRIPTION
**Pull request by def-**
not just for entities_clear

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
@Jupeyy Weird, dilating the file doesn't change it. Any idea?

**Comment by Jupeyy** [comment]
> @Jupeyy Weird, dilating the file doesn't change it. Any idea? I just copied it from entities_clear.

Mh i've a different sha256 checksum, have you recompiled the dilate, since it was changed in #3600

**Comment by def-** [comment]
`ninja all` doesn't rebuild the tools` apparently? Tried `ninja tools` now.

**Comment by Jupeyy** [comment]
Ah alright
bors r+

**Comment by heinrich5991** [comment]
@def- `all` is a CMake-specific target that gets built if you pass nothing else, so it's not everything for us. Use `everything` to build everything.

**Comment by def-** [comment]
I would argue cmake made the wrong decision and passing nothing should use something like `default` instead of all.

**Pull request merged**
