### PR TITLE
Leave space for \0 byte (fixes #1526)

### LINKED ISSUE #1526: Client freezes after pressing TAB in spectator view
I tested it on the latest master build on Linux.

How to reproduce it: 
1. start DDnet
2. join server 
3. type /spec in the chat or press your key.
4. press TAB to display the scoreboard.

Expected result:
Maybe you see the scoreboard? 

Actual result:
The client freezes and crashes somehow without an error message..........

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by def-** [comment]
Post mortem:

Quoting the man page of vsnprintf:

```
RETURN VALUE
       Upon successful return, these functions return the number of characters printed (excluding the null byte used
       to end output to strings).

       The functions snprintf() and vsnprintf() do not write more than size bytes (including  the  terminating  null
       byte  ('\0')).  If the output was truncated due to this limit, then the return value is the number of charac‐
       ters (excluding the terminating null byte) which would have been written to the final string if enough  space
       had  been  available.   Thus,  a return value of size or more means that the output was truncated.  (See also
       below under NOTES.)

       If an output error is encountered, a negative value is returned.

[...]

       The glibc implementation of the functions snprintf() and vsnprintf() conforms to the C99 standard,  that  is,
       behaves as described above, since glibc version 2.1.  Until glibc 2.0.6, they would return -1 when the output
       was truncated.
```

So when for example "16: " doesn't fit into the 4 byte sized `aBuffer` 4 is returned, even though only 3 bytes have been written. Thus passing the 4 into TextEx as the size means that the 4th character will never be reached since it's beyond the end already. My assumption was that a truncation would result in size being -1 to indicate an error (or 3 to indicate how much was written), both of which would have been fine. Approaches to go from here:

1. Be more careful about using str_format and then calling TextEx and similar functions
2. Fix str_format to behave as expected, its documentation says `Returns: Length of written string`

I'd go with 2.

**Comment by heinrich5991** [comment]
2) sounds like the sane option.

**Comment by def-** [comment]
Can we get this fix in anyway? We should have both.

**Comment by heinrich5991** [comment]
Oh true, sorry!

bors r+

**Pull request merged**
