### PR TITLE
add ellipsis again

### PR DESCRIPTION
**Pull request by C0D3D3V**
grafik
grafik

@Jupeyy  can you please test if this also decreases the fps significant more than without this PR?

without ellipsis (and name in mini score hud flows over the left border):
grafik

with ellipsis:
grafik

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by C0D3D3V** [comment]
without:
grafik

with:
grafik
grafik

**Comment by C0D3D3V** [comment]
So for me, we could also leave out the ellipsis altogether. And only add them when we cache the scoreboard at some point in the future. But we can also try it again to include the ellipsis in the client and see if someone complains about less fps.

**Comment by heinrich5991** [comment]
> So for me, we could also leave out the ellipsis altogether. And only add them when we cache the scoreboard at some point in the future. But we can also try it again to include the ellipsis in the client and see if someone complains about less fps.

I like including the ellipsis.

**Comment by heinrich5991** [comment]
bors r+

Thanks for figuring that out. :)

**Pull request merged**
