### PR TITLE
Move close button ingame to very left so old players don't use wrong muscle memory

### PR DESCRIPTION
**Pull request by def-**
Screenshot 2022-09-27 at 13 33 27
Screenshot 2022-09-27 at 13 36 11

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
I think it's fine on the left rather than on the right.

**Comment by heinrich5991** [comment]
I think it's bad that the close game button is where players expect the close window button.

Would it have few lines of code to add an option to swap close window and close game buttons, defaulting to close window on the right?

**Comment by heinrich5991** [comment]
> Is this a trick question? Too many options already :D

It's not supposed to be a trick question. I'm asking because I see that players are accustomed to the old position and it's some sort of input so it's hard to unlearn, but I also see the old position is bad because it's unintuitive.

But yea, too many options. ^^

**Comment by def-** [comment]
I'd prefer just going back to old state: https://github.com/ddnet/ddnet/pull/5906, I don't see any good solution here.

**Pull request closed without merging**
