### PR TITLE
Inform client about failure to join because of invalid utf8

### PR DESCRIPTION
**Pull request by def-**
As reported by Dan_cao. Will provide client fixes too.

### CODE REVIEW

**Comment by heinrich5991** [comment]
This should be done on the client side rather.

**Comment by def-** [comment]
I think we should do both, since some people won't update client.

**Comment by heinrich5991** [comment]
I think we shouldn't. This just introduces edge cases in the protocol.

**Comment by heinrich5991** [comment]
We could maybe drop the client if it sends us a bad info, so it is more actionable for the user.

**Comment by def-** [comment]
I don't think we can drop someone without connecting them first.

**Comment by heinrich5991** [comment]
`Server()->Kick` does not work?

**Comment by def-** [comment]
Thanks, that works. Dummy doesn't get it shown though.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
