### PR TITLE
Some browser improvements

### PR DESCRIPTION
**Pull request by def-**
screenshot-20200919@220208
screenshot-20200919@220156
- Increase size of Name and Clan in adding friend fields
- Smaller Search and Exclude fields
- No more duplicate Search - Search - Search text
- Smaller Connect and Refresh buttons
- Search and Exclude no longer so dark

### CODE REVIEW

**Comment by gerdoe-jr** [comment]
Looks cleaner, imo.

**Comment by edg-l** [comment]
I tested it and looks nice, just one note but it's probably unrelated to this pr, in the search and exclude textbox, the X button only shows hover effect when hovering the textbox and not the button, which feels weird.

**Comment by def-** [comment]
fixed.

**Comment by edg-l** [comment]
Works.

bors r+

**Pull request merged**
