### PR TITLE
Move map details to the file menu and add CC-BY-SA 4.0 license by default

### PR DESCRIPTION
**Pull request by necropotame**

### CODE REVIEW

**Comment by def-** [comment]
Looks reasonable. Other thoughts?

**Comment by heinrich5991** [comment]
Putting a license by default is a bad idea in my opinion. Most people probably don't even know what CC-BY-SA is.

**Comment by heinrich5991** [comment]
See also #391.

**Comment by necropotame** [comment]
There is always a default license, since an empty field means that you keep all the rights. This discreet default license only make things more coherent with how works TeeWorlds and map sharing. In #391, def- fears that people will start to think about license. In this commit, it's not particularly visible, but it doesn't change how map sharing works, so I guess it's fine. It makes only things more legal. Think about your map database. Are you sure that you can distribute all those maps? Have you checked that the license allows it? Or that the credits, that may be visible only in the mod, is included each time? I understand your point and that's why this dialog is automatically opened when you create a new package in TeeUniverse. But TeeWorlds works differently and it will be anoying in this context. And as I said, I think that this default license only ensure that TeeWorlds/DDNet works how you want.

**Comment by heinrich5991** [comment]
>It makes only things more legal. Think about your map database. Are you sure that you can distribute all those maps? Have you checked that the license allows it? Or that the credits, that may be visible only in the mod, is included each time?

I'm not sure a "license by default" is more legal than what we have today. Especially not if it's hidden as you describe.

**Comment by necropotame** [comment]
Ahah, if you want, I can add a pop-up at the first time the editor is opened: "By default, all maps are saved using the license CC BY-SA 4.0, which means that everyone can use and modify your map as long as you are credited. You can also change the license in the metadata dialog", with one button "Got it!" to close it :P

**Comment by timakro** [comment]
We should probably show the so called "Map details" every time the map is saved, maybe the file browser could be made a little bit smaller to make some space. There we could kindly ask the mapper to choose a license which allows modification and redistribution like CC BY-SA 4.0 because it makes sense in the context of an open source game and is in the interests of the community. The license you set on a map could be saved in a config setting and be used by default when a new map is saved.

**Comment by necropotame** [comment]
I think it's a bad idea to have meta datas in the same place than the file dialog. A dedicated entry is needed for me.
We can display a pop-up each time the map is saved with an empty license (like for a new map). The default license will be CC-SA-BY, but we will list some alternatives too. @heinrich5991, is it okay for you?

**Pull request closed without merging**
