### PR TITLE
[Idea] Add some decent hover effects and colors

### PR DESCRIPTION
**Pull request by Jupeyy**
Generally, would be nice to have very decent hover effects and decent colors.

I just tried for fun adding hover effects to menu tabs(red for the quit button),

hover effects for the server browser items

and color for search/exclude

I'm not an artist, it doesnt look good, if someone wants to overtake, he/she would be very welcome todo so

image

image

screenshot_2020-09-16_03-38-40

### CODE REVIEW

**Comment by def-** [comment]
I like the hover effect, especially in the server browser.

Not sure about the red and green search fields though. But sometimes these things take getting used to, like the game type and ping colors.

**Comment by Jupeyy** [comment]
Yeah it looks bad, the idea is to make it easier for new players to get a feeling for what the client can do... The whole server browser is really just a lot of white text

**Comment by def-** [comment]
Maybe also add the hover effect to votes.

**Comment by Jupeyy** [comment]
@def- opinion on using the space more efficient, and be more verbose in trade

screenshot_2020-09-16_14-53-45

**Comment by def-** [comment]
I like it. Maybe make the Refresh+Connect buttons bigger, same size as Reset filter and Add friend (they are not the same size yet either).

Also make Search and Exclude fields same size as Server address field.

I think Connect & Refresh should not be connected.

**Comment by Jupeyy** [comment]
Before(with adjusted button sizes):
screenshot_2020-09-16_15-24-48

After:
screenshot_2020-09-16_15-37-44

**Comment by Jupeyy** [comment]
Hover effect for listboxes added, that also includes
Resolution settings
Tee selection and other stuff that uses it

**Comment by Jupeyy** [comment]
maybe a simpler, more modern looking scrollbar?
image

**Comment by def-** [comment]
The search servers block is a bit too dark. Should have the same color as Countries/Types block.
Text in Search & Exclude is still smaller than in Server address
player(s) online -> players and player
server(s) online -> servers and server
For the scroll bar: Everything else is round, so not sure this fits in.

**Comment by def-** [comment]
Oh, and use the space for the Search servers: more effectively, in 5:4 it's nearly unusable
screenshot-20200916@164333

**Comment by Jupeyy** [comment]
screenshot_2020-09-16_16-56-51

screenshot_2020-09-16_16-57-21

**Comment by Jupeyy** [comment]
if there is a client update or unread news
image

uses the same color as the start menu, when there are unread news

**Comment by def-** [comment]
I think Filter, Info, Friends are too large. Might not fit with all translations.

**Comment by def-** [comment]
Rest looks good to me.

**Comment by Jupeyy** [comment]
0.7 uses iconds, but i dunno if they really intuitive enough

sidebar

**Comment by Jupeyy** [comment]
material icons have good icons, but they dont look very teeworlds like:
baseline_group_add_black_18dp

**Comment by Jupeyy** [comment]
tested some random languages, turkish and spanish seems like having the longest strings, should fit now

**Comment by def-** [comment]
Anyone else want to give their opinion before I merge?

**Comment by def-** [comment]
Server browser background is not transparent anymore, seems weird.

**Comment by def-** [comment]
bors r+
Good to see someone else working on UI improvements. I think a lot could still be improved all-over in the menus

**Pull request merged**
