### PR TITLE
Remove unused `CImageInfo::ImageFormatFromInt`

### PR DESCRIPTION
**Pull request by Robyt3**
Follow-up for #8326.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by heinrich5991 — COMMENTED** [review]
The first commit is obviously good.

Hmmm. I'm actually quite happy about forgetting that this was a format field in code, and only treat it as a "must be 1".

`CMapItemImage_v2::CURRENT_VERSION` should probably be removed, there's only one current version of the image item: the one we write to files.

**Comment by Robyt3** [comment]
I removed the second commit.

> Hmmm. I'm actually quite happy about forgetting that this was a format field in code, and only treat it as a "must be 1".

Yeah, I understand the motivation. Seems good like it is.

> `CMapItemImage_v2::CURRENT_VERSION` should probably be removed, there's only one current version of the image item: the one we write to files.

I eventually want to add a constants for the mapitem version to every mapitem class, but it makes sense that it wouldn't be called `CURRENT_VERSION` but only `VERSION` since it's not the current version as you say. So for example `CMapItemImage_v2::VERSION` denotes the minimum version which a `CMapItemImageX` object needs to have, so accessing it as a `CMapItemImage_v2` is supported.

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Comment by heinrich5991** [comment]
> > `CMapItemImage_v2::CURRENT_VERSION` should probably be removed, there's only one current version of the image item: the one we write to files.
> 
> I eventually want to add a constants for the mapitem version to every mapitem class, but it makes sense that it wouldn't be called `CURRENT_VERSION` but only `VERSION` since it's not the current version as you say. So for example `CMapItemImage_v2::VERSION` denotes the minimum version which a `CMapItemImageX` object needs to have, so accessing it as a `CMapItemImage_v2` is supported. I'll handle all map items in one commit eventually, not in this PR.

What's the benefit of having such a constant? Writing `>= CMapItemImage_v2::VERSION` instead of `>= 2` is a lot longer and seems about as clear to me.

**Pull request merged**
