### PR TITLE
Add dbg_unpredicted_shadow (fixes #2100)

### LINKED ISSUE #2100: add dbg_unpredicted_shadow 0/1?
I personally hate it when ctrl+shift+d'ing.
Maybe because i'm a "high" ping player, it's very distracting.
dbg_unpredicted_shadow

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
That looks like a mess. `dbg_unpredicted_shadow`, `cl_unpredicted_shadow`.

**Comment by def-** [comment]
Better suggestion?

**Comment by heinrich5991** [comment]
Nothing really comes to my mind. One idea would be having `cl_unpredicted_shadow` take multiple values (always, when in debug, never). I'll leave the judgment call about whether this is better to you.

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
Thanks.

bors r+

**Pull request merged**
