### PR TITLE
`CMsgPacker` doesn't know about message ID encoding

### PR DESCRIPTION
**Pull request by heinrich5991**
CC #6289

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
This doesn't work anymore. I think because `Header.m_Size = pMsg->Size();` is different when you don't add the message ID to the packer.

Would be cleaner if you change the `PackMessageSystem` function to `inline void PackMessageSystem(CMsgPacker &Msg)` and move it next to `SendMsgs`, so you don't need to use `CVariableInt` directly.

**Comment by heinrich5991** [comment]
> Would be cleaner if you change the `PackMessageSystem` function to `inline void PackMessageSystem(CMsgPacker &Msg)` and move it next to `SendMsgs`, so you don't need to use `CVariableInt` directly.

Putting it into `CMsgPacker` would be weird as well; its packer doesn't usually contain the message ID. Perhaps they could be replaced by `CPacker` instances instead.

**Comment by Robyt3** [comment]
> Putting it into `CMsgPacker` would be weird as well; its packer doesn't usually contain the message ID.

I mean move the `PackMessageSystem` function to `network_server.cpp` instead of keeping it in `CMsgPacker`.

I initially put the function in `CMsgPacker`, because it was also done like this on upstream.

This entire feature is weird TBO, as the engine network server depends on the higher-level protocol messages.

**Comment by heinrich5991** [comment]
Now I simply removed `CMsgPacker` and used `CPacker` instead, we gain nothing by using `CMsgPacker`.

**Comment by Robyt3** [comment]
Thanks.

bors r+

**Pull request merged**
