### PR TITLE
Fix shift + left click in editor (fixes #5626)

### LINKED ISSUE #5626: Shift + Left click in editor crashes the game
Reported by Seigneur on discord
Client version 16.2.2

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by Robyt3 — APPROVED** [review]
I assume it didn't crash before because the std::vector implementations may have more out-of-bounds error checking than tl/array?

**Comment by Kaffeine** [comment]
Seems correct.
I was in minutes from releasing a forked client with mod-specific editor features. :smile:

**Review by Kaffeine — APPROVED** [review]

**Comment by C0D3D3V** [comment]
> I assume it didn't crash before because the std::vector implementations may have more out-of-bounds error checking than tl/array?

No, the problem is the call and the function of CLayerTiles::FillSelection

https://github.com/ddnet/ddnet/blob/27a4c494e9d17836c7473165b67e47b2d876c265/src/game/editor/layer_tiles.cpp#L410-L459


Before it was not a problem to access `m_Brush.m_vpLayers[BrushIndex]` with `m_Brush.m_vpLayers` beeing empty and `BrushIndex` beeing 0, because the Brush gets not accessed inside of the function. Because of the `Empty` argument all path in that the brush is accessed are not used. Thats also why this change, changes the behaviour. I would recommend to set the brush to nullptr if `m_Brush.m_vpLayers.size() != NumEditLayers` or your new condition is met. Actually the old condition should be enough in theory but I guess the new is safer.

**Comment by Chairn** [comment]
@heinrich5991 can you accept the PR?

**Comment by heinrich5991** [comment]
I guess it fixes the crash, even if the logic looks wonky.

bors r+

Thanks!

**Pull request merged**
