### PR TITLE
Filter whitelist servers

### PR DESCRIPTION
**Pull request by scar17off**
## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [X] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
It looks like you could instead enter "whitelist" into the exclude field. Does that not work for you?

**Comment by def-** [comment]
You can also exclude multiple words by separating them using ; (I think)

**Comment by Robyt3** [comment]
The exclusion filter should be sufficient to achieve this. We don't need another option for it in my opinion.

**Comment by heinrich5991** [comment]
Can already be achieved with existing features.

**Pull request closed without merging**
