### PR TITLE
Remove mapbugs system, add sv_old_grenade_explosion

### LINKED ISSUE #1559: Grenade double explosion fix is broken
you all know the problems with tunezones and the fixed grenade physics.
turns out that the map "Lunar Base" by Blue has been impossible for the past 1.5 years
on the map at CPtele 12 when door 9 is open and you want to go over it with grenade boost it is now pretty muchg impossible.
i let N9mkOik, kys:), Lexin and Cor try the part (all very high ranked players , all already finished the map in a casual manner and 2 of them are in the top5)

jao added that link thats meant to fix it in the server setting but it didnt increase the boost enough.

pls fix

### PR DESCRIPTION
**Pull request by def-**
Fixes #1559

### CODE REVIEW

**Comment by heinrich5991** [comment]
In what way does that fix the bug reported in #1559?

Is the problem that the fix wasn't active? My understanding was that the fix itself didn't work.

As I understood you, DDNet won't implement backwards-incompatible changes in any way, so the map bugs system is a dead weight. In this way, this is a nice negative line count. :)

**Comment by def-** [comment]
I assumed the fix was not active anymore since someone changed something else in the map and forgot to update the hash. Maybe I'm wrong about that though.

**Comment by heinrich5991** [comment]
Or you keep the ranks and make players unhappy about unbeatable ranks. You always forget this option.

The idea of the mapbugs system was precisely that you *can* update the source to change old maps but you can *also* change maps to enable mapbugs via the `mapbugs` command in changed maps. There's no need to update the hash in the source – and as I understood jao, he updated the map to include the command.

**Comment by def-** [comment]
> Or you keep the ranks and make players unhappy about unbeatable ranks. You always forget this option.

I don't forget about it. I consider it unfair.

Oh, I didn't know about the mapbugs command. Then I don't know why it's not working.

**Pull request closed without merging**
