### PR TITLE
Fix vulnerability, see official teeworlds news

### PR DESCRIPTION
**Pull request by Schwertspize**
https://www.teeworlds.com/forum/viewtopic.php?pid=116308

### CODE REVIEW

**Comment by heinrich5991** [comment]
This is not a proper fix, it's just a hack.

**Comment by Schwertspize** [comment]
ehm nice Heinrich. on tw forum you say we should apply it, here you say we should not.

**Comment by heinrich5991** [comment]
We should commit a proper fix to the repository, not just the hack.

**Comment by CytraL** [comment]
commit in vanilla no? i see that DDRaceNetwork are too distanced of vanilla master no?

**Comment by heinrich5991** [comment]
Oh nvm, I thought this was the official teeworlds repository. You're free to apply this to ddnet obviously (sorry!).

**Pull request merged**
