### PR TITLE
DNSBL whitelist

### PR DESCRIPTION
**Pull request by 12pm**
I think it's easier to manage like that

### CODE REVIEW

**Comment by def-** [comment]
Should also allow ranges, right?

**Comment by Learath2** [comment]
I really think this belonged on the dnsbl server and not in here :/

**Comment by heinrich5991** [comment]
Yea, I think this should go into the DNSBL server we have running.

**Comment by 12pm** [comment]
I thought about it and figured it would be easier to apply (quick) changes like this

**Comment by def-** [comment]
Oh well, I didn't even know we had our own DNSBL server

**Pull request closed without merging**
