### PR TITLE
Add /pausevoted and /specvoted

### PR DESCRIPTION
**Pull request by def-**
- Also fix /pause and /spec with name parameter a bit
- Move out common code between pause/spec

### CODE REVIEW

**Comment by heinrich5991** [comment]
I think this changes behavior if using `/pause` while in `/spec`. Previously it got you back to the game, now it puts you into `/pause`.

**Comment by heinrich5991** [comment]
But without telling.

Can confirm on a currently running DDNet server.

**Comment by Learath2** [comment]
@heinrich5991 I think we didn't notice at the time and only discussed it after people noticed it. We should decide which one we want and never change it again.

**Comment by heinrich5991** [comment]
LGTM then I guess.

bors r+

**Pull request merged**
