### PR TITLE
Quit when configured bindaddr cannot be resolved, quit client when failing to open network client for 25 times 

### PR DESCRIPTION
**Pull request by Robyt3**
## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
bors r+
Nice

**Comment by heinrich5991** [comment]
bors r-

I think that resetting the config without telling the user is a bit bad; why do we even have the config in the first place?

**Comment by heinrich5991** [comment]
What does this fix? If it does fix something, could we give the user one of the warnings that their bind address hasn't been used? Resetting the config variable seems a bit much to me.

**Comment by Robyt3** [comment]
Without b6c84ac43b503e1e05f8b73617fb154fb77ae844 the client cannot connect to the HTTP master server when starting with a bindaddr that cannot be resolved. Alternatively, we could check whether the bindaddr can be resolved again in the HTTP component:

https://github.com/ddnet/ddnet/blob/dd09c59710cd480bc2c1ddf450c4038997dbfb1b/src/engine/shared/http.cpp#L252-L255

That's probably better, as it would also handle the case that the server uses this component. Additionally, we could print log messages when the bind address cannot be resolved in those cases.

cebcfda94b47ad4689c4de33339780f8f26e4794 fixes that the client hangs indefinitely when starting with a bindaddr that *can* be resolved but that the socket cannot be bound to. Instead of resetting the configured bindaddr we could also just print a log message that the bindaddr setting was not used and let the user deal with it, if you prefer that.

**Comment by Robyt3** [comment]
I also noticed that the SQL bindaddr config is entirely unused:

https://github.com/ddnet/ddnet/blob/dd09c59710cd480bc2c1ddf450c4038997dbfb1b/src/engine/shared/config_variables.h#L260

And the following seems wrong, as the same string is used as input and output for a `str_copy`:

https://github.com/ddnet/ddnet/blob/dd09c59710cd480bc2c1ddf450c4038997dbfb1b/src/engine/server/server.cpp#L3418

Should we always use the configured SQL bindaddr when adding SQL servers, or should we just remove the setting?

**Comment by heinrich5991** [comment]
If we think that the user is too stupid to handle the bindaddr config, maybe we should remove it from the client? On a server, bindaddr is used to bind to one specific interface/IP address in case the server has multiple. In this case, ignoring bindaddr is outright dangerous, it might leak IP addresses that were supposed to be hidden. What's the use case for bindaddr in the client? Is it affected by silently or not silently changing it?

**Comment by Robyt3** [comment]
> What's the use case for bindaddr in the client? Is it affected by silently or not silently changing it?

It allows clients to specify their network interface. Could be relevant for using a VPN network interface.

> Is it affected by silently or not silently changing it?

If you were trying to use a VPN but it doesn't work and silently ignores it then that's probably bad.

**Comment by Robyt3** [comment]
I changed it so client and server quit when the bindaddr cannot be resolved. And the bindaddr is not reset automatically now, but the error message suggest checking the bindaddr setting.

**Comment by Robyt3** [comment]
Still ready for review. We can think about allowing the client to start without networking afterwards (#6482). I consider quitting to be a definitive improvement over hanging when the network cannot be initialized.

**Comment by def-** [comment]
bors r+
Thanks!

**Pull request merged**
