### PR TITLE
Add +resetdummy

### LINKED ISSUE #2053: Reset Dummy/Main Function
Hello friends,

I'd like to know if its possible to add a function similar to cl_dummy_resetonswitch to the ddnet client.
Basically I'd love to reset my main or dummy via a single key press without having to switch to my dummy like the command mentioned above.

Yes, im aware it's possible to just enable hammerfly but upon disabling it, he'll just hook in the same direction he held before.

### PR DESCRIPTION
**Pull request by ardadem**
Closes #2053

### CODE REVIEW

**Comment by murpii** [comment]
@def- 
do you think you could make this work in custom .cfgs / console aswell? pretty please
as of now it only works if its bound to a key / doesnt have like +fire +weapon1-5 does.

**Comment by def-** [comment]
I don't understand. How does it work differently from +fire?

**Comment by murpii** [comment]
@def- 
You can test this ingame while playing. If you type +fire into the console, the tee fires. if you type +hook, +left, +right or +jump, the tee does nothing. If you have dummy hook a ceiling and type +resetdummy, the dummy doesnt reset. In order to actually reset you'd have to bind +resetdummy to a key and manually press the key.

**Comment by def-** [comment]
The reason is that you probably have no counter. Try making it a KeyInputCounter?

**Comment by murpii** [comment]
@def- oh that actually did the trick. Thanks 👍

**Comment by murpii** [comment]
@ardadem 
could you update it?

**Pull request merged**
