### PR TITLE
Editor: Select game layer by default (fixes #2834)

### LINKED ISSUE #2834: Select game layer on map load in editor
Game layer is a core thing for any map for most game types. Can we have it selected after map loaded in editor ?

### PR DESCRIPTION
**Pull request by def-**
Since it's the most important layer

### CODE REVIEW

**Comment by BannZay** [comment]
nice! This closes #2834

**Comment by Jupeyy** [comment]
should it also scroll to the game layer if its not visible, or not so important? @BannZay

**Comment by BannZay** [comment]
@Jupeyy I think it is not that important.

**Pull request merged**
