### PR TITLE
Verify ger10 servers button in left refresh button side on browser menu(T-Client idea)

### PR DESCRIPTION
**Pull request by mazty47**
I think this will good on the client for verify ger10 servers.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)
button

### CODE REVIEW

**Review by heinrich5991 — COMMENTED** [review]
Hello, and thank you for your first pull request!

Your pull request makes it possible for the player to click a button to verify their IP address to the ger10.ddnet.org server. This is probably something that should happen automatically when the user tries to connect to GER10. Could you perhaps hardcode GER10's IP address (45.141.57.22) and if the player connects to this IP address, do the verification with https://ger10.ddnet.org/ automatically?

This PR is related to #8210, but doesn't solve the general case. But that's okay, I just wanted to link to it.

**Comment by mazty47** [comment]
ok, i will try it

**Comment by ChillerDragon** [comment]
If we start hardcoding stuff can we add more? For example:
- https://wl.reitw.fr/
- https://tw.fokkonaut.de/

**Comment by jxsl13** [comment]
is there no such field in the masterserver's json that could simply be used for this verification process and for this button?

**Comment by heinrich5991** [comment]
> If we start hardcoding stuff can we add more? For example:
> 
> * https://wl.reitw.fr/
> 
> * https://tw.fokkonaut.de/

I'd not hardcode more.

> is there no such field in the masterserver's json that could simply be used for this verification process?

Currently not, but that'd be the correct solution for the general problem: #6808. Not something I want to ask from a first-time contributor though.

**Comment by Avolicious** [comment]
It would be nice if the webserver could return some data to the client, telling if he accepted or declined.

For example:
- You want to IP ban/range ban, you could add this as security measure to your server
- You are hosting a tournament and want specific players on specific servers due to tournament rules
- You want the user to OAuth2 first so he can allowlist for this server

We could either use HTTP status codes for this or use a json body response to send this to the client.

**Pull request closed without merging**
