### PR TITLE
Execute CFGFLAG_GAME configs from map load on the client

### LINKED ISSUE #6774: Deepfly prediction does not work.
in prediction/entities/charecter.cpp there is code that attempts to predict deepfly but it seems like the client isn't able to know the status of sv_deepfly even when the command is set in the maps server settings.

The client console reports "chatresp: No such command: sv_deepfly."

I think might be a broader issue with the CFGFLAG_GAME flag I'm not sure? 
sv_hit seems to be predicted correctly.

```cpp
// don't fire hammer when player is deep and sv_deepfly is disabled
if(!g_Config.m_SvDeepfly && m_Core.m_ActiveWeapon == WEAPON_HAMMER && m_Core.m_DeepFrozen)
    return;
```

### PR DESCRIPTION
**Pull request by sjrc6**
Fixes #6774

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by sjrc6** [comment]
Is there any reason sv_save_worse_scores should be CFGFLAG_GAME? @heinrich5991

**Comment by heinrich5991** [comment]
I think we use it in the map Flappy Birds, maybe others.

**Comment by heinrich5991** [comment]
This would probably make the commands accessible to the user as well? If so, could it be adjusted only for the time when the map configs are executed?

**Comment by sjrc6** [comment]
I also thought they would be accessible to the user but they don't seem to be?

**Comment by sjrc6** [comment]
Ah wait I guess they are but they don't autofill in F1, I'll fix it.

**Comment by fokkonaut** [comment]
Make sure the server cant change client settings through the map settings.

**Comment by heinrich5991** [comment]
Thanks!

**Pull request merged**
