### PR TITLE
Update French flag (fixes #4738)

### LINKED ISSUE #4738: French flag.
Hello, as the french president changed the color of the french flag, why not change it ingame for the next update? the blue is darker on the new one. Here is a preview :

FR

Thanks in advance.

Nouaa.

### PR DESCRIPTION
**Pull request by def-**
by Nouaa

Blue color was changed recently

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
ddnet-libs is unintended?

**Comment by def-** [comment]
Yes

**Comment by Chairn** [comment]
Technically, it's only the presidential palace flag that changed colour, not the official french flag which is the same since 1852 (according to wikipedia)

**Comment by def-** [comment]
@Chairn so you disagree with the color change?

**Comment by Jupeyy** [comment]
I guess he means that the flag was just changed (back) to what was used since 1853

bors r+

**Comment by Chairn** [comment]
I mean that the official flag hasn't changed, its just one that is used for some protocols stuff at the presidential palace.

**Pull request merged**
