### PR TITLE
Enable swapping in team 0

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by murpii** [comment]
did you change your mind? :D

**Comment by murpii** [comment]
Ah nevermind, heinrich had concerns regarding swap in team 0.

#3801

**Comment by def-** [comment]
Oh well, forgot the discussion. Not sure, people use /timeout instead, so it's still possible, but slightly more complicated.

**Comment by edg-l** [comment]
If a player is near the end, and you start and swap you can get 0.02 ranks easily.

**Comment by def-** [comment]
Opinions? We could also enable it cross-team: https://forum.ddnet.tw/viewtopic.php?f=118&t=7352

**Comment by heinrich5991** [comment]
Still against.

If this would be merged, cross-team would be okay in principle. But cross-team swapping would definitely contain new bugs, so it would have to be audited for that first.

@murpii @Learath2 @edg-l What do you think about enabling this PR?

**Comment by murpii** [comment]
I missed the initial discussion on discord unfortunately and it's been awhile since last time I thought about this thoroughly. I can't give you an opinion, sorry heinrich. I agree with your concern written in #3801.

**Comment by edg-l** [comment]
I'm fine with merging this.

**Comment by heinrich5991** [comment]
Most people are in favor, this means that we should go ahead with this. Could you rebase? @def-

**Pull request merged**
