### PR TITLE
Add sv_sql_bindaddr (fixes #5830)

### LINKED ISSUE #5830: bindaddr for mysql connections?
We need one IP the game server should be reachable on, but another for the mysql connection. I think this is not possible currently, with just `bindaddr`. Something like `sql_bindaddr` would be required. I'll check how to implement this

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Weird, I'm getting this error now with bindaddr for curl:
```
[2022-09-13 19:52:52][register]: unknown protocol '1'
[2022-09-13 19:52:52][http]: https://master1.ddnet.org/ddnet/15/register failed. libcurl error:
[2022-09-13 19:52:52][register/6/ipv6]: error response from master
```

**Review by heinrich5991 — APPROVED** [review]
LGTM. What about you, @Zwelf?

**Review by Zwelf — APPROVED** [review]
LGTM as well, all clean :)

**Pull request merged**
