### PR TITLE
Clang 11

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
If there is no way to get clang-format 10+11 green at once, this will be very annoying.

**Comment by heinrich5991** [comment]
I guess we'll wait for Ubuntu to upgrade to clang-format 11?

**Comment by def-** [comment]
But there will always be distributions with different clang-format versions. It's a bit of an annoying way to work, I wish there was a better compatibility/consistency built into clang-format.

**Comment by heinrich5991** [comment]
I'm honestly not sure what to do about that. On Arch, there's an AUR packet to install old versions of clang-format, on Debian there also seem to be packages for old clang-format executables.

**Pull request closed without merging**
