### PR TITLE
Use more secure hash function for map downloads 

### LINKED ISSUE #1127: Downloaded maps should have a stronger hash function
Why has no one created an issue yet? :P

### PR DESCRIPTION
**Pull request by heinrich5991**
SHA256 was chosen because it is reasonably standard, the file names
don't explode in length (this rules out SHA512) and it is supported by
basically all versions of OpenSSL (this rules out SHA512/256 and SHA3).

The protocol is changed in a backward compatible way: The supporting
server sends the SHA256 corresponding to the map in the `MAP_DETAILS`
message prior to sending the `MAP_CHANGE` message. The client saves the
SHA256 obtained from the `MAP_DETAILS` message until the next
`MAP_CHANGE` message.

For servers not supporting this protocol, the client falls back to
simply opening maps like in the previous scheme.

Remove the `map_version` tool, it is not being used and would have been
a little bit effort to update.

Use the OpenSSL implementation of SHA256 if it is supported, otherwise
fall back to a public domain one.

Fix #1127.

### CODE REVIEW

**Comment by heinrich5991** [comment]
I followed @def-'s wishes for now and didn't implement a SHA256 cache for servers not supporting the new protocol.

**Comment by heinrich5991** [comment]
Needs testing on Windows due to file system semantics that I'm unsure of.

**Comment by heinrich5991** [comment]
It was tested on Windows by @ChillerDragon and me. :)

**Comment by heinrich5991** [comment]
Addressed comments. Rebased due to merge conflicts.

**Comment by def-** [comment]
Thanks. Instead of rebasing let's just add it and further problems can be addressed later.

**Comment by heinrich5991** [comment]
We should start providing sha256ed maps on maps.ddnet.tw. I should update my map downloader.

> Instead of rebasing let's just add it and further problems can be addressed later.

I ment that I had already rebased it due to merge conflicts.

**Comment by def-** [comment]
maps.ddnet.tw is done already ;) Please update your map downloader. I used hardlinking.

**Comment by heinrich5991** [comment]
Something is wrong there:
```
#MegaRosenkohl_50c7e9ad.map
#MegaRosenkohl_50c7e9ad_50c7e9ad_56c8c8d17f52d1afef22ebfb2763d70eae200f605d5927cb797b0cdc5f0991f5.map
#MegaRosenkohl_50c7e9ad_56c8c8d17f52d1afef22ebfb2763d70eae200f605d5927cb797b0cdc5f0991f5.map
```

Some (most?) of the maps have a version with the CRC duplicated in the name.

**Comment by def-** [comment]
My bad, wil lfix.

**Comment by heinrich5991** [comment]
Good now!

**Pull request merged**
