### PR TITLE
Remove Nameless Score Setting

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Was there anything specific that triggered this?

**Comment by fokkonaut** [comment]
I have no idea, just sounds stupid to give nameless tee no permission to get ranks.

**Comment by ChillerDragon** [comment]
@fokkonaut nameless tee is used by so many different players that in some cases this name climbs to the first place of the ranks and players who actually play alone on their name have no chance to beat the collective power.

**Comment by fokkonaut** [comment]
I have never seen a nameless tee being on first rank. Also, if this is the only reason we would need a setting for brainless tee and haxxless tee aswell. But since this is deactivated on DDNet anyways, we can juez remove it.

**Comment by Learath2** [comment]
We'll keep this atleast for compatibility.

**Pull request closed without merging**
