### PR TITLE
Fix input issue when VSync enabled

### PR DESCRIPTION
**Pull request by CytraL**
When i play with vsync i can't change weapons fast using middle mouse wheel... with this fix, i can.

### CODE REVIEW

**Comment by CytraL** [comment]
Oops! ugly

**Comment by def-** [comment]
That's not the right solution. I have a feeling this might have been introduced by my introduction of CInput::NextFrame(). Could you try adding a call to Input()->Update() right after Input()->NextFrame() is called in client.cpp? Also, could I have your settings_ddnet.cfg? Maybe that helps with reproducing.

**Comment by CytraL** [comment]
Hi! if i add 'Input()->Update()' after 'Input()->NextFrame()' all works wrong with and without VSync... :/

Config
```
cl_predict 1
cl_antiping_limit 0
cl_antiping 0
cl_antiping_players 1
cl_antiping_grenade 1
cl_antiping_weapons 1
cl_nameplates 1
cl_nameplates_always 1
cl_nameplates_teamcolors 1
cl_nameplates_size 50
cl_nameplates_clan 0
cl_nameplates_clan_size 30
cl_text_entities 1
cl_autoswitch_weapons 1
cl_autoswitch_weapons_out_of_ammo 0
cl_showhud 1
cl_showhud_healthammo 1
cl_showhud_score 1
cl_showrecord 0
cl_showchat 1
cl_show_chat_friends 0
cl_showkillmessages 1
cl_show_votes_after_voting 0
cl_show_local_time_always 0
cl_showfps 1
cl_showpred 0
cl_eye_wheel 1
cl_eye_duration 999999
cl_airjumpindicator 1
cl_threadsoundloading 0
cl_warning_teambalance 1
cl_mouse_deadzone 0
cl_mouse_followfactor 0
cl_mouse_max_distance 400
cl_dyncam_max_distance 1000
cl_dyncam_mousesens 0
cl_dyncam_deadzone 300
cl_dyncam_follow_factor 60
ed_zoom_target 0
ed_showkeys 0
cl_show_welcome 0
cl_motd_time 10
cl_ddnet_version_server "version.ddnet.tw"
cl_ddnet_update2_server "update2.ddnet.tw"
cl_ddnet_maps_server "maps.ddnet.tw"
cl_languagefile ""
cl_vanilla_skins_only 0
cl_auto_statboard_screenshot 0
cl_auto_statboard_screenshot_max 10
cl_default_zoom 10
player_use_custom_color 0
player_color_body 65408
player_color_feet 65408
player_skin "default"
ui_page 6
ui_toolbox_page 0
ui_server_address "95.172.92.151:8321"
ui_scale 100
ui_mousesens 100
ui_color_hue 160
ui_color_sat 70
ui_color_lht 175
ui_color_alpha 228
ui_colorize_ping 1
ui_colorize_gametype 1
ui_demo_selected ""
gfx_noclip 0
dummy_name "brainless tee"
dummy_clan ""
dummy_country -1
dummy_use_custom_color 0
dummy_color_body 65408
dummy_color_feet 65408
dummy_skin "default"
cl_dummy_resetonswitch 0
player_name "unsigned char*"
player_clan "8-bits"
player_country -1
logfile ""
cl_cpu_throttle 0
cl_cpu_throttle_inactive 1
cl_editorundo 0
cl_load_country_flags 1
cl_skin_filter_string ""
cl_auto_demo_record 0
cl_auto_demo_max 10
cl_auto_screenshot 0
cl_auto_screenshot_max 10
cl_reset_wanted_weapon_on_death 1
cl_print_broadcasts 1
cl_friends_ignore_clan 0
inp_grab 0
br_filter_string ""
br_exclude_string ""
br_filter_full 0
br_filter_empty 1
br_filter_spectators 0
br_filter_friends 0
br_filter_country 0
br_filter_country_index -1
br_filter_pw 0
br_filter_ping 999
br_filter_gametype "ddrac"
br_filter_gametype_strict 0
br_filter_serveraddress ""
br_filter_pure 0
br_filter_pure_map 0
br_filter_compatversion 1
br_filter_exclude_countries ""
br_filter_exclude_types ""
br_sort 4
br_sort_order 1
br_max_requests 25
br_demo_sort 0
br_demo_sort_order 0
snd_buffer_size 512
snd_rate 48000
snd_enable 1
snd_enable_music 0
snd_volume 26
snd_device -1
snd_ambient_volume 70
snd_nonactive_mute 0
snd_game 1
snd_gun 1
snd_chat 1
snd_team_chat 1
snd_servermessage 1
snd_highlight 1
gfx_screen 0
gfx_screen_width 1680
gfx_screen_height 1050
gfx_borderless 0
gfx_fullscreen 0
gfx_alphabits 0
gfx_color_depth 24
gfx_vsync 1
gfx_resizable 1
gfx_display_all_modes 0
gfx_texture_compression 0
gfx_high_detail 1
gfx_texture_quality 1
gfx_fsaa_samples 0
gfx_refresh_rate 0
gfx_finish 1
gfx_backgroundrender 1
gfx_text_overlay 10
gfx_asyncrender_old 1
gfx_tune_overlay 20
gfx_quad_as_triangle 1
gfx_highdpi 0
inp_mousesens 100
inp_mouseold 0
inp_ignored_modifiers 0
cl_race_binds 1
cl_race_binds_set 1
cl_reconnect_timeout 120
cl_reconnect_full 1
cl_message_system_hue 42
cl_message_system_sat 255
cl_message_system_lht 192
cl_message_highlight_hue 0
cl_message_highlight_sat 255
cl_message_highlight_lht 192
cl_message_team_hue 85
cl_message_team_sat 255
cl_message_team_lht 212
cl_message_hue 0
cl_message_sat 0
cl_message_lht 255
cl_laser_inner_hue 170
cl_laser_inner_sat 255
cl_laser_inner_lht 191
cl_laser_outline_hue 170
cl_laser_outline_sat 137
cl_laser_outline_lht 41
conn_timeout 100
conn_timeout_protection 1000
cl_show_ids 0
cl_scoreboard_on_death 1
cl_auto_race_record 1
cl_demo_name 1
cl_demo_assume_race 1
cl_race_ghost 1
cl_race_show_ghost 1
cl_race_save_ghost 1
cl_ddrace_scoreboard 1
cl_show_decisecs 1
cl_show_others 0
cl_show_others_alpha 40
cl_show_quads 1
cl_zoom_background_layers 0
cl_background_hue 0
cl_background_sat 0
cl_background_lht 128
cl_background_entities_hue 0
cl_background_entities_sat 0
cl_background_entities_lht 128
cl_background_entities ""
cl_background_show_tiles_layers 0
cl_unpredicted_shadow 0
cl_predict_ddrace 1
cl_show_ninja 1
cl_show_other_hook_coll 1
cl_chat_teamcolors 0
cl_chat_reset 1
cl_show_direction 0
cl_http_map_download 1
cl_old_gun_position 0
cl_confirm_disconnect 0
cl_timeout_code "GoOcGYvdkzrjZRwt"
cl_dummy_timeout_code "KwTKcEeVNIFfFNvF"
cl_input_fifo ""
cl_show_console 0
inp_joystick 0
cl_config_version 1
cl_demo_slice_begin -1
cl_demo_slice_end -1
cl_demo_show_speed 0
unbindall
bind tab "+scoreboard"
bind space "+jump"
bind 0 "kill"
bind 1 "+weapon1"
bind 2 "+weapon2"
bind 3 "+weapon3"
bind 4 "+weapon4"
bind 5 "+weapon5"
bind a "+left"
bind d "+right"
bind e "say /pause"
bind g "drop"
bind k "minimize"
bind q "+showhookcoll"
bind r "fgpaint"
bind t "chat all"
bind u "+show_chat"
bind y "chat team"
bind f1 "toggle_local_console"
bind f2 "toggle_remote_console"
bind f3 "vote yes"
bind f4 "vote no"
bind f10 "screenshot"
bind right "spectate_next"
bind left "spectate_previous"
bind lshift "+emote"
bind rshift "+spectate"
bind mouse1 "+fire"
bind mouse2 "+hook"
bind mousewheelup "+prevweapon"
bind mousewheeldown "+nextweapon"
```

Cheers!

**Comment by CytraL** [comment]
Linux x86_64 version

**Comment by def-** [comment]
Can't reproduce, hm.

**Comment by CytraL** [comment]
On my notebook happens the same.. but appears to be a performance issue because without vsync weapon change not work very fast... (but in notebook i use a bluetooth mouse.. idk if can cause lag..).

Linux x86_64
Debian 8.4

**Comment by timakro** [comment]
I also have problems with my mousewheel and it seems related to vsync but sometimes it just doesn't switch weapon at all.

**Comment by CytraL** [comment]
ummm what print your server when run:
"locale -a"
??

**Comment by CytraL** [comment]
I see that if i enable "cl_cpu_throttle" all works fine.. that do the same.. "wait" xDD.

**Comment by FallenKN** [comment]
I was able to reproduce this aswell, Teeworlds thought that mousewheelup is mouse4 and mousewheeldown is mouse5.. if this can help

**Comment by def-** [comment]
Guys, can you test if you have the same issue with the current Teeworlds master branch (0.7, SDL2)? You can build it with `bam` and the binary is in `build/x86_64/debug/teeworlds`.

**Comment by CytraL** [comment]
No, in TW 0.7 appears to works fine... with VSync and without 'cl_cpu_throttle'

**Comment by def-** [comment]
So it's a bug I added! You could check the difference of what TW 0.7 does, or alternatively bisect the ddnet master branch.

**Pull request closed without merging**
