### PR TITLE
Fix new chat visuals!

### PR DESCRIPTION
**Pull request by Banana090**
fixed:
Screenshot_6

@Jupeyy 
unknown (1)

People complain about new chat style for a reason. What did you do!? Fix it. Now.

### CODE REVIEW

**Comment by Banana090** [comment]
Sorry for over 99999 commits in this xD
the changes are 2 lines only. Fixes margin and background rounding

**Comment by def-** [comment]
> Fix it. Now.

This is not the proper way to talk to others.

**Comment by Jupeyy** [comment]
btw, i personally think it looks stranger with more rounding, see single line chat and directly under it the multiline chat

**Comment by Banana090** [comment]
@Jupeyy yeah, the multiline looks a little weird, because it's different. It's ok for me, but we can also try to split multiline messages on several backgrounds to keep background pattern the same

**Comment by Banana090** [comment]
@Jupeyy btw what's wrong with tee icons now? The margin was different before. Bottommost pixel of feet was always on the same height as first character's pixel, but now it's a little lower

**Comment by Jupeyy** [comment]
ofc, you made the tee size 8, while the chat is size 6..

So the tee was going into the next chat

see:
https://cdn.discordapp.com/attachments/420565311863914496/766331993570279424/screenshot-20201015180619.png

the llllllllll guy for example with the bunny skin

**Comment by Banana090** [comment]
> > Fix it. Now.
> 
> This is not the proper way to talk to others.

I thought you released this chat in public version now and was in panic

**Comment by Banana090** [comment]
@Jupeyy 
Screenshot_7

I see nothing wrong here at all. The bunnies ears being high is ok.

**Comment by Jupeyy** [comment]
c'mon stop trolling:

image

**Comment by Banana090** [comment]
The best way to do it is by aligning tee with text by bottom. Turns out I had problems with tee alignment too.
But I'm not really complaining about tees, just mentioning

**Comment by Jupeyy** [comment]
Anyway, i've absolutly no problem with changing the margins to whatever ppl like, the only thing i wanted to fix the chat commit was, bcs i didnt want to waste performance for the GL 3.3 impl, and i didnt want undefined behaviour for the skin stuff.
Idc about the visuals, i don't think mine looks good, but also don't think it looks worse than adding more roundings :D
So i stay out of this discussion

**Comment by Banana090** [comment]
You've nicely fixed all the code stuff with render and skin loading, thank you a lot for that, you're the best. But yeah, configs should be tweaked :3

**Comment by Jupeyy** [comment]
I can understand the sense of you last commit, but i think you should do it by substracting the linewidth when creating the chat text, using the current max line width from the cursor, instead of changing random values.

Also please rewrite your commit history, or use a clean master and just add these 2 things there

**Comment by b3z** [comment]
Just a thought:

Maybe you could try to have the round corners only on the outer edges of the chat box. Between chat messages you could use negative roundings or so? Understand what I mean?
Also on the left it would be one straight line down. Might look not too bad and be worth a try. Maybe with a little smaller corner radius.

**Comment by Banana090** [comment]
@b3z I've thought about that when first implementing this visuals, but there is no such option as "negative rounding", so it will be very hard to make

**Comment by b3z** [comment]
> @b3z [...] it will be very hard to make.

Well that's a pitty.

> But that will look great, yes

So you know what we should do. Even if it is hard.

I might look into it as well. But I have never done anything with cpp so it might take a while...

**Comment by Learath2** [comment]
"Negative" rounding would imply drawing outside the rect so it's not quite a sane concept. Maybe 0 rounding when there is a longer message following it?

Though I don't think we should cause more re renders just because it looks a tad better.

**Pull request closed without merging**
