### PR TITLE
Only announce servers using Steam/Discord integration which are registered

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
It's weird a weird to look for a sentinel value to decide whether to add an address or not. Perhaps you could add a boolean instead that says whether to broadcast the address?

**Comment by def-** [comment]
Add the boolean where?

**Comment by heinrich5991** [comment]
`SetGameInfo` parameter.

**Comment by def-** [comment]
Done

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
