### PR TITLE
Menu tabs animations

### PR DESCRIPTION
**Pull request by Banana090**
Cool menu tabs animations, please merge

### CODE REVIEW

**Comment by def-** [comment]
On top it increases in size only in one dimension, on right side in 3 dimensions. intentional?

**Comment by Banana090** [comment]
yes

**Comment by def-** [comment]
It looks a bit inconsistent. I'm not sure if the community will like this change. Maybe another candidate for a vote? Could someone create a GIF that shows the animation? Then I'd do a vote on Discord

**Comment by def-** [comment]
Done.

**Comment by def-** [comment]
Vote won 39 - 6. Clear enough to submit. Code looks clean.
bors r+

**Comment by def-** [comment]
There were some change requests in https://github.com/ddnet/ddnet/pull/3193 Could you please fix them in a new PR?

**Pull request merged**
