### PR TITLE
Use dynamically allocated memory for the CacheChunk

### LINKED ISSUE #4785: double free or corruption (!prev)
```
Core was generated by `./DDRace64-Server_sql -f servers/8311.cfg'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6657d22b80 (LWP 2466233))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6657dfe537 in __GI_abort () at abort.c:79
#2  0x00007f6657e57768 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f6657f65e2d "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007f6657e5ea5a in malloc_printerr (str=str@entry=0x7f6657f68230 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007f6657e6009c in _int_free (av=0x7f6657f97b80 <main_arena>, p=0x55b8dc283610, have_lock=<optimized out>) at malloc.c:4317
#5  0x000055b8db80f151 in __gnu_cxx::new_allocator<std::_List_node<CServer::CCache::CCacheChunk> >::deallocate (__t=1, __p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/ext/new_allocator.h:120
#6  std::allocator_traits<std::allocator<std::_List_node<CServer::CCache::CCacheChunk> > >::deallocate (__n=1, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:492
#7  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_put_node (__p=<optimized out>, this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:446
#8  std::__cxx11::_List_base<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::_M_clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/list.tcc:81
#9  std::__cxx11::list<CServer::CCache::CCacheChunk, std::allocator<CServer::CCache::CCacheChunk> >::clear (this=0x7f6657d0b4d8) at /usr/include/c++/10/bits/stl_list.h:1500
#10 CServer::CCache::Clear (this=0x7f6657d0b4d8) at /home/teeworlds/src/master/src/engine/server/server.cpp:1811
#11 CServer::CacheServerInfoSixup (this=this@entry=0x7f6656f81010, pCache=pCache@entry=0x7f6657d0b4d8, SendClients=SendClients@entry=true) at /home/teeworlds/src/master/src/engine/server/server.cpp:2012
#12 0x000055b8db80f826 in CServer::UpdateServerInfo (this=this@entry=0x7f6656f81010, Resend=Resend@entry=false) at /home/teeworlds/src/master/src/engine/server/server.cpp:2156
#13 0x000055b8db81365d in CServer::UpdateServerInfo (Resend=false, this=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2148
#14 CServer::Run (this=this@entry=0x7f6656f81010) at /home/teeworlds/src/master/src/engine/server/server.cpp:2679
#15 0x000055b8db7fe5fd in main (argc=<optimized out>, argv=<optimized out>) at /home/teeworlds/src/master/src/engine/server/server.cpp:3732
```
happened on official server. @Learath2 UpdateServerInfo sounds like something you added a while ago, any idea?

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #4785 @ChillerDragon test pls, bcs i cannot reprod

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
#include <vector>

**Comment by ChillerDragon** [comment]
@def-

**Comment by Jupeyy** [comment]
xDDD trollestdragon

**Pull request merged**
