### PR TITLE
Overload GetCharacter with const version

### PR DESCRIPTION
**Pull request by ChillerDragon**
Allows to write this
```C++
for(const CPlayer *pPlayer : GameServer()->m_apPlayers)
{
	if(!pPlayer)
		continue;
	if(!pPlayer->GetCharacter())
		continue;

	// your code that does not change the character state
}
```

### CODE REVIEW

**Review by Robyt3 — CHANGES_REQUESTED** [review]
The non-`const` version seems unnecessary.

**Comment by ChillerDragon** [comment]
Woah indeed! Seems like I did not fully understood the const annotation yet. I assumed that the returned pointer can not be used to change state or something.

**Comment by Jupeyy** [comment]
i guess @heinrich5991 wants to review this?

i guess he doesn't like the promotion of immutability to mutable

a.k.a. it works cause the pointer can be cast to basically anything

**Comment by heinrich5991** [comment]
> i guess he doesn't like the promotion of immutability to mutable

Yeah.

> Btw an overload doesn't seem worth to upstream, if it's dead code

Seems like it could get some usage in the future though. Other methods probably haven't been annotated with `const` due to this annotation missing.

@Robyt3 What do you think? I'd prefer not to go from `const` to non-`const`, it doesn't really match intent IMO.

**Comment by Robyt3** [comment]
> @Robyt3 What do you think? I'd prefer not to go from `const` to non-`const`, it doesn't really match intent IMO.

Yeah, we could add a `const` overload that returns a `const CCharacter *` so it's clearer in this case.

We could also start using clang-tidy with `readability-make-member-function-const` in the future, but this will lead to some cases where clang-tidy wants us to add `const` where it feels wrong, like here, which we either have to accept or mark as NOLINT:

https://github.com/ddnet/ddnet/blob/4e272996573435ba02987aa4f61d93938f83329e/src/game/client/prediction/gameworld.cpp#L702-L706

**Comment by heinrich5991** [comment]
Status: Unaddressed review comment.

**Review by heinrich5991 — APPROVED** [review]
Thanks.

**Pull request merged**
