### PR TITLE
update readme on building with MSVC on windows

### PR DESCRIPTION
**Pull request by BlaiZephyr**
This PR updates the DDNet build instructions to properly describe basic build instructions for all IDEs, not just Visual Studio using MSVC, aswell as hand-holding when using visual studio code to get started.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by MilkeeyCat** [comment]
Windows detected, opinion rejected

**Comment by furo321** [comment]
Sentences should start with a capital letter.

**Comment by BlaiZephyr** [comment]
> Sentences should start with a capital letter.

Fixed, thanks for pointing it Out

**Comment by heinrich5991** [comment]
Why did this remove building with Microsoft Visual Studio? That should be preferred IMO, but at the very least not removed from the README.

**Comment by BlaiZephyr** [comment]
While Visual Studio is a good tool, I personally find it overwhelming and not very intuitive for beginners. i also find it very bloated. There are other great IDEs like Visual Studio Code or the JetBrains products that are pretty lightweight and many users are already familiar with. I'm open to revisiting the old description, but I personally prefer the idea of letting users choose what environment they want to work at. - maybe add it below? even tho that might bloat up the README too much.

**Comment by BlaiZephyr** [comment]
so i either dump the explanation to use vsc and rewrite it for visual studio 2022, or i place the old one (also updated) below - what would you prefer @heinrich5991 ?

**Comment by heinrich5991** [comment]
I'd prefer to place the old one above, and then expanding for arbitrary other editors below. That section is for people who don't need as much hand holding.

**Pull request merged**
