### PR TITLE
rescue on freeze/dfreeze (supersedes #3335)

### PR DESCRIPTION
**Pull request by def-**
Fixed all the merges and clang-format (hopefully)

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Was this tested in conjunction with one-tick unfreezes? Does this change where perma-frozen dummies get /r-ed to? E.g. to the start of the map in dummy maps instead of the last part?

**Comment by heinrich5991** [comment]
@gerdoe-jr ^

**Comment by gerdoe-jr** [comment]
Tested it doing my best. Hadn't expected something curious/non-standard.

**Comment by heinrich5991** [comment]
> Does this change where perma-frozen dummies get /r-ed to?

Remaining question.

**Comment by gerdoe-jr** [comment]
> > Does this change where perma-frozen dummies get /r-ed to?
> 
> Remaining question.

Sorry for late response, no, it doesn't change any positions or whatever else. I tested it in all ways and didn't find any bug, but I would be glad if someone else will check it. Rescue's behaviour is fine actually and I want to know that one more person agree with this.

**Comment by heinrich5991** [comment]
I think I'm fine with testing this. :)

bors r+

**Comment by murpii** [comment]
Bug reported by reo on discord: https://discord.com/channels/252358080522747904/342454474117218334/803506066116575232


https://user-images.githubusercontent.com/60477660/105812448-7bbf1280-5fae-11eb-81b1-45a7cfff533c.mp4

https://user-images.githubusercontent.com/60477660/105812469-85487a80-5fae-11eb-8e8f-e82071191d3b.mp4

**Comment by def-** [comment]
@murpii Can you make a new issue for this? Otherwise too easy to get lost here, since this PR is closed.

**Comment by def-** [comment]
Oh, this is actually newly merged, disregard my comment then. @gerdoe-jr any idea about this?

**Pull request merged**
