### PR TITLE
Tell MSVC that main is still entry

### PR DESCRIPTION
**Pull request by Jupeyy**
Need to wait for the artifacts to test, if this works, dont have VS currently

I wonder why VS doesnt output an error that WinMain isnt found :D

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Seems to work again

**Comment by heinrich5991** [comment]
Can you explain where you found this magic incantation? Is there a different way to fix this, maybe renaming our main() function to WinMain()?

**Comment by Jupeyy** [comment]
https://docs.microsoft.com/de-de/cpp/build/reference/entry-entry-point-symbol?view=msvc-160

WinMain has the disadvantage that it has a different style with the command args etc.
This is easier for compability.
There is no real difference between main and WinMain, you can get all info from both, but this is just the C style.

**Comment by heinrich5991** [comment]
I guess it works.

bors r+

Thanks for looking into this.

**Pull request merged**
