### PR TITLE
Use str_length

### PR DESCRIPTION
**Pull request by ChillerDragon**
Either we should delete str_length or we should use it. Feel free to downvote this pr if u think delete is the way to go.

### CODE REVIEW

**Comment by Learath2** [comment]
I agree, we should commit to the not using libc outside of system.c

**Comment by Jupeyy** [comment]
I prefer using more libc or std c++ instead of all these system hacks, thats what a standard is for

**Comment by Learath2** [comment]
> I prefer using more libc or std c++ instead of all these system hacks, thats what a standard is for

Not likely we'll get a rewrite any time soon, so might aswell be consistent.

**Pull request merged**
