### PR TITLE
Allow sv_show_others_default in map settings

### PR DESCRIPTION
**Pull request by def-**
for tutorial map

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Alternative: We could put the config into <mapname>.map.cfg. Downside: It wouldn't be consistent across servers. Maybe better the way you pull-requested?

**Comment by heinrich5991** [comment]
Tutorial has shipped already. Is this still relevant or have we found another solution?

**Comment by def-** [comment]
Still relevant, would like to set this for the shipped version.

**Pull request merged**
