### PR TITLE
Editor: keyboard support for fonts

### PR DESCRIPTION
**Pull request by ChillerDragon**
Press T to enter text mode and place font letters
based on keyboard presses

Support custom number and letter offsets using json files.
[self made cursor.svg](https://github.com/ddnet/ddnet/files/5928816/cursor.zip) (CC0 or whatever u need)

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

https://user-images.githubusercontent.com/20344300/106961168-83648100-673d-11eb-9526-a4703a8a19e9.mp4

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Something I noticed while mapping is that my big cucumber fingers sometimes smash T when I try to rotate with R. Maybe text mode should only work for mapres that have a metadata json and thus false positive presses for game layer or other mapres would be removed.

**Comment by Learath2** [comment]
Where would we look for the metadata json?

**Comment by ChillerDragon** [comment]
> Where would we look for the metadata json?

Next to the mapres with same name but json ending instead of png

https://github.com/ddnet/ddnet/pull/3602/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1136

**Comment by heinrich5991** [comment]
Hm. I'd prefer to have this without the configuration, instead moving the texts to a standard location.

**Comment by ChillerDragon** [comment]
> Hm. I'd prefer to have this without the configuration, instead moving the texts to a standard location.

Sure the standard location will be used if not specified otherwise. But changing ddnet_tiles.png probably causes some trouble. And there are plenty of custom fonts they barley have common offsets. I think for most users it is easier to edit a json file than editing a png file.

**Comment by heinrich5991** [comment]
I don't like having to ship an auxiliary file with tilesets. This can get lost, be different across tileset versions, etc.

Idk, write some JS single page app that fixes the tilesets so everyone can do it.

**Comment by heinrich5991** [comment]
This is an interesting feature, however as-is, I don't want to merge it. Having to ship another config file with each font tileset is too much IMO.

Possible ways forward:
- Implement a small HTML page that can shift the tiles around so they fit the typewriter in a standard location.
- Implement a client feature that can shift the tileset around so they fit the layout.
- Just drop the shift feature and instead leave it to the users to produce the tileset in the right place.

**Comment by heinrich5991** [comment]
As said, I don't like the auxiliary config file.

**Comment by ChillerDragon** [comment]
I was told it has performance issues on windows anyways. And I keep activating it accidentally in my fork. No hard feelings about this feature since it was a wish from Im' corneum. Anyways shameless plug here for users finding this and wanting to try it out its implemented in [chillerbot-ux](chillerbot.github.io/)

**Comment by ChillerDragon** [comment]
> As said, I don't like the auxiliary config file.

Its been a few years @heinrich5991. Any chance you like the auxiliary file now? The suggestions you made have too bad of a user experience. As a user I just want to start typing letters. Before I use a image editor to change a mapres I just manually place all the letters. What is your problem with the auxiliary config file?

The only way that is smooth is if the client already knows the offsets without the user having to edit anything. The standard ddnet client would include configs for all mapres that can be typed. And if a power user wants it also for additional mapres they can manually create the config file. Or I also had the idea instead of manually creating the file the editor could ask the user to click on the letter "a" and the number "1" and the client could auto generate the config.

**Comment by heinrich5991** [comment]
Honestly, I'm not sure about the necessity of this feature at all, it seems niche.

If it were to be added, I'm still against the auxiliary file. I gave alternatives that don't seem to be such a bad user experience, like creating a small web page where you can re-order the tiles.

**Comment by ChillerDragon** [comment]
> If it were to be added, I'm still against the auxiliary file. I gave alternatives that don't seem to be such a bad user experience, like creating a small web page where you can re-order the tiles.

As I said it is bad. I as a user would never close my client and visit a web page to type out one sentence in the editor. If it does not work out of the box its not worth the effort. If it does work out of the box it is a neat feature.

**Comment by ChillerDragon** [comment]
> I'm still against the auxiliary file

why?

**Pull request closed without merging**
