### PR TITLE
Allow choosing game layer entities for different gametypes, closes #1283

### LINKED ISSUE #1283: Mapping for different gametypes
make it easier: create a button like the Modifier but for Gametypes so you can access every entities from editor/entities_clear too.

### PR DESCRIPTION
**Pull request by timakro**
image

Implements #1283

### CODE REVIEW

**Comment by 12pm** [comment]
You should ship entities made for the editor instead of relying on those for in-game overlay. They can be confused with design. The file for vanilla is obviously already there and the other ones you can probably convert easily based on the ddnet one :D

**Comment by bojidar-bg** [comment]
Would be cool if it would autodetect available entities files instead of hardcoding them.

**Comment by bojidar-bg** [comment]
Looks good to me.

**Comment by def-** [comment]
Let's merge it for now, can be improved later if something is wrong. Thanks for the change.

**Pull request merged**
