### PR TITLE
Tees must be teamed up before loading

### PR DESCRIPTION
**Pull request by Learath2**
Compiles but couldn't test this as I have no desire to spend the rest of my year trying to setup a MySQL ddnet server :P Fixed some styling issues while at it.

Obsoletes #720

### CODE REVIEW

**Comment by def-** [comment]
So someone can just join the team quickly and load them into a wrong save.

**Comment by Learath2** [comment]
Hmm I don't see how that could happen. I check that the correct amount and the correct players are present in the team. Can you elaborate?

**Comment by def-** [comment]
Ok, so someone can just join the team and prevent them from ever loading.

**Comment by Learath2** [comment]
Well one could lock up the team and invite one by one, or the code could invite one by one which might be cute but then I'd need to track the state of the team and force the lock :/ 

I guess the proper approach would be to remove people who don't belong if all the saved tees are present.

**Comment by Learath2** [comment]
Implemented the last one.

**Comment by heinrich5991** [comment]
Now

>So someone can just join the team quickly and load them into a wrong save.

works again. Let me try to implement my solution. ^^

**Comment by Learath2** [comment]
Can we just decide on one first and work on that?

**Pull request merged**
