### PR TITLE
Add pause time

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
That seems strange to me. So someone can just drag you through the map and you get a 0 second time?

**Comment by Banana090** [comment]
Already broken

**Comment by fokkonaut** [comment]
> That seems strange to me. So someone can just drag you through the map and you get a 0 second time?

Someone asked why times are not paused in solo servers when using /pause.
Then I tried just something, I dont care if it gets added or not, but it works only on solo servers and it resumes you from pause if you have moved to avoid pausing time and being dragged through the map. So you can basically really only pause if you dont move.

**Comment by def-** [comment]
So on solo server I can pause while falling down and save time? This sounds bad.

**Comment by fokkonaut** [comment]
Please read correctly.
> So you can basically really only pause if you dont move.

**Comment by plsplsplslol** [comment]
too many problems that would require too many cases to fix

- waiting for grenade/shotgun/laser or telegun
- waiting for moving entities like hearts/bullets

**Pull request closed without merging**
