### PR TITLE
Don't refresh, if a job is already running

### LINKED ISSUE #3856: 15.5rc1 browser refresh button can be spammed to fill up the job queue
In case of impatience and master is responding slowly, it might create more unnecessary load on the master. Plus, it makes the list seemingly slow for no reason if user don't know how it works since the list only updates after the last http request is done.

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #3856

@heinrich5991 can you check if this is ok, then we can also add it to the release

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
e.g. in worst case it might not queue a new event on tab switching if the current job was too slow, but probably still better than spamming the job queue while holding down F5 key

**Comment by def-** [comment]
If a job gets stuck totally it would run into a timeout?

**Comment by Jupeyy** [comment]
So set a timeout for the job? I'd assume curl just retires to fetch the list so a new queued job wouldn't really help
Or do you mean stuck in some other way?

**Comment by def-** [comment]
I'm wondering if we do have a timeout. I can imagine a server malfunctioning and just not closing its http connection forever.

**Comment by Jupeyy** [comment]
I am really not a http master, but curl seems to use TCP keep alive with a timeout of 60seconds([here](https://everything.curl.dev/usingcurl/timeouts#keep-connections-alive)), so if the server somehow resets the connection without telling the client it will probably reject the packet, as soon as the port is listening again (or the router whatever just resets the TCP connection). Or is that not happeneng in real world, would be interesting to know.

**Comment by def-** [comment]
We currently use no timeout:
```
m_pEngine->AddJob(m_pGetServers = std::make_shared<CGet>(pBestUrl, CTimeout{0, 0, 0}));
```
So an evil server could just keep the TCP connection open and not send any further data, thus blocking the server list entirely. I'll push another change to add a timeout.

bors r+

**Comment by def-** [comment]
bors r-
Let's wait for heinrich's review.

**Comment by Jupeyy** [comment]
Maybe its too edge case, the manual even states to just use CURLOPT_LOW_SPEED_TIME
Would need to know if curl's progress function considers bad packages for its connection speed calculation, else it probably is handled there anyway

**Comment by heinrich5991** [comment]
I actually think that a timeout for the whole connection is a bad idea. Timeout for connection establishment and download speed should already cover the whole connection. By adding a timeout for the whole connection, we're setting a maximum filesize that is the users connection speed times that timeout.

I guess I can live with a connection timeout/low connect speed abort for the serverbrowser list download.

**Comment by Jupeyy** [comment]
> I actually think that a timeout for the whole connection is a bad idea. Timeout for connection establishment and download speed should already cover the whole connection. By adding a timeout for the whole connection, we're setting a maximum filesize that is the users connection speed times that timeout.
> 
> I guess I can live with a connection timeout/low connect speed abort for the serverbrowser list download.

Yeah I agree, are the values for the timeout ok,
and is the first commit fine from your side, or prefer a better solution?

**Pull request merged**
