### PR TITLE
Show /spec tees with a dashed skin

### LINKED ISSUE #2080: Feature request: "Visible" players in /spec
As said by **Boci#1337** on discord ([link](https://discordapp.com/channels/252358080522747904/293493549758939136/685965489037639720)):
> i have a great idea
> when someone goes spec, you would see his ghost, of where he went spec
> like if he were in freeze, but like 40% opacity

6 other people, including me, seem to like the idea, so there is graphical representation of possible solution by using new skin, let's say `x_spec`

| Skin |
| :---: |
| x_spec |

| In-game preview compared to regular skin |
| :---: |
| unknown |

-----

For whoever wants to test how the mentioned skin looks in-game:
[x_spec.zip](https://github.com/ddnet/ddnet/files/4303527/x_spec.zip)
###### _Note: You have to remove the `x_` part from the skin name to see it in client settings_

### PR DESCRIPTION
**Pull request by edg-l**
Adds the option `cl_show_spec_tee`

image

Don't merge until @Ekidoxx confirms it:
>  Wait a bit before merging the visible-spec, I will play around more with the skin. I.e. whiteish border around that black fill of dashed skin, like the nicks are displayed. Or the other way around - since deep is black due to ninja, maybe spec should use white dashed skin

Fixes https://github.com/ddnet/ddnet/issues/2080

### CODE REVIEW

**Comment by fokkonaut** [comment]
The name should be transparent `cl_show_others_alpha`

**Comment by edg-l** [comment]
image

**Comment by Ekidoxx** [comment]
Maybe not only name, but also the skin should be under same transparency setting?

**Comment by edg-l** [comment]
image

**Comment by def-** [comment]
I like the look

**Comment by Ekidoxx** [comment]
Four possibilities that I ended up with:

1. Black outline
2. White outline that becomes player's custom skin colors
3. Black and semi-transparent white outline
4. Black and white outline

Comparision

---

Personally I'd choose 2 and if it ends up looking bad with more players, then change to 4 in the future

**Comment by edg-l** [comment]
I would stick to 1

**Comment by edg-l** [comment]
[ddnet-windows-latest.zip](https://github.com/ddnet/ddnet/files/4814343/ddnet-windows-latest.zip)

**Comment by edg-l** [comment]
image
image
the skin is now white, and it uses colors

**Comment by def-** [comment]
I like it. Good to go from my side.

**Comment by edg-l** [comment]
Fixed a bug, instead of relying on m_Active it now relies on m_Spec

**Comment by HiRavie** [comment]
I suggest a more minimal approach:
Capture
Show dashed body outline with a faded nickname, it should be visible enough in _most_ cases but not look weird or intrusive, also if the outline isn't visible in very dark areas, the nickname definitely will be.
x_spec

**Comment by VxMiMxV** [comment]
Well personally i hate the dashed tee outline design but if others it like then.. yeah :)

Anyways i think something like this would fit the game better:

Screen 5649

(possibly could be even more transparent, i just played with the overall skin brightness and transparency to give you an idea)

**Comment by def-** [comment]
That would be hard to tell apart from players in other teams.

**Comment by VxMiMxV** [comment]
> That would be hard to tell apart from players in other teams.

Except you know, 
1. They don't have eyes
2. They don't have weapons
3. Their nicknames aren't colored (like they are when in a team)

**Comment by heinrich5991** [comment]
I like this minimal skin posted by @HiRavie. It does not require code changes AFAICT.

**Comment by Ekidoxx** [comment]
Ravie's version is basically just removing the feets, since nickname is already coded to have customizable transparency.
Although then I'd be for one of those (with just removed feets):

> 3. Black and semi-transparent white outline
> 4. Black and white outline

So that not only the nick but also skin will always be visible.

**Comment by Learath2** [comment]
Let's not use showothers transparency for this, I think we should reserve that for tees that are spec in another team.

**Comment by HiRavie** [comment]
Using semi transparent black is enough, seeing exactly where spectating tees are in every possible scenario is not crucial and having them too visible or using more than one color can be more distracting than useful. Also my image has some other subtle differences: the lines are thinner and symmetrical, also it better represents the size of a tee (Soreu's version seems to be slightly smaller)

**Comment by b3z** [comment]
I like the minimalistic approaches. 
Never the less I think the name should be faded because if many tees spec in one spot (normal in gores) it will just be a mess.

And one more question. Why not make it customizable for the player?
Just give the opportunity to load their own (or several different ddnet) spec-skins into the game?

**Comment by def-** [comment]
Alright, let's go with the HiRavie skin. @b3z It's only about the default, of course you could still replace the skin with any other you want.

**Comment by def-** [comment]
Merged manually.

**Pull request merged**
