### PR TITLE
Try to use openssl EVP (partially fixes #5548)

### LINKED ISSUE #5548: Clang Warnings
So many clang warnings lately:
- OpenSSL 3 deprecation warnings
- thread-safety-analysis

<Details>

```
[40/256] Building CXX object CMakeFiles/engine-shared.dir/src/engine/shared/jobs.cpp.o
src/engine/shared/jobs.cpp:113:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/shared/jobs.cpp:110:2: note: mutex acquired here
        }
        ^
src/engine/shared/jobs.cpp:113:1: warning: mutex 'm_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/shared/jobs.cpp:110:2: note: mutex acquired here
        }
        ^
2 warnings generated.
[64/256] Building CXX object CMakeFiles/engine-shared.dir/src/base/hash_openssl.cpp.o
src/base/hash_openssl.cpp:6:2: warning: 'SHA256_Init' is deprecated [-Wdeprecated-declarations]
        SHA256_Init(ctxt);
        ^
/usr/include/openssl/sha.h:73:1: note: 'SHA256_Init' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
src/base/hash_openssl.cpp:11:2: warning: 'SHA256_Update' is deprecated [-Wdeprecated-declarations]
        SHA256_Update(ctxt, data, data_len);
        ^
/usr/include/openssl/sha.h:74:1: note: 'SHA256_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
src/base/hash_openssl.cpp:17:2: warning: 'SHA256_Final' is deprecated [-Wdeprecated-declarations]
        SHA256_Final(result.data, ctxt);
        ^
/usr/include/openssl/sha.h:76:1: note: 'SHA256_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
src/base/hash_openssl.cpp:23:2: warning: 'MD5_Init' is deprecated [-Wdeprecated-declarations]
        MD5_Init(ctxt);
        ^
/usr/include/openssl/md5.h:49:1: note: 'MD5_Init' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Init(MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
src/base/hash_openssl.cpp:28:2: warning: 'MD5_Update' is deprecated [-Wdeprecated-declarations]
        MD5_Update(ctxt, data, data_len);
        ^
/usr/include/openssl/md5.h:50:1: note: 'MD5_Update' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Update(MD5_CTX *c, const void *data, size_t len);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
src/base/hash_openssl.cpp:34:2: warning: 'MD5_Final' is deprecated [-Wdeprecated-declarations]
        MD5_Final(result.data, ctxt);
        ^
/usr/include/openssl/md5.h:51:1: note: 'MD5_Final' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 int MD5_Final(unsigned char *md, MD5_CTX *c);
^
/usr/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
6 warnings generated.
[91/256] Building CXX object CMakeFiles/engine-shared.dir/src/base/system.cpp.o
src/base/system.cpp:665:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/base/system.cpp:664:14: note: mutex acquired here
        return aio->error;
                    ^
src/base/system.cpp:665:1: warning: mutex 'aio->lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/base/system.cpp:664:14: note: mutex acquired here
        return aio->error;
                    ^
src/base/system.cpp:685:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/base/system.cpp:683:2: note: mutex acquired here
        }
        ^
src/base/system.cpp:685:1: warning: mutex 'aio->lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/base/system.cpp:683:2: note: mutex acquired here
        }
        ^
src/base/system.cpp:701:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/base/system.cpp:698:2: note: mutex acquired here
        }
        ^
src/base/system.cpp:701:1: warning: mutex 'aio->lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/base/system.cpp:698:2: note: mutex acquired here
        }
        ^
6 warnings generated.
[135/256] Building CXX object CMakeFiles/DDNet.dir/src/engine/client/serverbrowser_http.cpp.o
src/engine/client/serverbrowser_http.cpp:147:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:147:1: note: mutex acquired here
src/engine/client/serverbrowser_http.cpp:147:1: warning: mutex 'm_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:147:1: note: mutex acquired here
src/engine/client/serverbrowser_http.cpp:171:17: warning: expecting mutex 'ls.m_Lock' to be held at start of each loop [-Wthread-safety-analysis]
        for(int i = 0; i < m_pData->m_NumUrls; i++)
                       ^
src/engine/client/serverbrowser_http.cpp:181:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:171:17: warning: expecting mutex 'ls.m_Lock' to be held at start of each loop [-Wthread-safety-analysis]
        for(int i = 0; i < m_pData->m_NumUrls; i++)
                       ^
src/engine/client/serverbrowser_http.cpp:199:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:171:17: warning: expecting mutex 'm_Lock' to be held at start of each loop [-Wthread-safety-analysis]
        for(int i = 0; i < m_pData->m_NumUrls; i++)
                       ^
src/engine/client/serverbrowser_http.cpp:199:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:171:41: warning: expecting mutex 'ls.m_Lock' to be held at start of each loop [-Wthread-safety-analysis]
        for(int i = 0; i < m_pData->m_NumUrls; i++)
                                               ^
src/engine/client/serverbrowser_http.cpp:199:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:197:15: warning: cannot call function 'CLockScope' while mutex 'm_Lock' is held [-Wthread-safety-analysis]
                        CLockScope ls(m_Lock);
                                   ^
src/engine/client/serverbrowser_http.cpp:197:15: warning: acquiring mutex 'm_Lock' requires negative capability '!m_Lock' [-Wthread-safety-negative]
src/engine/client/serverbrowser_http.cpp:197:15: warning: acquiring mutex 'm_Lock' that is already held [-Wthread-safety-analysis]
src/engine/client/serverbrowser_http.cpp:181:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:247:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:181:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:247:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:199:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:247:1: warning: mutex 'm_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:199:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:247:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:181:3: note: mutex acquired here
                }
                ^
src/engine/client/serverbrowser_http.cpp:247:1: warning: mutex 'm_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/client/serverbrowser_http.cpp:181:3: note: mutex acquired here
                }
                ^
14 warnings generated.
[140/256] Building CXX object CMakeFiles/DDNet.dir/src/engine/client/updater.cpp.o
src/engine/client/updater.cpp:59:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:59:1: note: mutex acquired here
src/engine/client/updater.cpp:59:1: warning: mutex 'm_pUpdater->m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:59:1: note: mutex acquired here
src/engine/client/updater.cpp:117:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:117:1: note: mutex acquired here
src/engine/client/updater.cpp:117:1: warning: mutex 'm_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:117:1: note: mutex acquired here
src/engine/client/updater.cpp:123:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:122:9: note: mutex acquired here
        return m_State;
               ^
src/engine/client/updater.cpp:123:1: warning: mutex 'm_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:122:9: note: mutex acquired here
        return m_State;
               ^
src/engine/client/updater.cpp:129:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:129:1: note: mutex acquired here
src/engine/client/updater.cpp:129:1: warning: mutex 'm_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:129:1: note: mutex acquired here
src/engine/client/updater.cpp:135:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:134:9: note: mutex acquired here
        return m_Percent;
               ^
src/engine/client/updater.cpp:135:1: warning: mutex 'm_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/client/updater.cpp:134:9: note: mutex acquired here
        return m_Percent;
               ^
10 warnings generated.
[150/256] Building CXX object CMakeFiles/DDNet.dir/src/engine/client/video.cpp.o
src/engine/client/video.cpp:452:9: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
        while(!pThreadData->m_Finished)
               ^
src/engine/client/video.cpp:476:5: note: mutex acquired here
                                }
                                ^
src/engine/client/video.cpp:452:9: warning: mutex 'g_WriteLock' is not held on every path through here [-Wthread-safety-analysis]
        while(!pThreadData->m_Finished)
               ^
src/engine/client/video.cpp:476:5: note: mutex acquired here
                                }
                                ^
src/engine/client/video.cpp:534:9: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
        while(!pThreadData->m_Finished)
               ^
src/engine/client/video.cpp:557:5: note: mutex acquired here
                                }
                                ^
src/engine/client/video.cpp:534:9: warning: mutex 'g_WriteLock' is not held on every path through here [-Wthread-safety-analysis]
        while(!pThreadData->m_Finished)
               ^
src/engine/client/video.cpp:557:5: note: mutex acquired here
                                }
                                ^
4 warnings generated.
[222/256] Building CXX object CMakeFiles/DDNet-Server.dir/src/engine/server/register.cpp.o
src/engine/server/register.cpp:322:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:277:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:322:1: warning: mutex 'm_pShared->m_pGlobal->m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:277:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:322:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:316:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:322:1: warning: mutex 'm_pShared->m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:316:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:388:1: warning: mutex 'ls.m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:388:1: note: mutex acquired here
src/engine/server/register.cpp:388:1: warning: mutex 'm_pShared->m_Lock' is still held at the end of function [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:388:1: note: mutex acquired here
src/engine/server/register.cpp:478:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:477:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:478:1: warning: mutex 'm_pShared->m_pGlobal->m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:477:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:478:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:468:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:478:1: warning: mutex 'm_pShared->m_pGlobal->m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:468:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:478:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:460:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:478:1: warning: mutex 'm_pShared->m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:460:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:715:1: warning: mutex 'ls.m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:671:2: note: mutex acquired here
        }
        ^
src/engine/server/register.cpp:715:1: warning: mutex 'm_pGlobal->m_Lock' is not held on every path through here [-Wthread-safety-analysis]
}
^
src/engine/server/register.cpp:671:2: note: mutex acquired here
        }
        ^
14 warnings generated.

```

</Details>

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
That seems like a regression in terms of number of allocations.

**Comment by def-** [comment]
Let me check, apparently it works on stack after all.

**Comment by Learath2** [comment]
Problem is what do we even switch to? LibreSSL probably mimics the OpenSSL api. NSS? Or do we just roll our own using windows and linux kernel crypto?

**Comment by heinrich5991** [comment]
We already have a sha256 for targets without OpenSSL (do we even have such targets anymore?): [src/base/libtomcrypt.cpp](https://github.com/ddnet/ddnet/blob/cbd0eafd958472cc060de88c1779eb9e2f4d86a2/src/base/hash_libtomcrypt.cpp).

**Comment by heinrich5991** [comment]
We could probably squelch the warnings by setting `#define OPENSSL_API_LEVEL 10101`:

https://github.com/openssl/openssl/blob/7fe7cc57af3db1e497877f0329ba17609b2efc8b/include/openssl/macros.h#L191-L212

**Comment by Learath2** [comment]
Iirc this implementation doesn't use CPU support for SHA256. Is that acceptable to drop an allocation?

**Comment by edg-l** [comment]
Discussion about the stack no longer supported here https://github.com/openssl/openssl/issues/7219

**Comment by edg-l** [comment]
You can probably reuse the context instead of creating it everytime:

```c
EVP_MD_CTX *ctx = EVP_MD_CTX_new();
EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_REUSE);
```

**Comment by heinrich5991** [comment]
> Discussion about the stack allocation no longer supported here [openssl/openssl#7219](https://github.com/openssl/openssl/issues/7219)

Thanks, I have looked for it but didn't find it.

**Comment by heinrich5991** [comment]
> You can probably reuse the context instead of creating it everytime:
> 
> ```c
> EVP_MD_CTX *ctx = EVP_MD_CTX_new();
> EVP_MD_CTX_set_flags(ctx, EVP_MD_CTX_FLAG_REUSE);
> ```

This obviously requires caching the context *somewhere*, where would we do that?

**Comment by heinrich5991** [comment]
(I also don't think we need to change our API to conform to the new OpenSSL, if we were to change to it. Our context could become a struct containing the pointer.)

**Comment by def-** [comment]
The reuse flag doesn't seem like a clean solution and we risk multiple threads accessing it at once etc.

I prefer the current stack approach, but we can't do that with EVP. Thus closed.

**Comment by def-** [comment]
> We could probably squelch the warnings by setting `#define OPENSSL_API_LEVEL 10101`:
> 
> https://github.com/openssl/openssl/blob/7fe7cc57af3db1e497877f0329ba17609b2efc8b/include/openssl/macros.h#L191-L212

> /usr/include/openssl/macros.h:105:4: error: "OPENSSL_API_LEVEL must not be defined by application"

**Pull request closed without merging**
