### PR TITLE
update libwebsocket to 4.x and fix bug and make client able to use websocket

### PR DESCRIPTION
**Pull request by QingGo**

### CODE REVIEW

**Comment by QingGo** [comment]
I don't know how to modify the format to pass the check. I use the clang-format version 9.0.0 and the .clang-format file of this repo.

**Comment by QingGo** [comment]
use the clang-format version 10.0.0 and fixed the format problem

**Comment by QingGo** [comment]
It seem that src/base/system.c and src/engine/client/client.cpp didn't pass the Check style. Should I submit a commit to fix these files' style by clang-format?

**Comment by heinrich5991** [comment]
@QingGo It suffices if you run `python scripts/fix_style.py --base HEAD^^^`.

The general form of this is `python scripts/fix_style.py --base <ddnet master branch>`.

**Comment by heinrich5991** [comment]
It'll only format the lines your diff touched.

**Comment by QingGo** [comment]
> @QingGo It suffices if you run `python scripts/fix_style.py --base HEAD^^^`.
> 
> The general form of this is `python scripts/fix_style.py --base <ddnet master branch>`.


Thanks for letting me know. It is convenience.

**Comment by def-** [comment]
> The general form of this is python scripts/fix_style.py --base <ddnet master branch>

@heinrich5991 I think we should that should be written somewhere one you get the warning so that people don't start trying to fix the formatting manually.

bors r+

@QingGo Thanks, let's give this a try!

**Pull request merged**
