### PR TITLE
New DDRace HUD

### PR DESCRIPTION
**Pull request by C0D3D3V**
If you want to test this PR, you have to test it on a Server that includes this PR too.

Textures are made by Ravie 

Here a showcase video with most parts shown: https://youtu.be/gPTVj-s3pgc 

Added to the new HUD
- A display of the weapons available to the player
- The weapon the player is carrying is highlighted
- Indicators for the special abilities of the player (Endless Hook, Endless Jumps, Jetpack, Teleport Weapons)
- Indicators for abilities taken away from the player (Deep/Life Freeze, No Hook, No Weapons collision, No Collision)
- Control indicators for dummy controls (dummy hammer, dummy copy) (bottom right)
- Jump indicator (max 10 jumps ar displayed, and greyed out as soon as a jump is used) 
- Ninja status bar that indicates how long a player is capable of using ninja (next to the ninja sword)
- Freeze status bar that indicates the thawing time of a player (below player)
- Movement Information can be displayed in a clean way above the mini score HUD (Position, Speed, Target Angle)
- Indicator if you are in practice mode

The complete HUD also works for players you spectate

I Added a new NetObj since the predicted values are not perfect and would make the display of the information a lot less good: DDNetCharacterDisplayInfo that contains the following information
```
NetIntRange("m_JumpedTotal", -2, 255),
NetTick("m_NinjaActivationTick"),
NetTick("m_FreezeTick"),
NetBool("m_IsInFreeze"),
NetBool("m_IsInPracticeMode"),

NetIntAny("m_TargetX"),  # used for the Movement Information display
NetIntAny("m_TargetY"),
NetIntAny("m_RampValue"),
```
So if someone has an idea what data we could also need in the client for making the display more nice, now is the right moment to add more data to this network object.

A few screenshots:
Assets Tab:
grafik
HUD Settings:
grafik
Mini Debug HUD:
grafik
Speed.X is calculated using the players ramp vaule

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Looks nice
Screenshot 2022-05-10 at 19 11 48

**Comment by def-** [comment]
Can we get rid of the server messages like "You are out of solo part" now?

**Comment by C0D3D3V** [comment]
> Can we get rid of the server messages

Good Idea :) I would prefer doing it in a additional PR, since this is already big enough.

I forgot that I suggested to rename hud.png in ddnet.png in #5047  
Do we still agree on this?

I will add the PR later (maybe tomorrow), but want to mention one thing ahead. I introduced a new snapshot type, so to get the full new HUD experience you have to test it on an server that includes this PR.

**Comment by C0D3D3V** [comment]
I will use ddnet.png, because it is only ddnet related and not for all ddrace mods.

**Comment by C0D3D3V** [comment]
after i have thought about it again and the others have revealed a little of their opinion. I think it's best to stick with hud.png. And add in another PR a new png for ddnet relevant entities. That way it's a little better separated. In the end it is not so bad if we maintain several pngs, and the assets tabs are still manageable and could be restructured if would need many more tabs. we could also load the textures of the new entities from the map resources instead of giving them a fixed shape by the client assets. or you could let the map override the client assets. But we should discuss this in another issue. 

I'm opening this up for reviews.

**Comment by C0D3D3V** [comment]
The display for jumps if you have exactly one jump in total is still broken. This is related to https://github.com/ddnet/ddnet/issues/4656.  We probably should fix the complete jumping physic.
So that I do not have to fix the calculations for the display
 https://github.com/C0D3D3V/ddnet/blob/fa2ac1bb64749c413419443cd06abc1de7d1ac9c/src/game/client/components/hud.cpp#L844-L876

**Comment by heinrich5991** [comment]
> I Added a new NetObj since the predicted values are not perfect and would make the display of the information a lot less good: DDNetCharacterDisplayInfo that contains the following information
> 
> ```
> NetIntRange("m_JumpedTotal", -2, 255),
> NetTick("m_NinjaActivationTick"),
> NetTick("m_FreezeTick"),
> NetBool("m_IsInFreeze"),
> NetBool("m_IsInPracticeMode"),
> 
> NetIntAny("m_TargetX"),  # used for the Movement Information display
> NetIntAny("m_TargetY"),
> NetIntAny("m_RampValue"),
> ```

Could this be added to `DDNetCharacter` instead?

`m_FreezeTick`: Is that calculatable from `DDNetCharacter::m_FreezeEnd`? What does `m_IsInFreeze` do? `m_IsInPracticeMode` sounds like something that belongs in a team object rather than a character one. What is `m_TargetX`/`m_TargetY` do? I don't understand what "Movement Information display" is. What is `m_RampValue` used for?

**Comment by heinrich5991** [comment]
The HUD looks amazing btw. :)

**Comment by C0D3D3V** [comment]
> Could this be added to DDNetCharacter instead?

How can we add this and still be backwards compatible? Or would you like to drop support for old DDNet versions (meaning they can not parse DDNetCharacter)?

**Comment by heinrich5991** [comment]
> How can we add this and still be backwards compatible? Or would you like to drop support for old DDNet versions (meaning they can not parse DDNetCharacter)?

I think adding fields only presents one backward compatibility hazard: New clients parsing old demos.

**Comment by C0D3D3V** [comment]
When I tried this back then, there were problems in any case. I think even if you then try to go to old servers, which still send the old snapshots, that is not parsed in the new client. Maybe I did something wrong.

To the data I send in DDNetCharacterDisplay I write later something in detail. But in generall you could predict from the upper data actually everything. Only that it is currently wrongly predicted, and is then also not available in spectator mode (with /pause) or as if you have predictions off.

**Comment by def-** [comment]
I say let's get this in and get some nightly beta testing done until 16.2 release in ~1-2 months. Only took a glance at the code, looked good.

**Comment by def-** [comment]
Something might have been merged wrongly here, the weapon shield looks wrong:
screenshot-20220515@133744

**Comment by C0D3D3V** [comment]
> Something might have been merged wrongly here, the weapon shield looks wrong

Yes it happened probably because I used an other enum for the pickups while developing and with the merge I switched to the old enum (That I did not know it exists) xD

Its fixed now, but please wait one more day... I want to try to fix the jumping count variables.

**Comment by C0D3D3V** [comment]
Mh in the last commit  https://github.com/ddnet/ddnet/pull/5085/commits/8494df2249ae7d11e40ba15623bc811ca2ed17b7 I swapped ARMOR_LASER with ARMOR_NINJA. so that at least these are sorted correctly. But since the entities are also wrong sorted and the feature is already for 18 days in it. Should I revert it again so that it is consistent and continue to use the wrong order, or do we want to directly also swap the entities?

**Comment by C0D3D3V** [comment]
since the change will not be in the next release anyway, i will revert the swap later.

**Comment by C0D3D3V** [comment]
@def- 
I fixed now the Jump display, I tested it and it displayed all the jumps correctly. I did change the gamecore a bit to force the rules we use in ddrace character already (this has no affects on other mods, because for them m_Jumps is always 2) and to make it clear that we count only air_jumps with m_JumpedTotal.
I haven't changed the jump physics, although we have fun bugs that could be fixed or at least specified as intended. But all the bugs are correctly displayed in the display (At least as far as I tested)

**Comment by def-** [comment]
Really cool, great work @C0D3D3V . Might just have to rename 16.2 to 17.0 for this ;)

Do we still want the stars when frozen now that we have the timer for freeze and ninja?

I think there might be too many HUD options, maybe we should decide to remove some:
Screenshot 2022-05-17 at 00 21 08

You're probably making many pros happy with the angle/position/speed displays.

As I said, let's get it in, some testing done and improve it.
bors r+

**Comment by l-ouis** [comment]
gun seems a little small compared to the other weapons, and dummy actions icons could be larger for better visibility.

could we change angle to 0>360 instead of 0>180>-180>0? seems a lot more intuitive
is there any way to disable stars now that we have the freeze bars? or also make freeze bars visible while inside freeze as well

very nice change, though.

**Pull request merged**
