### PR TITLE
Disable vulkan if client is off

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
BCS of find package? Guess can just disable that?

**Comment by def-** [comment]
```
-- Building vulkan shaders
CMake Error at cmake/BuildVulkanShaders.cmake:167 (message):

  COMMAND;GLSLANG_VALIDATOR_PROGRAM-NOTFOUND;--client;vulkan100;/home/teeworlds/src/master/data/shader/vulkan/prim.frag;[...]
```

**Comment by Jupeyy** [comment]
I noticed the same applies to ffmpeg, I also made it a explicit check for Client, bcs that's how other libs do it too

**Pull request merged**
