### PR TITLE
Optimization: Don't calculate with too small fraction

### PR DESCRIPTION
**Pull request by def-**
since it won't add up to anything anyway.

Hopefully doesn't break any physics.

### CODE REVIEW

**Comment by heinrich5991** [comment]
This is a complicated one. :(

Diff without whitespace changes: https://github.com/ddnet/ddnet/pull/2566/files?w=1.

**Comment by heinrich5991** [comment]
If I see this correctly, this roughly means that if your speed is larger than 100,000, then you won't move at all. Is that correct/the intention?

**Comment by def-** [comment]
Hm, I guess that might be too strict. I made the condition weaker so that we only stop when our new position has not moved at all from the old one and thus the calculations are too small to be done in float.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
