### PR TITLE
Add OpenGL error handling

### PR DESCRIPTION
**Pull request by Jupeyy**
Don't merge yet, since i don't know if this should be merged at all.
(only for OpenGL3 commands rn)

Might help with #2551, if the driver knows the error(e.g. texture incompleteness) and is able to output it.

@def- you can try (in debug mode!!) and see if the program outputs an error with that code, else it's hard to predict the error :D

### CODE REVIEW

**Comment by def-** [comment]
Do you still need me to run this? Found out how to reproduce reliably, see #2551.

**Comment by Jupeyy** [comment]
no it's fine then

**Comment by edg-l** [comment]
Imho this looks a bit ugly, this may be a opportunity to upgrade to opengl 4 which introduces [glDebugMessageCallback](https://docs.gl/gl4/glDebugMessageCallback) which makes this way cleaner. Since opengl is a experimental feature in ddnet and can be disabled I don't think it should matter removing support for old hardware that can't support this version.

**Comment by edg-l** [comment]
Wait, i think you can use [ARB_debug_output](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_debug_output.txt) which is supported from opengl 1.1

**Comment by Jupeyy** [comment]
I don't really want to increase the GL version just for debug output we rarely use, a opengl 1.1 dependecy doesn't imply that this is core since 1.1.. it basically only means you need atleast OpenGL 1.1 to even load this extension.
ARB and KHR just basically means, NVidia, amd etc., who basically say what would be possible for OpenGL, and KHR then writes the "core" version, so whoever claims to support that opengl version must also support these things, ( e.g. see  "(v13, 2012-04-19, pdaniell)
        - Remove ARB suffixs to make the extension ready for OpenGL 4.3." on the ARB page )
thats why khr debug is the thing that matters, and that's OpenGL 4.3

the point of this pr was actually that glvalidateprogram checks for completness of the programm AFTER a draw call, so e.g. if a texture is set wrongly or a sampler is invalid etc.

and since every GL call also generates a error after it fails i added it as a macro :D

I think i'll close it for now, because actually the chance of getting useful information of this isn't too high, or atleast not higher than the chance that the driver of a bugged game is the fault

**Pull request closed without merging**
