### PR TITLE
Use two fonts, one as explicit fallback

### PR DESCRIPTION
**Pull request by def-**
Merging with fontforge had problems, for example for the Bei (U+5317) in Beijing, see https://github.com/fontforge/fontforge/issues/4432

### CODE REVIEW

**Comment by def-** [comment]
Maybe someone can quickly see what I'm doing wrong.

**Comment by Jupeyy** [comment]
1 font file would be indeed nicer, tho:

line 497 - 523 just need to replace pFont with pInitialFont, else it doesn't upload to the texture of the initial font, but the fallback font:
```
		while(!GetCharacterSpace(pInitialFont, 0, (int)Width, (int)Height, X, Y))
		{
			IncreaseFontTexture(pInitialFont, 0);
		}
		UploadGlyph(pInitialFont, 0, X, Y, (int)Width, (int)Height, ms_aGlyphData);

		if(OutlineThickness == 1)
		{
			Grow(ms_aGlyphData, ms_aGlyphDataOutlined, Width, Height);
			while(!GetCharacterSpace(pInitialFont, 1, (int)Width, (int)Height, X, Y))
			{
				IncreaseFontTexture(pInitialFont, 1);
			}
			UploadGlyph(pInitialFont, 1, X, Y, (int)Width, (int)Height, ms_aGlyphDataOutlined);
		}
		else
		{
			for(int i = OutlineThickness; i > 0; i-=2)
			{
				Grow(ms_aGlyphData, ms_aGlyphDataOutlined, Width, Height);
				Grow(ms_aGlyphDataOutlined, ms_aGlyphData, Width, Height);
			}
			while(!GetCharacterSpace(pInitialFont, 1, (int)Width, (int)Height, X, Y))
			{
				IncreaseFontTexture(pInitialFont, 1);
			}
			UploadGlyph(pInitialFont, 1, X, Y, (int)Width, (int)Height, ms_aGlyphData);
		}
```

**Comment by def-** [comment]
Made a bug report for the merging in fontforge for now: https://github.com/fontforge/fontforge/issues/4432

**Comment by def-** [comment]
Thanks @Jupeyy, seems to work now!

**Comment by def-** [comment]
Thanks to @Jupeyy it is working fine now. Tested by @TsFreddie

**Comment by def-** [comment]
Anyone feeling up to review? I want to get this in for the 14.4 release. @Jupeyy can you judge if this is ok?

**Comment by Jupeyy** [comment]
i'll use this patch and generalize it more if thats ok, but generally the idea of fallback fonts is nice

**Comment by def-** [comment]
> i'll use this patch and generalize it more if thats ok, but generally the idea of fallback fonts is nice

Absolutely, I was hoping for you to make a clean version of my quick hack. :)

**Pull request closed without merging**
