### PR TITLE
"Spectate" to "Spectating" in Spectator UI

### PR DESCRIPTION
**Pull request by EGYT5453**
Changing "Spectate" to "Spectating" in the bottom right corner when in Spectator mode so it makes more grammatical sence

Before:
Before: "Spectate: player"
After:
After: "Spectating: player"

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — COMMENTED** [review]
I'm not sure if we should change that, other opinions? If we do, I'll go through the existing translations and replace the Spectate text in English so that it doesn't have to be retranslated in all languages.

**Comment by EGYT5453** [comment]
The modification does not affect the "Spectate" button, and replacing "Spectate" with "Spectating" in translations will result in button becoming untranslated.

nochange

**Comment by heinrich5991** [comment]
"Spectating: Free-View" might not be the best label. Someone suggested we could use "Following {player}" or "Free-View", both without "Spectate:"/"Spectating:".

**Comment by EGYT5453** [comment]
Yeah, removing `Spectate` entirely so there is only <player>/`Free-View`/`Multi-View` left also makes sence

**Comment by Robyt3** [comment]
Superseded by #8499.

**Pull request closed without merging**
