### PR TITLE
Make animations more consistent with high float values

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes what is described in #2997

Old client animation when server time is huge:

[vid_old.zip](https://github.com/ddnet/ddnet/files/5322484/vid_old.zip)

 client animation when server time is huge:

[vid_new.zip](https://github.com/ddnet/ddnet/files/5322486/vid_new.zip)

@Fireball-Teeworlds maybe u can try, if that fixes the stuff for u

### CODE REVIEW

**Comment by Fireball-Teeworlds** [comment]
Can't test it anymore - I took the previous discovery as a cue to install some updates. My systems uptime is gone :/

I like int64 for Time since there's no reason to have different precision based on the uptime of the server or client. Although it does seem to require more conversions to float-and-back in calculations.

**Comment by Jupeyy** [comment]
true, i can remove the timeoffset cast, but it doesnt matter too much anyway, the trade is that there is less floating point calculations in total

**Comment by Jupeyy** [comment]
anyway, we need this fix, bcs animations are still laggy with high times, e.g. synchronized animations

**Comment by def-** [comment]
bors r+
Let's try it, but not for this release.

**Pull request merged**
