### PR TITLE
 Fix pickups moving on their own (fixes #5137)

### LINKED ISSUE #5137: Shields and weapons sometimes move away / don't appear
This started yesterday after switching to new server version (@heinrich5991's rebased pr_ddnet_serverbrowse_http_server branch. Update: happens on master too so not related to the branch)
weirdstuff
I'm not sure what change is causing this, I can't reproduce it.

Old change: c5230110
New change: c082a842
Suspicious looking changes: https://github.com/ddnet/ddnet/pull/4959 https://github.com/ddnet/ddnet/pull/5125 https://github.com/ddnet/ddnet/pull/5076

Anyone got an idea or know how to reproduce it reliably?

### PR DESCRIPTION
**Pull request by def-**
Supersedes #5181 

Objects should be initialized fully, otherwise they are super easy to misuse and get weird undefined behavior that happens rarely.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Contains https://github.com/ddnet/ddnet/pull/5186 now

**Comment by C0D3D3V** [comment]
Are CI builds with this change, with our without IPO?

**Comment by def-** [comment]
Since it includes #5186, the new default is without IPO and thus the CI builds are without it too.

**Comment by C0D3D3V** [comment]
I can still not reproduce this bug without this change (I only tested on Arch linux, I would have to test in Windows VM probably), so I may not be the best reviewer, but the change itself looks good.

**Comment by def-** [comment]
It depends on what is in the memory before. I can get it locally just randomly, and can reproduce it even better (but only with LTO) with `valgrind --tool=memcheck --malloc-fill=0xFF ./DDNet-Server`

**Comment by C0D3D3V** [comment]
So I tried to build it with the following two commands and then start the server as you wrote with valgrind. But for me the bug does not occur:
`cmake -DIPO=ON .. && make -j$(nproc)`
also tried `cmake -DDEV=ON -DIPO=ON ..  && make -j$(nproc)` 
I have reloaded my testmap several dozen times.
I also tried it now in a windows VM, but without valgrind and didn't feel like doing anything else to dirty the heap.

But that's not important, I don't need to be able to reproduce it as long as the bug doesn't occur anymore. 

Thank you :)
bors+

**Review by C0D3D3V — APPROVED** [review]

**Comment by def-** [comment]
Tbh I also don't understand why the compiler sometimes default-initializes these union members, sometimes doesn't. But accessing uninitialized union members is undefined behavior, so I guess the compiler can do whatever it wants.

**Pull request merged**
