### PR TITLE
Kick-voting someone from team doesn't kill locked team (fixes #3207)

### LINKED ISSUE #3207: Why does kicking someone from your team kill the entire team
Probably with locked team
Reported by Skeith.

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
This changes the network in an incompatible way (killer IDs are sent over the network and need to be >= -3. I think WEAPON_GAME would fit nicely.

**Comment by def-** [comment]
You mean we just map it to WEAPON_GAME for what is sent over network, but on the server still handle it as -4?

**Comment by heinrich5991** [comment]
I think changing it to WEAPON_GAME on the server (and removing WEAPON_VOTE) would be fine.

**Comment by def-** [comment]
Ok, based on the name I assumed WEAPON_GAME would be used for something else.

**Pull request merged**
