### PR TITLE
Fix png error handling by setting jmpbuf

### PR DESCRIPTION
**Pull request by Jupeyy**
else libpng will kill the thread on an error bcs it's a fatal error.

broken skin can be found in discord bugs channel weeb_okayu

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
mac build fails. should be in 15.3.1?

**Comment by heinrich5991** [comment]
Is this a bug in libpng? Is it okay to longjmp out of libpng?

**Comment by def-** [comment]
Weird, still the same failure in macOS CI. I don't get the failure locally, so will release with this now.

**Pull request merged**
