### PR TITLE
Don't set predefined DDNet tunings by default

### PR DESCRIPTION
**Pull request by gerdoe-jr**
Finally found reason of weird vanilla demos behaviour. If it has downfalls in terms of prediction DDNet/DDRace/any other mod, please mention it here
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Why did you also set m_PredictDDRaceTiles? Related discussion issue #8923

**Comment by ChillerDragon** [comment]
Tagging related issue: https://github.com/ddnet/ddnet/issues/8895

**Comment by heinrich5991** [comment]
Does this still apply the correct tunings to DDNet demos?

**Comment by Kaffeine** [comment]
See also:
- [prev fix](https://github.com/ddnet/ddnet/pull/4795/commits/754562ce0bb7656dc146b8c9d823ee1a6756f4c8) (was not wrapped in `if(PredictDDRace)`)
- [prev fix revert and discussion](https://github.com/ddnet/ddnet/pull/4959). The keypoint for me was that server sends DDRace custom tuning (in other case vanilla and other clients won't work right), and that `NETMSGTYPE_SV_TUNEPARAMS` should be correctly unpacked and applied by the client. Probably the issue is in the `NETMSGTYPE_SV_TUNEPARAMS` processing, and the correct fix would fix demo playback with for any custom tunings, not just vanilla or DDRace. AFAIU, this custom tuning code should be dropped in the properly fixed client.

**Comment by Kaffeine** [comment]
The proper fix is:
1. Sync `CGameClient::m_aTuningList` from `CGameClient::m_Tuning` on `NETMSGTYPE_SV_TUNEPARAMS` read.
2. Drop the custom tuning entirely (as in https://github.com/ddnet/ddnet/pull/4795/commits/754562ce0bb7656dc146b8c9d823ee1a6756f4c8)

https://github.com/ddnet/ddnet/pull/4959#issuecomment-1093805477

**Comment by ChillerDragon** [comment]
@Kaffeine could you send a pr with that proper fix?

**Comment by Kaffeine** [comment]
> @Kaffeine could you send a pr with that proper fix?

Sorry, I won't have time for this in the foreseen future. Tune zones is a DDNet feature which breaks other mods. 

Considering #7777 I have no plan to put effort in fixing DDNet stuff.
More than than, I contributed too many refactoring with a hope to eventually pull it to infclass when it would be easier to port infclass ontop of this codebase but nah, I was too naive to put so much effort into "upstream first" approach. Now I have an even longer list of TODO for infclass, and even less motivation to do anything at all.

**Comment by ChillerDragon** [comment]
@Kaffeine  yes #7777 is a bummer. But I don't see it being in the way for fixing tunes. It is a pretty serious bug that should be fixed.

But if you are tired of contributing to upstream that is totally understandable thanks for all your efforts. I do for sure appreciate your merged prs a lot.

**Comment by ChillerDragon** [comment]
Superseded by #9174

**Pull request closed without merging**
