### PR TITLE
Fix votes for sixup

### PR DESCRIPTION
**Pull request by Learath2**
I think this looks sane but I haven't tested it at all for idk how to even test this locally/alone

### CODE REVIEW

**Comment by def-** [comment]
Tested by connecting on 127.0.0.1, lan address and internet address with 3 clients.

Noticed:
- Started kick vote on DDNet client, voted F4 on Teeworlds 0.7, doesn't register
- Started map vote on DDNet client, voted F4 on Teeworlds 0.7, registers as YES, not NO

So this seems like it doesn't work well yet at all.

**Comment by def-** [comment]
Ah, I see. The 0.7 player is not counted because they have to wait 300 seconds at the start before voting. Why don't 0.6 players have to wait 300 seconds? I have sv_join_vote_delay set to 300 as it's the default.

**Comment by Learath2** [comment]
@def- I think this completes it

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
