### PR TITLE
Check skin/sprite images for correctness

### PR DESCRIPTION
**Pull request by Jupeyy**
I hope this helps with downloading things at wrong resolution again.

Note that this commit is smaller than it seems, bcs of renaming files and moving code to it.
Also this requires new translations.

In the skin database are invalid skins too:

screenshot_2020-11-18_07-51-02
screenshot_2020-11-18_07-51-05

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Also resizes invalid ones to work properly

**Comment by def-** [comment]
We definitely have to fix the skins inside skin db, otherwise people can easily trigger this warning for everyone on a server.

**Comment by def-** [comment]
> Note that this commit is smaller than it seems, bcs of renaming files and moving code to it.
Also this requires new translations.

Note for the future: Would have been nice to split this into 2 commits, one that only moves stuff around, the other that does the actual change. Helps with reviewing.

**Comment by def-** [comment]
> We definitely have to fix the skins inside skin db, otherwise people can easily trigger this warning for everyone on a server.

Done.

bors r+

**Pull request merged**
