### PR TITLE
Add sv_check_teleport_hold_hook map setting

### PR DESCRIPTION
**Pull request by timakro**
Requested by phacrum

### CODE REVIEW

**Comment by def-** [comment]
Shouldn't sv_teleport_hold_hook just do that too?

**Comment by timakro** [comment]
Might break old maps using sv_teleport_hold_hook and checkpoint tele

**Comment by def-** [comment]
How many maps are we talking about?

**Comment by timakro** [comment]
No idea if there even are maps like that

**Comment by def-** [comment]
RON, Justice 2 and "Sonne, Mond und Sterne" use sv_teleport_hold_hook, no other maps.

**Comment by timakro** [comment]
The only one of those with checkpoint tele is Justice 2 by 645654, Pipou & Phacrum.

**Comment by def-** [comment]
So ask them if it would be a problem for their map and if so, let them fix their map.

**Comment by timakro** [comment]
Phacrum confirmed, that this change doesn't break Justice 2.

**Comment by def-** [comment]
Thanks

**Pull request merged**
