### PR TITLE
Make players AFK when they first join a server

### LINKED ISSUE #1797: Players should be considered idle when first entering server (or after map change), until their first movement
Idle players aren't counted in votes, but after map changes those idle players are no longer considered idle. Subsequent votes are impossible unless you wait for their idle timeout to trigger, or vote those players to spec. If we considered a player idle when first entering server (until their first movement), the problem would go away and you can change the map multiple times in a row even if there are a ton of idle players present.

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by bojidar-bg** [comment]
I think you should change `m_LastPlaytime` as well, since otherwise m_Afk would be reset immediately afterwards.

**Comment by fokkonaut** [comment]
LastPlaytime is set to time_get(), which should return the current time, isnt that correct?

**Comment by bojidar-bg** [comment]
It should probably be `time_get()-time_freq()*g_Config.m_SvMaxAfkVoteTime`

**Comment by fokkonaut** [comment]
oh, yes you are right

**Comment by fokkonaut** [comment]
I couldn't get it to work, since in this function (https://github.com/ddnet/ddnet/blob/fae314521c470a5a4192bc0fa409d913a7ee535a/src/game/server/player.cpp#L653) it will automatically set the m_LastPlaytime to now again. I will close this pull request and let someone else figure this out.

**Pull request closed without merging**
