### PR TITLE
Add integration test script and coverage map

### PR DESCRIPTION
**Pull request by ChillerDragon**
The ``scripts/integration_test.sh`` runs two clients and one server. Lets the two clients connect for a few seconds.
The goal is to get some automated runtime tests. Even tho the the two clients do not move they will touch a few gametiles by falling through them. This covers a few basic game mechanics like: freeze, draggers, bullets, solo, shields, tele, speedup, collision, player collision and map finishes.

This pr adds a new directory ``test/`` at the root of the repository. Holding a test map. (not sure if thats cool :shrug: )

The script can be run locally using ``scripts/integration_test.sh [build directory]`` using ``build`` as a default. It will catch client/server crashes and check if sqlite ranks are inserted. If built with asan/ubsan it will catch these errors too. Probably not too useful for local testing since it most likely will not cover the currently developed features.

In the CI it will use a ASan + UBSan build directory and thus catch all basic issues caused by simple  client server interaction.

image

### CODE REVIEW

**Comment by Chairn** [comment]
Wow, that is some nice work ;)
But fixing the ubsan in gamecore scares me as it's tightly related to physics...

**Comment by def-** [comment]
>  But fixing the ubsan in gamecore scares me as it's tightly related to physics...

Just make sure it returns the same result as we are currently getting on official servers.

**Comment by C0D3D3V** [comment]
Some ddnet features result from nan values that happen from some divisions by 0 or similar. Like when two tees are inside each other and you shoot with the shotgun it gets a huge boost. the question is if such bugs should be fixed or if the feature should stay in, so if we fix the nan values we still need to create big values.

**Comment by def-** [comment]
Physics should stay as it is and be made deterministic without using undefined behaviour.

**Comment by edg-l** [comment]
I havent checked the map, but i guess its all a free fall. My suggestion is to not make it all a free fall but move the tee around a bit with speeders, this way we can test they also don't change. Would do the same with any tile that moves the tee, such as draggers, explosion bullets, etc

**Comment by ChillerDragon** [comment]
> I havent checked the map, but i guess its all a free fall. My suggestion is to not make it all a free fall but move the tee around a bit with speeders, this way we can test they also don't change. Would do the same with any tile that moves the tee, such as draggers, explosion bullets, etc

Yes the map is free fall. I attached an image ^

Yes using speedups and draggers instead of free fall is a nice idea. The map is an early draft and can be improved a lot.

**Comment by Chairn** [comment]
How about we print tee position at every tick and compare it to a golden reference?

**Comment by ChillerDragon** [comment]
> How about we print tee position at every tick and compare it to a golden reference?

Doubt that works. Isn't player collision already random. Draggers probably as well.

Anways that sounds kinda spammy. Just checking the race time should also do.

**Comment by heinrich5991** [comment]
Looks good but does seem to unearth some ASAN problems in the client. They need to be fixed so this can be merged.

**Comment by heinrich5991** [comment]
Status: The newly enabled checks in "Check ASan & UBSan / check-clang-san (pull_request)" fail, this is not the fault of this pull request though.

**Comment by C0D3D3V** [comment]
We should probably fix the bugs reported by Asan & Ubsan soon, so we can get this in, to avoid problems like https://github.com/ddnet/ddnet/issues/5226 in the future.

**Comment by def-** [comment]
I'll give it a try to get this green.

**Comment by def-** [comment]
For clean runs locally I had to set it up with `mkdir san && cd san && CC=clang CXX=clang++ CXXFLAGS="-fsanitize=address,undefined -fsanitize-recover=address,undefined -fno-omit-frame-pointer" CFLAGS="-fsanitize=address,undefined -fsanitize-recover=address,undefined -fno-omit-frame-pointer" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja ..` and then for each run do `rm -rf test && git checkout -- test && cd san && ninja && cd .. && scripts/integration_test.sh san`. Run is now clean.

**Comment by heinrich5991** [comment]
Cool! Thank both of you. :)

bors r+

**Comment by C0D3D3V** [comment]
Since the integration tests only run under linux, they do not detect the crash of #5226. 
@ChillerDragon  would you like to extend this to windows?

**Pull request merged**
