### PR TITLE
Increase http connect timeout

### PR DESCRIPTION
**Pull request by ardadem**
Here is my curl output:

```
curl -o /dev/null -w  "%{time_starttransfer}\n" https://info.ddnet.tw/info
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6860    0  6860    0     0   1286      0 --:--:--  0:00:05 --:--:--  1467
5.333923
```

Also https://github.com/ddnet/ddnet/issues/1863

### CODE REVIEW

**Comment by def-** [comment]
This also means that if the maps.ddnet.tw server is unreachable you have to wait 10 seconds before loading from game server.

**Comment by Learath2** [comment]
@def- Hmm, maybe we should change the `CanTimeout` to a `Timeout` so we can have per task control of it?

**Comment by def-** [comment]
Sure, sounds fine. The info thing should never timeout though, should it?

**Comment by Learath2** [comment]
@def- It has to time out, a kernel job staying forever is not good as it'll waste a worker

**Comment by ardadem** [comment]
I'm closing it then. We can discuss it here: https://github.com/ddnet/ddnet/issues/1863

**Pull request closed without merging**
