### PR TITLE
Group a couple of "list" messages

### PR DESCRIPTION
**Pull request by heinrich5991**
This allows custom clients to understand when a list is complete, instead of relying on heuristics such as timeouts.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
I think it would be nicer to have only one start and one end message but it has a unique identifier as argument. With the current approach you need to keep adding custom net messages for every list. And if a list is sent twice you do not know which sending ended.

**Comment by heinrich5991** [comment]
> I think it would be nicer to have only one start and one end message but it has a unique identifier as argument. With the current approach you need to keep adding custom net messages for every list.

Adding net messages for every list that exists doesn't sound negative to me.

> And if a list is sent twice you do not know which sending ended.

With the current system, a list cannot be sent twice at the same time, you wouldn't know which of the items belongs to which of the concurrently sent lists of the same type.

**Review by def- — APPROVED** [review]

**Comment by ChillerDragon** [comment]
Okay seems to make sense

**Comment by ChillerDragon** [comment]
What about including the number of elements that will be sent in the first message. So the client could show a progress bar by counting them. Then the end message could also be dropped (but does not have to since adding a bunch of messages does not seem to be a problem).

**Pull request merged**
