### PR TITLE
Allow multiple addresses per server in the serverbrowser

### LINKED ISSUE #5158: HTTP master: Client should display servers with multiple addresses in a better way
Currently the server entry is just duplicated in the server list.

Also contains a rabbit hole in how to deal with favorites.

### PR DESCRIPTION
**Pull request by heinrich5991**
Support is incomplete for `leak_ip_address_to_all_servers` (will only
ping the first address of each server) and for the `leak_ip` setting
(which will also only ping the first address of each server).

Fixes #5158.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
@ChillerDragon I'm trying to run the scripts/integration_test.sh locally. How does a successful run of scripts/integration_test.sh look like? How do I figure out what went wrong? It seems that the server is not there anymore by the time that the second client starts. Is this expected?

**Comment by def-** [comment]
I did it like this: https://github.com/ddnet/ddnet/pull/5006#issuecomment-1137946894

**Comment by heinrich5991** [comment]
Rebased.

**Comment by def-** [comment]
Let's get this in so it doesn't have to be rebased again. Do we even have servers with multiple addresses right now? Do we want to enable ipv6 on ddnet official servers? Or is it mostly for proxy?

bors r+

**Comment by heinrich5991** [comment]
> Let's get this in so it doesn't have to be rebased again. Do we even have servers with multiple addresses right now? Do we want to enable ipv6 on ddnet official servers? Or is it mostly for proxy?

We don't have servers with multiple IP addresses right now, but any game server supporting both IPv4 and IPv6 would show up twice in the server list before this pull request.

Additionally, this sets the groundwork for proxies etc., as you mentioned.

**Pull request merged**
