### PR TITLE
Center tees in more places

### PR DESCRIPTION
**Pull request by Jupeyy**
tee settings
scoreboard
spectator board

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Screenshots would be nice. Best before/after, maybe by recording a demo.

**Comment by Jupeyy** [comment]
https://discord.com/channels/252358080522747904/293493549758939136/820011308979585114

What do you mean by demo?

**Comment by heinrich5991** [comment]
image
image

**Comment by heinrich5991** [comment]
I meant recording an ingame demo, so you could have the same scoreboard twice. Thanks for the screenshots.

**Comment by Jupeyy** [comment]
> I meant recording an ingame demo, so you could have the same scoreboard twice. Thanks for the screenshots.

To check the difference or what? Sry im too dump to understand it xD

Anyway, its not too special, it just uses a calculation to determine the center, like it does for chat and statboard, instead of random fixed numbers

**Comment by heinrich5991** [comment]
I was skeptical of the description, but the results look nice.

**Comment by def-** [comment]
bors r+
Nice

**Pull request merged**
