### PR TITLE
VBO deletion after VAO deletion & viewport adjustment for dpi scaled displays at fullscreen

### PR DESCRIPTION
**Pull request by Jupeyy**
That fixes the AMD driver bug, and readjusts fullscreen resolutions, so that the opengl viewport can render non dpi scaled at fullscreen(only) (if dpi awareness isn't enabled, e.g. windows 7)

### CODE REVIEW

**Comment by def-** [comment]
Failed circleci

**Comment by Jupeyy** [comment]
this time it failed, because bam died ^^

**Comment by def-** [comment]
Yes, but read the error message and fix it please.

**Comment by msiglreith** [comment]
FWIW that's not a driver bug. VAO only takes care of the setting up the input assembler related data (i.e vertex input slots etc.). VBOs are typed wrappers around the underlying GPU memory where the actual vertex data information is stored. This won't be consumed by a VAO somehow. Deleting the VBO allows the driver to reuse the VBO memory.

**Comment by Jupeyy** [comment]
> When a buffer, texture, renderbuffer, query, or sync object is deleted, its name
immediately becomes invalid (e.g. is marked unused), but the underlying object
will not be deleted until it is no longer in use. A buffer, texture, or renderbuffer
object is in use while it is attached to any container object or bound to a context
bind point in any context. 

https://www.khronos.org/registry/OpenGL/specs/gl/glspec33.core.pdf
D.1.2

the spec clearly says that, so it's a driver bug

**Comment by Rootkitee** [comment]
Umm poop?

**Pull request merged**
