### PR TITLE
Feature: Hook range indicators

### PR DESCRIPTION
**Pull request by metamuffin**
Since it's hard for new players to estimate the length of their hook on the fly, it would be useful to have a indicator for that.
I've added thin circles around the players and options to enable this for your own hook and the one of other players.

(screenshot upload doesn't work sadly)
## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
screenshot-20210320@092415
Looks ok, from my side, but might be a bit annoying to play with. Not sure if new players would know to activate this. (and we probably don't want to turn it on by default)

**Comment by MetaMuffin** [comment]
I though I already disabled it by default. When 0 means disabled then the 0 as the 'Def' parameter in MACRO_CONFIG_INT disables this. Have i misunderstood something there?

**Comment by def-** [comment]
No, it works.

**Comment by 12pm** [comment]
dumbs the game down for no reason, hook behaviour is something you can learn as a beginner

**Comment by fokkonaut** [comment]
Also there is the hookline, always indicating the length. I dont think this is needed.

**Comment by Learath2** [comment]
I think it's nice to have, would be better if it changed colors the same way the hookline does, but as is it's also nice.

Does it dumb the game down, idk did hookline dumb the game down? I think it might be a nice training tool for newer people

**Comment by heinrich5991** [comment]
I'm okay with showing this information.

What does this show? The hook range for hooking walls? Or for hooking tees? What is the requirement for either of these to happen? Can you show screenshots of some edge cases?

**Comment by MetaMuffin** [comment]
Changing the colors is a good idea. For now i have just used some hardcoded ones.
What could the colors indicate there? Doing a collision check like the hookline for every point in the circle is not an option, since its too expensive.

Also the circle shows the distance for hooking anything. (I hope I am not wrong there)

I also didn't implement any edge cases, because i don't know any. The circle just shows the *maximal* range, not like the hookline. The goal for this feature is mainly for practice as you've guessed. It should not replace hookline.

**Comment by heinrich5991** [comment]
> Also the circle shows the distance for hooking anything. (I hope I am not wrong there)

If that's your assumption, you should really test it ingame. ;) I think hooks to ground have a slightly different range from hooks to other tees.

**Comment by Learath2** [comment]
> > Also the circle shows the distance for hooking anything. (I hope I am not wrong there)
> 
> If that's your assumption, you should really test it ingame. ;) I think hooks to ground have a slightly different range from hooks to other tees.

Is that not because tees have a fatter hitbox?

**Comment by MetaMuffin** [comment]
I thought that too. I can only find a variable for *the* hook range.

**Comment by kamillentee** [comment]
I like the idea, thought about it when you have another tee laying on top of a freezed platform and this tee is almost unreachable. 
In those cases the freezed tee can't use the hookcoll itself to check if it is saveable as the hook starts from tee center but the hitbox is much bigger, and the saviour already has trouble to not fail near all that freeze and cannot help with hookcoll either. 
~~So an idea is to change the circle color to yellow  as soon as a hookable tee is in reach. An aimbot-like approach to find tees within reach should not be too expensive, is'nt it?~~ 

Ok the informations get useless when there are multiple tees nearby. I think the circle alone without a colorchange is fine already, as people will get used to it and guess if its even possible to save a failed tee. In combination with hookcoll you can make an area visible where a tee is still hookable.


> What does this show? The hook range for hooking walls? Or for hooking tees? What is the requirement for either of these to happen? Can you show screenshots of some edge cases?

Hookcoll always showed the hookrange to tees only (to their real hitbox). 
screenshot_2021-03-20_20-29-44
screenshot_2021-03-20_20-30-09
screenshot_2021-03-20_20-31-01
screenshot_2021-03-20_20-31-19

Note how it is very accurate for tees but not for walls. If you want to hook a wall on the right side, the hookcoll seems to touch the wall already at x.12 (I moved a step < to make it more clear) while the first coordinate to reach the wall is x.69 that is 18/32 blocks further apart. For the hookcircle it will not be different as it uses the same variables.

**Comment by BannZay** [comment]
Could this range check be added to the map editor proof feature, please?

**Comment by fokkonaut** [comment]
> Could this range check be added to the map editor "Proof" feature, please?

Has to be tunezone dependent tho.

**Comment by heinrich5991** [comment]
@metamuffin Current behavior needs explanation whether this is wall/tee hooking length. Also would need to be rebased.

Sorry for leaving this around for half a year. Are you still interested in this?

**Comment by heinrich5991** [comment]
Ping me if you want to reopen this. :)

**Pull request closed without merging**
