### PR TITLE
Improve AppStream manifest

### PR DESCRIPTION
**Pull request by ElXreno**
This tags required for [Flathub AppData Guidelines](https://github.com/flathub/flathub/wiki/AppData-Guidelines).

If watch this tags in [FreeDesktop AppStream Guidelines](https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html), `content_rating` tag is optional but `releases` tag required.

If you want to know a little bit more about `OARS`, watch [this](https://hughsie.github.io/oars/index.html).

### CODE REVIEW

**Comment by heinrich5991** [comment]
Thanks for the pull request.

I got this result from the OARS website:
```
  <content_rating type="oars-1.1">
    <content_attribute id="violence-cartoon">moderate</content_attribute>
    <content_attribute id="social-chat">intense</content_attribute>
  </content_rating>
```

What do you think about this? This was:

> Cartoon Violence
>
>Defined as fictional characters depicted in an animated film or a comic strip which do not look human.
>
>For example, this would include an animated worm fighting with a bird. 

and:

>Online Text-only Messaging
>
>Defined as any messaging system connected to the Internet.

**Comment by ElXreno** [comment]
@heinrich5991 I agree with your result, I think it more correct that mine.

Waiting for @def- opinion.

**Comment by def-** [comment]
Yeah, let's take @heinrich5991's  content_rating

**Pull request merged**
