### PR TITLE
fix 0.7 feet offset

### PR DESCRIPTION
**Pull request by SoulyVEVO**
before
before

after
after

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — COMMENTED** [review]
Why is it more correct this way?

**Comment by SoulyVEVO** [comment]
Looks more appealing and closer to what we have on 0.6, i saw quite a lot of people complain about this when trying 0.7

**Comment by heinrich5991** [comment]
Can you post a comparison between similar 0.6 and 0.7 skins, perhaps the default skin?

**Comment by SoulyVEVO** [comment]
After the change:
comparision
Before the change:
comparision2

**Comment by heinrich5991** [comment]
Thanks for the nice comparison images. I agree that the new values look closer to what we have already.

**Comment by ChillerDragon** [comment]
I also only ever hear complains about the feet while nobody ever defended them. Not sure how that was introduced. Maybe it was an accident.

Thanks for doing this @SoulyVEVO :heart:

**Review by def- — APPROVED** [review]

**Comment by TsFreddie** [comment]
> I also only ever hear complaints about the feet while nobody ever defended them. Not sure how that was introduced. Maybe it was an accident.
> 
> Thanks for doing this @SoulyVEVO ❤️

i think it just happens when all the assets were remade and rendering code has to redone to a degree in 0.7. it's probably unnoticeable for the dev doing the work at the time. (and probably to most people imho)

**Pull request merged**
