### PR TITLE
Add more debug info to teamrace to figure out how duplicate ranks occur

### PR DESCRIPTION
**Pull request by Zwelf**
Should help with #6194. I don't have my mysql setup with me right now, so I can't check if I can find out what is going wrong. I'll see if I can do that tomorrow :)

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
bors r+
Thanks, let's give that a try.

**Comment by Zwelf** [comment]
(sorry just found a thing wrong with the patch, when trying to sleep thinking about what could cause duplicate ranks (lol)

**Comment by Zwelf** [comment]
A return statement was missing: https://github.com/ddnet/ddnet/compare/1491daf88c0970153a706a36feaceed94426c701..f5dc372d79a4a1abe196a2d3bdbc53f35945c1a7, I think should be good now.

**Comment by def-** [comment]
bors r+
Good catch :)

**Pull request merged**
