### PR TITLE
show if user has rank on map in browser (+filter)

### PR DESCRIPTION
**Pull request by timgame**
Works with file score and sql score. Client requests has rank on serverbrowser refresh and on name change. Server sends has rank on map finish.

credits to Soreu for the graphics

### CODE REVIEW

**Comment by heinrich5991** [comment]
The general idea is nice, but the implementation will not work like that: It's too easy to DoS this service.

E.g.: You can spawn a thread on the server for a packet worth roughly 50 bytes, that means you can spawn spawn 20k threads in one second if you're on a line that can handle 1MB/s upload.

**Comment by H-M-H** [comment]
just wrote something similar on skype :), this things should be stored clientsided somehow and requested only if really required

**Comment by def-** [comment]
@H-M-H It still stays just as easy to DoS for an attacker that skips the client cache and simply sends a few thousand requests per second.

**Comment by east** [comment]
> just wrote something similar on skype :), this things should be stored clientsided somehow and requested only if really required
The main problem is that the server will do sql requests on demand. We'll need to send cached ranks instead.

**Comment by def-** [comment]
@east Won't work. Imagine an attacker that spoofs IP addresses and sends a new random name all the time.

**Comment by east** [comment]
Isn't it about players ingame?

**Comment by east** [comment]
Okay, since the idea requires to allow requesting of any name, a proper protocol with handshake and flooding prevention is needed.

**Comment by H-M-H** [comment]
@def- true, in theory the client could do everything on it's own. The server is required only cause the client didn't remember already finished maps. So what about adding a file that lists all finished maps and create a way to download such a file with all maps finished on ddnet from the website

**Comment by heinrich5991** [comment]
That would work, but it would be ddnet-only. I guess one could fix that by creating a way of querying the ranks URL.

**Comment by def-** [comment]
> That would work, but it would be ddnet-only. I guess one could fix that by creating a way of querying the ranks URL.

And while you're at it, same complaint comes in for map downloads. The server should simply say: Try to get my maps from http://maps.ddnet.tw/MAPNAMEHERE

**Comment by timgame** [comment]
I don't know much about networks. Why this is more dangerous than the normal server info request for example?

**Comment by east** [comment]
see https://github.com/ddnet/ddnet/pull/344#issuecomment-145974664

**Comment by timgame** [comment]
The thread and the SQL is a problem but is the package size bigger than the

**Comment by timgame** [comment]
Sorry, I'm trying to use github on my phone.

**Comment by timgame** [comment]
Closing for now.

**Comment by markusmo3** [comment]
Is this at all possible? Because i would *really* love to have this!
I cant remember all the maps i finished and switching in and out is kinda annoying.

**Comment by def-** [comment]
It could be implemented by asking the ddnet main server to send you a list of all the maps that you have finished, like on https://ddnet.tw/players/deen

We already have a service running for the /players/ thing, so that could be extended and would probably be reasonably fast. ( < 100 ms) But the load on the server could be pretty high. And I don't know if we want the client to make an https request every time that you refresh the ddnet browser.

Also that kind of solution would be DDNet specific, so other servers would not benefit.

**Comment by markusmo3** [comment]
Hmmm, the request could contain a md5 hash of a locally cached version of completed maps. Also update that cache when you finish a map. This way the full response is only sent if either you have no local cache or it is outdated due to you playing on a another computer. The request call would still be there though...

I might have a look at it if i find time and have the urge to learn c++ again ^^

**Comment by def-** [comment]
I have added this.

**Pull request closed without merging**
