### PR TITLE
CMakeLists.txt: Replace PythonInterp with Python

### PR DESCRIPTION
**Pull request by yangfl**
FindPythonInterp is deprecated since CMake version 3.12. Use Python to
automatically detect Python 3 or 2.

### CODE REVIEW

**Comment by Learath2** [comment]
Looks good to me. Thanks
bors r+

**Comment by heinrich5991** [comment]
It seems that we don't test on old CMake versions anymore (?). Can we please revert this? As far as I can tell, this bumps our minimum required CMake version to 3.12: https://cmake.org/cmake/help/latest/release/3.12.html#modules.

**Comment by heinrich5991** [comment]
Never mind, I didn't see that it falls back to the old code. I guess this is fine then.

**Comment by yangfl** [comment]
@heinrich5991 I did include PythonInterp just for old CMake 2.8.

**Pull request merged**
