### PR TITLE
Revert ingame menu close button, Add help text at bottom left when menu is open

### LINKED ISSUE #5881: Close game button and settings button are in inconsistent locations (from #5861)
IMO this is not good UX. If you try to click the settings button it is going to be in a different spot depending on if you are in-game or in menus. even worse the button which replaces it when you are in-game causes the game to close. 

from https://github.com/ddnet/ddnet/pull/5861
image
image

### PR DESCRIPTION
**Pull request by def-**
Even I got confused by it and accidentally hit power off button. Left side seems not popular for close either (#5888)

Since opening the menu requires Escape, players can probably figure out Escape to close it again.

Add help text at bottom left when menu is open

screenshot-20221003@000950

> Revert "Don't show home button ingame"
>
> This reverts commit d3ff903d445a7c5d62f9ed55690546a4689a608d.
>
> Revert "Move home button to very right so it is consistent with close button ingame (fixes #5881)"
>
> This reverts commit 9cc08cc9d31820a57cc5e221dcad3785542845c1.
>
> Revert "Add close button to close ingame menu"
>
> This reverts commit cfcfb7b3f0326da99f0bf9b1274e20d6dbfa5532.

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
Power off ask for confirmation, so it shouldn't be a problem :)

**Comment by def-** [comment]
Only asks after some game time I think, so while moderating and chatting I wasn't asked.

**Comment by heinrich5991** [comment]
> any stats for this? cant imagine this happens to more than a very few ppl

I haven't kept track. It was a significant amount of people.

**Comment by heinrich5991** [comment]
> we'd need smth like a dropdown, bcs we also use this dialog based on the playing time
> 
>     * dont ever show again
> 
>     * timeout time
> 
>     * always show

Wouldn't need that, it'd be okay with just two options: don't show unless you have a high time, or always show.

**Comment by def-** [comment]
Fixed

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
