### PR TITLE
support arm64 build

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
The following image builds ddnet for aarch64 but it crashes:
```
# WILL BE BACK AFTER DINNER
FROM    arm64v8/ubuntu:20.04
ENV     DEBIAN_FRONTEND=noninteractive
RUN     apt-get update -y && \
        apt-get upgrade -y && \
        apt-get install -y build-essential cmake ninja-build curl wget pkg-config
RUN     curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh -s -- -y
RUN     mkdir -p /ddnet-builder
WORKDIR /ddnet-builder
RUN     wget https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-ucrt-ubuntu-20.04-aarch64.tar.xz && \
        tar xavf llvm-mingw-20240619-ucrt-ubuntu-20.04-aarch64.tar.xz
ENV     PATH=/ddnet-builder/llvm-mingw-20240619-ucrt-ubuntu-20.04-aarch64/bin:/root/.cargo/bin:$PATH
ENV     CC=aarch64-w64-mingw32-clang
ENV     CXX=aarch64-w64-mingw32-clang++
ENV     RC=aarch64-w64-mingw32-windres
ENV     AR=aarch64-w64-mingw32-ar
RUN     rustup target add aarch64-pc-windows-gnullvm
RUN     apt-get install -y git
RUN     git clone https://github.com/SchrodingerZhu/ddnet -b winarm64 --recursive
RUN     apt-get install -y glslang-tools python3
RUN     cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/mingw64-aarch64-llvm.toolchain -DCMAKE_BUILD_TYPE=Release -S ddnet -B build && \
        cmake --build build --parallel
```
I do not have time for further investigation. Could you take over from here? I think the building procedure is clear by now.

**Comment by SchrodingerZhu** [comment]
cc @def-

**Comment by SchrodingerZhu** [comment]
A simple debug indicates that
```
* thread #1, stop reason = Exception 0xc000001d encountered at address 0x7ff79a5f2c74
    frame #0: 0x00007ff79a5f2c74 DDNet.exe`vkEnumerateInstanceLayerProperties
DDNet.exe`vkEnumerateInstanceLayerProperties:
->  0x7ff79a5f2c74 <+0>:                                  ; unknown opcode
    0x7ff79a5f2c78 <+4>: ldnp   s9, s29, [x22, #-0xac]
    0x7ff79a5f2c7c <+8>: adrp   x28, 7963

DDNet.exe`vkEnumeratePhysicalDevices:
    0x7ff79a5f2c80 <+0>:                                  ; unknown opcode
(lldb)
```
So this may be due to VulkanRT I downloaded from https://vulkan.lunarg.com/.

**Comment by SchrodingerZhu** [comment]
Good news is that OpenGL version runs without a problem

**Comment by def-** [comment]
Amazing work!

**Comment by Jupeyy** [comment]
> So this may be due to VulkanRT I downloaded from https://vulkan.lunarg.com/.
> 
> Actually not, because I can run the `MSYS2` compiled binaries with the dependencies from my `ddnet-libs`.

If your computer hardware has a vulkan driver, then you don't need use the vulkan-1.dll from ddnet-libs..

Simply delete it all along.
Since arm64 computers most likely are always come with a vulkan driver, the dependency could be completely dropped.

**Comment by SchrodingerZhu** [comment]
non-cross build works, including vulkan.

**Review by def- — CHANGES_REQUESTED** [review]
All good except the ddnet-libs, I will have to build them myself (doing so now)

**Comment by def-** [comment]
> ERROR: Permission to DDNet-WinArm64/ddnet.git denied to def-.

I'll just push this to my own PR and submit

**Pull request closed without merging**
