### PR TITLE
Disabling quick editing in the console

### LINKED ISSUE #3925: DDNet freezes when going into select mode in the console on Windows
https://www.youtube.com/watch?v=--IRLg3bkao

Apparently you can simply go into select mode, then when DDNet tries prints something, it freezes. If you have DDNet in fullscreen mode, you apparently can't go out of the select mode anymore, in windowed mode the fix works, apparently.

I'd guess that this is done by Windows and that we can't do anything about it.

Any Windows gurus that can chime in? :)

Reported to me by M Emile.

### PR DESCRIPTION
**Pull request by BloodWod-513**
I think it should fix #3925.

Previously, the game stopped due to the fact that it was possible to turn on the selection by a random click, but if you disable the quick edit flags, then the selection can be made only by right-clicking the mouse and selecting an necessery option. 

The game will also stop, but after copying it will immediately continue, and this eliminates accidental pressing, that is, the person is fully responsible for his actions.
console
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Anyone who can verify? I'll ask M Emile on Discord

**Comment by def-** [comment]
Quoting M Emile:

> well
> kinda?
> it still does it if you right-click / Mark
> then highlight
> but you can't highlight easely which kinda makes it hard to do accidentally?
> but the point of the console is to highlight messages so you can ctrl-c them to copy

**Comment by BloodWod-513** [comment]
Now there is no accidental clicking.
1) Right-click, click " mark"
2) Highlight the message
3) Press the keyboard shortcut ctrl+c
After copying or pressing "enter", the work will continue. If you don't press anything, then yes, of course the game will hang, but it made sense to switch to the "mark" mode, this will remove random clicks that you sometimes don't notice and it's annoying

**Comment by def-** [comment]
bors r+
Fair enough, it's a definitive improvement.

**Pull request merged**
