### PR TITLE
Add commands for switching pages in console

### PR DESCRIPTION
**Pull request by ChillerDragon**
For now they were just hardcodet on page up and down keys.
The new command allows it to bind it for example on the f-keys for laptop users.

### CODE REVIEW

**Comment by def-** [comment]
Why would laptop users want to use f-keys?

**Comment by def-** [comment]
Did you remove the old hardcoding?

**Comment by Learath2** [comment]
Doesn't look like he did

**Comment by ChillerDragon** [comment]
Should i remove the old hardcoding? F-keys came to my mind because they work in server browser and menu. I didn't test but i think they can be used in console too. Most other keys in console won't be effective binds because they are seen as inputs to the console i guess.

**Comment by def-** [comment]
Since you are binding them, shouldn't it be handled twice now, once by the hardcoding, once by your bind?

**Comment by ChillerDragon** [comment]
Yes that makes sense but it should defnetly be default binded to page up and down then. Ill have a look at it tomorrow i think.

**Comment by def-** [comment]
But don't you get double page up with your implementation now?

**Comment by ChillerDragon** [comment]
Well the page up key is still binded to page up in console since it is hardcodet. But my new pageup console command isn't binded default so it will probably only used by people without an pageup key on their keyboard. So there is nothing doublebinded. It just keeps everything as comfortable as before for people with numpad extended keyboards but it also adds the possibility for others without this key to use the command manually in console or bind it on f-keys.

**Comment by def-** [comment]
Oh, I see. I thought you added a default bind for it, my bad.

**Pull request merged**
