### PR TITLE
Run MysqlUninit later (fixes #6571)

### LINKED ISSUE #6571: MySQL library not in initialized state
```
2023-05-07 23:31:02 I console: executing 'mysql.cfg'
2023-05-07 23:31:02 I server: Adding new SqlWriteServer: DB: 'teeworlds' Prefix: 'record' User: 'teeworlds' IP: <{}> Port: 3306
2023-05-07 23:31:02 I server: Adding new SqlReadServer: DB: 'teeworlds' Prefix: 'record' User: 'teeworlds' IP: <{}> Port: 3306
2023-05-07 23:31:02 I server: starting...
2023-05-07 23:31:02 I net: failed to bind socket with domain 2 and type 2 (98 'Address already in use')
2023-05-07 23:31:02 I server: couldn't open socket. port 8340 might already be in use
2023-05-07 23:31:02 I assert: /home/teeworlds/src/master/src/engine/server/databases/mysql.cpp(153): MySQL library not in initialized state
```
Seems like when the server can't use the port it ends up with a bad mysql state?

### PR DESCRIPTION
**Pull request by def-**
Otherwise the mysql thread can still be running in the background while we uninitialize it.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by heinrich5991 — APPROVED** [review]
LGTM.

**Comment by def-** [comment]
It's not sufficient unfortunately. We also have to kill the threads, they are still running in the background:
```
thread_init_and_detach(CWorker::Start, new CWorker(m_pShared), "database worker thread");
thread_init_and_detach(CBackup::Start, new CBackup(m_pShared), "database backup worker thread");
```
I'm wondering if this could also cause https://github.com/ddnet/ddnet/issues/6738

**Comment by heinrich5991** [comment]
Another option would be not deinitializing stuff.

**Comment by def-** [comment]
Now I'm even more confused why this crashes:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==6077==ERROR: AddressSanitizer: SEGV on unknown address 0x7f28ba47e910 (pc 0x7f28befaa59b bp 0x7ffef9f45720 sp 0x7ffef9f45680 T0)
==6077==The signal is caused by a READ memory access.
    #0 0x7f28befaa59b  (/lib/x86_64-linux-gnu/libc.so.6+0x9659b) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #1 0x56394f3dc88d in thread_wait(void*) /home/runner/work/ddnet/ddnet/src/base/system.cpp:799:15
    #2 0x56394ec37532 in CDbConnectionPool::~CDbConnectionPool() /home/runner/work/ddnet/ddnet/src/engine/server/databases/connection_pool.cpp:474:3
    #3 0x56394eca297f in CServer::~CServer() /home/runner/work/ddnet/ddnet/src/engine/server/server.cpp:368:2
    #4 0x56394eca2ba5 in CServer::~CServer() /home/runner/work/ddnet/ddnet/src/engine/server/server.cpp:353:1
    #5 0x56394f2ee4a7 in CKernel::~CKernel() /home/runner/work/ddnet/ddnet/src/engine/shared/kernel.cpp:63:5
    #6 0x56394f2ee775 in CKernel::~CKernel() /home/runner/work/ddnet/ddnet/src/engine/shared/kernel.cpp:57:2
    #7 0x56394ec5d106 in main /home/runner/work/ddnet/ddnet/src/engine/server/main.cpp:195:2
    #8 0x7f28bef3dd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #9 0x7f28bef3de3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #10 0x56394eb5e8d4 in _start (/home/runner/work/ddnet/ddnet/DDNet-Server+0x7258d4) (BuildId: 69f811ea100c67e4)
```

**Review by Zwelf — APPROVED** [review]
I don't know if this helps, because the `CMysql` holding the MySQL connections are created only in the thread. The connections aren't shared between threads and are only cleared up `ProcessQueries()` completes.

The change looks better than the current state, because we make sure that we clear up the threads and the change should not harm. Approving.

**Pull request merged**
