### PR TITLE
Bump GTest version so we don't have to patch it anymore

### LINKED ISSUE #3388: Stop patching gtest once they resolve the CMake deprecation issue
See https://github.com/google/googletest/issues/3040. PR exists at https://github.com/google/googletest/pull/3094, but doesn't look like it's going to get merged soon.

CC #3387

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #3388.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Looks like I need to enable C++11 support for GTest specifically.

**Comment by def-** [comment]
Was there a problem with enabling it for all of DDNet?

**Comment by heinrich5991** [comment]
No. We don't enable it "globally" because we're good CMake citizens. ;)

**Comment by def-** [comment]
ah, I see. We have it on in DDNet, but not for the gtest dependency.

**Comment by edg-l** [comment]
I want to see if it works now

bors try

**Comment by edg-l** [comment]
We should update the hash to 0134d73a4902574269ff2e42827f7573d3df08ae probs (current master)

**Comment by Jupeyy** [comment]
bors try

**Comment by Jupeyy** [comment]
> We should update the hash to 0134d73a4902574269ff2e42827f7573d3df08ae probs (current master)

Seems like ubuntu 18 doesnt like such a new version xD

**Pull request merged**
