### PR TITLE
Support 32bit color depth, default to it (fixes #4549)

### LINKED ISSUE #4549: Alt-tabbing takes ages on Windows 10
On a computer of a friend of mine, alt-tabbing takes a long time. This applies to desktop fullscreen and fullscreen.

It seems like Windows changes the resolution back and forth but both DDNet and the desktop are configured to use 1920x1080.

Is this a general Windows problem or do I need to figure out more details?

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Seems to work fine for me, but I had no problem with alt-tabbing

**Comment by heinrich5991** [comment]
My friend tells me that it got better with this. :) Still remains a (smaller) problem.

bors r+

Thanks for the quick fix.

**Comment by Jupeyy** [comment]
The only thing this patch does is, that it adds a bug. There is no code path that will help setting this to 32, but there is a check with this variable for the old selected list element and that fails now

**Comment by fokkonaut** [comment]
@heinrich5991 make sure his resolution is set to desktop resolution.

**Comment by heinrich5991** [comment]
> make sure his resolution is set to desktop resolution.

Yea, that's the case.

**Pull request merged**
