### PR TITLE
sv_server_info_per_second, sv_van_conn_per_second: allow 0 to disable

### PR DESCRIPTION
**Pull request by def-**
Clean up code a bit, also allow larger values

### CODE REVIEW

**Comment by heinrich5991** [comment]
This has a behavioral change. In each accounting interval, it always sends the first n server infos with client information. Before, it didn't if the server was currently under attack. Is this intended? (E.g. to make the code simpler?)

**Comment by def-** [comment]
Yes, I think that behaviour implements the description of the configs more accurately and is also what I would have expected the behaviour to be.

**Comment by heinrich5991** [comment]
Thanks for the PR and the clarification. :)

bors r+

**Comment by heinrich5991** [comment]
Hmmm.

**Pull request merged**
