### PR TITLE
Add Sleepbubble to ClAfkMark

### PR DESCRIPTION
**Pull request by fushi-gg**
With setting cl_afk_mark to 2 you will now get a sleepbubble on afk instead of the mark.

Which option should be default?
Also it displays chatbubble instead of sleepbubble when the playerflag is active. (I don't know which behavior is preferred)
Kept sleepy eyes on afk aswell.

 screenshot_2019-07-29_14-47-34

### CODE REVIEW

**Comment by Ryozuki** [comment]
Imho bubble should be default

**Comment by def-** [comment]
This looks pretty tee-ish

**Comment by fokkonaut** [comment]
We should remove the other option.

**Comment by Learath2** [comment]
@FallenKN if possible can you add screenshot with a lot of people afk?

**Comment by FallenKN** [comment]
@Learath2 
screenshot_2019-07-30_13-52-45

**Comment by def-** [comment]
> We should remove the other option.
Agreed.

**Comment by FallenKN** [comment]
> 
> 
> > We should remove the other option.
> 
> Agreed.

Allright I am going to edit the PR once I find time.

**Pull request merged**
