### PR TITLE
automatically kick k-client

### PR DESCRIPTION
**Pull request by nobody-mb**

### CODE REVIEW

**Comment by BannZay** [comment]
This client will be updated due to this pr which makes things worse tho. Are not better to restrict in other way such client ?

**Comment by heinrich5991** [comment]
It doesn't ban the newest version of the client which does not have cheats AFAIUI.

**Comment by def-** [comment]
For the style use `python scripts/fix_style.py --base HEAD~` in the future :D

**Comment by BannZay** [comment]
> It doesn't ban the newest version of the client which does not have cheats AFAIUI.

Yea, just saying that we will lose tracking of cheaters if client will began masking themselve

**Pull request merged**
