### PR TITLE
Added plus/minus buttons to numeric value selectors in editor

### LINKED ISSUE #7705: New Editor Tool Idea: Resize Map tile Layers
new Tool so u can resize 
Tile layers perfectly +1 height and width (so they dont go endless)

### PR DESCRIPTION
**Pull request by bencie**
changes

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by archimede67** [comment]
I don't think this fixes the mentioned issue. I believe what the author meant to say was that they wanted a way to resize layers without having their tiles touch the layer edges so that the tiles won't be expended to infinity.

**Comment by bencie** [comment]
> I don't think this fixes the mentioned issue. I believe what the author meant to say was that they wanted a way to resize layers without having their tiles touch the layer edges so that the tiles won't be expended to infinity.

You're right, although I think his issue is already fixed with "Shift by", since you could just shift every layer 1 right and 1 down so that no blocks are on the border. My changes are related to Robyt3's comment, where he suggested this exact feature. See https://github.com/ddnet/ddnet/issues/7705#issuecomment-1913147621

**Comment by archimede67** [comment]
> You're right, although I think his issue is already fixed with "Shift by", since you could just shift every layer 1 right and 1 down so that no blocks are on the border. My changes are related to Robyt3's comment, where he suggested this exact feature. See [#7705 (comment)](https://github.com/ddnet/ddnet/issues/7705#issuecomment-1913147621)

Shifting to the right and down does not ensure that the layer will have no blocks on the border as you can still have blocks on the right and bottom border. I think the comment should be extracted as a separate issue.

**Review by Robyt3 — CHANGES_REQUESTED** [review]
I think we can remove `PROPTYPE_INT_SCROLL` and related code entirely and rename `PROPTYPE_INT_STEP` to `PROPTYPE_INT`, since I don't see a use for an integer property that can be adjusted by scrolling but not with plus/minus buttons. Please squash the commit when you are done.

**Review by Robyt3 — APPROVED** [review]
Looks good, please rebase on current master to resolve the conflict.

**Review by Robyt3 — APPROVED** [review]

**Pull request merged**
