### PR TITLE
clang-format entire repo

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
bors r+

Awesome.

**Review by heinrich5991 — APPROVED** [review]

**Comment by heinrich5991** [comment]
It seems like this reformatting missed some files, e.g. src/engine/server/server.h. You can run clang-format with my script from #2927.

**Comment by def-** [comment]
Weird, any idea why find would do fewer files fix_style.py?

Fixed it now and took in your change from #2927

**Comment by heinrich5991** [comment]
Just reviewed the headers.
src/antibot/antibot.h: The enum that is commented out needs some tabs after the // (//<tab>TEAM_SPECTATORS. 
It modifies `src/engine/client/keynames.h` which says that it's autogenerated and should not be edited.
Kinda breaks the comment for SHA256_EXTENSION in src/engine/demo.h, perhaps it could be moved above the declaration.
src/engine/kernel.h has comments with weird indentation after the reformat, maybe just remove `virtual unsigned InterfaceID` and `virtual const char *InterfaceName`.
src/engine/keys.h says it's autogenerated, yet it's modified by clang-format.

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
