### PR TITLE
Remove unused DoFilter

### PR DESCRIPTION
**Pull request by def-**
Thanks to cheeser0613

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Fine by me. We can add it back if we need it or extract the mostly duplicate code for the existing search boxes at some point.

Do you also want to remove the "Search:" text from the language files? We already had "Search" (without the colon) so this was redundant anyway.

**Comment by def-** [comment]
done

**Comment by Robyt3** [comment]
Conflicts

**Comment by def-** [comment]
Resolved

**Pull request merged**
