### PR TITLE
Fix and change text cursor

### LINKED ISSUE #3110: Cursor position in text field overlaps text
@Jupeyy probably caused by your alignment change. can you take a look?
screenshot-20201016@110012

### PR DESCRIPTION
**Pull request by Jupeyy**
Pls check if u like the new cusor and if it works now
fixes #3110

### CODE REVIEW

**Comment by def-** [comment]
No cursor at all now, don't like. It only appears on empty text field.

**Comment by Jupeyy** [comment]
maybe just forgot to clear the texture

**Comment by def-** [comment]
Between the letters it is fine now, start is fine too. at the end it is shown too far right.

**Comment by Jupeyy** [comment]
yes freetype sometimes returns higher char width than the actual advance is, this isnt really fixable sadly:
https://stackoverflow.com/questions/45304838/how-is-it-possible-that-the-horizontaladvance-of-a-glyph-is-smaller-than-the-gly

i'll think about it, maybe i have an idea maybe not

**Comment by Jupeyy** [comment]
I hope this is good enough for now, else we might have to revert the text alignment, because the implementation isnt 100% ready for such things yet

**Comment by def-** [comment]
It's still a bit far right, but fair enough.
bors r+

**Pull request merged**
