### PR TITLE
Hopefully fix execution on Mac by fixing link to SDL

### PR DESCRIPTION
**Pull request by def-**
As reported by zou'
Bildschirmfoto_2021-12-03_um_22 58 32

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
https://ddnet.tw/downloads/DDNet-15.7-test-osx.dmg

**Comment by def-** [comment]
Seems to work better, but something else still fails:
> after a error message i clicked always ignore and the game started but not in fullscreen so i tryed to enter fullscreen and it worked but when i try to click something like settings it always goes back to the left corner and click there

Weirdly enough no issue on Steam.

**Comment by ChillerDragon** [comment]
> https://ddnet.tw/downloads/DDNet-15.7-test-osx.dmg

**macOS Big Sur (11.6)**

Launching in fullscreen or window mode works fine.
Even launching in window mode and then change to fullscreen causes no bugs.
Tabbing out in fullscreen is still a pain but that's another issue I guess. (only way I found to get out of fullscreen is ``minimize`` in local console. But then the screen is black when tabbing back in)

I have to note to I am running on a dev machine that has brew and all the ddnet deps installed.
But since the binary links all relevant libs locally from the app dir that should not matter.

```
% otool -L DDNet 
DDNet:
	/usr/local/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 158.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.51.6)
	@rpath/libfreetype.6.dylib (compatibility version 24.0.0, current version 24.1.0)
	@rpath/SDL2.framework/Versions/A/SDL2 (compatibility version 17.0.0, current version 17.0.0)
	@rpath/libavformat.58.dylib (compatibility version 58.0.0, current version 58.76.100)
	@rpath/libavcodec.58.dylib (compatibility version 58.0.0, current version 58.134.100)
	@rpath/libavutil.56.dylib (compatibility version 56.0.0, current version 56.70.100)
	@rpath/libswscale.5.dylib (compatibility version 5.0.0, current version 5.9.100)
	@rpath/libswresample.3.dylib (compatibility version 3.0.0, current version 3.9.100)
	@rpath/libsteam_api.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	@rpath/discord_game_sdk.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 963.50.8)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1561.40.112)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.23.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.23.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by def-** [comment]
As more people are running into this, I think I should quickly release this as 15.7.1. I guess overwriting 15.7 Mac version with this would not be good style. Thoughts?

**Comment by ChillerDragon** [comment]
> As more people are running into this, I think I should quickly release this as 15.7.1. I guess overwriting 15.7 Mac version with this would not be good style. Thoughts?

Yea also got reports in game that new mac release does not work. What about 15.7.1.1 ? :D

**Comment by def-** [comment]
I went the dirty way and overwrote 15.7 for Mac

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
