### PR TITLE
Add font index, support font family variants depending on language

### LINKED ISSUE #6881: Support using different font family variants depending on user language
https://heistak.github.io/your-code-displays-japanese-wrong/

TL;DR: There are characters (e.g. all in `刃直海角骨入`) that look different depending on the language of the content being Japanese, Simplified Chinese, Traditional Chinese and Hangul, because Unicode uses the same codepoint for characters regardless of the language.

This is how it looks with DDNet client currently on all languages:

- 

Upstream does this correctly already thanks to @TsFreddie (teeworlds/teeworlds#2704), so this is how it looks there:

- Japanese:

- Simplified Chinese:

- Traditional Chinese:

- Hangul:

The idea is to port the "Add multi-font fallback support as well as regional variant switching" changes from upstream including the font index file.

The index is a json file looking like this:

```json
{
    "font files": [
        "DejaVuSans.ttf",
        "SourceHanSans.ttc"
    ],
    "default": "DejaVu Sans",
    "language variants": {
        "japanese": "Source Han Sans",
        "korean": "Source Han Sans K",
        "simplified_chinese": "Source Han Sans SC", 
        "traditional_chinese": "Source Han Sans TC"
    },
    "fallbacks": [
        "Source Han Sans"
    ]
}
```

We would also add another entry for the icon font.

Looks like upstream uses Source Han Sans for all CJK languages, whereas we currently use Glow Sans Compressed for Japanese and Source Han Sans for Simplified Chinese.

### PR DESCRIPTION
**Pull request by Robyt3**
Add `fonts/index.json` which specifies:

- List of all font files that should be loaded (filenames).
- Default font (specified by family name or by family and style name).
- Font variants for different languages, using the name of the language file as key.
- Fallback fonts.
- Icon font.

There are characters (e.g. all in `刃直海角骨入`) that look different depending on the language of the content being Japanese, Simplified Chinese, Traditional Chinese and Hangul, because Unicode uses the same codepoint for characters regardless of the language. To render these characters correctly, the active variant font is switched depending on the selected language.

The `ITextRender` interface is changed so the current language variant can be set using `SetFontLanguageVariant` and the default and icon fonts can be toggled using `SetFontPreset`. The class `CFont` is removed entirely.

The text render is restructured: The font faces and font atlas are now managed by a separate class `CGlyphMap` like on upstream. As the text fill and outline textures always have the same size, the texture skyline only needs to be stored once and free positions in the atlas only need to be calculated once for each glyph instead of separately for the fill and outline textures.

The font files and their licenses are also updated:

- Update Source Han Sans to version 2.001.
- Update Glow Sans Japanese Compressed to version 0.93.
- Update Deja Vu Sans to version 2.37.
- Update Font Awesome icons font to March 2023 version.

Closes #6881.

Screenshots:
- English selected: 
en
- Japanese selected:
jp
- Simplified Chinese selected:
chinese simplified
- Traditional Chinese selected:
chinese traditional
- Korean selected:
korean

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [X] Tested in combination with possibly related configuration options (client language)
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [X] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
I'm not able to review any time soon. But the license file seems to be missing

**Comment by Robyt3** [comment]
The licenses for the fonts are included in the license.txt, I'll take a look at that file though, since it seems outdated.

**Comment by edg-l** [comment]
looked a bit over it and looks good to me, also tested in game

**Comment by edg-l** [comment]
image

found this, idk if its related, but the bg doesnt match the text width

**Comment by Robyt3** [comment]
> found this, idk if its related, but the bg doesnt match the text width

Thanks, fixed.

**Pull request merged**
