### PR TITLE
Add missing includes

### PR DESCRIPTION
**Pull request by ChillerDragon**
Some header files were using types that depend on includes but those files were not included. This practically works during the compile process because they are included in the right order. But is theoretically bad style. It can cause unexpected compile errors on reordering includes. It breaks IDE environments (neovim + clangd for example). Also those missing includes break https://github.com/ddnet/ddnet/pull/8151.

```
$ clang-tidy src/game/client/components/emoticon.h -p build-camel/
410 warnings and 2 errors generated.
Error while processing /home/chiller/Desktop/git/ddnet/src/game/client/components/emoticon.h.
/home/chiller/Desktop/git/ddnet/src/game/client/components/emoticon.h:17:29: error: incomplete type 'IConsole' named in nested name specifier [clang-diagnostic-error]
   17 |         static void ConKeyEmoticon(IConsole::IResult *pResult, void *pUserData);
      |                                    ^~~~~~~~~~
/home/chiller/Desktop/git/ddnet/src/game/client/component.h:72:8: note: forward declaration of 'IConsole'
   72 |         class IConsole *Console() const;
      |               ^
/home/chiller/Desktop/git/ddnet/src/game/client/components/emoticon.h:18:23: error: incomplete type 'IConsole' named in nested name specifier [clang-diagnostic-error]
   18 |         static void ConEmote(IConsole::IResult *pResult, void *pUserData);
      |                              ^~~~~~~~~~
/home/chiller/Desktop/git/ddnet/src/game/client/component.h:72:8: note: forward declaration of 'IConsole'
   72 |         class IConsole *Console() const;
      |               ^
```

image

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by heinrich5991** [comment]
Do you have an idea how we could check this in CI?

**Comment by Robyt3** [comment]
> Do you have an idea how we could check this in CI?

Maybe with [Include What You Use](https://github.com/include-what-you-use/include-what-you-use), but the number of false positive might be quite high. I've only used the tool manually in #5276 and #5450.

**Comment by ChillerDragon** [comment]
> Do you have an idea how we could check this in CI?

It will be checked by clang tidy if https://github.com/ddnet/ddnet/pull/8151 is merged

**Comment by heinrich5991** [comment]
> > Do you have an idea how we could check this in CI?
> 
> It will be checked by clang tidy if #8151 is merged

That sounds great. :)

**Comment by ChillerDragon** [comment]
> > Do you have an idea how we could check this in CI?
> 
> It will be checked by clang tidy if #8151 is merged

That is no longer true. Since https://github.com/ddnet/ddnet/pull/8151 does no longer run clang tidy on individual files.
But I am sure we can activate some option in the .clang-tidy for exactly that.

**Pull request merged**
