### PR TITLE
Version 16.1

### PR DESCRIPTION
**Pull request by def-**
DDNet 16.1 is supposed to release in 1 week, assuming no bad bugs are found. Please test the Release Candidate to prevent problems being only discovered after release. Report bugs in the #bugs channel on DDNet Discord or directly on Github:

- Windows 32bit: https://ddnet.tw/downloads/DDNet-16.1-rc2-win32.zip
- Windows 64bit: https://ddnet.tw/downloads/DDNet-16.1-rc2-win64.zip
- Linux x86: https://ddnet.tw/downloads/DDNet-16.1-rc2-linux_x86.tar.xz
- Linux x86_64: https://ddnet.tw/downloads/DDNet-16.1-rc2-linux_x86_64.tar.xz
- Mac OS X: https://ddnet.tw/downloads/DDNet-16.1-rc2-macos.dmg

You can also test the release candidate in Steam by clicking on Settings -> Properties -> Betas and opting into the Release Candidates. This will automatically update you to a new release candidate when it is available, and to the next release when no new candidate is available. So you can always leave this setting enabled to help us test new releases earlier.
shields
167973498-bccaac07-756e-4e59-a19d-66d3e24542d0

The following changes are included, ideally test their behaviour specifically. But just playing as you do normally also helps:
- [Client] **Add option to change default eyes when joining server** [sjrc6]
- [Client] **Tooltips to explain some settings** [Ryozuki]
- [Server] **Enable swapping in team 0**
- [Server] **Shields that take away specific weapons** [Jupeyy, Cellegen, Konsti]
- [Client+Server] **Unify logging infrastructure so that F1 shows all** [heinrich5991]
- [Client+Server] **Switch new players to DDNet config dir, support Teeworlds as fallback**
- [Client] Adjustable hook collision line alpha [sjrc6]
- [Client] Fix whisper sending/receiving differentiation [srdante]
- [Client] Respect GPU type better [Jupeyy]
- [Client] Better forced viewport handling (Vulkan) [Jupeyy]
- [Client] Fix Vulkan on dual core CPUs [Jupeyy]
- [Client] Allow onfly FSAA change under Vulkan [Jupeyy]
- [Client] Display super with "super" string in scoreboard
- [Client] Unselect text after ctrl-u
- [Client] Fix wrong quad offset for (not caused by transparent) flushes (Vulkan, OpenGL 3.3) [Jupeyy]
- [Client] Improve demo slice popup, minor refactoring of UI/menus [Robyt3]
- [Client] Fix flashing colors in console when scrolling up continuously [Robyt3]
- [Client] Remove cl_predict_ddrace [c0d3d3v]
- [Client] Remove cl_show_quads standard bind
- [Client] Ignore F5 key press when ingame menu is open
- [Client] Fix pistol sounds for BW servers [Nouaa]
- [Client] Allow freecam to center on world border [c0d3d3v]
- [Client] Fix local hookline direction when mouse is exactly centerered [sjrc6]
- [Client] Fix ghost color [c0d3d3v]
- [Client] Check if the resolution is "really" not supported before applying desktop resolution [Jupeyy]
- [Client] Try default opengl settings first, when vulkan fails [Jupeyy]
- [Editor] Fix editor animation offset time being affected by the animation speed factor [Jupeyy]
- [Editor] Ctrl+Right click tile to select layer [ChillerDragon]
- [Server] Do not release the hooks if you swap [c0d3d3v]
- [Server] Fix /top5 inconvenience / local ranking problem [srdante]
- [Server] Fix SQL duplicated top and player team top 5 [srdante]
- [Server] Fix websocket crash on client connect [srdante]
- [Server] Fix angle calculation for 0.7 clients [c0d3d3v]
- [Server] Make super ignore livefreeze [Ryozuki]
- [Server] Don't allow infinite shotgun bounce
- [Server] Allow sv_show_others_default in map settings
- [Server] Continuously test MySQL too instead of just MariaDB

### CODE REVIEW

**Comment by murpii** [comment]
Are the 2 bench demos used for anything? (found in install dir/demos)

**Comment by def-** [comment]
Oops, they should not have been added.

**Comment by murpii** [comment]
The main menu music is OFF by default, not sure if that's intended.

**Comment by def-** [comment]
Has been like that since 2014: https://github.com/ddnet/ddnet/commit/096caff08cb7fa7775875ad9d634bbc82161c1d1

**Comment by murpii** [comment]
Traditional Chinese is missing a flag icon in Language Tab

**Comment by murpii** [comment]
> Has been like that since 2014: [096caff](https://github.com/ddnet/ddnet/commit/096caff08cb7fa7775875ad9d634bbc82161c1d1)

Ah I see. Should we maybe turn it back on to get rid of the sheer silence in the main menu? ^^

**Comment by C0D3D3V** [comment]
If we would make it default, we should not make it as loud as in  teeworlds. xD For me that is way to loud.

**Comment by murpii** [comment]
> If we would make it default, we should not make it as loud as in teeworlds. xD For me that is way to loud.

Yep ^^ but this shouldn't be a problem, thanks to #4567

**Comment by def-** [comment]
> Ah I see. Should we maybe turn it back on to get rid of the sheer silence in the main menu? ^^

I'm against it. Also, doesn't seem like it belongs in this topic, since it's not a new 16.1 bug.

> Traditional Chinese is missing a flag icon in Language Tab

This was done after some vocal mainland Chinese kept screaming on Steam about us having a Taiwanese flag. Also not new in this version.

**Comment by murpii** [comment]
> > Ah I see. Should we maybe turn it back on to get rid of the sheer silence in the main menu? ^^
> 
> I'm against it. Also, doesn't seem like it belongs in this topic, since it's not a new 16.1 bug.
> 
> > Traditional Chinese is missing a flag icon in Language Tab
> 
> This was done after some vocal mainland Chinese kept screaming on Steam about us having a Taiwanese flag. Also not new in this version.

I see, yeah im just listing things arbitrarily. If I find anything else, i'll open a issue instead

**Pull request closed without merging**
