### PR TITLE
Automatically store map configs in maps, add tools for storing and retrieving these configs

### PR DESCRIPTION
**Pull request by heinrich5991**
See also #235.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Will rebase if requested.

**Comment by def-** [comment]
I like it so far. config_retrieve can't open any maps for me. Am I using it in a wrong way?

**Comment by heinrich5991** [comment]
@def- The config used is always `<mapname>.cfg`. I wonder why `config_retrieve` didn't work, though.

**Comment by def-** [comment]
I think you missed my edit:

> Edit: tune_dump, tune_reset, tune_zone_dump, tune_zone_reset should probably not be map settings.

Can you rebase?

**Comment by def-** [comment]
config_store does not seem to work anymore at all. I get a 36 byte sized map as a result.

**Comment by def-** [comment]
Something is seriously broken:

1. download the official Kobra 4 map and config
2. put them together with `./config_store Kobra\ 4.map`
3. open this map in the editor, map config is fine
4. save it and load again, map config is broken

**Comment by def-** [comment]
Looks good to me now, thanks for the great work! Maybe I'll find more problems when running it on official servers.

**Pull request merged**
