### PR TITLE
Fix whispering to players with quotes (fixes #2151)

### LINKED ISSUE #2151: Can't whisper to players with quotes at beginning and end of name (eg. "nameless")
SP | Someone (aka Zombietoad) found this bug.
Given a player with the name "nameless" (including quotes!):
`/w "nameless" test`
doesn't work. it gives some error about player not found, I forget

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by fokkonaut** [comment]
Did not work for me

**Comment by def-** [comment]
Tested with name `"nameless tee"`. Works with:

```
/w "\"nameless tee\"" hi
```

**Comment by fokkonaut** [comment]
Oh, yes I didnt write it with the backslashes.

**Comment by heinrich5991** [comment]
@fokkonaut Then you have to escape even more.

Failure looks spurious.

bors r+

Thanks.

**Comment by heinrich5991** [comment]
bors retry

**Pull request merged**
