### PR TITLE
Use nullptr in generated and editor

### PR DESCRIPTION
**Pull request by ChillerDragon**
There is currently `0`, `0x0`, `NULL` and `nullptr` mixed in the code.

The flag `-Wzero-as-null-pointer-constant` suggests to use `nullptr`. It is in a zillion places so I started with the editor.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
Use regexp to fix this everywhere in the code ;)

**Comment by ChillerDragon** [comment]
> Use regexp to fix this everywhere in the code ;)

Well I used `-Wzero-as-null-pointer-constant` to find it. One could use some proper regex to auto fix it. But I can tell you my buggy regex would be more error prone than doing it manually.

**Comment by Chairn** [comment]
Something like `sed -i 's/\(m_p\w\+\s*\)=\s*\(0\|0x0\|NULL\);/\1 = nullptr;/g' **/*.cpp **/*.h` is what i would use for = assignment. You can adjust for parenthesis initialization.

**Comment by Chairn** [comment]
Well, incidentally, it does find some wrong naming :D

**Comment by heinrich5991** [comment]
LGTM. Can you squash the commits?

**Comment by Learath2** [comment]
> Something like `sed -i 's/\(m_p\w\+\s*\)=\s*\(0\|0x0\|NULL\);/\1 = nullptr;/g' **/*.cpp **/*.h` is what i would use for = assignment. You can adjust for parenthesis initialization.

Parsing C++ with a regex (FSA) is a bad bad idea given C++ syntax isn't context free. If we want to do this throughout the code we definitely want clang to handle this.

**Comment by ChillerDragon** [comment]
> Something like `sed -i 's/\(m_p\w\+\s*\)=\s*\(0\|0x0\|NULL\);/\1 = nullptr;/g' **/*.cpp **/*.h` is what i would use for = assignment. You can adjust for parenthesis initialization.

Didn't test but looks to me like it would confuse an `0` assignment of a dereferenced integer.

`*m_pMyInt = 0`

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by Chairn** [comment]
> > Something like `sed -i 's/\(m_p\w\+\s*\)=\s*\(0\|0x0\|NULL\);/\1 = nullptr;/g' **/*.cpp **/*.h` is what i would use for = assignment. You can adjust for parenthesis initialization.
> 
> Didn't test but looks to me like it would confuse an `0` assignment of a dereferenced integer.
> 
> `*m_pMyInt = 0`

this would fail at compile, you can't assign nullptr to a non pointer type.

**Pull request merged**
