### PR TITLE
Fix client crash when server does not send gameinfo

### PR DESCRIPTION
**Pull request by Robyt3**
As reported by @ChillerDragon on Discord.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
It was just a assumption. Did you verify that the server can actually crash the client?

**Comment by Robyt3** [comment]
Yes, I modified the server to never send any gameinfo and it crashes the client on exactly that line.

**Comment by ChillerDragon** [comment]
> Yes, I modified the server to never send any gameinfo and it crashes the client on exactly that line.

Ah nice. Good job hackerman!

**Comment by ChillerDragon** [comment]
bors +r

**Pull request merged**
