### PR TITLE
Reset relative mouse motion on toggle

### PR DESCRIPTION
**Pull request by Jupeyy**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Can you explain, best in the commit/PR description, what this does? What problem does it fix? What behavior will be different afterwards?

**Comment by Jupeyy** [comment]
It just resets the relative mouse motion, which happens in #bugs
Doesn't change anything

**Comment by Jupeyy** [comment]
E.g. returning from f1 toggles MouseModeRelative, just as alt+tab (focusing in) does

**Comment by Jupeyy** [comment]
Just looked at git blame, it even was me who broke it, when i tried to fix relative mouse mode with windowed fullscreen mode, probably bcs the description was irritating

**Pull request merged**
