### PR TITLE
chore(Gitignore): add ignore all folders cmake-build-* for Clion

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by edg-l** [comment]
This is fine to add, but please put it in alphabetical order (within the ide section).

Thanks!

**Comment by heinrich5991** [comment]
Sorry that I changed `cmake-build-*/*` to `cmake-build-*` without asking you.

Is there any particular reason that you prefer the `/*`? Both should ignore the whole folder. Many other items in the list are also folders, so it'd be weird to use `/*` if there's no particular reason.

**Comment by IntelligentQuantum** [comment]
With cmake-build-* you cant see build folder in the ide

**Comment by heinrich5991** [comment]
> With cmake-build-* you cant see build folder in the ide

I see. Weird that CLion interprets .gitignore files differently from git itself. I squashed your commits again.

**Pull request merged**
