### PR TITLE
added entities clear for other gametypes

### PR DESCRIPTION
**Pull request by timakro**

### CODE REVIEW

**Comment by def-** [comment]
This looks like a bad idea. Now if you want to edit some tile, you need to edit not 4 files, but 7 instead. What's the benefit of this?

**Comment by timakro** [comment]
You can see proper openfng and race entities and you cant see tiles that are unused in the gametype your playing but used on ddnet servers.

**Comment by def-** [comment]
Are these useless tiles on common openfng or race maps?

**Comment by Soreu** [comment]
Wait with eventual merge, I will be editing these entities today/tomorrow

**Comment by timakro** [comment]
"Are these useless tiles on common openfng or race maps?"
No

**Comment by def-** [comment]
So nothing will visually change by this PR from what I can tell.

**Comment by timakro** [comment]
Ofcourse something will change, you will be able to play race and openfng with entities.

**Comment by def-** [comment]
How are you unable to do this now?

**Comment by timakro** [comment]
I don't want to replace my entities clear just for playing two rounds of openfng.

**Comment by def-** [comment]
Ah, you actually changed something in the fng.png, all the others are subsets of the DDNet one I thought.

**Comment by timakro** [comment]
Maybe compiling subsets together at compile time using bam.lua to call a script could be an option. The script could additionally generate a c++ file which contains data about which gametype uses which tiles so unused tiles could be removed clientside for supported gametypes.

Overcomplicated or a good idea?

**Comment by def-** [comment]
I thought about something similar, but seems too complicated to be practical.

**Comment by Soreu** [comment]
https://forum.ddnet.tw/viewtopic.php?f=93&t=3534&p=37272#p37272

**Comment by timakro** [comment]
Soreu improved the entities for all gametypes. Can be merged because Soreu has no problem with changing more files when updating a tile and he did almost every change to the entities over the last time.

**Comment by def-** [comment]
Thanks timakro, Soreu.

**Pull request merged**
