### PR TITLE
Display super with "super" string in scoreboard (fixes #4724)

### LINKED ISSUE #4724: Super players are now in team 64
@def- i think while you added a proper super prediction (which would have been better possible with DDNetCharacter::m_Super) you forgot to not set TEAM_SUPER players into team 64, lol.

Why didnt you update your commit using the DDNetCharacter's m_Super, then there would also not be any issue with team highlighting, since I said that before on Discord.

### PR DESCRIPTION
**Pull request by def-**
instead of showing the number 64

Alternative to https://github.com/ddnet/ddnet/pull/4725

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
I dont like this. The team should stay in my opinion. That would have been my chance to make colored nameplates :D

Away from that, I dont like it either because its weird displaying thode in a separate team.

**Comment by heinrich5991** [comment]
Sounds good to me. Needs rebase.

**Comment by def-** [comment]
Done

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
