### PR TITLE
Send serverinfo when client joins

### PR DESCRIPTION
**Pull request by def-**
for GER3

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
Maybe put it in an else?

**Comment by def-** [comment]
screenshot-20220918@130937
With the legacy serverinfo looks ugly, will try EXTENDED now.

**Comment by def-** [comment]
screenshot-20220918@131824
Better now

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
