### PR TITLE
Add option to disable whispers

### PR DESCRIPTION
**Pull request by def-**
Since it's easy to abuse and impossible to moderate

Partially solves https://github.com/ddnet/ddnet/issues/8364

Screenshot 2024-08-13 at 13 35 37

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Needs some feedback on the other side, I'd say. Otherwise your messages will go into the void and you won't even notice it.

**Comment by sjrc6** [comment]
Could have 3 levels
0: whispers not blocked
1: replaced with "Whisper blocked from $user$"
2: no message at all

**Comment by jxsl13** [comment]
when it's a server side feature, it should be more of a message like: "whispering is disabled on this server".

When it's a client telling the server that they don't want to receive any whispers, I'd go with Tater's suggestion, except for point 1. where it should tell the person sending the whisper that the receiver opted out of whispering, otherwise you could annoy the person not wanting any whispering messages with those "blocked from" server messages.

In regard to point 2, some special kind of trolls should not know that you opted out of whispering.

**Comment by jxsl13** [comment]
The feature itself would not be abusable but the troll would seek other means to annoy you.

**Comment by murpii** [comment]
> In regard to point 2, some special kind of trolls should not know that you opted out of whispering.

This is poor game design. What if I'm not a troll and just want to say hi to someone via whisper, but they never receive my message because they at some point forgot to change this setting? (Just an example)

**Comment by heinrich5991** [comment]
Duplicate of #8368 btw.

**Comment by jxsl13** [comment]
It's a tradeoff in the end.
The setting disables itself by leaving the server, as it is bound to the current server and is not a client setting.

**Comment by murpii** [comment]
> The setting disables itself by leaving the server, as it is bound to the current server and is not a client setting. Especially when IPs are involved, it is not a client setting.

My point still stands. Some people spend multiple hours on one map. With this kind of behaviour I would stop trusting the whisper system altogether because I might be left in the dark.

**Comment by jxsl13** [comment]
Make sense.
It was meant to be a last resort if needed.
I don't know how toxic the players can become on ddrace, so it might definitly make sense to keep the part with "no feedback about whether my message reached the recipient or not" out in the first iteration and see whether there will be at all a need for having another level of protecting oneself from really annoying people in order to leisurely play the game, assuming that that does give "more" protection.

**Comment by Draggoryy** [comment]
> The feature itself would not be abusable but with that information the troll would seek other means to annoy you.

Forcing the troll to find other means to annoy you is beneficial in it's own way no? It requires them to use more public methods, I.E saying it in all chat or actively blocking them, which then allows for reports to be made easier. Granted, these more public methods are probably more annoying than just getting whispered in some cases, so it's not a perfect solution.

**Comment by BlaiZephyr** [comment]
Stepfunn initially requested that as a way to open up Chat while streaming without having to worry about penalties on His platform because some people seek Attention through verbal abuse iirc. A way to indicate the Person whispering that the message won't go through seems fine, If they fallback to all Chat moderator's can do their magic. How about adding a small Icon or Server Message every X Minutes within the Chat so you can Tell If you have dnd/whispers on/Off ?

**Comment by jxsl13** [comment]
Great points.

In a stream sniping scenario, the additional feature to not inform the person trying to whisper would be completely pointless.

In regard to public trolling or not, it comes down to moderator response times and the intention of the person who blocks another player from sending them whisper messages.

In case that you want that public scenario in order for a moderator to step in, then it would indeed nit make sense, at least when a moderator is present, to actually, let's call it shadowmute (w/o giving them feedback) the other player./.

If you want to just ignore the troll and keep on playing or give the troll the impression that he's being ignored. Maybe the troll might even stop trolling due to no response, who knows.

In case that a moderator is not present, it could make sense to shadow mute the troll and inform a moderator in the mean time. In that case it would take the troll some time to realize that he's been whisper muted. Only them he would take that trolling to the public chat.

In case that there is no moderation, I'd guess that short term you would have silence but after some time the troll would take that to the public chat anyway, in which case it would be even better to have the troll earlier in the public chat than later, in order for the other players to kickvote him.

In total it's definitly becoming less and less of an increased protection to none at all.

:+1:

**Comment by heinrich5991** [comment]
Needs feedback to the sender, otherwise it'd make the whisper feature too unreliable to be useful.

**Comment by def-** [comment]
Disagree strongly. If the sender gets feedback, then they will find another way to harass their victim.

**Comment by heinrich5991** [comment]
So the problem is that we have two problems that we want to solve:

1) The legitimate player who wants to whisper someone wants to be informed that the whisper message did not arrive. Otherwise they can't know that the other player isn't ignoring them deliberately. People would get used to not sending whispers instead, making the whisper feature useless. We could entirely remove the whisper feature instead, I guess.
2) The spammer/troll who wants to annoy someone by whispering. They shouldn't be informed of the failed whisper because they'd use another method to annoy the victim. If it's known that the player ignores whispers, this defense wouldn't help, the troll would immediately go for a different method.

1 and 2 are in direct conflict. I believe we cannot implement 2 without making the whisper feature essentially useless. Hence I don't think 2 is the way forward.

What do you think about this conflict, @def-?

**Comment by def-** [comment]
2 is way more important than 1 since players are harassed and they have no way of stopping it.

If someone happens to have whispers disabled (how would they even find out how to do that?), you can still ask them in a normal message if they have seen your whispers, so 1 is easy to solve manually.

**Comment by heinrich5991** [comment]
> 2 is way more important than 1 since players are harassed and they have no way of stopping it.

I don't think enabling "no whispers" will stop the harassment. As you already noted, it can simply move to public chat. To silence a single harasser, you can also mute them directly, whereas a "no whispers" option disables whispers from all players.

**Comment by def-** [comment]
But they might think their whispers are not arriving. We need an escape hatch for this since we can't moderate whispers.

**Comment by heinrich5991** [comment]
> We need an escape hatch for this since we can't moderate whispers.

The "whispers are disabled but the sender gets a message" provides such an escape hatch. It forces all communication to go through public channels. Furthermore, it doesn't hurt people who just want to communicate with a person.

**Comment by def-** [comment]
Fine, reimplemented server-side

**Review by heinrich5991 — APPROVED** [review]
Thanks.

**Pull request merged**
