### PR TITLE
Switch to C++20, convert some enums to static const variables

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
This might be a little too soon. How is the compiler support for C++20 now? Does our oldest desired distro ship a recent enough gcc/clang?

**Comment by def-** [comment]
That's what this PR is for, to test it. So far I noticed gcc on Ubuntu 20.04 doesn't supported designated initializer syntax, and cmake on Debian 9 doesn't know CXX20:
```
  Target "crapnet" requires the language dialect "CXX20" , but CMake does not
  know the compile flags to use to enable it.
```
Rest seems to work.

**Comment by Kaffeine** [comment]
The source code changes are totally backward compatible. I'd suggest to merge the code changes and keep CMake files intact (do not set/require the standard version 20).

**Comment by Kaffeine** [comment]
Hello, @def-. What was the reason to close this MR? What's wrong with changing enums to static const variables? I see you had to put workaround like https://github.com/ddnet/ddnet/commit/4c8e33ee8ea98e8c61d46887adfc71bcdb59aee0.

You don't have to activate C++20 to use static const vars.

**Comment by Kaffeine** [comment]
`static const` variables are decades old. We don't have too pull all or any C++20 features to use them. Particularly it is not clear why designated initializers are needed for that but still maybe I misread or miss something.

**Pull request closed without merging**
