### PR TITLE
Don't render fully transparent quads

### PR DESCRIPTION
**Pull request by Jupeyy**
@def- i mean u could test the fps diff, its quite huge
and if u really only have 50fps, others will only have 30fps xd

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Makes a giant difference, can easily reach 150-200 fps now. Thanks for the quick reaction!
bors r+

**Comment by Jupeyy** [comment]
I changed it to only for non gl 3.3 for now tho, i'll give it a different try some day

**Comment by Jupeyy** [comment]
@def- i guess this should do the trick :D

**Comment by def-** [comment]
bors r+
Seems to work.

**Pull request merged**
