### PR TITLE
Allow PaladiN skin to use custom colors

### PR DESCRIPTION
**Pull request by d3fault**
Hey @def- what png optimizer did you use? The ones I tried either didn't get the file as small as yours, or mucked up the transparency :(. Feel free to optimize and push to my branch (but I'm still kinda curious which one you used)

### CODE REVIEW

**Comment by def-** [comment]
I didn't optimize the skins. You might need to run the file through dilate after optimizing it.

**Comment by heinrich5991** [comment]
What did you change?

**Comment by d3fault** [comment]
@def- 847b6f3 - Optimize PNGs
what's dilate? I'm on Debian Linux (Jessie). I used max png compression in GIMP and then used "optipng" (also tried pngcrush), but the filesize before was ~3k whereas now it's ~5k :(. I also tried some online png optimizer sites that brought it down to ~3k, but they all mucked the transparency :(.

@heinrich5991 I gave it a tiny bit of color. Not even noticeable to human eye. Apparently if the skin is true black then it ignores custom colors. imo tbh this gives users of PaladiN skin an advantage in team modes like CTF/TDM/FNG ("is that guy on my team or the enemy team?"), but that's not why I did this change (ddrace is lyfe).

**Comment by def-** [comment]
I used zopflipng -m
PaladiN

**Pull request merged**
