### PR TITLE
Use borderless by default on Mac (fixes #2632)

### LINKED ISSUE #2632: Fullscreen is completely broken on macOS
Thus our new default is broken on macOS. There is an SDL/GL issue on macOS that causes the initial values determined for screen width and height to be wrong, causing broken ui clipping. The fix would be to react on window size changes (`SDL_WINDOWEVENT_SIZE_CHANGED`) properly to set the size of the viewport correctly after start.

Something similar to https://github.com/Learath2/teeworlds/commit/7f594afc9be9b402263f18f866a8b59abb08cbe1

### PR DESCRIPTION
**Pull request by def-**
Proper fix would be https://github.com/Learath2/teeworlds/commit/7f594afc9be9b402263f18f866a8b59abb08cbe1

Would be great if someone could provide and test it.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Cannot test, don't have macOS.

**Comment by Learath2** [comment]
I need a crossbuilt version to test

**Comment by heinrich5991** [comment]
The (non-cross-built) version from CI doesn't work?

**Comment by Learath2** [comment]
I didn't try, but it probably can't. It's also built on Catalina

**Comment by def-** [comment]
What's there to test here? This changes the default, nothing else.

**Comment by def-** [comment]
I think I'll just include this in the build because otherwise we are totally broken on Mac right now.

**Pull request merged**
