### PR TITLE
Better indikator4 fail

### PR DESCRIPTION
**Pull request by danielkempf**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
oh god, another PR that will mess up my beautiful logs...

Can you please reopen the PR, force push a single commit (from ddnet/master to danielkempf/betterIndikator4Fail) and then close it again?

**Comment by Chairn** [comment]
To avoid this kind of logs:
image

**Comment by danielkempf** [comment]
Yea i reopen it and done a commit :)

**Comment by Chairn** [comment]
Seems like it didn't erase previous commits

**Comment by def-** [comment]
@Chairn Why do you care about the logs of branches we don't merge anyway? Seems weird.

**Comment by Chairn** [comment]
I use this as config for some repo which fetches all the PRs:
```
[remote "origin"]
    url = https://github.com/ddnet/ddnet.git
    fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
    fetch = +refs/heads/*:refs/remotes/origin/*
```
So then this kind of PR messes up logs

**Comment by def-** [comment]
Just don't look at branches which have not been merged into master?

**Pull request closed without merging**
