### PR TITLE
Consider as not-afk on emoticon, chat, vote,

### PR DESCRIPTION
**Pull request by def-**
call vote, spectator mode, info change

### CODE REVIEW

**Comment by Jupeyy** [comment]
do we really want this?
when i spec someone i chat and spam emotes sometimes

**Comment by def-** [comment]
I guess it depends on what you want to consider afk for. If you're actively watching someone on the server you are capable of voting. But if someone expects you to react to you, it's not. Do we want to split up the meanings? I think that would cause some confusion too. I'm honestly not sure what the best way is.

**Comment by Jupeyy** [comment]
Yeah not sure either, but splitting sounds good too.
I mean the eyes look different when specing, but if you spec for a longer time it might be consfusing tho

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
