### PR TITLE
Add man pages with asciidoc

### LINKED ISSUE #1240: Improve manpage
Debian has a simple manpage for DDNet and DDNet-Server, it should be improved and added to this repo:

https://salsa.debian.org/yangfl-guest/ddnet/blob/master/debian/DDNet.6
https://salsa.debian.org/yangfl-guest/ddnet/blob/master/debian/DDNet-Server.6

### PR DESCRIPTION
**Pull request by Ryozuki**
Fixes #1240 

I added a simple script to generate the man pages.

To edit the man pages in the future, you must edit the `.adoc` files and then run generate.sh

You need asciidoc package to generate the manpages.

`sudo apt install asciidoc`

http://asciidoc.org/

Writing plain troff is a pain in the ass.

### CODE REVIEW

**Comment by def-** [comment]
Are they the same as in the Debian/Ubuntu version or improved ones?

**Comment by def-** [comment]
What about CMake integration, how should that work? (not sure how it's usually done)

**Comment by def-** [comment]
Also, would the man page be the proper place for https://ddnet.tw/settingscommands/ ? Generated with https://github.com/ddnet/ddnet-scripts/tree/master/client

**Comment by Ryozuki** [comment]
I am not super good with cmake, but i guess one could make a custom target to generate the man pages, i could only find this reference: https://github.com/KiCad/kicad-doc/blob/master/CMakeModules/AsciidocHelpers.cmake

Basically you have to use the a2x tool.

I don't know either if we should add settings and commands to the man pages, should we?
I still haven't found a game with manpages for reference.

**Comment by def-** [comment]
Thanks!
bors r+

**Pull request merged**
