### PR TITLE
Render tees in skin selector with default emote

### PR DESCRIPTION
**Pull request by sjrc6**
suggested in https://github.com/ddnet/ddnet/issues/5057
works for player and dummy

image

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Cool, I like it

**Comment by C0D3D3V** [comment]
grafik

I like it too.
But could you please use the Variable you already defined in Line 590? It is exactly the same just a different name `Emote` 
https://github.com/ddnet/ddnet/blob/8f00e9558b3bf74545d91ad6ef4b4b7a6cc8eebd/src/game/client/components/menus_settings.cpp#L590

**Comment by sjrc6** [comment]
oops lol

**Comment by sjrc6** [comment]
why does ubuntu build fail? did I break something?

**Comment by def-** [comment]
Looks unrelated.
bors r+

**Pull request merged**
