### PR TITLE
fix FindMySQL not finding mysql under NixOS

### PR DESCRIPTION
**Pull request by BlaiZephyr**
the FindMySQL.cmake file is completly broken if used with nix/NixOS and it's way of declaring packages and libraries within the /nix/store

this has been tested on NixOS and Arch-linux on x86_64-linux. AFAIK this has been broken on windows before, so this would require someone to actually test this please.
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — COMMENTED** [review]
It seems a bit weird to me that you need to explicitly list /nix/store. How does it work for other libs?

**Comment by BlaiZephyr** [comment]
i debugged this by adding outputs to every path it looks into and found out while it properly finds the client (e.g libmysqlclient.so) - it has trouble finding the headers. 

if i let cmake recursively look through the entire nix/store it finds the includes under the mysql package  `mysql/include`
while it finds the client under `mariadb-server/lib/`

```
-- Found MySQL headers: /nix/store/r63mknli0yqgsw1fwx993clddvlgxl8y-mysql-8.4.2/include/mysql
-- Found MySQL: /nix/store/v9p2g5i0xqx9gbw2j6494vbjcr7kynqc-mariadb-server-10.11.9/lib/libmysqlclient.so
```

i couldnt find a more proper solution rather than defining both mysql and mariadb as paths in the nix/store to look through/for.

other packages, such as ffmpeg are found using pkg-config, which doesnt work for mysql, which i also debugged:

```
-- Looking for MySQL using pkg-config...
-- Checking for modules 'mysql;mariadb'
--   No package 'mysql' found
--   No package 'mariadb' found
-- pkg-config did not find MySQL
```

**Comment by BlaiZephyr** [comment]
i will play around with it more - if i find a proper/better solution that doesnt explicitly have to define the nix/store path i'll supersede this

**Comment by heinrich5991** [comment]
Why does this add a lot of other paths that are not needed for nix? Please remove them, otherwise we won't be sure in the future which of them is required for nix.

**Pull request merged**
