### PR TITLE
Add timeout for serverbrowser http request

### PR DESCRIPTION
**Pull request by def-**
to prevent getting stuck entirely. Following #3889

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Ah now i get it, the timeout is also set for curl, thought its some job internal timeout :D

I would be ok with this

**Review by Jupeyy — APPROVED** [review]

**Comment by def-** [comment]
I hope our jobs are simple and correct enough that we never have to kill them in some way.

**Comment by Jupeyy** [comment]
Maybe still interesting to know, apparently even a value of 0 doesn't mean no timeout("Set to zero to switch to the default built-in connection timeout - 300 seconds." -- [here](https://curl.se/libcurl/c/CURLOPT_CONNECTTIMEOUT_MS.html))

**Comment by Jupeyy** [comment]
Maybe we should also set a parameter for the full request and not only the connecting phase?(CURLOPT_TIMEOUT_MS)
I mean this is all very edge case, but i guess this is what you meant in the other pr, that a already opened connection could die)

**Comment by def-** [comment]
Ah yeah, that would make sense. Do you want to take this change and add CURLOPT_TIMEOUT_MS to a new change, all in your PR?

**Comment by Jupeyy** [comment]
Yeah i'll do it

**Pull request closed without merging**
