### PR TITLE
Implement shields that remove specific weapon (fixes #4572)

### LINKED ISSUE #4572: Give switched shields an attribute which weapon to delete
Switched hammer off/on tile let u set which weapon they shall turn off by using the delay feature in switches. The same can work for shields as the delay isnt used for them yet.

Setup delay:

1 - removes Ninja from player
2 - unused or maybe deletes jetpack?
3 - removes shotgun from player
4 - removes grenade from player
5 - removes laser from player

This could help mappers A LOT for parts where they have to deal with more weapons  and dont want to create a  mess with different teleporters to give the player only a specific weapon and avoids the spam of weapon and shield tiles.

### PR DESCRIPTION
**Pull request by def-**
Thanks to Cellegen for graphics.

Functionality works, still a bit buggy sprite display (see screenshot), maybe someone can
quickly spot what I'm doing wrong

Screenshot 2022-02-18 at 00 50 14

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Zoozti** [comment]
i guess the small graphics are in the wrong resolution. They are 64x64. i dont know which they must have

**Comment by Zoozti** [comment]
Someone should also quick test if they work as switched shields also.
I cant cuz im too dumb for cmake

**Comment by fokkonaut** [comment]
Why did you not make it as switch + delay?

**Comment by fokkonaut** [comment]
> Why did you not make it as switch + delay?

That would automatically fix vanilla support, but would disallow sending those by code. Hm.

**Comment by Zoozti** [comment]
> Why did you not make it as switch + delay?

i mean that was my idea at first but could it even work with showing different graphics to players with compatible clients? Maybe show old/vanilla clients just a normal shield if possible

**Comment by Jupeyy** [comment]
I added a commit, so the quadoffsets are easier to use, i hope it helps

**Comment by def-** [comment]
Thanks, much better.

**Comment by def-** [comment]
Screenshot 2022-02-18 at 11 27 28
Thanks to @Jupeyy, works now.
Remaining question: Do we want this as separate entities as it is now (easier to map) or on switch layer with the number as initially proposed (shown in vanilla then)?

**Comment by def-** [comment]
> The good thing about having it as seperate tiles is that u can stack this tile 3x with game, front and switch layer which means you can delete up to 3 specific weapons, this is cool for mappers.

With switch number we could do this too, but then display becomes harder again:
```
1 - Shotgun
2 - Grenade
4 - Laser
8 - Ninja
```
Then you can sum up the numbers to combine them, so 11 would disable ninja, grenade and shotgun.

**Comment by fokkonaut** [comment]
Using entity ex is probably the way to go, combined with delay. I dont think we need multi removal on one tile, as that would also remove the intention of indivudal graphics. If one wants to remove 2 weapons, place 2 tiles.

**Comment by heinrich5991** [comment]
I like the current graphics, wouldn't suggest to combine removal of multiple weapons.

Currently has a merge conflict, can you resolve that @def-?

**Comment by def-** [comment]
Done

**Comment by Zoozti** [comment]
Great. Dont want to put pressure but do u know when it will be online in client/server?

**Comment by def-** [comment]
When it's merged plus 1 day plus the time it takes for official servers to restart. In nightly client after 1 day, no official client release planned yet, maybe in 1-2 months.

**Comment by heinrich5991** [comment]
bors r+

New gameplay features. ^^

**Comment by fokkonaut** [comment]
What about vanilla compatibility? What about EntityEx that would have a perfect usecase here?...

**Comment by edg-l** [comment]
No need for that.

**Comment by C0D3D3V** [comment]
Because this is now a new functionality anyway xD why did we actually stay with shields. Historically grown games really have the funniest ideas to make a nuclear missile out of a hat. Or from a shield a forced disposal of weapons.
Since I play ddnet for ages I have no problem with it. Only this would have been the opportunity to come up with something new, since we have now anyway vanilla apparently left out.

**Comment by def-** [comment]
> What about vanilla compatibility? What about EntityEx that would have a perfect usecase here?...

So I guess we haven't discussed about Vanilla compatibility enough yet. @fokkonaut  We have a few features already that don't work well with Vanilla client, should we remove them?

> why did we actually stay with shields.

Because it's what we have available. If you have better graphics, we could use them.

**Comment by fokkonaut** [comment]
> No need for that. If you are playing with the vanilla client, you are already set for a bad experience anyway.

Thats very dumb. Why do we have 0.7 support then?
And why didnt nobody listen to me? Its not hard to implement it as a normal shield, with a entityex that contains info on which shield it is. That would automatically fix vanilla compatibility.

**Comment by def-** [comment]
Yes

**Comment by Zoozti** [comment]
I think its the best way to just show vanilla/old client players a normal shield. So they see they will lose weapons and dont get surprised by an invisible tile

**Comment by l-ouis** [comment]
I think this change is unnecessary for a few reasons:

1. principle
it will cause mappers to use confusing mechanics in their parts. these shields will encourage mappers to make maps where the flow of "weapon pickups" is not fluid throughout the whole map (changing the weapon combination rapidly part after part, which leads to confusion). in my opinion, this is annoying to play as you have to keep track of which weapon you have and which you don't have.

2. compatibility: 
other than vanilla compatibility, wouldn't this not display shields for anyone still using custom gameskins or entities? while i do believe it's the player's responsibility to make sure of these things, i don't think these 3 shields are significant enough to cause everyone to update their assets. 

3. practicality:
i'm not sure what benefits this gives over simply putting an armor entity and the weapon you want to keep right after it. the only benefit i can see is that it takes up less space, which shouldn't be a problem in 99% of maps. additionally, it's the more confusing as it forces the player to consider what weapons they already have and mentally work out which weapons the shield will remove.
on the other hand, with the "shield + weapon right after", the player can clearly tell what weapons they will be left with afterwards.

**Comment by heinrich5991** [comment]
> 3\. practicality:
>         i'm not sure what benefits this gives over simply putting an armor entity and the weapon you want to keep right after it. the only benefit i can see is that it takes up less space, which shouldn't be a problem in 99% of maps. additionally, it's the more confusing as it forces the player to consider what weapons they already have and mentally work out which weapons the shield will remove.
>         on the other hand, with the "shield + weapon right after", the player can clearly tell what weapons they will be left with afterwards.

I think @Zoozti requested these shields, perhaps you can comment what you want to achieve with them?

**Comment by Zoozti** [comment]
I dont think louis sees the possibilities this mechanique brings into the game. It is a pretty simple feature which is easy to understand. 
"Confusing" mechanics isnt really a reason i think. We got a lot of tunes map and there is absolutely no way to tell which physics they contain and still they can be used fine.
The shields design exactly shows what will happen.
It is NOT possible to just put a shield and a weapon in any case. I got a map with parts you will cross 3 or 4 times throughout playing it. Without these shields i would have to create a huge mess of switches, shields and weapons which is way more confusing than just a simple shield that pretty easy shows what it will do.

I guess louis arguments are the default argument against "something new"
I know that because usually its me who argue like that.

This feature helps mappers and makes parts with different weapons less confusing, not more.

**Comment by C0D3D3V** [comment]
> as you have to keep track of which weapon you have and which you don't have.

If #5085 get merged you do not have to keep track about your weapons.

**Comment by Zoozti** [comment]
> > as you have to keep track of which weapon you have and which you don't have.
> 
> If #5085 get merged you do not have to keep track about your weapons.

Yeah, wanted to mention that too.
Features will be displayed soon :D

**Comment by l-ouis** [comment]
I'm not arguing against 'something new', I'm saying that this isn't worth the promised "mechanics" it will bring.

As for the HUD, yes it will make it easier to tell, but still requires you to take a peek at the corner of your screen.

I don't think it's worth causing a lot of compatibility issues for a tile that won't really be used often. Similar to live freeze, I think it's imperative that **multiple** experienced mappers talk about the entity. Right now it feels like you want to use this tile in one of ur own maps which is why you want it to be added so much.

**Comment by Zoozti** [comment]
> I'm not arguing against 'something new', I'm saying that this isn't worth the promised "mechanics" it will bring.
> 
> As for the HUD, yes it will make it easier to tell, but still requires you to take a peek at the corner of your screen.
> 
> I don't think it's worth causing a lot of compatibility issues for a tile that won't really be used often. Similar to live freeze, I think it's imperative that **multiple** experienced mappers talk about the entity. Right now it feels like you want to use this tile in one of ur own maps which is why you want it to be added so much.

I dont see compatibility issues here. Vanilla has a really bad experience on DDNet maps already, i wont count that as an argument lol.
For now your the only one who is against this.
I asked bunch of people what they think about that, for example Silex who found it cool.
Yes it is correct that I would like to use them in a new map from me. It would work without too yes. But the change is really not much of a discussion worth.
Its very easy to understand IF mappers use it. I dont see a problem it will cause in the community. Dont think people will complain about that.

**Comment by l-ouis** [comment]
i didnt mean vanilla compatibility, i meant compatibility with the many players who use custom gameskins and entities

as far as the practicality, i guess if many mappers think its useful then i can't argue against that. i just have a feeling that ppl will use this to make disgusting spammy parts instead of using them in a clear way - but i guess testing can take care of those.

i cant argue against it much more, but id recommend to release this with a news update clearly notifying about the gameskin/entity compatibility

**Comment by Zoozti** [comment]
> i didnt mean vanilla compatibility, i meant compatibility with the many players who use custom gameskins and entities
> 
> as far as the practicality, i guess if many mappers think its useful then i can't argue against that. i just have a feeling that ppl will use this to make disgusting spammy parts instead of using them in a clear way - but i guess testing can take care of those.
> 
> i cant argue against it much more, but id recommend to release this with a news update clearly notifying about the gameskin/entity compatibility

Oh yeah you clearly got a point there, i didnt think of custom game skins. That may be cause Some problems.
But they wont be the last new game tiles so i guess it is not possible to avoid to break the compatibility. Updates needed from time to time.
Btw i also use live freeze in that map :P

**Comment by C0D3D3V** [comment]
This is in my opinion another reason to let the map overwrite the game assets. 
I will open an issue for that...

**Pull request merged**
