### PR TITLE
Create custom look for DMG using dmgbuild (fixes #4442)

### LINKED ISSUE #4442: macOS dmg should allow installation by dragging into Applications
Other applications work that way, see for example Firefox. That seems cleaner than what we have now.

### PR DESCRIPTION
**Pull request by def-**
This removes cross-building DMG support since dmgbuild requires hdiutil, which is macOS only. Thoughts?

Nice background image by Ravie:
Screenshot 2021-12-27 at 00 29 43

### CODE REVIEW

**Comment by def-** [comment]
Maybe dmgbuild can be made to support running without hdiutil

**Comment by def-** [comment]
Background image by Ravie added

**Comment by def-** [comment]
Failure is unrelated:

```
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 6549 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'googletest-src'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 804 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Cloning into 'googletest-src'...
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 7367 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
-- Had to git clone more than once:
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:66 (message):
          3 times.
  Failed to clone repository: 'https://github.com/google/googletest.git'


make[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1
CMakeFiles/googletest.dir/build.make:90: recipe for target 'googletest-prefix/src/googletest-stamp/googletest-download' failed
make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/googletest.dir/all' failed
Makefile:83: recipe for target 'all' failed
```

**Comment by heinrich5991** [comment]
Has conflicts as well. Did I wait too long?

**Comment by def-** [comment]
Fixed

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
