### PR TITLE
serverbrowser: communities->servers instead of communities->icon->servers

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by heinrich5991 — APPROVED** [review]
Not sure if we can moving it eventually makes sense, but I guess this code doesn't hurt.

**Comment by Jupeyy** [comment]
Did enough versions pass, or do I need to port this workaround? xd

**Comment by def-** [comment]
I haven't actually moved them away from icons yet in the json: https://info.ddnet.org/info

**Comment by Jupeyy** [comment]
> I haven't actually moved them away from icons yet in the json: https://info.ddnet.org/info

Yeah, would it make sense to move them now, or did not enough time pass yet?

**Comment by def-** [comment]
Not yet I'd say. People are using older versions.

**Comment by Jupeyy** [comment]
Then please remove 18.1 from website at least. Bcs this seems like a weird workaround for a single version.

**Comment by def-** [comment]
Fine, changed it.

**Comment by heinrich5991** [comment]
Not sure why we want to stop old versions from working with communities for a cosmetical change…

**Comment by Jupeyy** [comment]
> Not sure why we want to stop old versions from working with communities for a programmer-cosmetic change… I think that's a bad decision.

Bcs then I can use serde derive instead of some weird workarounds.
Also this is an obvious bug, dropping a single version sounds more than sane

**Comment by def-** [comment]
So there is no way to just deprecate it?

**Comment by heinrich5991** [comment]
If we accept this bug that only affects the beauty of this protocol, then we could tell people that we'll never deprecate the old paths until we create a new endpoint.

**Comment by def-** [comment]
Fine, I put it back into icons for now.

**Pull request merged**
