### PR TITLE
Fix misspellings

### PR DESCRIPTION
**Pull request by rffontenelle**
Fix misspellings ("typos") reported by [codespell](https://github.com/codespell-project/codespell).

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
bors r+
Always saw some, but in total more than expected.

**Comment by def-** [comment]
Can we add the codespell config you probably made for this to our CI?

**Comment by rffontenelle** [comment]
Totally possible. Since it reports some false-positives, we have to adjust to properly skip files and ignore words. There is the upstream's action [actions-codespell](https://github.com/codespell-project/actions-codespell), but we can always use the tool.

**Comment by rffontenelle** [comment]
By the way, I did not config. codespell reported errors and I went fixing the errors and ignoring false-positives. But this surely can be put in an action with better filters than the one I used.

**Comment by def-** [comment]
Ok, not sure it's worth the effort then.

**Pull request merged**
