### PR TITLE
Link to localized Wikis even if they are not complete

### PR DESCRIPTION
**Pull request by def-**
Traditional Chinese links to Simplified Chinese wiki
Portuguese links to Brazilian Portuguese wiki
Rest is 1:1 match

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I don't know about Brazilian Portuguese. Does someone speak Portuguese or Brazilian Portuguese and can comment on whether that's understandable?

**Comment by def-** [comment]
@rffontenelle ^

**Comment by rffontenelle** [comment]
Brazilian native and pt-br ddnet translator here.  I'm good 👍

**Comment by heinrich5991** [comment]
bors r+

Thanks!

**Pull request merged**
