### PR TITLE
Make editor entities layer explanations localizable, refactor editor entities layer explanations

### PR DESCRIPTION
**Pull request by Robyt3**
## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I've always been against this, way too much effort to translate.

**Comment by Vy0x2** [comment]
looks good 👍

**Comment by heinrich5991** [comment]
I agree with deen, probably too much effort for translators, only helping mappers.

**Comment by Robyt3** [comment]
If we don't want this then we can close #2412 as not planned as well.

**Pull request closed without merging**
