### PR TITLE
Remove non-free skins by Moby Dog (fixes #2547)

### LINKED ISSUE #2547: CC-BY-NC-SA skin license
> lightbulb, tank, emo, bunny, hedgehog, napoleon, roman, caesar, nosey, savage:
> Copyright Lappi
> CC-BY-NC-SA license

I would argue that CC-BY-NC-SA is too restrictive. It certainly does not line up with the rest of ddnet's source and data licenses. Unless Lappi re-licenses, we should delete these skins.

### PR DESCRIPTION
**Pull request by yangfl**

### CODE REVIEW

**Comment by fokkonaut** [comment]
Why do we delete all of these skins? For the steam version? Its very sad because so many good and actively used skins were removed already :(

**Comment by yangfl** [comment]
See #2547 for discussion of the license (in short, NC clause contradicts other parts of DDNet)

**Comment by def-** [comment]
@fokkonaut At least they can still be used using the skin downloader.

**Comment by def-** [comment]
I guess yangfl is right. Originally I missed in #2547 that the skins by MobyDog are also affected.

@heinrich5991 You were in touch with MobyDog, could you ask him to relicense the skins?

**Comment by heinrich5991** [comment]
@yangfl It is incorrect that NC is at odds with other licensing in DDNet, we can ship NC skins just fine together with our zlib'ed source code. The licenses do not contradict each other.

The Debian project does not want to ship NC licensed stuff.

**Comment by heinrich5991** [comment]
@def- 
I don't want to contact MobyDog about this again tbh. I'm fine with stripping them from the source now that we have the skin downloader, so that Debian can ship our source verbatim.

**Pull request merged**
