### PR TITLE
Remove unmaintained Android code (fixes #1575)

### LINKED ISSUE #1575: Remove android related code
I think getting android support is a thing no one will ever do, and I also think it doesn't make sense to have this game on a mobile device.

### PR DESCRIPTION
**Pull request by def-**
Thoughts?

### CODE REVIEW

**Comment by Ryozuki** [comment]
this is an improvement

**Comment by fokkonaut** [comment]
f3

**Comment by 12pm** [comment]
agree

**Comment by def-** [comment]
Ok with me if @Ryozuki and @Learath2 agree and no one wants to start maintaining the Android version.

**Comment by heinrich5991** [comment]
Negative diff count. :)

Seemed to be fine by @Learath2, also fine by me.

bors r+

**Pull request merged**
