### PR TITLE
Try crc for maps if sha256 isn't available (fixes #4327)

### LINKED ISSUE #4327: Can't save demo after cutting, demo recorder videos
Reported by Gummibaer12345 on Discord
Unbenannt
@Robyt3 I'm not seeing anything unicode, but could this still be related? I can't reproduce on Linux and Wine

### PR DESCRIPTION
**Pull request by def-**
Happens with demos cut from KoG

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
This will allow people to successfully attack with maps with colliding CRCs again, so this opens a vulnerability that people might try to abuse.

The map is available inside the demo, so maybe that could be used instead?

**Comment by def-** [comment]
I have tried passing m_File, but that failed, not sure why.

**Comment by def-** [comment]
I tried reading the CDemoRecorder::Start method again and couldn't find why it fails to  create a working demo when a file is passed.

**Comment by def-** [comment]
I guess the demo player reading the file at the same time as the demo recorder trying to read it messes this up.

**Comment by def-** [comment]
Ooooh, the m_File in CDemoPlayer is the demo file, not the map file.

**Comment by heinrich5991** [comment]
Ah yeah, that seems right. Thanks. :)

bors r+

**Pull request merged**
