### PR TITLE
Remove the unused Skinstealaction

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by def-** [comment]
Who added it originally?

**Comment by fokkonaut** [comment]
https://github.com/ddnet/ddnet/commit/3607218f121f34c619e958f190dddc062e17d381#diff-484561fa827fcba7d4ff098e92833c2cR596

**Comment by def-** [comment]
ok, lgtm. another admin want to chime in?

**Comment by Learath2** [comment]
We don't use it, I haven't seen any servers using it, we can merge.

**Comment by Learath2** [comment]
We don't use it, I haven't seen any servers using it, we can merge.

**Comment by heinrich5991** [comment]
Thanks.

bors r+

**Pull request merged**
