### PR TITLE
Fix text kerning and add flags for better positioning

### PR DESCRIPTION
**Pull request by Jupeyy**
This is a different implementation to #1419.

Also this fixes character kerning, which I disabled default now, since it was never ever correctly implemented in the teeworlds code.

### CODE REVIEW

**Comment by def-** [comment]
bors r+

Looks good, seems to work great. I'd merge it in for now and if there are problems we can change it later.

**Comment by def-** [comment]
And thanks a lot for the crazy amount of work you're putting into our rendering!

**Comment by fokkonaut** [comment]
I got a not-centered name again in ddnet 11.8

**Comment by Jupeyy** [comment]
can u give the name, i saw utf decoding is bit broken in the current client, maybe its related

**Pull request merged**
