### PR TITLE
Use a cubic polynomial for smoothing zoom

### PR DESCRIPTION
**Pull request by heinrich5991**
Supersedes #2420.

### CODE REVIEW

**Comment by def-** [comment]
Looks really nice.

**Comment by heinrich5991** [comment]
Thanks.

**Comment by fokkonaut** [comment]
Why did you remove the config option?

**Comment by heinrich5991** [comment]
For me it's not "why don't you add a config option?" but rather "why is a config option required here?".

Why is a config option required here?

**Comment by Learath2** [comment]
I'd guess to allow people recording with this some creative freedom?
Honestly I don't see it ever being used

**Comment by def-** [comment]
bors r+

Thanks a lot @edg-l & @heinrich5991 !

**Pull request merged**
