### PR TITLE
Implementation note for dilate: Unused sum&counter

### PR DESCRIPTION
**Pull request by Patiga**
The code is confusing, as the sum and counter are not used. Establishing a different dilate algorithm would be a hassle. The difference is minor and probably not noticeable.

## Checklist
- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Patiga** [comment]
@Jupeyy this took me longer to debug than I'd like to admit :p

**Comment by Jupeyy** [comment]
I dunno what you need dilate for, but I strongly suggest you to merge #7169 for that too

**Comment by Patiga** [comment]
Ah thanks for the reference. I reimplemented dilate for twmap

**Comment by Patiga** [comment]
This pull request doesn't change the behavior, only points it out.
If #7169 is merged somehow, this `break` could also be removed.

**Comment by Jupeyy** [comment]
> Ah thanks for the reference. I reimplemented dilate for twmap

Ah well then size won't matter ig :D

**Pull request merged**
