### PR TITLE
Fix Leak IP check

### LINKED ISSUE #9035: "Leak IP" maybe broken
With the teeworlds master server you can see the server name and player count of your favorites even if they are not registered in the master ``sv_register 0``. In ddnet this is no longer possible because the client gets all its information from the http master server which does not know about unlisted servers.

### PR DESCRIPTION
**Pull request by TsFreddie**
Fixes #9035

one liner fix.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Have you tested your fix?

**Comment by TsFreddie** [comment]
by refreshing the three servers i have in my favorites. yes.

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Comment by ChillerDragon** [comment]
Works so good. Thank you so much fred :heart:

**Pull request merged**
