### PR TITLE
Added map_find_env tool

### PR DESCRIPTION
**Pull request by sctt**
a simple tool which given an envelope id returns a list of all quads associated with that envelope, screenshot attached below.
Screenshot from 2022-08-13 18-48-41

p.s.
deen told me its not a problem to commit these kind of map tools to ddnet

### CODE REVIEW

**Comment by Chairn** [comment]
You forgot the .cpp extension in the filename :)

What's the use case for this?

**Comment by sctt** [comment]
> You forgot the .cpp extension in the filename :)
lol thanks

> What's the use case for this?
when map is complex you might have forgotten where all your envs are used exactly. that's my case.

**Comment by Chairn** [comment]
Feel kinda overkill. Maybe you could add it to editor directly?

**Comment by sctt** [comment]
> Feel kinda overkill. Maybe you could add it to editor directly?

i might do it for fun, but i don't actually need it right now, so it won't happen soon.
feel free to ditch this PR if you find this tool an overkill.

**Comment by def-** [comment]
Doesn't hurt to have this included.
bors r+

**Pull request merged**
