### PR TITLE
Move switcher snapping code to own method

### PR DESCRIPTION
**Pull request by ChillerDragon**
Feels more organized to not do this wall of switcher code in the CGameController snap

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Seems to only move the `Snap` function for switches. Perhaps it could be moved to `CGameContext::SnapSwitches` instead? The whole data structure still lives there.

**Comment by ChillerDragon** [comment]
> Seems to only move the `Snap` function for switches. Perhaps it could be moved to `CGameContext::SnapSwitches` instead? The whole data structure still lives there.

Yea would also be nice. I just thought switchers are such a big feature that one would like to find it in file finder and potentially it could be extended with more stuff later on to collect it all in one place.

**Comment by ChillerDragon** [comment]
> Seems to only move the `Snap` function for switches. Perhaps it could be moved to `CGameContext::SnapSwitches` instead? The whole data structure still lives there.

Why CGameContext? And not keep it in IGameController::SnapSwitches?

**Comment by ChillerDragon** [comment]
Okay I did that. Code still untested.

**Comment by ChillerDragon** [comment]
Okay I joined in game and was able to turn switchers on or off just fine

**Review by heinrich5991 — APPROVED** [review]
Thanks.

**Comment by ChillerDragon** [comment]
SnapSwitches would be the first code snippet that calls it switches instead of switchers that seems wrong

**Comment by ChillerDragon** [comment]
bors +abort

**Comment by heinrich5991** [comment]
"switches" seems to be the correct word: [switcher](https://en.wiktionary.org/wiki/switcher#English) vs [switch on wiktionary](https://en.wiktionary.org/wiki/switch#English).

**Comment by ChillerDragon** [comment]
> "switches" seems to be the correct word: [switcher](https://en.wiktionary.org/wiki/switcher#English) vs [switch on wiktionary](https://en.wiktionary.org/wiki/switch#English).

I prefer consistent over correct. So either we fix all to correct english or we also name this one switcher.

**Comment by ChillerDragon** [comment]
Okay i force pushed from ``SnapSwitches`` to ``SnapSwitchers`` so it is the same everywhere. Renaming all to switchers is a big diff. The term does not sound too incorrect. And it is easier to search for it in the code base because the singular does not conflict with the english word in comments and C++ keyword ``switch``

**Pull request merged**
