### PR TITLE
Add check for correct finish time in integration_test.sh

### PR DESCRIPTION
**Pull request by Zwelf**
## Checklist

- [ ] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
The CI might be too laggy for such precise checks. Are physics supposed to work exactly the same if the server can't keep up with the tick speed?

**Review by def- — APPROVED** [review]
This should work

**Comment by Zwelf** [comment]
The dragger seems to depend on which exact tick the player joined. Modifying the map now to have the time completly reproducable.

**Comment by Zwelf** [comment]
https://github.com/ddnet/ddnet/assets/9964758/1e55f84c-d364-435c-8ee4-45b4d629dfd5


https://github.com/ddnet/ddnet/assets/9964758/41bf5eff-ea45-4f55-900d-5e627b27651e

**Comment by Zwelf** [comment]
CI failure slightly frustrating, because finish time is the same, but some checkpoint times are off by one tick (cp11, cp12, cp15, cp16). The tee is 1 Tick faster in CI than on my computer. But all other times are matching and it looks consistent on CI too.

```diff
3,4c3,4
< player: client1 time: 6249.44 cps: 0.42 0.5 0.0 0.68 0.94 0.02 300.18 300.46 300.76 300.88 301.0 301.18 301.38 301.6 301.82 301.92 302.24 302.52 308.22 308.96 308.98 309.02 309.32
< player: client2 time: 302.36 cps: 0.42 0.5 0.0 0.68 0.94 0.02 300.18 300.46 300.76 300.88 301.0 301.18 301.38 301.6 301.82 301.92 302.24 0.0 0.0 0.0 0.0 0.0 0.0
---
> player: client1 time: 6249.44 cps: 0.42 0.5 0.0 0.68 0.94 0.02 300.18 300.46 300.76 300.88 300.98 301.16 301.38 301.6 301.8 301.92 302.24 302.52 308.22 308.96 308.98 309.02 309.32
> player: client2 time: 302.36 cps: 0.42 0.5 0.0 0.68 0.94 0.02 300.18 300.46 300.76 300.88 300.98 301.16 301.38 301.6 301.8 301.92 302.24 0.0 0.0 0.0 0.0 0.0 0.0
```

**Comment by Zwelf** [comment]
https://github.com/ddnet/ddnet/assets/9964758/cc3a1f25-4f28-40b4-a943-ffc697c70dbf

**Comment by Zwelf** [comment]
Disabled exact check for finish times on valgrind. I hope this test map isn't fragile. Apart from the different time on valgrind I think it produces stable finishes.

https://github.com/ddnet/ddnet/assets/9964758/f12e8554-fcbb-4663-a349-56e5f4578410

It does also add a few more physics tests to the coverage map.

**Comment by Zwelf** [comment]
Hopefully final version :sweat_smile: for this PR

https://github.com/ddnet/ddnet/assets/9964758/334dafbb-32a1-4059-bc4f-a5f29a85a984

**Comment by ChillerDragon** [comment]
Good job on making it pass @Zwelf. Working with the CI can be quite annoying nice that you finished it.
Also I saw you added many more test cases (I love the push through the other tee and attempted stopper skip).

Any chance you could optimize for speed? I am sure some distances could be shorter and some speedups could be faster without removing any test cases. It would make debugging more pleasant.

**Review by Robyt3 — APPROVED** [review]

**Comment by heinrich5991** [comment]
> Disabled exact check for finish times on valgrind.

Why are the finish times different in valgrind?

**Comment by Zwelf** [comment]
> Why are the finish times different in valgrind?

I assume due to valgrind being slower and maybe Ticks(?) being missed. Or the second client joining too late. I want to change CI to make the server demo an artifact to be able to aspect test failures.

**Comment by heinrich5991** [comment]
Ticks should not be missed:

https://github.com/ddnet/ddnet/blob/2dbcb9795af3f6252852e251bc11b3572f7cf10e/src/engine/server/server.cpp#L2878

All ticks should be evaluated in order, no matter how slow the process is.

> Or the second client joining too late.

This could be the reason.

**Pull request merged**
