### PR TITLE
added viewers command

### PR DESCRIPTION
**Pull request by ChillerDragon**
This adds the command '/viewers' which shows a list of all people watching you in spec or pause.
Idea by Cellegen https://forum.ddnet.tw/viewtopic.php?p=58183#p58183

### CODE REVIEW

**Comment by heinrich5991** [comment]
Opinions on privacy? Should someone be able to tell that I'm watching them? @Learath2 @def- @ChillerDragon ?

**Comment by ChillerDragon** [comment]
@heinrich5991 you prefer just the number of watching dudes? Hmm i don't think some1 has privacy problems. I never use /pause but i guess i don't care if some1 knows who i am watching.

But anyways i had an idea while reading Cellegens post. Because checking in chat is pretty annoying -> It would be great if the server automatically informs you if you reach some viewers. Lets say if you hit 3 views the server says "*** much wow you currently have 3 stalker" and this gets checked lets say every 10 minutes.

**Comment by ChillerDragon** [comment]
And what does the circleci and travis fail mean? I checked it local it compiled fine on my windows machine. What did i do wrong? ._.

**Comment by heinrich5991** [comment]
Click on the "Details" link:
```
src/game/server/ddracechat.cpp: In static member function ‘static void CGameContext::ConViewers(IConsole::IResult*, void*)’:
src/game/server/ddracechat.cpp:1380:22: error: ‘strcat’ was not declared in this scope
     strcat(aMsg, aBuf);
```

You shouldn't use `strcat`, use functions from `system.h` instead (in this case `str_append`).

**Comment by def-** [comment]
Strongly against it.

**Comment by H-M-H** [comment]
To be honest I do not really see any use in this only some more code to maintain.

**Comment by heinrich5991** [comment]
I mostly hear negative feedback for this change. In order to provide a quick response, I'm going to close this pull request. If you want it reopened, please comment so.

Thanks for hearing user requests and implementing them.

**Pull request closed without merging**
