### PR TITLE
Revert "Show official server icon in friends list"

### PR DESCRIPTION
**Pull request by heinrich5991**
This reverts commit fc3583a18e59c7ded88a6ca537d8ae95476a435d.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I see that the connect popup was reverted already, which makes me happy. We don't want to discourage "non-official" servers, whatever that might mean.

If I understood our direction correctly, we wanted to get rid of the DDNet tab or "official server markings" at some point, so we shouldn't add new places to show these icons.

**Comment by heinrich5991** [comment]
> This was the direction you wanted DDNet to go. (Or rather to disappear among the other servers that we should promote instead?)

I had the impression that other people also didn't like the privileged status of DDNet/KoG server above others, and that we should seek better solutions than those that just push up random servers we gave the checkmark, e.g. like noby's fng servers but not unique's race servers.

> This seems tough for moderators who will end up using their auth on the wrong servers

I see that this is a problem.

> and people in general getting DoSed because they join the wrong server which has fakes of their friends showing as players.

I have not heard about this being a problem, people being lured into the wrong servers by showing their friends. In fact, we haven't had such a fake player problem before.

**Comment by Syrinok** [comment]
> I have not heard about this being a problem, people being lured into the wrong servers by showing their friends. In fact, we haven't had such a fake player problem before.

We should only start caring when it does happen? I guess SP Someone has to work his magic yet again, truly the hero of DDNet.

**Comment by heinrich5991** [comment]
> > I have not heard about this being a problem, people being lured into the wrong servers by showing their friends. In fact, we haven't had such a fake player problem before.
> 
> We should only start caring when it does happen? I guess SP Someone has to work his magic yet again, truly the hero of DDNet.

To a point, yes, if something is only a theoretical problem and not likely to happen, then yes, we should maybe wait and see…

We ban servers that report fake players from the masterserver. For the rest… I do not really see the problem. You join the wrong server with SP|Someone in it and then what happens exactly?

**Comment by def-** [comment]
> > This was the direction you wanted DDNet to go. (Or rather to disappear among the other servers that we should promote instead?)
> 
> I had the impression that other people also didn't like the privileged status of DDNet/KoG server above others, and that we should seek better solutions than those that just push up random servers we gave the checkmark, e.g. like noby's fng servers but not unique's race servers.

Sorry for the harsh wording.

Better solutions would be fine, but until we have them we should make use of the verified servers. If we had a way of everyone registering their own set of connected servers, then there should be a display of what network the server belongs to, instead of just the blue mark.

**Pull request closed without merging**
