### PR TITLE
Make GL 1.5 default

### PR DESCRIPTION
**Pull request by Jupeyy**
If ppl see white textures its related to
#2125
and you need to revert it, bcs thats not fixable, there is no extension for GL_GENERATE_MIPMAP or smth

### CODE REVIEW

**Review by def- — APPROVED** [review]
+1 from my side, this should get some of the problems with bad gpu/opengl drivers down.

**Comment by Jupeyy** [comment]
Until now the only reports i saw were from intel and under windows, we could also just disable it for intel.

**Comment by Jupeyy** [comment]
actually nvm, lets just revert it, seems like even amd can handle it

**Comment by def-** [comment]
I would really like to see one of those crashdumps. If 2 gpu drivers crash, maybe we're doing something wrong?

**Comment by Jupeyy** [comment]
well the 2 gpu drivers just invalidated itself.
he cannot even open the client with gfx_opengl_major 1

**Comment by Jupeyy** [comment]
But tbh i'd still prefer to use gl 1.x again, bcs then i dont have to answer these endless driver questions anymore.
Then you can always assume its either the code or some SDL stuff xd

**Comment by Learath2** [comment]
> I would really like to see one of those crashdumps. If 2 gpu drivers crash, maybe we're doing something wrong?

I'm still baffled at the amount of graphics drivers that can't handle these quite basic tasks. It'd make more sense if it was our fault tbh.

> But tbh i'd still prefer to use gl 1.x again, bcs then i dont have to answer these endless driver questions anymore.
> Then you can always assume its either some other code, the driver doesnt work at all or some SDL stuff xd

Make gl3 experimental again?

**Comment by Jupeyy** [comment]
> I'm still baffled at the amount of graphics drivers that can't handle these quite basic tasks. It'd make more sense if it was our fault tbh.
Stand now, only intel reports, the AMD one was a false report, his data or config was broken, had nothing todo with the implementation.

> Make gl3 experimental again?
it still is

**Pull request merged**
