### PR TITLE
Ask for confirmation before placing border tiles

### LINKED ISSUE #2823: Border button broke my map frequently
If you not changed layer and pressed on a place where tele/switch number picker stays then you are fucked (because Border resides in this place). 

I don't think this button is usable nowadays. Please add confirmation message at least or move this button to less frequently used place.

### PR DESCRIPTION
**Pull request by Fireball-Teeworlds**
Fixes #2823

### CODE REVIEW

**Comment by Fireball-Teeworlds** [comment]
Link to the message in \#mapping where most people agreed that the button is at the very least not used very often: https://discord.com/channels/252358080522747904/746534464984973323/755040877587464293.

**Comment by edg-l** [comment]
Test and works, lgtm.

**Comment by BannZay** [comment]
I am kinda confused of decision to keep this button (as we have limited space for toll buttons) but whatever.

**Comment by Fireball-Teeworlds** [comment]
I agree I might've been too cautious when not just removing it.

**Comment by Fireball-Teeworlds** [comment]
PS: Didn't notice your Contributor badge when looking for an issue to fix - sorry if I've fixed something you were planning to fix yourself :)

**Comment by BannZay** [comment]
Don't worry, everything is okay.

**Pull request merged**
