### PR TITLE
Allow automatic multi-view for players in a team

### PR DESCRIPTION
**Pull request by Possseidon**
Implements #7007, to summarize:

If all players, that are currently in view, are in the same team, when switching to multi-view it will now switch to those players. Previously, this only worked for players in team 0.

If players of differing teams are in view, it will still use the old "only team 0" behavior, which simply ignores players in teams.

## Checklist

- [x] Tested the change ingame
- [x] ~Provided screenshots if it is a visual change~
- [x] ~Tested in combination with possibly related configuration options~
  - While there are some multi-view options, they don't really affect any of this
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Vy0x2** [comment]
If there is a team of 4 players and you were looking at 2 of them, only those will be activated then. Is this intended?
An alternative would be, that all tees from the team should be activated or everyone you deactivate everyone but the team is being set so it will look at all automatically

**Comment by Possseidon** [comment]
Was intentional, yes.

**Comment by Robyt3** [comment]
Looks good to me. Also good for you, @Vy0x2 ?

**Review by Robyt3 — APPROVED** [review]
Thanks @Possseidon!

**Pull request merged**
