### PR TITLE
Fix alignment for chat....

### PR DESCRIPTION
**Pull request by Learath2**
I hope this will be the last commit. Took longer then expected :(

### CODE REVIEW

**Comment by Learath2** [comment]
Could further align the extra lines with the name but this looks fine.

**Comment by Learath2** [comment]
Apparently not :(

**Comment by Learath2** [comment]
Apparently did fix that problem but there is another problem with a single long word.

**Comment by Learath2** [comment]
The overflowing text remains but seems to also happen when hearts are disabled. I'm lost here.

**Comment by def-** [comment]
Thanks!

**Pull request merged**
