### PR TITLE
Don't print pongs

### PR DESCRIPTION
**Pull request by def-**
as suggested by Sorah

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
Please leave it in or fix pings in f1 command `ping` aswell as scoreboard ping. This is the only real ping we have.

**Comment by heinrich5991** [comment]
You could put it into the ADDINFO output level if fokkonaut wants to keep it. Would that work? @fokkonaut

**Comment by fokkonaut** [comment]
Keep it in F1, we had a discussing on discord, that this was only requested because people use F1 as chat history, but we shouldnt remove the real purpose of it, but improve the chat to be scrollable then. Please keep the intention of the F1 console. Moving it to console window only wouldnt help at all, since most players including me play with it being disabled, and why should one alt tab out everytime joining a server just to see a real, and good ping?

**Comment by heinrich5991** [comment]
@fokkonaut You can change the console output level, I think it's called `console_output_level`.

**Comment by fokkonaut** [comment]
i dont think that should be a reason to remove this info

**Pull request closed without merging**
