### PR TITLE
Remove save group/layer button (fixes #1475)

### LINKED ISSUE #1475: Remove "save group/layer" button from editor
https://forum.ddnet.tw/viewtopic.php?f=48&t=6759

It's very easy to accidentally disable it and it doesn't seem useful at all. If you don't want to keep a layer, you just delete it.

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by 12pm** [comment]
Thanks :)

Layer buttons (editor.cpp:3354) need `CUI::CORNER_R` too, otherwise looks good

**Comment by fokkonaut** [comment]
why tho

**Comment by def-** [comment]
> Layer buttons (editor.cpp:3354) need CUI::CORNER_R too, otherwise looks good

Argh, I know I should've tested it.

> why tho, still part of vanilla client

What purpose does the button have?

**Comment by def-** [comment]
When you click the "S" button to disable a group from being saved then it won't be saved in the map file and when you open it in DDNet client that group is not there.

**Comment by fokkonaut** [comment]
oh, oka

**Pull request merged**
