### PR TITLE
Demo to video converter

### PR DESCRIPTION
**Pull request by H-M-H**
This adds a way to convert demos into mp4 (h.264) videos using ffmpeg-libraries. This feature is optional and defaults to off. It can be included by setting `ffmpeg.value = true` in config.lua.

Demos can be converted by playing them in the demoplayer and calling `start_video` and `stop_video` in local console. The videos will then be saved in the OS-dependent teeworlds data folder in the subdirectory video.

The number of FPS to use for recording can be specified by cl_video_recorder_fps which defaults to 60.

Internally this works by feeding the output of glReadPixels to ffmpeg-libs and synchronizing the time passed in the demo to the current frame that is going to be recorded. This can result (and mostly does) in the demoplayer looking laggy.

### CODE REVIEW

**Comment by H-M-H** [comment]
Recording audio is currently not supported.

**Comment by def-** [comment]
Very cool. Any time line for when this will be finished? Is just audio missing or more?

**Comment by H-M-H** [comment]
Recording video already works nicely. Things that still need to be done:
- audio (this is going to be funny as i need to sync it with the speed the video is recorded somehow; even the current demoplayer does not respect that with slower playingspeed the sound should also be played slower)
- add ffmpeg-libraries for other platforms than windows
- some cleanup as this still contains a few now unnecessary debug messages etc.
- update build instructions
- some tweaks to how the user can record videos
- check if doing it threaded is more performant

**Comment by PathosEthosLogos** [comment]
@H-M-H How about directly using the Teeworlds sound file to save into the video file? It'd basically be copy/pasting the audio file into the audio tracks of the video file.

I think this can be quite helpful for your "some tweaks to how the user can record videos" for slower computers. Let's say someone's computer can't really handle recording at 60 FPS at full resolution. The demo player can be slowed down to 0.25 or so and record at 15 FPS, then post-process it 4x faster. This would make the audios sync with the _regular speed_ video output still.

**Comment by H-M-H** [comment]
The problem about directly throwing the audiofiles into the video is that teeworlds does not just play them but processes them further which is why my initial idea was to just capture everything teeworlds spits out.

About slower computers: The thing about this is that it will generate perfect 60fps videos on any computer that can run the ddnet-client, replaying demos is automatically slowed down to capture every single frame :)

**Comment by PathosEthosLogos** [comment]
What are some of the other libraries considered besides FFmpeg?

Second point: I see. That's perfect.

First point: wouldn't that be more difficult?

**Comment by PathosEthosLogos** [comment]
@H-M-H How about an MVP (minimum viable product) for now? If demo is not being recorded at 1x speed, don't record audio at all. Audio recording can be implemented later. Just release the version where you can record the video for now and other things can be sorted out over time. I honestly think MVP is fine for now and if people really want it, they can record on OBS anyway, or include separate audio files themselves until more refined version of demo recording comes out.

**Comment by def-** [comment]
I agree, people keep asking for this, would be nice just to make some small videos to share quickly.

**Comment by ChillerDragon** [comment]
Is @H-M-H even active? I didn't see him for ages ._.
Uffa bam conflicts xd

**Comment by H-M-H** [comment]
I guess I will have a look at this again. As a matter of fact someone asked me about it recently and I rebased everything: https://github.com/H-M-H/ddnet/tree/video_rebased2, binaries for windows can be found here: https://github.com/H-M-H/Teeworlds-binaries

**Comment by def-** [comment]
@H-M-H So let's get it into DDNet even if it doesn't work perfectly I'd say. Improvements can come later and could be done by others too.

**Comment by fokkonaut** [comment]
Any updates on this? Still waiting ...

**Comment by sirius1242** [comment]
Sorry, why this PR not be merged and why still open?

**Comment by heinrich5991** [comment]
Superseded by #1928.

**Pull request closed without merging**
