### PR TITLE
Add check_dilate (WIP)

### PR DESCRIPTION
**Pull request by def-**
Not sure what files to check actually, many are apparently not dilated.

### CODE REVIEW

**Comment by def-** [comment]
I guess the editor auto-dilate is good enough for now.

**Comment by heinrich5991** [comment]
```
[2020-10-13 23:41:25][dilate]: /tmp/background.vly.png: not an RGBA image
[2020-10-13 23:41:41][dilate]: /tmp/checker.dR1.png: not an RGBA image
data/browse_icons.png is not dilated
data/countryflags/LY.png is not dilated
data/countryflags/default.png is not dilated
data/demo_buttons.png is not dilated
data/demo_buttons2.png is not dilated
data/editor/audio_source.png is not dilated
data/editor/entities/DDNet.png is not dilated
data/editor/entities/FNG.png is not dilated
data/editor/entities/Race.png is not dilated
data/editor/entities/Vanilla.png is not dilated
data/editor/entities/blockworlds.png is not dilated
data/editor/entities_clear/blockworlds.png is not dilated
data/editor/entities_clear/ddnet.png is not dilated
data/editor/entities_clear/ddrace.png is not dilated
data/editor/entities_clear/fng.png is not dilated
data/editor/entities_clear/race.png is not dilated
data/editor/entities_clear/vanilla.png is not dilated
data/editor/front.png is not dilated
data/editor/speedup.png is not dilated
data/editor/switch.png is not dilated
data/editor/tele.png is not dilated
data/editor/tune.png is not dilated
data/emoticons.png is not dilated
data/gui_icons.png is not dilated
data/gui_logo.png is not dilated
data/mapres/basic_freeze.png is not dilated
data/mapres/bg_cloud1.png is not dilated
data/mapres/bg_cloud2.png is not dilated
data/mapres/bg_cloud3.png is not dilated
data/mapres/ddnet_start.png is not dilated
data/mapres/ddnet_tiles.png is not dilated
data/mapres/desert_background.png is not dilated
data/mapres/desert_doodads.png is not dilated
data/mapres/desert_main.png is not dilated
data/mapres/desert_mountains.png is not dilated
data/mapres/desert_mountains_new_background.png is not dilated
data/mapres/desert_mountains_new_foreground.png is not dilated
data/mapres/desert_sun.png is not dilated
data/mapres/entities.png is not dilated
data/mapres/fadeout.png is not dilated
data/mapres/font_teeworlds.png is not dilated
data/mapres/font_teeworlds_alt.png is not dilated
data/mapres/generic_clear.png is not dilated
data/mapres/generic_deathtiles.png is not dilated
data/mapres/generic_lamps.png is not dilated
data/mapres/generic_unhookable.png is not dilated
data/mapres/generic_unhookable_0.7.png is not dilated
data/mapres/grass_doodads.png is not dilated
data/mapres/grass_doodads_0.7.png is not dilated
data/mapres/grass_main.png is not dilated
data/mapres/grass_main_0.7.png is not dilated
data/mapres/jungle_deathtiles.png is not dilated
data/mapres/jungle_doodads.png is not dilated
data/mapres/jungle_main.png is not dilated
data/mapres/jungle_unhookables.png is not dilated
data/mapres/moon.png is not dilated
data/mapres/mountains.png is not dilated
data/mapres/snow_mountain.png is not dilated
data/mapres/stars.png is not dilated
data/mapres/sun.png is not dilated
data/mapres/water.png is not dilated
data/mapres/winter_doodads.png is not dilated
data/mapres/winter_main.png is not dilated
data/mapres/winter_mountains.png is not dilated
data/mapres/winter_mountains2.png is not dilated
data/menuimages/demos.png is not dilated
data/menuimages/editor.png is not dilated
data/menuimages/local_server.png is not dilated
data/menuimages/play_game.png is not dilated
data/menuimages/settings.png is not dilated
data/particles.png is not dilated
data/skins/Aoe4leg.png is not dilated
data/skins/PaladiN.png is not dilated
data/skins/Terrorist.png is not dilated
data/skins/antiantey.png is not dilated
data/skins/beast.png is not dilated
data/skins/blacktee.png is not dilated
data/skins/bluekitty.png is not dilated
data/skins/chinese_by_whis.png is not dilated
data/skins/coala_bluekitty.png is not dilated
data/skins/coala_limekitty.png is not dilated
data/skins/coala_x_ninja.png is not dilated
data/skins/demonlimekitty.png is not dilated
data/skins/dino.png is not dilated
data/skins/dragon.png is not dilated
data/skins/evil.png is not dilated
data/skins/evilwolfe.png is not dilated
data/skins/ghost.png is not dilated
data/skins/ghostjtj.png is not dilated
data/skins/giraffe.png is not dilated
data/skins/greensward.png is not dilated
data/skins/greyfox.png is not dilated
data/skins/greyfox_2.png is not dilated
data/skins/hammie-chew.png is not dilated
data/skins/hammie-whis.png is not dilated
data/skins/jeet.png is not dilated
data/skins/kintaro_2.png is not dilated
data/skins/kitty_brownbear.png is not dilated
data/skins/kitty_x_ninja.png is not dilated
data/skins/limekitty.png is not dilated
data/skins/mermydon-coala.png is not dilated
data/skins/mermydon.png is not dilated
data/skins/mouse.png is not dilated
data/skins/musmann.png is not dilated
data/skins/nanami.png is not dilated
data/skins/nanas.png is not dilated
data/skins/nersif.png is not dilated
data/skins/oldman.png is not dilated
data/skins/oldschool.png is not dilated
data/skins/penguin.png is not dilated
data/skins/random.png is not dilated
data/skins/redbopp.png is not dilated
data/skins/santa_bluekitty.png is not dilated
data/skins/santa_bluestripe.png is not dilated
data/skins/santa_brownbear.png is not dilated
data/skins/santa_cammo.png is not dilated
data/skins/santa_cammostripes.png is not dilated
data/skins/santa_coala.png is not dilated
data/skins/santa_default.png is not dilated
data/skins/santa_limekitty.png is not dilated
data/skins/santa_pinky.png is not dilated
data/skins/santa_redbopp.png is not dilated
data/skins/santa_redstripe.png is not dilated
data/skins/santa_saddo.png is not dilated
data/skins/santa_toptri.png is not dilated
data/skins/santa_twinbop.png is not dilated
data/skins/santa_twintri.png is not dilated
data/skins/santa_warpaint.png is not dilated
data/skins/teerasta.png is not dilated
data/skins/veteran.png is not dilated
data/skins/voodoo_tee.png is not dilated
data/skins/wartee.png is not dilated
data/skins/whis.png is not dilated
data/skins/x_ninja.png is not dilated
data/themes/auto.png is not dilated
data/themes/autumn.png is not dilated
data/themes/heavens.png is not dilated
data/themes/jungle.png is not dilated
data/themes/none.png is not dilated
data/themes/rand.png is not dilated
data/themes/winter.png is not dilated
```

@Jupeyy These all need to be dilated?

**Comment by Jupeyy** [comment]
I think a lot are still dilated with the old version of the tool. Flags that don't contain 
Also some of these images shouldn't contain transparent pixels, dunno why they are listed here

Generally it's safe to dilate all. For 2d array textures I'd only be required if transparent and opaque pixels are mixed for at least one tile.  So just dilate xd

**Comment by Jupeyy** [comment]
ok just checked, and yes, i assume that all these files are dilated with the old tool, so if we update them, they should not show not dilated again

**Comment by Jupeyy** [comment]
If we still want this, we should make sure, we only compare the dilated files after unpacking the pngs,
deen optimized some PNGs with zopflipng, and it'd be nice to still have the possibility to use such optimizers

**Comment by Jupeyy** [comment]
Fixed the shell script a bit locally: https://github.com/Jupeyy/ddnet/tree/pr-check_dilate
sadly the dilate of ubuntu is outdated?
I made it work for my debian now, but would like to test it with the github workflow to be sure :D

**Comment by Jupeyy** [comment]
I think i finished this:

Here is an output example if it fails:
https://github.com/Jupeyy/ddnet/runs/1446892909

**Comment by def-** [comment]
Great, can you upload it?

**Comment by Jupeyy** [comment]
<details>
	<summary>Skin database</summary>
	
	List:

	undead.png is not dilated
	ChuCky.png is not dilated
	coala_phoenix.png is not dilated
	Cactus.png is not dilated
	Steilgeher.png is not dilated
	Saddocybe.png is not dilated
	Yellow ray.png is not dilated
	bomb_exploded.png is not dilated
	Yellow.png is not dilated
	bunny.png is not dilated
	todeskind_skin.png is not dilated
	liari.png is not dilated
	Scholar.png is not dilated
	emotion_robot.png is not dilated
	greyfoxcyborg.png is not dilated
	Orange_Camouflage.png is not dilated
	Zippahpurple.png is not dilated
	zombie.png is not dilated
	mermydon_blue.png is not dilated
	foxi.png is not dilated
	nava.png is not dilated
	jeet.png is not dilated
	Tidon.png is not dilated
	kittygw.png is not dilated
	bomb.png is not dilated
	troll.png is not dilated
	pikminwhite.png is not dilated
	t2.png is not dilated
	zangoosetee.png is not dilated
	hammie.png is not dilated
	zomby.png is not dilated
	draw.png is not dilated
	caesar.png is not dilated
	Chameleon.png is not dilated
	hottyai3.png is not dilated
	krieger.png is not dilated
	WolfTee.png is not dilated
	Soldier2.png is not dilated
	racer_lime.png is not dilated
	squammo.png is not dilated
	Neron.png is not dilated
	greyfox.png is not dilated
	kurokonobasuke_dog.png is not dilated
	EyeBall.png is not dilated
	WARskin.png is not dilated
	planet.png is not dilated
	Red.png is not dilated
	mmor.png is not dilated
	Bub.png is not dilated
	Bob.png is not dilated
	Tutawek.png is not dilated
	Straw Crytek.png is not dilated
	alphatee.png is not dilated
	teletinkywinky.png is not dilated
	Colory BLACK.png is not dilated
	Black Phantom.png is not dilated
	White.png is not dilated
	Tunda.png is not dilated
	sordes2.png is not dilated
	Haire.png is not dilated
	ice cat.png is not dilated
	Cowboy.png is not dilated
	tkitty_nohar.png is not dilated
	Greeny.png is not dilated
	Voodoo_tee_1.png is not dilated
	skorpion.png is not dilated
	Icetee.png is not dilated
	redz.png is not dilated
	Fox.png is not dilated
	Gengar.png is not dilated
	Manaphy.png is not dilated
	Chincat.png is not dilated
	Panda.png is not dilated
	red_bird.png is not dilated
	Sentret.png is not dilated
	Shadowtee.png is not dilated
	Lord_of_Zombie.png is not dilated
	planet_earth.png is not dilated
	chao.png is not dilated
	x_ninja.png is not dilated
	Blue.png is not dilated
	Ben.png is not dilated
	Chinswords.png is not dilated
	Babygamer-ninja.png is not dilated
	Bomb 2.png is not dilated
	catalin.png is not dilated
	hedgehog.png is not dilated
	kintaro_2.png is not dilated
	foks.png is not dilated
	pepsicoala.png is not dilated
	Rock_Lee.png is not dilated
	roman.png is not dilated
	flokes.png is not dilated
	Beast_1.png is not dilated
	m&mred.png is not dilated
	tamedwolf.png is not dilated
	m&myellow.png is not dilated
	pepsi.png is not dilated
	telepo.png is not dilated
	Shadow.png is not dilated
	pikminpurple.png is not dilated
	lolhair.png is not dilated
	Mycel.png is not dilated
	SpotTee.png is not dilated
	nosey.png is not dilated
	Mr.Rock.png is not dilated
	clefairy.png is not dilated
	gladiator.png is not dilated
	Fighta.png is not dilated
	Fighter.png is not dilated
	Peef.png is not dilated
	Kimmo_3.png is not dilated
	Flying Silex.png is not dilated
	Electro Tee.png is not dilated
	Ablush NeoN.png is not dilated
	Mobys Skull.png is not dilated
	Pachirisu.png is not dilated
	Samuraitee.png is not dilated
	splashtee.png is not dilated
	musictee2.png is not dilated
	dragon 2.png is not dilated
	dino.png is not dilated
	lady.png is not dilated
	demonlimekitty.png is not dilated
	Blind r0xr.png is not dilated
	Blinded.png is not dilated
	Omfg_tee.png is not dilated
	Energy_personal.png is not dilated
	Farmer.png is not dilated
	Chinman2.png is not dilated
	ram.png is not dilated
	OLD Tee.png is not dilated
	random.png is not dilated
	Colors.png is not dilated
	waddletee.png is not dilated
	redam.png is not dilated
	hammie-chew.png is not dilated
	Crazy.png is not dilated
	Apple green.png is not dilated
	amina_kitty.png is not dilated
	P-SkizZ 2.png is not dilated
	SteelCammo.png is not dilated
	turtle_l.png is not dilated
	sordes.png is not dilated
	Puar.png is not dilated
	nyu2.png is not dilated
	Fluffy_1.png is not dilated
	emo.png is not dilated
	sweetdog.png is not dilated
	Chan.png is not dilated
	musmann.png is not dilated
	almostcoala.png is not dilated
	Irradiated Sunny.png is not dilated
	soul.png is not dilated
	nanosuit.png is not dilated
	drizzle.png is not dilated
	Bat.png is not dilated
	Fluffy.png is not dilated
	planet_saturn.png is not dilated
	triumph.png is not dilated
	chera.png is not dilated
	napoleon.png is not dilated
	Bonsly.png is not dilated
	Mudkip.png is not dilated
	LeO.png is not dilated
	future.png is not dilated
	Egg.png is not dilated
	Red Coke.png is not dilated
	power_beam.png is not dilated
	Green.png is not dilated
	military_stripes.png is not dilated
	MummyBear.png is not dilated
	tails.png is not dilated
	Blit.png is not dilated
	evilwolfe.png is not dilated
	Demon.png is not dilated
	dynamite.png is not dilated
	Green person.png is not dilated
	giraffe.png is not dilated
	deer.png is not dilated
	Startee.png is not dilated
	Red_Tiger.png is not dilated
	laservis0rtee.png is not dilated
	Sayn.png is not dilated
	Musictee3.png is not dilated
	paintgree.png is not dilated
	PaladiN 2.png is not dilated
	Boink.png is not dilated
	meta-knight.png is not dilated
	mermydon.png is not dilated
	hpn_hat.png is not dilated
	mewtu.png is not dilated
	bugofdoom.png is not dilated
	sirtee.png is not dilated
	blackstripe.png is not dilated
	Redboppenom.png is not dilated
	greensward.png is not dilated
	bauer.png is not dilated
	pokeball.png is not dilated
	spiderpig.png is not dilated
	Bam.png is not dilated
	Wolfie.png is not dilated
	sportee.png is not dilated
	kirby.png is not dilated
	planet_mars.png is not dilated
	Cooldown.png is not dilated
	mauzi.png is not dilated
	mario.png is not dilated
	Azumarill.png is not dilated
	Master_of_disguise.png is not dilated
	zoro.png is not dilated
	greyfox_2.png is not dilated
	fuck_yeah.png is not dilated
	Chinman.png is not dilated
	taijitee.png is not dilated
	kirby blue.png is not dilated
	Colorful TEE.png is not dilated
	Mummy.png is not dilated
	Evil Puffi.png is not dilated
	dashie.png is not dilated
	morty.png is not dilated
	Cowgirl.png is not dilated
	tkitty.png is not dilated
	kitty_brownbear.png is not dilated
	fluttertee.png is not dilated
	Locked.png is not dilated
	fairo.png is not dilated
	hvad.png is not dilated
	Grizli.png is not dilated
	Cyclops.png is not dilated
	Terrorist.png is not dilated
	peruchan.png is not dilated
	Bouldy.png is not dilated
	Azurill.png is not dilated
	ninja2.png is not dilated
	Kasper.png is not dilated
	Teentacion.png is not dilated
	amor.png is not dilated
	luigiteemd2.png is not dilated
	mermydon-coala.png is not dilated
	turtle_r.png is not dilated
	Big_tee.png is not dilated
	Marill.png is not dilated
	masterchief.png is not dilated
	Mainblack2.png is not dilated
	Rapper.png is not dilated
	military man.png is not dilated
	bluekittydemon.png is not dilated
	Hairy coala.png is not dilated
	Acid.png is not dilated
	cutie.png is not dilated
	turtle_m.png is not dilated
	begoggled.png is not dilated
	speedpunk.png is not dilated
	coala_ninja.png is not dilated
	ghostjtj.png is not dilated
	mike.png is not dilated
	zombie3.png is not dilated
	sasuke.png is not dilated
	Tutawek1.png is not dilated
	Chinlila.png is not dilated
	SkeleTee.png is not dilated
	Mouse_tee.png is not dilated
	coala_limekitty.png is not dilated
	masa-san.png is not dilated
	Japanese.png is not dilated
	Twinbobpenom.png is not dilated
	wartee.png is not dilated
	Batman.png is not dilated
	tintintee.png is not dilated
	demonbear.png is not dilated
	Yroo.png is not dilated
	cute_coala.png is not dilated
	Demigod.png is not dilated
	Frent.png is not dilated
	raupi.png is not dilated
	zombie1.png is not dilated
	Steel.png is not dilated
	Apish Coke.png is not dilated
	sharp.png is not dilated
	chinese.png is not dilated
	monkey.png is not dilated
	greyflokes.png is not dilated
	Toykeb.png is not dilated
	tiger.png is not dilated
	warpaint_trela.png is not dilated
	togepi.png is not dilated
	whitehead.png is not dilated
	P-Rush1.png is not dilated
	Green ray.png is not dilated
	skeyster.png is not dilated
	jotaro.png is not dilated
	4coca.png is not dilated
	Serfer.png is not dilated
	hero_chao.png is not dilated
	robin_hood.png is not dilated
	pandabear.png is not dilated
	Volt.png is not dilated
	mermyfox.png is not dilated
	pumpkin.png is not dilated
	Trey.png is not dilated
	PaladiN.png is not dilated
	fuzzy_coala.png is not dilated
	pbody.png is not dilated
	spidibx8.png is not dilated
	godlike.png is not dilated
	White_tee.png is not dilated
	Pogok.png is not dilated
	Name.png is not dilated
	ghost.png is not dilated
	ts2_contest_skin.png is not dilated
	eliteknight.png is not dilated
	water.png is not dilated
	penguin.png is not dilated
	handsome man.png is not dilated
	hurted.png is not dilated
	rainbowo.png is not dilated
	swordl.png is not dilated
	mouse.png is not dilated
	coala_bluekitty.png is not dilated
	potato_tee.png is not dilated
	Magic_tee.png is not dilated
	Hosmy.png is not dilated
	Trey_z.png is not dilated
	Zombie_brownbear.png is not dilated
	teledipsy.png is not dilated
	Programmer four-eyes.png is not dilated
	sweet.png is not dilated
	darkforce.png is not dilated
	sensei_wu.png is not dilated
	flame.png is not dilated
	twintrikitty.png is not dilated
	twinyellow.png is not dilated
	eartee2.png is not dilated
	GREEN Hairy.png is not dilated
	limekitty.png is not dilated
	duobopp.png is not dilated
	Matrose.png is not dilated
	P-Petroceli.png is not dilated
	greyshades.png is not dilated
	Writer.png is not dilated
	trela.png is not dilated
	viking.png is not dilated
	Sui.png is not dilated
	teerasta.png is not dilated
	Sharpy one.png is not dilated
	hot.png is not dilated
	noob.png is not dilated
	red_flame.png is not dilated
	rick.png is not dilated
	Teemafia.png is not dilated
	atlas.png is not dilated
	furofdoom.png is not dilated
	Ness.png is not dilated
	silverteenu1.png is not dilated
	turtle_d.png is not dilated
	headphoneearstee.png is not dilated
	zetfighter.png is not dilated
	goku.png is not dilated
	Trey_top.png is not dilated
	stripespiky.png is not dilated
	Dandy.png is not dilated
	Froze.png is not dilated
	planet_uranus.png is not dilated
	tweety.png is not dilated
	Smiley.png is not dilated
	teebone.png is not dilated
	fuzzy_limekitty.png is not dilated
	yellow_bird.png is not dilated
	Pikachu.png is not dilated
	Kimmo.png is not dilated
	Sonic.png is not dilated
	ZekkeN.png is not dilated
	naruto.png is not dilated
	eartee.png is not dilated
	Commander.png is not dilated
	Cyan.png is not dilated
	savage.png is not dilated
	Hidden Assassin.png is not dilated
	L-thinking.png is not dilated
	reaper.png is not dilated
	Twinbop-Sword.png is not dilated
	Tangela.png is not dilated
	Programmer.png is not dilated
	nanas.png is not dilated
	Pro-Ninja.png is not dilated
	yetti.png is not dilated
	zombie2.png is not dilated
	Demix.png is not dilated
	pikminyellow.png is not dilated
	iceberg.png is not dilated
	Blue ray.png is not dilated
	Yao_ming.png is not dilated
	Jirachi.png is not dilated
	Sharpy two.png is not dilated
	wolf.png is not dilated
	Kimmo_2.png is not dilated
	Fashion_tee.png is not dilated
	Red and White.png is not dilated
	sea.png is not dilated
	Voodoo_tee.png is not dilated
	DoD-Skin!!!.png is not dilated
	PsychoGod.png is not dilated
	hypecack.png is not dilated
	Silver.png is not dilated
	whis.png is not dilated
	Dante.png is not dilated
	spike.png is not dilated
	Grizz.png is not dilated
	dark_chao.png is not dilated
	catwhis.png is not dilated
	Soldier.png is not dilated
	Robot.png is not dilated
	nanami.png is not dilated
	enjilly.png is not dilated
	telelaalaa.png is not dilated
	redbopp.png is not dilated
	nersif.png is not dilated
	Hormz.png is not dilated
	Energy.png is not dilated
	glitch.png is not dilated
	mainblack.png is not dilated
	evil.png is not dilated
	boo.png is not dilated
	Jericho.png is not dilated
	DuMoH.png is not dilated
	gladiator_godlike.png is not dilated
	Arab.png is not dilated
	darky.png is not dilated
	MummyFoxy.png is not dilated
	oldschool.png is not dilated
	Russian man.png is not dilated
	Samurai.png is not dilated
	Snorlax.png is not dilated
	mariotee.png is not dilated
	Kitty.png is not dilated
	bluekitty.png is not dilated
	Tee in BLACK.png is not dilated
	veteran.png is not dilated
	Purple.png is not dilated
	zzz.png is not dilated
	dragon.png is not dilated
	zombie4.png is not dilated
	Hippy.png is not dilated
	kotin.png is not dilated
	antiantey.png is not dilated
</details>

**Comment by def-** [comment]
I'm wondering if the identify tool is too finicky somehow. Are those really all not dilated?

**Comment by Jupeyy** [comment]
I assume most are dilated with the old tool, which produces slightly different output

**Comment by Jupeyy** [comment]
see the example in https://github.com/ddnet/ddnet/pull/2888

**Pull request merged**
