### PR TITLE
Replace some global g_Configs with Config()

### PR DESCRIPTION
**Pull request by ChillerDragon**
Road to no globals :D

Also solves the null pointer trap for components since gameclient did not set m_pClient yet. So components using Client() run into nullptr issues.

## Checklist

- [X] Tested the change ingame (Might need more testing before release since a lot of code is affected)
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
This has conflicts, can you also quickly show the 3 changed lines
Else i have nothing against it, but i could assume new prs ignore it, as its not forced, and in alot of places it's much harder than this :D

**Comment by Learath2** [comment]
I flat out don't like this, why are we avoiding globals? Storing configuration is a perfect use for a global.

**Comment by Jupeyy** [comment]
Maybe at some point we could split the dummy instance from the main instance and have less bugs

**Comment by Learath2** [comment]
If by split you mean to another thread the thing you are looking for is a mutex. If by split you mean within the same thread it's perfectly fine to access a global like that.

There really is no benefit to this change in my opinion

**Comment by Jupeyy** [comment]
With split i mean the whole gameclient
So instead of having [2] everywhere
you'd start 2 clients, that only share some stuff like graphics

**Comment by Learath2** [comment]
Hm, I don't really see how having a non-global config would help

**Comment by Jupeyy** [comment]
> Hm, I don't really see how having a non-global config would help

Ah i thought you mean globals in general, e.g. we have alot of static use in many components
As for config you might be right, maybe if we want to support multi config, or allow the server to exist in the same process

**Comment by heinrich5991** [comment]
Status: Seems @Learath2 doesn't like it, I don't really care. So currently a no?

**Comment by heinrich5991** [comment]
Apparently we don't like code changes that solely make us look more like upstream.

Thanks for the efforts though, @ChillerDragon.

**Pull request closed without merging**
