### PR TITLE
Only sort friends, if you got any

### PR DESCRIPTION
**Pull request by Jupeyy**
as TsFreddie pointed out, it asserts inside the array function back(), bcs the list is empty.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Sort function should work when the list is empty I think. I would prefer to have that fixed.

**Comment by Jupeyy** [comment]
yeah the sort isnt really the problem, its the back() function in the teeworlds list data structure that complains

**Comment by def-** [comment]
I still think the sort_range implementation should be changed.

**Comment by Jupeyy** [comment]
so u want me to check it there or what do you mean with changed?

**Comment by def-** [comment]
Ok, thanks :D One step further: Shouldn't the all() function return an empty range if it's called for a size 0 range? I'm not that familiar with the tl code.

**Comment by Jupeyy** [comment]
I am even less familiar with that code xD
Always prefered STL

Dunno what to put there, two NULL pointers?

**Comment by def-** [comment]
I tried reproducing it in a unit test but failed:
```
TEST(SortedArray, Foo)
{
	sorted_array<int> x;
	x.sort_range();
}
```
Shouldn't this fail?

**Comment by Jupeyy** [comment]
> I tried reproducing it in a unit test but failed:
> 
> ```
> TEST(SortedArray, Foo)
> {
> 	sorted_array<int> x;
> 	x.sort_range();
> }
> ```
> 
> Shouldn't this fail?

did you build in release mode? its an debug assert i think

**Comment by def-** [comment]
Thanks, that helps.

**Comment by def-** [comment]
bors r+
Eh, this range stuff is weird. I added my test at least.

**Pull request merged**
