### PR TITLE
Refactor nameplate rendering, slightly improve performance

### PR DESCRIPTION
**Pull request by Robyt3**
See commit messages.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [X] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by fokkonaut** [comment]
Please let it not break rainbowname🥲

**Comment by Robyt3** [comment]
> Please let it not break rainbowname🥲

Could you test that with these changes?

**Comment by fokkonaut** [comment]
> > Please let it not break rainbowname🥲
> 
> Could you test that with these changes?

Yes, will do

**Comment by heinrich5991** [comment]
> > Could you test that with these changes?
> 
> Yes, will do

What's the result of the tests?

**Review by heinrich5991 — APPROVED** [review]
Looks good to me, thanks!

**Review by fokkonaut — APPROVED** [review]

**Pull request merged**
