### PR TITLE
Implement reserved nicks

### PR DESCRIPTION
**Pull request by Learath2**
Not really sure about the way I added this in. In DDNet/DDRace code it's a pretty blurry line between `CServer` & `CGameContext`.

### CODE REVIEW

**Comment by def-** [comment]
> I think kicking people for having the wrong nick is a pretty strong thing to do.

Yeah, forced rename to "nameless tee" sounds more reasonable. Clan tag would not be distinguishable enough since it only appears in scoreboard, not in chat.

**Comment by Learath2** [comment]
Damn that would have been significantly simpler to implement. :(

**Comment by def-** [comment]
I guess this is "accounts light" and the next step is to give the well-known players such reserved nicks as well with a powerless rcon login.

**Comment by Learath2** [comment]
It's pretty reasonable to assume staff names are reserved though. jao hasn't been able to play with his own name in a while now.

Faking any standard tee has not much of a downside, but faking staff makes us look bad/ineffective. People expect that when they see a staff member on the scoreboard that the server will be moderated.

**Comment by def-** [comment]
Well, faking well known tees has the advantage of making you look respectable. So that's why I'd consider that the next step after this.

**Comment by Learath2** [comment]
Reserving nicks is a very touchy-feely issue in this community from what I see. I doubt most will agree with reserving nicks which is why I avoided that in all my accounts proposals.

**Comment by heinrich5991** [comment]
I like the way Quakenet handles their accounts: Not tied to a nickname. A friend of mine likes to call themselves "Blue", if we had reserved nicknames for players, this would not be possible.

Most online gaming platforms have abandoned the "reserved nickname" concept (off the top of my head: Steam, Discord, Battle.net, I think Minecraft does have identity tied to nicknames). It might be that I just don't play the games where this concept is still alive: I don't know about the EA platform, the Ubisoft platform, the Xbox platform (does that exist?), the Nintendo platform.

The thing we're after seems to be some recognition for staff members. Maybe we should highlight them in scoreboard/chat messages?

**Comment by heinrich5991** [comment]
Some IRC channels highlight staff members with @ (others do not, see many freenode channels). Discord highlights admins by color by default, Teamspeak (another platform without ties between nickname and identity) puts an icon behind their name.

**Comment by Learath2** [comment]
Freenode does reserve nicks using NickServ no?

**Comment by heinrich5991** [comment]
Freenode does it, but by default it allows other people to join with the nick. That's why I mentioned that I like the way Quakenet does it. :)

**Comment by Learath2** [comment]
For normal tees, I agree completely. Because there is no way to know who is
who. But in this case there is a nice clean line and it's crystal clear who
the nick belongs to which is why I'm okay with this usecase.

I don't see any non malicious use of using a staff members nick.

**Comment by Learath2** [comment]
Does marking really solve the problem at hand though? jao still wouldn't be able to play with his name and it'd still be possible that a "Learath2" ingame isn't me and thus isn't able to moderate.

@snailx3 && @12pm what do you think?

**Comment by heinrich5991** [comment]
What is the problem that results in jao not being able to play?

The Learath2 is the real one if it's marked in the score board — maybe we should have some form of (secure!) autologin.

**Comment by 12pm** [comment]
> The solution of marking staff members in the score board/chat only improves the current situation, without making anything worse.

I would prefer that too, but you rejected a similar thing here https://github.com/ddnet/ddnet/pull/1001#issuecomment-374422269. Is that now ok for you?

**Comment by heinrich5991** [comment]
> Is that now ok for you?

I definitely like this more than reserving nicks, so yes, I think this is OK for me now.

**Comment by Learath2** [comment]
So what kind of indicator would you guys prefer? @, + like in IRC, colors like in Discord or other symbols?

**Comment by 12pm** [comment]
Colored is most obvious and least confusing imo

**Comment by def-** [comment]
colored is fine. 🙈 also works

**Comment by def-** [comment]
Any progress @Learath2 ?

**Comment by Learath2** [comment]
One issue with colors is that we already color teams. Not sure how that should work

**Comment by 12pm** [comment]
The name itself isn’t colored tho (in scoreboard

**Comment by def-** [comment]
@Learath2 Still working on this?

**Comment by Learath2** [comment]
Forgot about this one, I'll give it a try tomorrow :/

**Pull request closed without merging**
