### PR TITLE
Highlight 0XF game type

### PR DESCRIPTION
**Pull request by 0xfaulty**
Highlight 0XF game type

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Can you explain what 0xf is, got a link?

**Comment by gerdoe-jr** [comment]
Block modification afair

**Comment by 0xfaulty** [comment]
> Can you explain what 0xf is, got a link?

A DDNet-based modification designed more for "Block", with its own system of accounts, clans, various tournaments, many visual additions etc..

**Review by def- — APPROVED** [review]
bors r+

**Pull request merged**
