### PR TITLE
Fix text rendering over maximum line width with newline

### LINKED ISSUE #4541: text renderer prints over width with newline
happens in our default motd for example
Screenshot 2021-12-28 at 01 14 16

### PR DESCRIPTION
**Pull request by Robyt3**
When a word is rendered over the maximum line width it should be moved to the next line.

However, this was not working correctly if the word ends with a newline instead of a space, because then the text x-advance including this word did not exceed the maximum width, as the newline caused the x-advance to be reset before it can be used.

This is fixed by replacing the unused flag `TEXTFLAG_ALLOW_NEWLINE` with the flag `TEXTFLAG_DISALLOW_NEWLINE`, which causes newline characters to be replaced with space characters. This flag is then used when calculating whether the next word fits in the current line.

Closes #4541.

Before:

newline old

After:

newline new

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Does this break our official motds?

**Comment by Robyt3** [comment]
Official motds should be unaffected:

screenshot_2023-02-22_10-20-05

**Comment by def-** [comment]
Screenshot 2023-02-26 at 13 01 20
Doesn't look great on some servers, not sure how best to deal with it.

**Comment by Robyt3** [comment]
Maybe you can apply some heuristic to detect long mapper lines and then add explicit newlines after commas as well as another line segment for the box.

**Pull request merged**
