### PR TITLE
Pick client icon file based on client name

### PR DESCRIPTION
**Pull request by ChillerDragon**
convenience for downstream projects that renamed the client

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]
bors r+

**Comment by heinrich5991** [comment]
This breaks builds that change `CLIENT_EXECUTABLE`. It should probably be reverted.

**Comment by ChillerDragon** [comment]
> This breaks builds that change `CLIENT_EXECUTABLE`. It should probably be reverted.

Yes it breaks builds that renamed the executable but not the icon.

**Comment by heinrich5991** [comment]
`CLIENT_EXECUTABLE` is currently a user-settable config variable. When you change it in the DDNet build, it breaks the build. Maybe it shouldn't be a config variable? But if it is one, then changing it shouldn't break the build.

**Comment by Robyt3** [comment]
Maybe we can just rename the icon files so they don't contain the name of the game?

**Comment by heinrich5991** [comment]
That's an option, but I don't know if that would suit @ChillerDragon.

**Comment by ChillerDragon** [comment]
My idea was it being a feature that the icon files have to be renamed so one can edit the icons without getting conflicts when ddnet updates them. But I guess Heinrich has a point it might cause more trouble than it solves it for users that quickly wanna rename the binary without worrying about icons. I'm totally fine with a revert.

**Pull request merged**
