### PR TITLE
Automatically register ddnet:// url handler on macOS

### PR DESCRIPTION
**Pull request by def-**
Should work automatically on first time running client.

See https://hublog.hubmed.org/archives/001154

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
It's registered, but client doesn't get the url via command line argument, let me check: https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app

**Comment by def-** [comment]
Ok, there is nothing on command line being passed, we might need this in the obj-c layer: https://developer.apple.com/documentation/foundation/nsurlprotocol?language=objc

**Comment by Jupeyy** [comment]
you could try sdl-main

it's the recommended cross platform solution anyway

I think i used it for the android port on the client

**Comment by Jupeyy** [comment]
https://stackoverflow.com/questions/53129883/url-scheme-not-registed-while-debugging

this is maybe interesting, in case u didnt find a solution yet

**Comment by Robyt3** [comment]
Did you not want to put this in a separate executable (#6072)? Or do we only want a separate one for Windows, because we need admin privileges? We could also add a separate code branch in the client that installs the protocol/filetype handler and then immediately quits, so the client would launch itself with admin privileges and the sub-process immediately exits, so there is little risk that the client does anything bad while it has admin privileges.

**Comment by def-** [comment]
Would be great if you can do it for Windows. I found out macOS has this way, which works automatically. So no need for a separate file. Every application you move into Applications folder is automatically registered for all protocols it claims to support.

**Comment by def-** [comment]
Works on macOS now, ready for review.

Could also be extended to support opening .map and .demo files easily.

**Comment by def-** [comment]
Works with demo and map files into client too.

Making it work with DDNet-Server would require implementing this from SDL2 ourselves, maybe not worth it: https://github.com/spurious/SDL-mirror/blob/master/src/video/cocoa/SDL_cocoawindow.m#L144

**Comment by Robyt3** [comment]
Thanks. Dropping `.demo` and `.map` files also works on Windows.

bors r+

**Pull request merged**
