### PR TITLE
Optimize CCollision::MoveBox to stop looping once velocity is 0

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Have you tested that this doesn't decrease performance for the common case too much? We now compute square roots for every unit each tee moves.

**Comment by def-** [comment]
Ok, new try.

**Comment by fokkonaut** [comment]
`if(Vel == vec2(0,0))`

**Comment by def-** [comment]
Done.

**Comment by Learath2** [comment]
I think this one looks good, but I have one last concern, does the velocity actually become `vec2(0,0)` this might need proper floating point comparison as `vector2_base` doesn't implement it.

**Comment by heinrich5991** [comment]
You can imagine basic floating point operations like `+`, `*` etc. to be done exactly, and then rounded to the accuracy of the floating point. This completely reflects the results.

Since 0.0 is a representable float, `Vel.y *= -0.0` will make `Vel.y` `-0.0` or `0.0`, depending on the sign of `Vel.y` before the operation. Since `0.0 == -0.0`, this doesn't cause issues.

LGTM, thanks.

bors r+

**Pull request merged**
