### PR TITLE
Try using Windows 2022 (fixes #4658)

### LINKED ISSUE #4658: Window CI is broken
https://github.com/ddnet/ddnet/pull/4657#issuecomment-1030106374

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
[Visual Studio 17 2022](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html)

**Comment by def-** [comment]
I noticed too.

**Comment by Jupeyy** [comment]
:/ maybe its just broken :D

**Comment by def-** [comment]
Nope, works.

**Comment by Jupeyy** [comment]
nice
bors r+

**Pull request merged**
