### PR TITLE
Editor improvements

### PR DESCRIPTION
**Pull request by BannZay**
Short list of what has been done:
1. Added key bindings to buttons (Load Current map, grid, Tele, Switch, etc...)
2. Reordered top menu. Added conditions whether show button set or not
3. Added "Find empty slot" for tele/switch button

I still work with it but I would like to deliver my changes with small merge requests in order to avoid future code merge conflicts

### CODE REVIEW

**Comment by heinrich5991** [comment]
This looks good, thanks for making this pull request.

Could you change your variable naming to adhere to Teeworlds conventions? It's CamelCase with the first letter also as a capital letter.

**Comment by BannZay** [comment]
Sorry about that. Should be fixed now

**Comment by heinrich5991** [comment]
Last thing I saw: `static int PreviousNumber` → `static int s_PreviousNumber` in two functions.

**Comment by heinrich5991** [comment]
Thanks for your persistence!

bors r+

**Comment by BannZay** [comment]
Thank you for the assistance! :)

**Pull request merged**
