### PR TITLE
Cherry-pick bam 0.5.0 fix from vanilla

### LINKED ISSUE #506: Fails building with bam 0.5.x
When building DDNet with bam 0.5.0, the following error message is displayed and building won't continue:

> $ bam  -t -t release
[string "src/base.lua"]:38: this file for version 0.4.x of bam. you are running 0.5.x.
backtrace:
  [string "src/base.lua"](38): CheckVersion global
  bam.lua(1): (null) 
bam: script error (-t for more detail)

Environment: Arch Linux 64-bit, [bam 0.5.0-1](https://www.archlinux.org/packages/community/x86_64/bam/), [lua 5.3.3-1](https://www.archlinux.org/packages/extra/x86_64/lua/), AUR package: [teeworlds-ddnet](https://aur.archlinux.org/packages/teeworlds-ddnet) (I'm the maintainer of this package)

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #506.

### CODE REVIEW

**Comment by def-** [comment]
Does this mean we can't build with bam 0.4 anymore?

**Comment by heinrich5991** [comment]
Yes.

**Comment by def-** [comment]
That sounds like a problem. Now people need bam 0.4 to build every teeworlds mod and bam 0.5 to build DDNet. What's the advantage of using bam 0.5?

**Comment by heinrich5991** [comment]
Yes, it sounds like a problem. The advantage is that people are going to get bam 0.5 at some point in their distributions (like Arch Linux has already, see #506), and we need bam 0.5 for vanilla Teeworlds already.

**Comment by def-** [comment]
Vanilla Teeworlds 0.6 is also using bam 0.4. Teeworlds 0.7 is not released from what I know.

**Pull request closed without merging**
