### PR TITLE
Move key constants to namespace to avoid conflicts

### PR DESCRIPTION
**Pull request by ChillerDragon**
Fixes the windows conflict. And allows to include ncurses without headache.

## Checklist

- [x] Tested the change ingame
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by ChillerDragon** [comment]
> Have you considered only including one of these at a time?

Well I managed to include ncurses by following the include with a bunch of undefs like ``undef KEY_BACKSPACE``

Not sure who one includes one of these at a time.

**Comment by def-** [comment]
> Not sure how one includes one of these at a time.

Make sure that each cpp either includes the ddnet key constant header, or the ncurses one. None both.

**Comment by ChillerDragon** [comment]
> > Not sure how one includes one of these at a time.
> 
> Make sure that each cpp either includes the ddnet key constant header, or the ncurses one. None both.

I doubt that works. keys.h is used all over the place.

**Comment by Jupeyy** [comment]
I guess generally a namespace makes sense. A proper namespace prefix might be nicer tho, TW_KEY or whatever, else we have the same problem some day again

**Comment by heinrich5991** [comment]
I made a src/engine/client/client2.cpp file with the following contents:
```c++
#include "client.h"

#include <stdio.h>

int test()
{
	printf("%d\n", KEY_BACKSPACE);
	return 0;
}
```

It gave me this error:
```
src/engine/client/client2.cpp: In function ‘int test()’:
src/engine/client/client2.cpp:7:24: error: ‘KEY_BACKSPACE’ was not declared in this scope
    7 |         printf("%d\n", KEY_BACKSPACE);
      |                        ^~~~~~~~~~~~~
```

So you can apparently create a file only including one of ncurses.h or keys.h. Please do that. Contact me if you need help.

This makes the PR superfluous.

**Comment by ChillerDragon** [comment]
I solved it by undefining the keys

```
#include "terminalui_keys.h" /* undefines conflicting ncurses key codes */
#include <ncurses.h>
``` 

https://github.com/chillerbot/chillerbot-ux/blob/81b604a1c8d48fc284adbc0646d606b0056adabf/src/game/client/components/chillerbot/terminalui_keys.h

**Pull request closed without merging**
