### PR TITLE
Add disallow entities option

### PR DESCRIPTION
**Pull request by fokkonaut**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
What's the use case for this option?

At first, it seems user-hostile to me.

**Comment by fokkonaut** [comment]
> What's the use case for this option?
> 
> At first, it seems user-hostile to me.

I would need it in my mod, where players have no name and can hide behind bushes to survive and trick other players. Of course this option should be used carefully from a server developer to not distract players. If chosen wrongly, it could make players rage, but that's their own fault then.

**Comment by ChillerDragon** [comment]
Hiding behind doodads is also a thing in some xPanic/Inf thingy mod. Also there are city servers with mazes. And using entities is a known zoom protection bypass on onbgys fng server. So on some servers entitites is a cheat for sure.

**Comment by heinrich5991** [comment]
> I would need it in my mod, where players have no name and can hide behind bushes to survive and trick other players.

I think zCatch solved it by not sending tees behind obstacles. This also makes it harder to cheat with custom clients.

**Comment by fokkonaut** [comment]
> I think zCatch solved it by not sending tees behind obstacles. This also makes it harder to cheat with custom clients.

Sure, that was our idea a few months or years ago too, but halfly being seen is also a thing, which in my opinion ruins the gameplay if a tee just pops up or the gun should be seen. With tiles, you can also simply aim at enemies since you know you definitely won't get rendered.

**Comment by ChillerDragon** [comment]
doodads

**Comment by heinrich5991** [comment]
Status: I don't like it, what do others think?

@Learath2 @murpii

I don't like restricting the user from going into entities, smells like restricting the user. I fear that too many server owners will enable it on their servers.

I guess you could say it's similar to disallowing zoom. It seems hard to enforce this for custom clients (just as with zoom).

**Comment by ChillerDragon** [comment]
> I don't like restricting the user from going into entities, smells like restricting the user. I fear that too many server owners will enable it on their servers.

If the ddnet client can not be restricted it has to be considered a cheat client in some circumstances then.

**Comment by Learath2** [comment]
I don't see it any different from restricting zoom and I'm fine with it. I'm still of the opinion that entities display is a cheat anyway.

**Comment by heinrich5991** [comment]
> I don't see it any different from restricting zoom and I'm fine with it. I'm still of the opinion that entities display is a cheat anyway.

Hm, the entities could also be viewed in the editor. It's a cheat only due to the problem mentioend here, that it allows you to view tees behind bushes? Perhaps one could allow to overlay the entities over the normal map design then, that shouldn't be a cheat according to the definition? Cause you could also look them up in the editor?

Other problem I see upcoming: Are nameplates a cheat due to that as well? Server could disable sending names, does debug mode/hook strength indicators become a cheat then because because you can see tees behind bushes with it?

**Comment by ChillerDragon** [comment]
> Other problem I see upcoming: Are nameplates a cheat due to that as well? Server could disable sending names, does debug mode/hook strength indicators become a cheat then because because you can see tees behind bushes with it?

Ye debug mode is a bummer for that case. If we could get a server side option to hide nameplates and other text around tees that would be cool yes. But that is also a problem in vanilla. And actually way less used than entities. For example I know many people playing always with entities and never hear of players playing mainly with debug mode.

> Hm, the entities could also be viewed in the editor. It's a cheat only due to the problem mentioned here, that it allows you to view tees behind bushes? Perhaps one could allow to overlay the entities over the normal map design then, that shouldn't be a cheat according to the definition? Cause you could also look them up in the editor?

Same here. Way less known and less used. Back in the days when ddrace clients were not that wide spread I never heard of that trick to solve mazes. It is more complex and more effort.

**Comment by heinrich5991** [comment]
> For example I know many people playing always with entities and never hear of players playing mainly with debug mode.

I remember this being a thing for the hidden nameplates in zCatch. It's probably just not used because entities is a thing?

> Same here. Way less known and less used. Back in the days when ddrace clients were not that wide spread I never heard of that trick to solve mazes. It is more complex and more effort.

I can see the point of bushes hiding tees, and this being considered a cheat. I think my proposal to allow the entities to overlay the map would prevent that problem.

I think I view show entities like "view source" in the browser. It shouldn't be possible to disable it entirely, no matter whether the game server/HTTP server owner wants that to happen or not.

**Comment by fokkonaut** [comment]
Then lets get a setting to force current map as entities background and/or a setting to show tile layers of the map because they are the ones on top of the tee, so forcing those 2 would work.

**Comment by heinrich5991** [comment]
> Perhaps one could allow to overlay the entities over the normal map design then, that shouldn't be a cheat according to the definition?

This is the solution that would be accepted. As of right now, the pull request doesn't implement that.

**Comment by fokkonaut** [comment]
I gave up on this one, I tried using the flag so that the foreground layer will be rendered aswell, so hiding behind bushes is not possible anymore, but I think this would need a whole restructuring of this part of the code (I am not very familiar with this part and it is not very easy to understand at the first look).

This commit does: Rendering the normal map, including foreground tile layers but also entities inbetween. They are rendered in the order of the map of course, which means for example a grass main or generic layer used for hook/unhook is rendered in front of the entities game layer.

Would appreciate help/anyone finishing this somehow.

**Pull request closed without merging**
