### PR TITLE
Minor refactoring of engine jobpool

### PR DESCRIPTION
**Pull request by Robyt3**
See commit messages.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by heinrich5991** [comment]
> The client/server jobpools were previously only using a fixed number of 2 threads. Now the pools use `2 * hardware-concurrency + 2` threads, which should provide better performance overall, as we expect threads to often wait on I/O.

Can you give details on that? Which actions are expected to go faster? How much resources does this cost?

**Comment by Robyt3** [comment]
Eventually I'd want to start a job for every skin to load them lazily, so we'd have a lot of jobs doing some I/O and then decoding PNG data. I expect that having only two worker threads could result in long delays for higher priority jobs like serverlist loading and map saving, when there are many low priority file loading jobs scheduled. From what I've read, using more threads than CPUs in such cases can compensate for the latency when waiting for I/O.

https://stackoverflow.com/a/4350982

https://stackoverflow.com/a/44410898

Additional memory usage for the threads' stacks seems negligible to me: https://stackoverflow.com/a/1826072

**Comment by heinrich5991** [comment]
> Eventually I'd want to start a job for every skin to load them lazily, so we'd have a lot of jobs doing some I/O and then decoding PNG data. I expect that having only two worker threads could result in long delays for higher priority jobs like serverlist loading and map saving, when there are many low priority file loading jobs scheduled.

It seems the solution to that is not "more threads", as these can still be saturated by loading many skins.

The linked stackoverflow answers do not suggest spawning twice a many threads as there is hardware concurrency, the most I could see was 1.5x.

> Additional memory usage for the threads' stacks seems negligible to me: https://stackoverflow.com/a/1826072

For a 16 core machine, we get 256 MiB extra RAM per Teeworlds process in glibc, that doesn't sound negligible to me.

**Comment by heinrich5991** [comment]
> For a 16 core machine, we get 256 MiB extra RAM per Teeworlds process in glibc, that doesn't sound negligible to me.

On Linux, I can confirm that the extra RAM usage is negligible. I don't see the difference between before and after the patch. Maybe someone should test on Windows as well; threads have the reputation of being heavyweight on Windows.

**Comment by Robyt3** [comment]
On Windows I can see no significant difference before and after either.

**Pull request merged**
