### PR TITLE
Add includes for ddnet mod configs

### PR DESCRIPTION
**Pull request by ChillerDragon**
This allows ddnet forks to create the following files

src/game/ddracechat_mod.h
src/game/ddracecommands_mod.h
src/game/variables_mod.h

They will be loaded automatically and no git conflict surface is created.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Honestly, I think the mod can do that on its own. Adding a single line should be okay, from a git conflict point of view.

**Comment by ChillerDragon** [comment]
> Honestly, I think the mod can do that on its own. Adding a single line should be okay, from a git conflict point of view.

The conflict is easy to fix. But there is a big difference in maintenance effort and automation when it comes to conflict or no conflict.

And these are common spots where mods insert code. What is the downside of adding it?

**Comment by ChillerDragon** [comment]
If it does conflict it is not ok

**Comment by heinrich5991** [comment]
I don't think we can satisfy the wishes of mod authors here. This won't be the last spot you ask for inclusions.

If you wish to have no merge conflicts, you could e.g. not include this in git commits, but instead add this as the third line to these files after applying your mod's changes.

**Comment by ChillerDragon** [comment]
> I don't think we can satisfy the wishes of mod authors here. This won't be the last spot you ask for inclusions.
> 
> 
> 
> If you wish to have no merge conflicts, you could e.g. not include this in git commits, but instead add this as the third line to these files after applying your mod's changes.

Yes it would also be nice to have includes in the character.h class definition and also inside the player.h but those are more dirty and I would understand if they seem too hacky. The thing is no matter where in character.h and player.h one defines his variables it will always conflict. And those two classes are crucial.


Using scripts to patch the code can also break but more importantly they do not work well with version control. Line numbers are off in backtraces and git. And also the current working tree is always dirty which is not an option for me.

Are 5 of those includes really bad? And if so why?

**Comment by ChillerDragon** [comment]
> > Using scripts to patch the code can also break
> 
> 
> 
> Yes.
> 
> 
> 
> Otherwise you're pushing the work to do that onto DDNet.

There is no work involved maintaining those includes is there?

**Comment by heinrich5991** [comment]
Every time my suggested script would break, someone in DDNet would have to figure out how to change these includes appropriately.

I guess my problem stems from the fact that this has unclear scope.

**Comment by ChillerDragon** [comment]
> Every time my suggested script would break, someone in DDNet would have to figure out how to change these includes appropriately.


The include moves with the macro calls. It's a simple structure. Don't see how that cause additional effort.

> I guess my problem stems from the fact that this has unclear scope.

The scope is 5 includes.

**Comment by heinrich5991** [comment]
> The scope is 5 includes.

No, it's not. This is about more mod support in DDNet. This is not a single pull request, this is one of a series.

**Comment by ChillerDragon** [comment]
> > The scope is 5 includes.
> 
> 
> 
> No, it's not. This is about more mod support in DDNet. This is not a single pull request, this is one of a series.

Ah then it's those 5 includes and the controller support. If I still am motivated after that maybe more methods in the controller. But that would be it.


My craziest dream but I would consider it unrelated. And I am too lazy to actually implement it. Would be to refactor Antibot into a plug-in system that can not load only one Antibot but multiple plugins.

**Comment by heinrich5991** [comment]
I think I don't want this in DDNet.

**Comment by Kaffeine** [comment]
In the same way as you said in https://github.com/ddnet/ddnet/pull/7475#issuecomment-1817623184
> I think the mod should not touch mod.cpp but create modname.cpp instead. 

I think the mod should create and use `<mod>_config_variable.h` instead. The chat commands are even more questionable: the mod (probably and I'd say typically) need its own chat commands. The way to go is move the chat and custom console commands from gamecontext to the controller. Or maybe [introduce](https://github.com/ddnet/ddnet/pull/3501) `CGameContextMod` (personally I abandoned that idea for now).

**Pull request closed without merging**
