### PR TITLE
Remove bam

### PR DESCRIPTION
**Pull request by Learath2**
With cmake working on OSX I think we can finally phase out bam.

### CODE REVIEW

**Comment by heinrich5991** [comment]
I would like to keep it around for some time after we fixed the last cmake-related bug, say 1 month or so?

**Comment by def-** [comment]
But we end up having to fix both systems now, lots of useless work.

**Comment by Learath2** [comment]
Been more than two months, is there anything that isn't working with cmake anymore?

**Comment by def-** [comment]
Yes, releases.

**Comment by heinrich5991** [comment]
Postponed. Feel free to reopen.

**Pull request closed without merging**
