### PR TITLE
Use SDL_FlashWindow to request user's attention

### PR DESCRIPTION
**Pull request by Jupeyy**
We should soon update to SDL 2.0.16 for our bundled libs, but don't merge before this happened.

This drops the remaining X11 dependency.

We should then also use GLEW with EGL for official builds for easy native wayland support(which i discussed before already)

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Looks good. Ping me when SDL 2.0.16 is released.

**Comment by heinrich5991** [comment]
Status: [SDL 2.0.16 seems to be released.](https://en.wikipedia.org/w/index.php?title=Simple_DirectMedia_Layer&oldid=1041549892) What needs to be done?

**Comment by def-** [comment]
I need to update the SDL version we use first I guess. On my todo list it says:
> Upgrade to SDL 2.0.16 with https://github.com/libsdl-org/SDL/pull/4306 and https://github.com/libsdl-org/SDL/pull/4683

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by heinrich5991** [comment]
bors retry

**Comment by Jupeyy** [comment]
Oh you are right, they changed the behavior :/
classic SDL devs, always break everything

**Comment by Jupeyy** [comment]
But still works on KDE apparently

**Comment by def-** [comment]
With https://github.com/ddnet/ddnet/pull/4220 it's as before for me

**Pull request merged**
