### PR TITLE
Fix out of bounds read in CPlayer::Snap with IsSixup (fixes #2416)

### LINKED ISSUE #2416: Out of bounds read in CPlayer::Snap
https://github.com/ddnet/ddnet/blob/a79b1265df195b96d4cd5277324fc29f0c17b1ea/src/game/server/player.cpp#L301

SnappingClient is -1 for a serverside demo.

https://github.com/ddnet/ddnet/blob/a79b1265df195b96d4cd5277324fc29f0c17b1ea/src/game/server/player.cpp#L401

Unconditionally calls `IsSixup`.

https://github.com/ddnet/ddnet/blob/a79b1265df195b96d4cd5277324fc29f0c17b1ea/src/engine/server/server.h#L449

Out of bounds read (-1).

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by fokkonaut** [comment]
SnappingClient < 0 should be == m_ClientID

**Comment by def-** [comment]
Why?

**Comment by fokkonaut** [comment]
Ah yea, no, sorry

**Pull request merged**
