### PR TITLE
Add Teehistorian UUIDs to every record

### PR DESCRIPTION
**Pull request by Learath2**
For statistic collecting purposes, don't merge before updating the SQL Schema.

    ALTER TABLE record_race ADD COLUMN GameID VARCHAR(64) AFTER cp25;
    ALTER TABLE record_teamrace ADD COLUMN GameID VARCHAR(64) AFTER ID;

### CODE REVIEW

**Comment by heinrich5991** [comment]
Better include the teehistorian UUID. :P

**Comment by heinrich5991** [comment]
For less coupling between `CGameContext` and the score code, you'd give that as a parameter instead of fetching it from the score code. I think the game UUID is only set if we're recording to teehistorian, and I guess it only makes sense to record it then. The `CREATE TABLE` code has to be updated as well.

**Comment by Learath2** [comment]
Aren't you rewriting the entire SQL score thing? I didn't think too much of coupling because of that.

**Comment by heinrich5991** [comment]
Yes, I am. Still good practice? :P

**Comment by Learath2** [comment]
`m_GameUuid` is always set, further coupling this to `CGameTeams` is pointless IMHO

**Comment by heinrich5991** [comment]
I don't know how the SQL schema can be updated. Just enter it on any server? @def-

**Comment by def-** [comment]
I think if you enter it on one as correct user on correct db it will get propagated to all. ddnet.tw has a few more indexes than the other servers btw, for the website. I believe I added them by connecting as another user to another db (one of those should work, forgot which)

**Comment by heinrich5991** [comment]
Thanks.

bors r+

**Pull request merged**
