### PR TITLE
Add -DSECURITY_COMPILER_FLAGS=OFF option

### PR DESCRIPTION
**Pull request by def-**
To disable -D_FORTIFY_SOURCE=2 -fstack-protector-all, see https://bugs.gentoo.org/888875 for report. Default behavior is not changed.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Honestly not sure if it's our job to make sure you can build without enabled security flags. What do you think, @Learath2 @edg-l? You used Gentoo, before, I think.

**Comment by Learath2** [comment]
This could also be used as an epatch in gentoo, if you'd rather not allow disabling them. I honestly don't know the best practice with this.

**Comment by def-** [comment]
I think patches in distributions should be minimal, there have been bugs in them too. I think it makes some kind of sense to have these kind of settings centrally controlled for a distribution, not set by each developer manually. Thus I think we can provide this for distro maintainers (and no one else probably).

**Comment by edg-l** [comment]
honestly im in favour of adding this if the security options are on by default

**Comment by heinrich5991** [comment]
Alright then.

bors r+

Thanks.

**Pull request merged**
