### PR TITLE
Add a flag `-DDOWNLOAD_GTEST` to automatically download and build GTest

### PR DESCRIPTION
**Pull request by heinrich5991**
Enable tests on Circle CI, macOS on Travis and Appveyor.

### CODE REVIEW

**Comment by heinrich5991** [comment]
WIP

**Comment by Learath2** [comment]
Do we really want our cmake to download and compile another project?

**Comment by heinrich5991** [comment]
It's what googletest suggests: [README.md](https://github.com/google/googletest/blob/7b6561c56e353100aca8458d7bc49c4e0119bae8/googletest/README.md#incorporating-into-an-existing-cmake-project). We also provide binaries for some of our dependencies. :)

It makes it easier to run tests; since googletest doesn't want to be shipped as a binary, this would be the best option.

**Pull request merged**
