### PR TITLE
Optimize `str_format(…, …, "%d", …)` using templates

### PR DESCRIPTION
**Pull request by heinrich5991**
This would make the function `str_from_int` unnecessary, at least user-facing.

Advantage: User doesn't have to care about `str_from_int`/`str_format` distinction.

Disadvantage: We're adding some template programming to `system.h`, potentially slowing all compilation.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
@Learath2 @Robyt3 Do we want something like this?

**Comment by Learath2** [comment]
I like it. I'm curious if this gets optimized out properly to a direct call for compile time constant format strings

**Comment by heinrich5991** [comment]
I checked with all major compilers on Godbolt and this is what I ended up with. It gets optimized out properly for compile-time constant format strings.

**Comment by Chairn** [comment]
This looks like over optimization. What happens if the string is " %d" or "%d\n" or even any other format like %lld or %u ?

**Comment by heinrich5991** [comment]
> This looks like over optimization. What happens if the string is " %d" or "%d\n" or even any other format like %lld or %u ?

It doesn't work in this case. What I'd like to avoid is humans having to remember to call `str_from_int`. This function was introduced for measurable performance impact (#7056):
> This increases FPS in the editor by ~25% when many numbers are rendered for switch/tele/speedup/tune layers or with "Show Info" being enabled.

**Comment by Robyt3** [comment]
Looks good. I prefer this over having a separate `str_from_int`.

**Review by def- — APPROVED** [review]

**Review by Robyt3 — APPROVED** [review]

**Pull request merged**
