### PR TITLE
Smooth zoom

### PR DESCRIPTION
**Pull request by edg-l**
Preview: https://www.youtube.com/watch?v=ZWDffbmyQmo

~Disabled by default and~ you can change the animation length.

### CODE REVIEW

**Comment by Patiga** [comment]
I would love to use it if it would zoom faster whenever i zoom more aggressively.

**Comment by trafilaw** [comment]
Looks nice! :D

**Comment by def-** [comment]
Instead of a linear movement from one to another zoom level I think it would look better if you used a logistic funtion: https://en.wikipedia.org/wiki/Logistic_function
900px-Logistic-curve svg
This would also take care of zooming more agressively when you quickly zoom out further. (I think)

I think this should be enabled by default, but still be switchable.

**Comment by edg-l** [comment]
https://www.youtube.com/watch?v=n87XuBnH8X4&feature=youtu.be

Only thing needed to do is implementing the ability to change zoom smoothly while there is a zoom animation in place.

**Pull request closed without merging**
