### PR TITLE
Only show the scorelimit box in other mods than ddrace.

### PR DESCRIPTION
**Pull request by luk51**
#3702 this issue.
sorry for lots of commits, i don't know how to rebase.

## Checklist

- [x ] Tested the change ingame
- [x ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by luk51** [comment]
I already think I forgot to adjust the text inside the spectators hud. I think it will be rendered not at the top of the box, but a little bit down.

**Comment by Chairn** [comment]
On my windows git, i have:

- `git config core.autocrlf` set to `true`
- `git config core.safecrlf` set to `false`

To rebase, use `git rebase -i master` and select squash for all commits except the last one (i think).

**Comment by luk51** [comment]
ok, ill try again.
but i get emails from github that the build failed. but locally i could build. i also only made so few changes. do you know what could be the reason?

**Comment by C0D3D3V** [comment]
Execute `scripts/fix_style.py` in the project root folder.

See https://github.com/ddnet/ddnet#code-formatting

**Comment by C0D3D3V** [comment]
Also you would need to include cstring instead of string.h, but I thing we have own str_cmp functions in base

**Comment by luk51** [comment]
okay, ill use str_cmp, but is getting currentserver inside onrender fine? i think it gets called a lot. is it a network call?
also i dont see any other changes when i compare my branch to master. why fix_styling.py? are there files that are ignored by git, that have a changed style? or how come that git doesnt show the style change with git diff master?

**Pull request closed without merging**
