### PR TITLE
Don't reset zoom when using timeline in demo

### PR DESCRIPTION
**Pull request by def-**
Thanks to Lady Saavik for reporting

### CODE REVIEW

**Comment by fokkonaut** [comment]
I dont get it? But I would love to use the zoom reset bind in demos

**Comment by def-** [comment]
Fixed, bind still works.

The problem is that when you click on the timeline, the OnReset function was called and thus the zoom was reset.

**Comment by heinrich5991** [comment]
Why is `OnReset` getting called? I think this also leads to other problems such as not spectating the client you chose anymore (for a serverside demo).

**Comment by def-** [comment]
OnReset has been called in menus_demo.cpp since forever: https://github.com/ddnet/ddnet/commit/72c06a258940696093f255fb1061beb58e1cdd0b

I guess because otherwise tees will start flying through the map, so it's better to reset the client.

**Comment by heinrich5991** [comment]
It's been there since the introduction of the demo player:

https://github.com/ddnet/ddnet/commit/12472ef7f405f5e8eb620059cbf95926a458538a#diff-4d014b7597f3da3a22e874656229fd11R93

> I guess because otherwise tees will start flying through the map

What effects do you mean by this? I just patched out the `OnReset` and everything seemed to behave just fine. Note that other things changing the demo player position already do not call `OnReset`, e.g. the code handling the Home key. Zoom also persists when pressing the Home key.

**Comment by def-** [comment]
Oh well, then removing the OnReset call there is even better I guess.

**Comment by heinrich5991** [comment]
bors r+

Thanks. I think this also fixes the spectating problem in teehistorian2demo's demos.

**Pull request merged**
