### PR TITLE
Merge DejaVuSansCJKName with DejavuWenQuanYiMicroHei and use it for all (fixes #2593)

### LINKED ISSUE #2593: Switch all to CJK font
Since we have lots of CJK players now, maybe we should unify the fonts into a single one.

Are there still lags when playing with CJK font? @ACTom any experience?

How to merge the fonts so that we take all characters in the DejaVuSansCJK plus the ones missing from it from the full file? I hope there is a program that can do that automatically.

### PR DESCRIPTION
**Pull request by def-**
allows reading CJK for everyone independent of language chosen.

got them merged with fontforge, finally looks good.

Hopefully the lags are gone.

### CODE REVIEW

**Comment by Learath2** [comment]
Does this do anything to the character spacing? CJK font makes the text tighter, is it now tighter for every language?

**Comment by def-** [comment]
That's what the previous merging did wrong. Now I fixed the merging, font looks exactly the same as before, only CJK added.
Old: screenshot-20200819@130738
New: screenshot-20200819@130800

**Comment by Learath2** [comment]
Oh btw, have you seen any performance degradation?

**Comment by def-** [comment]
Nope, looked fine to me so far.

**Comment by Learath2** [comment]
LGTM

bors r+

**Pull request merged**
