### PR TITLE
Improve envelope editor

### PR DESCRIPTION
**Pull request by Marmare314**
See #6045.

envelope_editor2

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Is it useful for mappers to have the layers and envelopes side by side like this? It would be simpler in term of UI/UX to have a 4th tab in the top left for the list of Envelopes, so you don't need to drag the envelopes list. This would also make it simpler to support using up/down navigate the items of the envelope list.

**Comment by VoxelDoesCode** [comment]
But that's the thing, it's very vital to have the envelopes section be integrated within the map editing section, because as a mapper, if you're every editing an envelope and want to see how it's effecting the animation live, you would want it to be in a spot where you can move 1 node and see that movement in the map. If it's in a different panel, it hides the live changes from us, and makes it much harder to determine our actions without having to tab back and forth many times.

**Comment by Marmare314** [comment]
If it is in a new window we would definitely need to show the map view there too. But I don't think that would be a problem.
First of all, you can actually click on the envelopes button, which toggles it, and I think is easier than clicking through the windows. But at the moment I don't think there is any reason against that from a mapping efficiency viewpoint. Although I don't like hiding them in another window especially because of new mappers. Envelopes are important enough that it should be obvious how to use them / that they exist when opening the editor for the first time.
Also I was planning on adding a feature that you can drag the entities onto quads for which it would be more convenient to have it on the same page with the layers, so that you can switch between them.
When they are in a different window we also can't / shouldn't move the animation play/stop buttons to the envelope window. But I think this would a lot of sense as they are so closely related.

**Comment by HiRavie** [comment]
Splitting envelopes away from the envelope editor and putting them with layers makes no sense, they should stay where they belong. The current envelope editor is nicely self-contained and gets the job done, if we decide to change it (or any other part of the map editor honestly) then it should be a proper overhaul. Random cosmetic changes don't help with the editor being cluttered and full of confusing/useless features, more of which keep getting added.

**Comment by Marmare314** [comment]
Maybe me already adding this as a draft gives off the wrong impression. This PR aims to implement all the changes I described in #6045. The reason I did so is that I wanted to start this conversation so I don't waste my time on an unwanted feature.
My idea was that unifying the way you interact with layers and envelopes would make it very intuitive. But if you would only consider this 'some random cosmetic change' and 'confusing' it would be nice to know what you would consider to be a 'proper overhaul' of the editor.

**Comment by HiRavie** [comment]
> My idea was that unifying the way you interact with layers and envelopes would make it very intuitive.

I don't think moving envelopes from the envelope editor to a different part of the UI is very intuitive. Also the layers view can already get crowded on a big map, and there can be tens of envelopes as well so putting them all in the same place isn't great either.

> it would be nice to know what you would consider to be a 'proper overhaul' of the editor.

A proper overhaul for me would start with going over all the features and seeing what can be removed or simplified. Trying to improve UI while the feature set is a mess won't help very much.

**Comment by Marmare314** [comment]
> I don't think moving envelopes from the envelope editor to a different part of the UI is very intuitive. Also the layers view can already get crowded on a big map, and there can be tens of envelopes as well so putting them all in the same place isn't great either.

We should probably get some more opinions on this, but in the meantime I'll try to think of alternatives.

> A proper overhaul for me would start with going over all the features and seeing what can be removed or simplified. Trying to improve UI while the feature set is a mess won't help very much.

I agree that this is also important, but I don't see how it is relevant. This PR would not block any simplifications. The only reason would be if the envelope editor would be simplified, which this PR is trying to do. In that case it would be helpful to know what a simplified envelope editor would look like to you.

Unless you mean a full rewrite of the editor of course, but I don't see why that would block changes either.

**Comment by Robyt3** [comment]
I don't think a complete rewrite of the editor is feasible. The editor2 project on upstream teeworlds stalled almost immediately after it was made available to contribute for everyone even though it was not limited by the unavailability of the maintainer. A complete rewrite would be hard to test and likely contain several new bugs and miss functionality from the old editor. We are barely managing to fix the bugs of our current editor. A complete rewrite would also be very painful for downstream projects to merge, if they have custom editor changes.

I prefer incremental changes, so we can properly test them and keep the number of bugs low. But we should have discussions before adding new features, since the editor is already bloated with features and you can't really remove features again after adding them. As far as I remember, the only feature we removed from the editor was the undo/redo implementation, since it was very buggy and caused crashes all the time, so it was never really useable to begin with.

> A proper overhaul for me would start with going over all the features and seeing what can be removed or simplified. Trying to improve UI while the feature set is a mess won't help very much.

Is there realistically anything in the editor that can be removed without breaking someones workflow?

**Comment by VoxelDoesCode** [comment]
The borders button

**Comment by HiRavie** [comment]
I'm not suggesting rewriting the editor from scratch, I think the current editor is a good base. On the topic of this PR I'm mostly just saying that random little changes like this don't do much good. To properly rework any part of the editor we should see what can be removed, come up with concepts and discuss how it can be improved before implementing something. This looks to me like just a change for the sake of change and not an improvement.

**Comment by heinrich5991** [comment]
I haven't had a chance to look at this PR, was away for some time, sorry.

This PR seems to add some QoL to the envelopes editor, which seem to be a straight improvement to me.

@Marmare314 seems to have some ideas in mind in #6045.

**Comment by Robyt3** [comment]
I liked the idea to make the envelope editor resizable by dragging. I think that's more convenient than pressing the envelope 3 times to get to the maximum size.

**Pull request closed without merging**
