### PR TITLE
More aggressive analysis & check 2.0 gl Functions that were used

### PR DESCRIPTION
**Pull request by Jupeyy**
If even that fails, I'm out of ideas

Checks all texture shaders, checks all functions used.

### CODE REVIEW

**Comment by Jupeyy** [comment]
I increased the analysis texture size to 1024x1024 now. thats what most tilesets use, so it hopefully safe like that

**Comment by def-** [comment]
Fails to build. Should I rebuild the nightly once fixed?

**Comment by Jupeyy** [comment]
@def- yeah msvc didnt see that the vars were const :D

You can build the nightly, i dunno if its better like that or changes smth, but we can atleast try.

Bcs else i can just disable OpenGL 2.0 context and hope that all 2.1 GPUs work

**Comment by Jupeyy** [comment]
just a small typo, but doesnt change critical behaviour

**Comment by def-** [comment]
bors r+
Seems to work according to Seninha. Let's get this in and do a hotfix release.

**Pull request merged**
