### PR TITLE
Move to new-style CMake, allow external GLEW, pnglite, wavpack 

### LINKED ISSUE #1016: Glew should be able to be loaded externally
instead of using the bundled version. Useful for packagers especially.

> 16:03 <+quinerr> Hi, I'm packing ddnet for debian. However I see currently src heavily depends on bundled libs
> 16:18 <+quinerr> Hmm you know debian ftp master
> 16:18 <+quinerr> block everything
> 16:31 <+quinerr> I still get embedded-library errors for 11.0.3
> 16:41 <+quinerr> It's glew which is bundled in

### LINKED ISSUE #1023: Update wavpack
Teeworlds currently uses version 4.something, current distributions ship version 5.
```
../src/engine/client/sound.cpp: In static member function ‘static int CSound::DecodeWV(int, const void*, unsigned int)’:
../src/engine/client/sound.cpp:485:50: error: cannot convert ‘int (*)(void*, int)’ to ‘const char*’ for argument ‘1’ to ‘WavpackContext* WavpackOpenFileInput(const char*, char*, int, int)’
  pContext = WavpackOpenFileInput(ReadData, aError);
                                                  ^
```

### PR DESCRIPTION
**Pull request by heinrich5991**
New-style CMake adds libraries via targets that automatically pull in
the needed compile definitions, include directories and library
locations.

Needs a bit of band-aid because object libraries (which are used for
source-shipped dependencies) are not first-class CMake targets.

Also allow for updated wavpack, fixes #1023.

Fixes #1016.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Would also supersede #1021 and contains #1026.

**Comment by heinrich5991** [comment]
Blergh, will fix errors tomorrow.

**Comment by def-** [comment]
Woah, big change.

**Comment by heinrich5991** [comment]
Superseded by #1034. Couldn't get new-style CMake to work. :(

**Pull request closed without merging**
