### PR TITLE
Allow to dynamically load the Discord SDK on Linux

### LINKED ISSUE #3580: Add runtime Discord support for Linux x86-64
Using dlopen: https://linux.die.net/man/3/dlopen

> a subsequent call with RTLD_NOW may force symbol resolution for a library earlier loaded with RTLD_LAZY.

### PR DESCRIPTION
**Pull request by heinrich5991**
Set `-DDISCORD_DYNAMIC=ON` on the CMake command line to enable this
feature.

Fixes #3580.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
This seems like it only works for linux with the `.so` extension, is that intentional? If so maybe gate it as such so people can't compile it for windows with `-DDISCORD_DYNAMIC=ON`

**Comment by edg-l** [comment]
Tested it on arch linux, it worked.

**Review by edg-l — APPROVED** [review]

**Comment by heinrich5991** [comment]
> This seems like it only works for linux with the `.so` extension, is that intentional? If so maybe gate it as such so people can't compile it for windows with `-DDISCORD_DYNAMIC=ON`

Done.

**Pull request merged**
