### PR TITLE
Allow specifying texture LOD BIAS

### PR DESCRIPTION
**Pull request by Jupeyy**
For Ravie, and others that want the old renderer opengl 3.3 feeling back xd

### CODE REVIEW

**Comment by Jupeyy** [comment]
e.g. `gfx_opengl_texture_lod_bias -1000` would be one step higher mipmap resolution

**Comment by def-** [comment]
Do we really need that or is it just for Ravie? :D

**Comment by Jupeyy** [comment]
i could swear, i answered to this, wtf:

Anyway i wrote smth like:
Its just a QOL, its optional and doesnt apply anything if 0.
It also fixes what you, yourself, called blurrier than before.
just set it to -100 for example so the driver will shift more to a higher resolution mipmap

**Comment by def-** [comment]
Ok, I guess it's fine. Any other opinion before I merge this?

**Comment by Learath2** [comment]
I still can't believe we need a setting for this. Other than that fine

**Comment by def-** [comment]
Yeah, same. I think we should just use the best looking setting as default.

**Comment by Jupeyy** [comment]
thats too driver dependent, the best looking would be native resolution textures, so probs u need a 2k display

**Comment by Jupeyy** [comment]
but with Full HD it will look less sharp and if u want it be displayed like on 2k screen u need the bias

**Comment by Learath2** [comment]
Can't we bias depending on resolution to get it to be at LOD0 at default
zoom?

**Comment by Jupeyy** [comment]
the question is, does it really look good for everyone.
i posted an image before, ofc this isnt really realistic scenario, but when zooming out far without mipmaps it would get too a point where it samples the original texture like a zoomed tile
img

this actually also happens in 0.7 editor, e.g. if you load multimap into it, bcs 0.7 has no mipmaps

linear interpolation just isnt always enough

**Comment by def-** [comment]
And we need to use linear interpolation for performance reasons? Why was it better before?

**Comment by Jupeyy** [comment]
in early 3.3 versions i calculated the mipmap before, but that requires additional shader state changes

**Comment by def-** [comment]
For reference, Cøke also can't use new client  because it's too blurry for him.

**Comment by Jupeyy** [comment]
well this is a fix for exactly that, i dont get why this is worse then using the old shaders XD
gfx_opengl_texture_lod_bias -100 and they have their old feelings back xD

**Comment by def-** [comment]
But it is currently blurrier not just for these 2 mappers, but for many other players. I don't think every player should play around with lod bias to find a good-looking value.

**Comment by Jupeyy** [comment]
I fear a bit that textureLOD is broken, even heinrich had the bug 
https://github.com/ddnet/ddnet/issues/994#issuecomment-501916165

this function is not so shader dependent,
BUT, honestly i don't care, add the old LOD calculation, test it in nightly, if it works its fine

**Comment by Jupeyy** [comment]
Ah and btw u only add it for opengl 3.0, bcs before that version it didnt exist

**Comment by Jupeyy** [comment]
at full hd:

linear mipmap interpolation:
linear

linear mipmap interpolation, biased:
linear_bias

nearest mipmap:
nearest

nearest mipmap, biased:
nearest_bias

nearest mipmap, biased with -1000:
screenshot_2020-09-23_00-55-20

ddnet 14
ddnet14

**Comment by Jupeyy** [comment]
and linear with bias -1000 to make it fair:
screenshot_2020-09-23_00-59-48

**Comment by Jupeyy** [comment]
ah and bias also effects any texture, see weapon

**Comment by Jupeyy** [comment]
so maybe a default LOD bias of -500(results to -0.5) could be apllied. that would make teeworlds generally sharper and shouldnt really waste performance, and doesnt need to be applied to the shaders

**Comment by Jupeyy** [comment]
-500 bias
screenshot_2020-09-23_06-04-20

-1000 bias
screenshot_2020-09-23_06-04-42

i think -500 is reasonable bcs, we choose the closest mipmap, so imagine it like a floating point.

for the driver calculated mipmap level from 1.0-1.999999(+- some very small floating point margin) adding -0.5 => it would choose mipmap 1 (bcs thats the closed mipmap then)
which is of higher quality

**Comment by Jupeyy** [comment]
sry for the spam, but need to be clear:
normally linear mipmap linear interpolation should be the smoothest, bcs that also performs worst.
its probably the safest option for all kinds of resolution too look good, adding a small bias to it already improves quality.
nearest however will always look sharpest, and might look more pixelated on resolutions that calculate the same mipmap (bcs nearest, so fraction of the float is obviously ignored).

**Comment by def-** [comment]
> i think -500 is reasonable bcs, we choose the closest mipmap, so imagine it like a floating point.

Defaulting to -500 sounds good to me.

**Comment by Jupeyy** [comment]
Ravie on discord:
"looks really good in this one"

mind wants to test this too tomorrow

**Comment by Jupeyy** [comment]
mind said looks sharper in general, but didn't notice a real diff since the newest commit.
But thats what i said in
https://github.com/ddnet/ddnet/pull/2889#issuecomment-697126068

its resolution, maybe gpu driver, maybe monitor dependent.
there are so many factors.

**Comment by Jupeyy** [comment]
on a i3-3120m trilinear filtering removes around 2-8% performance, tested on a few maps
thats a CPU from 2012 btw

**Comment by def-** [comment]
> mind said looks sharper in general, but didn't notice a real diff since the newest commit.

Does this mean this change is good or not? :D

**Comment by Jupeyy** [comment]
The text from ravie and mind are both about the filtering. Not about the texture lod bias..

Ravie saw a difference while moving, I saw the difference the analysing the screenshot image closely, and mind didn't see it

**Comment by def-** [comment]
To get good perfomrance back you just set it to 0? Default is better-looking graphics, right?

**Comment by Jupeyy** [comment]
Well no, sry. Trilinear filtering will basically always look a bit better and will always remove the bit performance. I added it bcs ravie complained that nearest mipmap looked over sharp while moving, bcs in the cases where the lod value is close to a 0.5 fraction, it might load the higher mipmap then. I could see this difference when analysing the screen shots.


The lod bias itself probably won't affect performance alot. Imagine it more like an array access.  Accessing a bigger array makes only a small difference

**Pull request merged**
