### PR TITLE
Put shaders into the data/ directory

### PR DESCRIPTION
**Pull request by heinrich5991**
Simplifies a lot of things

### CODE REVIEW

**Comment by Jupeyy** [comment]
But it's not data, it's code.

**Comment by def-** [comment]
What's the difference between code and data? *cough* lisp *cough*

**Comment by Jupeyy** [comment]
Then pack the binary there too ;P

**Comment by heinrich5991** [comment]
a) Unless it's absolutely not suited for `data/`, I would still put it there, maintaining another folder doesn't seem to be worth it (would also be a hassle for people packaging this, e.g. it breaks [the AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ddnet).

b) Where do you draw the line between code and data? :P Fonts and maps also contain code. :)

**Comment by heinrich5991** [comment]
(And unlike the DDNet binaries, it's architecture- and OS-independent.)

**Pull request merged**
