### PR TITLE
Support bezier envelope curves in maps and editor, forward compatiblity for upstream map item changes

### PR DESCRIPTION
**Pull request by Robyt3**
screenshot

Port map and editor support for `CURVETYPE_BEZIER` from upstream, i.e. support bezier curves with configurable in- and out-tangents for every envelope point.

The in- and out-tangents are represented by triangles and can be dragged in the envelope editor like the envelope points.

Support reading and writing the bezier information as a separate UUID-based map item. If the bezier information is not found, bezier will default to linear behavior. Old clients will still be able to read the new maps and ignore the unknown map item. The unknown curvetype will also be handled as linear by old clients.

Allow reading upstream maps that use `CMapItemEnvelope` version 3. On upstream, a different struct is used to store all envelope points including bezier information, which broke compatibility to old clients.

Fix holding Ctrl for slow envelope point editing not working for vertical movement.

Highlight the currently selected element (envelope point or bezier tangent marker) which is being used with the value/time edit boxes.

Hide the value/time edit boxes when no element is selected.

Add a version item check in `CMap`.

Support loading maps with `CMapItemLayerTilemap` version 4, which makes use of the `CTile::m_Skip` member to compress tile layers.

Support loading CMapItemImage version 2. This map item version adds the `m_Format` field, which specifies the image format for embedded images. The default value is `CImageInfo::FORMAT_RGBA` for map items of the previous version.

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Status: I don't actually know. Probably waiting for decision on what to implement.

Nit: I find it a bit weird to use `CDataFileReader` as a index → byte array container (`ReplaceData`).

Supporting the loading of upstream maps sounds good.

Saving bezier curves in a format incompatible with old DDNet clients sounds bad to me. I'd either write our own backward compatible extension to save those, or simply not support saving them.

**Comment by ChillerDragon** [comment]
**bump** is this blocked by anything? I would really love to see this merged.

**Comment by Robyt3** [comment]
I'll try to work on this next. I think those are the general steps:

- [ ] Support loading maps with `CMapItemEnvelope` version 3 (additional `CEnvPoint` members for bezier)
- [ ] Port upstream bezier rendering code
- [ ] Port upstream bezier editor code
- [ ] Support saving maps with bezier envelopes in backwards compatible format

**Comment by Robyt3** [comment]
It was easier then expected to port the editor code. Loading upstream maps should work correctly, haven't tested with lots of other maps yet though. Code might still need some cleanup.

**Comment by Robyt3** [comment]
Ready for some comments. #6530 should be merged first, because the PRs will conflict.

**Comment by Patiga** [comment]
Regarding image item version 2: https://github.com/teeworlds/teeworlds/issues/2812. Sadly, this issue is stale.
We could talk about whether we want to support that item version.
When I coded twmap, that issue was fresher, and I decided to not support RGB images. I figured that this addition to the map format doesn't seem to serve a purpose other than increase code complexity, and should not be incentivized.
Instead, I opted to just throw an error if I encounter an RGB image.
However, that issue is now also already 2.5 years old and things might've changed and more maps with RGB images might exist.

Bézier curves on the other hand are a great addition imo. They are super flexible compared to the other curve types and also a standard feature in other animation software. It's a bit sad that they made it a breaking change.

**Comment by Patiga** [comment]
To give context and figure out if I understand correctly:
- Env Points were their own item type which always only had one item with all the point data
- Env Pointe Ex would simply be another added item type with no redundant data, just with one set of bezier values for each envelope point

I always thought it was weird that the envelope points were the only piece of dynamically sized data which is not contained in a data-item for compression. However weird that might be, decompression is by far the slowest process during map loading, so I'd be fine with continuing that trend. I support this way of adding bezier curves. However, I don't have an educated opinion on how vanilla-related compatibility/incompatibility should be done.

**Comment by ChillerDragon** [comment]
@heinrich5991 any updates on this?

**Review by def- — APPROVED** [review]
@heinrich5991 If you have no complaint, I'd submit this.

**Comment by Robyt3** [comment]
It will probably conflict with #6752, so I'll rebase this again later.

**Comment by ChillerDragon** [comment]
@heinrich5991 robsti seems finished with this :)

The two prs #6872 and #5949 would like to see this merged.

**Pull request merged**
