### PR TITLE
Copy ingame console like in ATH

### PR DESCRIPTION
**Pull request by BloodWod-513**
The idea is taken from the implementation of this in ATH client

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Could you try to get rid of the 4 merges, you can try rebasing on current master state instead.
Also clang-format is failing

**Comment by BloodWod-513** [comment]
> Could you try to get rid of the 4 merges, you can try rebasing on current master state instead.
> Also clang-format is failing
Yes, I would like to figure out how to avoid this, but when I use the rebase there are no these commits (merges)

**Comment by heinrich5991** [comment]
Try
```
git fetch https://github.com/ddnet/ddnet
git rebase FETCH_HEAD
```

**Comment by BloodWod-513** [comment]
> Try
> 
> ```
> git fetch https://github.com/ddnet/ddnet
> git rebase FETCH_HEAD
> ```

Thank you

**Comment by Jupeyy** [comment]
btw this is purposly on draft, bcs we talked in PM and i wanted to refactor textrenderer class a bit so its easier to use selection generally

**Comment by Jupeyy** [comment]
@BloodWod-513 Last commit is how to integrate it with the new refactoring
Also allowed multiple lines to be copied, guess that can be useful

**Comment by Jupeyy** [comment]
If you want you can fix some stuff(e.g. page down/up should reset selection, stuff like that :D)

**Comment by Jupeyy** [comment]
LGTM, i tested your latest changes and they work

**Comment by Jupeyy** [comment]
Ok found one edge case
When console is selected, then closed

then new console lines are added

Then it still uses the old selection

**Comment by BloodWod-513** [comment]
> Ok found one edge case
> When console is selected, then closed
> 
> then new console lines are added
> 
> Then it still uses the old selection

I thought to leave it as a feature

**Comment by Jupeyy** [comment]
> I thought to leave it as a feature

I see, i mean its not horrible, just weird that the selection doesnt move up.

**Comment by Jupeyy** [comment]
Why is it not moving up btw, thought we implemented the counter for thatxD

**Comment by BloodWod-513** [comment]
> > I thought to leave it as a feature
> 
> I see, i mean its not horrible, just weird that the selection doesnt move up.

All the verification takes place in the render where pEntry. Maybe that's why, I don't know

**Comment by Jupeyy** [comment]
> Why is it not moving up btw, thought we implemented the counter for thatxD

`m_NewLineCounter = 0` might be called without entities being rednered, that's probs my fault
Wanna patch or should i?

**Comment by Jupeyy** [comment]
I'll improve the char bearing a bit now, after i finished, it looks good to me,
@BloodWod-513 do you still have anything you are unhappy with, even if its minor?

**Comment by BloodWod-513** [comment]
> I'll improve the char bearing a bit now, after i finished, it looks good to me,
> @BloodWod-513 do you still have anything you are unhappy with, even if its minor?

So far, I don't find any more problems

**Comment by Jupeyy** [comment]
I guess without mono fonts it will never be perfect with the char hitboxes and selection, not even libreoffice is really good, but atleast i improved it a bit, especially for the first and last char in the selection :D

**Comment by def-** [comment]
Really cool, seems to work well. But wow, that's a huge diff.
bors r+

**Pull request merged**
