### PR TITLE
Add loglevel config (fixes #5178, fixes #5174)

### LINKED ISSUE #5174: Register output even when sv_register 0 is set
I keep getting this output even with `sv_register 0`. I guess could disable it:
```
[2022-05-20 23:17:56][register]: info: {"max_clients":64,"max_players":64,"passworded":false,"game_type":"TestDDraceNetwork","name":"My DDNet server","map":{"name":"Embrace","sha256":"d8098a29b6e3621928fa57570dcce5b22c932b47a81c52a40b3546240b65b824","size":345491},"version":"0.6.4, 16.1","clients":[]}
```
@heinrich5991 agreed?

### LINKED ISSUE #5178: Set log_level?
Right now everything is always logged, including tracing.

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I would rather put that into the respective loggers. Where do you want to reduce the log level? stdout? f1?

**Comment by def-** [comment]
Both. Trace and debug logging should not be shown by default.

**Comment by def-** [comment]
logfile logging on servers is becoming so huge now that we are running out of disk space and are losing teehistorian files on RUS. The logs are full of register info messages.

**Comment by C0D3D3V** [comment]
This looks good to me. I see it the same as deen, the log level should apply to all outputs. Can we merge this @heinrich5991?

**Comment by heinrich5991** [comment]
Sorry for my lack of communication. I'd rather have one config for each log output, defaulting to log only info and more severe. Since I haven't done that yet, I guess I should merge it for now.

bors r+

**Review by heinrich5991 — APPROVED** [review]

**Pull request merged**
