### PR TITLE
Fix crash on test servers (fixes #3789)

### LINKED ISSUE #3789: Crash on test servers with rcon usage
```
(gdb) bt
#0  0x000056009d33cc36 in CGameTeams::ResetRoundState (this=this@entry=0x56009ee14b80, Team=Team@entry=64)
    at /home/teeworlds/src/master/src/game/server/teams.h:53
#1  0x000056009d33f93e in CGameTeams::OnCharacterDeath (this=0x56009ee14b80, ClientID=1, Weapon=Weapon@entry=-2)
    at /home/teeworlds/src/master/src/game/server/teams.cpp:879
#2  0x000056009d304d72 in CCharacter::Die (this=0x56009d3f84d0 <ms_PoolDataCCharacter+4048>, Killer=<optimized out>, 
    Weapon=Weapon@entry=-2) at /home/teeworlds/src/master/src/game/server/player.h:35
#3  0x000056009d32e821 in CPlayer::KillCharacter (this=this@entry=0x56009d437228 <ms_PoolDataCPlayer+1160>, 
    Weapon=Weapon@entry=-2) at /home/teeworlds/src/master/src/game/server/player.cpp:589
#4  0x000056009d324dca in CGameContext::OnMessage (this=0x7fdb5dd93010, MsgID=<optimized out>, 
    pUnpacker=0x7ffd92368150, ClientID=1) at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:2366
#5  0x000056009d2f82d0 in CServer::ProcessClientPacket (this=0x7fdb5fdca010, pPacket=0x7ffd92369570)
    at /home/teeworlds/src/master/src/engine/server/server.h:110
#6  0x000056009d2f96ab in CServer::PumpNetwork (this=0x7fdb5fdca010, PacketWaiting=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2236
#7  0x000056009d2fa094 in CServer::Run (this=0x7fdb5fdca010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2622
#8  0x000056009d2e8120 in main (argc=3, argv=0x7ffd9236a2b8)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3602
```

### PR DESCRIPTION
**Pull request by def-**
Thanks to Cøke for report

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Introduced by https://github.com/ddnet/ddnet/pull/3654/ I believe

**Comment by heinrich5991** [comment]
I don't follow completely. My thoughts: SvTeam = 3 means it's a solo server? Each person is in their own team there, with team ID equal to client ID? TEAM_SUPER is 64, and calling the function with 64 is going to lead to some out of bounds access in the function?

**Comment by def-** [comment]
Yes. And someone used super, that put them into TEAM_SUPER.

**Comment by heinrich5991** [comment]
bors r+

Thanks for the explanation.

**Pull request merged**
