### PR TITLE
Rework the pause system

### PR DESCRIPTION
**Pull request by Learath2**
Fixes some odd bugs about the pause system. Including `/pause` while `/spec`, vice-versa and `force_pause`.

Consequently fixes the vote "Move player to spectators".

First reported in #628.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Only gave it a very quick glance – maybe it shouldn't be "force-paused" if it doesn't correspond to `/pause` – perhaps "you have been moved to spec"?

**Comment by Learath2** [comment]
It does correspond to `/pause` b/c I assumed we want to keep them switched. 

Now at code level it is as expected `PAUSE_SPEC` removes your character as soon as its stable and grounded `PAUSE_PAUSE` pauses your character. The meanings are switched at command level `/spec` calls `ConTogglePause` and `/pause` calls `ConToggleSpec`

**Comment by Rootkitee** [comment]
Nice Learath - aka Slishtee ( Hint* Hint)

**Comment by Learath2** [comment]
Are you Slishtee or am I Slishtee. I was chatting with him a day or two ago, If I was Slishtee why would I be chatting with Slishtee. Do I have multiple personality disorder? /me is confused.

**Comment by Rootkitee** [comment]
Omg im hitting for you to come see me ingame u fool xD

**Comment by heinrich5991** [comment]
But vote-to-spec is supposed to remove your character, like `/spec`, if `/spec` is allowed on the server (otherwise it just moves you to spectators).

**Comment by Learath2** [comment]
/me is confused again. Didn't we swap around  `/pause` and `/spec` which means `/pause` moves the player to spec and as an extension of that concept "pausing" refers to using `/pause`

**Comment by heinrich5991** [comment]
Both `/spec` and `/pause` let the player view the map as if in the spectator mode. `/spec` also removes your character from the map and stops the race timer until you enter again.

Vote to spec is supposed to use force-`/spec` if it is available, otherwise it should move to spectators.

**Comment by Learath2** [comment]
So we don't have them switched around?

**Comment by heinrich5991** [comment]
Once upon a time, the roles of `/pause` and `/spec` were not the same as today. But deen has switched them since then, so that's where we are today.

**Comment by def-** [comment]
Becaus everyone had a bind for /pause, and then we enabled disappearing on /pause on a few maps and it was super annoying that tees disappeared everywhere. So I tried educating people to use /spec instead but my attempts were futile. So instead I just switched them around.

**Comment by heinrich5991** [comment]
This was not ment as critique, it was just a history lesson. ^^

**Comment by Learath2** [comment]
Oh so `/pause` isn't supposed to make you disappear at all

**Comment by heinrich5991** [comment]
That's true.

**Comment by timakro** [comment]
Is there a good reason why you can't spec and unspec quickly after each other?

**Comment by Learath2** [comment]
No, I fixed that in #774, you always get a guaranteed unspec in that PR. The delay in general was for the spam of sound and visual effects, at least that's why we added it in the first place.

**Comment by Ryozuki** [comment]
I would remove the delay like before, i never saw that "spam".

**Comment by Learath2** [comment]
The delay was always there :)

**Pull request merged**
