### PR TITLE
Add SQL/Score tests

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I'm a bit confused by the failure on Ubuntu 18.04:
```
[ RUN      ] Score.SaveScore
/home/runner/work/ddnet/ddnet/src/test/score.cpp:62: Failure
Value of: CScoreWorker::SaveScore(conn, &scoreData, false, aError, sizeof(aError))
  Actual: true
Expected: false
no such column: false
[  FAILED  ] Score.SaveScore (3 ms)
```
sqlite behavior change?

**Comment by def-** [comment]
Next steps:
- Make the same tests run with MySQL backend
- Add Postgres backend, and make the tests run with them too
But can also be done in a separate change, if someone wants to review this already. The productive code is just moved from score.cpp to scoreworker.cpp, so risk of this change should be low.

**Comment by heinrich5991** [comment]
I like it a lot, thanks for writing code that tests the DB stuff.

Could we maybe keep building DDNet on ubuntu-18.04 even if we don't test it there? Just so we keep build-compatibility.

Status: Needs rebase.

**Comment by def-** [comment]
Done

**Comment by heinrich5991** [comment]
One failing test on latest Ubuntu, disabling the tests didn't seem to work on old Ubuntu.

**Comment by def-** [comment]
Fixed, I hope

**Comment by heinrich5991** [comment]
One more failing test in old Ubuntu.

**Comment by def-** [comment]
Finally green

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
