### PR TITLE
Remove deepfly binds (fixes #3667)

### LINKED ISSUE #3667: fix controls for deepfly / 45 deg angle
they are broken if you do not have:
mouse1 hammer mouse2 for deepfly 
and
200 sens and 400 mouse_max_distance for 45 degree angle

this will break a lot of people's controls and they will be confused, should either be removed temporarily or fixed quickly. the binds should grab the key binded to those controls and use those instead of using presets.

Also, maybe implement a single key for toggling deepfly similar to the hammerfly bind instead of having a separate key for on/off

### PR DESCRIPTION
**Pull request by def-**
Anyone have a better idea?

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by gerdoe-jr** [comment]
Can be fixed if we'll save mouse1 bind before rebinding. That also doesn't fix current problem because player can use another button to fire (should we find this bind among others somehow?)

45 degree bind problem is solving by saving before use too.

**Comment by l-ouis** [comment]
does this remove the 45 degree angle bind too? that one messes up people's configs more than deepfly

**Comment by def-** [comment]
Done

**Comment by Learath2** [comment]
I gave 2 options for ways to keep this in #3667. A third way would be to generate the bind at the time it's bound in controls but that could still lead to broken configs.

I think the easiest option is to remove these unless someone wants to spend the time to fix this.

**Comment by heinrich5991** [comment]
I think this is good to go. This has a merge conflict now, unfortunately.

**Comment by def-** [comment]
Fixed.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
