### PR TITLE
Treat timeout code as sensitive data

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by Learath2** [comment]
The logs are only seen by the owner of the server. If the concern is a malicious server owner you can't be sure they didn't modify the code.

I don't see any other safety concern with them, so I think timeout codes aren't sensitive data.

**Comment by ChillerDragon** [comment]
@Learath2 it reduces the possibility that an non tech server hoster finds that in the logs and decides to troll far players on ddnet. And i also would like to share the logs with people i don't have to trust in some situations. Some public logs would be fun to read chat historys or what ever. you are right the server hoster could always modify the server but this doesn't mean we should ship an sensitive data sniffer.

**Comment by Learath2** [comment]
You can't really troll with it easily either. You'd need to knock off the player somehow to steal his place ((D)DoS).
There is no trivial use for knowing someones timeout code.

My point is that the data is not sensitive so by definition we aren't shipping a sensitive data sniffer.

For log sharing It'd be better to write a tool to censor logs then to censor the actual log.

**Comment by heinrich5991** [comment]
If you want to strip the logs from this data, you can use this sed command line:
```
cat logs | sed 's|\(\[[0-9: -]*\]\[chat-command\]: [0-9]* used /timeout \).*|\1[censored-code]|'
```

**Comment by heinrich5991** [comment]
(I have not tried to determine whether we should pull these changes or not.)

**Comment by ChillerDragon** [comment]
no comment ._.

**Comment by def-** [comment]
What Learath2 said.

**Pull request closed without merging**
