### PR TITLE
Fix x11 notify by Maiski

### PR DESCRIPTION
**Pull request by Jupeyy**
This works on KDE without problems, he also tested on i3

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Would ofc be nice if this somehow would be done dynamically so we dont need x11 at compile time.

But atleast better than before :D

**Comment by def-** [comment]
On xmonad I think this changes the behaviour. Previously when I had the window open on another virtual desktop on another screen (but not focussed) it would still show me an x11 notify telling me on which desktop it is. With this change I only get the notification when the desktop is not on any visible screen.

**Comment by Jupeyy** [comment]
> On xmonad I think this changes the behaviour. Previously when I had the window open on another virtual desktop on another screen (but not focussed) it would still show me an x11 notify telling me on which desktop it is. With this change I only get the notification when the desktop is not on any visible screen.

is it bcs of the // Old hints
or was it bcs of the other code?
bcs the old hints just didnt do anything on KDE, so maybe there's still a chance :D

**Comment by Jupeyy** [comment]
ok i was wrong, both versions are broken

**Comment by Jupeyy** [comment]
a lib that detects the WM or DE would be really better, to bad i cant find anything

**Comment by vainiovano** [comment]
I'm the Discord user Maiski.

@def- I have no idea why this patch changes the behaviour on xmonad because [it seems to handle `UrgencyHint` and `_NET_WM_STATE_DEMANDS_ATTENTION` in the exact same way](https://github.com/xmonad/xmonad-contrib/blob/aa6d1eb60b69dcfc148b47df5b55d9d2f8ac9b3b/XMonad/Hooks/UrgencyHook.hs#L356-L380).

So, do other applications that use urgency work as expected? What is your `SuppressWhen` setting?

**Comment by def-** [comment]
Ok, apparently I misremembered and it works the same, my bad. What about the problem Jupeyy still had?: "ok i was wrong, both versions are broken"

**Comment by Jupeyy** [comment]
I meant the old code only

**Comment by vainiovano** [comment]
> But why sending the event is different to changing these property... No idea

[EWMH says](https://specifications.freedesktop.org/wm-spec/latest/ar01s05.html#idm45953950695264):
> The Window Manager SHOULD honor _NET_WM_STATE whenever a withdrawn window requests to be mapped. A Client wishing to change the state of a window MUST send a _NET_WM_STATE client message to the root window (see below). The Window Manager MUST keep this property updated to reflect the current state of the window. 

Many window managers only check a window's _NET_WM_STATE property when a client requests the window to be mapped. After that, the window's _NET_WM_STATE property is basically owned by the window manager and the window's owner shouldn't change it directly. I think that it is designed like this in order to avoid some race conditions, because both parties can change the window's state.

Many window managers don't do anything if a window's _NET_WM_STATE property is directly written to, but it seemed to affect KDE in some way.

**Comment by Jupeyy** [comment]
if everything is so well documented, why has nobody yet made a cross windowmanager and cross plattform notifier, do you know such a lib maybe?
I wish SDL could just implement it, then we wouldn't require x11 dependencies

**Comment by vainiovano** [comment]
GLFW has `glfwRequestWindowAttention` for requesting attention, but it obviously requires using GLFW. I don't know if there are any cross-platform libraries that only handle requesting attention.

**Comment by Jupeyy** [comment]
just asked upstream `https://github.com/libsdl-org/SDL/issues/4372`

**Pull request merged**
