### PR TITLE
Allow specifying DATA_DIR by compiler option

### PR DESCRIPTION
**Pull request by yangfl**

### CODE REVIEW

**Comment by def-** [comment]
What's the motivation here?

**Comment by yangfl** [comment]
Since the original DATA_DIR does nothing more than line 168, either. (rather than wasting cpu time)

**Comment by heinrich5991** [comment]
Looks good to me.

bors r+

Thanks.

**Comment by def-** [comment]
This change breaks running DDNet from Steam for example, since that requires the data path etc.

**Comment by yangfl** [comment]
How it was broken? It should not affect any existing code except you modify DATA_DIR before every compile (which is a bad practice).

**Comment by def-** [comment]
Well we needed m_aDataDir to be set to data directly and not aBaseDir/data. I guess this is because DDNet is a bit stricter about accessing files from absolute paths, while relative paths work.

**Pull request merged**
