### PR TITLE
Resample to the device playback rate

### LINKED ISSUE #8815: Sound issues for some Android users
@headshot2017:

> sound is broken atm but other than that it runs fine
> i hear like crackling/garbage on the music and SFX
> fixed it by changing `snd_rate` to 44100
> it was 48000 by default

@TsFreddie 

> sounds like sampling issue
> i can probably tell what's wrong just by hearing it. i've been dealing with rhythm game and custom audio engine too much.

@BlaiZephyr:
> android version works flawlessly except for map sounds randomly bugging out on server join - can someone reproduce it? - best map would be nostalgia/binary ig - happened 2-3 times, then never again 

We could set the sampling rate to 44100 per default on Android as a workaround, if this fixes the issue for everyone, but I'd like a proper fix for whatever is causing this.

### PR DESCRIPTION
**Pull request by TsFreddie**
Fixes #8815 
> at least attempted to

Test needed from affected users. @headshot2017 

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]

**Comment by TsFreddie** [comment]
sorry. re-did the pr to minimize the changes.

**Review by Robyt3 — COMMENTED** [review]
Not sure if this has any effect because the last parameter of `SDL_OpenAudioDevice` is set to zero.

See https://wiki.libsdl.org/SDL2/SDL_OpenAudioDevice

> If your application can only handle one specific data format, pass a zero for `allowed_changes` and let SDL transparently handle any differences.

Seems like this makes SDL do the resampling to enforce the specified input format. Should specify only `SDL_AUDIO_ALLOW_FREQUENCY_CHANGE` AFAICT.

**Comment by TsFreddie** [comment]
> Not sure if this has any effect because the last parameter of `SDL_OpenAudioDevice` is set to zero.

You are right.
https://github.com/libsdl-org/SDL/blob/4eac44bed446f1ce9083b765dd9744b8ca81497e/src/audio/SDL_audio.c#L1446

> Should specify only `SDL_AUDIO_ALLOW_FREQUENCY_CHANGE` AFAICT.

Let's try that. Although if this works, it means SDL2 might be doing something wrong on Android.

**Comment by TsFreddie** [comment]
@headshot2017 can you also try snd_buffer_size 1024 instead of changing snd_rate

**Comment by headshot2017** [comment]
> @headshot2017 can you also try snd_buffer_size 1024 instead of changing snd_rate

snd_rate with default value (48000) and snd_buffer_size 1024 still plays crackling and garbage noises

**Review by Robyt3 — APPROVED** [review]
LGTM, can you squash the commits?

**Comment by TsFreddie** [comment]
> > @headshot2017 can you also try snd_buffer_size 1024 instead of changing snd_rate
> 
> snd_rate with default value (48000) and snd_buffer_size 1024 still plays crackling and garbage noises

Thanks, let's try this after we have an Android build of this.

**Pull request merged**
