### PR TITLE
Use 0.7 gameskin by @Zatline

### PR DESCRIPTION
**Pull request by Jupeyy**
https://github.com/teeworlds/teeworlds/commit/a5105264ff9366c3bf5deb8aaa3aba7026640c46
https://github.com/teeworlds/teeworlds/commit/db0823950609859327ee96aea62271877d61d984
https://github.com/teeworlds/teeworlds/commit/31c6d2684d6a0f08a311fc5edd5c165b9efa1d4f

Wtf is clang-format doing in line 257 xD (will just use clang-format-10 for now to fix it)

dunno if github can close prs
closes #2921

and ty to @ChillerDragon for the initial commit,

game.png is dilated, and optimized.

So i guess we wait for #2754 ?

### CODE REVIEW

**Comment by def-** [comment]
Why wait for #2754? Looks like this can be submitted.

**Comment by Jupeyy** [comment]
ah thought bcs of overwritting game.png

**Comment by def-** [comment]
If we want to wait for #2754, we don't just have to wait for it to be released, but at least a few months until enough players switch to it.

**Comment by Jupeyy** [comment]
well i guess most ppl are on steam now, but yeah, probs makes no sense to wait

**Comment by def-** [comment]
Should we add the old gameskin in assets at least?

**Comment by Jupeyy** [comment]
i'd prefer the first, except the hearts its not a huge difference anyway, and the 0.7 hearts deffs look much nicer :D

**Pull request merged**
