### PR TITLE
Remove IP skins

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by fokkonaut** [comment]
Why do you remove them?

**Comment by def-** [comment]
We don't have the permission to distribute others' intellectual property.

**Comment by Patiga** [comment]
Skimmed through the skins, also noteworthy are:
```
pikminpurple.png
pikminwhite.png 
pikminyellow.png
red_bird.png
Shadow.png
t2.png
Blind r0xr.png
```

**Comment by def-** [comment]
Thanks, removed.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
