### PR TITLE
Make server aware of client prefered language

### PR DESCRIPTION
**Pull request by edg-l**
This an initial pr towards having server side localization to help with https://github.com/ddnet/ddnet/issues/269#issuecomment-706080357

I don't know if we should normalize the language (currently whats send is the language file...), use a enum or what.

(This pr doesnt add localization yet)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I think it would be better if we kept localization in the client, with the server sending generic messages.

**Comment by heinrich5991** [comment]
To expand: We can update the client with new messages, but we can't update the servers that other people run.

**Comment by edg-l** [comment]
> To expand: We can update the client with new messages, but we can't update the servers that other people run.

maybe thats better yeah

**Comment by edg-l** [comment]
loook https://github.com/ddnet/ddnet/issues/3091

**Pull request closed without merging**
