### PR TITLE
Handle FS failures while updating (fixes #1560)

### LINKED ISSUE #1560: When updating removing and overwriting might fail, print a big error
It seems like some AV software that Colora on Discord uses blocks our client from updating. Disabling it fixes the issue. We should catch if we can't overwrite the executable during update and print a big error message.

Update: The software is AVG, adding an exception for DDNet makes it work again.

### PR DESCRIPTION
**Pull request by def-**
Not sure if I caught all locations

### CODE REVIEW

**Comment by Ryozuki** [comment]
You are using goto, some people would  call you a demon :imp:

**Comment by def-** [comment]
I'm emulating try-catch because we pretend to be using C inside of classes.

**Comment by def-** [comment]
Could also wrap it in a function I guess, but meh.

**Comment by def-** [comment]
Wrapped it, no more devilish goto.

**Pull request merged**
