### PR TITLE
Recreate all entities when restarting round, fix server crash on maps with more than 64 spawn points of same type

### PR DESCRIPTION
**Pull request by Robyt3**
## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Just to make sure, this does not affect weapons shot yourself, right? Because those not resetting is intentional and gets used for race map speed runs

**Comment by fokkonaut** [comment]
> Just to make sure, this does not affect weapons shot yourself, right? Because those not resetting is intentional and gets used for race map speed runs

This will only be done when using the restart command, when all tees get killed, not when a single tee respawns.

**Comment by def-** [comment]
Oh right, it's still fixing the `restart` command which we don't use anyway.
bors r+

**Comment by teini94** [comment]
Works Nice ! with Solo Maps specially with Lasers . Great Job.

However if u use it when u joined into a Team -

it seems to think your in team 0
- u can Restart ur Time when u reenter Start
- each player has a their own Race time (no teamtime)
- u can interact with team 0 players (but they look invisible if ur alpha is 0/low enough)
- u cant unlock or lock ur team (like in team 0 normally)
- (u first have to join another team (before u first hit the Start) and then u can join team 0 again.)

**Pull request merged**
