### PR TITLE
Fix all Multiplication type alerts by CodeQL

### PR DESCRIPTION
**Pull request by def-**
> Multiplication result converted to larger type

> A multiplication result that is converted to a larger type can be a
> sign that the result can overflow the type converted from.

Example: https://github.com/ddnet/ddnet/security/code-scanning/17?query=ref%3Arefs%2Fheads%2Fmaster

### CODE REVIEW

**Comment by heinrich5991** [comment]
As far as I can see, this just silences the warning. Incorrect results still occur.

1) Casting to `size_t` will wrap negative integers to large positive integers.
2) (Maybe not so relevant:) On 32 bit, `size_t` is also just 32 bit, so the multiplication can still trivially overflow.
3) On 64 bit, when we have 3 factors, the multiplication can still overflow.

What would be needed here is checking the factors before multiplication to ensure that overflow does not occur.

**Comment by def-** [comment]
The only thing this warning was about and that I tried to fix was: If a value gets multiplied and can fit into the type that it will be stored into, it should not overflow.

**Comment by heinrich5991** [comment]
bors r+

Thanks for the elaboration.

**Comment by def-** [comment]
And to be clear: It would still be better to switch many types to something like size_t and make things safer, so that we can at least allocate as much memory as the system supports.

**Comment by heinrich5991** [comment]
I disagree. It does not make things more secure, integer overflow is still possible and the attacker can still abuse it. The only thing this does is give us fuzzy feelings for having less warnings.

**Comment by heinrich5991** [comment]
(It even enabled a different class of overflows due to the change to unsigned integers.)

**Comment by def-** [comment]
So let's revert this?

**Pull request merged**
