### PR TITLE
Add color selector for Tee settings (fixes #3576)

### LINKED ISSUE #3576: color picker missing for Tee colors and UI color
@Banana090 could you add this?

as reported by louis

### PR DESCRIPTION
**Pull request by def-**
Can't be done for UI yet since alpha is not supported
screenshot-20210201@233523

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Cool.
Skins dont have the full color range tho

**Comment by gerdoe-jr** [comment]
Will client support old color choosing sliders?

**Comment by def-** [comment]
No, of course not.

**Comment by heinrich5991** [comment]
> Cool.
> Skins dont have the full color range tho

Would be better to show the actual colors that can be picked IMO.

**Comment by Jupeyy** [comment]
We could also think about enabling the full color range

**Comment by heinrich5991** [comment]
It made tees' eyes hard to see, I wouldn't like that. The completely black tee skin was quite popular.

**Comment by Jupeyy** [comment]
> It made tees' eyes hard to see, I wouldn't like that. The completely black tee skin was quite popular.

Yeah understandable, 0.7 allows a wider range tho, doesnt it?

**Comment by Learath2** [comment]
> > It made tees' eyes hard to see, I wouldn't like that. The completely black tee skin was quite popular.
> 
> Yeah understandable, 0.7 allows a wider range tho, doesnt it?

Slightly, yes. The darkest is a tad darker there

**Comment by Jupeyy** [comment]
Not required anymore

**Pull request closed without merging**
