### PR TITLE
Remove /modhelp (fixes #1401)

### LINKED ISSUE #1401: Remove /modhelp
Pointless feature since there is no way to make it non-abuseable

### PR DESCRIPTION
**Pull request by def-**
Thoughts? I wasn't really involved with the development and usage of this feature, so I can't judge, but removing it is easy enough.

### CODE REVIEW

**Comment by def-** [comment]
Also fixes #1378 I guess.

**Comment by def-** [comment]
Oh well, too bad for all the work that went into this :/

**Comment by heinrich5991** [comment]
LGTM. Not too much work went into this.

bors r+

**Comment by def-** [comment]
Build failure unrelated.

**Pull request merged**
