### PR TITLE
Reset practice after team saved and got killed

### PR DESCRIPTION
**Pull request by def-**
As reported by Polector on Discord

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
Sounds like this should happen in the function right below this one `ResetSavedTeam`. Or maybe even in `onChangeTeamState` which is interestingly never used :P

**Comment by def-** [comment]
No, ResetSavedTeam empties out the team, which is different from this.

**Comment by heinrich5991** [comment]
This looks annoying to review. :( Such a good change for potentially allowing to cheat. ^^

**Comment by def-** [comment]
I don't think it can be used for cheating. All players in team are killed and only after that practice mode is disabled.

**Comment by Zwelf** [comment]
I'm not sure what this PR is trying to fix.

After issuing a `/save` the team gets killed and enters a mode, where it waits for an acknowledgment. Most of the times this mode only lasts for less than a second. During this mode, the team can't start. Therefore it shouldn't matter if the team is still in `/practice`. If the saving fails, the team gets loaded again (reason for this mode). And if the saving succeeds, the team gets reset (including `/practice` I believe).

To test what can happen during this mode you can add a delay to the MySQL-Server (running localhost)[[1]](https://stackoverflow.com/a/40203517):

```bash
sudo tc qdisc add dev lo root handle 1: prio priomap 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
sudo tc qdisc add dev lo parent 1:2 handle 20: netem delay 3000ms
sudo tc filter add dev lo parent 1:0 protocol ip u32 match ip dport 3306 0xffff flowid 1:2
```

**Comment by def-** [comment]
> And if the saving succeeds, the team gets reset (including /practice I believe).

This is the part that doesn't work according to Polector.

**Comment by Zwelf** [comment]
Ah, can reproduce now for solo servers. Should go in `ResetSavedTeam` as Learath2 said. ResetSavedTeam gets called, when the save was successful.

**Comment by def-** [comment]
done

**Comment by Zwelf** [comment]
Looks good now and works as intended.
* [x] Tested the change ingame

bors r+

**Pull request merged**
