### PR TITLE
Allow moderators to use dump_log for 10 min

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Vy0x2** [comment]
lgtm but should test it if it doesnt crash/timeout the rcon users when too many messages get displayed. There was a problem like that with bans, doesnt it?
I can test it later this day.

**Comment by Vy0x2** [comment]
Okay two problems:

- I experience permanent crashes with max_logs = 1024 (same problem as bans?)
- There is a bug in the current code where sometimes it cuts off and something like that will be displayed:

`2023-07-15 11:35:19 I server: ClientID=0 rcon='dump_log'`
`2023-07-15 11:35:19 I log: , -66 seconds ago < addr=XXX name='O�� ' client=0`
`2023-07-15 11:35:19 I log: Chat: hi, 10 seconds ago < addr=XXX name='Vy0x2.'' client=17011`
`2023-07-15 11:35:19 I log: Chat: hi, 10 seconds ago < addr=XXX name='Vy0x2.'' client=17011`

or

`2023-07-15 11:42:50 I server: ClientID=0 rcon='dump_log'`
`2023-07-15 11:42:50 I log: , -787 seconds ago < addr=XXX name=' ה&v ' client=374`
`2023-07-15 11:42:50 I log: Chat: hi, 10 seconds ago < addr=XXX name='Vy0x2.'' client=17011`
`2023-07-15 11:42:50 I log: Chat: hi, 10 seconds ago < addr=XXX name='Vy0x2.'' client=17011`

I tested it with sv_spamprotection 0 and sv_spam_mute_duration 0.
I can imagine that when messages are flying in too quickly something breaks, but i have to investigate it further.

**Comment by def-** [comment]
I'll let you take this over @Vy0x2 . You cold try sleeping inbetween sending the logs.

**Comment by Vy0x2** [comment]
superseded by #6865

**Pull request closed without merging**
