### PR TITLE
Version 9.1

### PR DESCRIPTION
**Pull request by H-M-H**

### CODE REVIEW

**Comment by H-M-H** [comment]
If you think there is something important missing for the next version leave a comment here. If there are no problems I will merge this soon and we will finally have a new release.

**Comment by def-** [comment]
Important remaining bugs:
- Having the same name twice on server: https://github.com/ddnet/ddnet/issues/381
- Having names with newlines in them
- Auto demo recorder doesn't work properly

**Comment by H-M-H** [comment]
True but as of this https://github.com/ddnet/ddnet/pull/396 and this https://www.teeworlds.com/forum/viewtopic.php?id=11739 I do not want to wait too long.

**Comment by def-** [comment]
Sure, but you asked. For all I care you can make a release per day.

**Comment by H-M-H** [comment]
Ok, thanks for reminding. Nevertheless it is time to bring out a new release.

**Pull request merged**
