### PR TITLE
Fix macos github action

### PR DESCRIPTION
**Pull request by def-**
Currently seeing:
```
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/pthread.h:331:6: error: macro expansion producing 'defined' has undefined behavior [-Werror,-Wexpansion-to-defined]
```
and
```
In file included from /Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/client/backend_sdl.cpp:15:
/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
/Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
```

### CODE REVIEW

**Comment by Learath2** [comment]
The second one I had to reinstall xcode to fix, it's command line tools and the toolchain included in xcode somehow conflicting. Couldn't fix it for the life of me.

**Comment by def-** [comment]
Verbose build output:
```
2020-05-01T09:04:31.3272070Z [ 65%] Building CXX object CMakeFiles/DDNet.dir/src/engine/client/client.cpp.o
2020-05-01T09:04:31.3380750Z /Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DCONF_DEBUG -DGLEW_STATIC -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/freetype/include/freetype2 -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/external/glew -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/opus/include/ogg -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/opus/include -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/opus/include/opus -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/external/pnglite -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/sdl/include/mac -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/external/wavpack -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/debug/src -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src  -Wno-expansion-to-defined -Werror -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -std=gnu++11 -g -isysroot /Applications/Xcode_11.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9   -F/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/sdl/mac/lib64  -fstack-protector-all -stdlib=libc++ -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wno-nullability-completeness -o CMakeFiles/DDNet.dir/src/engine/client/client.cpp.o -c /Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/client/client.cpp
2020-05-01T09:04:31.3484800Z /Applications/Xcode_11.4.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DCONF_DEBUG -DGLEW_STATIC -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/freetype/include/freetype2 -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/external/glew -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/opus/include/ogg -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/opus/include -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/opus/include/opus -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/external/pnglite -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/sdl/include/mac -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/external/wavpack -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/debug/src -I/Users/runner/runners/2.169.1/work/ddnet/ddnet/src  -Wno-expansion-to-defined -Werror -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -std=gnu++11 -g -isysroot /Applications/Xcode_11.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9   -F/Users/runner/runners/2.169.1/work/ddnet/ddnet/ddnet-libs/sdl/mac/lib64  -fstack-protector-all -stdlib=libc++ -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wno-nullability-completeness -o CMakeFiles/DDNet.dir/src/engine/client/backend_sdl.cpp.o -c /Users/runner/runners/2.169.1/work/ddnet/ddnet/src/engine/client/backend_sdl.cpp
```

**Comment by def-** [comment]
Thanks @Learath2

**Pull request merged**
