### PR TITLE
Editor: fix click drag navigation selecting quads/sounds

### LINKED ISSUE #9002: Editor: click drag navigation can catch quads and alter their position
https://github.com/user-attachments/assets/f41ae00f-3df8-474d-a7aa-d8a45036c9e8

Mouse based navigation is impossible without breaking your map if it looks like this:

image

The group the quad is in needs para to be able to get moved under the cursor on move.

### PR DESCRIPTION
**Pull request by dobrykafe**
Closes #9002

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by Robyt3 — COMMENTED** [review]
Not sure about changing the existing hotkey.

Can you try to check if the active UI item is not `&m_MapEditorId` instead or something like that?

**Comment by dobrykafe** [comment]
> Can you try to check if the active UI item is not `&m_MapEditorId` instead or something like that?

Turns out it was never set as active item in the first place.

**Review by Robyt3 — CHANGES_REQUESTED** [review]
Nice, this looks like a cleaner solution already.

However, currently, when you pan over a quad or sound point it will briefly stop panning. You can avoid this by not allowing the quad and sound points to become to hot item if the map editor is the active item, so while panning is active the quad and sound points cannot be interacted with. For that add a check in `CEditor::DoSoundSource` so `SetHotItem` is only called when `Ui()->ActiveItem() != &m_MapEditorId`. And in `CEditor::SetHotQuadPoint` you can simply return immediately at the beginning if `Ui()->ActiveItem() == &m_MapEditorId`.

**Comment by dobrykafe** [comment]
@Robyt3 Done.
> However, currently, when you pan over a quad or sound point it will briefly stop panning.

How did you figure this out? Is there a quick and easy way?

**Review by Robyt3 — APPROVED** [review]

**Comment by Robyt3** [comment]
> How did you figure this out? Is there a quick and easy way?

I tested if the original bug was fixed by these changes and noticed that the panning speed and tooltip briefly changed when going the quad/sound points.

**Comment by dobrykafe** [comment]
I forgot to test the mouse3 version before and only tested the ctrl+mouse1 one. The active item and editor operation were getting reset when they shouldn't and the ctrl+mouse1 version kinda escaped that on accident.

**Review by Robyt3 — APPROVED** [review]
Thanks!

**Pull request merged**
