### PR TITLE
Update pull_request_template.md to mention the usage of smart pointers

### PR DESCRIPTION
**Pull request by edg-l**
Related to #5160 to we dont forget.

### CODE REVIEW

**Comment by heinrich5991** [comment]
I think we shouldn't pollute our pull request template with this. Perhaps we should rather reduce the amount of tick boxes there. Most aren't checked anyway.

**Comment by heinrich5991** [comment]
See e.g. this very pull request, it didn't use the template.

**Comment by edg-l** [comment]
maybe not put at as tick boxes but as hidden markdown comments so you remember

**Comment by heinrich5991** [comment]
No, I don't think we should add it as a requirement or to the PR template. The issue I opened was just about asking whether it's approved or not, just so I don't do stuff that doesn't have consensus.

**Pull request closed without merging**
