### PR TITLE
Provide MinGW SDL2 (fixes 13.0 on Windows)

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by def-** [comment]
untested

**Comment by def-** [comment]
I'd like to give this another try this evening.

**Comment by def-** [comment]
@heinrich5991 Doesn't quite work as intended:
```
  file COPY cannot find
  "D:/a/ddnet/ddnet/ddnet-libs/windows/lib64/vc/libcurl.dll": No such file or
  directory.
```

**Comment by def-** [comment]
Ok, got those errors (mostly, except for FFmpeg) fixed. New error on Windows VC build:

```
CMake Error at CMakeLists.txt:447 (message):
  You must install SDL2 to compile the DDNet client
```
Maybe we should just only ship the mingw version. After all we also only ship mingw stuff for everything else? I can try creating a .lib file for VS compatibility.

**Comment by def-** [comment]
looks fine now, ready for review

**Comment by Learath2** [comment]
@def- the CI failure seems genuine.
`Error copying file "D:/a/ddnet/ddnet/D:/a/ddnet/ddnet/ddnet-libs/curl/windows/lib64/curl.lib" to "pack_DDNet-13.0.1-win64_zip/DDNet-13.0.1-win64/".`

**Pull request merged**
