### PR TITLE
Add SendNotifications for custom ddnet forks

### PR DESCRIPTION
**Pull request by ChillerDragon**
Allows custom clients to implement own config system without touching
ddnet notify api

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
This changes the meaning of `ClShowNotifications` which should at the very least be documented.

FWIW I think this patch is just skirting around the issue by creating a configuration gray-zone which is to be later abused. If we want to allow filtering of notifications we should implement it explicitly.

However, I don't even think this is necessary at all since we are very conservative with our notifications and this is just trying to avoid a trivial merge conflict.

**Comment by ChillerDragon** [comment]
> However, I don't even think this is necessary at all since we are very conservative with our notifications and this is just trying to avoid a trivial merge conflict.

agree

**Comment by ChillerDragon** [comment]
I am open for ideas on how to have custom forks use own notification configuration without having to alter ddnet code.

**Comment by ChillerDragon** [comment]
@Learath2 pro coder shared a very handy snippet with me:

 ```C++
 ((IEngineGraphics *)Kernel()->RequestInterface<IEngineGraphics>())->WindowActive()
 ```
 
 Using that I could reimplement Notify() in my own class without altering ddnet code. So need to merge this pr and "cut through abstraction"
 
 :heart: @Learath2  :heart:

**Pull request closed without merging**
