### PR TITLE
Also check for divisibility by 16 of height (fixes #2687)

### LINKED ISSUE #2687: Official maps show the red texture warning
@Jupeyy is it supposed to show for graphics on official maps? Should we go through them and fix all?
screenshot-20200831@125808

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Jupeyy** [comment]
thx, can we also have this for:
https://github.com/ddnet/ddnet/blob/de328c1360b9d3e1495adccf3a929aa9e3b2844d/src/game/editor/popups.cpp#L1118
https://github.com/ddnet/ddnet/blob/76566b57fbc56606a37ceb3abcfec187e96244cd/src/game/editor/layer_tiles.cpp#L935

**Comment by def-** [comment]
Done.

**Comment by Jupeyy** [comment]
oh sry, didnt saw earlier, the title of the popup:
https://github.com/ddnet/ddnet/blob/de328c1360b9d3e1495adccf3a929aa9e3b2844d/src/game/editor/popups.cpp#L1095

**Comment by heinrich5991** [comment]
Thanks.

bors r+

**Pull request merged**
