### PR TITLE
Fix client crash/hang when launching without data directory

### LINKED ISSUE #4638: Headless client issues
Not sure if anyone cares. But here some known issues with the client when compiled with -DHEADLESS_CLIENT=ON

- [x]  "cl_download_skins 1" crashes the client
- [ ] no data/ dir crashes the client
- [x] no signals are catched ctrl+c keeps a timeouted client on the server (in gui version SDL catches that)

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #4638.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Why would we want to support having no data dir?

To me this is an essential part of the client and should be considered existing instead of allowing to be "null".

the headless client works with the data dir, doesn't it?

**Comment by Learath2** [comment]
Either way no harm in these changes. No need to invoke UB for a bad installation or broken `storage.cfg`.

**Review by def- — APPROVED** [review]
Seems cleaner to me

**Comment by Jupeyy** [comment]
> Either way no harm in these changes. No need to invoke UB for a bad installation or broken `storage.cfg`.

I'd say its the exact opposite: this will create UB, you add new code and ofc don't think about a file not existing in data (if it clearly does).
Better would be to fail early if the data directory does not exist

**Comment by Learath2** [comment]
Even if we do decide to fail early, I think we still shouldn't be invoking UB. Currently dereferencing `pFont` there would be UB without the null check.

**Comment by Jupeyy** [comment]
Complete disagree again. If the font file fails to load this is an absolute fatal error. without a font, no text, without text no error message

The user will see a "working" that is not working at all. It should show a big fat ass error popup saying that the client is broken to a point where its unusable

**Comment by Learath2** [comment]
I'm not saying we shouldn't kill there with an error. I'm saying we should fail in a sane way that doesn't involve dereferencing a null pointer.

**Comment by Jupeyy** [comment]
Ok, then I got u wrong maybe. But what I want to say is. We should make sure the font loaded. Then the ptr cannot be null anyway

**Comment by ChillerDragon** [comment]
> the headless client works with the data dir, doesn't it?

But would be nice if the headless client would also work without it.

Then you could launch just the headless bin on a system without any dependencies.

**Comment by Jupeyy** [comment]
Mh yeah but honestly headless client second.

But seems like most devs prefer this solution anyway..

**Comment by Robyt3** [comment]
I fixed another bug when no themes are found. Everything now seems to work as far as I can tell. Normal client also works with no data dir. The client seems to add a dummy skin as a placeholder when no other skin was loaded.

**Comment by ChillerDragon** [comment]
> Mh yeah but honestly headless client second.

Agree actually. The main/gui client should not bend it self to please the headless client.

If those missing graphics are so critical and you do not want the client to launch like that @Jupeyy what about throwing a informative error and exiting the client but only do so if its not compiled in headless mode.

**Comment by Jupeyy** [comment]
I don't know if this is so much better. It would/could still lead to weird behavior for a given use case. U might not need the UI code. The next person that uses it and thinks it works without data dir will then see it failing and add exceptions to the code. Then we have a fail error mode that is useless BCS the client can handle these errors anyway.

Anyway I made my position clear, rest is not my decision.

**Comment by edg-l** [comment]
this prevents dereferencing a possible null pointer and a bug with themes, so i think we should get it in, we can fix the other issues in another pr (making sure the font is always loaded, etc)

bors r+

**Pull request merged**
