### PR TITLE
Fix array as initializer g++ 4.9 error (fixes #2320)

### LINKED ISSUE #2320: src/game/server/teeinfo.cpp:32:91: error: array used as initializer
In the build for release:
```
/ddnet-master/src/game/server/teeinfo.cpp: In constructor ‘CTeeInfo::CTeeInfo(const char*, int, int, int)’:
/ddnet-master/src/game/server/teeinfo.cpp:32:91: error: array used as initializer
 CTeeInfo::CTeeInfo(const char *pSkinName, int UseCustomColor, int ColorBody, int ColorFeet)
                                                                                           ^   
/ddnet-master/src/game/server/teeinfo.cpp: In constructor ‘CTeeInfo::CTeeInfo(const char**, int*, int*)’:
/ddnet-master/src/game/server/teeinfo.cpp:40:94: error: array used as initializer
 CTeeInfo::CTeeInfo(const char *pSkinPartNames[6], int *pUseCustomColors, int *pSkinPartColors)
                                                                                              ^   
```

Probably because it's an old gcc version. @Learath2 Do you want to take a look? I could also do so later.

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by fokkonaut** [comment]
Doesnt this initialize the first entry with `'\0'` and the rest with `0`?

**Comment by def-** [comment]
Yeah, but that's fine, since it's all 0, right?

**Comment by Learath2** [comment]
Well as long as the first char is `\0' the rest doesn't even matter.

**Comment by heinrich5991** [comment]
@fokkonaut '\0' and 0 have the same value.

bors r+

Thanks.

**Pull request merged**
