### PR TITLE
Build our own drmingw with mingw

### PR DESCRIPTION
**Pull request by def-**
Get WinSDKDebuggingTools compatible with Windows 7:
https://www.microsoft.com/en-us/download/details.aspx?id=8279&ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-hqwNB0ABR6xeVqDZwkGZAw&epi=a1LgFw09t88-hqwNB0ABR6xeVqDZwkGZAw&irgwc=1&OCID=AID2200057_aff_7806_1243925&tduid=%28ir__qxvdeeyzhskf6zzy0axab6w3ye2xvkxn3xgwkihq00%29%287806%29%281243925%29%28a1LgFw09t88-hqwNB0ABR6xeVqDZwkGZAw%29%28%29&irclickid=_qxvdeeyzhskf6zzy0axab6w3ye2xvkxn3xgwkihq00

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Asked eeetadam to test if this works: https://ddnet.tw/downloads/DDNet-drmingw-win64.zip https://ddnet.tw/downloads/DDNet-drmingw-win32.zip

**Comment by Jupeyy** [comment]
guess this needs a rebase now?

**Comment by def-** [comment]
Done, I just reminded eeetadam to test the version.

**Comment by Jupeyy** [comment]
ok

/remind me 2 days

**Comment by Jupeyy** [comment]
oh doesnt work, too bad ^^

**Comment by def-** [comment]
He updated his Windows 7 and it started working, so no way to test if this would have done the trick. Oh well...

**Comment by Jupeyy** [comment]
OK, then lets get this in and see if nightly players report any bugs
bors r+

**Pull request merged**
