### PR TITLE
Improve selection popups and dropdown menus, add dropdown menus to select screen and active controller

### PR DESCRIPTION
**Pull request by Robyt3**
Screenshots:
- Controls settings:
   - Before: 
controls old
   - After: 
controls new
- Graphics settings (collapsed):
   - Before: 
graphics_collapsed old
   - After: 
graphics_collapsed new
- Graphics settings (expanded):
   - Before: 
graphics_expanded old
   - After: 
graphics_expanded_1 new
graphics_expanded_2 new
graphics_expanded_3 new
- The maximum dropdown menu height is limited to 40% of the screen height. The content will begin to scroll if this is exceeded:
scrolling
- If there is not enough space below the dropdown button to open the dropdown menu popup, then the popup opens to the top instead:
alignment

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I think it looks a bit too noisy to have the grey with dark around it, could we keep the options more transparent?
Screenshot 2023-06-08 at 15 54 37

**Comment by Robyt3** [comment]
So you think we should make the buttons more transparent and keep the dark background? Or change the dark background to reduce the contrast? Too much transparency doesn't look good because then you see too much of the UI elements below the popup.

Here are some possibilities:

- A:
A

- B:
B

- C:
C

**Comment by def-** [comment]
Maybe not have a separate box for each element?

**Comment by Robyt3** [comment]
More ideas:

- D (no background color for unselected buttons, default popup color):
D

- E (no background color for unselected buttons, popup color identical to the dropdown button, no popup border):
E

- F (no background color for unselected buttons, lighter popup background/border colors)
F

I like E because it fits nicely with the color of the dropdown button, but it's not very readable due to the transparency.

My favorite is currently F.

**Comment by def-** [comment]
F is fine, D would be ok too.

**Comment by Robyt3** [comment]
It's using option F now.

**Review by def- — APPROVED** [review]
bors r+

**Comment by Robyt3** [comment]
bors retry

**Pull request merged**
