### PR TITLE
Use C++17 (requires Debian 9 to build)

### PR DESCRIPTION
**Pull request by def-**
Ubuntu 18.04's cmake doesn't like C++20 (same with my Linux Debian build jobs):

> The CXX_STANDARD property on target "testrunner" contained an invalid
    value: "20".

Mac and Windows official builds have no problem with this.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
It's a bit weird that opengl files fail to compile with C++17:
```
 c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/DDNet.dir/build.make:585: CMakeFiles/DDNet.dir/src/engine/client/backend/opengl/opengl_sl.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/DDNet.dir/build.make:543: CMakeFiles/DDNet.dir/src/engine/client/backend/glsl_shader_compiler.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/DDNet.dir/build.make:795: CMakeFiles/DDNet.dir/src/engine/client/input.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/DDNet.dir/build.make:613: CMakeFiles/DDNet.dir/src/engine/client/backend/opengles/backend_opengles.cpp.o] Error 1
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [CMakeFiles/DDNet.dir/build.make:627: CMakeFiles/DDNet.dir/src/engine/client/backend/opengles/backend_opengles3.cpp.o] Error 1
```

**Comment by def-** [comment]
I have switched to Debian 9 and all official builds work with C++17.

**Comment by Jupeyy** [comment]
> It's a bit weird that opengl files fail to compile with C++17:
> 

Last time we had these fails, I switched the build system to ninja and it worked 
https://github.com/ddnet/ddnet/pull/4087/commits/55b6d27d362fddce900911b65b5f66ac7dfdaa62

**Comment by def-** [comment]
That's weird... Let's try it anyway.

**Comment by Jupeyy** [comment]
Really weird that it works, I think Heinrich once found out that the--parallel argument caused problem on cmake, but I thought this was a single cmake version

**Comment by def-** [comment]
Ok, works now. Debian 9 means we require glibc 2.24 now. Thus we lose support for these major distributions:
- Ubuntu 16.04 LTS, 16.10
- SUSE 12
- Debian 8 obviously

**Comment by edg-l** [comment]
I think it's fine to lose support for those platforms, we can just make a little announcement saying it won't be supported so if someone uses them they won't have surprises

**Pull request merged**
