### PR TITLE
Use 0.7 gameskin by @Zatline

### PR DESCRIPTION
**Pull request by ChillerDragon**
https://github.com/teeworlds/teeworlds/commit/a5105264ff9366c3bf5deb8aaa3aba7026640c46
https://github.com/teeworlds/teeworlds/commit/db0823950609859327ee96aea62271877d61d984
https://github.com/teeworlds/teeworlds/commit/31c6d2684d6a0f08a311fc5edd5c165b9efa1d4f

### CODE REVIEW

**Comment by def-** [comment]
looks good from my side. other opinions?

**Comment by ChillerDragon** [comment]
It also changes all 0.6 custom based gameskins since 0.7 uses new scaling. The ninja bar is still unused but lets not rush too much in at once.

**Comment by heinrich5991** [comment]
This breaks all old gameskins. Seems like we should at least provide a script or something to fix them before applying this change.

**Comment by heinrich5991** [comment]
Or wait, it doesn't? Coordinates look changed in code, but the image looks similar. Care to elaborate, @ChillerDragon? :)

**Comment by def-** [comment]
This should be done as part of #2928. I guess the changed coordinates are to support the loading bar.

**Comment by ChillerDragon** [comment]
Vanilla did not change any coordinates just scaling.

**New unscaled**
07_not_scaled

**New scaled**
07_scaled

**Old unscaled**
06_not_scaled

**Old scaled** (this is how old custom skins will look like)
06_scaled

I differed from vanilla tho and actually changed coordinates of the grenade ammo. I do not know why but vanilla does not scale grenade ammo and that causes a small offset in ddnet.

So instead of:
``Array[n] = IGraphics::CQuadItem(x + n * 12, y + 24, 10, 10);``
no_offset

I went with:
``Array[n] = IGraphics::CQuadItem(``**1 +**``x + n * 12, y + 24, 10, 10);``
offset

**Comment by def-** [comment]
Yep, yours looks better for ammo

**Comment by def-** [comment]
As I know this community, we'll probably need an option to get the old behaviour back. Otherwise this is fine for me. Maybe after #2928 is in switch the default to the 0.7 gameskin by @Zatline?

**Comment by Jupeyy** [comment]
If we'll use this don't forget to dilate it

**Comment by def-** [comment]
@ChillerDragon Could you please add the option for scaling and add this skin now that #2928 has been merged?

**Comment by heinrich5991** [comment]
I don't like options that the user has to configure. Can we instead detect a new gameskin by checking for non-transparent pixels in the ninja bar area?

**Comment by heinrich5991** [comment]
Also, if possible rewrite git history so that we only the dilated game.png in the repository.

**Comment by Jupeyy** [comment]
The HUD quad container should be deleted correctly, and also when recreating it should recreate everything like in `OnInit`
else the flags and cursors are missing, if you are unsure what i mean, i can also fix it

**Comment by Jupeyy** [comment]
independent of this commit, we should probably, resave the image, bcs currently it has transparent pixels as white, which causes the png consist of Byte patterns like:
R G B A
255 255 255 0

image

We could resave it with black transparent pixels, would save a few more bytes, independent of png optimizers

**Comment by ChillerDragon** [comment]
@Jupeyy you are the pro go make the improvements. You can also pr against my branch and I will merge.

**Comment by Jupeyy** [comment]
I will create a independent pr for the at runtime check if ninja bar exist, but that pr will take a bit of time,
after that we'll fix this pr to work with my pr(bcs my pr changes some things)

**Comment by Jupeyy** [comment]
@ChillerDragon are you ok when i force push force to ur branch, then i can also squash the commits

**Comment by def-** [comment]
You could also cherry-pick his commits into your own branch

**Comment by Jupeyy** [comment]
Yeah, just wanted to make sure he's ok with it, bcs he asked me to pr against his repo :D

**Comment by ChillerDragon** [comment]
Thanks for the rework @Jupeyy

As discussed on irc this pr is closed by https://github.com/ddnet/ddnet/pull/3045

**Pull request closed without merging**
