### PR TITLE
Ignore emoticon of spammy players (fixes #2387)

### LINKED ISSUE #2387: Add smth like to block emotes from player
Right now you can just disable all emotes, but maybe add smth to block one player emotes.. There are some annoying players who spam non stop emotes <.<

### PR DESCRIPTION
**Pull request by def-**
Controlled with the regular ignore chat button in players menu

### CODE REVIEW

**Comment by fokkonaut** [comment]
Against it, exactly when you muted someone you can sometimes only notice he wants something important because he emotes you.

**Comment by def-** [comment]
screenshot-20200627@011504

**Comment by fokkonaut** [comment]
Nice :)

**Comment by HiRavie** [comment]
I came up with this
gui_icons

**Comment by Ekidoxx** [comment]
| Image | Preview |
| :---: | :---:|
| gui_icons | image |

[gui_icons.zip](https://github.com/ddnet/ddnet/files/4840793/gui_icons.zip) (already dilated)

**Comment by def-** [comment]
@Ekidoxx  Yours are not centered properly for me.
screenshot-20200627@194636

**Comment by Ekidoxx** [comment]
@def- could you do win64 build so could play around with it?

**Comment by def-** [comment]
isn't this one working? https://github.com/ddnet/ddnet/suites/849194034/artifacts/9658766

**Comment by Ekidoxx** [comment]
| Author | Image | In-game preview |
| :---: | :---: | :---: |
| Barsik | gui_icons - Barsik | image |
| Ravie | gui_icons - Ravie | image |
| Soreu | gui_icons - Soreu | image |

[gui_icons.zip](https://github.com/ddnet/ddnet/files/4841151/gui_icons.zip) (already dilated)

**Comment by heinrich5991** [comment]
Needs resolution on which icon set we want.

**Comment by def-** [comment]
I'll start a vote on Discord (and hopefully not ignore the result)

**Comment by def-** [comment]
Looks like @HiRavie's option is winning the vote on Discord. Could you center the pictures with the latest build? https://github.com/ddnet/ddnet/suites/849478511/artifacts/9664570

**Comment by HiRavie** [comment]
Done, didn't need to touch the old two
gui_icons

**Pull request merged**
