### PR TITLE
Fix macOS build on Travis

### PR DESCRIPTION
**Pull request by H-M-H**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Dunno if we should work-around bugs from travis-ci or whether we should just wait until they fix it. https://github.com/ddnet/ddnet/pull/885#issuecomment-335266544, https://github.com/travis-ci/travis-ci/issues/8552

**Comment by Learath2** [comment]
Well `brew update` doesn't hurt

**Comment by heinrich5991** [comment]
From the [docs](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-OS-X):
>To speed up your build, try installing your packages without running `brew update` first, to see if the Homebrew database on the build image already has what you need.

**Comment by heinrich5991** [comment]
Thanks.

**Pull request merged**
