### PR TITLE
Fix `CFGFLAG_STORE` commands not getting stored when executed from reset file

### LINKED ISSUE #9024: `restart` in `reset.cfg` causes crash
```
Thread 1 "DDNet-Server" received signal SIGSEGV, Segmentation fault.
IGameController::GameServer (this=0x0) at /home/user/Development/ddnet-pr/src/game/server/gamecontroller.h:31
31              CGameContext *GameServer() const { return m_pGameServer; }
#0  IGameController::GameServer (this=0x0) at /home/user/Development/ddnet-pr/src/game/server/gamecontroller.h:31
#1  0x000000000037b555 in IGameController::ResetGame (this=0x0) at /home/user/Development/ddnet-pr/src/game/server/gamecontroller.cpp:453
#2  0x000000000037b5e2 in IGameController::StartRound (this=0x0) at /home/user/Development/ddnet-pr/src/game/server/gamecontroller.cpp:465
#3  0x0000000000363225 in CGameContext::ConRestart (pResult=0x7fffffff21d8, pUserData=0x7ffff55aa010)
    at /home/user/Development/ddnet-pr/src/game/server/gamecontext.cpp:3143
#4  0x00000000003e5dff in CConsole::ExecuteLineStroked (this=0x65c230, Stroke=1, pStr=0x68423c "restart", ClientId=-1, InterpretSemicolons=true)
    at /home/user/Development/ddnet-pr/src/engine/shared/console.cpp:557
#5  0x00000000003e615c in CConsole::ExecuteLine (this=0x65c230, pStr=0x68423c "restart", ClientId=-1, InterpretSemicolons=true)
    at /home/user/Development/ddnet-pr/src/engine/shared/console.cpp:624
#6  0x00000000003e63e2 in CConsole::ExecuteFile (this=0x65c230, pFilename=0x6190a4 <g_Config+12364> "reset.cfg", ClientId=-1, LogFailure=false, 
    StorageType=-1) at /home/user/Development/ddnet-pr/src/engine/shared/console.cpp:664
#7  0x000000000036872b in CGameContext::OnInit (this=0x7ffff55aa010, pPersistentData=0x684fd0)
    at /home/user/Development/ddnet-pr/src/game/server/gamecontext.cpp:3912
#8  0x000000000031c0a6 in CServer::Run (this=0x7ffff5600010) at /home/user/Development/ddnet-pr/src/engine/server/server.cpp:2858
#9  0x0000000000303c71 in main (argc=1, argv=0x7fffffffd688) at /home/user/Development/ddnet-pr/src/engine/server/main.cpp:198
```

To reproduce, add `restart` in your `reset.cfg` and then do a map change or reload.

### PR DESCRIPTION
**Pull request by dobrykafe**
Closes #9024

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by Robyt3 — COMMENTED** [review]
Not sure about this, it seems like moving this code could change the behavior. Now the constructor game controller constructor does not see the variable values loaded from the reset file and map settings.

**Comment by dobrykafe** [comment]
I don't know what was going through my head before but I think I have actual fix now. I'll update the PR later.

**Review by Robyt3 — CHANGES_REQUESTED** [review]
Seems good, please remove the commented out code and adjust the commit message like the PR title.

**Review by Robyt3 — APPROVED** [review]

**Comment by furo321** [comment]
Could this be merged?

**Review by def- — APPROVED** [review]

**Pull request merged**
