### PR TITLE
Implement /roll to get a random number

### PR DESCRIPTION
**Pull request by def-**
As requested by Aoe to decide who gets to do a part.

Other games support the same: https://wow.gamepedia.com/Roll

screenshot-20201121@114310

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Heh, crashes with /roll 2147483648 2147483647 because of modulo 0 calculation

**Comment by Patiga** [comment]
I want to question if this feature should actually be added.
1. there already are a lot of chat commands, also ones I probably don't know yet, just like config options (for example only recently I learned of `/specvoted`). I think the number of commands should be kept relatively low
2. `/roll` by itself isn't really related to ddnet
3. the problem of choosing a part can (and should imo) be solved in a different way. a random number generator is one of many ways and you can easily get random numbers elsewhere

while other games apparently have this feature, I don't really see why ddnet also needs it. I personally don't know of a new game that has this feature, or at least haven't yet encountered it in the games I do know.

**Comment by gerdoe-jr** [comment]
I'm agree with @Patiga, but it can be used in another way. Maybe, /team without any parameter will invite player to:
- existing unlocked team
- unselected team
/roll is the part of it, if your team number is engaged, you are rolling number between 1-64 and here you go.

**Comment by def-** [comment]
That doesn't work when people are racing. For the original motivation for this see https://youtu.be/E_ID1TYUTTc?t=6013

**Comment by heinrich5991** [comment]
Hm, I don't find the motivation convincing.

**Comment by l-ouis** [comment]
it would be a cool command, pretty harmless.

i'd use this in a context like "if i roll above 50 I'll solo this faily part"

if implemented, it should just be /roll to roll a number from 1-100, parameters aren't really needed. it might be too late tho since its already closed

**Comment by def-** [comment]
Yes, that's how it works, 1-100 is the default range. I expected not to get this change in.

**Comment by dropalways** [comment]
can this be reopened and merged 🙏

**Pull request closed without merging**
