### PR TITLE
Try to get map background working (WIP)

### PR DESCRIPTION
**Pull request by def-**
Missing:
- Regular maps stopped working, see screenshot
- Animations (maybe just have to somehow make them run while no game time is available)
- winter map not loading (maybe some 0.7 specific thing we don't support, could just remove it)

Anyone want to try to fix this? I'm a bit tired of merging our changes with the 0.7 changes without breaking anything.
screenshot-20200904@113451

### CODE REVIEW

**Comment by fokkonaut** [comment]
Also need to make sure entities and kill tile border in entities arent rendered in the menu. I fixed this in F-Client by checking for State == ONLINE || DEMOPLAYBACK, then entities are allowed, otherwise not

**Comment by fokkonaut** [comment]
Quads in menus also need to be Force rendered at 100 alpha.

**Comment by def-** [comment]
@fokkonaut  Oh, if you have this for F-Client already, could you just port this to DDNet please?

**Comment by heinrich5991** [comment]
What's the reason for forcing quads to 100 alpha?

**Comment by fokkonaut** [comment]
@heinrich5991 to have the quads in the menu background? players may play without quads, but the menu background is not a map to play, instead a background. Same for editior, we force the quads in editor to 100 alpha already.

@deen F-Client is 0.7 based, I merged entities in it, not the other way round.

**Comment by def-** [comment]
Superseded by https://github.com/ddnet/ddnet/pull/2863

**Pull request closed without merging**
