### PR TITLE
Add mysql to github workflow in ubuntu 20.04

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
The MySQL tests succeeded in the latest push, even if Github removed them (maybe I pushed too many times)

**Comment by heinrich5991** [comment]
Why is this tested on Ubuntu 20.04 rather than 22.04?

**Comment by def-** [comment]
Because 22.04 already tests with MariaDB ;) I'll resolve the conflicts.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
