### PR TITLE
Version 11.4.5

### PR DESCRIPTION
**Pull request by def-**
Anything you guys still want in or ready for release?

### CODE REVIEW

**Comment by Ryozuki** [comment]
This https://github.com/ddnet/ddnet/issues/1362 would be cool to be fixed asap, as it's really annoying :/

**Comment by fokkonaut** [comment]
would want #1347

**Comment by Learath2** [comment]
I'll do #1362 tonight. Release tomorrow?

**Comment by def-** [comment]
ok.

**Pull request merged**
