### PR TITLE
Change default from borderless to fullscreen

### PR DESCRIPTION
**Pull request by def-**
Switching the default means everyone with borderless window will be
switched to fullscreen. Fullscreen has lower latency and better
performance.

As suggested by Shyzo and voted on on Discord.

### CODE REVIEW

**Comment by BannZay** [comment]
> Switching the default means everyone with borderless window will be
> switched to fullscreen.

Does it affects already configured clients ? 

I am not fun of any affects on configured settings.

Fullscreen has some limitations to me.
1. Any windows notification makes game very laggy untill it overlaps the game
2. Not possible to debug on windows in fullscreen

**Comment by def-** [comment]
> Does it affects already configured clients ?

Yes, but you can change it once and then it won't change again.

**Comment by BannZay** [comment]
Not sure if I should post such thing here, but I truly hate when any app patches my configurations. Back in days I completely abandon apex legends because of this thing. 

Probably we should consider some kind of soft mechanism for such updates with ability to make decision by user for future

**Comment by def-** [comment]
We had the opposite problem previously, where we had no chance to change still defaulted config values after a release.

**Comment by Learath2** [comment]
How does this affect already configured clients? I only see a change to the defaults

**Comment by def-** [comment]
I recently changed it so that when your value is equal to the default, it is not set in settings_ddnet.cfg. So it will be reset to the default if you had borderless set.

**Comment by Learath2** [comment]
Hm, I missed that change completely. Can we explicitly set it to the default?

**Comment by def-** [comment]
I don't understand.

**Comment by Learath2** [comment]
Currently if I set a setting to the default, it'll just change however we change the defaults. There is no way to get it to be "set" to the value I want.

**Comment by def-** [comment]
Nope, no way at the moment. I preferred this over the old way because it was always annoying to change very wrong defaults and still having most players stay on the old default.

**Comment by Learath2** [comment]
I think this LGTM, the config issue we can talk about later, this is indeed better than the old state.

bors r+

**Pull request merged**
