### PR TITLE
Fix: background colors being set to white

### PR DESCRIPTION
**Pull request by Aerll**
After changing either of background colors in ddnet tab in settings and reopening the client, both become white.

### CODE REVIEW

**Comment by def-** [comment]
> After changing either of background colors in ddnet tab in settings and reopening the client, both become white.

Tried to reproduce but couldn't. Weird.

**Comment by Aerll** [comment]
Now that's weird. I always end up with some ridiculous color values.
console
#1804 caused this.

**Comment by Aerll** [comment]
I just tested it on official ddnet client and it indeed works just fine. I used client compiled in vs and for whatever reason, it has this issue.

**Comment by def-** [comment]
Ah, that's interesting. @Learath2 Sounds like you're using some UB

**Comment by Learath2** [comment]
Sounds, off.
@Aerll couple questions:
- Does this reproducibly happen?
- Does this only happen if you manipulate the colour through the menu?
- Does changing the colour actually work and it only breaks on restart?
- If so can you check what the value is being set to in the client (through the console) and what ends up getting saved.

**Comment by Aerll** [comment]
@Learath2 I did some more digging. For both clients color value gets changed as soon as you open ddnet tab in settings, and this value gets saved in the config. The difference occurs when I open the client. My client always yields 16777215 (white), official client reads the value properly.

**Comment by Learath2** [comment]
I have a feeling it"s a ui id reuse again. I'll take a look tonight

**Comment by Learath2** [comment]
Eh, I really don't see it and it's pretty hard to find when I can't reproduce it. You can try taking a look  at the ids used for the sliders or try to follow the values back. I'll try installing a windows vm in the meanwhile, hoping at least visual studio always reproduces it :)

**Comment by Aerll** [comment]
> The difference occurs when I open the client. 
By that I meant that I don't need to interact with anything, value is incorrect from the beginning. I'll try to find it today.

**Comment by Aerll** [comment]
@Learath2 turned out to be UB.

**Comment by def-** [comment]
can you explain further?

**Comment by Aerll** [comment]
@def- in short, str_toint is called with unsigned value, that's ub

**Comment by Learath2** [comment]
`str_toint` uses `atoi`, which indeed specifies that the behaviour is undefined if the value is out of the range of an int and in the case of a color with alpha, that'd be the case but I don't remember the background colors having alpha

**Comment by Aerll** [comment]
I changed it in the first commit, Pack() includes alpha by default, I guess you just overlooked these 2 calls.

**Pull request merged**
