### PR TITLE
Remove confusing cl_mouse_followfactor

### PR DESCRIPTION
**Pull request by def-**
Since we have dyncam already. As suggested by n000b on Discord

### CODE REVIEW

**Comment by heinrich5991** [comment]
Note: This will break existing, old dyncam configurations.

**Comment by Learath2** [comment]
Not if cl_dyncam is set, no?

**Comment by heinrich5991** [comment]
Yes, but old dyncam configurations don't have that set.

**Comment by def-** [comment]
Quoting teini94 on Discord:
> uff
> some people useing dyn settings in static setup and binds for that also like that famous straight shoot up bind
> I mean I guess u have to change ur binds settings etc then but could make a lot of problems for a lot of people
> many people may wont know how to deal with this new setting out of nowhere and maybe will be confused

**Comment by heinrich5991** [comment]
I think that's enough reason not to do this change. We could display a checkbox or a warning if the dyncam setting doesn't match cl_mouse_followfactor.

**Pull request closed without merging**
