### PR TITLE
Add `IJob::Done` callback called on main thread

### PR DESCRIPTION
**Pull request by Robyt3**
We currently poll if specific background jobs are done in various places to perform some final computations on the main thread.

To simplify job handling the virtual function `IJob::Done` is added to perform these final computations. This function will be called automatically on the main thread by the job pool, for all jobs that have finished their `Run` function. Hence, polling the current state of jobs is not necessary anymore for most use-cases.

The `CJobPool::Update` function is added, which must be called on the main thread periodically to call the `Done` callback for all finished jobs, which are stored in a separate queue.

For the generic `CHostLookup` and `CHttpRequest` jobs the `Done` function can be set to a lambda function, so overriding these classes is not necessary just to specify a custom `Done` function.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [X] Written a unit test (especially base/) or added coverage to integration test
- [X] Considered possible null pointers and out of bounds array indexing
- [X] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
What's the idea wrt. cleanup? The closures passed to `IJob::Done` must make sure to only pass data that will live longer than the job pool?

**Comment by Robyt3** [comment]
Yeah, each job, its input/output data and everything used in the `Done` function has to live until either the respective job is destroyed or the entire job pool is destroyed.

I wanted to make this a refactoring PR only, but I also want to make the following changes in the future:

1. Ensure each job that has been queued is executed before the job pool is destroyed. The reason for this is that there are important jobs that have to be run before the client quits or data could be lost (e.g. saving the editor map). Currently, each worker thread will only finish up to one job before terminating.
2. Ensure the `Done` function is called for each executed job before the job pool is destroyed.

**Comment by heinrich5991** [comment]
> 1. Ensure each job that has been queued is executed before the job pool is destroyed. The reason for this is that there are important jobs that have to be run before the client quits or data could be lost (e.g. saving the editor map).

This doesn't seem to make sense to me. Many jobs will unnecessarily delay the quitting, e.g. DNS lookups or HTTPS requests that are just requesting information. It seems more useful to me that jobs can specify whether they should delay the quitting or not.

**Comment by heinrich5991** [comment]
> Yeah, each job, its input/output data and everything used in the `Done` function has to live until either the respective job is destroyed or the entire job pool is destroyed.

So currently, the job pool is destroyed in the engine destructor. I find it non-obvious how to check that each job actually only accesses data that is still alive when the engine class instance is dropped. Can we somehow improve it so that it's more obvious that no `Done()` function accesses anything bad?

**Comment by Robyt3** [comment]
> So currently, the job pool is destroyed in the engine destructor. I find it non-obvious how to check that each job actually only accesses data that is still alive when the engine class instance is dropped. Can we somehow improve it so that it's more obvious that no `Done()` function accesses anything bad?

Here is my proposed solution. Add `EJobState::STATE_CANCELLED`. Add function `IJob::Cancel` which changes a job's state to `STATE_CANCELLED`, unless the job is already in `STATE_DONE`. Prevent job from changing state if it's already in `STATE_CANCELLED`. Do not call `IJob::Done` function for completed jobs if they are in `STATE_CANCELLED`. Where necessary, add separate `free` operations in job destructors, to prevent memory leaks when jobs are cancelled, as memory was previously freed in the `Done` function. Cancel individual jobs when the components being used in the `Done` function are destroyed, to prevent accesses to dead memory. One issue with this is that it requires manually adding the correct job cancellations everywhere to prevent those bad accesses.

**Comment by heinrich5991** [comment]
Could we maybe not call the `Done` function if we're shutting down? Perhaps we could add a function to the engine that says something like `FinishActiveJobs`. We call that on regular shutdown. On irregular shutdown, the destructor takes care of deallocating the resources used.

**Comment by Robyt3** [comment]
Outdated, will eventually rework it.

**Pull request closed without merging**
