### PR TITLE
Set constant and uniform names for the server and client CMake targets

### PR DESCRIPTION
**Pull request by Kaffeine**
This MR set the server and client CMake target names to `game-server` and `game-client` which are uniform with other targets such as `engine-gfx`, `engine-shared`, and `game-shared`.

Set uniform names for the targets to:
1. Avoid long rebuilds on the target _executable_ name changed
2. Provide the same name for different executables and/or different setup (use-cases are `cmake --build . --target game-server` and various CMake target lookups in IDEs)

Those changes are necessary but not enough to allow CI for custom app name on all platforms.

Personally this 'll allow me switch to between DDNet and Infclass branches faster and without breaking the targets configuration (e.g. with that patchset I can have `game-client` as an active target in both branches), and also reduces the conflicts in `CMakeLists.txt`.
Easier to switch between the forks => easier to contribute.

### CODE REVIEW

**Comment by def-** [comment]
Does this mean I can't run `ninja DDNet-Server` anymore to build just the server? I think the target having the same name as the executable it produces is nice to have.

**Comment by Kaffeine** [comment]
> Does this mean I can't run `ninja DDNet-Server` anymore to build just the server? I think the target having the same name as the executable it produces is nice to have.

That is correct. Hm OK, if that is the wanted behavior then I can add a line to make it work.

I thought that if anyone ever used the target then they would quickly come to the idea to make it look like a typical CMake target rather than virtually an app display name.
I thought you only build `all` target.

IIUC for you it is convenient to build the server with `ninja DDNet-Server` but one can't make a universal script for that. `ninja DDNet-Server` for DDNet, `ninja FNG-Server` for fng, `ninja KoG-Server` for KoG, etc. If you'd ever use `SERVER_EXECUTABLE` option then you'll also hit that issue with something like `ninja DDNet-Server-Test`, etc.
It also breaks the targets configuration in IDE.
Executable name is just that (the executable name), why would its change break everything?
Having one `ninja game-server` seems to be a better option.

In the same way, if a dev want to open `game-shared` target, they use that name in the locator. E.g. in Qt Creator's locator it would be `cmo game-shared` (standing for "CMake Open game-shared")

**Comment by Kaffeine** [comment]
Ohmm, hmm. Extra targets are not needed. Ninja is smart enough to figure out that you want to get that file and it builds the right target automatically.

IOW, `ninja DDNet-Server` still works (as long as it the name of the executable).

**Comment by heinrich5991** [comment]
LGTM. Anyone wanna do name bikesheding? Perhaps "client" and "server" instead of "game-server" and "game-client"? Just suggestions, no need to implement for now.

**Comment by Jupeyy** [comment]
i dunno, maybe something more explicit: "client-bin", "server-bin"

**Comment by Kaffeine** [comment]
> cant do `make DDNet` anymore

Try `make game-client`. It seems that ninja is smarter than make.

> And TAB completion is insanely slow

There can't be any slowdown compared to the previous CMake code.

**Comment by Kaffeine** [comment]
> cant do `make DDNet` anymore
Or hm, maybe `make DDNet.exe` will work? Maybe `make` is capable for file <-> target matching.

**Comment by Jupeyy** [comment]
> 
> > And TAB completion is insanely slow
> 
> There can't be any slowdown compared to the previous CMake code.

Yeah I guess this was always the case, if you type in a non-target. I just now noticed it since there was not matching target :D

**Comment by Kaffeine** [comment]
I'll add the extra targets then. I've suggested it at first but then it seems to be unneeded.

**Comment by ChillerDragon** [comment]
I guess I am a bit late to the party but I only was made aware of the change during my merge conflict :D

I just wanted to say thanks @Kaffeine for working on this. We downstream maintainers appreciate every removal of the hardcodet string "ddnet" from the CMakeLists.txt makes updating forks and forks of forks with custom rebrands so much easier!

:heart:

**Pull request merged**
