### PR TITLE
keep input if chat is closed

### LINKED ISSUE #4653: Leaving chat stops directional keys from being held
From [Discord](https://discord.com/channels/252358080522747904/757720336274948198/938551323635376158):

> [10:47 PM] Moyoi: Bug or feature? But anyway annoying 
>
> https://user-images.githubusercontent.com/366230/152337298-fae5b59b-f3bc-42e2-9944-ef290b1666bc.mp4
> 
> [10:58 PM] MaCRoYale: what did you press?
> [11:16 PM] Skeith: If you're holding a directional while typing, then you press enter, it'll stop holding

### PR DESCRIPTION
**Pull request by C0D3D3V**
fixes #4653

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [?] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by C0D3D3V** [comment]
I have no Idea what m_BugDDRaceInput should do, but the same condition is basically in line 284 again, so without this change m_BugDDRaceInput always resets the inputs.

**Comment by heinrich5991** [comment]
I have a feeling this is not the correct fix. The original commit that introduced it was this: 8b5ee98193ea005523d48a0ea68246e9fb90e2e9.

**Comment by C0D3D3V** [comment]
was probably wrong already 5 years ago

**Comment by C0D3D3V** [comment]
and removing the reset server side does not help, only this change made the diffrence

**Comment by heinrich5991** [comment]
Does it work before that change? Because if so, the correct thing to do might just be to revert the above mentioned commit.

**Comment by heinrich5991** [comment]
Also #5032 claims to do the same but only touches the server side, AFAICT.

**Comment by C0D3D3V** [comment]
> Does it work before that change?
Nope, 10.1.1 is way older
I tested #5032 it does not fix it

**Comment by C0D3D3V** [comment]
I think he is talking about the inputs while chatting, not after closing the chat

**Comment by C0D3D3V** [comment]
no m_BugDDRaceInput is true if it is ddnet, so it is not executed on ddnet server. If this should emulate teeworlds chat rules, than its also not completely correct, because in teeworlds 0.7 inputs already stop on chat enter.

**Comment by C0D3D3V** [comment]
removing the reset completely would also work, but than on other mod server you would also hold the inputs.

**Comment by C0D3D3V** [comment]
I just tested it on vanilla servers xD there the reset is forced already on chat entering by the server, so the condition is wrong anyway (if it should emulate the 0.7 behaviour)

**Comment by C0D3D3V** [comment]
Actually I thought teeworlds also keeps input while chatting because of this: https://github.com/teeworlds/teeworlds/issues/719 
but probably it got patched out :?

**Comment by C0D3D3V** [comment]
The correct fix is probably to emulate the teeworlds chat behaviour correctly if the flag is not set.

**Comment by C0D3D3V** [comment]
I also removed the drop of inputs on server side

we probably should rename m_BugDDRaceInput to something more meaningful. 
The behaviour is as follow: 
- if true: do not reset inputs if chat or menu is open
- if false: stop sending inputs in chat or menu
 
 but I still do not undestand what happens here https://github.com/C0D3D3V/ddnet/blob/b0a73025f7672dcd48f26de84ec86f697fa8b427/src/game/client/components/controls.cpp#L118-L147
 ...

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
