### PR TITLE
Eliminate static libcurl dependency, second try

### PR DESCRIPTION
**Pull request by heinrich5991**
Last try was #1925.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Fun, I just found a more complicated way to achieve the same: https://blog.gibson.sh/2017/11/26/creating-portable-linux-binaries/#building-a-portable-libcurl-so-4-without-versioned-symbols.

**Comment by def-** [comment]
Does this mean that we now need to ship shared libs for curl on Linux or just use the system ones? Might have to update my script for building the libs.

**Comment by heinrich5991** [comment]
This would mean that we just use the system libs on Linux. The stub library exists solely so that the executable will link to all libcurls on the different distributions, regardless of which SSL library they were compiled against (since we don't rely on any specific one).

**Comment by def-** [comment]
Alright, let's give it a try then. Sorry for the conflicts, can you resolve them?

**Comment by heinrich5991** [comment]
Updated.

**Comment by def-** [comment]
bors r+
Let's give it a try.

**Comment by def-** [comment]
Do we need to update ddnet-libs first or what's the problem?

**Comment by heinrich5991** [comment]
Yep.

**Comment by heinrich5991** [comment]
bors r=def-

**Pull request merged**
