### PR TITLE
Rework HTTP to use curl-multi interface

### PR DESCRIPTION
**Pull request by Learath2**
This PR tries to rework the http interface to utilize the curl-multi interface. In the process we lost the `IJob` interface.

I experimented with getting rid of the `std::unordered_map` using `CURLOPT_PRIVATE` [here](https://github.com/Learath2/ddnet/commit/9770f1d39510036e7bbbec2c0607113282539a3c). I don't really like the end result, it might look a little better with `boost::intrusive::list` if we want boost or maybe if I tread the list through `CHttpRequest` itself.

Remaining concerns:
- How should errors be handled within `CHttp::Run`
- Changes within `serverbrowser_http` I'm a bit unsure about
- Need to add TSan. Couldn't figure out how to get it to work with `std::mutex`

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
@heinrich5991 `curl_multi_poll` pulls our curl requirement up to 7.66.0. If this is too undesirable I could implement `curl_multi_poll` in terms of `curl_multi_wait`.

**Comment by heinrich5991** [comment]
The only extra functionality of `curl_multi_poll` over `curl_multi_wait` is its interruptability, right? Do we use that? If not, it should be doable to rewrite it in terms of `curl_multi_wait`, I'd certainly prefer that.

Should I do it?

**Comment by Learath2** [comment]
> The only extra functionality of `curl_multi_poll` over `curl_multi_wait` is its interruptability, right? Do we use that? If not, it should be doable to rewrite it in terms of `curl_multi_wait`, I'd certainly prefer that.
> 
> Should I do it?

I use the interruptability indeed. 2 differences in `curl_multi_wait` one is that it'll return immediately if there is nothing to wait for (e.g. no easy handles in the multi handle) and second is that `curl_multi_wakeup` won't work on it.

We could do what curl internally does and just create a `socketpair()` insert it into the extrafds argument of `curl_multi_wait`, and write on the pair to wakeup. Issue with this is that we have to emulate `socketpair()` on windows (we could take it from libcurl source).

Or I could try to stop using the intteruptability and have a CV of my own to wait on. This could make sense since there is no need for us to `curl_multi_wait` if there are no handles.

Now that I wrote this out the second option sounds more viable, I think I'll go for that if you have no objections, it also avoids the fact that `curl_multi_poll` can't be made to block forever like a CV.

**Comment by heinrich5991** [comment]
Status: Needs rebase, and a bird told me that @Learath2 is reworking it anyway, right now.

**Pull request closed without merging**
