### PR TITLE
Add a groundjump-only tile

### PR DESCRIPTION
**Pull request by heinrich5991**
Implements a new mode of jumping: "you only have ground jump".  This differs from "you only have one jump" in that it doesn't allow you to air-jump, even if you haven't jumped to get off the ground. To access this mode, it reuses the "air-jump tile" in the switch layer with the number of jumps set to 255.

This tile is planned to be used in tutorial developed by unique2 and Alisa.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
This still has a prediction problem, I don't really know how to debug it though. :(

If you jump while you have -1 jumps, the client predicts that you don't jump and only gets the information from the server later. I don't see the code path that leads to this.

**Comment by heinrich5991** [comment]
Ah, and I need to think about interactions with walljump tiles etc.

**Comment by Chairn** [comment]
If it's only gonna be used for tutorial, maybe it's not that much of a problem?

**Comment by corneum** [comment]
cant you just tune air_jump_impulse 0?

**Comment by fokkonaut** [comment]
I am against using delay for such hidden features which are not even connected to it.

**Comment by def-** [comment]
> This still has a prediction problem, I don't really know how to debug it though. :(
> 
> If you jump while you have -1 jumps, the client predicts that you don't jump and only gets the information from the server later. I don't see the code path that leads to this.

@trml any idea?

**Comment by heinrich5991** [comment]
> If it's only gonna be used for tutorial, maybe it's not that much of a problem?

The prediction problem is especially bad for a tutorial, gives a bad first impression to new players.

> cant you just tune air_jump_impulse 0?

This would still show the airjump particles, right? This would be confusing, you get aa airjump animation but not an airjump. It might also set your vertical speed to 0?

> I am against using delay for such hidden features which are not even connected to it.

The delay is already used for the number of jumps. Are you against using a special value of 255 for "no airjump"?

**Comment by fokkonaut** [comment]
> Are you against using a special value of 255 for "no airjump"?

Yes

> This would still show the airjump particles, right?
>  It might also set your vertical speed to 0?

No

**Comment by heinrich5991** [comment]
> > This would still show the airjump particles, right?
> > It might also set your vertical speed to 0?
> 
> No

I just tried that on a server on "Sunny Side Up". I entered `tune air_jump_impulse 0` and then tried airjumping. It set my vertical speed to 0 (i.e. stopped my vertical movement) and showed airjump particles.

How can I get the behavior you describe?

**Comment by heinrich5991** [comment]
> I am against using delay for such hidden features which are not even connected to it.

What do you mean with "not connected to it"? The delay specifies the number of jumps you get, normally. A delay of 3 gives you 3 jumps, a delay of 0 removes all your jumps.

**Comment by fokkonaut** [comment]
> > I am against using delay for such hidden features which are not even connected to it.
> 
> What do you mean with "not connected to it"? The delay specifies the number of jumps you get, normally. A delay of 3 gives you 3 jumps, a delay of 0 removes all your jumps.

Delay 255 = 255 jumps, not only ground jump, thats what i mean.

**Comment by heinrich5991** [comment]
You'd like to have a new tile?

I kinda considered this to be the "fixed" version of "1 jump", but we obviously can't replace it because there surely is a map out there that uses "1 jump".

**Comment by fokkonaut** [comment]
Whats the issue in using air jump impulse 0 or mapping 1 and 0 jump tiles around and on a platform, like a "normal" mapper would do too? There are definitely ways to achieve this without a new tile, which gets added in a "weird" way (what i said, delay 255 for a feature that is not really fitting into that position)

**Comment by heinrich5991** [comment]
> Whats the issue in using air jump impulse 0

Mentioned above: Airjump indicator and the airjump still working by setting the tee's vertical speed to 0.

> mapping 1 and 0 jump tiles around and on a platform, like a "normal" mapper would do too?

Lots of chat messages and generally weird behavior around feet color, something that shouldn't appear in a tutorial.

> There are definitely ways to achieve this without a new tile, which gets added in a "weird" way (what i said, delay 255 for a feature that is not really fitting into that position)

If you find a way to do it without any weirdness and new tiles, I'm all ears. I couldn't find such a way that didn't involve weirdness in one way or another that would not fit into a tutorial.

In case we find that we need to introduce new behavior, what would your preferred way be? New tile? Using a magic number of the existing jump-tile?

**Comment by corneum** [comment]
i found a fix that might work:  place 0 jump tile with switch. put stopper tiles ID:62 (front layer) into every solid block. the stoppers will give the tee a jump anyway but only when you touch the grund. once you leave it you loose it. 
its not perfect tho because you cant jump on edges and sometimes the feet are tilted even tho youre on the ground because stopper tiles are bigger than un/hook. also there is still a delay.

**Comment by fokkonaut** [comment]
What do you need ground jump only even for, it its not part of any ddrace map? Shouldnt the player be introduced into normal physics instantly?

**Comment by heinrich5991** [comment]
> What do you need ground jump only even for, it its not part of any ddrace map? Shouldnt the player be introduced into normal physics instantly?

To introduce the player to airjump mechanics. The tutorial has a short first part without airjump.

**Comment by fokkonaut** [comment]
> > What do you need ground jump only even for, it its not part of any ddrace map? Shouldnt the player be introduced into normal physics instantly?
> 
> To introduce the player to airjump mechanics. The tutorial has a short first part without airjump.

Why would they need to be stopped from airjumping completely?

**Comment by trml** [comment]
> This still has a prediction problem, I don't really know how to debug it though. :(
> 
> If you jump while you have -1 jumps, the client predicts that you don't jump and only gets the information from the server later. I don't see the code path that leads to this.

The problem seems to be in network.py, the number of jumps is clamped to 0 with `NetIntRange("m_Jumps", 0, 255)` in DDNetCharacter, which is used for prediction. So maybe that should be changed to `NetIntRange("m_Jumps", -1, 254)`, or perhaps even to a signed char with `NetIntRange("m_Jumps", -127, 128)`.

It seemed to work when I tested it, so I guess that it doesn't change anything for the extended object uuids?

For some reason the jump tiles don't seem to predict properly (in the short time between touching one and getting the updated number of jumps in the snapshot), but that seems unrelated to this pr.

**Comment by heinrich5991** [comment]
> Why would they need to be stopped from airjumping completely?

Answer from Alisa:

The testers we had so far had a lot of trouble understanding the airjump mechanic: "Why can I sometimes jump in the air and sometimes not?". They expect being able to airjump twice if they got off the floor without jumping, they expect the airjump to reset when hooking the wall or shooting a rocket, they don't really differentiate between a jump and an airjump in their thinking... at least the first 4 or 5 testers still felt confused about how the jump mechanic works after completing the tutorial. It is something we didn't expect, but that is how it turned out. We gradually added more and more explanations regarding the airjump, but people not differentiating between an airjump and a groundjump in their thinking made those rather ineffective. 

Our current approach to address this is to have a short first part without an airjump, then reaching a point where an airjump is needed to proceed, and can be obtained by walking through airjump particles, making the player perceive the airjump as an extra ability. This accomplishes 2 things: Making the player think of their groundjump and their airjump as two distinct things, and making them associate the airjump to the airjump particles, so that it is easier for us to give explanations involving the airjump later.

**Comment by heinrich5991** [comment]
> It seemed to work when I tested it, so I guess that it doesn't change anything for the extended object uuids?

Yes, the UUID is generated solely from the string `character@netobj.ddnet.tw` passed to `NetObjectEx`.

**Comment by fokkonaut** [comment]
In my opinion it doesnt make sense. If you dont understand it even with multiple explanations and detailed ones, they didnt read it well enough.

I think a solid explanation, saying exactly that you can jump off the ground once and in the air once, no matter whether you didnt jump off the ground before or that you dont have your two jumps are only possible if one was off the ground, then it is fine.

**Comment by def-** [comment]
Based on the code I believe there is no new tile anymore but you are special casing the 255 jump tile? lgtm

**Comment by heinrich5991** [comment]
> Based on the code I believe there is no new tile anymore but you are special casing the 255 jump tile?

This is correct.

**Comment by def-** [comment]
ok, good then, I didn't read the original diff. Let's get this into 15.9 for prediction?
bors r+

**Comment by heinrich5991** [comment]
Sounds amazing, thank you!

**Pull request merged**
