### PR TITLE
Prevent placing unused tiles in the editor

### PR DESCRIPTION
**Pull request by timakro**
Prevent placing unused tiles in the editor, can be turned off with a new switch in the editor

### CODE REVIEW

**Comment by def-** [comment]
The purpose is that you don't add tiles by accident which might have an unintentional meaning later, right? So you couldn't use DDNet editor for mapping for other modifications as long as the switch is on, right?

**Comment by timakro** [comment]
Exactly.

**Comment by def-** [comment]
Hmm, that might be a problem. I believe some other communities also use DDNet client for mapping, just with their custom entities.png. How would they find out about this switch being introduced?

**Comment by timakro** [comment]
I don't have any ideas how to warn mappers who use these tiles in the editor. Maybe a warning in the news section could do the job.

**Pull request merged**
