### PR TITLE
Add missing translations

### PR DESCRIPTION
**Pull request by MilkeeyCat**
If I understood correctly, #8499 added a new translation but didn't add in translation files, so I ran `./scripts/languages/update_all.py` and it updated these files.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by MilkeeyCat** [comment]
Also there's something wrong with `belarusian` and `polish` translation files. if you run the `update_all.py` script 5 times it wont change any file except these 2. It just removes translation for graphics error related translations.

**Comment by def-** [comment]
I usually run this before the release

**Comment by MilkeeyCat** [comment]
So if i want to add a new translation I can just use it in code, and don't touch the translation files?

**Comment by def-** [comment]
Yes, but the issue about not updating all files is annyoing

**Comment by MilkeeyCat** [comment]
> Also there's something wrong with `belarusian` and `polish` translation files. if you run the `update_all.py` script 5 times it wont change any file except these 2. It just removes translation for graphics error related translations.

The reason why it worked weird is because these 2 files miss context line and because of this python script was breaking everything xd.

**Pull request closed without merging**
