### PR TITLE
Missing parameter in error list

### PR DESCRIPTION
**Pull request by Jupeyy**
Never lucky

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
image

normally it shows the error like this

**Comment by def-** [comment]
Should this go out as 16.7.1?

**Comment by Jupeyy** [comment]
its not high prio, if we have some translation updates its fine tho

**Pull request merged**
