### PR TITLE
Fix hook collision

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by heinrich5991** [comment]
The change in question was
```diff
 	// draw gun
 	{
-		CServerInfo Info;
-		Client()->GetServerInfo(&Info);
-		if(ClientID >= 0 && (((IsDDRace(&Info) || IsDDNet(&Info)) && g_Config.m_ClShowHookCollAlways) || (Player.m_PlayerFlags&PLAYERFLAG_AIM && ((!Local && g_Config.m_ClShowHookCollOther) || (Local && g_Config.m_ClShowHookCollOwn)))))
+		if(ClientID >= 0 && ((GameClient()->m_GameInfo.m_AllowHookColl && g_Config.m_ClShowHookCollAlways) || (Player.m_PlayerFlags&PLAYERFLAG_AIM && ((!Local && g_Config.m_ClShowHookCollOther) || (Local && g_Config.m_ClShowHookCollOwn)))))
 		{
 			vec2 ExDirection = Direction;
```
or more succinctly `((IsDDRace(&Info) || IsDDNet(&Info)) && g_Config.m_ClShowHookCollAlways)` to `(GameClient()->m_GameInfo.m_AllowHookColl && g_Config.m_ClShowHookCollAlways)`. It doesn't change behavior as far as I can see.

Looking at your diff, I think your PR *does* change behavior, so it's something else than a follow-up fix. E.g. from the code, it seems like you now disallow hookline on vanilla servers where it was not disallowed before.

**Comment by fokkonaut** [comment]
yea, true. but like you implemented it was wrong aswell. because yours did only disallow it if you have the client variable activated to show it always.

**Comment by heinrich5991** [comment]
That's the way it has worked before, I think.

**Comment by fokkonaut** [comment]
Before we didnt have such an option to disallow it serverside?

**Comment by heinrich5991** [comment]
Is that a question?

We disabled always-on hook collision on non-DDRace servers before. I tried not to change that.

**Comment by fokkonaut** [comment]
Lol, why tho? its just a client setting to show everyone's hookline, just for you

**Comment by heinrich5991** [comment]
I have no idea, you could use `git-blame` to find out who introduced it.

**Comment by fokkonaut** [comment]
Useless. Let's just find a good way for it

**Comment by heinrich5991** [comment]
It was introduced by deen, you could ask him why he did it that way: 96ecbfcfa80fd5fa5218b863c4f358a3d69affba.

**Pull request closed without merging**
