### PR TITLE
show real key presses in show_direction

### LINKED ISSUE #3281: Show other peoples key presses while they are frozen
I've asked on discord but didn't really get an answer. Is this possible to implement?

### PR DESCRIPTION
**Pull request by C0D3D3V**
fixes #3281, #5149
This was requested in Discord, maybe we can make a vote about this somehow?
https://youtu.be/d0xymfFYVP8

Since DDNetCharacterDisplayInfo is not yet send on the server, and the client is not released with it, we can probably just add it to that.

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
What is "real"? Maybe call it `InputJump`. Perhaps fall back to the old code if the new net object isn't available.

**Comment by C0D3D3V** [comment]
> Perhaps fall back to the old code if the new net object isn't available.
I already do

Yes I wasn't entirely happy about the naming either.
but we already have PlayerInput.m_Direction
Is DDNetCharacterDisplayInfo.InputDirection really better?

**Comment by murpii** [comment]
Will this complement #5148?

**Comment by C0D3D3V** [comment]
heinrich would like it if we would not send these data twice, So I will test out if we can send the not manipulated inputs to the client in the original snaps, without big problems.

**Comment by sjrc6** [comment]
maybe you could also use client input to update direction for the local tee

**Comment by C0D3D3V** [comment]
No I want it for all or for none

**Comment by C0D3D3V** [comment]
I have now looked at the jump and direction physic for quite a while (and also tried to revise it). But that is firstly too much for me now and too tricky that the physic and especially game input / tick conditions then changes. 
Basically I would say the data we send so far has only a partial correlation with the real inputs, and if you don't send the physic data to the client it might not be able to predict its own inputs as well as it now can do.

Then I'd rather stay without a real input display for now, if we don't want to put it in the flag field. I'll make a PR for the change to a flag field in DDNetCharacterDisplayInfo and adjust this PR as soon as the upcoming flag is merged.

**Comment by C0D3D3V** [comment]
i'll close this and make a new issue if needed (at least for the flickering weapons display)

**Pull request closed without merging**
