### PR TITLE
Constify snap more (inspired by upstream)

### PR DESCRIPTION
**Pull request by ChillerDragon**
Incorporate const added in those upstream commits:
https://github.com/teeworlds/teeworlds/commit/d86d576217eeb843c822568f6b8f97ac852ac0d7
https://github.com/teeworlds/teeworlds/commit/e6b8518b49c353963af35efad8465d9066fb819e

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
I don't think we need the functions `SnapInvalidateItem` calling `InvalidateItem` calling `Invalidate` anymore. The only call to `SnapInvalidateItem` was removed in 59436b5e6dec43286d85e7948949f86182c7280f (#5210). [Link to the removed lines that previously contained the call](https://github.com/ddnet/ddnet/commit/59436b5e6dec43286d85e7948949f86182c7280f#diff-597779b4eb51af9adfedd04b8a235afff01091a4ba741daa604cb5cbeda4e3daL1126-L1145). Looks like the validation was moved to [`UnpackAndValidateSnapshot`](https://github.com/ddnet/ddnet/commit/59436b5e6dec43286d85e7948949f86182c7280f#diff-9008c287b2e3181f671692c3dd859c3921d5ee178753b62cc254d9abd1b1e5a3R2231-R2269) and inside the NetObjHandler.

LGTM otherwise!

**Comment by ChillerDragon** [comment]
> I don't think we need the functions `SnapInvalidateItem` calling `InvalidateItem` calling `Invalidate` anymore. The only call to `SnapInvalidateItem` was removed in [59436b5](https://github.com/ddnet/ddnet/commit/59436b5e6dec43286d85e7948949f86182c7280f) (#5210). [Link to the removed lines that previously contained the call](https://github.com/ddnet/ddnet/commit/59436b5e6dec43286d85e7948949f86182c7280f#diff-597779b4eb51af9adfedd04b8a235afff01091a4ba741daa604cb5cbeda4e3daL1126-L1145). Looks like the validation was moved to [`UnpackAndValidateSnapshot`](https://github.com/ddnet/ddnet/commit/59436b5e6dec43286d85e7948949f86182c7280f#diff-9008c287b2e3181f671692c3dd859c3921d5ee178753b62cc254d9abd1b1e5a3R2231-R2269) and inside the NetObjHandler.
> 
> LGTM otherwise!

Good catch! fixed :)

**Comment by Robyt3** [comment]
I meant that you can just remove the entire `SnapInvalidateItem` function. We can always readd it if we ever need it. And I don't like the spammy `snap invalidate problem` debug messages either (I already made a PR on upstream to remove them), as they cause a lot of lag and are not very informative.

If you want to do it more cleanly, first make a commit that removes this function and then make another commit that adds const:

1. undo the commit but keep the changes in the working tree: `git reset HEAD^`
2. remove the `SnapInvalidateItem` function
3. stage just the changes that remove the function with `git add -p`, or use a git GUI for this
4. commit the removal
5. stage the changes that add const again
6. commit the const changes
7. force push

**Comment by ChillerDragon** [comment]
This will outdate the documentation:

https://github.com/ddnet/ddnet/blob/b7da20826d2f382226515a9a185af9193ca47aa6/src/engine/docs/snapshots.txt#L27

> The client can also call <snap_invalidate_item> if an item contains improper information that could harm the operation of the client

**Comment by Robyt3** [comment]
> This will outdate the documentation:

I suppose you can delete that sentence, as well as the following one, which refers to it. Then add those changes to the first commit.

**Comment by Robyt3** [comment]
Thanks.

bors r+

**Pull request merged**
