### PR TITLE
Write log and sqlite files to storage unless given as absolute path

### LINKED ISSUE #4755: DDNet-Server writes to steam directory
The Server still writes to the steam directory `ddnet-server.sqlite` & `autoexec_server.log`
I guess it would be nicer to see the steam directory as read-only, who knows what permission problems this can cause on Windows

### PR DESCRIPTION
**Pull request by Robyt3**
Closes #4755.

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Should we add backwards compatiblity for users that have the sqlite file in the same folder as the server executable? Otherwise they'll need to move it manually.

**Comment by def-** [comment]
I hope this doesn't break on official servers
bors r+

**Comment by Robyt3** [comment]
It uses the first storage location for saving, so it will only find the existing file if `add_path $CURRENTDIR` is the first line in storage.cfg. An absolute path to the sqlite file should also work the same as before.

**Comment by heinrich5991** [comment]
The code duplication of `TYPE_ABSOLUTE` looks a bit bad. Perhaps it should be supported by `IStorage` itself, a flag that allows paths starting with `/` to be interpreted as absolute paths.

**Comment by Robyt3** [comment]
We could add `TYPE_ALL_AND_ABSOLUTE` and `TYPE_SAVE_AND_ABSOLUTE` to reduce the duplicate code.

**Comment by heinrich5991** [comment]
I think this would be a good idea. Maybe rather `TYPE_ALL_OR_ABSOLUTE`.

`TYPE_ABSOLUTE` seems to be a lie btw, it's just the normal path interpretation (the one without `IStorage`), even for relative paths.

**Comment by def-** [comment]
@Robyt3 aar? reported that the ddnet-server.sqlite file doesn't work next to DDNet-Server anymore. But it works in ~/.local/share/ddnet. Is that expected?

**Comment by Robyt3** [comment]
It also creates the `ddnet-server.sqlite` next to the DDNet-Server for me on Windows. It should create the file in the user directory unless the config variable is an absolute path. This seems to be a regression introduced by an conflict between #5948 and this PR.

To fix it, these calls to `RegisterSqliteDatabase` should be using `aFullPath` and not `Config()->m_SvSqliteFile`:

https://github.com/ddnet/ddnet/blob/34a56095355fa3a735113c2439280fb21ae31a76/src/engine/server/server.cpp#L2543-L2557

**Pull request merged**
