### PR TITLE
Add libpng, remove pnglite

### PR DESCRIPTION
**Pull request by Jupeyy**
Current issues are:
libpng16.dll.lib is missing
libpng16.dll should be without "-16"

the .dll is depending on a shared zlib library (zlib1.so)
so either static link it into the libpng or we remove zlib from external too

in the includes
"pnglibconf.h" is missing

Haven't tested it heavily yet, only tested if dilate and DDNet-Client still work

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Or should we just put libpng in src/engine/external and build it like that? Adding a new dependency usually causes problems.

**Comment by Jupeyy** [comment]
I've no idea what is easier :D

**Comment by def-** [comment]
Pushed into external, I think it's best if we handle it exactly as pnglite before, fewest surprises.

**Comment by Jupeyy** [comment]
Well on windows it expects this generated header file.

the others are just failing bcs i didnt add the library dep for all executables, since i added it to shared engine, so we don't have code dublication for all the tools that use PNGs

**Comment by def-** [comment]
check_dilate fails now:
```
convert-im6.q16: improper image header `/tmp/checker.dYv.png' @ error/png.c/ReadPNGImage/4092.
```

**Comment by Jupeyy** [comment]
> check_dilate fails now:
> 
> ```
> convert-im6.q16: improper image header `/tmp/checker.dYv.png' @ error/png.c/ReadPNGImage/4092.
> ```

will fix that once the dependencies are working

**Comment by def-** [comment]
> the others are just failing bcs i didnt add the library dep for all executables, since i added it to shared engine, so we don't have code dublication for all the tools that use PNGs

Yep, do you want to fix or should I give it a try?

**Comment by Jupeyy** [comment]
> > the others are just failing bcs i didnt add the library dep for all executables, since i added it to shared engine, so we don't have code dublication for all the tools that use PNGs
> 
> Yep, do you want to fix or should I give it a try?

Yeah I can do it

**Comment by Jupeyy** [comment]
"/home/runner/work/ddnet/ddnet/src/engine/external/png/pngpriv.h:920:4: error: #error ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"

on older ubuntu version.., thats annoying xD

**Comment by def-** [comment]
Using the bundled version should fix it, right?

**Comment by Jupeyy** [comment]
> Using the bundled version of both zlib and png should fix it, right?

i assume so :D

**Comment by Jupeyy** [comment]
> > Using the bundled version of both zlib and png should fix it, right?
> 
> i assume so :D

what is the best way todo this? or do you want to overtake again xd

**Comment by def-** [comment]
> what is the best way todo this? or do you want to overtake again xd

Done, but not in a very nice way. Maybe @heinrich5991 has a good idea how to ensure we always use the same zlib version.

**Comment by heinrich5991** [comment]
I don't want to look into this right now. I don't like adding libpng to each of our binaries, I'd much prefer to dynamically link it. I know that this goes directly against what deen said. :(

**Comment by def-** [comment]
I don't want to deal with all the linking problems of that, we always ended up with broken clients when we add an external dependency, especially on Linux distros. Reopened https://github.com/ddnet/ddnet-libs/pull/15 anyway.

**Comment by Jupeyy** [comment]
i dunno what the problem was, but i removed dd0d287a8e0d32cb70ae885d22bc0b5ea6dc5978
and just added libpng to the workflow installation, works.

**Comment by Jupeyy** [comment]
I see it also wasnt trying to find png as cmake package

**Comment by Jupeyy** [comment]
> I don't like adding libpng to each of our binaries, I'd much prefer to dynamically link it. I know that this goes directly against what deen said. :(

personally idc, we do the same for pnglite rn anyway, so its not worse than before, for size comparasion:
its around 300kb more

e.g. compiling with lto and stripping is still 500kb less than the pnglite version with stripping but without lto

**Comment by heinrich5991** [comment]
What's the status of this? It seems Jupeyy kept this updated. I'm still unhappy with compiling libpng from source, deen probably still wants this.

**Comment by Jupeyy** [comment]
Well i don't care if we inlcude it here or add the libs to ddnet-libs
I keep this updated and also use it in my client
here and there i hit indexed RGB colors, which cant be loaded by pnglite
and libpng might also be a bit more optimized (atleast it seems to be faster than stb, and robyte made some benchmark between stb and pnglite, vanilla pr)

**Comment by def-** [comment]
It's easier for me if we build it from source, but for all I care let's put it into ddnet-libs. Better than keeping pnglite probably.

**Comment by Jupeyy** [comment]
So then i removed libpng here again

**Comment by Jupeyy** [comment]
oh the macos build doesnt even fail, thats interesting, probs they include it in the sdk or smth

**Comment by Learath2** [comment]
pnglite seems to suggest the use of `stb_image` have you taken a look at that? A single header library that has a very compatible license so we can just include it "in-tree"

**Comment by Jupeyy** [comment]
> pnglite seems to suggest the use of `stb_image` have you taken a look at that? A single header library that has a very compatible license so we can just include it "in-tree"

Haven't look deeper into it, but they say
```
Some of these libraries seem redundant to existing open source libraries. Are they better somehow?
Generally they're only better in that they're easier to integrate, easier to use, and easier to release (single file; good API; no attribution requirement). They may be less featureful, slower, and/or use more memory. If you're already using an equivalent library, there's probably no good reason to switch.
```
So i assume libpng is just better for pngs, quick internet search atleast shows libpng is a bit faster

**Comment by Learath2** [comment]
Yeah, I just don't like integrating large libraries, just wanted to ask if you took a look. @Robyt3 ran some benchmarks on vanilla iirc, showing stb being only a little slower than pnglite.

**Comment by Jupeyy** [comment]
> Yeah, I just don't like integrating large libraries, just wanted to ask if you took a look. @Robyt3 ran some benchmarks on vanilla iirc, showing stb being only a little slower than pnglite.

What do you mean integrate?
It will be a library just like curl or SDL

If someone prefers and wants to implement stb idc, i'd personally go with libpng, since I know it even works well on android, and is tested a lot

**Comment by heinrich5991** [comment]
libpng sounds like the better choice, it's also used by browsers, so has better security vetting than stb_image.

**Comment by Jupeyy** [comment]
Oh, Visual studio cant handle ar files, guess we need .lib files

**Comment by def-** [comment]
Ok, I'll have to figure out how to get a .lib file out.

**Comment by Jupeyy** [comment]
Seems like generally .a files work with VS for c only libraries

```cmake

  set(ORIGINAL_FIND_LIBRARY_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
  if(TARGET_OS STREQUAL "windows")
    set(CMAKE_FIND_LIBRARY_SUFFIXES "${CMAKE_FIND_LIBRARY_SUFFIXES}" ".a")
  endif()

  set_extra_dirs_lib(PNG png)
  find_library(PNG_LIBRARY
    NAMES png16 libpng16
    HINTS ${HINTS_PNG_LIBDIR} ${PC_PNG_LIBDIR} ${PC_PNG_LIBRARY_DIRS}
    PATHS ${PATHS_PNG_LIBDIR}
    ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
  )
  set(CMAKE_FIND_LIBRARY_SUFFIXES ${ORIGINAL_FIND_LIBRARY_SUFFIXES})
```

But it still fails because it tries to link against `_errno`

**Comment by heinrich5991** [comment]
I think this needs a blacklist for formats that libpng can't load, at least in some places.
This would be so that we don't accidentally add such images to the skin DB etc. Alternatively, these places would need code changes to prevent such images from being added.

**Comment by Jupeyy** [comment]
I guess you meant, pnglite?
In worst case the older clients just fail to load the PNG, but that sounds fair enough to me.

But anyway, I guess ddnet can just stay with the status quo, there are often conflicts with this pr and its open since a very long time, so i'll close it for now

**Pull request closed without merging**
