### PR TITLE
Don't allocate the windows console default

### LINKED ISSUE #3661: Consider removing console on windows as default setting
As already described in #3403
Not allocating the console on windows makes the windows focus mouse input behavior much less triggerable(at starting),
I'm not sure what exactly triggers this weird behavior in windows, and why there is seems no fix for it.
But it seems to be a problem with windows not liking that the windows loosing focus and then grabs the input, just as described in #3577
But at startup this is kinda mandatory, because windows doesnt minimize the window, even if it lost the focus(not sure why this is happening, maybe even an windows "bug"/"undefined behavior").

This whole stuff is pretty easy to reproduce on a slow windows VM with steam client
just click on the console while opening the client, which then causes the console to be the focused window instead of the actual window.
Disabling the console doesnt fix this completly, but makes it alot harder to trigger, because the window is shown much earlier(dunno why this happens, also a weird behavior)

I'll leave a pr, for showcase

### PR DESCRIPTION
**Pull request by Jupeyy**
fixes #3661

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Oh, it's actually possible to do the reverse? I'm much in favor.

I thought it wasn't possible to spawn a console if you don't start with one. :D

**Comment by Jupeyy** [comment]
I only tested it with windows 10 vm yet

**Comment by Learath2** [comment]
Needs to be tested all the way down to XP where you can get some oooooddd oddd console behaviour. But if it does work, I like it aswell.

**Comment by Jupeyy** [comment]
Windows 7 also works

**Comment by def-** [comment]
I think Soreu still has WinXP, I'll ask him to test.

**Comment by Jupeyy** [comment]
works on windows xp, tested with VM

**Comment by def-** [comment]
Great, thank you!

bors r+

**Pull request merged**
