### PR TITLE
Make it more clear that this is a sixup translation server

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Learath2** [comment]
Should also probably add a line to our welcome message for sixup people to
let them know this is a translated server and they it's still rather
experimental.

**Comment by def-** [comment]
Done.

**Comment by Learath2** [comment]
Hm, shouldn't we still suggest our client? If you think it's okay like this it LGTM

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
