### PR TITLE
update desktop db after install

### PR DESCRIPTION
**Pull request by Ryozuki**
So it let you use ddnet links

### CODE REVIEW

**Comment by heinrich5991** [comment]
I think this might not be the correct strategy, as this `make install` is also used for packaging. Perhaps you could display a message telling the user to run this command if they want to have the DDNet links available immediately? What do you think?

**Comment by Ryozuki** [comment]
I don't think updating the desktop db does any harm, and if it fails for whathever reason, it will do it quietly, hence the -q.

**Comment by heinrich5991** [comment]
It does changes outside the packaging directory, that's why I'm worried about it.

**Comment by def-** [comment]
> I don't think updating the desktop db does any harm, and if it fails for whathever reason, it will do it quietly, hence the -q.

That's not the way to go, we should not do random stuff. I'd be more interested what the best practice is. How do other GUI programs with a cmake build system set this?

**Comment by Ryozuki** [comment]
> 
> 
> > I don't think updating the desktop db does any harm, and if it fails for whathever reason, it will do it quietly, hence the -q.
> 
> That's not the way to go, we should not do random stuff. I'd be more interested what the best practice is. How do other GUI programs with a cmake build system set this?

i don't know :/

**Comment by heinrich5991** [comment]
> I'd be more interested what the best practice is.

I just asked the person next to me with a GUI program. They just leave it to the packager. I think a message would be fine.

**Comment by Kaffeine** [comment]
Update of the desktop DB should always be up to distribution/packager. Usually touch of anything out of the build is a 'no-go' and has no effect.

Some distros (e.g. Fedora) usually installs desktop files with a special tool that updates db:
https://src.fedoraproject.org/rpms/quake2/blob/master/f/quake2.spec#_93

Others triggers the update in a post-install section:
https://github.com/sailfishos/sailfish-office/blob/master/rpm/sailfish-office.spec#L73

**Comment by heinrich5991** [comment]
Permalinks:

https://src.fedoraproject.org/rpms/quake2/blob/40dace27aee7204fd783f6d1a483a66195dc36b0/f/quake2.spec#_93

https://github.com/sailfishos/sailfish-office/blob/77d7a6b1d070728a9b7de76b89661b7e7f95419a/rpm/sailfish-office.spec#L73

**Comment by Learath2** [comment]
I guess that's that

**Pull request closed without merging**
