### PR TITLE
Restore grass_main_0.7.png vanilla compability

### LINKED ISSUE #8747: 0.7 dm7 has some floating tiles
DDNet 0.7
gg

Teeworlds 0.7
ee

### PR DESCRIPTION
**Pull request by ChillerDragon**
Reset to the current teeworlds version. Removing the ddnet specific extension from 2015.

https://github.com/ddnet/ddnet/commit/929919d44ba05a913030c556a28f6fd96d84b6e7#diff-d3cf443ce462f6e0cf9543319e40497f2c93505528a40cb7d923781643094f99

Closed #8747

```
$ wget https://raw.githubusercontent.com/teeworlds/teeworlds/a1911c8f7d8458fb4076ef8e7651e8ef5e91ab3e/datasrc/mapres/grass_main.png -O grass_main_0.7.png
$ dilate grass_main_0.7.png
```

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Blocked on https://github.com/ddnet/ddnet/issues/8747#issuecomment-2293816655.

Not sure why the new image is larger than the old one. Also needs to change the automapper rules, I guess.

**Comment by ChillerDragon** [comment]
```python
#!/usr/bin/env python3
# grass.py

import sys

import numpy
import twmap

def check_map(path: str):
    m = twmap.Map(path)

    for img in m.images:
        if not img.is_embedded() and img.name == "grass_main_0.7":
            print(f"map '{map}' has external grass_main_0.7")
            sys.exit(1)

for map in sys.argv[1:]:
    check_map(map)
```

Had zero hits on https://github.com/ddnet/ddnet-maps. I run it using

```zsh
git clone https://github.com/ddnet/ddnet-maps
cd ddnet-maps/types
grass.py ./**/*.map
```

I don't have a dump of kog maps right now.

**Comment by heinrich5991** [comment]
I've asked @Avolicious for a KoG map dump or KoG map downloads.

**Comment by heinrich5991** [comment]
See discussion in #8747.

**Comment by ChillerDragon** [comment]
> Also needs to change the automapper rules, I guess.

So revert it back to the older version? I think hi_leute_gll had a plan when he improved the auto mapper I don't think its the best idea to just revert his doings. Thats why I would suggest renaming the old file to grass_main_ddnet.png and use the auto mapper for that.

**Comment by Kaffeine** [comment]
We have some `mapsres/ddnet_*.png`. Would it be better to maintain own `ddnet_grass.png` with this ([2015](https://github.com/ddnet/ddnet/commit/929919d44ba05a913030c556a28f6fd96d84b6e7)) and maybe further development / extensions? Sure I can be wrong but maybe the missing one tile height dark bordered tiles (similar to the light tiles added in 0.7) can be useful in some cases.

**Comment by ChillerDragon** [comment]
avo said on discord the script had 0 hits.

**Comment by ChillerDragon** [comment]
This is no longer blocked on anything.

> Blocked on https://github.com/ddnet/ddnet/issues/8747#issuecomment-2293816655.

Checked all ddnet and kog maps.

> Also needs to change the automapper rules, I guess.

The auto mapper was moved in this pr https://github.com/ddnet/ddnet/pull/8760

**Review by def- — APPROVED** [review]

**Comment by heinrich5991** [comment]
> Not sure why the new image is larger than the old one.

This was unfortunately ignored and it's now too late to do anything about it, since the repository size has already permanently increased with the larger image size. Importing the smaller image now would only increase the repository size further.

**Comment by ChillerDragon** [comment]
> > Not sure why the new image is larger than the old one.
> 
> 
> 
> This was unfortunately ignored and it's now too late to do anything about it, since the repository size has already permanently increased with the larger image size. Importing the smaller image now would only increase the repository size further.
> 
> 

Oh yeah wopsi forgot about that. For repo size optimizations we could split textures into a new repo and have this one only for the code.

Not sure what made it bigger the commands I run to get the image are in the commit message. Messing with it any further seems risky and annoying.

**Comment by Kaffeine** [comment]
> > Not sure why the new image is larger than the old one.
> 
> This was unfortunately ignored

Yep. At the very least, we could use `git checkout b5044ea83210b3319f71d9b01ed73080595c5dd6 grass_main_0.7.png` to restore the originally added 0.7 texture with zero bytes added to the repository (well, the commit still'd add a few bytes).

**Comment by Kaffeine** [comment]
@heinrich5991, you could request changes to make it red and noticeable (I see how we all forget to do it timely, and realize the options only afterwards :heart: ).

**Comment by ChillerDragon** [comment]
> Yep. At the very least, we could use `git checkout b5044ea83210b3319f71d9b01ed73080595c5dd6 grass_main_0.7.png` to restore the originally (b5044ea83210b3319f71d9b01ed73080595c5dd6) added 0.7 texture with zero bytes added to the repository (well, the commit still'd add a few bytes).


Ah nice idea. Haven't thought about it.

**Comment by heinrich5991** [comment]
> Yep. At the very least, we could use `git checkout b5044ea83210b3319f71d9b01ed73080595c5dd6 grass_main_0.7.png` to restore the originally ([b5044ea](https://github.com/ddnet/ddnet/commit/b5044ea83210b3319f71d9b01ed73080595c5dd6)) added 0.7 texture with zero bytes added to the repository (well, the commit still'd add a few bytes).

We can't, it'd require a force push at this point.

**Comment by def-** [comment]
Why do we care about repo or image size? If there is a good reason, then add a CI check to run the image through zopflipng.

**Comment by heinrich5991** [comment]
> Why do we care about repo or image size?

Because repo size only ever increases. The DDNet repo is currently 350 MiB in size, and everyone who downloads it needs to download everything.



> then add a CI check to run the image through zopflipng.

Wouldn't have helped here, the solution was to check out the old image we already have in the repository.

**Comment by def-** [comment]
At the current rate of development I'm not worried about DDNet repo size becoming a huge factor. Having to download Rust is a much bigger factor for example. (1.5 GB on my system)

**Comment by ChillerDragon** [comment]
> At the current rate of development I'm not worried about DDNet repo size becoming a huge factor.

I agree with heinrich here. We should optimize for size. And I would go that far to say that it is already bad. Downloading ddnet code with slow internet is noticeably harder than teeworlds source code. Also when my disk was full recently I could free multiple gigabytes by deleting a few ddnet forks I had flying around.

> Having to download Rust is a much bigger factor for example. (1.5 GB on my system)

For me personally ddnet size matters more because I install rust only once but have multiple ddnet based repos on my pc and vps.







Long download and compile times make it harder and slower to start playing or hacking on ddnet. Compile times is of course something different but paired together it's a heavy entry for a free simple 2D Kirby game.

**Comment by def-** [comment]
If you don't get the git history it's quite fast and lean:
```
$ time git clone --depth 1 https://github.com/ddnet/ddnet
Cloning into 'ddnet'...
remote: Enumerating objects: 1783, done.
remote: Counting objects: 100% (1783/1783), done.
remote: Compressing objects: 100% (1651/1651), done.
remote: Total 1783 (delta 126), reused 1135 (delta 97), pack-reused 0 (from 0)
Receiving objects: 100% (1783/1783), 42.75 MiB | 23.98 MiB/s, done.
Resolving deltas: 100% (126/126), done.
git clone --depth 1 https://github.com/ddnet/ddnet  0.66s user 0.22s system 29% cpu 3.009 total
$ du -sch ddnet
110M	ddnet
110M	total
```

**Pull request merged**
