### PR TITLE
Change type of `m_HookTick` to `NetIntAny`

### LINKED ISSUE #8022: `CharacterCore::m_HookTick` is a duration, not an absolute tick
CC https://github.com/heinrich5991/libtw2/issues/93
CC @Zwelf

The type `NetTick` seems wrong, should probably be a NetInt.

https://github.com/ddnet/ddnet/blob/2258cbca57f2f009f50649d99906c29b00d3a374/src/game/gamecore.cpp#L215

https://github.com/ddnet/ddnet/blob/2258cbca57f2f009f50649d99906c29b00d3a374/datasrc/network.py#L191

### PR DESCRIPTION
**Pull request by furo321**
Closes #8022

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — COMMENTED** [review]
Is that so simple? No need for backwards compatibility etc?

**Comment by furo321** [comment]
`NetTick` is just an alias for `NetIntAny` as far as I understand it

https://github.com/ddnet/ddnet/blob/effc79cc87cb0be4833d9e5c02732e9635153317/datasrc/datatypes.py#L402-L404

**Comment by BlaiZephyr** [comment]
what is the reason behind clamping `m_HookTick` on seven/network.py  but not on /network.py ? just curious

**Comment by furo321** [comment]
> what is the reason behind clamping m_HookTick on seven/network.py but not on /network.py ? just curious

DDNet's `NetTick` is a `NetIntAny` while on 0.7 it's clamped between 0 and max_int. Why DDNet's `NetTick` differs is due to this commit https://github.com/ddnet/ddnet/commit/3ea1bab6174e41a5531daf9505af3548c84986f4 from 10 years ago, which fixed some bug?

**Comment by heinrich5991** [comment]
> Is that so simple? No need for backwards compatibility etc?

Yes.

**Review by def- — APPROVED** [review]
Alright, just an alias makes sense.

**Pull request merged**
