### PR TITLE
Add `./configure` script

### PR DESCRIPTION
**Pull request by heinrich5991**
This allows the common sequence for building programs:
```
./configure
make
make install
```

### CODE REVIEW

**Comment by def-** [comment]
Is that common practice? I thought cmake was supposed to replace autotools/configure, not imitate them.

**Comment by def-** [comment]
Because then we have 3 ways of building already, "bam", "cmake && make" and "./configure && make"

**Comment by heinrich5991** [comment]
We don't have to maintain three build systems though, this is just a thin wrapper . This is just a little convenience for people who don't know `cmake`. `./configure && make` is pretty standard.

**Comment by def-** [comment]
I don't see the use, but I have no problem with it if others do. If anyone else is for it, add it.

**Comment by daverck** [comment]
This can help more people to test development version imo

**Comment by heinrich5991** [comment]
This will need some changes to be added. Closing for now.

**Pull request closed without merging**
