### PR TITLE
Get rid of wrong dbg_assert that can crash server

### PR DESCRIPTION
**Pull request by Ryozuki**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Why is this `dbg_assert` wrong? It looks legitimate to me. If it is, you might be hiding a programming error by removing the assert (if the server crashed due to the assert).

**Comment by heinrich5991** [comment]
It would be great if you could put this kind of information into the commit message or the pull request description.

**Comment by def-** [comment]
1. The condition is always true
2. dbg_asserts used to crash the server, even in release builds

**Comment by heinrich5991** [comment]
If the condition is indeed always true (should be always true), then it would be beneficial to keep the assert, this is what asserts are for (detecting unusual state that shouldn't happen). From what I can tell, the parameter is never user-generated but always by the server.

**Comment by def-** [comment]
No, it's not beneficial. Every int is >= 0 or <= MAX_CLIENTS. The person who wrote that wanted to express && instead of ||. If you want to have crashes in debug builds, then please make it so that you have to write the condition once, and not like here where 1 line below you return.

**Comment by heinrich5991** [comment]
Ah true, I didn't see that. Thanks.

"Get rid of `dbg_assert` that tests for nothing (and certainly can't crash the server)"

**Pull request merged**
