### PR TITLE
Improve editor color picker popup

### PR DESCRIPTION
**Pull request by Robyt3**
- Color picker button:
   - Before:
screenshot_2023-06-14_20-25-38
   - After:
screenshot_2023-06-14_20-25-18

- Color picker popup:
   - Before: 
screenshot_2023-06-14_20-25-43
   - After:
screenshot_2023-06-14_20-25-24

## Checklist

- [X] Tested the change ingame
- [X] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — APPROVED** [review]
bors r+

**Comment by HiRavie** [comment]
The old RGBA and Hex fields seem redundant with the improved picker. I think it's a good opportunity to clean up the menus even more since RGBA feels clunky to use anyway, could look like this:
image

**Comment by Robyt3** [comment]
> The old RGBA and Hex fields seem redundant with the improved picker. I think it's a good opportunity to clean up the menus even more since RGBA feels clunky to use anyway

Okay. Do you think many mappers are going to miss the old individual RGBA value selectors? Or do mappers mostly copy in some Hex-value or use the HSV color picker to begin with?

**Comment by HiRavie** [comment]
> Okay. Do you think many mappers are going to miss the old individual RGBA value selectors? Or do mappers mostly copy in some Hex-value or use the HSV color picker to begin with?

I can't say for sure but RGBA is not a very intuitive system for humans so I assume most people use the picker.

**Pull request merged**
