### PR TITLE
HiDPI-aware Resolution List

### PR DESCRIPTION
**Pull request by TsFreddie**
This is a version of https://github.com/teeworlds/teeworlds/pull/2827

Which gives you a resolution list that allows you to select appropriate window size (which is saved in config and used to initialize videos), while showing the canvas size (which is the drawing resolution), at least on MacOS.

This also fixes incorrect clips that happens without HiDPI enabled, because `Graphics()->ScreenWidth()` (in canvas size) was reported incorrectly before, which is now fixed.

Also, I noticed that `m_DesktopScreenWidth` and `m_DesktopScreenHeight` (in window size in MacOS) is used incorrectly or differently from what it was used during initialization:

* During initialization, DesktopScreenWidth is the "screen width of your desktop", but it was used as the "game window size on your desktop" when checking whether to resize window. I added a separate window size calculation to use during resize.

Also, god, I hope SDL's different sizes and stuff is reported consistently at least in Wayland or X, so please test. I know in Windows they are always in pixel/canvas size so it might not be a huge issue there.

## Checklist

- [x] Tested the change ~~ingame~~ on MacOS
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options (again, on MacOS, with both HiDPI and non-HiDPI settings)
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Independent of this pr:
We might want to consider waiting for the GLES pr, bcs rebasing it will probably be a pain, than the other way around.

**Comment by TsFreddie** [comment]
Yep. forgot we are doing GLES stuff.

Also, non-HiDPI mode is still broken and `SDL_GL_GetDrawableSize` reports size differently before and after `SDL_SetWindowSize` which is driving me nuts for the past hour. The resolution list thing still works, but the commits are back and forth dirty now. I'll redo it afterwards.

**Comment by def-** [comment]
@TsFreddie Can you please rebase?

**Comment by TsFreddie** [comment]
@def- So we are getting this first instead of GLES?

**Comment by def-** [comment]
Oh, I thought we merged GLES already. Sorry. But this is definitely more important, since people are running into it daily. I'll try to review GLES.

**Comment by Jupeyy** [comment]
But wont this just help with MacOS, as far as i am aware macos is the only OS that implements hdpi like this.
@Learath2 u know such things

**Comment by TsFreddie** [comment]
Ye, only helps MacOS and *maybe* Wayland. 

For the Windows HiDPI issue we keep getting lately, maybe we can make a hotkey for resetting resolution, and make sure we make a confirm+countdown dialog for reverting resolution changes like all other games do. But before that we need to address the missuse of  m_DesktopScreenWidth:

> During initialization, DesktopScreenWidth is the "screen width of your desktop", but it was used as the "game window size on your desktop" when checking whether to resize window. I added a separate window size calculation to use during resize.

Otherwise resetting resolution is kinda impossible.

Either way the graphics needs to be touched a little bit.

**Comment by Jupeyy** [comment]
What do you think @def- how important is "Show only supported [resolutions]", were there problems without it before?

Else we could also just remove that function from the menus, so it can only be accessed in f1

**Comment by def-** [comment]
I'd be ok with removing the button, but I'm not sure if that's the actual cause of the wrong resolution.

**Comment by Jupeyy** [comment]
> I'd be ok with removing the button, but I'm not sure if that's the actual cause of the wrong resolution.

Yeah, thats true too. i asked that guy on discord, hopefully he'll answer. Mostly they wont xD

**Comment by TsFreddie** [comment]
On Windows, it is possible that someone launched the game before and have a 4k resolution set. And somehow they changed the scaling setting or launched steam in low DPI mode.

Then we still initialize a window with a 4k frame which is large than the scaled down desktop size.

We can always check `g_Config.m_GfxScreenWidth` against `Graphics::m_DesktopScreenWidth` which seems to be reporting correctly on both of my Windows PC and Mac.

**Comment by Jupeyy** [comment]
I always thought that windows shouldnt care about dpi settings, as we have #917

Did you test it with an official release, or is it maybe only a MSVC thing?

**Comment by TsFreddie** [comment]
We shouldn't during rendering. Application will think the user has a small screen. Same thing WILL happen if the user changed their monitor from a 4k one to a 1080p one, which has the exact same problem on Windows.

**Comment by Jupeyy** [comment]
> We shouldn't during rendering. Application will think the user has a small screen. Same thing WILL happen if the user changed their monitor from a 4k one to a 1080p one, which has the exact same problem on Windows.

I understand the second case, but that also shouldnt happen that often.
But if you tried it i believe you. When i first added the pr above i especially tested setting other scalings as this was the main problem

**Comment by TsFreddie** [comment]
image
Did you test this?

**Comment by Jupeyy** [comment]
> image
> Did you test this?

mh i doubt, i think i only tested it with the windows 10 settings, which also were called HDPI or smth, so if this is smth different ok, is it per app, would ppl need to set it manually or is automatic for some apps?

**Comment by TsFreddie** [comment]
Didn't work fully for @Learath2, might due to different MacOS versions or AppKit versions, and we discussed a bit and didn't come to a conclusion on how to fix it for all MacOS versions.

**Comment by Learath2** [comment]
FWIW the only thing that really broke was the highest resolution being missing when hidpi is on. If that is fixed/fixable we can get this in.

The AppKit thing had more to do with #2173. Which seemed to oddly not affect @TsFreddie .

**Comment by TsFreddie** [comment]
some changes
demo: https://streamable.com/qtbaxb

Exchanged `IGraphics::m_DesktopScreenWidth` with `g_Config.m_GfxDesktopWidth` so we can remember users display resolution. If we detected user's display changes (changing DPI scaling, changing Monitors, changing DPI settings, etc), we clamp down the resolution to desktop resolution. If display haven't changed (any of above didn't happen), user can still force super high resolution if they really want to.

I'll later add pre resolution change warning for changing to resolution higher than desktop size, and a countdown revert dialog for reverting a broken resolution is selected.

**Pull request merged**
