### PR TITLE
Add tutorial joining code and tutorial map (fixes #269)

### LINKED ISSUE #269: Tutorial and/or "Getting Started" help
When the client is started for the first time, we should show the new player around, explain some stuff and show how the game works, potentially with a tutorial map.

Some ideas here:
- http://forum.ddnet.tw/viewtopic.php?t=1942
- http://forum.ddnet.tw/viewtopic.php?t=1941&p=20587#p20587

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
serverlist now contains a Tutorial server type

**Comment by def-** [comment]
I didn't see a good way to use the Tutorial server type, going by name now. Is that ok?

**Comment by Jupeyy** [comment]
there are conflicts,
I tested it, should be good enough for a start, I dunno if @heinrich5991 is currently available and ok with this, else lets just join and can still be improved later

**Comment by def-** [comment]
Fixed.

**Pull request merged**
