### PR TITLE
Update Tutorial map by unique_2

### PR DESCRIPTION
**Pull request by def-**
> We made a small update of the tutorial map because of the new freeze
> graphics. We also made the teleport tiles the airjump hints
> consistent. Idk how updating the map works on your end, ideally
> everyone keeps their time because the changes don't influence anyone's
> times.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Patiga** [comment]
The map passes the usual checks :+1:

**Comment by def-** [comment]
@Patiga can we add those checks to CI for the maps in repo? What do I have to call?

**Comment by def-** [comment]
The output now is:
```

Run find . -type f -name '*.map' -print0 | xargs -0 ~/.cargo/bin/twmap-check-ddnet
"./data/maps7/LearnToPlay.map": Time cps are missing on the map
"./data/maps7/Tutorial.map": Map setting - Unusual: 'sv_show_others_default'
"./data/themes/heavens_day.map": Time cps are missing on the map
"./data/themes/heavens_night.map": Time cps are missing on the map
"./data/themes/newyear.map": Time cps are missing on the map
"./data/themes/autumn_night.map": Map - Image error at index 3 : 'generic_lamps' is not a valid external image in version DDNet06
"./data/themes/jungle_night.map": Time cps are missing on the map
"./data/themes/autumn_day.map": Time cps are missing on the map
"./data/themes/jungle_day.map": Time cps are missing on the map
"./data/themes/winter_night.map": Time cps are missing on the map
"./data/themes/winter_day.map": Time cps are missing on the map
"./data/maps/dm6.map": Time cps are missing on the map
"./data/maps/dm2.map": Time cps are missing on the map
"./data/maps/dm9.map": Time cps are missing on the map
"./data/maps/ctf7.map": Time cps are missing on the map
"./data/maps/ctf5.map": Time cps are missing on the map
"./data/maps/ctf3.map": Time cps are missing on the map
"./data/maps/dm1.map": Time cps are missing on the map
"./data/maps/ctf4.map": Map - Image error at index 3 : 'jungle_doodads_old' is not a valid external image in version DDNet06
"./data/maps/ctf2.map": Time cps are missing on the map
"./data/maps/dm8.map": Time cps are missing on the map
"./data/maps/LearnToPlay.map": Time cps are missing on the map
"./data/maps/ctf6.map": Time cps are missing on the map
"./data/maps/ctf1.map": Time cps are missing on the map
"./data/maps/dm7.map": Time cps are missing on the map
"./data/maps/Tutorial.map": Map setting - Unusual: 'sv_show_others_default'
```
but still succeeds.

**Comment by Patiga** [comment]
@def- The checks would be both `twmap-check` and `twmap-check-ddnet`. However, I don't think they have helpful return codes which could be used.
The discord-bot simply checks if it prints something to stdout to determine if everything is okay

**Comment by def-** [comment]
I'm using something similar with a whitelist of the current problems now.

**Comment by Patiga** [comment]
Hmm, I guess `twmap-check-ddnet` is sufficient. `twmap-edit` would only give more output with `-vv`, which would print warning and info logs. Those are not relevant for the pipeline though

**Comment by def-** [comment]
Ready for review

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
