### PR TITLE
Test tools in CI (#9368)

### PR DESCRIPTION
**Pull request by ChillerDragon**
So far there are basics tests for 3 tools. For testing the tools we will need some binary files such as images/maps/demos and they should not be in the main repository to avoid growing its size. I thought about using some git submodule but not sure if I like it. For now the script downloads the one demo it needs from [github](https://github.com/ChillerDragon/ddnet-test-tools/blob/master/data/dm1.demo). If we decide to go that way this repo should be moved to the ddnet organization first before merging it.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Please write the tests in Python or another language that can be easily executed on Windows.

**Comment by def-** [comment]
Is bash harder to install than Python?

**Comment by heinrich5991** [comment]
Yes.

Python has an installer on https://python.org/ or can easily be installed together with MSVS (just a checkbox).

**Comment by ChillerDragon** [comment]
I would argue every windows dev has bash installed. But anyways not every ddnet dev needs to run the integration tests for tools anyways. Its more for the CI. Imo bash is the best tool for the job.

So what to do about the files that I would like to keep out of git? Are you okay with downloading them from another repo?

**Comment by heinrich5991** [comment]
> I would argue every windows dev has bash installed.

Definitely not. Maybe every Linux dev running Windows already has bash installed.

I don't think this should be merged if it's implemented in bash.

**Comment by ChillerDragon** [comment]
Well I don't have the numbers. But I personally had bash installed before I knew how to install linux. [It came with git for me](https://gitforwindows.org/).

Anyways your the maintainer and you made your final call. I will not rewrite it in python so somebody else can pick up the issue.

**Comment by ChillerDragon** [comment]
@heinrich5991 could you add don't use bash to CONTRIBUTING.md to avoid wasting time like this again?

**Pull request closed without merging**
