### PR TITLE
Use local inputs for direction arrows and aim line toggle

### PR DESCRIPTION
**Pull request by sjrc6**
This removes the delay from latency when activating aim line or viewing your own direction arrows.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
This might stop the direction line thing from being server-controlled. Or do we have a flag for that nowadays?

**Comment by sjrc6** [comment]
Is that required for some reason? I didn't know the server had a reason to force hookline on your local tee?

**Comment by def-** [comment]
Yes, we want server owners to be able to disallow using aim line. In the beginning I was not sure how controversial the aim line would be and if some server owners might consider it as a cheat, so I left this option open for them.

**Comment by heinrich5991** [comment]
You can make the hook collision prediction conditional on `GameClient()->m_GameInfo.m_AllowHookColl`, then the server can decide to disable it.

**Comment by sjrc6** [comment]
Yes I was doing it right at you sent that lol

**Comment by heinrich5991** [comment]
I think the more correct way would be to only consider overwriting the server choice if that flag is set. I.e. don't override the current server flag if hookcoll is not marked as allowed. Then the server can still set it if it wants to.

**Comment by sjrc6** [comment]
ok sure.

**Comment by heinrich5991** [comment]
Thanks!

**Pull request merged**
