### PR TITLE
AntiPing limit is unintuitive, remove from settings

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by fokkonaut** [comment]
Why? I liked it with the slider.

**Comment by def-** [comment]
People don't understand that the slider corresponds to your ping and when your ping is higher than specified value, antiping gets enabled.

**Comment by fokkonaut** [comment]
Then dont remove the slider instead add a help text, or we finally add hover help texts.

**Comment by def-** [comment]
@fokkonaut could you give that a try?

**Comment by fokkonaut** [comment]
Very busy lately, dont even commit anything to my own mod. When I get free time maybe, but who knows when that will be

**Comment by heinrich5991** [comment]
I think this is good to remove, unless someone else improves it. Thanks!

bors r+

**Pull request merged**
