### PR TITLE
FIX: Set StrongWeakID to 0 if SvNoWeakHook enabled

### PR DESCRIPTION
**Pull request by Avolicious**
- [ x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Avolicious** [comment]
Setting the strong weak indicator to 0, cleaner solution would be to send a correct gameflag for the client to remove strong/weak indication and set it to neutral

**Comment by Jupeyy** [comment]
the client has this information, so should probs not be hard. `m_WorldConfig.m_NoWeakHookAndBounce`

**Comment by def-** [comment]
Sorry @Avolicious . Didn't know we already transmit this in WorldConfig.

**Comment by Avolicious** [comment]
> the client has this information, so should probs not be hard. `m_WorldConfig.m_NoWeakHookAndBounce`

But then it should be renamed, because `NoWeakHookAndBounce` doesnt exists on server-side, it has been changed with fokko's merge here https://github.com/ddnet/ddnet/pull/5770/files

**Pull request closed without merging**
