### PR TITLE
Don't crash when no ids are left (fixes #4565)

### LINKED ISSUE #4565: Crash with dbg_assert("id error")
```
Core was generated by `./DDRace64-Server_sql -f servers/8319.cfg'.
Program terminated with signal SIGILL, Illegal instruction.
#0  dbg_break () at /home/teeworlds/src/master/src/base/system.cpp:124
124     /home/teeworlds/src/master/src/base/system.cpp: No such file or directory.
[Current thread is 1 (Thread 0x7fbcd6df5000 (LWP 1287319))]
(gdb) bt
#0  dbg_break () at /home/teeworlds/src/master/src/base/system.cpp:124
#1  dbg_assert_imp (filename=<optimized out>, line=<optimized out>, msg=msg@entry=0x55637f16e7b4 "id error", test=0)
    at /home/teeworlds/src/master/src/base/system.cpp:117
#2  0x000055637f0ace71 in dbg_assert_imp (
    filename=filename@entry=0x55637f16ee60 "/home/teeworlds/src/master/src/engine/server/server.cpp", line=line@entry=98, 
    test=test@entry=0, msg=msg@entry=0x55637f16e7b4 "id error") at /home/teeworlds/src/master/src/base/system.cpp:119
#3  0x000055637f0ba6b1 in CSnapIDPool::NewID (this=0x7fbcd66fe654) at /home/teeworlds/src/master/src/engine/server/server.cpp:98
#4  0x000055637f0dc7ba in CEntity::CEntity (this=0x556382de95c0, pGameWorld=<optimized out>, ObjType=<optimized out>, Pos=..., 
    ProximityRadius=<optimized out>) at /home/teeworlds/src/master/src/game/server/entity.cpp:20
#5  0x000055637f0d6d07 in CDragger::CDragger (this=0x556382de95c0, pGameWorld=<optimized out>, Pos=..., Strength=3, 
    NW=<optimized out>, CaughtTeam=38, Layer=4, Number=91) at /home/teeworlds/src/master/src/base/vmath.h:26
#6  0x000055637f0d761c in CDraggerTeam::CDraggerTeam (this=0x7ffdebc402b0, pGameWorld=0x7fbcd3feba08, Pos=..., Strength=3, NW=true, 
    Layer=4, Number=91) at /home/teeworlds/src/master/src/game/server/entity.h:18
#7  0x000055637f0f1b56 in IGameController::OnEntity (this=0x55638260f3e0, Index=47, Pos=..., Layer=<optimized out>, Flags=0, 
    Number=91) at /home/teeworlds/src/master/src/game/server/gamecontroller.cpp:368
#8  0x000055637f0e7abc in CGameContext::OnInit (this=0x7fbcd3fdc010)
    at /home/teeworlds/src/master/src/game/server/gamecontext.cpp:3400
#9  0x000055637f0c281c in CServer::Run (this=this@entry=0x7fbcd6013010)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:2560
#10 0x000055637f0ad56b in main (argc=<optimized out>, argv=<optimized out>)
    at /home/teeworlds/src/master/src/engine/server/server.cpp:3695
```

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
I have no idea what this code does. Is the idea of the commit merely to turn a runtime assertion into a runtime log, because it worked fine before™?

**Comment by def-** [comment]
Yes, the -1 ID was previously handled as meaning we don't have space for further IDs.

**Comment by heinrich5991** [comment]
As far as I can tell, these IDs end up in `CEntity::m_ID` and are then used to create new items in `CSnapshotBuilder::NewItem`. This function treats the integer as 16-bit integer and ORs it with the type ID making the resulting combined ID a constant -1. It looks like the snapshot permits multiple items with the same combined ID, and it looks pretty implementation defined from then on.

Perhaps we could make the `CSnapshotBuilder::NewItem` function return `nullptr` when an ID of `-1` is passed?

**Comment by heinrich5991** [comment]
@ChillerDragon Might this be causing your snapshot problems?

**Comment by def-** [comment]
I noticed that NewItem has some dangerous dbg_asserts too, aren't they super easy to break by creating many items?

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by ChillerDragon** [comment]
> @ChillerDragon Might this be causing your snapshot problems?

Nah given that this was mergen in jan this is not fixing anything for me.

**Pull request merged**
