### PR TITLE
Allows low mousesens

### PR DESCRIPTION
**Pull request by ChillerDragon**
Lower minimum mousesens value to avoid confusion. Responing to GG Kid's request:
https://forum.ddnet.tw/viewtopic.php?f=45&t=5807&p=58207&hilit=mousesens#p58207

I did some testing and found no bugs... but i wonder why it was set to 5. So maybe it had some reason i don't understand so please only merge if you know what you are doing ;p

### CODE REVIEW

**Comment by heinrich5991** [comment]
Could you check how that interacts with the option menu where you can also set the mouse sensitivity?

I think there's a second variable concerning this, mabye `ui_mousesens`?

**Comment by heinrich5991** [comment]
bors r+
Thanks!

**Comment by fokkonaut** [comment]
does this affect the current mousesens so do we have to set it to another value or will it stay the same?

**Comment by heinrich5991** [comment]
It stays the same.

**Pull request merged**
