### PR TITLE
added Kenney_Stones: png by RaiNy,  rules by DoNe

### PR DESCRIPTION
**Pull request by timgame**

### CODE REVIEW

**Comment by def-** [comment]
Should we really add this? We have to decide which tilesets to ship with.

**Comment by heinrich5991** [comment]
A long term solution would be to have tilesets downloadable separately from maps. We obviously don't have that yet, so...

@timgame Did you draw these tilesets? If not, have you got permission to include them in DDNet under DDNet's license? E.g. it'll probably be allowed to just strip the credits, etc.

That leaves us with the next question: Should there be credits in official mapres? It inflates the file size.

As I understand it you can't use the tileset in maps just yet (without embedding them), because we also support clients other than DDNet.

**Comment by timgame** [comment]
Some1 asked me to do a automapper for that tileset. In that case I normally create a pull request to add the automapper to the client since it could be useful to other mappers. Ofcourse I also include the tileset with the automapper. An external database for automappers and mapres would be an option so you don't have to download the mapres if you want the client. I have no permissions but I'm sure the creator is okay with it since he posted it hisself in the DDNet forum http://forum.ddnet.tw/viewtopic.php?f=14&t=538#p4619.

**Comment by def-** [comment]
I think such a database would be great and I also think Soreu has been working on it. Would be nice if you get in touch with him, maybe you can work on that? I imagine it similar to the skin database, a curated list of useful graphics for mapping.

**Comment by timgame** [comment]
If we do that we should join the skin database and the the other graphics. Since the skin database isn't really expandable I would have to rewrite it and use a real database. This could be a fun project but it would take some time to do. I'll contact Soreu, I don't know if hes familiar with programming but it would be nicer to do it in a team.

**Pull request closed without merging**
