### PR TITLE
Receive NETMSG_TIME_SCORE as game message (fixes #1622)

### LINKED ISSUE #1622: time score/ normal score in demos
demos use the score format that the client had on the last server he joined. the demo needs to know when the client had time score or normal score, because it can also change during gameplay if the server sends the msg to change score format.

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by heinrich5991** [comment]
This should probably be in a `CNetObj` as well, otherwise skipping in demos doesn't work.

Perhaps add a new `CNetObj_DDNetGameInfo` with a flags variable where the first bit is that flag?

**Comment by fokkonaut** [comment]
Why tho? Its good like this, just at the wrong place when sending it as a system message. It belongs to the game message.

**Comment by fokkonaut** [comment]
And I dont know how to make CNetObj's. Maybe you could do it if i

**Comment by fokkonaut** [comment]
Sorry ^^

**Comment by heinrich5991** [comment]
Register your `CNetObj` in datasrc/network.py. Come talk to me for more details.

> Why tho? Its good like this, just at the wrong place when sending it as a system message. It belongs to the game message.

I answered this above:

> This should probably be in a `CNetObj` as well, otherwise skipping in demos doesn't work.

**Comment by fokkonaut** [comment]
I tried to talk to you many times on discord, you never answered me. There are several things you said I can ask you for help alread

**Comment by heinrich5991** [comment]
Mh… Okay, sorry. Perhaps I overestimated the time I spend on Discord. :(

**Comment by fokkonaut** [comment]
I have a command on my server to change between time score and normal score (chat command, seperated for every tee). If I have NO dummy connected, it works just fine. But when the dummy is connected, it doesnt update that I have changed the format using the command, only if both, the dummy and the main tee enter the command. So if its the same, then it works again.

How can I fix that?

**Comment by fokkonaut** [comment]
@heinrich5991

**Comment by Learath2** [comment]
Can we discuss these new netobjs before adding them? They will be used in the future, we should make sure they are properly extensible

**Comment by fokkonaut** [comment]
I will close it, I am unable to make this working fine with Dummy support (so that both players have it seperated).

Someone can make a DDNetGameInfo NetObj and add this as first bit.

**Pull request closed without merging**
