### PR TITLE
Upgrade to macos 12 in github CI

### PR DESCRIPTION
**Pull request by def-**
> macOS-latest pipelines will use macOS-12 soon. For more details, see https://github.com/actions/runner-images/issues/6384

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Fails to run for me:
```
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
Referenced from: <37564404-46C0-3849-B4A4-87B1D07F5057> /Applications/DDNet.app/Contents/MacOS/DDNet
Reason: tried: '/usr/local/opt/freetype/lib/libfreetype.6.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/freetype/lib/libfreetype.6.dylib' (no such file), '/usr/local/opt/freetype/lib/libfreetype.6.dylib' (no such file), '/usr/local/lib/libfreetype.6.dylib' (no such file), '/usr/lib/libfreetype.6.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)
```

**Comment by def-** [comment]
Works now, new problem is that the data files are somehow missing, let me check:
Screenshot 2023-01-13 at 18 38 47

**Comment by Jupeyy** [comment]
uhm i have never seen it, also you use bundled libs so it should work?^^

**Comment by def-** [comment]
Yes, pretty weird.

**Comment by def-** [comment]
This might just be the "Gatekeeper Path Randomization"

**Comment by def-** [comment]
Still ready for review

**Comment by Jupeyy** [comment]
why is this better than macos-latest?

**Comment by def-** [comment]
We can decide when we upgrade to next version. I forgot the initial motivation, but when it switches to macOS 12 automatically CI will break, which is annoying.

**Pull request closed without merging**
