### PR TITLE
Much more readable Call Vote menu and code

### PR DESCRIPTION
**Pull request by Banana090**
I find "Call Vote" menu useless af right now, because it's simply impossible to read it. So when you want to call vote for a map you open website and find the one you want, after that making /map skipping the "Call Vote" menu completely. It's useful for calling for random map btw, but anyway too ugly to look at.

**OLD LOOK**
callvoteold

**NEW LOOK**
callvotenew

**NEW LOOK (RconAuted)**
callvotenewrcon

Changed nothing, but row and text size + View rect size, because for some reason it was small for preserving space for RCON Auted users. Why?
Also changed the name of rect "Extended" to "RconExtension" to make it more clear what is it for.

Would be cool also to remove all that junk that is not actual votes from DDNet server vote list (finishers, average time) and merge it into one line with map's name. 

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
How can you force votes when authed now?

I don't think we should make fonts smaller.

**Comment by Banana090** [comment]
@def- sorry, forgot to rcon-auth for screenshot lol, I'll change rcon prewiew image now

**Comment by edg-l** [comment]
Now that you are at it, you could make the reason bigger, maybe big enough to display the max characters it can display, atleast on big resolutions.

**Comment by Banana090** [comment]
@edg-l don't really want to remake call votes now, so just tweaked some values to make it at least somewhat usable

**Comment by edg-l** [comment]
Well this should be pretty easy to do, ill just do it after it gets merged then.

**Comment by b3z** [comment]
if you make the fonts smaller it is easier to find maps. @def- 
it is the same problems with tw skins. You search for ages because they are so big in the skin browser.

**Comment by Banana090** [comment]
@b3z thanks for mentioning, I'll look at it afterwards xD

**Comment by Banana090** [comment]
Merge?

**Comment by def-** [comment]
Please don't ping or write a comment without content.

**Comment by def-** [comment]
The new RconAuthed looks weird to me:
- Too much empty space between the top and bottom line
- The Force vote seems to make no sense next to search
- Remove is in a weird location too, not close to add
- Remove is large, but Add is not

**Comment by Banana090** [comment]
Wow, weird. I didn't change anything in rcon menu or something... But it seems to be changed, lol...

**Comment by Banana090** [comment]
Fixed this, now rcon panel looks exactly like it was. Didn't want to change anything except font size and main view size for non-rcon

**Comment by def-** [comment]
Thanks, looks fine now.

bors r+

**Pull request merged**
