### PR TITLE
Remove Language button text localization

### PR DESCRIPTION
**Pull request by BannZay**
There should be way to change laguage to user native(or at least to english) if he did wrong configuration

### CODE REVIEW

**Comment by def-** [comment]
And what about people who don't speak English? :D

**Comment by BannZay** [comment]
@def- , so comes time to learn one single word for them xD

First my though - is make smthing like "Sprache (Language)" (button should contain localized and non localized text), but there not enough space. 

I guess it should be good enough just without localization

**Comment by FallenKN** [comment]
Maybe its time to display some symbols there 😏

**Comment by CytraL** [comment]
Or you can learn where the button is...

**Comment by BannZay** [comment]
> Maybe its time to display some symbols there 

Good idea, but there is no such symbol. I guess, make such picture - true way

> Or you can learn where the button is...

 In menu a lot of buttons, which could used once/zero time. User dont have to keep in mind, where which button is. It is absurd.

**Comment by def-** [comment]
This symbol might work, but it's not in our font: http://www.fileformat.info/info/unicode/char/1f4ac/index.htm

**Comment by def-** [comment]
Anyway, the first field is the language, there's not much searching required. I'll just close this.

**Pull request closed without merging**
