### PR TITLE
Add invincible mode

### PR DESCRIPTION
**Pull request by timakro**
This PR adds invincible mode as an alternative to super that is safe for /practice mode. Specifically, it does not allow the player to interact with members of other teams. Please read the individual commit messages for details.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [x] Tested in combination with super and unsuper rcon commands
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by timakro** [comment]
Any ideas how to visually indicate that a player is invincible?

**Comment by def-** [comment]
Invincibility mushroom

**Comment by timakro** [comment]
> Invincibility mushroom

You mean as an icon in the top left of the screen, right? I like the idea

Though I think you should also be able to tell if other players are invincible. Maybe rainbow colored tees although that may be a too much visual noise.

**Comment by BlaiZephyr** [comment]
oh i like this! i think we could just render an "invincible" text, given we do the same for super
grafik

**Comment by Jupeyy** [comment]
Perma confetti

**Comment by timakro** [comment]
I've added some HUD icons for super and invincible.
image
Looks like this in game:
image

**Comment by timakro** [comment]
Not sure if these icons should go into the row with the "capabilities" like endless hook, unlimited jumps or in the row with the team mode and freeze indicators like practice mode, deep freeze. Right now I've added them to the capabilities row.

**Comment by timakro** [comment]
As for showing that other players are invincible maybe it is not that important. But I'm not happy with the current suggestions, I think rainbow tees are ugly and perma confetti is distracting.

**Comment by BlaiZephyr** [comment]
>But I'm not happy with the current suggestions, I think rainbow tees are ugly and perma confetti is distracting.

what about mine :(

**Comment by timakro** [comment]
> what about mine :(

The part where it says "super" in your screenshot is where the team name goes. That's because when you are super you are in a special team (team 64) that allows you to interact with players of all teams. Invincible mode doesn't have that, players stay in their regular team. So putting it there wouldn't really work.

**Comment by timakro** [comment]
Okay, I think I am mostly happy with the state of this PR.

Doors, draggers, plasma turrets, and freeze bullets are not disabled in invincible mode right now, but those things are used so rarely in modern maps that I'm not sure if it's worth implementing.

The star HUD icons could maybe fit a little bit better with the style of the other icons but I think this is the end of my graphics skills.

As for indicating that other players are invincible/super: I'm not sure how to implement a shiny/sheen effect on the player skin; I think this would at least require a off screen buffer to render the tee to first but I'm not sure the graphics APIs exist for that. And I'm not really satisfied with the other proposed ideas. So I would be willing to live it without any visual indication.

What do you think?

**Comment by timakro** [comment]
In a discussion on Discord some people were against adding more HUD icons. By visually changing the player skin we could indicate both to the player itself and to other players that they are invincible, eliminating the need for more HUD icons. People really seemed to like the "minecraft item shine" idea but we don't know how to implement it.

**Comment by timakro** [comment]
I removed the HUD icons and added a sparkling trail to invincible tees.

[Screencast From 2024-10-04 19-04-40.webm](https://github.com/user-attachments/assets/3f828773-34a8-413d-8f2b-55afc85e2e80)

**Comment by timakro** [comment]
Can we get this merged?

**Review by def- — APPROVED** [review]

**Comment by def-** [comment]
Can we get rid of super?

**Comment by ewancg** [comment]
> I removed the HUD icons and added a sparkling trail to invincible tees.

I think this is a much better idea than the HUD state (many people such as myself have all the symbolic HUD elements off). The icon that you made for it made me giddy when I first saw it, and I still thought it was very tasteful.
Randomized per-particle decay time within a 0.5 second range or so could be fun. Having fewer sparkles and a lesser opacity for the particles themselves might make the animation less distracting but still entirely noticeable.

> Can we get rid of super?

I don't know who currently uses super, let alone who uses it on a non-customized version of DDNet. Within official DDNet & KOG servers it's probably just disabled for moderators, so I imagine the only people who removing super would affect are  a). test DDRace servers and  b). very small third party servers

**Comment by timakro** [comment]
> Having fewer sparkles and a lesser opacity for the particles themselves might make the animation less distracting but still entirely noticeable.

I found that even right now it can be hard to notice against light backgrounds. And my impression was that the slower spawn rate of the freeze particles only works there because we have the ninja skin as primary indication and the particles are only secondary. The sparkle particles are special because they grow in size. Most if not all other particles shrink over time. I found that this really helps to make it look like a sparkle but combined with the increasing transparency it means that they can be hard to see because they are small at the start and transparent at the end. I invite you to play around with the parameters yourself. I agree that it can be improved to be more readable and less distracting.

> Can we get rid of super?

Dou you think we should add immunity to draggers, doors, freeze bullets or anything else I missed before removing super? My stance is still that these are used so rarely that it's unnecessary but others might feel different.

**Comment by sjrc6** [comment]
I strongly disagree that this is a replacement for super, and that super should be removed. This currently is lacking many features that super has which are probably useful for testers.

**Comment by BlaiZephyr** [comment]
> Can we get rid of super?

maybe this is a question that we want some tester's to answer on, given they're practically the only people using it on official servers.

**Comment by ChillerDragon** [comment]
Can we get the mod relevant label here please? See #7895

**Pull request merged**
