### PR TITLE
Don't register integration test servers

### PR DESCRIPTION
**Pull request by def-**
Also print out more of the diff

Should help with debugging sporadic failures like https://github.com/ddnet/ddnet/runs/7058704316?check_suite_focus=true

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by C0D3D3V** [comment]
Btw. I just noticed that in the default config `auto_exec.cfg` is `sv_register 0` set. Does this file not get copied in the build data directory so that the server should use it. This is not only for the CI interesting, but also for local builds in a build directory.

**Comment by def-** [comment]
It's part of data dir, so it should be copied but is actually not. Let me fix.

**Comment by Chairn** [comment]
Can we also copy `*.supp` files into build dir?

**Comment by Learath2** [comment]
Should they maybe register on a local master so that part also gets covered
by the integration test?

**Comment by def-** [comment]
That doesn't fix the timing problem of when the server responds. Maybe in a separate change.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
