### PR TITLE
DDNet Tutorial

### PR DESCRIPTION
**Pull request by timakro**
**Code reviews are very much appreciated!**

<h1 id="how-it-works">How it works</h1>

When a client is started for the first time the following steps are happening.

1. The player is asked for his language.
step1
2. A short explanation of DDNet is shown to the player.
step2
3. The player is asked to adjust some graphic settings and choose a nickname.
step3
4. A serverbrowser listing all available tutorial servers is shown to the player. The client is displaying servers from the `ddnet-server.json` file, which are listed under the gametype `Tutorial` there. Here I'm hosting a server by myself.
step4

When a player connects to a tutorial server his client language is sent to the server automatically via a chat command `/lang LANGUAGE`. In case this language is not available for the tutorial, the player is asked to select another language manually. `/lang` lists all available languages and `/lang LANGUAGE` selects a language.
screenshot

After successfully selecting a language the player is moved from the spectators to a team only for himself. He spawns inside an info tile. Info tiles are placed in the tune layer. When the player stands inside an info tile a broadcast with text out of a text file is shown to him. On tutorial servers broadcasts that don't fit in one line are automatically wrapped by the client. The line number of the text file depends on the number of the tune zone that is configured for the info tile. The text file is chosen based on the language the player selected.
screenshot-1

The first info tile will explain to the player how to walk left and right for him to get to the next info tile. Shortly after the start line is explained to the player using an info tile and there is a real start line in the map for the player to try it out. After the player learned the basics of movement he is taught how to connect a dummy. For the purpose of the tutorial the dummy will spawn next to him. Further info tiles explain to the player that he now is his dummy and how to hook and move his real player around. Later it is shown how to switch between the dummy and player and some very easy two player parts can be built. In the end info tiles explain the finish line and the player can cross it and gets a real rank on the map. `/points`, `/top5`, `/rank`, etc. are explained. Crossing the finish line also causes the same effect as pressing the skip tutorial button instead of joining a tutorial server: The next time the client is started the introduction process won't be shown again.

I also changed some default settings to make DDRace playable without having to go through the settings menu before.

<h2 id="changes-to-the-tune-layer">Changes to the tune layer</h2>
Currently every index in the tune layer (except 0) is working as a tune zone. Because I'm using another tile of the tune layer now I changed it so that only index 68 (the one marked in the entities) is working for tune zones. heinrich5991 is checking all the released maps for tune tiles with a different index than 68. It has been confirmed that there are no maps released on DDNet using indexes other than 68 and 0 in the tune layer.

<h1 id="todo">TODO</h1>

<h2 id="map">Map</h2>
The most important part is obviously creating the map, nobody is currently working on that. Help is needed here!

<h2 id="translations-in-the-client">Translations in the client</h2>
All translations in this example file are needed: <a href="https://github.com/ddnet/ddnet/files/785089/german_translation.txt">german_translation.txt</a>

Please send me the translations in the exact format of the example file if you want to do a translation of the languages listed below. Try to keep the translations short so there is enough space in the GUI to display them. You can have a look at the screenshots above to get a feeling for the amount of space you have. You will get credits in the language file like <a href="https://github.com/ddnet/ddnet/blob/master/data/languages/italian.txt#L9">here</a>. You can write a mail to tim@timakro.de, <a href="https://forum.ddnet.tw/memberlist.php?mode=viewprofile&u=52">write a PM on the DDNet forum</a> or comment on this PR.

Languages missing:
* belarusian Беларуская
* bosnian Bosanski
* brazilian_portuguese Português brasileiro
* bulgarian Български
* czech Česky
* danish Dansk
* dutch Nederlands
* finnish Suomi
* french Français
* hungarian Magyar
* italian Italiano
* japanese 日本語
* korean 한국어
* kyrgyz Кыргызча
* norwegian Norsk
* persian Persian
* portuguese Português
* romanian Română
* russian Русский
* serbian Srpski
* simplified_chinese 简体中文
* slovak Slovensky
* swedish Svenska
* traditional_chinese 繁體中文
* turkish Türkçe
* ukrainian Українська

<h2 id="translations-for-the-info-texts">Translations for the info texts</h2>
The info texts are not complete yet, information on how to contribute will follow later.

### CODE REVIEW

**Comment by savander** [comment]
Polish translation
[polish_translation.txt](https://github.com/ddnet/ddnet/files/737636/polish_translation.txt)

**Comment by timakro** [comment]
Thanks!

**Comment by savander** [comment]
I guess, it's 2017 not 2016 :D

**Comment by timakro** [comment]
Darn it, always takes me a month or two to catch up with the date ^^
Anyways, fixed it.

**Comment by necropotame** [comment]
I like the idea of info tile. This could be used in regular map as well.

For the language, it should be a part of the protocol (like player info). This is very important for the server to know the language of the player in order to send localized text. And this should be transparent for the player (client language should always be the same as the server language).

**Comment by Wuzzy2** [comment]
Your German translation had some grammar issues (commas, imperative, Denglisch), I fixed them for you:

```
Welcome to DDraceNetwork
== Willkommen im DDraceNetwork

DDraceNetwork (DDNet) is an actively maintained version of DDRace, a Teeworlds modification with a unique cooperative gameplay. Help each other play through custom maps. All ranks made on official servers are available worldwide and you can collect points!
== DDraceNetwork (DDNet) ist eine stetig weiterentwickelte Version von DDRace, einer einzigartigen kooperativen Teeworlds-Modifikation. Bewältige vielfältige Maps im Team und sammle Punkte. Alle Ränge, die auf offiziellen Servern erzielt wurden, sind weltweit verfügbar.

Adjust those settings for the best experience on your system.
== Pass diese Einstellungen an dein System an.

Borderless window
== Rahmenloses Fenster

Your nickname is displayed ingame, you can change it at any time.
== Dein Spitzname wird im Spiel angezeigt, du kannst ihn jeder Zeit ändern.

Select a server with a low ping (latency)
== Wähl einen Server mit einer niedrigen Latenz (Ping)

Start tutorial
== Einführung starten

Skip tutorial
== Einführung überspringen
```

**Comment by heinrich5991** [comment]
Thanks for taking the time to try to improve the translations.

I think the "e" at the end of an imperative is okay, see e.g. [Duden on "anpassen"](https://www.duden.de/rechtschreibung/anpassen). I think the comma between "einzigartig" and "kooperativ" is mandatory, as "einzigartig" does not refer to "kooperativ".

**Comment by Wuzzy2** [comment]
Canoo.net on “anpassen”:
http://canoo.net/inflection/anpassen:V:haben

Seems both are OK. xD
OK with your comma argument (sorry, my fault).

**Comment by rffontenelle** [comment]
Are the translation still being accepted? Here is my contribution: [brazilian_portuguese_translation.txt](https://github.com/ddnet/ddnet/files/2308289/brazilian_portuguese_translation.txt)

**Comment by timakro** [comment]
Thank you, added your translation in [this commit](https://github.com/timakro/ddnet/commit/b8dd0b13d6aea283ae0accda953c01ae3bcc08ac). Currently the state of this project is that I don't know if a map was finished and there was no feedback if people like the idea/implementation. It certainly is kind of hacky in multiple ways. Now with the new ability to add custom network messages this could be implemented cleaner.

**Comment by fokkonaut** [comment]
Any progress?

**Pull request closed without merging**
