### PR TITLE
Fix physics change by weak hook fix (fixes #5769)

### LINKED ISSUE #5769: `sv_no_weak_hook_and_bounce 1` causes critical physics changes
@Jupeyy
it's probably more than just shotgun strength

edit: grenade strength aswell (dont mind the different config var on grenade video, its just on my srv)

https://user-images.githubusercontent.com/35420825/186419628-1be63dd8-b7cd-4284-afbc-c60ba088580f.mp4

https://user-images.githubusercontent.com/35420825/186444883-9ac6bbef-0fc4-49c9-91f1-568a06f3825c.mp4

### PR DESCRIPTION
**Pull request by fokkonaut**
fixes #5769

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Ping @fokkonaut

**Comment by heinrich5991** [comment]
Status: Waiting for author.

The function name `PreTick` sounds very misleading. It's only called if `g_Config.m_SvNoWeakHookAndBounce` is set. Perhaps rename it or call it regardless of that config variable.

**Comment by fokkonaut** [comment]
That belongs to another PR. Anyways, we could also just adapt to the way simpler way of 0.7 that doesnt break anything, since bounces are not fixed anyways.

**Comment by fokkonaut** [comment]
@heinrich5991 pushed something here, ready now

**Pull request merged**
