### PR TITLE
Some osx cleanup

### PR DESCRIPTION
**Pull request by Learath2**
@def- you'll need to build compiler-rt on your osxcross too, but as far as I could test it all works

### CODE REVIEW

**Comment by def-** [comment]
Do I need to rebuild the libs with 10.9 too?

Should this fix the macos central build?

**Comment by Learath2** [comment]
I'd just rebuild everything with 10.9 that's going to be our new minimum version but it shouldn't be necessary(tm)

It doesn't fix the CI build, I couldn't really look into that one :/

**Comment by heinrich5991** [comment]
bors r+

Thanks for working on this. :)

**Comment by heinrich5991** [comment]
bors retry

**Comment by heinrich5991** [comment]
bors retry

**Pull request merged**
