### PR TITLE
Extend antibot interface

### PR DESCRIPTION
**Pull request by heinrich5991**

### CODE REVIEW

**Comment by def-** [comment]
What if the shared lib doesn't have these functions? Do we handle this or does this mean that the antibot shared lib has to be updated at the exact same moment as the server executable?

**Comment by Learath2** [comment]
We don't handle it and neither would the dynamic linker, so yes this needs to be a simultaneous upgrade. However old servers that can't be restarted should be fine because the library should be loaded in memory.

**Comment by def-** [comment]
Fine from my side

**Comment by heinrich5991** [comment]
@Learath2 made something better.

**Pull request closed without merging**
