### PR TITLE
Check whether using a C header trips up clang-tidy

### PR DESCRIPTION
**Pull request by heinrich5991**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
From https://github.com/ddnet/ddnet/pull/8310#discussion_r1610799726, @ChillerDragon:
> btw the whole script can be replaced with a clang check :D
>
> https://clang.llvm.org/extra/clang-tidy/checks/modernize/deprecated-headers.html

Doesn't seem to be the case, we already activate that check:

https://github.com/ddnet/ddnet/blob/60fb40676a34146a188a40eaa1754de92da4b6c1/.clang-tidy#L55

**Comment by ChillerDragon** [comment]
I use clang 19 tooling locally. And clangd keeps warning me. Maybe math.h is also cursed because there is also math.h in the codebase.

**Comment by ChillerDragon** [comment]
image

**Comment by ChillerDragon** [comment]
https://github.com/ChillerDragon/ddnet/actions/runs/9217424960/job/25359369970

```
/home/runner/work/ddnet/ddnet/src/game/client/components/scoreboard.cpp:18:10: error: inclusion of deprecated C++ header 'stdio.h'; consider using 'cstdio' instead [modernize-deprecated-headers,-warnings-as-errors]
#include <stdio.h>
         ^~~~~~~~~
         <cstdio>
```

https://github.com/ChillerDragon/ddnet/commits/test_includes/

**Comment by ChillerDragon** [comment]
Can we close this pr?

**Comment by ChillerDragon** [comment]
This can be closed.

**Comment by heinrich5991** [comment]
Sorry and thanks.

**Pull request closed without merging**
