### PR TITLE
Option to remove weak hook & bounce

### LINKED ISSUE #5641: Add server-option to remove weak-hook for poor KoG-enjoyers
Would especially be a great addition to trashmap, which is also used by KoG-mappers.

### PR DESCRIPTION
**Pull request by Jupeyy**
Fixes #5641 
server side only

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Could this be sent to the client so it can theoretically know how to predict correctly?

**Comment by fokkonaut** [comment]
Can we just name it sv_weak_hook_bounce and set it to 1 by default, and also allow it as CFGFLAG_GAME to be set by a map to 0?

**Comment by fokkonaut** [comment]
https://github.com/ddnet/ddnet/pull/5642/files#diff-95a9207711f0fa572be4148ea6239216afd4ff86cfbb4e8510463ad21bba2f12R67
please change it to 8

**Comment by fokkonaut** [comment]
Well, anything is better than `NO_WEAK_STRONG_AND_BOUNCE`, because that just sounds confusing. Let's just call it `sv_strong_hook` and `GAMEINFOFLAG2_STRONG_HOOK`, so that the flag only gets sent when we actually want strong hook for everyone + it has a fitting name. For me, strong hook obviously includes the bouncing, when done correct, because that's basically a part of the strong hook, which then everyone has.

**Comment by heinrich5991** [comment]
The names don't really matter, do they?

**Comment by fokkonaut** [comment]
I dont see a reason to change it later, when we can just think about a good naming before? Something that really identifies what it is?
Also, why do you name your clientside variable `m_NoWeakHookAndBounce `, while the flag to set it is named `NO_WEAK_STRONG_AND_BOUNCE `, and the serverside option is named `sv_strong_hook_and_bounce`. 3 names, for one thing?
Just adapt to one, which is probably the best to go with the serverside config name.

**Comment by fokkonaut** [comment]
It's not obvious, since I asked 3 times now and gave ideas on what to rename it, and you simply said you dont want to rename it to any of those. Keep your personal issues out of GitHub, please.

**Comment by fokkonaut** [comment]
You just talk a lot of nonsense. Instead of talking normal and discussing, you come up with stuff like this.

**Comment by fokkonaut** [comment]
Also, its simply not obvious from the conversation. Strong is often used as a word for strong hook, and since your fix also goes for the bouncing part, it would indeed make sense to call it like that. Sometimes you just have to think more, but instead you make up something and start a very unpolitical conversation on a place like Github.

**Comment by fokkonaut** [comment]
Completely out of context, but okay. It doesnt matter what it was, but how you act on it. Btw, could you please also change the GAMEINFO_CURVERSION to 8, as I suggested before?

**Comment by Learath2** [comment]
Should we somehow make this the new default for new maps? Maybe a flag in the map format.

**Comment by heinrich5991** [comment]
> Should we somehow make this the new default for new maps? Maybe a flag in the map format.

I'd move this to separate issue, this is just a simple PR.

**Comment by heinrich5991** [comment]
In order to not increase the amount of physic instances we have to support forever, I think we should add a check that disallows this for new maps on DDNet.

@Patiga Can your map library do something like this?

**Comment by def-** [comment]
Sounds useful for testing maps for KoG. Let's get this in and as @heinrich5991 suggested not allow it for official DDNet maps (for now?)

**Pull request merged**
