### PR TITLE
Added Copy & Paste Beside UiServerAddress

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by def-** [comment]
I think a general support for ctrl-c, ctrl-v in all text fields would be better.

**Comment by GoJEGrEEN** [comment]
yes sure but what about paste ip address ? I don't want write ip in chat I just click C button and I can paste it in chat don't need close and open menu , just select a server and click C button http://image.noelshack.com/fichiers/2016/18/1462530378-screenshot-2016-05-06-14-36-34.png

**Comment by heinrich5991** [comment]
Thanks for your pull request. @def- suggests that a more general solution to this problem might be more helpful: Being able to press ctrl-c, ctrl-v in every text field.

For your use case it would be: Click the address text field, press ctrl+c, press enter to open the chat, press ctrl+v to paste.

**Comment by def-** [comment]
Thanks to this I notice we already have ctrl-c ctrl-v in every editbox: https://forum.ddnet.tw/viewtopic.php?t=3619

**Pull request closed without merging**
