### PR TITLE
Use fewer threads on 32-bit to save memory

### PR DESCRIPTION
**Pull request by Jupeyy**
Guess we should still let eeetadam test this

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
s/less/fewer/ ;)

Should we include this in 16.0?

**Comment by Jupeyy** [comment]
> s/less/fewer/ ;)
> 
> Should we include this in 16.0?

if it works yes, if not no xd

**Comment by def-** [comment]
According to eeetadam it doesn't crash now, but just black output in video.

**Comment by Jupeyy** [comment]
looks like that guy generally cannot read data from the GPU.

His screenshots are also black

**Comment by def-** [comment]
So my preference would be to include this in 16.0.2 and reenable win32 video renderer again.

**Comment by Jupeyy** [comment]
Yes, we also managed now to get it working with a very old mesa software renderer, the newer ones apparently expect a vulkan driver, even if it's not used

**Pull request merged**
