### PR TITLE
SDL 2.0.10 -> 2.0.8 (fixes #1997)

### LINKED ISSUE #1997: SDL 2.0.9 and higher run extremly bad on Windows
So while i was on Windows now, I noticed, that SDL 2.0.9 and higher run insanly bad, and i really mean around 100% worse than 2.0.8.

I used the latest client and run with 2.0.8, 2.0.9 and 2.0.10 from here(64 bit):
https://libsdl.org/release/

I would really suggest to downgrade to 2.0.8 if we don't need features from higher versions.
Btw you can also see the difference in wine

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Learath2** [comment]
Is changing the bundled lib enough? Kinda feels like we are missing something :D

**Comment by def-** [comment]
Yes, tried it and works. I checked the SDL_Events.c and couldn't find any other related change other than the runtime-enabled event logging.

**Comment by def-** [comment]
Would like to release a new DDNet version with this soon.

**Pull request merged**
