### PR TITLE
Limit zooming out further (fixes #2497)

### LINKED ISSUE #2497: Crash in zoom out
Happened to rezee during Tournament

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Why did you choose 30?

Not sure what value is correct here. I think some people zoom out crazy far.

**Comment by def-** [comment]
That's where it starts lagging for me.

**Comment by Learath2** [comment]
@def- even with the gl3 renderer?

**Comment by def-** [comment]
Ah no, with gl3 I can zoom much further.

**Comment by heinrich5991** [comment]
That's 23 zoom steps without OpenGL3 and 28 with OpenGL3. I get 30 FPS on zoom level 28 with OpenGL3.

**Comment by def-** [comment]
I get 10 fps and already felt quite laggy, but I'm also just using an integrated GPU.

**Comment by heinrich5991** [comment]
Okay, let's go with these limits.

Can you modify the check so that it checks whether OpenGL3 is enabled and not whether it will be enabled on next start? `Graphics()->IsBufferingEnabled()` returns that for example (which kind of makes sense; enable larger zoom when buffering is enabled, which improves performance) or by providing another getter for that value.

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
