### PR TITLE
Handle hookthrough shortcut as hookblocker too

### PR DESCRIPTION
**Pull request by 12pm**
If someone manages to map it on its own

### CODE REVIEW

**Comment by def-** [comment]
Are we sure this doesn't change any existing maps?

**Comment by 12pm** [comment]
@heinrich5991 could you check if this exists in any map?

**Comment by heinrich5991** [comment]
I prefer #2031 over this.

**Comment by heinrich5991** [comment]
I don't want to assign this tile another meaning, I prefer #2031 over this.

**Pull request closed without merging**
