### PR TITLE
Allow joining and inviting others via Steam friend list

### LINKED ISSUE #2642: Use Steam API to provide links to join to another player
We already support running `DDNet ddnet:ger.ddnet.tw:8303`.

@heinrich5991 recently added Steam API support, so I think this can be extended more easily now: https://github.com/ddnet/ddnet/pull/2615

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #2642.

### CODE REVIEW

**Comment by Learath2** [comment]
Huh, I didn't think this was possible without the gameserver part of the steamapi, nice find.

**Comment by BannZay** [comment]
Should not we check player team to say that they are playing togather?

**Comment by BannZay** [comment]
and should they maybe auto join team on "Join friend" ?

**Comment by heinrich5991** [comment]
Sounds a lot harder, we don't have the infrastructure in place for this. Feel free to create an issue for this.

**Comment by def-** [comment]
Very cool. Did you test this already or should we do a small test tomorrow?

bors r+

**Comment by heinrich5991** [comment]
@def- Tested all interactions I could think of, gave the binary to a couple of friends.

**Comment by Learath2** [comment]
Couple Qs:
- Does it work with an instance already working?
- Does it bypass the disconnect warning if you click join someone but you are in the middle of a race?
- Does it reconnect you if you click join but you are already in the same server?

**Comment by heinrich5991** [comment]
> * Does it work with an instance already working?

Yes

> * Does it bypass the disconnect warning if you click join someone but you are in the middle of a race?

Yes.

> * Does it reconnect you if you click join but you are already in the same server?

Yes.

**Comment by Learath2** [comment]
I think the last two should probably be made into "No"s

**Pull request merged**
