### PR TITLE
Fix colored speed values after connecting to a server

### LINKED ISSUE #8814: Speed in HUD is sometimes red/green with no speed
No idea how to reproduce, but I was just standing still while this happened.

image

### PR DESCRIPTION
**Pull request by MilkeeyCat**
The way to reproduce this is have some speed and disconnect. After joining the tee will have old speed values.

Fixes #8814

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by BlaiZephyr** [comment]
implements suggestion of: #8911 to use `ESpeedChange::NONE;` - can be closed if this gets merged.

**Comment by furo321** [comment]
I don't think this fixes #8814. That issue can occur whenever and not just when you joined.

**Comment by MilkeeyCat** [comment]
When did it also happen to you?

**Comment by furo321** [comment]
> When did it also happen to you?

It says in the issue, it happened while standing still after playing for a while.

**Comment by MilkeeyCat** [comment]
> > When did it also happen to you?
> 
> It says in the issue, it happened while standing still after playing for a while.

What map were you playing?

**Comment by furo321** [comment]
I got a demo of it, it was green for me in game at the 1:36 mark. The HUD seems to always be green in the demo when Y is 0.00, but that wasn't the case in game. Probably because demos are 25 ticks, but it may help you narrow the issue regardless. This was on the map `TelEdge`

[speed-hud-demo.zip](https://github.com/user-attachments/files/17005057/speed-hud-demo.zip)

**Comment by MilkeeyCat** [comment]
I could reproduce the wrong color for speed when you are ingame, to reproduce change `TICK_SPEED` to 500 and build a server. After that press move buttons very quickly and eventually you will get wrong colored speed value.

**Review by Robyt3 — APPROVED** [review]
Seems good. The previous code made the color only update if the text container was also updated I guess.

**Review by def- — APPROVED** [review]

**Pull request merged**
