### PR TITLE
Add regional rankings to /top5team

### PR DESCRIPTION
**Pull request by KebsCS**
Feature requested on discord
image

image

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [x] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by KebsCS** [comment]
> The output is pretty huge with regional rankings, especially if teams have many people

I get that, but most maps have teams with only 2 people, especially on top of the leaderboards. Users know they'll get a larger output on the rare maps that require bigger teams. Plus, the output was already large before, and the regional rankings only add 3 more records with 4-6 names per line at most, so the difference is minimal. If it's still a big issue, is there anything specific I could change to make it work better?

**Review by def- — APPROVED** [review]

**Comment by BlaiZephyr** [comment]
maybe seperate it to smth like /top5region ? this way /top5team's output isn't unneccessarily huge while still having a proper way of displaying it

**Comment by KebsCS** [comment]
Would it be fine to add a new command, `/top5teamregion`, while keeping `/top5team` as it is? @def-

**Comment by SuadoCowboy** [comment]
dunno if my opnion counts but i think that the region ranks being on /top5team is consistent with the other commands and output size was never rlly a big deal for no one i believe

**Comment by KebsCS** [comment]
Resolved merge conflicts, I don't know why it requested a review from Patiga 

Also this feature request got 10 approval reactions on discord in 2 days. I don't know what other opinions we need about it here

**Review by def- — APPROVED** [review]
Let's see how it goes

**Pull request merged**
