### PR TITLE
Fix doors not resetting on restart on solo server

### PR DESCRIPTION
**Pull request by Zwelf**

### CODE REVIEW

**Comment by def-** [comment]
Have you tested that this works? Looks fine to me.

**Comment by Zwelf** [comment]
Tested it on RocketIsKey for one door.

**Comment by Zwelf** [comment]
Team are reset too often now. Didn't tested loading tee.

**Comment by Zwelf** [comment]
Should work now (tested both cases now, killing and save/load). As a side note: Maybe it would be cleaner if all switchers always reset when teamstate is set to TEAMSTATE_OPEN (e.g. in onChangeTeamState).

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
