### PR TITLE
Proposition: Extend the protocol using NETMSG_NULL

### PR DESCRIPTION
**Pull request by Learath2**
NETMSG_NULL is currently unused.

### CODE REVIEW

**Comment by heinrich5991** [comment]
We should probably tread carefully here. ^^

I'd propose using a four-byte identification instead of a TW-encoded integer.

**Comment by east** [comment]
The extended protocol msgid unpack is missing on client-side.

@heinrich5991 Why would you use a four-byte identification instead? I don't think we would ever collide with other client-mods there.

**Comment by heinrich5991** [comment]
@east Basically so we don't clash with later versions of the same protocol.

E.g. if another client adopts this model, then integers are hard to distribute, it's unclear who owns which ranges.

If we use four bytes, it's still somewhat unclear, but at least everyone just tries to use bytes that are somehow identifying, like in this case maybe "leaa", "leac", etc., hopefully reducing collisions...

Perhaps we should use UUIDs instead. ^^ (<-- actually serious proposal).

**Comment by east** [comment]
@Learath2 
There needs to be atleast a null byte at the beginning because of NETMSG_NULL.

**Comment by heinrich5991** [comment]
The null byte is already unpacked at that point:

    int Msg = Unpacker.GetInt();

**Comment by east** [comment]
Okay, right

**Comment by heinrich5991** [comment]
So apart from the question whether we should rather use UUIDs, this is done, right?

UUIDs are basically 16 bytes, generated according to a known policy, which probably eliminates duplicates.

4 bytes are obviously shorter, thus consume less traffic, but the chance of collisions is higher.

What do you think about UUID vs 4 bytes?

**Comment by Learath2** [comment]
This isnt incomplete at all. I believe it can just be merged when needed. Its literally a 2 line change to switch to 16 byte uuids instead.

**Comment by Learath2** [comment]
Obsoleted by #615.

**Pull request closed without merging**
