### PR TITLE
Update mapres by mind

### PR DESCRIPTION
**Pull request by def-**
Adapted from 0.7 for new renderer. Not sure if this makes sense :D

### CODE REVIEW

**Comment by def-** [comment]
I personally can't judge if this makes sense. @Soreu @Jupeyy ?

**Comment by Jupeyy** [comment]
It will look better, if we keep the new renderer, because the borderfix patch isn't in it anymore.

Lets just wait if we keep the new renderer

**Comment by Ekidoxx** [comment]
If we do keep the renderer (I hope we do), then it's really good idea to update the mapres - lots of maps will just look better due to removed effect of borderadd

**Review by heinrich5991 — APPROVED** [review]
There are some actual changes in [desert_main](https://github.com/ddnet/ddnet/commit/f0971f51e07958c38ed1007b3afe26bd39a45254?short_path=564b880#diff-564b8803a054721c518db51907350b68) (three collision tiles not aligning with the tile boundary anymore) and [grass_doodads](https://github.com/ddnet/ddnet/commit/f0971f51e07958c38ed1007b3afe26bd39a45254?short_path=ad269c1#diff-ad269c1444070cb01d15ca40f1c2a7b8) (fence type changed), but I think these are minor enough.

Thanks deen, thanks mind. :)

bors r+

**Pull request merged**
