### PR TITLE
Check if swapchain can be created, e.g. if windows starts minimized

### PR DESCRIPTION
**Pull request by Jupeyy**
@Robyt3 try this

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
Doesn't seem to be enough. I still get a black screen with these changes.

**Comment by Jupeyy** [comment]
> Doesn't seem to be enough. I still get a black screen with these changes.

but that's exactly the problem, without some SDL event the backend can't know when to recreate the swap chain.

blackscreen is better than before tho isnt it?

**Comment by Robyt3** [comment]
> blackscreen is better than before tho isnt it?

No, it's exactly the same as before. With the combined changes from yesterday the client seems to fallback to OpenGL when starting minimized, which is only a minor improvement.

**Comment by Jupeyy** [comment]
well to say it different:
yesterday you got validation errors, is this still the case?

**Comment by Robyt3** [comment]
This is the code we had yesterday:

```patch
diff --git a/src/engine/client/backend/vulkan/backend_vulkan.cpp b/src/engine/client/backend/vulkan/backend_vulkan.cpp
index c895739b0..b87ace0c6 100644
--- a/src/engine/client/backend/vulkan/backend_vulkan.cpp
+++ b/src/engine/client/backend/vulkan/backend_vulkan.cpp
@@ -2338,7 +2338,10 @@ protected:
 			{
 				dbg_msg("vulkan", "recreating swap chain requested by user (prepare frame).");
 			}
-			RecreateSwapChain();
+			if(RecreateSwapChain() != 0)
+			{
+				return PureMemoryFrame();
+			}
 		}
 
 		auto AcqResult = vkAcquireNextImageKHR(m_VKDevice, m_VKSwapChain, std::numeric_limits<uint64_t>::max(), m_vSigSemaphores[m_CurFrames], VK_NULL_HANDLE, &m_CurImageIndex);
@@ -4130,6 +4133,8 @@ public:
 		uint32_t SwapImgCount = GetNumberOfSwapImages(VKSurfCap);
 
 		m_VKSwapImgAndViewportExtent = GetSwapImageSize(VKSurfCap);
+		if(m_VKSwapImgAndViewportExtent.m_SwapImageViewport.width == 0 || m_VKSwapImgAndViewportExtent.m_SwapImageViewport.height == 0)
+			return false;
 
 		VkImageUsageFlags UsageFlags;
 		if(!GetImageUsage(VKSurfCap, UsageFlags))
@@ -5516,6 +5521,17 @@ public:
 		int Ret = 0;
 		vkDeviceWaitIdle(m_VKDevice);
 
+		VkSurfaceCapabilitiesKHR VKSurfCap;
+		if(!GetSurfaceProperties(VKSurfCap))
+			return -1;
+
+		auto Caps = GetSwapImageSize(VKSurfCap);
+		if(Caps.m_SwapImageViewport.width == 0 || Caps.m_SwapImageViewport.height == 0)
+		{
+			m_RenderingPaused = true;
+			m_RecreateSwapChain = true;
+		}
+
 		if(IsVerbose())
 		{
 			dbg_msg("vulkan", "recreating swap chain.");
@@ -7473,8 +7489,8 @@ public:
 #ifdef CONF_PLATFORM_ANDROID
 			if(!CreateSurface(m_pWindow))
 				return false;
-			m_RecreateSwapChain = true;
 #endif
+			m_RecreateSwapChain = true;
 			m_RenderingPaused = false;
 			if(!PureMemoryFrame())
 				return false;
```

Seems like this only works because it falls back to OpenGL when starting minimized, so that's not much better when it downgrades to OpenGL silently.

**Comment by Jupeyy** [comment]
let's take your patch, not trivial enough

**Pull request closed without merging**
