### PR TITLE
[?] Add condition variables

### PR DESCRIPTION
**Pull request by Learath2**
Not sure if we want this anymore given we have C++11 now. Already had it so wanted to PR it.

### CODE REVIEW

**Comment by H-M-H** [comment]
I think we do not want this but should use those provided by C++11. The thing we might want is some wrapper that takes care of the mutex required for C++11 condition_vars.

**Comment by Learath2** [comment]
Thought about that as well but I think we shouldn't "take care" of the mutex really. As seen in this case e.g. it's useful to keep the mutex separate.

**Comment by H-M-H** [comment]
I thought mostly about managing lifetime of the mutex, I guess that should be fine ?

**Comment by def-** [comment]
Windows build fails

**Comment by Learath2** [comment]
Apparently WinAPI condition variables are only available on >= Vista. So we better use C++11 ones.

**Pull request closed without merging**
