### PR TITLE
Reset color in RenderLoading

### PR DESCRIPTION
**Pull request by Jupeyy**
Trying to fix a color bug during initialization for MilkeeyCat

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by Robyt3 — COMMENTED** [review]
It doesn't seem to be caused by `RenderLoading`, at least not with the specific settings I use. It can't be reproduced by adding `Graphics()->SetColor(1.0f, 1.0f, 1.0f, 0.5f);` at the end of `RenderLoading` but it can be reproduced by adding this line at the beginning of `CHud::OnInit()`.

I think the correct fix would be to add `Graphics()->SetColor(1.0f, 1.0f, 1.0f, 1.0f);` at the beginning of `CHud::OnInit()`. I think relying on the previous component to reset the color is more error-prone.

**Review by def- — APPROVED** [review]

**Comment by Jupeyy** [comment]
> I think relying on the previous component to reset the color is more error-prone.

Yes, but then we should check all components.
Ultimately we shouldn't use a global state for this, but have some kind of render scope

**Comment by Jupeyy** [comment]
> It can't be reproduced by adding `Graphics()->SetColor(1.0f, 1.0f, 1.0f, 0.5f);` at the end of `RenderLoading`

I checked the code for RenderLoading and it's time based, if it's called or not, so it's _random_ anyway

**Comment by Jupeyy** [comment]
Removing 
```cpp
if(Now - m_LoadingState.m_LastRender < std::chrono::nanoseconds(1s) / 60l)
		return;
```
Let's me reproduce the issue

**Comment by Jupeyy** [comment]
From a quick test it seems to only affect the HUD, but only checked visually not by code

**Review by Robyt3 — APPROVED** [review]
LGTM.

**Pull request merged**
