### PR TITLE
Add buttons for Kill and Pause

### PR DESCRIPTION
**Pull request by def-**
Seems more useful than Spectate and Connect Dummy, both of which are often mistaken by newcomers.
screenshot-20200903@120548

### CODE REVIEW

**Comment by BannZay** [comment]
The overall idea is great but I see some improvements here:
1. Hide menu after player press Pause/Kill/Pause
2. Disable Kill button if you are in pause mode (as it does not work in this case)
3. Make all buttons the same width
4. Render Unpause when you are in pause. (Might be even better to leave pause when ESC pressed for the first time to prevent additional clicks)
5. ? Rename kill to Restart

**Comment by BannZay** [comment]
And Kill Pause does not work when you are in spectator team as well

**Comment by def-** [comment]
> And Kill Pause does not work when you are in spectator team as well

Yeah, that would require https://github.com/ddnet/ddnet/issues/2719

**Comment by def-** [comment]
> Make all buttons the same width

They won't fit on screen in 5:4 resolution then.

**Comment by BannZay** [comment]
> 
> 
> > Make all buttons the same width
> 
> They won't fit on screen in 5:4 resolution then.

Shouldnt we make other buttons smaller?

**Comment by def-** [comment]
All done:
screenshot-20200903@170155
screenshot-20200903@170106

**Comment by heinrich5991** [comment]
@edg-l correctly mentions on Discord that we already have the pause/spec state in the client, via `DDNetPlayer`, in `m_Flags&EXPLAYERFLAG_PAUSED` and `m_Flags&EXPLAYERFLAG_SPEC`.

**Comment by edg-l** [comment]
Maybe make the button a dropdown "Actions"

**Comment by BannZay** [comment]
I`ve found another problem - "Join blue" button does not fit in new layout (1920*1080)

And, to be honest I am not a fun of enlarged menu (in 2 rows). It would be nice to precalculate the available width for buttons to fit them all (they are big enough to be scaled tho)

Button names bit confusing but not sure if we can handle it better.

**Comment by heinrich5991** [comment]
> It would be nice to precalculate the available width for buttons to fit them all

That would make it annoying for translations, and captions in general.

**Comment by def-** [comment]
> I`ve found another problem - "Join blue" button does not fit in new layout (1920*1080)

Fixed

> @edg-l correctly mentions on Discord that we already have the pause/spec state in the client, via DDNetPlayer, in m_Flags&EXPLAYERFLAG_PAUSED and m_Flags&EXPLAYERFLAG_SPEC.

Done.

**Comment by fokkonaut** [comment]
Can we maybe leave the Spectate and Join Game button at the top left? Also not sure about /pause and /spec being a button(?)

**Comment by def-** [comment]
> Can we maybe leave the Spectate and Join Game button at the top left

Done

**Comment by def-** [comment]
Thoughts on getting this in and releasing?

**Comment by def-** [comment]
screenshot-20200904@123159
If we remove the Spec and make Kill & Pause smaller, we can also make it always fit in one line.

**Review by Learath2 — APPROVED** [review]
LGTM

bors r+

**Comment by Jupeyy** [comment]
@def- Unpause only works on ddnet server(not kog or older servers)

**Comment by def-** [comment]
Correct, they should update.

**Pull request merged**
