### PR TITLE
Fall back to Visual Studio 16

### PR DESCRIPTION
**Pull request by def-**
since it seems not all github worflow servers are on VS17 yet

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
Build looks good.

bors r+

**Comment by def-** [comment]
An alternative would be to explicitly specify the windows version, like `os: windows-2022` or `os: windows-2019`, but then we have to keep upgrading that.

**Comment by heinrich5991** [comment]
I like the autodetection better.

**Comment by def-** [comment]
I figured, but in case it causes problems I wanted to note the alternative somewhere :D

**Pull request merged**
