### PR TITLE
Kick people using overlong UTF-8 sequences

### PR DESCRIPTION
**Pull request by heinrich5991**
This works around the bug in older clients (including vanilla) that
interpret those sequences incorrectly.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Thinking about it again, it might be better to just ignore the message. Thoughts? Opinions?

**Comment by def-** [comment]
Yes, I think ignoring it is better than kicking.

**Comment by heinrich5991** [comment]
Now it only ignores the messages.

**Comment by def-** [comment]
Thanks.

**Pull request merged**
