### PR TITLE
Update arabic.txt

### PR DESCRIPTION
**Pull request by Sedonya**
Now I know 99% Arabic

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — CHANGES_REQUESTED** [review]
Trolling?

**Comment by Sedonya** [comment]
What's with the trolling? What did I do wrong? Are you saying I translated it wrong?

**Comment by Sedonya** [comment]
Why dismiss PR as if it would have been translated differently in the future

**Comment by def-** [comment]
Are you familiar with the Arabic DDNet community and the communication they use? If not, this is not useful at all.

**Pull request closed without merging**
