### PR TITLE
Add non-destructive brush drawing

### PR DESCRIPTION
**Pull request by 12pm**
New brush draw mode that doesn't override existing tiles. Empty brush still acts as an eraser. Button and ctrl+d shortcut to toggle it.

### CODE REVIEW

**Comment by def-** [comment]
Sounds a bit unintuitive. What's it used for?

**Comment by 12pm** [comment]
e.g. place tiles around or inside a shape without having to worry about destryoing it. I believe this is really useful for mapping something like gores.

**Comment by 12pm** [comment]
Basically allows you to draw more sloppy

**Comment by def-** [comment]
bors r+
Quite a large change.

**Pull request merged**
