### PR TITLE
Ellipsis at end in scoreboard and hud

### PR DESCRIPTION
**Pull request by def-**
Looks nicer to have consistent length in HUD, more clear that something is cut off with the ellipsis.
screenshot_2022-04-18_12-57-22
Thoughts on kill message?
## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Chairn** [comment]
Fixes https://github.com/ddnet/ddnet/issues/3174

**Comment by Jupeyy** [comment]
how about increase the scoreboard size when its only one tab, looks like there is still plenty of space

**Comment by C0D3D3V** [comment]
It's definitely better than before, but we could really think about giving name displays a maximum width in general,  in kill-messages, in nameplates and in the scoreboard and give everything that's longer a smaller font size instead of cutting them off.

**Comment by def-** [comment]
> how about increase the scoreboard size when its only one tab, looks like there is still plenty of space

In 5:4 there is not much space left.



> It's definitely better than before, but we could really think about giving name displays a maximum width in general, in kill-messages, in nameplates and in the scoreboard and give everything that's longer a smaller font size instead of cutting them off.

I don't like smaller font sizes, I think it looks inconsistent.

**Comment by Jupeyy** [comment]
> In 5:4 there is not much space left.

Depends, generally there is quite a lot space left for a single scoreboard

image


We'd need to consider allowing kill messages and hud overlapping

So the question is what is nicer. The names being cut off, or the scoreboard potentially overlapping with other hud... with chat it already overlapps anyway.

Even if this pr is a small visual improvement (im not against it) it doesn't really help imo. The dots won't make the players with long names more happy ^^

Could also generally decrease the font size, tho the scoreboard looks really empty with few players only, i think with 64 players these long names werent a problem bcs the fontsize shrinks so much right?

**Comment by Jupeyy** [comment]
Well anyway we can discuss that independent of this pr

However, there is still one thing:
Since the ellipsis "wastes" 1 character, it will now render one char less than before.

That might affect ppl, so we should check if the last char could fit and if it does, dont render the ellipsis

**Comment by def-** [comment]
> Could also generally decrease the font size, tho the scoreboard looks really empty with few players only, i think with 64 players these long names werent a problem bcs the fontsize shrinks so much right?

Correct.

**Comment by Jupeyy** [comment]
> I don't think there are such players. It's just an annoying little issue when someone is trolling with long name. Only few character combinations end up too long, none of them natural names.

With one exception: If they have showids on

would affect my name, with and without this patch:
screenshot_2022-04-19_16-32-57

with this patch 2 characters are gone

Anyway i dont really want to hold this feature back. That the name in any combination cannot fit into the scoreboard is smth that generally needs a fix imo, not related to this pr

**Comment by def-** [comment]
Hm, I think it should only put the ellipsis in if the original text doesn't fit. Let me check.

**Comment by def-** [comment]
For me it also doesn't fit currently:
screenshot_2022-04-20_00-34-27

**Comment by Jupeyy** [comment]
Nice name hehe

but as said an example is `WWWWWWWWWii` (i think its resolution dependent, 1280x1024 breaks it for me)

**Comment by heinrich5991** [comment]
Looks generally good.

> but as said an example is `WWWWWWWWWii` (i think its resolution dependent, 1280x1024 breaks it for me)

Have you checked that it actually stays within the box and doesn't slightly over?

**Comment by def-** [comment]
Can reproduce the issue Jupeyy reported. So in general we have to check the total width before. This makes this change quite a bit more expensive, not sure if it's worth it.

**Comment by heinrich5991** [comment]
Conflicts.

I'd be okay with a slightly slower code path for adding more exact ellipses. What do you think, @Jupeyy?

**Comment by Jupeyy** [comment]
I'm also ok with it, dunno how much work it is tho

**Comment by heinrich5991** [comment]
Okay, so this would be good to go. Needs a rebase though.

**Comment by def-** [comment]
Done.

**Pull request merged**
