### PR TITLE
add #ifdef checks around GLEW_VERSION checking

### PR DESCRIPTION
**Pull request by d3fault**
This fixes compilation on Debian Stretch

### CODE REVIEW

**Comment by def-** [comment]
This does not seem like the best way to do this. @Jupeyy Opinions?

**Comment by d3fault** [comment]
I'm not surprised, however it works and seems relatively safe.
Here's the error message I was receiving:
> /home/user/ddnet/src/engine/client/backend_sdl.cpp:3735:5: error: ‘GLEW_VERSION_4_6’ was not declared in this scope

**Comment by Jupeyy** [comment]
just remove 4_6 for now, the other versions exist since over 6 years, so without 4_6 it should be fine on every platform

**Comment by Jupeyy** [comment]
or what is our compile downward compability for linux?

**Comment by d3fault** [comment]
I'm still scratching my head wondering why they thought this form of version checking was a good idea. Presumably 4_6 brings some benefits (otherwise why does it exist)? #ifdefing it out like I did seems better than removing it.

**Comment by Jupeyy** [comment]
im also ok with #ifdef

the reason for this is, to have a strong fallback, bcs with glewexperimental=true, glew will check for major specific functions and then you can tell even in a gl 1.1 context that the GPU the user is using has 4_6 support.

Generally its nice to have a way for higher OpenGL versions, its easy to add some things from e.g. OpenGL 4.5(direct state access) then.

**Comment by d3fault** [comment]
hmm this is my first night using @Jupeyy 's OpenGL changes... and while I do like the visual updates... my screen flashed, for just a second, to mostly black with weird crazy geometric colors (none of which even slightly resembled the game). I've seen similar graphics bugs with dying GPUs

$ lspci
> 00:02.0 VGA compatible controller: Intel Corporation 82Q35 Express Integrated Graphics Controller (rev 02)

**Comment by Jupeyy** [comment]
Can you maybe open the game in terminal and give some output from it?
since thats a pretty old gpu it should stay on GL 1.x probably

**Comment by d3fault** [comment]
> [2020-09-03 00:44:13][sdl]: SDL version 2.0.5 (compiled = 2.0.5)
[2020-09-03 00:44:13][gfx]: Created OpenGL 2.0 context.
[2020-09-03 00:44:13][OpenGL]: Version string: 2.1 Mesa 13.0.6

**Comment by d3fault** [comment]
on the bright side, I'm getting much better fps using your changes :)

**Comment by Jupeyy** [comment]
does the error happen often?
maybe you can run valgrind over it and see if its an error in our code,

else you can just try and see if its a mesa bug

**Comment by Jupeyy** [comment]
https://feedback.wildfiregames.com/report/opengl/device/Intel%28R%29%20Q35

seems like they added 2.1 support in mesa, but on wikipedia its listed as a GL 1.x card (https://de.wikipedia.org/wiki/Intel-3-Serie)

**Comment by d3fault** [comment]
I don't know if it happens often, first night running your changes. I've only seen it happen once so far though and been playing for a few hours. maybe I'll try valgrinding it sometime

**Comment by Jupeyy** [comment]
ok thanks :D

**Pull request merged**
