### PR TITLE
Add address logging server

### PR DESCRIPTION
**Pull request by heinrich5991**
We currently use that on some of the servers, thanks to @H-M-H for trying to upstream it.

### CODE REVIEW

**Comment by Learath2** [comment]
Shouldn't most of this functionality be behind a config option rather then just `CONF_FAMILY_UNIX`?

**Comment by heinrich5991** [comment]
For some reason I thought I had already commented...

It actually is behind a config option: [`sv_conn_logging_server`](https://github.com/ddnet/ddnet/pull/967/files#diff-b823dfdaeaa815f00cea7ad708f4053aR377].

**Comment by Learath2** [comment]
Oh apparently I'm blind. AppVeyor still fails on aio, so does my computer.
bors r+

**Comment by Learath2** [comment]
Oh I doubt bors will succeed with AppVeyor broken though.

**Pull request merged**
