### PR TITLE
Disable OpenGL3 by default

### PR DESCRIPTION
**Pull request by Learath2**
Maybe we could do a release while the OpenGL3 version is getting more thoroughly tested.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Let's ask @def- (https://github.com/ddnet/ddnet/commit/cb00a294b82ec3f275cb00733b8dce91b4875a54).

**Comment by Jupeyy** [comment]
i agree, tho, is there any trouble?
my latest pull request should fix alot of things

**Comment by Learath2** [comment]
Works perfectly on my laptop, even with the weird nvidia optimus on linux setup I have.

**Comment by heinrich5991** [comment]
@def- Assigning you because you initially activated it. @Learath2 complains that "it doesn't work" on his Windows computer. Maybe you could elaborate, @Learath2.

**Comment by Learath2** [comment]
After digging further I've concluded OpenGL is fine but it's @heinrich5991's aio logger that breaks it for my  computer.

**Pull request closed without merging**
