### PR TITLE
Add .clang-format

### PR DESCRIPTION
**Pull request by edg-l**
We should discuss if these rules are good. The ones i added i think are the best and match the current style. (allman)

I didn't add any script, but it would be cool if bors can format after a commit or something.

Here there is a example scripts from clang itself: https://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting

Scoreboard.cpp formatted by clang-format with these settings:
https://hastebin.com/deqabuximu.php
Scoreboard.h: https://hastebin.com/voyeloveya.cpp

### CODE REVIEW

**Comment by def-** [comment]
This has the implication of breaking from Vanilla entirely. Do we want that?

**Comment by def-** [comment]
Also need to add a check to GitHub so that formatting always stays good. Could also look into clang-tidy.

**Comment by Ryozuki** [comment]
> This has the implication of breaking from Vanilla entirely. Do we want that?

https://github.com/ddnet/ddnet/issues/1435#issuecomment-462437849

**Comment by ChillerDragon** [comment]
why not use the format vanilla uses?

**Comment by def-** [comment]
What clang-format style is Vanilla using?

**Comment by Ryozuki** [comment]
This clang format I made tries to adapt to the actual code on ddnet.

**Comment by Learath2** [comment]
I think last time I tried to add a clang-format I couldnt find a setting to
omiy space after for/if/while.

**Comment by Ryozuki** [comment]
omiy? omit? 

```
SpaceBeforeParens: ControlStatements
```
I think space before if statements are good. And so i added it to the clang-format

**Comment by Learath2** [comment]
Maybe you should commit the result of the formatting as well, so we can judge what it looks like.

**Comment by Ryozuki** [comment]
Done

**Comment by def-** [comment]
The main question is whether we want a .clang-format that is as close as possible to the current formatting and thus minimizes the diff size or a .clang-format that is reasonable.

**Comment by Ryozuki** [comment]
I am for updating to a new reasonable format, specially one that allows 

```cpp
void x() {
}
```

Putting all like
```
{
}
```

Is super old fashioned and I dislike it.

**Comment by Learath2** [comment]
I vote for keeping the diff as small as possible as there is no way we all agree on a new style.

**Comment by fokkonaut** [comment]
True, we couldnt agree on a style, also cleaning up the whole code wouls take too long.

**Comment by def-** [comment]
I guess this will make cherry-picking from teeworlds and to ddnet7 harder, so let's not add a .clang-format file for now.

**Pull request closed without merging**
