### PR TITLE
Remove annoying "added option" logging

### PR DESCRIPTION
**Pull request by def-**
Fills our logs all the time

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Learath2** [comment]
I like the idea, but maybe log levels would be more appropriate? Would also
help with the masterserver spam

**Comment by heinrich5991** [comment]
We do have log levels, but the console gets all the log levels.

**Comment by heinrich5991** [comment]
Okay, let's say we go ahead with this. For symmetry, could you also remove the log messages in the success case of `remove_vote` and `clear_votes`?

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
@def- Forgot to push?

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Pull request merged**
