### PR TITLE
Fix weak hooks

### PR DESCRIPTION
**Pull request by Banana090**
Again disappointed in the community, so doesn't care. But here is the working version.
The way it works:
-If you hook someone you gain strong
-If you hook someone while he's already hooking you - you gain weak. And stay weak for this entire hook until you rehook while not being hooked by that person.

Complicated, but the idea is that you're always strong except for the times when two tees hooking each other at the same time. Then someone is weak to simulate current physics behavior so it don't change anything for game world

## Checklist

- Tested the change ingame
- Changed YES physics that affect existing maps <<<<<<<<<<<

### CODE REVIEW

**Comment by def-** [comment]
> Again disappointed in the community, so doesn't care. But here is the working version.

Wait, why do we even do a vote then? :D

**Comment by edg-l** [comment]
close this, as it has been voted no by the community

**Comment by heinrich5991** [comment]
We don't seem to have an issue to talk about this.

Instead of making the UI more complicated as people are asking right now (with the weak-strong-ID), maybe something like this (not necessarily this implementation) would be better.

Changing people's weak-strong-order as they hook is quite ingenious, I hadn't thought about that. Backward compatible and all. Maybe we could add a /weak command for the cases where you need to have weak hook, which removes you from the automated weak-strong rotation.

**Comment by Learath2** [comment]
I think this adds even more hacky complexity to something already insanely obscure. I would only be in favour of removing weak with a proper patch like in vanilla equalizing the hook strength for everyone.

If removing weak is not politically acceptable (community) or technically impossible (maps, ranks etc.), I say we just make a prettier UI for it.

**Comment by heinrich5991** [comment]
> I think this adds even more hacky complexity to something already insanely obscure. I would only be in favour of removing weak with a proper patch like in vanilla equalizing the hook strength for everyone.

I think that the idea that the moment your hook attaches, you get the strongest hook, is pretty simple and amazingly backwards-compatible.

**Comment by Learath2** [comment]
Simple as long as only one tee is hooking, managable with 2 tees hooking eachother, very tough to reason about anything past that. It makes every tick of interaction require extra context that we didn't require before.

It is pretty backwards compatible though, I'll give it that.

**Comment by heinrich5991** [comment]
> It makes every tick of interaction require extra context that we didn't require before.

A simpler idea I had in mind when saying "not necessarily this implementation" is that you get the strongest hook each time your hook attaches. I don't think it requires extra context. Thinking about it, it's not symmetric; there will be ties that need to be resolved (probably implicitly, not so nice).

**Comment by Learath2** [comment]
One interaction I'm having trouble reasoning about is the triple fly. I think with your idea, as soon as the middle tee hooks the bottom tee the top tee loses strong on the middle tee as he is now the strongest. So it would atleast make the feeling of 3fly different for people that rehook every other hammer.

**Comment by heinrich5991** [comment]
Okay, you're right about that, it needs more complicated analysis of who hooks whom, simply making the latest hooker the strongest does not work.

**Comment by Jupeyy** [comment]
Let's create an issue next time we discuss it

**Pull request closed without merging**
