### PR TITLE
Console command "color_from_rgb" (fixes #1581)

### LINKED ISSUE #1581: Support color names and RGB color input
> <fokkonaut> we should have presets that can be used in the whole client, like some enums. So you can use those for authed color, laser color, clan color and whatever color that can be customized

Maybe #AA00FF to select RGB colors have them auto-converted as well as something like browsers support: https://htmlcolorcodes.com/color-names/

### PR DESCRIPTION
**Pull request by def-**
Converts RGB colors to TW's HSL format

### CODE REVIEW

**Comment by fokkonaut** [comment]
maybe allow this converter also for the general commands, so on every command that can accept colorcodes you can just give a RGB Format color

**Comment by def-** [comment]
The problem is they are not commands, but variables. We'd have to introduce commands to set these variables. It all seems pretty hacky.

**Comment by fokkonaut** [comment]
I think thats okay?

**Comment by heinrich5991** [comment]
I think this deserves a more meaningful name. Maybe `fromrgb`?

**Comment by def-** [comment]
Done

**Comment by heinrich5991** [comment]
Thanks.

bors r+

**Pull request merged**
