### PR TITLE
0.7 Compatibility layer

### PR DESCRIPTION
**Pull request by Learath2**
This turned out much uglier then expected but I just don't have it in me to scrap this again.

This "mostly" works, what remains is:
- [ ] Map Conversions
- [x] Whispers
- [x] Serverinfo

### CODE REVIEW

**Comment by Learath2** [comment]
Except for the funny bug with gunshots creating spawn effects, I think this is good on the playability side. It'd be nice if a couple of you can give it a test while I finish up the serverinfo.

It'd also be nice to know how @fokkonaut and @ChillerDragon handled the teamcore in their 0.7 clients so we can have teams showing nicely on the scoreboard.

**Comment by def-** [comment]
I don't find the server on LAN in 0.7 and I can't connect to it on localhost at all. If I connect on my lan ip with 0.7 I just get these errors and get stuck at "Connecting to":

```
[2020-06-13 08:59:44][connection]: got token, replying, token=794e237d mytoken=85263c1
[2020-06-13 08:59:44][client]: connected, sending info
[2020-06-13 08:59:44][client]: dropped weird message 'invalid' (0), failed on '(type out of range)'
[2020-06-13 08:59:44][client]: dropped weird message '(out of range)' (-6), failed on '(type out of range)'
[2020-06-13 08:59:44][client]: loading map, map=Kobra 4 wanted sha256=fa7be107e956c90596b3a3ca444893f53d6694fac8399277f1f1940f298dc814 crc=ad9dbb62
[2020-06-13 08:59:44][datafile]: loading. filename='maps/Kobra 4.map'
[2020-06-13 08:59:44][datafile]: could not open 'maps/Kobra 4.map'
[2020-06-13 08:59:44][datafile]: loading. filename='downloadedmaps/Kobra 4_fa7be107e956c90596b3a3ca444893f53d6694fac8399277f1f1940f298dc814.map'
[2020-06-13 08:59:44][datafile]: allocsize=3488
[2020-06-13 08:59:44][datafile]: readsize=3008
[2020-06-13 08:59:44][datafile]: swaplen=3028
[2020-06-13 08:59:44][datafile]: item_size=2472
[2020-06-13 08:59:44][datafile]: loading done. datafile='downloadedmaps/Kobra 4_fa7be107e956c90596b3a3ca444893f53d6694fac8399277f1f1940f298dc814.map'
[2020-06-13 08:59:44][client]: loaded map 'downloadedmaps/Kobra 4_fa7be107e956c90596b3a3ca444893f53d6694fac8399277f1f1940f298dc814.map'
[2020-06-13 08:59:44][client/network]: loading done
[2020-06-13 08:59:44][datafile]: loading data index=13 size=116 uncompressed=6912
[2020-06-13 08:59:44][datafile]: loading data index=14 size=122 uncompressed=6912
[2020-06-13 08:59:44][datafile]: loading data index=16 size=1065 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=19 size=1656 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=20 size=1659 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=21 size=11688 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=22 size=991 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=24 size=5034 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=25 size=8899 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=26 size=3139 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=27 size=5811 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=28 size=2372 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=29 size=3721 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=30 size=1731 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=31 size=1686 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=32 size=991 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=34 size=991 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=36 size=991 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=38 size=991 uncompressed=1000000
[2020-06-13 08:59:44][datafile]: loading data index=1 size=11583 uncompressed=663984
[2020-06-13 08:59:44][datafile]: loading data index=3 size=28153 uncompressed=4194304
[2020-06-13 08:59:44][datafile]: loading data index=5 size=15071 uncompressed=867312
[2020-06-13 08:59:44][datafile]: loading data index=7 size=62983 uncompressed=4194304
[2020-06-13 08:59:44][datafile]: loading data index=9 size=7242 uncompressed=4194304
[2020-06-13 08:59:44][datafile]: loading data index=11 size=93572 uncompressed=5635200
[2020-06-13 08:59:44][chat]: -1: : *** DDraceNetwork Mod. Version: 0.6.4, 13.0.2
[2020-06-13 08:59:44][chat]: -1: : *** please visit DDNet.tw or say /info for more info
[2020-06-13 08:59:44][chat]: -1: : *** Welcome on my server!
[2020-06-13 08:59:44][client]: delta unpack failed!
[2020-06-13 08:59:44][client]: delta unpack failed!
[2020-06-13 08:59:44][client]: delta unpack failed!
[2020-06-13 08:59:45][client]: delta unpack failed!
[2020-06-13 08:59:45][client]: delta unpack failed!
[2020-06-13 08:59:45][client]: delta unpack failed!
[2020-06-13 08:59:45][client]: delta unpack failed!
[2020-06-13 08:59:45][client]: delta unpack failed!
[2020-06-13 08:59:46][client]: delta unpack failed!
[2020-06-13 08:59:46][client]: delta unpack failed!
[2020-06-13 08:59:46][client]: delta unpack failed!
[2020-06-13 08:59:46][client]: delta unpack failed!
[2020-06-13 08:59:46][client]: delta unpack failed!
[2020-06-13 08:59:47][client]: delta unpack failed!
[2020-06-13 08:59:47][client]: delta unpack failed!
[2020-06-13 08:59:47][client]: delta unpack failed!
[2020-06-13 08:59:47][client]: delta unpack failed!
[2020-06-13 08:59:47][client]: delta unpack failed!
[2020-06-13 08:59:48][client]: delta unpack failed!
[2020-06-13 08:59:48][client]: delta unpack failed!
[2020-06-13 08:59:48][client]: delta unpack failed!
[2020-06-13 08:59:48][client]: delta unpack failed!
[2020-06-13 08:59:48][client]: delta unpack failed!
[2020-06-13 08:59:49][client]: delta unpack failed!
[2020-06-13 08:59:49][client]: delta unpack failed!
[2020-06-13 08:59:49][client]: delta unpack failed!
[2020-06-13 08:59:49][client]: delta unpack failed!
[2020-06-13 08:59:49][client]: delta unpack failed!
[2020-06-13 08:59:50][client]: delta unpack failed!
[2020-06-13 08:59:50][client]: delta unpack failed!
[2020-06-13 08:59:50][client]: delta unpack failed!
[2020-06-13 08:59:50][client]: delta unpack failed!
[2020-06-13 08:59:50][client]: delta unpack failed!
[2020-06-13 08:59:51][client]: delta unpack failed!
[2020-06-13 08:59:51][client]: delta unpack failed!
[2020-06-13 08:59:51][client]: delta unpack failed!
```
Am I doing something wrong?

**Comment by ChillerDragon** [comment]
@Learath2

https://github.com/ddnet/ddnet7/commit/b8ded9031a7888854bce4a4d27fdb2a8ffee32f7
https://github.com/ddnet/ddnet7/commit/71f823fd4f9cd2f9273365aab55765db8ae8feb8

**Comment by Learath2** [comment]
@def- Serverinfo isn't there yet so it's normal that you don't see it in the browser, but the snap issue is odd. Can you check which type of netobj the client is failing to unpack? A `dbg_msg` in `snapshot.cpp` right before the `return -1;` should help

**Comment by edg-l** [comment]
To me this looks making the code really ugly, i can see it come, the time when 0.8 drops there, sevenup all over the code too.

**Comment by Learath2** [comment]
The problem is that teeworlds mods are impossible to maintain with vanilla codebase being so hostile. Try to code a mod that is mostly self contained and avoid touching the vanilla code and you'll instantly see the issues.

It'd be so nice if we could have a more mod friendly vanilla so we could just keep up with it without hours of work upgrading.

**Comment by def-** [comment]
Client hangs when I click on News. Doesn't happen on master, weird :D

**Comment by def-** [comment]
Cool, now it works!

**Comment by ChillerDragon** [comment]
@Learath2 yay it is working good job :tada: 

Be aware that the playerflags changed and currently using scoreboard freezes input.

**Comment by Learath2** [comment]
@def- ah we'll need to lighten the colors back up before sending to 0.7 because they don't clamp L like we do.

@ChillerDragon Yeah I'm generating a flag map

**Comment by def-** [comment]
Not sure if you saw my edit:

> Hammer doesn't show an effect and makes no sound in 0.7

**Comment by Learath2** [comment]
Hm, lighting it back up as usual seems to over lighten it, this will require some more debugging to figure out what makes the colors dark.

**Comment by Learath2** [comment]
I've fixed any issues I've found, need more people to test further.

**Comment by def-** [comment]
- Server is not shown as compatible, so I have to uncheck "Compatible version" in 0.7 client

- I don't see the server in 0.6 client in LAN browser anymore, also can't connect from 0.6 at all

- I tried to change map with sv_map Kobra 4, can't connect anymore from 0.7, have to reconnect manually

**Comment by Learath2** [comment]
@def- I can't reproduce your 0.6 issue. The map download does seem to get stuck, will fix.

**Comment by def-** [comment]
Tried on Linux x86-64, Release build, client from this PR as well.

Actually I can't see or connect to any servers with the client anymore.

**Comment by Learath2** [comment]
@def- As I said on discord. I don't have access to linux except for a headless VM, it'd be very helpful if you could debug this a little or maybe atleast bisect it so I know which commit to scrutinize.

**Comment by def-** [comment]
```
723c1ef43035af7a267e320562c38d02f654e888 is the first bad commit
commit 723c1ef43035af7a267e320562c38d02f654e888
Author: Learath <learath2@gmail.com>
Date:   Tue Jun 16 15:41:30 2020 +0300

    Serverinfo and Register support for 0.7
    
    Co-authored-by: Tim Schumacher <tim@timakro.de>
```

**Comment by def-** [comment]
Tees are brighter on 0.7 than in 0.6 now, but doesn't matter much I guess.

**Comment by Learath2** [comment]
I spent a couple hours trying to figure out why tees were brighter. Even
after adjusting the allowed range it still ended up looking wrong. I'd
really love to know if anyone figures it out.

**Pull request merged**
