### PR TITLE
Use CSaveTee for rescue (fixes #2241)

### LINKED ISSUE #2241: /rescue isn't saving ninja, number of jumps, jetpack, etc
We should probably use the SaveTee logic from /save instead of reimplementing all that.

### PR DESCRIPTION
**Pull request by def-**
Untested. Edit: Tested, seems to work.

### CODE REVIEW

**Comment by heinrich5991** [comment]
This needs to make sure we don't load certain variables.

Race time?
Practice mode enabled!
…

I welcome the effort to use `CSaveTee`.

**Comment by fokkonaut** [comment]
Does this still work on windows then?

**Comment by Learath2** [comment]
Sure, the saved tee never leaves the memory

**Comment by def-** [comment]
> Race time?

Does it really matter? They can't finish anyway. Done anyway

> Practice mode enabled!

Not required since it only enabled practice mode, never disables it when loading.

> EDIT: Hooked character.

Done

**Comment by heinrich5991** [comment]
bors r+

Thanks for implementing this idea. :)

**Pull request merged**
