### PR TITLE
Print sqlite statements

### PR DESCRIPTION
**Pull request by Zwelf**
This prints SQLite statements to the console. I tried to expand MySQL statements with the SQLite function as well, but this didn't work since it isn't valid SQLite syntax.

### CODE REVIEW

**Comment by Zwelf** [comment]
Uh, Ubuntu 16.04 doesn't have the minimum required version for `sqlite3_expanded_sql`. SQLite introduced it in [3.14](https://sqlite.org/changes.html#version_3_14), Ubuntu 16.04 packages [3.11](https://packages.ubuntu.com/xenial-updates/sqlite3).

**Comment by def-** [comment]
Interesting. On DDNet we have Debian 10 with sqlite3 `3.27.2 2019-02-25 16:06:06 bd49a8271d650fa89e446b42e513b595a717b9212c91dd384aab871fc1d0alt1` btw.

But should still not push too hard version requirements I guess. Hmm...

**Comment by heinrich5991** [comment]
You could link weakly to that function, and only using it when it is available.

**Comment by def-** [comment]
Windows build still fails?

**Comment by def-** [comment]
Could you use the scripts/fix_style.py script to fix the style? Otherwise +1

**Pull request merged**
