### PR TITLE
Store ranks as json on sql-failure & add tool to put them to a database

### PR DESCRIPTION
**Pull request by H-M-H**
This will store failed inserts in a file each line containing the json representation of a rank. 

Additionally there is a tool to restore them to a database; it will read the server- and especially the sql-config and use the same mechanism as the server to reach the db-serves and do the inserts.

### CODE REVIEW

**Comment by def-** [comment]
So, what solution should we choose for the C++11 problem?

**Comment by timakro** [comment]
I would like C++11 support, could you explain the problems or link a discussion if there already is one?

**Comment by H-M-H** [comment]
The only problem about C++11 is that some of our servers run on debian wheezy which does not ship a C++11 compliant gcc version :/ .

**Comment by heinrich5991** [comment]
Debian Wheezy compiles C++11 just fine, you need to pass the command line flag `-std=gnu++11` or `-std=c++11`.

**Comment by H-M-H** [comment]
As far as I know C++11 is not fully implemented as of gcc 4.7.2 which is the version wheezy ships, which is also why building failed back then when I tested this.

**Comment by heinrich5991** [comment]
Oh wow, this looks like a huge diff. So let's start with the high-level questions.

What problem does this pull request solve? How does the pull request solve the problem?

From the description, it seems that this should store ranks in a JSON file if the insertion into the database failed for some reason. From the diff, it looks like similar functionality was present before but using a different format (plain SQL `INSERT` statements). (What problems did the previous format have?)

Is it necessary to include a new JSON library?

**Comment by H-M-H** [comment]
This prevents losing ranks if no databaseserver is reachable. So it stores ranks and teamranks as json to write them to a database later.
The previous version that just writes raw sql does not take into account, that some additional logic needs to be applied for adding ranks and teamranks. Those stored ranks can not simply be written to the database but also points or teamrank times might need to be updated which requires some selects on the database.

It indeed is necessary to include a new json lib as the previously included one only supports parsing but not writing json.

**Comment by Learath2** [comment]
Should the server be the one doing the logic for teamranks and pointts?

**Comment by heinrich5991** [comment]
I dislike that this pull request rewrites all JSON-related code.

There seems to be a corresponding JSON-writer library to our current parser: https://github.com/udp/json-builder. It doesn't require C++11 and it also doesn't require the use of exceptions.

**Comment by H-M-H** [comment]
@Learath2 at least currently the server does some logic and this pull request adds a tool to read the stored ranks from json and apply the same logic. And I guess as long as the server updates the database directly it has to do some logic. Do you have another (preferably better :P) idea ?

@heinrich5991 I guess this means you would rather like to stick to the current set of language features and keep things rather C-ish ?

Btw. it seems all our servers support C++11 now.

**Comment by Learath2** [comment]
Well I probably had another daemon in the middle in mind, but that's pointless. I should stop commenting right after I wake up.

**Comment by H-M-H** [comment]
To be honest I also thought about something like that before. Write some daemon in a language that gives you an ORM like python with sqlalchemy to make interaction with sql less painful but in the end this probably just overcomplicates things. Thus I also came to the conclusion to bury this idea again.

**Comment by Learath2** [comment]
I don't really know how we store and propagate ranks currently but depending on the situation maybe a simple daemon that listens for simple FINISH messages might be a good idea.

I also think we should stay with C'ish code and use the json-builder that's C'ish :)

**Pull request closed without merging**
