### PR TITLE
Allow for the update of dll files

### PR DESCRIPTION
**Pull request by Learath2**
Some slight improvements to code and elimination of some bugs.

### CODE REVIEW

**Comment by heinrich5991** [comment]
@Learath2 Does removing "[DONT MERGE]" imply that you're done with this and this is ready for review?

**Comment by Learath2** [comment]
@heinrich5991 yep can be merged just needs to be tested on linux and maybe windows xp.

**Comment by Learath2** [comment]
Do test this on windows xp. There actually is a significant amount of people still using win xp :P

**Comment by def-** [comment]
Seems to work on Linux, no WinXP test done.

**Pull request merged**
