### PR TITLE
Don't reset chat on map change (fixes #2451)

### LINKED ISSUE #2451: Keep chat string across map changes
> [11:22 AM] Lady Saavik: sometimes I write long msg and someone changes map before I send it and my msg is gone! Is it possible to keep my unfinished msg after loading new map?!
> [11:23 AM] ᶰ°Konͧsti: agree, thats annoying xdd

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
This also doesn't reset the chat when manually disconnecting. Perhaps it could go into the `OnStateChange` callback?

**Comment by def-** [comment]
But OnStateChange also gets called when changing map, since you then reconnect.

**Comment by heinrich5991** [comment]
Cannot confirm this. The state only goes from `STATE_ONLINE` to `STATE_LOADING` to `STATE_ONLINE` again when changing maps. When going offline, the `OnStateChange` will be called with `STATE_OFFLINE`.

**Comment by def-** [comment]
I see, done.

**Comment by heinrich5991** [comment]
Thanks.

bors r+

**Pull request merged**
