### PR TITLE
Put hearts before friends names. Closes #606

### LINKED ISSUE #606: Different colored name for friend's name in the chat
Right now, there are red, blue, and purple colors for red team, blue team, and spectators. How about opposite color of the purple, so some hue of green for someone added into friend list?

### PR DESCRIPTION
**Pull request by Learath2**
This one uses U2665.
image
Alternative is U2764
image

### CODE REVIEW

**Comment by Ryozuki** [comment]
Could you add a option to disable it?

**Comment by Learath2** [comment]
I could also give it sliders like all other message kinds but I couldn't find where to fit said sliders.

**Comment by Learath2** [comment]
On second thought maybe I could move the laser color out, It doesn't actually belong to HUD afterall.

**Comment by Learath2** [comment]
Looks much better now \o/

**Comment by Learath2** [comment]
This is what it looks like

image
 
image

**Comment by heinrich5991** [comment]
Looks good to me. Thanks!

**Pull request merged**
