### PR TITLE
Join identical chat lines to prevent spam

### PR DESCRIPTION
**Pull request by edg-l**
image

May fix https://github.com/ddnet/ddnet/issues/259

Needs a bit more testing

### CODE REVIEW

**Comment by def-** [comment]
The counter is wrong. It should show (2) when you said the message twice, but shows (1) instead.

**Comment by def-** [comment]
and it looks like your name is "deen (1)" which is confusing. Maybe show the counter left of the name and in a half-transparent color.

**Comment by heinrich5991** [comment]
I know the original issue asked to do this. The proper fix would be to tell the client about its spec'ed state instead of fixing it up on the client side again.

**Comment by edg-l** [comment]
> I know the original issue asked to do this. The proper fix would be to tell the client about its spec'ed state instead of fixing it up on the client side again.

I didn't made this feature directly for that issue, but if it kinda fixes it it's nothing bad.

**Comment by edg-l** [comment]
image
This is how it looks now.

**Comment by def-** [comment]
bors r+
Thanks

**Pull request merged**
