### PR TITLE
Visual Chat Update

### PR DESCRIPTION
**Pull request by Banana090**
https://github.com/ddnet/ddnet/pull/3093

### CODE REVIEW

**Comment by Jupeyy** [comment]
just as a disclaimer:
@Banana090 asked me to finish this pr, he does not want to fix it anymore, bcs he is happy with it

**Comment by Jupeyy** [comment]
not finished yet, but maybe you'll already find some critical things

**Comment by Banana090** [comment]
Idk what you have done yet, but the bugs was found my version:
1. Holding tab is a disaster. Can break everything
2. I had a player on map with dummy. He wrote some messages as dummy, then we changed the map. The dummy's skin in the chat was shown, but not the right one. And each time chat updates it could change to something new.

**Comment by Jupeyy** [comment]
Yeah but I rewrote a lot. So dunno if these can happen, thanks anyway

**Comment by def-** [comment]
```
src/game/client/components/chat.cpp: In member function ‘virtual void CChat::OnRender()’:
src/game/client/components/chat.cpp:1191:8: warning: variable ‘LineWidth’ set but not used [-Wunused-but-set-variable]
 1191 |  float LineWidth = m_pClient->m_pScoreboard->Active() ? 90.0f : (200.0f - MESSAGE_PADDING - 8.0f);
      |        ^~~~~~~~~
```

**Comment by def-** [comment]
screenshot-20201017@110642
Long lines that nearly break over need the space of 2 lines, but are still shown on 1 line.

**Comment by def-** [comment]
There is now some spacing between the grey boxes, intentional?

There is not enough spacing on the right side of the box, looks too close to the last letter.

**Comment by def-** [comment]
scoreboard overlaps the chat, is that intentional?

**Comment by Jupeyy** [comment]
> There is now some spacing between the grey boxes, intentional?

I don't know what the best solution is, but the subpixels might add 1 pixel for multiline when rebuilding the text, but i'll make the text almost look like the screenshot in discord, just some changes

**Comment by def-** [comment]
> I don't know what the best solution is, but the subpixels might add 1 pixel for multiline when rebuilding the text, but i'll make the text almost look like the screenshot in discord, just some changes

But the original change by Banana090 did not have this issue

**Comment by Jupeyy** [comment]
> But the original change by Banana090 did not have this issue

it was just inside the box and u didnt notice, but i can do it like that if u want

**Comment by Jupeyy** [comment]
Guess its ready for testing, maybe i oversaw minor things.

I added 2 configs now, bcs the background wastes more space than the tee alone, and maybe ppl only want one of them.
I know the config discussion isnt finished, but i do know that not adding these config will result in discussions too xd

**Comment by def-** [comment]
cl_chat_tee 0 and then cl_chat_tee 1 later will not show skins in old lines. Intentional?

**Comment by def-** [comment]
> I added 2 configs now

Careful, if heinrich5991 sees this you'll be in trouble!

**Comment by Jupeyy** [comment]
> cl_chat_tee 0 and then cl_chat_tee 1 later will not show skins in old lines. Intentional?

i know, i can change this, but it then always track player skins, even if you dont need them, I thought "you probably dont change the config the whole time", but i can also change it

**Comment by def-** [comment]
That's fine, no need, as long as it's a conscious decision. Otherwise I noticed no problems so far, looks nice to me.

**Pull request merged**
