### PR TITLE
fix walking while paused or chatting (fixes #2036)

### LINKED ISSUE #2036: Possible to walk while paused or chatting
When holding a or d, then pressing chat or pause bind you will continue to walk.

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

**Comment by def-** [comment]
don't see this as wanted behaviour

**Comment by fokkonaut** [comment]
Well, in vanilla chat also stops walking. And pause should also stop it. It used to be like that, until the freeze inputs got fixed by m_SavedInput. The guy who implemented savedinput just forgot to reset it in ResetInput. In player.cpp in OnDirectInput, the input gets reset while chatting or while paused. Its surely wanted that the input gets reset.

**Comment by def-** [comment]
But I added this behaviour with intention as I and other players use it often while racing. Why would we want the same behaviour as vanilla?

**Comment by fokkonaut** [comment]
This can be achieved using f1 too. Thats what most people are used to I guess.

**Comment by fokkonaut** [comment]
Hook reset was commented out in ResetInput anyways. So this is really just about walking. Hook is kept.

**Comment by def-** [comment]
Wanted when hanging from somewhere and holding a/d.

**Pull request closed without merging**
