### PR TITLE
Add logging macros `log_{error,warn,info,debug,trace}`

### PR DESCRIPTION
**Pull request by heinrich5991**
This makes it almost as short to log as with `dbg_msg` (one to two more
characters), and much shorter than
`Console()->Print(IConsole::OUTPUT_LEVEL_{STANDARD,ADDINFO,DEBUG})`.

### CODE REVIEW

**Comment by heinrich5991** [comment]
Anyone want to bikeshed the macro names?

@def- I intend to leave `log_log` as a building block, I didn't intend it to be called directly (answering your comment at https://github.com/ddnet/ddnet/pull/5013#discussion_r861076862).

**Comment by heinrich5991** [comment]
Depends on #5013.

**Comment by heinrich5991** [comment]
> I think `ERROR, WARN, INFO, DEBUG, TRACE` are more common and they stand out more than `log_error` when reading. Plus all capital letters signify to the reader that these are macros.

Would probably also work, and was even the first idea for the names I came up with. ^^

In favor of the names as in this PR: It's not really important to know that they're macros and they blend in better with the old `dbg_msg` and other functions.

**Comment by heinrich5991** [comment]
> I think `ERROR, WARN, INFO, DEBUG, TRACE` are more common and they stand out more than `log_error` when reading. Plus all capital letters signify to the reader that these are macros.

Now I remember what I wanted to say: Do we want logging macros to stand out?

**Comment by edg-l** [comment]
I like the names from the title

**Pull request merged**
