### PR TITLE
Add APPEARANCE Settings page

### PR DESCRIPTION
**Pull request by C0D3D3V**
This could potentially also be added to 16.2

I also renamed  `cl_ddrace_hud` to `cl_showhud_ddrace` and ` cl_show_jumps_indicator` to `cl_showhud_jumps_indicator` I guess that fits better the pattern of the other configs.

grafik

grafik

grafik
grafik

### for the following 3 tabs there is now room to add a preview in future
grafik
grafik
grafik
grafik

I changed some of the texts ... so please look at them carefully 

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [x] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
> This could potentially also be added to 16.2

Why? Does it fix a new regression in 16.2? If we keep adding changes, the release date will keep being pushed backs. Only regression fixes and translations should go in.

**Comment by C0D3D3V** [comment]
Yes, I think that is not so important... does not have to be added to 16.2. Are actually only improvements in the quality of life.

**Comment by heinrich5991** [comment]
Please no more stuff for 16.2.

**Comment by C0D3D3V** [comment]
Ready for review now.

**Comment by def-** [comment]
tried it out, lgtm
bors r+

**Pull request merged**
