### PR TITLE
Work on compound binds

### LINKED ISSUE #1417: composed binds (ctrl+, shift+, alt+)
https://github.com/teeworlds/teeworlds/pull/1589/files
https://github.com/teeworlds/teeworlds/commit/c4fbceb02e118ae370e02152e776d8c94ec1abd4

### PR DESCRIPTION
**Pull request by Learath2**
Closes #1417

### CODE REVIEW

**Comment by def-** [comment]
Does it work the same way as in Vanilla or is this our own way?

**Comment by Learath2** [comment]
It works the same way as vanilla.

Even the code is mostly the same I just had to modify it a little to get it to work with the array of pointers we have and a couple more small things.

**Comment by def-** [comment]
Then good with me.

**Pull request merged**
