### PR TITLE
report extra player info to master http

### PR DESCRIPTION
**Pull request by edg-l**
couldn't test yet

this doesnt show extra info on the client server list yet, just makes the server report it

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
About the protocol: I think the added info should be at the top-level, not under extra. I agree about creating an extra layer of indirection for the skins, I think it should not include both 0.6 and 0.7 info but only one of them.

Internal API-wise, the first thing could e.g. either be achieved by letting the function return something like `,"afk":true}` or continue returning `{"afk":true"}` and letting the calling function replace the opening brace with a comma.

**Comment by edg-l** [comment]
I don't think it's THAT much bigger, even more, given text compresses really well.

And this is not just for some website, we can show the player skins on the player list from the server browser for example, and color it for the team they are. And show if they are afk, etc.

**Comment by Learath2** [comment]
Well let's be quantitative. At 2k players you will add ~64kb to servers.json, for a 64p server it'll add an extra 2kb per update to the traffic between the server and the master, just for 0.6 skin info. Is this whole feature a good idea?

If yes, maybe it'd be appropriate for this to be updated less often, maybe even employ delta compression? Honestly the entire serverinfo protocol could benefit from delta compression but that's another issue.

**Comment by heinrich5991** [comment]
> Well let's be quantitative. At 2k players you will add ~64kb to servers.json, for a 64p server it'll add an extra 2kb per update to the traffic between the server and the master, just for 0.6 skin info. Is this whole feature a good idea?

That assumes 32 byte extra info and that it's uncompressed. It's currently indeed uncompressed from game server and master, but not from master to client.
```py
>>> len('"skin":{"name":"","use_custom_color":true,"color_body":"123456","color_feet":"123456"}')
86
>>> len('"skin":{"name":"default"}')
25
```

**Comment by heinrich5991** [comment]
Compared to ~5 KiB on a currently 62/63 DDNet GER Multeasymap server.

<details>
`{"addresses":["tw-0.6+udp://176.9.114.238:8312","tw-0.7+udp://176.9.114.238:8312"],"location":"eu","info":{"max_clients":63,"max_players":63,"passworded":false,"game_type":"DDraceNetwork","name":"DDNet GER2 - Novice","map":{"name":"Multeasymap","sha256":"5c80d1f6832fb4440962f8d0c9eeb8f670cdb7edee97bec8a10618955d1b914c","size":445478},"version":"0.6.4, 16.4","clients":[{"name":"Lidor","clan":"","country":-1,"score":-484,"is_player":true},{"name":"69♚","clan":"ArmyOf1Man","country":376,"score":-623,"is_player":true},{"name":"Liraz ✡","clan":"EISBBBEIN","country":376,"score":-9999,"is_player":true},{"name":"Superfrog","clan":"","country":324,"score":-880,"is_player":true},{"name":"丂卄丨几ㄖ","clan":"","country":-1,"score":-9999,"is_player":true},{"name":"CONNECTED","clan":"","country":504,"score":-685,"is_player":true},{"name":"Baklava Pako","clan":"","country":792,"score":-9999,"is_player":true},{"name":"Kratos","clan":"ℛes|฿an","country":-1,"score":-447,"is_player":true},{"name":"Jessia","clan":"","country":792,"score":-591,"is_player":true},{"name":"SO HOT","clan":"","country":784,"score":-9999,"is_player":true},{"name":"Silk","clan":"","country":-1,"score":-534,"is_player":true},{"name":"ghostly","clan":"мσση","country":652,"score":-485,"is_player":true},{"name":"Lisa","clan":"","country":-1,"score":-480,"is_player":true},{"name":"Erways","clan":"","country":792,"score":-879,"is_player":true},{"name":"Pikivichi","clan":"","country":-1,"score":-9999,"is_player":true},{"name":"Glock Bitch","clan":"","country":-1,"score":-9999,"is_player":true},{"name":"LEdoudou","clan":"Ɖiɑɱoηd","country":-1,"score":-459,"is_player":true},{"name":"]GameReady[","clan":"Diego","country":-1,"score":-503,"is_player":true},{"name":"VisiøƞX","clan":"GAY","country":682,"score":-431,"is_player":true},{"name":"Happy GrandPa","clan":"","country":-1,"score":-484,"is_player":true},{"name":"SEPIA","clan":"","country":12,"score":-839,"is_player":true},{"name":"[D] Happy Grand","clan":"","country":-1,"score":-9030,"is_player":true},{"name":"NooBiPRO","clan":"","country":-1,"score":-513,"is_player":true},{"name":"Pikivichy","clan":"Lucιdιтy","country":250,"score":-641,"is_player":true},{"name":"NAVAR0G","clan":"Iɳϝιnity","country":-1,"score":-520,"is_player":true},{"name":"Itay","clan":"Hefe","country":376,"score":-340,"is_player":true},{"name":"aaleexx_","clan":"","country":-1,"score":-1152,"is_player":true},{"name":"Govard","clan":"PIN","country":-1,"score":-482,"is_player":true},{"name":"ABC","clan":"","country":-1,"score":-547,"is_player":true},{"name":"Charlieasy","clan":"LuciTànity","country":-1,"score":-431,"is_player":true},{"name":"pako","clan":"","country":-1,"score":-382,"is_player":true},{"name":"NoAH","clan":"Russian men","country":643,"score":-669,"is_player":true},{"name":"rod","clan":"","country":-1,"score":-554,"is_player":true},{"name":"waynextx 😈","clan":"EISBBBEIN","country":528,"score":-9999,"is_player":true},{"name":"el AL!3N","clan":"","country":724,"score":-681,"is_player":true},{"name":"nameless tee","clan":"","country":-1,"score":-364,"is_player":true},{"name":"pingu","clan":"","country":-1,"score":-542,"is_player":true},{"name":"Leech","clan":"","country":905,"score":-1200,"is_player":true},{"name":"Krown","clan":"EISBBBEIN","country":-1,"score":-9999,"is_player":true},{"name":"psycho","clan":"LT|Łegaȼy","country":-1,"score":-444,"is_player":true},{"name":"misiex","clan":"","country":-1,"score":-908,"is_player":true},{"name":"kirf","clan":"","country":-1,"score":-9999,"is_player":true},{"name":"Fluffy","clan":"","country":-1,"score":-794,"is_player":true},{"name":"♄αмẕα","clan":"Łegaȼy","country":788,"score":-760,"is_player":true},{"name":"Çürük Vhat","clan":"RA","country":24,"score":-9999,"is_player":true},{"name":"橘子屁","clan":"","country":-1,"score":-569,"is_player":true},{"name":"AM KANAL","clan":"S̷E̷K̷S","country":-1,"score":-1195,"is_player":true},{"name":"Spike_666","clan":"Lucιdιтy","country":-1,"score":-431,"is_player":true},{"name":"Choouini","clan":"Łegaȼy","country":276,"score":-427,"is_player":true},{"name":"(1)♄αмẕα","clan":"Łegaȼy","country":788,"score":-9999,"is_player":true},{"name":"VisiøƞZ","clan":"GAY","country":682,"score":-709,"is_player":true},{"name":"Tree","clan":"Łegaȼy","country":-1,"score":-629,"is_player":true},{"name":"iSlowiX","clan":"Lucιdιтy","country":756,"score":-410,"is_player":true},{"name":"Mikasa","clan":"Lucιdιтy","country":56,"score":-518,"is_player":true},{"name":"2kg Пиздя","clan":"","country":-1,"score":-9999,"is_player":true},{"name":"ohweyz","clan":"","country":-1,"score":-9999,"is_player":true},{"name":"emperiAAA","clan":"Hefe","country":-1,"score":-9999,"is_player":true},{"name":"entarible","clan":"","country":804,"score":-1073,"is_player":true},{"name":"Bambikiller","clan":"EISBBBEIN","country":8,"score":-386,"is_player":true},{"name":"gfdkjgbfdhvkjfd","clan":".ᴍᴇ'","country":499,"score":-400,"is_player":true},{"name":"shaGGY","clan":"","country":-1,"score":-1226,"is_player":true},{"name":"Mitsch","clan":"","country":-1,"score":-397,"is_player":true},{"name":"Vhen","clan":"EISBBBEIN","country":-1,"score":-9999,"is_player":true}]}}`
</details>

**Comment by edg-l** [comment]
now it only  shows either 0.6 or 0.7 info

**Comment by fokkonaut** [comment]
Shouldnt it at least contain an info which skin format to use? Otherwise it would always be trial and error parsing it.

**Comment by edg-l** [comment]
just check if part_names exists.

**Comment by heinrich5991** [comment]
Currently, the custom colors for 0.6 are emitted even if use_custom_colors is false.

As with the 0.6 skins, I think it'd be better if the fields for 0.7 had better names. Perhaps we could go with something similar like 0.7? E.g.
```
{
"body": {
  "name": "default",
  "color": 123,
},
"marking": {
  "name": "default",
},
"hands": …,
"feet": …,
"eyes": …,
}
```
or
```
{
"body": "default",
"body_color": 123,
"marking": "default",
"hands": …,
"feet": …,
"eyes": …,
}
```

What do you think?

**Comment by fokkonaut** [comment]
The 0.7 field names are good like that. They are also arrays on the clientside, so it makes sense to do that here aswell. Will also keep the file smaller, as you dont need num_parts*3 variables, instead just 3 arrays

**Comment by heinrich5991** [comment]
The 0.7 field names aren't really descriptive, we're also not putting the whole info into an array even though we could.

**Comment by edg-l** [comment]
ready for review again, havent tested this new version yet tho.

i now don't put colors if custom colors arent being used etc

**Review by heinrich5991 — COMMENTED** [review]
I think this looks good to me now, thanks for doing the custom color changes.

Remaining questions that I'd like to discuss:
- Is there a better representation than the HSL encoded into 4 bytes of an integer for colors?
- Is it reasonable to pack the DDNet team in a variable named "team"?

**Comment by edg-l** [comment]
>     * Is there a better representation than the HSL encoded into 4 bytes of an integer for colors?

I don't know much about colors, maybe @Learath2 should decide what's best here.

>     * Is it reasonable to pack the DDNet team in a variable named "team"?

Should it be renamed to ddnet_team?
Maybe `team` is fine since we know the gamemode this server is reporting is ddnet, so we can interpret the team as a ddnet team.

But I'm fine with either way.

**Comment by Learath2** [comment]
At the very least 4 byte HSL is the only exact color format we have with roundtrip guarantee

**Comment by heinrich5991** [comment]
> At the very least 4 byte HSL is the only exact color format we have with roundtrip guarantee

I was wondering if there was some more standard textual format to represent our HSL in, but there's probably not(?). The textual HSL stuff that I saw was using 360° for the hue component, not 1-256. Using our "HSL encoded in 8-bit groups of an integer" is bit weird, but if it's the best option we have, it's probably okay.

**Comment by edg-l** [comment]
fixed the comment

**Comment by heinrich5991** [comment]
Can you squash the commits? Good to go from my side, otherwise.

**Comment by edg-l** [comment]
done

**Pull request merged**
