### PR TITLE
Adapt move_sqlite.py script to _backup tables

### PR DESCRIPTION
**Pull request by def-**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Zwelf** [comment]
I would suggest to only move ranks/teamranks/saves older than 5 minutes (or a similar arbitrary value). To not move ranks still ongoing in DDNetServer (this would lead to duplicate ranks). Looks good otherwise.

**Comment by def-** [comment]
Duplicate ranks are automatically detected. I guess duplicate saves might happen if they are with two different pws.

**Comment by def-** [comment]
Done

**Review by Zwelf — APPROVED** [review]

**Comment by Zwelf** [comment]
Thanks

bors r+

**Pull request merged**
