### PR TITLE
Allow the antibot to get more insight into the network

### PR DESCRIPTION
**Pull request by heinrich5991**
E.g. allow it to see the messages the server sends.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
As this is a new antibot ABI, one has to be careful rolling it out to the servers. I'll try to do that once it gets merged.

**Comment by def-** [comment]
lgtm. @Learath2 any comments or can I submit?

**Comment by Learath2** [comment]
Just got home, let me give this a quick look over and I'll merge it

**Comment by Learath2** [comment]
LGTM, we'll deploy this tonight

bors r+

**Pull request merged**
