### PR TITLE
Get rid of unnecessary queue in CFetcher

### PR DESCRIPTION
**Pull request by Learath2**
Use a `CJob` instead. Also kept fetcher as a separate interface but it might also fit in `IEngine` along with `HostLookup`

Appears to be working on Linux x86_64. Please test it on another platform before merging.

### CODE REVIEW

**Comment by def-** [comment]
Did you test map downloads, info download and updating?

**Comment by Learath2** [comment]
Won't work because we need `GAME_RELEASE_VERSION` in fetcher which is in `game/version.h`, including which would break the compilation order.

**Comment by heinrich5991** [comment]
> Please test it on another platform before merging.

What should I do in order to test this?

**Comment by Learath2** [comment]
HTTP Map download, the info download and the updater. To test the updater
just change version in version.h

**Comment by heinrich5991** [comment]
Works for me (on Linux x86_64 as well).

**Comment by Learath2** [comment]
@eeeee unless you have a compelling reason and a half decent way to get rid of `CFetcher` I think I'll merge it like this.

**Comment by heinrich5991** [comment]
> a half decent way to get rid of `CFetcher`

What problem problem did you encounter?

**Comment by Learath2** [comment]
To get rid of `CFetcher` I'd need a `JOBFUNC Foo` that takes a `CFetchTask` and does the task. `Foo` would need to be static and would need access to private members of `CFetchTask` which means foo would either need to be in a friend class like it currently is or a member of `CFetchTask` which I dislike as I don't really like having `Do()/Execute()/Run()`.

Let's say I make that friend class `CEngine`. Because there is no declaration to `CEngine` I can't possibly have my function static nor can I have it above the definition of `CEngine` as then I'd be trying to dereference an incomplete type . I could possibly get the interfaces from the `Kernel` but that'd require `CFetchTask` itself be an `IInterface` which sounds stupid, or I could add the interfaces to `CFetchTask` as private members which also sounds stupid, why would a task have interface pointers.

What if all the members of `CFetchTask` is public? It could work, but there is no need for the user to access them. 

Could possibly have `CFetchTask` be a struct but I haven't investigated that possibility yet.

In any case I end up with one ugly `engine.cpp`.

**Comment by heinrich5991** [comment]
Works on Windows 7 as well.

**Comment by heinrich5991** [comment]
Shall I merge?

**Comment by heinrich5991** [comment]
Yes.

**Comment by heinrich5991** [comment]
Thanks.

**Pull request merged**
