### PR TITLE
Reset m_ServerCapabilities on Disconnect

### PR DESCRIPTION
**Pull request by def-**
Reported by builder17 that on Vanilla server timeout code can get sent

### CODE REVIEW

**Comment by Jupeyy** [comment]
Dunno how hard it is to reproduce, but makes sense.
bors r+

**Comment by heinrich5991** [comment]
I don't see a code path that can lead to this.

On `NETMSG_MAP_CHANGE`, `m_ServerCapabilities` gets initialized if it hasn't been initialized already.

**Comment by def-** [comment]
Hm, indeed the map change gets sent on initial connection. Not sure how this could have happened then.

**Comment by Jupeyy** [comment]
maybe some overflow somewhere, since we also have a problem with map download (atleast under windows), i also checked, and on kog the HTTP map download isnt triggered

**Comment by heinrich5991** [comment]
> on kog the HTTP map download isnt triggered

It's because kog doesn't send map SHA256s AFAIK.

**Comment by Jupeyy** [comment]
yeah sry, i wasnt clear what i mean. the map was deleted somehow, even tho HTTP is not trigged(so not a similar bug like we had before)

**Pull request merged**
