### PR TITLE
Enable rpath on Linux for shipping SDL2 shared lib

### PR DESCRIPTION
**Pull request by def-**
I guess we should have a way to say when we want to build against the
static sdl2? Or we just ship SDL2 for the ddnet.tw releases as well. I'd
be fine with the latter, but it adds a few MB probably.

### CODE REVIEW

**Comment by heinrich5991** [comment]
I think I'd prefer doing the shared lib approach. That decouples the versions, makes it easier to e.g. update SDL but not the DDNet or vice versa.

**Comment by def-** [comment]
But this means we should also ship the SDL2 shared lib for our regular linux releases to stay consistent with the steam ones?

**Comment by def-** [comment]
And also, all other linux libraries we linked in statically.

**Comment by def-** [comment]
We are also missing support to auto-update .so files

**Comment by def-** [comment]
@Learath2 your opinion?

**Comment by heinrich5991** [comment]
Linking it dynamically would mean that we can ship it for Steam and keep it out for non-Steam. On non-Steam we'd use the system library and on Steam we'd use the bundled one. Then we don't need support for `.so` in the auto updater (do they need special support?).

**Comment by Learath2** [comment]
`.so` shouldn't need special support as linux doesn't handle opened files any differently. However, I don't think we should ship the SDL to everyone, we can just ship it to steam.

**Comment by Learath2** [comment]
You could just build both with the rpath and ld should take care of the case where the library isn't bundled.

**Comment by def-** [comment]
Done.

**Comment by heinrich5991** [comment]
LGTM.

bors r+

**Pull request merged**
