### PR TITLE
removed unused comment

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Thanks :)

**Comment by Henningstone** [comment]
I think this 'comment' was used as a seperator between voting related stuff (below it) and whatever stuff above. So it was not at all unused, it even served a higher purpose than any "real" comment could ever dream of!

**Comment by ChillerDragon** [comment]
xd i also was thinking of it but i was too stupid to find the sense ._.
rip me

**Comment by Henningstone** [comment]
rip the poor poor comment rather

**Pull request merged**
