### PR TITLE
Fix team rejoin logic for sv_team 3

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by def-** [comment]
Finally found the source of the problem, should be good to go.

**Comment by fokkonaut** [comment]
NewTeam has to be 0, because 64 tees on a solo map require teams 0 to 63, so each tee has its own team

**Comment by fokkonaut** [comment]
NewTeam has to be 0, on a solo server with 64 tees team 0 is needed, because every tee needs its own team (0-63)

**Comment by def-** [comment]
See line 592, team 0 is used if no other team is available.

**Comment by Learath2** [comment]
"SERIOUSLY" :) LGTM

bors r+

**Pull request merged**
