### PR TITLE
Menu auto font size

### PR DESCRIPTION
**Pull request by Jupeyy**
Can defs still be improved.
Ignored for text input

Before:
screenshot_2022-03-05_09-54-08

After:
screenshot_2022-03-05_10-12-40

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Mhh i guess a bit tollerance might be needed, currently it seems like no text is fitting into the current UI

**Comment by Jupeyy** [comment]
updated the screenshot

**Comment by C0D3D3V** [comment]
I would not put two components in one line, so that there is enough space for each components. 
This has already been partially addressed in https://github.com/ddnet/ddnet/pull/4787.

For example, due to the too short naming, I don't understand at all what the slider for "Alpha" and "Größe" is for. I would prefer to have just a label or another component in one line, so that the description can be short but detailed enough. Better to have a completely new additional settings page than confusing too short descriptions of the settings.

**Comment by Jupeyy** [comment]
> I would not put two components in one line, so that there is enough space for each components. This has already been partially addressed in #4787.
> 

this pr isnt in contrast to what you want (and the other pr)
This fixes a general problem. Many languages dont fit into the space..

See the Button "Zurücks." (Reset) also doesnt fit

**Comment by C0D3D3V** [comment]
Just like "Standardlänge" and "Wiederholungen aktivieren" :D  No idea what that means in the recordings section.
If both were in a separate line, you could perhaps add one more word that might explain it.

**Comment by C0D3D3V** [comment]
Yes I mean that as a supplement. Because different languages have different long words. Changing the font size is a very good step in the right direction and I think top, but if each component had its own line, then you would have much more space in the different languages.

**Comment by def-** [comment]
Much better I think. Probably not realistic to get all the languages to fit. Any other opinions on this?

**Comment by C0D3D3V** [comment]
I like it very much.

**Comment by Jupeyy** [comment]
rebased

**Pull request merged**
