### PR TITLE
Remove fetch-depth from CodeQL

### PR DESCRIPTION
**Pull request by Jupeyy**
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Seems to fail/deadlocking at the linking phase

**Comment by Jupeyy** [comment]
https://github.com/ddnet/ddnet/pull/4087/checks?check_run_id=3338406085

**Comment by Jupeyy** [comment]
without `--paralell` 2 times success yet

**Comment by Jupeyy** [comment]
ninja also works,
But the Code scanning results just cancel with 1 analysis not found,
maybe we should just disable CodeQL, it doesn't seem todo alot for cpp anyway,
clang-tidy seems more useful

**Comment by edg-l** [comment]
bors try

**Comment by Jupeyy** [comment]
bors r- 
wait i merged te commits

**Comment by Jupeyy** [comment]
bors try

**Pull request merged**
