### PR TITLE
Add option to zoom ingame cursor

### LINKED ISSUE #3421: play with zoom out
when we use zoom out become hard catch anything by hook because the mouse pointer become useless being very far and big

so my suggest

with every (zoom out) reduce where place the pointer can move  and minimize the size

by hussainx3

zoom out

### PR DESCRIPTION
**Pull request by fokkonaut**
Closes #3421 

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I'm not sure I like it. Any other opinions?

**Comment by fokkonaut** [comment]
Its optional and I also thought about adding it when I ported zoom to my client, because I had this behaviour without noticing at first.

**Comment by heinrich5991** [comment]
"It's optional" is not an argument for a new feature.

**Comment by Learath2** [comment]
What does it mean to "zoom cursor"? Can you show a screenshot?

**Comment by heinrich5991** [comment]
I'm against this change, since no one else has chimed in, I'm going to close this PR. Still thanks for trying to close issue. :)

**Comment by fokkonaut** [comment]
Sad... I really liked it too, whats the problem with it?

**Pull request closed without merging**
