### PR TITLE
Add `install`, `package` and `package_source` targets to CMake

### PR DESCRIPTION
**Pull request by heinrich5991**
On Linux, `install` installs DDNet into the normal file system (root
rights required).

`package` tries to create an archive similar to today's release archives
and `package_source` tries to create a source archive similar to today's
source archives.

### CODE REVIEW

**Comment by Learath2** [comment]
We could get this working on CIs by updating cmake and caching it in our scripts but the question is do we want this?

**Comment by def-** [comment]
Do we really need the new cmake feature?

**Comment by def-** [comment]
Or what about disabling these commands for old cmake versions?

**Comment by def-** [comment]
I guess I'll keep using bam for releases in the foreseeable future.

**Comment by def-** [comment]
Hm, how to make a release using this? `make package` has weird output

**Comment by def-** [comment]
But the tar is empty.

**Comment by heinrich5991** [comment]
Mhh.... CMake version? In the meantime, try `make package_default`.

**Comment by def-** [comment]
3.4.3

**Comment by def-** [comment]
package_default does something

**Pull request merged**
