### PR TITLE
Use map download url from info2.ddnet.tw (fixes #3546)

### LINKED ISSUE #3546: Let gameserver tell client which http server to use for http map download?
Then we could make the CHN servers download maps from chn1.ddnet.tw instead of maps.ddnet.tw (which is not in mainland china because we don't have cloudflare enterprise)

### PR DESCRIPTION
**Pull request by def-**
which info2.ddnet.tw provides using a geolite db to provide a better
server for players in China

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Ah damn, after implementing it I remembered that we use cloudflare for the info2.ddnet.tw too, so we can't use geoip...

**Comment by def-** [comment]
Ok, can use https://support.cloudflare.com/hc/en-us/articles/200168236-Configuring-Cloudflare-IP-Geolocation

**Comment by heinrich5991** [comment]
Unclear from the docs, but perhaps CF-Connecting-IP or X-Forwarded-For can also be used to get the actual IP address:

https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-CloudFlare-handle-HTTP-Request-headers-

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by def-** [comment]
Yes, but since Cloudflare already does the resolution to us, it's ok to use the country they tell us.

**Pull request merged**
