### PR TITLE
Add 2 changes to formatting-revs so git blame is usable

### PR DESCRIPTION
**Pull request by def-**
With .git/config containing:
```
[blame]
  ignoreRevsFile = formatting-revs.txt
```

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by C0D3D3V** [comment]
I just found out that you explain in the commit message of https://github.com/ddnet/ddnet/commit/ee8872fb752b36c94132e932dc66c2019ef09891 how to use formatting-revs.txt maybe we should add this somewhere that is read by new devs like me. xD I did always the trick above.

**Comment by heinrich5991** [comment]
Using `tig blame` can also help enormously, it lets you skip over such a revision with a single keypress (comma).

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by Chairn** [comment]
Yup, just learned something. I use tig blame as well.

**Pull request merged**
