### PR TITLE
add team0mode indicator

### LINKED ISSUE #8225: Add `/team0mode` indicator to HUD
Just like practice and lock is currently shown.

### PR DESCRIPTION
**Pull request by BlaiZephyr**
add a team0mode indicator. closes #8225 

~~we are currently missing a fitting indicator, mine is just a placeholder to test functionality. I kindly asked Insanity and she might create something for us.~~

image
image

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Review by def- — CHANGES_REQUESTED** [review]
There is a weird black line on the graphic. Is it dilated?

**Comment by BlaiZephyr** [comment]
> There is a weird black line on the graphic. Is it dilated?

oh sorry i forgot that in the initial PR - i basically just scribbled it down with paint while waiting for a fitting indicator, so i didnt really check if it properly fits nor did i dilate it. Insanity is on it at the moment :)

**Comment by BlaiZephyr** [comment]
@def- which one would you prefer? :)

hud3
hud4
hud1

**Review by def- — APPROVED** [review]
Looks good to me

**Comment by l-ouis** [comment]
Just a small nitpick - #8467 but nice otherwise!

**Pull request merged**
