### PR TITLE
server: Handle dnsbl and other non-critical stuff only on new ticks

### PR DESCRIPTION
**Pull request by def-**
Less risk of causing microlags then, I think once per second is often enough since it has to iterate through all players

This looked slightly suspicious in a `perf recording`
## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by heinrich5991** [comment]
What did you see in the perf recording?

This is how we do all our timers in the code base AFAIK. We check them for completion after every tick.

**Comment by def-** [comment]
Screenshot 2024-08-12 at 18 28 33
The CServer::Run method itself is pretty expensive.

**Comment by heinrich5991** [comment]
I guess we could put all the non-critical stuff into `if(NewTick)`. Then it'll happen at most every tick, but not for every network packet, as it is right now.

**Review by Robyt3 — APPROVED** [review]

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Pull request merged**
