### PR TITLE
Add FreeBSD instructions

### PR DESCRIPTION
**Pull request by def-**
https://www.freshports.org/games/DDNet

Thanks to @AMDmi3. Not sure if "pkg install DDNet" can also be used.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
I just noticed @AMDmi3 is also the maker of [Repology](https://repology.org/project/ddnet/versions) that we use in https://github.com/ddnet/ddnet#installation-from-repository Nice!

**Comment by AMDmi3** [comment]
> Not sure if "pkg install DDNet" can also be used.

It can, it's just that the package will be available in a few days.

> of Repology that we use in https://github.com/ddnet/ddnet#installation-from-repository

:+1:

**Comment by heinrich5991** [comment]
Which do you prefer, `pkg install DDNet` or `cd /usr/ports/games/DDNet && make install clean`? I'd lean towards the former because it's shorter.

**Comment by AMDmi3** [comment]
> Which do you prefer, `pkg install DDNet` or `cd /usr/ports/games/DDNet && make install clean`? I'd lean towards the former because it's shorter.

The former installs a binary package, the latter builds package from source. I'd pick the former - it's more like official way, and straightforward for all kinds of users. Users who prefer building from sources will most likely figure out there's also a port.

**Comment by heinrich5991** [comment]
bors r+

Thanks. :)

**Pull request merged**
