### PR TITLE
Fix /practice chat responses and a few others

### LINKED ISSUE #5087: No notification in team 0 if you try to use /practice
See https://youtu.be/gPTVj-s3pgc?t=149 
at 2:28

### PR DESCRIPTION
**Pull request by heinrich5991**
Fixes #5087.

### CODE REVIEW

**Comment by Learath2** [comment]
LGTM
bors r+

**Comment by C0D3D3V** [comment]
I know how to look this up but I thought you could give me a quick answer as to why the change made sense.

The PR you linked is the action you took to mitigate the problem, but not the reason why this should be good at all.

You have revised the logging mechanisms. And before, the messages were sent correctly. Without looking at exactly how you revised it, why didn't you add an argument whether it should be sent or not. And why are chat responses send from the consol logging api and not from the game server?

**Comment by heinrich5991** [comment]
> how come we change from such granular categories like "help" "join" "rank" all to "chatresp"?

I don't think these categories were used except for stdout anyway.

> You have revised the logging mechanisms.

Yes, now log messages from all threads can be seen not only in the local console.

> And before, the messages were sent correctly.

Where the messages ended up was pretty arbitrary. I think all of them went to stdout, but messages from other threads and chat commands only went to stdout but not rcon or local console.

> why didn't you add an argument whether it should be sent or not.

As I noted in the PR, I don't have a good solution for it. An extra argument seems to be about as good as making it "chatresp", except that old code still compiles, which might or might not be a good thing.

> And why are chat responses send from the consol logging api and not from the game server?

That's the same as before.

**Comment by heinrich5991** [comment]
Essentially, there were two logging APIs before, with varying ergonomics, now there's just one. That's the improvement the original PR did.

**Comment by heinrich5991** [comment]
> Mh thanks for the explanation, so if I understand this correctly you could also just use `m_pGameServer->SendChatTarget` directly everywhere where `pSelf->Console()->Print` is used to send chat responses, would make much more sense.

Some sort of proper solution would also be nice, since rcon commands have the same problem. In a sense, the console being responsible for it makes sense, the command doesn't care that it goes to chat, it might as well also go to rcon.

**Pull request merged**
