### PR TITLE
Arrow key support in editor

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by heinrich5991** [comment]
Crashes with a segfault when pressing up/down without having an image selected in the image view.

Otherwise looks like nice UX improvements. :)

**Comment by def-** [comment]
I can't reproduce the crash with no image selected.

**Comment by heinrich5991** [comment]
Start DDNet. Click on the pen to enter the editor. Press the right arrow key to go to the images tab. Click on "Add". Add "bg_cloud1". Press the down arrow key. Segfault.

```
#0  0x00005555557da354 in CEditor::RenderImages(CUIRect, CUIRect) (this=0x555555b0fcc0, ToolBox=..., View=...) at ../src/game/editor/editor.cpp:4043
#1  0x00005555557e5556 in CEditor::Render() (this=0x555555b0fcc0) at ../src/game/editor/editor.cpp:6041
#2  0x00005555557e7836 in CEditor::UpdateAndRender() (this=0x555555b0fcc0) at ../src/game/editor/editor.cpp:6499
#3  0x00005555556ad942 in CClient::Run() (this=0x7ffff6016010) at ../src/engine/client/client.cpp:3154
#4  0x00005555556b31a8 in main(int, char const**) (argc=0x1, argv=0x7fffffffe2d8) at ../src/engine/client/client.cpp:4170
```

I'm building with `-DDEV=ON`.

**Comment by def-** [comment]
Thanks, reproduced and fixed.

**Pull request merged**
