### PR TITLE
Remove some unused includes

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by Learath2** [comment]
@ChillerDragon `libtomcrypt` needs it for memcpy. I wonder why that compiles on circle at all.

**Comment by Learath2** [comment]
I don't get how these things keep compiling, only travis on mac seems to be checking this properly. (maybe a clang thing)

Anyway, updater needs `string.h` for `std::string`

**Comment by def-** [comment]
system headers on different platforms will have different dependencies themselves. Some might only forward-declare some symbols while others simply include the necessary headers.

**Pull request merged**
