### PR TITLE
Fix the `bors test` command, ignore `testing.tmp` on all CIs

### PR DESCRIPTION
**Pull request by heinrich5991**

### CODE REVIEW

**Comment by heinrich5991** [comment]
bors test

**Comment by heinrich5991** [comment]
Unlikely to be contentious, trying out the bors merge:

bors r+

**Comment by def-** [comment]
> error C2660: 'malloc': function does not take 2 arguments

**Comment by heinrich5991** [comment]
You probably ment #1107. Forgot to build the target `everything`, only tested server and client compilation locally.

**Pull request merged**
