### PR TITLE
added (console-)command usage

### LINKED ISSUE #387: Proper (for casuals) hints about commands
chat: /save
`Invalid arguments... Usage: save r` → `Invalid format, use: "/save [password]" or "/save [country code] [password]"`

console: ban
`Invalid arguments... Usage: ban s?ir` → `Invalid format, use: "ban [ip | id] [time] [reason]"`

and so on...

### PR DESCRIPTION
**Pull request by H-M-H**
would fix #387 
However, I am not exactly satisfied with this as servers can not send the usage to clients properly. At the moment servers just concat params and usage and sent it to client, which causes that old clients can not display the whole text as their buffer is too small.

### CODE REVIEW

**Comment by def-** [comment]
Now you have duplicate information, `?s` and `[file]`. Alternatively the parser could be changed to parse `[file]` but that might be too much work.

**Comment by heinrich5991** [comment]
This kinda duplicates work of #388.

**Comment by H-M-H** [comment]
Well it was already done when #388 appeared.

@def- like this we would loose typeinformation.

**Comment by Henningstone** [comment]
Also, #388 obviously won't work.

**Comment by Laxa** [comment]
I guess the best option would be to rework all the "Help" argument inside the Console()->Register.
Sadly, we can't always have a solution that will fit all cases. Client needs to be updated once in a while.

**Comment by Laxa** [comment]
Another idea : modify the parser to have a comment char like `?s#[File]`

**Comment by H-M-H** [comment]
@def- @Laxa I liked you idea the new format is now: parametertype + description in brackets.
Example: "i[some number] s[a string] ?i[optional number]"

**Comment by H-M-H** [comment]
Okay, no complaints so far, my locals tests were fine so I will merge this.

**Comment by heinrich5991** [comment]
If you're asking for complaints, this is what I thought when reading the code:
1) Why stuff the extra information into the format string for the parameters instead of making a second parameter that contains a space (or whatever)-separated list of parameter names?
2) This is as you said not really backward-compatible, but it wouldn't be hard with 1).

**Comment by H-M-H** [comment]
As you see I did it with a usage string first but as deen pointed out this is kinda redundant and adding this requires changes in networkcode. The problem is now that the server can send further information here: https://github.com/ddnet/ddnet/blob/e41b4f463d867d3fee63e4a70e2d42122a3a79d5/src/engine/server/server.cpp#L896-L900 but the new clients would not be able to process it as they do not know if the server already sends them: https://github.com/ddnet/ddnet/blob/e41b4f463d867d3fee63e4a70e2d42122a3a79d5/src/engine/client/client.cpp#L1614-L1621

**Pull request merged**
