### PR TITLE
Different distance between buttons in editor 

### PR DESCRIPTION
**Pull request by BannZay**

### CODE REVIEW

**Comment by def-** [comment]
Thanks.

**Comment by def-** [comment]
Why should this be more distant? 90° and CCW/CW are related, for related buttons distance 5 is used, not 10.

**Comment by BannZay** [comment]
Oh, my bad. I suppose so, becouse distance 10 used between X/X,Y/Y and  90, there is wrong

**Comment by BannZay** [comment]
5 less distance not really unites buttons by functionality, while aesthetically looks not so. What about make perfected distance or unite all them?

**Comment by def-** [comment]
To me distance 5 looks correct, putting them together would probably look ok as well.

**Pull request merged**
