### PR TITLE
cl_mouse_min_distance as requested by Makoyuri

### PR DESCRIPTION
**Pull request by def-**
also cl_dyncam_min_distance

### CODE REVIEW

**Comment by def-** [comment]
No compaints after 2 days means I can merge?

**Comment by Ryozuki** [comment]
What does this do? Does this disable the trick of setting mouse distance to 2 to get 45º angle?

**Comment by def-** [comment]
Nope, it prevents you from moving your mouse too close to the tee, so that it always stays at least a minimum distance away from the center

**Comment by Ryozuki** [comment]
Does so the mouse go throught like in a straight line? maybe it makes dragging a deep tee harder

**Comment by def-** [comment]
nope, moves smoothly around in a circle

**Comment by heinrich5991** [comment]
Except if it moves too fast within one frame.

LGTM.

bors r+

**Pull request merged**
