### PR TITLE
Revert "Let's not crash the client and server on dbg_assert"

### PR DESCRIPTION
**Pull request by heinrich5991**
This reverts commit a6e144e.

## Checklist

- [ ] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Why?
That i mean its called dbg assert for a reason, it also adds additional runtime.

**Comment by Learath2** [comment]
I support this, it's a bit of a performance hit but we already avoid it on the hot path. I would like to check with @def- though

**Comment by Jupeyy** [comment]
can we make this optional then? i dont want this in my client

**Comment by heinrich5991** [comment]
@Jupeyy Did you add performance-sensitive dbg_asserts in the past? We could disable those in release mode.

**Comment by def-** [comment]
So should we rename it from dbg_assert to something more representative of what's actually happening?

**Comment by Jupeyy** [comment]
> @Jupeyy Did you add performance-sensitive dbg_asserts in the past? We could disable those in release mode.

there are dbg_assert calls in the game loop if you mean that,
also it feels like that shouldnt used anymore then, bcs its not zero cost(while developping, and maybe create some function like, "check for correctness" or smth similar.

**Comment by heinrich5991** [comment]
> there are dbg_assert calls in the game loop if you mean that,
> also it feels like that shouldnt used anymore then, bcs its not zero cost(while developping, and maybe create some function like, "check for correctness" or smth similar.

Cost shouldn't be too high, it's an always correctly predicted branch (unless you do some complicated calculations in the assert).

**Comment by Learath2** [comment]
If you are extremely concerned maybe we can add a normal `assert` along with `dbg_assert` and we can only disable the dbg one on release builds

**Comment by Jupeyy** [comment]
> If you are extremely concerned maybe we can add a normal `assert` along with `dbg_assert` and we can only disable the dbg one on release builds

If most are for this change, I won't prevent it, my points are still the same:
additional runtime overhead
its meant for development

so imo this is bloating the software, and yes, i think a runtime_assert would fit better.

**Comment by heinrich5991** [comment]
Rebased.

**Comment by Jupeyy** [comment]
I still find this counter intuitive, don't you think a "runtime_assert" or smth makes more sense

**Comment by heinrich5991** [comment]
> I still find this counter intuitive, don't you think a "runtime_assert" or smth makes more sense

I agree that `dbg_assert` is counter-intuitive for an assert that is always active. I think that it's more useful not to change it though, because all of the code in Teeworlds/DDNet already uses this function (just like `dbg_msg` which also prints stuff in release, but I also definitely wouldn't want to rename it).

**Comment by def-** [comment]
Do we win much by crashing on a wrong assertion? I think I removed it in Release builds since there was a crash from a wrong assertion. I guess we have more than enough ways to crash the client and server with invalid maps etc, so this probably doesn't hurt much.

**Comment by Jupeyy** [comment]
Btw not directly related to this pr particually,
there are currently two
`dbg_assert(sha256_from_str(`
In the code, don't they currently get optimized out?
But looks like they are just used for console printing

**Comment by def-** [comment]
Yeah, function calls like that should not be in a dbg_assert if their results are used elsewhere.

**Comment by heinrich5991** [comment]
> Do we win much by crashing on a wrong assertion?

In my opinion, a crash is preferable to some weird other bug happening when assert conditions are violated but not checked.

The `dbg_assert`s are also in places where we interact with other libraries, by not having them turned on, I fear we'll only notice problems later.

**Comment by heinrich5991** [comment]
I still want this. Can we merge it and try it out?

**Pull request merged**
