### PR TITLE
Add gfx debug

### PR DESCRIPTION
**Pull request by Jupeyy**
If someone wants to try, you have to execute the client with a config that contains dbg_gfx 1
If opengl debug is supported it will show "Enabled OpenGL debug mode" in the console

### CODE REVIEW

**Comment by Learath2** [comment]
Since we set `glewExperimental`, maybe you should check the entrypoint instead, that would make it work on more drivers. Could also look for `GL_ARB_debug_output` to cover even more ground and finally maybe create it as a debug context.

**Comment by Jupeyy** [comment]
> Since we set `glewExperimental`, maybe you should check the entrypoint instead, that would make it work on more drivers. 

Why? glew sets something as given, as soon all required functions are loaded

**Comment by Learath2** [comment]
> > Since we set `glewExperimental`, maybe you should check the entrypoint instead, that would make it work on more drivers.
> 
> Why? glew sets something as given, as soon all required functions are loaded

I don't quite follow this sentence, my point was that the driver might not advertise the extension in it's extension string but still support the extension. Though how reliable this unadvertised support would be, I'm not sure.

**Comment by Jupeyy** [comment]
> Could also look for `GL_ARB_debug_output` to cover even more ground and finally maybe create it as a debug context.

Done

**Comment by Jupeyy** [comment]
> I don't quite follow this sentence, my point was that the driver might not advertise the extension in it's extension string but still support the extension. Though how reliable this unadvertised support would be, I'm not sure.

GLEW just loads the functions, it doesnt look for some extension strings

```
#ifdef GL_ARB_debug_output

static GLboolean _glewInit_GL_ARB_debug_output ()
{
  GLboolean r = GL_FALSE;

  r = ((glDebugMessageCallbackARB = (PFNGLDEBUGMESSAGECALLBACKARBPROC)glewGetProcAddress((const GLubyte*)"glDebugMessageCallbackARB")) == NULL) || r;
  r = ((glDebugMessageControlARB = (PFNGLDEBUGMESSAGECONTROLARBPROC)glewGetProcAddress((const GLubyte*)"glDebugMessageControlARB")) == NULL) || r;
  r = ((glDebugMessageInsertARB = (PFNGLDEBUGMESSAGEINSERTARBPROC)glewGetProcAddress((const GLubyte*)"glDebugMessageInsertARB")) == NULL) || r;
  r = ((glGetDebugMessageLogARB = (PFNGLGETDEBUGMESSAGELOGARBPROC)glewGetProcAddress((const GLubyte*)"glGetDebugMessageLogARB")) == NULL) || r;

  return r;
}

#endif /* GL_ARB_debug_output */
```

**Pull request merged**
