### PR TITLE
Don't load movement and pause state when rescuing

### LINKED ISSUE #2439: /r saves /pause state (including "held" keys trick), but shouldn't
I was running towards a cliff with freeze below and I accidentally pressed my /pause bind *before* letting go of my movement key (a, d, +left, +right) so of course the movement key was "held" down and I ran off the cliff into freeze. I unpaused and also pressed my movment key to *un-stick* it.... then typed /r, but when I did both the movement key was "held" down (again) *and* I was back in /pause!! Neither of these are desired.

Naturally I kept running off the cliff and falling into freeze over and over each time I pressed /r :-P

### PR DESCRIPTION
**Pull request by Zwelf**
Fixes #2439

### CODE REVIEW

**Comment by fokkonaut** [comment]
Better use ResetInput(), since also weapon input etc. is saved

**Comment by Zwelf** [comment]
`ResetInput()` only resets `m_Input`, not `m_SavedInput`. In `DDRaceTick` where the input is evaluated, `m_Input` gets overwritten with `m_SavedInput`, so just calling `ResetInput()` doesn't work here.

**Comment by heinrich5991** [comment]
bors r+

Thanks.

**Comment by fokkonaut** [comment]
@Zwelf ResetInput(); m_SavedInput = m_Input;

**Comment by Zwelf** [comment]
:+1: look cleaner

**Pull request merged**
