### PR TITLE
Further android build fixes

### LINKED ISSUE #4615: Android Build Error
When I tried building DDNet for android, using the command-
`scripts/android/cmake_android.sh all DDNet Release`
I got the error: 
`> Task :compileReleaseJavaWithJavac FAILED
/home/-/-/ddnet-master/build_android/src/main/java/tw/DDNet/NativeMain.java:3: error: package org.libsdl.app does not exist
import org.libsdl.app.SDLActivity;`

I followed the instructions at [https://github.com/ddnet/ddnet/tree/7e697963cf9f7657a22d74fdd0f85032f73baa2e/scripts/android](https://github.com/ddnet/ddnet/tree/7e697963cf9f7657a22d74fdd0f85032f73baa2e/scripts/android).
I also used the precompiled DDNet Libraries.

### PR DESCRIPTION
**Pull request by Jupeyy**
I just build the whole Android project now to check if there is other stuff:
- SDL also renamed a CMAKE flag
- apparently we updated icons, 512x512 was removed
- the newer compiler version warned about mismatched c function signature(SDL_main)
- since we moved all resize stuff to the main thread i made sure the main thread gets the updated window, which is important for android

I tested it on phone, so it works now and fixes #4615

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by def-** [comment]
Very cool! I'd like to try buliding an android version too. Will the readme contain all info I need?

bors r+

**Comment by Jupeyy** [comment]
yeah, should be all in, if something isnt clear just ask me and update the readme, i suck at writing stuff like that xD

**Comment by fokkonaut** [comment]
> Very cool! I'd like to try buliding an android version too. Will the readme contain all info I need?
> 
> bors r+

iirc controls are still missing. @Jupeyy could you readd the old controls for now?

**Comment by Jupeyy** [comment]
> > Very cool! I'd like to try buliding an android version too. Will the readme contain all info I need?
> > bors r+
> 
> iirc controls are still missing. @Jupeyy could you readd the old controls for now?

i dont actually care about android, but bcs alot of ppl were asking for it, I added the SDL build instructions, so that doesnt block it

**Comment by fokkonaut** [comment]
I know that you dont care about it that much, but I told most of these persons to ask at DDNet directly. And if I understood @def- correctly, he also wants to support it again. So it would just need the controls again which you did not add again in your initial commit, and I am asking you because I think you are the most experienced person in this area.

**Pull request merged**
