### PR TITLE
Add optional argument to movement commands

### PR DESCRIPTION
**Pull request by furo321**
Add the ability to move X amount of tiles with `left`, `right`, `up`, `down` commands. Suggested by Cellegen.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Robyt3** [comment]
It's generally best to split independent features like this into separate PRs, so we can discuss them separately.

I don't see a good reason why you would want to navigate multiple pages in the console at the same time. And you could also do for example `console_page_down; console_page_down` if you want to navigate two pages, so I don't think this is useful. Scrolling in the console should be reworked entirely anyway.

**Comment by furo321** [comment]
Yeah, I guess it doesn't really make that much sense for the console_page commands. I have removed them now.

**Comment by Robyt3** [comment]
Looks good. Can you also update the PR title and description?

**Review by Robyt3 — APPROVED** [review]
Thanks.

**Pull request merged**
