### PR TITLE
Make teehistorian easier to reproduce

### PR DESCRIPTION
**Pull request by Zwelf**
I've tested it ingame, but still have to make sure, that the ordering of the teehistorian messages are right. I would be really happy if we could land this before changing team joining logic (#4006 or /practice logic, but there isn't a pr for this yet), but I would like to make sure that the change is correct.

## Checklist

- [x] Tested the change ingame
- [ ] Tested in combination with possibly related configuration options
- [x] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Can i ask how this conflicts with #4006 ?
The other pr still gives you a "normal" team, its really just a console wrapper to make it easier to join an empty team

**Comment by heinrich5991** [comment]
@Zwelf What's the status of this? Can it be merged?

**Comment by Zwelf** [comment]
Hi, I think I have one thing:

* record practice and team at the begin of the tick, because chat messages get evaluated before the tick (but have to check that again)

I'll try to make it mergeable soon

**Comment by Zwelf** [comment]
If the checks pass this is good to go from my side :tada:. I've looked at the teehistorian output and it looks very reasonable to me.

**Review by heinrich5991 — CHANGES_REQUESTED** [review]
What's the design of these messages wrt. players leaving and teams getting disbanded?

Currently it records changing team to 0 when the next player joins, I think. Maybe it would be best to assume new players start in team 0?

Should we maybe add a message for teams getting disbanded (and thus reset)? I could do this point since it's a new feature.

**Comment by Zwelf** [comment]
> Currently it records changing team to 0 when the next player joins, I think. Maybe it would be best to assume new players start in team 0?

Correct. Could set the team to 0 on for new players either when recording the JOIN or DROP message? Didn't test with solo maps at all yet, there the players start in the team with the player_id, so it would be interesting when these messages are recorded there.

**Comment by Zwelf** [comment]
^ Tested on solo map as well now.

> Should we maybe add a message for teams getting disbanded (and thus reset)? I could do this point since it's a new feature.

Yeah I think a separate pull request would be nice there.

**Review by heinrich5991 — APPROVED** [review]
bors r+

Thanks.

**Comment by heinrich5991** [comment]
bors retry

**Pull request merged**
