### PR TITLE
Remove "Show only supported" switch from graphics tab

### PR DESCRIPTION
**Pull request by ardadem**
gfx_display_all_modes can be used instead

## Checklist

- [X] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by Jupeyy** [comment]
Should we also rename m_GfxDisplayAllModes to m_GfxDisplayAllVideoModes, so the config gets resetted?

**Comment by def-** [comment]
I don't like it. I use this all the time when playing in windowed mode to get a smaller window. Maybe only remove the ones larger than your screen size or something like that?

**Comment by Jupeyy** [comment]
You can still access it over f1. It's useless for 99.9% of all users

**Comment by Jupeyy** [comment]
Also resize now works on all os we support. We could default that on and if it didn't work on xmaund you could make a bug report

**Comment by Jupeyy** [comment]
tested xmonad now. i did gfx_resizable 1
restart
and did this:

https://user-images.githubusercontent.com/6654924/119125849-907a5700-ba32-11eb-9589-98eac9387709.mp4

Looks good enough as "resize", what exactly do you expect? :D

**Comment by def-** [comment]
I'm probably the only one with my use case, so ok.

bors r+

**Pull request merged**
