### PR TITLE
Don't register to ipv6 when sv_ipv4only is enabled. (fixes #7091)

### LINKED ISSUE #7091: sv_ipv4only 1 doesn't work
I'm not sure if I'm using it wrong but the server still attempts to register IPV6.

### PR DESCRIPTION
**Pull request by furo321**
It makes no sense to try to register server to IPv6, when it's not enabled.

## Checklist

- [x] Tested the change ingame
- [ ] Provided screenshots if it is a visual change
- [ ] Tested in combination with possibly related configuration options
- [ ] Written a unit test (especially base/) or added coverage to integration test
- [ ] Considered possible null pointers and out of bounds array indexing
- [ ] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by sjrc6** [comment]
This fixes #7091?

**Comment by heinrich5991** [comment]
This should probably go into the `CRegister::OnConfigChange` function.

**Comment by furo321** [comment]
Yeah, that's better. Fixed!

**Review by heinrich5991 — APPROVED** [review]
Thanks!

**Pull request merged**
