### PR TITLE
Strip spaces in browser (server name)

### PR DESCRIPTION
**Pull request by ChillerDragon**
before:
image
after:
image

### CODE REVIEW

**Comment by heinrich5991** [comment]
This doesn't really fix the issue. Can anything? I don't know.

This will lead to people prefixing their server names with `! ! ! !`.

Proposal: For sorting, only use alphanumeric characters. I.e. create a string that strips all the non-alphanumeric characters and do sorting in the serverbrowser based on that. We'll get `AAA` servers, but I guess people will limit it because it looks bad if you do too much of it? I don't know.

**Comment by ChillerDragon** [comment]
@heinrich5991 this more about moving to 0.7ish code than solving an actual issue. And in the last year nobody in 0.7 came up with things like ``! ! !`` but good idea I might do that for my server :p

**Comment by Learath2** [comment]
Surprising. I wonder why no one came up with the !. In the extremely
competitive landscape that is the dozen people who play 0.7

**Comment by ChillerDragon** [comment]
This is only used in vanilla and 0.7 has more vanilla players than 0.6 @Learath2. But I think the browser filter now sorts by player count now so new players join full servers.

**Comment by Learath2** [comment]
Looks like it's fine now

bors r=heinrich5991

**Pull request merged**
