### PR TITLE
[WIP] Make key presses scalable; Add option for old key presses position

### PR DESCRIPTION
**Pull request by C0D3D3V**
This PR is the continuation of #4697

In the Discord, two players pointed out to me that due to the new position of the arrows, there are larger gaps between the tees and the player names (See https://discord.com/channels/252358080522747904/757720336274948198/945642195757707265). This PullRequest is intended to deal with this problem.

I have made 3 changes: 
1. I have made the arrows that are displayed for the key presses scalable. This can also be set in the menu or via the console (with `cl_show_direction_size`).
2. I added an option called `cl_show_direction_position`. This makes it possible to show the arrows of the key presses:
    -  between the tee and the nameplate. The nameplate is moved up by the size of the arrows
    -  at the old position - in the middle of the nameplate. 
    - under the nameplate, thus at the top of the tee
    - in the tee - side direction arrows on the side in the middle of the tee
4. In the new position I have moved the arrows down by 2 units, as the arrows have already a transparent frame.

The scaled arrows are centred around the middle and are separated by a spacer by 8 scaled units.

Opinions on the labelling in the menu and the descriptions of the configuration variables are also welcome. 

A few impressions:

<details> 
  <summary>The menu: </summary>

grafik2

The setting for the size disappears if the option is generally deactivated:

grafik

</details>

<details> 
  <summary>The console: </summary>

image1

image2

</details>

## Please vote which of these options you like

Respond with these reactions (you may vote for multiple favorites):

 - :tada: `cl_show_direction_position 0` between the tee and the nameplate 
 - :heart:  `cl_show_direction_position 1` at the old position - in the middle of the nameplate
 - :rocket:  `cl_show_direction_position 2` under the nameplate, thus at the top of the tee
 - :eyes: `cl_show_direction_position 3` in the tee - side direction arrows on the side in the middle of the tee 

All images are with `zoom 10` and `cl_nameplates_size 0`:

<details> 
  <summary>How it is in release  15.9.1: </summary>
  
00 current_release_show_direction_style

</details>

<details> 
  <summary> `cl_show_direction_position 0` between the tee and the nameplate </summary>
  
  **notice how the nameplates move upwards**
  
05 my_changes_old_new_show_direction_style

With 50% Scale:
06 my_changes_old_new_show_direction_style_50%

</details>

<details> 
  <summary> `cl_show_direction_position 1` at the old position - in the middle of the nameplate </summary>
  
01 my_changes_old_show_direction_style

With 50% Scale:
03 my_changes_old_show_direction_style_50%

</details>

<details> 
  <summary> `cl_show_direction_position 2` under the nameplate, thus at the top of the tee </summary>

02 my_changes_new_show_direction_style

 
With 50% Scale:

04 my_changes_new_show_direction_style_50%

</details>

<details> 
  <summary> `cl_show_direction_position 3` in the tee - side direction arrows on the side in the middle of the tee </summary>
  
 02 my_changes_new_show_direction_style

With 50% Scale:
04 my_changes_new_show_direction_style_50%

</details>

## Checklist

- [x] Tested the change ingame
- [x] Provided screenshots if it is a visual change
- [x] Tested in combination with possibly related configuration options
- [ ] Written a unit test if it works standalone, system.c especially
- [x] Considered possible null pointers and out of bounds array indexing
- [x] Changed no physics that affect existing maps
- [ ] Tested the change with [ASan+UBSan or valgrind's memcheck](https://github.com/ddnet/ddnet/#using-addresssanitizer--undefinedbehavioursanitizer-or-valgrinds-memcheck) (optional)

### CODE REVIEW

**Comment by WatermelonDriveway** [comment]
I guess I'll chime in because I was one of the people who complained.

I always have my nameplate size at the smallest possible option.  Apparently with a bigger nameplate, the arrows start to get hidden underneath the nameplate, which I never noticed.  I think most people play with smaller nameplate sizes.  This recent change with the positions is attempting to solve that issue.  I understand why you want to fix this.

The problem that we are having with the new nameplate position is basically just that it feels different.  We've gotten used to it looking/feeling a certain way and now it's bigger, takes up more space, and feels different.  This makes it distracting.  I personally feel like the nameplate should take up the least amount of space as possible, and by moving it upwards to make room for the arrows beneath it, it's taking up a ton more space.

Whenever I've seen somebody complain about this in the discord, the solution that you've given is "just turn off directions", which is not a solution.  People want to have the nameplates in the normal spot AND have direction arrows, like they've always had.

I personally feel like the best solution is to keep the nameplates in the same spot (where they have always been), and make the directions/arrows move upwards as you increase the nameplate size.  So if you have the smallest possible nameplate size, the arrows are above the nameplate (like they've always been).  If you have the largest possible nameplate size, the arrows then move upwards, so that they still stay just above the nameplate.  From what I understand this is a bit harder to code, but It seems like the best solution to me.  As it is now, turning directions on moves the nameplate up.  It makes way more sense for the nameplate to stay in the same position, regardless of the directions setting.

Also, if you're going to decide on a permanent solution that involves moving the nameplate at all, please just include a setting for the old functionality.

- tela

**Comment by C0D3D3V** [comment]
If you make the arrows to the old position. And move them upwards when you enlarge the nameplate (e.g. to the default size of 50%). Then they are no longer in the old position. That would annoy people again. Furthermore you would push the arrows into the clan name. or whatever other nameplate options you have, e.g. strong weak indicator.

You could also just make the arrows fixed to the old position without any moving or scaling and display them above the player name so that the player name does not cover the arrows, but the arrows cover the player name. How would you like that?

**Comment by heinrich5991** [comment]
What's the status of this? Do you want to make a vote on the Discord?

**Comment by C0D3D3V** [comment]
since no one else has complained and in the meantime the new position of the arrows is already in 16.0.1 - 16.0.3  (so the position I marked here as cl_show_direction_position 0), we could also close the PR for now. Maybe someone else wants to look at it again in the future. But it seems that the new position was well received by most. cl_show_direction is also on by default, which means every new player sees the arrows. and no one else has complained xD

**Pull request closed without merging**
