### PR TITLE
Need to send info when updating skin in text field

### PR DESCRIPTION
**Pull request by def-**
As reported by abcqwerty on Discord

### CODE REVIEW

**Comment by Jupeyy** [comment]
thanks
bors r+

**Comment by def-** [comment]
The check style error message is weird, it just says "This check failed", never seen that before. Locally it was green.

**Comment by heinrich5991** [comment]
This looks wrong. It seems to me that it is sending the change the moment the user types a single letter. Should be done after defocussing.

**Comment by Jupeyy** [comment]
oh sry, rerun the jobs now, thought its just an internal error

**Comment by def-** [comment]
> This looks wrong. It seems to me that it is sending the change the moment the user types a single letter. Should be done after defocussing.

m_NeedSendinfo is only used in CMenus::SetActive when the menu is closed.

**Comment by Jupeyy** [comment]
When you are ok with the behaviour, just merge @heinrich5991

**Comment by heinrich5991** [comment]
Sorry, to have intervened, you judgement was right. @Jupeyy 

bors r+

Thanks.

**Comment by def-** [comment]
No problem. Better to review too strictly and I author has to explain than the opposite.

**Comment by Jupeyy** [comment]
See @heinrich5991,
you are even right, when meant something different. I directly thought about this pr, when i noticed that, the typing has a major problem, it spams download request every time the skin name input is changed, because m_pSkins->Find is called.

@def- ^

**Comment by def-** [comment]
I know, I noticed that and don't find it too bad. What would the alternative be? It's just 1 request per letter, right?

**Comment by Jupeyy** [comment]
the alternative is passing a bool to find, which disabled downloads, or a local state variable.
Well idc, but 10 invalid skins request is also not that less

**Pull request merged**
