### PR TITLE
added sv_deepfly (default 1) to disable deepfly

### PR DESCRIPTION
**Pull request by timgame**
sv_deepfly - Allow fire non auto weapons when deep

### CODE REVIEW

**Comment by heinrich5991** [comment]
I'd be against this. More fragmentation of maps.

**Comment by cinaera** [comment]
embrace the "features" \o/

**Comment by timgame** [comment]
In my opinion the best would be to make this default and only allow it for deepfly maps.

**Comment by Soreu** [comment]
For what creating next command nobody will know about, if you can simply use switch layer?

---

I'd like to remind you that this feature exists since the dummies were created (even though it wasn't known back then), and can be used even by two normal players if they have good enough timing, so there is simply no way at all to figure out who used it on which map and if at all.

With that said, I bet it's easy to see that it's way too late for suddenly calling it a bug, right?
So by "We could remove all better ranks" you basically mean removing all ranks ever made since otherwise you cannot be in any way fair as long as you can't determine which ranks were cheated from 2014-04-30 to now...

**Comment by timgame** [comment]
The most people don't like this for reasons.

**Pull request closed without merging**
